### ISSUE TITLE
Strange loading of pages of served Gitbook

### ISSUE THREAD

**Issue by patrickrand** [GitbookIO/gitbook#1000]
When clicking on links in our Gitbook, there is a split second re-rendering of the page we are trying to access. For a brief instance you see that page's content as plain-text (more or less). We are using the 2.2.0 version of Gitbook, and did not experience this issue when using version 0.5.6 . This occurs both when using `gitbook serve` as well as when we put the compiled book behind an Apache server. This issue only seems to occur about 65%, and only when trying to navigate to a different page.

**Comment by AaronO** [comment]
@patrickrand This was fixed in `gitbook`@`2.3.0` (https://github.com/GitbookIO/gitbook/blob/master/CHANGES.md#230).

The latest version of `gitbook` is `2.5.2` you'll probably want to update to that.

Give that a try and let me know if it fixes the issue for you :)

**Comment by patrickrand** [comment]
Thanks! Everything seems to be working

**Comment by AaronO** [comment]
Perfect :) BTW if you use [GitBook.com](https://www.gitbook.com) you will always be up to date (we handle automatic builds and hosting, including custom domains).
