### ISSUE TITLE
Is There a Way to Enable SmartyPants for the Generated Books

### ISSUE THREAD

**Issue by v0lkan** [GitbookIO/gitbook#1001]
First of all, thanks for the awesome work; it's requires a great deal of work to automate all the things.

I love writing, I have authored, been a technical editor of a few books. And the moment I swore that I will never write a book again (because it's damn hard work, and all the editorial / proofreading / publishing etc stuff gets excruciatingly boring over time); I've found gitbooks; and I'm glad I did :) --- Thank you.

Back to my question:

When I look into kramed (the markdown parser that gitbooks currently use) I see that it has an option to enable smartypants; however, I cannot find a way to directly enable this in the book configuration.

Expectation: Adding `"smartypants": true` into the book's configuration JSON will convert dumb typography to smart typograpy in the build process.

Am I missing anything?

**Comment by vipuldelwadia** [comment]
Is there any update on this? Did you figure it out @v0lkan?

**Comment by nathanwebb** [comment]
I've just published a plugin that runs the code through Typogr.

Install it by adding "typogr" to the plugins array in book.json. E.g.
```
{
  "plugins": [ "typogr" ]
}
```

Then run `gitbook install`

It works well for me, but hasn't been extensively tested yet. If you have any bug reports, please let me know at https://github.com/nathanwebb/gitbook-plugin-typogr/issues
