### ISSUE TITLE
[gitbook markdown] How to insert vertical line "|" into table?

### ISSUE THREAD

**Issue by zheeeng** [GitbookIO/gitbook#1004]
Plz check it in raw:

Operators	|Meaning			
:-------------:	|:----------------:	
&&			| and
\|\|			| or
!			| not

Grammar above  works fine in common parser, but not in gitbook markdown parser. Any solutions?

**Comment by TakahiRoyte** [comment]
type in `&#124;` for substitution

http://www.theasciicode.com.ar/ascii-printable-characters/vertical-bar-vbar-vertical-line-vertical-slash-ascii-code-124.html

**Comment by zheeeng** [comment]
@TakahiRoyte Thx for you suggestion. Indeed it's an efficient solution.
