### ISSUE TITLE
No images in PDF

### ISSUE THREAD

**Issue by RomMos** [GitbookIO/gitbook#1006]
Images are not shown in the PDF if the path that points to the image is created as a symbolic link using relative path (a full path symbolic link works fine).
Html version of the book shows them properly.
Example of the code:
    <pre><code>![alt text](../manual_content/Screenshots/Commander/CommanderWindows.png)</code></pre>

**Comment by AllieRays** [comment]
+ 1

**Comment by edno** [comment]
I've find a quick and dirty workaround:
`![alt text](http://localhost:4000/assets/header.jpg)`
then serve the book with `gitbook serve` before generating the PDF.
