### ISSUE TITLE
some error:static_url,{{ }}...

### ISSUE THREAD

**Issue by fratcn** [GitbookIO/gitbook#1008]
I come to some error when gitbook serve or build:
one of my md-file contain codes block like this
```
    <script src="{{static_url("js/jquery.min.js")}}"></script>
```
then here:
Template render error: (/home/x/app/Python/304.md) [Line 110, Column 27]
  Error: Unable to call `static_url`, which is undefined or falsey (In file '304.md')

another code block:
```
    {% set website = "<a href='http://www.itdiffer.com'>welcome to my website</a>" %}
```
while gitbook serve:
Template render error: (/home/x/app/Python/307.md) [Line 22, Column 28]
  unknown block tag: end (In file '307.md')

**Comment by SamyPesse** [comment]
It conflicts with the templating syntax used by GitBook: http://help.gitbook.com/format/templating.html

You can use `{% raw %}` and `{% endraw %}` to escape the syntax.

**Comment by fratcn** [comment]
and when gitbook serve,it does this: 
RangeError: Maximum call stack size exceeded

**Comment by SamyPesse** [comment]
I'm working on fixing this one, it's related to the search plugin, `lunr` fails indexing at some point, the current solution is to disable search, in your `book.json`:

```js
{
    "plugins": ["-search"]
}
```
