### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fratcn** [GitbookIO/gitbook#1009]
gitbook serve stoped

```
gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: loading book configuration....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: load plugin gitbook-plugin-livereload ....OK 
info: >> 5 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 

RangeError: Maximum call stack size exceeded
```

**Comment by SamyPesse** [comment]
It's related to the search plugin, lunr fails indexing at some point, the current solution is to disable search, in your book.json:

```js
{
    "plugins": ["-search"]
}
```

**Comment by junwucs** [comment]
I meet the same problem many times and hope anybody can fix it, thanks.

**Comment by mikaoras** [comment]
same problem and willing to have a fix,
search is really useful

**Comment by SamyPesse** [comment]
Since latest release, you can configure the maximum size of the index:

```json
{
    "pluginsConfig": {
       "search": {
              "maxIndexSize": 100000
       }
    }
}
```

If your book is hosted on **gitbook.com**, we are working on a better search solution with a server-side indexing.

**Comment by mikaoras** [comment]
Thanks :)

**Comment by starshiner** [comment]
where can I find the "book.json" file?

**Comment by starshiner** [comment]
@SamyPesse   I have a problem about this ,and I edit the file named 'book,json'  in .//test/books/config-json/book.json  and  .//test/books/structure/book.json, but it didn't work ,how can I do now?

**Comment by jarodmeng** [comment]
I started to have this problem today. I've tried -search and maxIndexSize, but they don't seem to work.

**Comment by nagim** [comment]
@SamyPesse Is it possible to set things so lunr does not stop indexing? The above setting has no effect.

**Comment by fcardinali** [comment]
This is not working at all i still get RangeError: Maximum Call stack size exceeded.

```
user@hostname/c/workspace/gitbook (master)
$ gitbook build user_guide/
info: 7 plugins are installed
info: 6 explicitly listed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 6 pages
info: found 5 asset files

```
RangeError: Maximum call stack size exceeded


i have made changes to my book.json as well


```
var pkg = require('./package.json');

module.exports = {
    // Documentation for GitBook is stored under "docs"
    root: './docs',
    title: 'GitBook Toolchain Documentation',

    // Enforce use of GitBook v3
    gitbook: '>=3.0.0-pre.0',

    // Use the "official" theme
    plugins: ['theme-official', 'sitemap'],

    {
    "plugins": ["-search"]
}

{
    "pluginsConfig": {
       "search": {
            "maxIndexSize": 100000
       }
    }
}

    variables: {
        version: pkg.version
    },

    pluginsConfig: {
        sitemap: {
            hostname: 'https://toolchain.gitbook.com'
        }
    }
};

```

**Comment by nagim** [comment]
It works for me now, just try to set the value to some ridiculously high number (like 1000000000 or something). My `search_index.json` fike is more than 11MB large...

**Comment by fcardinali** [comment]
i set the config like below: 

still not working
do i have to do git init again? or refresh something? or simply git build?


```
var pkg = require('./package.json');

module.exports = {
    // Documentation for GitBook is stored under "docs"
    root: './docs',
    title: 'GitBook Toolchain Documentation',

    // Enforce use of GitBook v3
    gitbook: '>=3.0.0-pre.0',

    // Use the "official" theme
    plugins: ['theme-official', 'sitemap'],

    {
    "plugins": ["-lunr"]
}

{
    "pluginsConfig": {
       "lunr": {
            "maxIndexSize": 1000000000
       }
    }
}

    variables: {
        version: pkg.version
    },

    pluginsConfig: {
        sitemap: {
            hostname: 'https://toolchain.gitbook.com'
        }
    }
};
```

**Comment by nagim** [comment]
You have two plugins declaration, remove the second, just need this:
`plugins: ["theme-official", "sitemap","-lunr"]`
On Jun 24, 2016 3:24 PM, "fcardinali" <notifications@github.com> wrote:

i set the config like below:

still not working
do i have to do git init again? or refresh something? or simply git build?

var pkg = require('./package.json');

module.exports = {
    // Documentation for GitBook is stored under "docs"
    root: './docs',
    title: 'GitBook Toolchain Documentation',

    // Enforce use of GitBook v3
    gitbook: '>=3.0.0-pre.0',

    // Use the "official" theme
    plugins: ['theme-official', 'sitemap'],

    {
    "plugins": ["-lunr"]
}

{
    "pluginsConfig": {
       "lunr": {
            "maxIndexSize": 1000000000
       }
    }
}

    variables: {
        version: pkg.version
    },

    pluginsConfig: {
        sitemap: {
            hostname: 'https://toolchain.gitbook.com'
        }
    }
};

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GitbookIO/gitbook/issues/1009#issuecomment-228344330>,
or mute the thread
<https://github.com/notifications/unsubscribe/APdFO7aW2si6QLMXbqPh4Vabidn_WR9zks5qO9qlgaJpZM4GgTFQ>
.

**Comment by fcardinali** [comment]
Yes i have figured out ... still not working... :( 

what do you think i am doing wrong?

```
var pkg = require('./package.json');

module.exports = {
    // Documentation for GitBook is stored under "docs"
    root: './docs',
    title: 'GitBook Toolchain Documentation',

    // Enforce use of GitBook v3
    gitbook: '>=3.0.0-pre.0',

    // Use the "official" theme
    plugins: ['theme-official', 'sitemap',"-lunr"],


    variables: {
        version: pkg.version
    },

    pluginsConfig: {
        sitemap: {
            hostname: 'https://toolchain.gitbook.com'
        },
         "lunr": {
            "maxIndexSize": 200000
        }
    }
};
```

**Comment by viogp** [comment]
Hi,

I'm still having the same problem when using `gitbook serve` locally (CLI version: 2.3.2
GitBook version: 3.2.3), even if it seems to be ok on the gitbook website. Here is my book.json:
```
{
    "plugins": ["mathjax-commonhtml",
		"bibtex-citations-and-references",
		"image-captions",
		"theme-official", "sitemap","-lunr","-search"
	       ],
    "pluginsConfig": {
	"image-captions": {
          "caption": "Image - _CAPTION_"
	},
	"mathjax-commonhtml": {
            "defaultScaling": false
        },
	"sitemap": {
            "hostname": "https:////msm.gitbook.io"
        },
       "lunr": {
            "maxIndexSize": 1000000000
       }
    }
}
```
