### ISSUE TITLE
API for list other's author books

### ISSUE THREAD

**Issue by pyhedgehog** [GitbookIO/gitbook#1021]
Shouldn't there be `/api/books/:username` or `/api/books/@:username`?

**Comment by SamyPesse** [comment]
We are adding an API: `https://api.gitbook.com/author/:username/book`.

It'll be available in a few hours.

**Comment by SamyPesse** [comment]
Done: https://api.gitbook.com/author/samypesse/books

**Comment by pyhedgehog** [comment]
:+1:
