### ISSUE TITLE
spacing around lists

### ISSUE THREAD

**Issue by DaveBackus** [GitbookIO/gitbook#1022]
It seems that I sometimes get a space after a list, sometimes not.  See for example

https://davebackus.gitbooks.io/test/content/installing-python.html

and look for "Step 2" or "Pro tip".  If I view this on GH (link below), there's a space before them.  In the GitBook, not.  

Any idea why?  And how I can get more regular spacing?  

https://github.com/DaveBackus/Data_Bootcamp_Book/blob/master/installing-python.md

**Comment by DaveBackus** [comment]
I'm reasonably confident this is new.  It doesn't show up in pdf's from a few weeks ago.

**Comment by SamyPesse** [comment]
It'll be in the next release (probably `2.6.0`).

**Comment by DaveBackus** [comment]
Perfect, thanks a lot.
