### ISSUE TITLE
How to switch a free book to a paid one

### ISSUE THREAD

**Issue by naturalprogrammer** [GitbookIO/gitbook#1024]
I've published a [book](https://www.gitbook.com/book/naturalprogrammer/spring-lemon-getting-started/details), which is free now. I want to make it paid ($ 9). As I gather, it's not possible through the settings. Could you please let me know what steps I could follow to make it paid?

**Comment by fizzvr** [comment]
Hidden this option?I see last week now can't see. :x:

**Comment by SamyPesse** [comment]
We are now longer offering this option directly in gitbook.com. Instead we are building integrations with existing sales platform to help you sale your private GitBook on it.

Our first integration is with [Gumroad](https://www.gumroad.com), it's open source and on [GitHub](https://github.com/GitbookIO/services-gumroad).

I'm currently writing some documentation on how to use this integration, but basically here is how it works:

1. Create a private book on gitbook.com
      2. Write your book
3. Signup on Gumroad
4. Enable the developer mode of your [Gumroad account](https://gumroad.com/settings)
5. Create a product with a webhook
6. Enter the webhook url: `https://gumroad-service.gitbook.com/webhook/:author/:book/:gitbookApiToken`
7. Share your Gunroad product!

Everytime someone buy your Gumroad product, it will create an access key on your private GitBook; the reader will be able to access the web version of your book.

Overall this integration is better for readers and authors:
- Gumroad offers an awesome buying experience
- Author can have a nice designed page that present their product
- Author will earn more royalties (Gumroad is taking 5%)

Let me know if you need help or have any feedback about this.

**Comment by naturalprogrammer** [comment]
Sounds great!

So, the users who would have bought the book will be able to access the web version from any PC and browser? For that, they will need to login into their GitBook account, Gumroad account, or both? It would be great you publish the documentation on it early, so that we can tell our readers to refer that for accessing the web version of the book.

**Comment by SamyPesse** [comment]
The reader does not require a Gumroad or GitBook account, it just need to enter his email.

Once the reader bought the book (using a credit card or PayPal), it will be redirected to a private url to access the content.
It'll also receive an email from Gunroad that contains this url.

I'll publish the documentation this week, this documentation is intended for authors. the user-experience for readers is really easy (and doesn't require documentation).

**Comment by naturalprogrammer** [comment]
Awesome!

**Comment by naturalprogrammer** [comment]
I am trying it out, and finding that it is working well for books directly in my account (sanjay/:book). But, for the book which is under an organization that I have created (naturalprogrammer/spring-lemon-getting-started), the webhook isn't working. I tried both these webhook urls:

```
https://gumroad-service.gitbook.com/webhook/sanjay/spring-lemon-getting-started/:api-key
https://gumroad-service.gitbook.com/webhook/naturalprogrammer/spring-lemon-getting-started/:api-key
```
 but neither is working.

**Comment by naturalprogrammer** [comment]
Also, one feedback. If the URLs of the paid books would now be different for different users, we wouldn't be able to post a link to a page of a paid book from another book or website. That looks like a notable shortcoming to me - do you see a way for this?

**Comment by SamyPesse** [comment]
Yes the service doesn't support organization for now, but I'm working on it. I'm also working on a better UX for authors with login via GitBook, then login via Gumroad, and a simple UI to add the webhook.

The only URL that you'll need to share will be the Gumroad URL. The URL on gitbook.com will be private. If you post a link to this book, visitors will get a 404, except if they bought the book on this device (the access key is stored in a cookie session).

**Comment by drreen** [comment]
Any updates on support for organizations on this?

**Comment by AlastairTaft** [comment]
Any updates on organisation support? But annoyed I signed up for a paid personal account and couldn't write a book for my organisation's private repo. So I then signed up for a paid organisation and still couldn't find a way of linking it.
