### ISSUE TITLE
How can i integrate my private gitbook to my product

### ISSUE THREAD

**Issue by gopimr2** [GitbookIO/gitbook#1028]
# Gitbook Integration with projects

I need to integrate private gitbook to my product. Is there any option or API available to do this via **Node.js**?

**Comment by SamyPesse** [comment]
There is a [Node.js client](https://github.com/GitbookIO/node-gitbook-api) for the GitBook API: http://developer.gitbook.com

You can use the [Contents API](http://developer.gitbook.com/books/contents/index.html) to access the output content.

**Comment by gopimr2** [comment]
@SamyPesse  i need to show the book in my broduct (client )

**Comment by AaronO** [comment]
@gopimr2 Are you using `electron` or `node-webkit` ?

You can use `access keys` to get a public URL to a private GitBook.

Go to your book's `settings`, then under `Keys` you'll find a page where you can add new keys, add a new key for your app and when you click on it, you'll see the full URL.

Simply then get your app to open that URL in a webview (or `iframe`) and that should do the job.

**Comment by gopimr2** [comment]
Thanks @AaronO.
