### ISSUE TITLE
Can't specify relative path for entries in `structure` in configuration

### ISSUE THREAD

**Issue by joakin** [GitbookIO/gitbook#1029]
From: https://github.com/gpbl/gitbook-demo/issues/1

I was trying to test a setup for using gitbook for documenting OSS projects : https://github.com/gpbl/gitbook-demo

In the repo and article they suggest having the `SUMMARY.md` inside `docs/`, and having in the `book.json`:

``` json
{
  "structure": {
    "summary": "docs/SUMMARY.md"
  }
}
```

This doesn't work with gitbook 2.6.2 but it does with gitbook 2.4.3. I've tracked it (I think) to the usage of `path.basename` here https://github.com/GitbookIO/gitbook/commit/9b7a90afef5a19c97c45339a3ccc4ebc3db36397#diff-b5a2ce966f78818a95c0455376feeb24R604 which extracts the relative path out of the file name when actually querying the file in the file system https://github.com/GitbookIO/gitbook/commit/9b7a90afef5a19c97c45339a3ccc4ebc3db36397#diff-b5a2ce966f78818a95c0455376feeb24R615

I've looked at the `CHANGES.md` and I haven't seen anything regarding the removal of this feature, or maybe it never was a feature, but be aware that there are projects using it to keep their docs outside of the root of the project (like [redux](https://github.com/rackt/redux/blob/master/book.json) and others...)

Is this something that needs fixing or is this feature not supported?

**Comment by joakin** [comment]
The problem exists with `2.6.x` but not with less than that (`2.5.2` works fine)

**Comment by SamyPesse** [comment]
We are aware that some projects are using GitBook to build documentation that are inside a sub-directory. It never was a fully supported feature, but it's something that we want to support.

### Previous "solution": `structure` configuration

This configuration can be specified to force GitBook to use another file than `README.md` (and keep the `README.md` for GitHub).

But this configuration doesn't work well if you specify a file inside a sub-directory (ex: `docs/README.md`), because GitBook will output this file as `docs/index.html` and there will be no `index.html` in the root folder.

So I recently enforce the structure to be in the root directory (I forgot to signal it in the changelog for 2.6.0, sorry!).

### New potential solution: `root` option

We can add a `root` option to the `book.json`:

```
README.md   (-> for GitHub or the team)
book.json
docs/
     README.md (-> for GitBook)
     SUMMARY.md
```

Implementing this will require few work in GitBook itself, but more work in the editor.

What do you think?

**Comment by joakin** [comment]
This is not only about `README.md`. It also forces you to have the `SUMMARY` in the root directory.

One solution would be makng root configurable as you said, but it seems pretty complicated when we could just change the basename call from https://github.com/GitbookIO/gitbook/blob/9b7a90afef5a19c97c45339a3ccc4ebc3db36397/lib/book.js#L604

```diff
    var ext = path.extname(filename);
+     var dirname = path.dirname(filename);
    var basename = path.basename(filename, ext);

    // Ordered list of extensions to test
    var exts = parsers.extensions;
    if (ext) exts = _.uniq([ext].concat(exts));

    return _.reduce(exts, function(prev, ext) {
        return prev.then(function(output) {
            // Stop if already find a parser
            if (output) return output;

-             var filepath = basename+ext;
+             var filepath = path.join(dirname, basename+ext);
```

This way it doesn't loose the dirname of the path in the `book.json` and I guess it would behave the same as it did in `2.5.2`.

Does this sound sensible?

**Comment by gpbl** [comment]
I would find very useful if we could specify a different path for the *summary* file. Instead I'm not sure why we should need to change the root.

Anyway [this is the article](https://medium.com/p/465dd8d5bfba) I wrote and that @joakin is referring to :-) For now I ask users to stay on v2.5.

Thanks for the awesome project, @SamyPesse !

**Comment by GuillaumeLeclerc** [comment]
Any news on this ?

**Comment by tuchk4** [comment]
+1

**Comment by julienvincent** [comment]
You can do this with the latest version by changing

```
{
  "structure": {
    "summary": "docs/SUMMARY.md"
  }
}
```
to
```
{
  "structure": {
    "summary": "docs.SUMMARY.md"
  }
}
```

**Comment by julienvincent** [comment]
Nevermind - that still does not work.

**Comment by tomdavidson** [comment]
I would structure to be relative to the doc root to facilitate GitBook as a project documentation microsite that already has a README.md in the project root. For example:

project root:
```
package.json
docs/
docs/SUMMARY.md
docs/lots-of-various,md
README.md
book.js
```

books.js
```js
  "root": "./docs",
  "structure": {
    "summary": "SUMMARY.md",
    "readme": "../README.md"
  }
```
