### ISSUE TITLE
Table with indentations failed

### ISSUE THREAD

**Issue by camsong** [GitbookIO/gitbook#1031]
When table markdown has indentations, it can not render the table.

``` code
1. item 1

    | Name | Value |
    |-----------|------------------------|
    | App | `componentWillReceiveProps` |
    | Home | `componentWillUnmount` |
    | Invoice | `componentDidMount` |

2. item 2
```

The output is

![image](https://cloud.githubusercontent.com/assets/948896/11415350/b7b03ca8-943c-11e5-9143-1749d0414501.png)

**Comment by xiaobitipao** [comment]
I also found the same problem. If there is indentation, the table will not display properly.
