### ISSUE TITLE
Custom domain does not affect to internal links

### ISSUE THREAD

**Issue by markomanninen** [GitbookIO/gitbook#1034]
I'd like to get a confirmation, if this subject is discussed. It seems that if I have configured a custom domain, links on navigation menu and other text content points to gitbook.io, not to the configured domain.

Is this in purpose or should they be changed to custom domain? I'm thinking this from the search engine point of view. But also from consistency, when user clicks a link on pdf, I think they should point to custom domain.

For example my pre-released book is served on: [http://artifacts.flowerofliferesearch.com/](http://artifacts.flowerofliferesearch.com/)

but links on navigation and content points to:

[https://markomanninen.gitbooks.io/artifacts-of-the-flower-of-life/content/references.html](https://markomanninen.gitbooks.io/artifacts-of-the-flower-of-life/content/references.html)

while I think better would be:

http://artifacts.flowerofliferesearch.com/references.html

**Comment by markomanninen** [comment]
That was my bad. In GoDaddy domain control I had made subdomain forward with a mask. That caused frame solution appearing on my subdomain.

Right way was to create a new CNAME with artifacts host and point that to www.gitbooks.io. Now internal links work as I was expecting.

**Comment by SamyPesse** [comment]
OK :) Glad to see you found the issue
