### ISSUE TITLE
execute 'gitbook serve'，"can't find index.html"

### ISSUE THREAD

**Issue by tinygg** [GitbookIO/gitbook#1039]
E:\project_book>gitbook init

> info: init book at E:\project_book
> info: detect structure from SUMMARY (if it exists)
> info: create PAGE1.md
> info: found README.MD
> info: create folder/PAGE2.md
> info: create NOTFOUND.md
> info: initialization is finished
> 
> Done, without error

E:\project_book>gitbook serve

> Live reload server started on port: 35729
> Press CTRL+C to quit ...
> 
> info: loading book configuration....OK
> info: load plugin gitbook-plugin-highlight ....OK
> info: load plugin gitbook-plugin-search ....OK
> info: load plugin gitbook-plugin-sharing ....OK
> info: load plugin gitbook-plugin-fontsettings ....OK
> info: load plugin gitbook-plugin-livereload ....OK
> info: >> 5 plugins loaded
> info: start generation with website generator
> info: clean website generatorOK
> info: generation is finished
> 
> Starting server ...
> Serving book on http://localhost:4000

then,open http://localhost:4000/ ,it shows:

> ENOENT: no such file or directory, stat 'E:\project_book_book\index.html'

**Comment by wenjoy** [comment]
I met this problem and solve it.You should check your README.md at the same directory as SUMMARY.md

**Comment by namuol** [comment]
This also breaks if you have a configuration like so:

```json
{
  "structure": {
    "readme": "README.md",
    "summary": "docs/README.md"
  }
}
```

(I use this approach so browsing to `docs` on GitHub shows you the summary, by default.)
