### ISSUE TITLE
Can't load plugins in v2.5.0 and above

### ISSUE THREAD

**Issue by aiden0w0** [GitbookIO/gitbook#1040]
I'm using the v 2.6.4 and found that although the static html file have js loaded, none of them are included in html code. However those faqs are showing screenshots of correct. So I use `-v` and the 2.4.0 and down are working fine.
Why's that?

**Comment by SamyPesse** [comment]
Which plugins? Do you have a link to the source of your book?

**Comment by mikaoras** [comment]
all default plugins, highlight, search, fontsetting

**Comment by SamyPesse** [comment]
What is your book? this is working fine for me (ex: https://help.gitbook.com) and there are unit tests for this.

**Comment by mikaoras** [comment]
It's some Chinese(Traditional) books, and I've no idea whether it's because of my network or something.
I've put them online -> http://yocat.b0.upaiyun.com/gb/index.html
BTW, it's wired that the menu and fontsetting works on the webhosting but not in my local mamp
