### ISSUE TITLE
Glossary and Latex

### ISSUE THREAD

**Issue by vhuber** [GitbookIO/gitbook#1041]
Hi there,

I've found a strange behavior mixing LaTeX and Glossary.

I've on the glossary the entry `## rank`.
I write somewhere in my book:
>
> $$\mathrm{rank}(f(\overrightarrow{x}))$$
>

The display with the editor (web based or local) is as expected : 
<img width="140" alt="capture d ecran 2015-12-08 a 09 32 49" src="https://cloud.githubusercontent.com/assets/2920150/11651127/ae32d0fe-9d8e-11e5-94fc-fb6ec11ee47e.png">

But online, I see that:

<img width="944" alt="capture d ecran 2015-12-08 a 09 28 54" src="https://cloud.githubusercontent.com/assets/2920150/11651078/533f785a-9d8e-11e5-8fc2-b8630544bc86.png">

Do I miss something ?

**Comment by SamyPesse** [comment]
Fixed, it'll be in the next release.
