### ISSUE TITLE
Support for ISBN per e-book format

### ISSUE THREAD

**Issue by glueckpress** [GitbookIO/gitbook#1042]
In some parts of the world, legislation requires an ISBN be assigned to _each format_ of an e-book. In order to support that requirement, it would be great if we could just assign 1 ISBN to each format in book.json, e.g. something like:

```
{
    "isbn": {
        "epub": "ISBN_FOR_EPUB_HERE",
        "mobi": "ISBN_FOR_MOBI_HERE",
        "pdf": "ISBN_FOR_PDF_HERE"
    }
}
```

Output should be made available accordingly, probably somehow like `options.isbn.epub`, `options.isbn.mobi`, `options.isbn.pdf` or so.

**Comment by SamyPesse** [comment]
This is a good idea, and a requirement to make GitBook adapted for publishing books.

But I'm considering two types of option.

### Type 1

Like @glueckpress  suggested:

```js
{
    "isbn": {
        "epub": "ISBN_FOR_EPUB_HERE",
        "mobi": "ISBN_FOR_MOBI_HERE",
        "pdf": "ISBN_FOR_PDF_HERE"
    }
}
```

### Option 2

Allow to replace some configuration according to type of build, there is already a `pdf` entry to configure specific of PDF build.

```js
{
    "isbn":"DEFAULT_ISBN",

    "pdf": {
          "title": "Title for PDF only",
          "isbn": "ISBN_FOR_PDF"
    },
    "epub": {
          "title": "Title for ePub only",
          "isbn": "ISBN_FOR_EPUB"
    }
}
```


@AaronO , @jpreynat what do you think?

**Comment by markomanninen** [comment]
Agree. Now I have put: ```{isbn} (pdf), {isbn} (epub), and {isbn} (mobi)``` all on same field.

**Comment by glueckpress** [comment]
@SamyPesse Option 2 clearly sounds preferable to me. :+1:
