### ISSUE TITLE
Add Word (doc/docx) -export

### ISSUE THREAD

**Issue by markomanninen** [GitbookIO/gitbook#1044]
I noticed many proof-reading and edit companies support only Word document as a file format. Thus, it would be nice to get an export to doc/docx. Conversion from PDF doesn't work well. I don't know how about single HTML file to word then, because I have not get single page format working yet...

**Comment by klauern** [comment]
I've been using GitBook recently and I think this would be an excellent plugin or addition.  I don't know how this could be done, but I just recently saw that [HackMyResume](https://github.com/hacksalot/HackMyResume/blob/62c967526f1f783389245dbae6db7f9404c30ea9/src/generators/html-pdf-cli-generator.js) has a PDF cli option, so maybe piggy-back off of that?

**Comment by klauern** [comment]
Gah, I have my awful-file-format names of PDF and Doc crossed.  There's also a [Word Doc generator](https://github.com/hacksalot/HackMyResume/blob/f4e763bd9c8b63747b80e3e72ce5316c48833330/src/generators/word-generator.js).

**Comment by FickleLife** [comment]
Any word on doc/docx export?

**Comment by markomanninen** [comment]
I did it manually by downloading epub format, opening it in Calibre and saving to Word docx format. Maybe that can be automated by passing a configuration to Calibre and letting it do the job?

**Comment by imwota** [comment]
Will be good to have export to word or pdf option in Gitbook..

**Comment by louisrawlins** [comment]
@markomanninen Thanks for the idea. Worked much better than expected.

On macOS with [Calibre](https://calibre-ebook.com/) installed, I ran these commands in the terminal:

`% gitbook epub`
`% ebook-convert book.epub book.docx`

As Marko says, the first line generates a file `book.epub` and the second line uses a utility from Calibre that converts that to the file `book.docx` in Word DOCX format.
