### ISSUE TITLE
Support :toc: is asciidoc format

### ISSUE THREAD

**Issue by prudhomm** [GitbookIO/gitbook#1046]
it would be very nice and convenient to have a local table of contents in asciidoc files generated using :toc: 
We are writing scientific documents using GitBook, some of the files are just long and helping navigation in them would be very helpful

**Comment by ebullient** [comment]
This is possible?

Include the following just under the page title, and the TOC will show up: 

:toc:
:toc-placement: preamble
:toclevels: 1

(twiddle with the settings as you will, but those work for me)

The key is there can be no space between the page header and those lines.

**Comment by prudhomm** [comment]
indeed it works but it needs special layout

```
toto
===
:toc:

some text

== section 1

== section 2
````

if `some text` is missing or you use
`= toto` for the title it won't work.

in any case thanks a lot for the tip

**Comment by ebullient** [comment]
https://github.com/powerman/asciidoc-cheatsheet

=)
