### ISSUE TITLE
Support including source files in asciidoc format

### ISSUE THREAD

**Issue by prudhomm** [GitbookIO/gitbook#1048]
We would like to insert code blocks in asciidoc from source files such as 

```
:sourcedir: src/main/java

[source,java]
----
include::{sourcedir}/org/asciidoctor/Asciidoctor.java[]
----
```

We write a benchmarking book (private) and would like to include source code (at least subsets by selecting lines) from files use to generated the benchmark data (which would be displayed like this #1047 
)

**Comment by soulmachine** [comment]
+1

**Comment by prudhomm** [comment]
@SamyPesse any hope in getting this supported in gitbook ?
to write technical books, it is kind of mandatory to have this feature

**Comment by nagim** [comment]
@prudhomm You can use a plugin for that (https://plugins.gitbook.com/plugin/codesnippet).

For the sourcedir, you can put it into a page-level or book-level variable.

**Comment by jaredmorgs** [comment]
Getting the `include` directive is important if you want to offer full AsciiDoc support in GitBook.
