### ISSUE TITLE
How to disable git auto-commit when saving

### ISSUE THREAD

**Issue by yeasy** [GitbookIO/gitbook#1051]
The latest version of git-book will automatically commit when saving.

But we need more explicit commit with meaningful commit-msg.

How to disable it?

Thanks!

**Comment by androchentw** [comment]
+1 want to know that, too

**Comment by ryanhoo** [comment]
+1 I hate auto commting

**Comment by juaalta** [comment]
+1 I want commit when i finish i no when a save.

**Comment by at15** [comment]
it seems this feature is added to config in the beta version https://www.gitbook.com/blog/releases/editor-5-beta 

> Many of you wanted more control over your commits, we heard you and with the help of some code made that happen, you can now commit multiple files at once and enter a custom commit message !
Authors can disable “Auto-commit” from the settings dialog. Once a file is modified, you can commit changes by clicking the “Commit” button and entering a short description of your changes.
You can now revert changes to a specific file or all files (from the files tree).

**Comment by uniquejava** [comment]
I think this defect can be closed. I can disable auto commit and do manual commit in the latest version of gitbook editor 👍

**Comment by aladagemre** [comment]
Is this feature removed in 6.2.0? I can't find a way to disable auto-commit? I could do it on 5.x

**Comment by eugene-goroschenya** [comment]
Still auto-committing when sync external changes
