### ISSUE TITLE
Convert .md links to other pages to .html

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#1055]
To allow links to other pages to work on the web or pdf they need to link to the final `.html` file, that make links on GitHub useless. I propose to detect when links are pointing to other pages using their original `.md` extension (or any other of the extensions allowed by GitHub) and in that case change it to `.html` on the fly.

**Comment by SamyPesse** [comment]
This is already being done.

Example:
- Source: https://github.com/GitbookIO/documentation/blob/master/format/README.md
- Output: http://help.gitbook.com/format/index.html

**Comment by piranna** [comment]
Since what GitBook version is this available? In the example the links start with `./`, is this mandatory so they can be detected, or is just enough they are relative paths?

**Comment by SamyPesse** [comment]
`[test](hello.md)` should work fine.

What version of GitBook are you using? It's available since a long long time.

**Comment by piranna** [comment]
> [test](hello.md) should work fine.

Great! :-D Just what I wanted :-)


>> What version of GitBook are you using?
> It's available since a long long time.

I'm currently using `2.2.0`, I'll try later to see if it works :-)

**Comment by piranna** [comment]
Just a question: this also works when using anchors on the url? I know they works when using a `.html` extension, but don't know if it would also convert correctly the `.md` ones... :-/

**Comment by piranna** [comment]
I've just checked this with GitBook up to 2.6.5 and is not working... Does it only works for bullet points? I'm interested on having the links in the main text...

**Comment by piranna** [comment]
I've found why is failling to me: when the .md link url has a space it doesn't get converted, but it doesn't have it works correctly. I think it would be easy to fix...
