### ISSUE TITLE
Glossary terms are linked in code blocks

### ISSUE THREAD

**Issue by gnomeontherun** [GitbookIO/gitbook#1057]
I'd like to suggest that glossary terms should not be linked inside of code blocks, or at least should be configurable. It gets in the way of presenting code content that might happen to use a glossary term.

**Comment by nagim** [comment]
I think it's fixed (even in scripts, according to [this commit](https://github.com/GitbookIO/gitbook/commit/6eb1605be634799cc56d97f83a25d3e7bb87f86d)). I checked and it works for me with Gitbook 2.6.4.
