### ISSUE TITLE
Gitbook editor: auto-inserts are in markdown and not asciidoc

### ISSUE THREAD

**Issue by ebullient** [GitbookIO/gitbook#1058]
I would love be able to have a preference to select (for the book) asciidoc or markdown, and have all of the formatting tools correctly use asciidoc

I am using asciidoc, when I create a new file, it is correctly named with adoc, but it uses markdown syntax for the header. The button to insert code snippets also uses markdown backticks instead of creating an asciidoc code block.

**Comment by reyman** [comment]
:+1:

**Comment by rich4j** [comment]
+1 for this also

**Comment by SamyPesse** [comment]
Closing this issue, since I opened an issue on our private repository for the editor.
