### ISSUE TITLE
Custom PDF stylesheet not being parsed since 2.5.0

### ISSUE THREAD

**Issue by glueckpress** [GitbookIO/gitbook#1060]
I noticed recently that my PDF stylesheet doesn’t get parsed, or at least parts of it. Custom font families and list styles don’t get applied in the PDF built.

When I revert GitBook to version 2.4.3 via book.json, everything works as expected whereas all version from 2.5.0 on and above show the result described above.

**Screenshot of TOC with GitBook 2.4.3 (styled as expected):**
![bildschirmfoto 2015-12-14 um 14 45 01](https://cloud.githubusercontent.com/assets/308422/11783110/97a25ac6-a275-11e5-8703-04f367efaef6.png)

**Screenshot of TOC with GitBook 2.5.0+ (missing custom font + list styles):**
![bildschirmfoto 2015-12-14 um 15 08 58](https://cloud.githubusercontent.com/assets/308422/11783136/b7e8d210-a275-11e5-810c-e20c2c6f40f6.png)

**Comment by hspencer** [comment]
Yep, having the same issue.

**Comment by nateberkopec** [comment]
@glueckpress Can you share an example of the CSS you're using?
