### ISSUE TITLE
.md links are not converted when they have a space

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#1070]
Links that point to a local `.md` file [are converted to .html](https://github.com/GitbookIO/gitbook/issues/1055), but I've found that if the path has spaces this doesn't happens and is left as is, so they later doesn't work. This is causing too to show errors on the console about the hyperlinks are outside the spine when generating a PDF.

**Comment by k-rus** [comment]
I was hit with the issue. In my case it was enough to have spaces in the link text, while the link itself did not have any spaces. An example of not converted link:
```
[list of statements](statements.md)
```
`statements.md` is not converted into HTML and hyperlink goes to the MD file. The gitbook log contains warning:
> warn: page README.md contains an hyperlink to resource outside spine 'statements.md'

**Comment by piranna** [comment]
> warn: page README.md contains an hyperlink to resource outside spine 'statements.md'

I think this error is not related with this bug according to what I understood about it, seems it's a security behaviour for ebooks, to be sure there are no dead links.

**Comment by k-rus** [comment]
> I think this error is not related with this bug according to what I understood about it, seems it's a security behaviour for ebooks, to be sure there are no dead links.

I think you are right. It would be great if you can point me where I can read about the security behaviour.

**Comment by piranna** [comment]
> I think you are right. It would be great if you can point me where I can read about the security behaviour.

I just searched about that error and point me to some ebook format documentation from Adobe, don't remember where.

**Comment by piranna** [comment]
Anyway, I think gitbook or calibre should be intelligent enough to detect this security issue could happen and format URLs so it doesn't warn to the user... This seems to be introduced about gitbook 2.3 or something similar.

**Comment by k-rus** [comment]
> I just searched about that error and point me to some ebook format documentation from Adobe, don't remember where.

I was not so patient when I searched about the error. So far I haven't found any meaningful information about my error. I will continue to search. Thank you for the comment.



> Anyway, I think gitbook or calibre should be intelligent enough to detect this security issue could happen and format URLs so it doesn't warn to the user... This seems to be introduced about gitbook 2.3 or something similar.

This problem is very annoying. My current work around is to include all my MD files into the global summary.

Thank you for your feedback and sorry for off-topic.

**Comment by akauppi** [comment]
Faced this. Changing the links themselves proved to be enough, and corrected the problem (spaces in link texts could remain).

```
$ ./node_modules/.bin/gitbook --version
CLI version: 2.3.0
GitBook version: 2.4.3
```

**Comment by garyng** [comment]
Any updates for this issue?
Links with space in `SUMMARY.md ` will be converted. But others(in the content) will not.

**Comment by iBobik** [comment]
Still not working

CLI version: 2.3.2
GitBook version: 3.2.3

**Comment by ljharb** [comment]
@addisonschultz can you link to a PR or commit that fixed this?

**Comment by addisonschultz** [comment]
Hi @ljharb - This version of GitBook has been deprecated for the last few years, and hasn't been under active development for a while. You can read more about that here: https://github.com/GitbookIO/gitbook/tree/legacy?tab=readme-ov-file

This repository is now home to the rendering engine of the most up-to-date version of GitBook. Further development of this version will continue to be found in this repository!

**Comment by addisonschultz** [comment]
@piranna Correct - as this this version of GitBook is deprecated no longer maintained, unfortunately this and other issues will not be fixed moving forward

**Comment by ljharb** [comment]
Then you should close it as gray (won’t fix) instead of purple (fixed)

**Comment by piranna** [comment]
Agree on that, set them as won't fix.

**Comment by addisonschultz** [comment]
@ljharb @piranna - I agree, and apologies for the confusion so far on this. We'll take a look at this with further cleanup efforts to this repository and project. It doesn't seem possible to do in bulk, but we'll take this into consideration moving forward
