### ISSUE TITLE
Unable to break lines on generated pdf file

### ISSUE THREAD

**Issue by teles** [GitbookIO/gitbook#1071]
I'm using gitbook to publish a poetry book (written in portuguese).
- My gitbook source code is here: https://github.com/versosdomundo/versosdomundo.github.io;
- It is being published by github pages here: http://versosdomundo.github.io/livro/

As my book is a poetry book i'm overwriting the default sass from gitbook to wrap the lines as poetry, [here](https://github.com/versosdomundo/versosdomundo.github.io/blob/master/sass/temas/_poesia.sass):

``` sass
.book .book-body .page-wrapper .page-inner section.normal p
    white-space: pre-wrap
```

It works great for the website build, but doesn't work for the pdf build as can be seen in the [generated pdf file](http://versosdomundo.github.io/livro/versosdomundo.pdf). -> Example: Go to page 6 on pdf and compare with this page http://versosdomundo.github.io/livro/poesias/segunda-feira.html

**Comment by teles** [comment]
So, I would like to know how can I break lines for pdf file (may using another css property or other gitbook option)

Best regards

**Comment by neothemachine** [comment]
![capture](https://cloud.githubusercontent.com/assets/530988/14535368/716adff4-0265-11e6-8a06-018e0b0d34a8.PNG)

I have a similar problem in the PDF output I think, not sure if it's the same. When the line in a code block gets too long then it draws some scrollbar which doesn't make sense and you can't use it anyway, at least in Adobe Reader. This should just force-wrap.
