### ISSUE TITLE
How can i edit this string "Introduction"?

### ISSUE THREAD

**Issue by akar1nchan** [GitbookIO/gitbook#1076]
<li class="chapter active done" data-level="0" data-path="index.html">
            
                
                    <a href="./index.html">
                        <i class="fa fa-check"></i>
                        
                         Introduction
                    </a>
                
            
            
        </li>

**Comment by nagim** [comment]
In the GitBook Editor, in the *Table of contents*, just right-click on the **Introduction** section and click **Edit**. The **Edit Summary Entry** dialog will pop up, where you should be able to change the title.

![intro](https://cloud.githubusercontent.com/assets/16205115/12111768/28d1dfe8-b398-11e5-9847-9dd67ab4a226.jpg)

Or you can just open the **SUMMARY.md** file and change the link text of **README.md** (in the below example, `[Introduction]` to `[Whatever you want]`).
```
# Summary

* [Introduction](README.md)
* [First Chapter](FIRST.md)
   * [Subsection](SUB.md)
* [New Section](NEW.md)
   * [Chapter 1](chapter1.md)
```

Cheers,
Imre

**Comment by akar1nchan** [comment]
thx for your answer!
