### ISSUE TITLE
GitBook URLs are not clean

### ISSUE THREAD

**Issue by innermatrix** [GitbookIO/gitbook#1077]
For example, foo/bar.md is turned into foo/bar.html and leads to URL ending in foo/bar.html. Instead, I want GitBook to generate semantic URLs, and turn foo/bar.md into foo/bar/index.md, and use foo/bar in links to it.

**Comment by timpulver** [comment]
Also having an option to turn `foo/foo.md` to `foo/index.html` would be great!

**Comment by jawache** [comment]
Was there ever a fix for this?

**Comment by cipsys** [comment]
When hosting the html static content into an S3 bucket lack of index.html in the links breaks the functionality. This is a requirement if GitBook is ever to work with S3 hosting
