### ISSUE TITLE
Support for Markdown frontmatter

### ISSUE THREAD

**Issue by airbornemint** [GitbookIO/gitbook#1079]
As far as I can tell, GitBook currently does not support Markdown frontmatter (the most common format being YAML frontmatter) — when I add some frontmatter in the web editor, it just shows up in the output. 

I would like to have the ability to add metadata to my book pages (which can then be using from inside a plugin), and I think that YAML frontmatter is a good way to accomplish this. Please add support for YAML frontmatter to GitBook.

**Comment by nagim** [comment]
I think it's already on the way (see #795).
