### ISSUE TITLE
Asciidoc callout not supported in gitbook ?

### ISSUE THREAD

**Issue by reyman** [GitbookIO/gitbook#1086]
Hi, i try to create some source code with [callout](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code), and it seems is not supported bit gitbook.
This is a bug or a future feature ? 

```
[source,ruby]
----
require 'sinatra' # <1>

get '/hi' do # <2>
  "Hello World!" # <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response
```

**Comment by nagim** [comment]
Hi,

Since the code is Ruby, you need to use the comment character (`#` instead of `//`) according to Ruby syntax.
So the code block should look like this:
```
[source,ruby]
----
require 'sinatra' # <1>

get '/hi' do # <2>
  "Hello World!" # <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response
```

**Comment by reyman** [comment]
I correct the example, but anyway that don't work in gitbook.

**Comment by nagim** [comment]
In editor, when previewing, it doesn't show correctly, shows me stuff like this:
```
require 'sinatra'  <b class="conum">(1)</b>
1. Library import
```
However, when I build the files, it works fine with both `#` and `//`.

My code:
```
[source,ruby]
----
require 'sinatra'  // <1>
get '/hi' do       # <2>  
  "Hello World!"     
end
----
<1> Library import
<2> URL mapping
```
Result:
![callout](https://cloud.githubusercontent.com/assets/16205115/12199700/8290a17a-b61a-11e5-86c6-2cbfa3ad0e30.jpg)

@SamyPesse, could you please take a look (if you have time and capacity), to display this correctly in the editor preview (I'm using 5.0.0.-beta3). Thanks!

**Comment by reyman** [comment]
I open a new [issue](https://github.com/GitbookIO/gitbook/issues/1087) because callout can be also draw with image in asciidoc. This option seem here not work by default.
