### ISSUE TITLE
Display icon image for block text with asciidoc in gitbook preview ?

### ISSUE THREAD

**Issue by reyman** [GitbookIO/gitbook#1087]
Hi,

It seems **icons image** or _font-awesome icons_  used to create special bloc with asciidoctor doesn't work in preview mode of gitbook.

You can try by adding this asciidoc code (from [asciidoc documentation](http://asciidoctor.org/docs/user-manual/#delimited-blocks)) to your book : 

```
[IMPORTANT] 
.Feeding the Werewolves
==== 
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
```

**Comment by gristel** [comment]
Is it me or do icon images not show?

```
CAUTION: Some caution message
```
This does not display the caution image but just the word CAUTION:

**Comment by reyman** [comment]
Any news of dev team on asciidoctor better support ?

**Comment by gristel** [comment]
The latest news I got is that there will be better support for Asciidoctor in gitbook version 3.0..
Meanwhile I'm trying to create a theme that has some workarounds for current issues..

**Comment by manoelcampos** [comment]
I made it work by adding the plugin `asciidoc-admonition-icons` to the `book.json` file:

```json
{    
    "plugins": ["asciidoc-admonition-icons"]
}
```
