### ISSUE TITLE
Is there a way to create plugins that does not require you publishing them to NPM?

### ISSUE THREAD

**Issue by dionridley** [GitbookIO/gitbook#1093]
I'm trying to create a plugin but would like to avoid publishing to NPM because it is specific to our company.  I tried to create the node_modules folder and build my plugin identical to the way gitbook install sets them up in your project but did not have any success.

The error message is that it must be installed with gitbook install.  Is there any work around for this?

**Comment by SamyPesse** [comment]
You can potentially use a GIT url in the `book.json`, since `gitbook install` is running the NPM command to install it.

Try something like:

```
{
    "plugins": [
        {
            "name": "myplugin",
            "version": "git+https://github.com/YourCompany/myplugin.git"
        }
    ]
}
```

Not sure if it'll work, but I can make the require changes to make it work in the future versions of GitBook.

**Comment by dionridley** [comment]
Thanks, this solution seems to work for us.

**Comment by AaronO** [comment]
@dionridley I just wanted to add that you can also simply version your plugin in the git repo by keeping in under `node_modules`.

You'll have to correctly tweak your `.gitignore` obviously, but it should work.

**Comment by uliska** [comment]
There is another way to use non-published gitbook plugins:

In your plugin's `package.json` there must be a

```json
  "engines": {
    "gitbook": "*"
  },
```
entry. If that's not present Gitbook won't recognize it and ask you to install using `gitbook install`. So if your plugin contains that entry Gitbook won't try to install it.

What I do is *not* to actually have the plugin folder within the book but somewhere else and use a symlink in `path/to/your/book/node_modules`.
