### ISSUE TITLE
How to add <link> to header?

### ISSUE THREAD

**Issue by denysdovhan** [GitbookIO/gitbook#1100]
I wrote a [gitbook-plugin-rss](https://github.com/denysdovhan/gitbook-plugin-rss). Now this plugin only displays a link to feed like here:
![](https://cloud.githubusercontent.com/assets/3459374/12374850/81a6cd9a-bcb2-11e5-9b05-251fea000d3b.png)

But I need to add special `<link>` into  `<head>`:

```html
<link href="http://book.com/rss.xml" title="Book" rel="alternate" type="application/rss+xml">
``` 

Is there any possible way how to do this? As I [understood](https://developer.gitbook.com/plugins/assets.html) I can do this only using javascript.

**Comment by SamyPesse** [comment]
You can use the snipper `head:end` to append a `<link>` (https://github.com/GitbookIO/gitbook/blob/master/theme/templates/website/layout.html#L22)

```js
module.exports = {
    website: {
        html: {
             'head:end': function() { return '<link>....' }
        }
    }
};
```

Let me know if that works :)

**Comment by denysdovhan** [comment]
Awesome! [gitbook-plugin-rss@1.1.0](https://github.com/denysdovhan/gitbook-plugin-rss/blob/master/index.js#L15-L17) has been published!
