### ISSUE TITLE
Add support for RTL languages in Gitbook editor

### ISSUE THREAD

**Issue by christopheradams** [GitbookIO/gitbook#1101]
While the gitbook command can generate web and epub with correct display of RTL languges, the same cannot be said of the editor (both web and Desktop versions up to 5.0 beta). I'm finding it awkward to work with Arabic text in the editor, since the word order and justification are incorrect.

Can the editor be made to read the language of the book and display the editing and preview fields with the correct `dir` attribute set?

**Comment by boustanihani** [comment]
I also hope this will be supported soon as Gitbook 3 has been recently released :+1:

**Comment by SamyPesse** [comment]
This is will be supported in the next release of GitBook Editor.

**Comment by boustanihani** [comment]
Do you mean the next major (4.x) or minor (3.x) release ?

**Comment by SamyPesse** [comment]
The GitBook Editor is a separated product, with its own versioning.

**Comment by boustanihani** [comment]
Oh I didn't know that :) so should we move this feature request somewhere else ?

Will the next major or minor "GitBook Editor" release support this?

**Comment by boustanihani** [comment]
Would you mind pasting the "GitBook Editor" repo, I couldn't find it.

**Comment by boustanihani** [comment]
Is the fix included version 3.2.0 which was released today ?

**Comment by boustanihani** [comment]
Any Updates ?

**Comment by Eng-Fouad** [comment]
Any updates? :)

**Comment by boustanihani** [comment]
Maybe you could make use of this project =>

https://github.com/MohammadYounes/rtlcss

**Comment by boustanihani** [comment]
Any updates on this? will the new gitbook platform get 100% RTL support for editing and viewing?
