### ISSUE TITLE
Book doesn't load

### ISSUE THREAD

**Issue by wimpers** [GitbookIO/gitbook#1104]
For some reason my book shows an empty  page when going to https://www.gitbook.com/book/openvstorage/openvstorage/details .

**Comment by wimpers** [comment]
Seems it is now fixed.

**Comment by SamyPesse** [comment]
It was a small bug in our latest release for books with collaborators, I fixed it a few minutes later.

**Comment by wimpers** [comment]
Thanks for the swift fixing!
