### ISSUE TITLE
gitbook生成的文件无法发布到github上?

### ISSUE THREAD

**Issue by snailbig** [GitbookIO/gitbook#1107]
下面是我的操作步骤，我把它贴出来，否则我可能表达不清我的问题

创建仓库和分支

gitbookTest2是我在github上新建的仓库

➜  ~  git clone https://github.com/snailbig/gitbookTest2.git
➜  gitbookTest2 git:(master) git checkout -b gh-pages
➜  gitbookTest2 git:(gh-pages) git push -u origin gh-pages
➜  gitbookTest2 git:(gh-pages) git checkout master

同步静态网站代码到分支
➜  ~  git clone -b gh-pages https://github.com/snailbig/gitbookTest2.git book-end
此时我将我用gitbook serve生成的_book静态网站文件夹放到了book_end文件下
➜  book-end git:(gh-pages) ✗ git add .
➜  book-end git:(gh-pages) ✗ git commit -m "push to branch gh-pages"
➜  book-end git:(gh-pages) git push -u origin gh-pages

等会一会，再访问http://snailbig.github.io/gitbookTest2还是404页面，前两天我也试了，也没有成功，请教哪里出了问题?,该怎样做?

**Comment by jhaoheng** [comment]
既然都用了 github 當靜態檔的存放地
怎不直接用 gitbook 的服務 
https://www.gitbook.com

感覺這不是 gitbook 的問題，或許是 github pages 的設定問題

**Comment by yafey** [comment]
@snailbig 在 gh-pages 分支 新增 .nojekyll 文件 来标记 不需要 jekyll 解析， 存放的是 html/css 文件。

**Comment by yafey** [comment]
@snailbig 在 gh-pages 分支 新增 `.nojekyll` 文件 来标记 不需要 jekyll 解析， 存放的是 html/css 文件。
