### ISSUE TITLE
Relative image paths not working

### ISSUE THREAD

**Issue by ralfw** [GitbookIO/gitbook#1111]
Here's a small book to illustrate relative image paths not working:

https://www.gitbook.com/book/ralfw/test_imagepaths/details/de

It's a multi language book with de/ and en/ sub-directories and a LANGS.md file. That part is working very well.

But as you can imagine, I'd like to share images between the translations. I don't want to put images into each language's branch, but keep them as global resources to be linked to from each language.

As you can see, though, it's impossible to reference global images from .md files in sub-directories. Check out the two introductory pages of the book. Their paths are:

/de/README.md
/en/README.md

and they are supposed to show the images located at

/resources/images/*

*It neither works with an absolute path nor a relative path like ../resources/images/kitten.jpg.*

However, pointing down the branch is no problem. That's what the German translation does. It links to an image located in it's branch at /de/de_images/kitten2.png by just using a relative pathname: de_images/kitten2.png.

Relative paths up the folder hierarchy (and then down again in a different branch) don't work in any of the generated books (web, pdf, epub, mobi). Interestingly, though, they work in the editor.

In my view this is a bug. It severely impedes writing multi language books, because it would require the author to duplicate images in every languge's branch leading to a maintenance nightmare if an image changed.

Please fix it. I'd like to see more kittens, ideally all of them. Don't you? ;-)

-Ralf

*Web-View of page:*

<img width="200" alt="bildschirmfoto 2016-01-24 um 17 13 16" src="https://cloud.githubusercontent.com/assets/132662/12537377/0e484470-c2be-11e5-8918-e4945e906326.png">

*Editor-View of same page. See how the relative path is working:*

<img width="600" alt="bildschirmfoto 2016-01-24 um 17 14 02" src="https://cloud.githubusercontent.com/assets/132662/12537380/161504fe-c2be-11e5-9fe3-ae63cda7a9f0.png">

**Comment by SamyPesse** [comment]
I'm closing this issue, this is the same issue as https://github.com/GitbookIO/gitbook/issues/744

It'll be fixed in GitBook v3 (https://github.com/GitbookIO/gitbook/pull/1109).
