### ISSUE TITLE
Syntax highlight in  5.0.0 editor 

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#1116]
Hi guys, 
This first I've recognized in gitbook  5.0.0-beta.6 editor 

the book support inline interpretation for markdown but it misses to highlight code syntax inline which will be really elegant 

Note: I've faced some unexpected crashes after installing the beta version but crashes vanish for some reason now 

you're awesome guys!

**Comment by xxiao** [comment]
is it possible to get highlightjs plugin working for gitbook? the default syntax highlight could probably just leverage highlight.js (or pygment)
