### ISSUE TITLE
"Can not fast forward" in GitBook Editor 4.2.3 Mac

### ISSUE THREAD

**Issue by warpech** [GitbookIO/gitbook#1117]
Using GitBook Editor 4.2.3 Mac, I always have a problem when one of my teammates pushes a change to a book while I have unsynced changes. We are hosting the book on GitHub.

When I press sync button, I get the following message:

![screen shot 2016-01-28 at 12 40 05a](https://cloud.githubusercontent.com/assets/566463/12652676/2df6cd42-c5ec-11e5-8768-a6c7cea61ada.png)

A workaround for that is to go to the git folder and do a manual `git pull`, which makes a merge by `recursive` strategy.

**Comment by miyconst** [comment]
:+1: This is extremely annoying. Would be very good to get it fixed.

**Comment by nagim** [comment]
I think it's not an editor related issue, rather how git works. If someone has pushed to the same branch as you, git cannot push your changes.
As you said, the solution is to make a `git pull` before, which you can do from the editor as well (in the menu, **Book** > **Pull**).
In order to avoid this kind of errors, it's useful to make a new branch for draft changes and merge it to `master` when it's done.

**Comment by warpech** [comment]
Using *Book* > *Pull* from the menu also tries to do a fast-forward merge, even when it's not possible. If I didn't know how to do a plain `git pull` in the command line, I would not be able to proceed.

**Comment by warpech** [comment]
See the below screengrab where I try both the Sync button (from the toolbar) and Pull option (from the menu):

![bug](https://cloud.githubusercontent.com/assets/566463/12652810/eeebcb38-c5ec-11e5-9687-2a3977e3bff4.gif)

**Comment by nagim** [comment]
Hmmm, that's indeed strange. I know if you merge branches in the editor, it does not fast-forward, even if it would be possible. I assumed that Pull works the same.
Have you tried the 5.0.0-beta editor? There were some upgrades regarding git operations.

Cheers,
Imre

**Comment by warpech** [comment]
Same problem in 5.0.0-beta.6:

![bug](https://cloud.githubusercontent.com/assets/566463/12674968/4eece7d4-c687-11e5-9015-66e9e5eadb50.gif)

**Comment by warpech** [comment]
Actually 5.0.0-beta.6 makes it more painful. With GitBook Editor 4.2.3 it was enough to do a `git pull` in the console (see the workaround described above).

In 5.0.0-beta.6, `git pull` does not work because saved changes are not commited:

<img width="697" alt="screen shot 2016-01-29 at 13 16 32" src="https://cloud.githubusercontent.com/assets/566463/12675464/c389a7b4-c68a-11e5-9905-edbac95a81ca.png">

I need to do a `git stash` before `git pull`.

**Comment by nagim** [comment]
Yes, the new beta comes with the new option of separating the saving and committing. This way, you can commit multiple changes in a single commit. There is a separate **Commit** button next to the **Save** button in the editor.
You can of course switch back to commit with every save in the editor settings.

**Comment by warpech** [comment]
> Yes, the new beta comes with the new option of separating the saving and committing. This way, you can commit multiple changes in a single commit. There is a separate Commit button next to the Save button in the editor.

That's a very welcome to have, I didn't know about it! 

But I think it doesn't work at the moment, because it was **on** in my case:

![screen shot 2016-01-29 at 13 48 04](https://cloud.githubusercontent.com/assets/566463/12676016/17d160c4-c68f-11e5-8c85-93d4866b9258.png)

Yet, my saved changes were not commited - therefore I needed to stash them.

**Comment by warpech** [comment]
Point is, I have never had such problem in the online editor, so I guess it is only the desktop editor that always wants to use ff.

On a side note, I wonder, what is the merging strategy for the online editor in case of a conflict?

Thanks a lot for being so responsive!

**Comment by SamyPesse** [comment]
@warpech Are you sure `README.md` and `webshop.md` were not edited by another program ?

GitBook Editor is not writing file on the disk before committing them (stored in the local-storage of the web view). Basically GitBook Editor can't work with staging file from other programs.

We are working on fixing all of this, currently we just prompt an error when there are conflicts during merge, our goal for the next release is to have a nice UI to resolve these conflicts.

**Comment by nagim** [comment]
@SamyPesse Thanks a lot, just what I wanted to ask/note about merge conflict, but you were faster. :smile:

**Comment by warpech** [comment]
> @warpech Are you sure README.md and webshop.md were not edited by another program ?

Yes, I've recorded another screengrab to show this:

![bug](https://cloud.githubusercontent.com/assets/566463/12676415/699afd9a-c692-11e5-9766-454b546130e6.gif)

`git status` (as shown on the screengrab) shows that after saving there is a change in the index that is not commited.

**Comment by KINGSABRI** [comment]
Same issues here "Gitbook desktop editor Version 5.0.0-beta.6"

**Comment by duckrun** [comment]
good: change log
bad: for local editor no conflict merge support (just telling you error), for web editor, either override no give up the changes, just no means to merge the conflict at all, which as a result almost CANNOT be used in collaborative editing

**Comment by aleen42** [comment]
Hello, I have solved it by finding the local directory, and use command to pull and push. Maybe, it's work for you.
