### ISSUE TITLE
Please add emoji support to Gitbooks

### ISSUE THREAD

**Issue by bhalothia** [GitbookIO/gitbook#1120]
We have created a book from our learning repository on DevOps.

Github repo: https://github.com/TheRemoteLab/awesome-learning
Gitbook: https://theremotelab.gitbooks.io/awesome-learning/content/

The emojis could not be loaded in the Gitbook. :expressionless:

I tried looking but there's no issue opened/closed on emoji support. Please take it as an enhancement request.

**Comment by DotJoshJohnson** [comment]
I second this. I am exploring the possibility of migrating my wikis to GitBooks, but I make pretty heavy use of emojis in my documentation to draw attention to call-outs.

**Comment by LabLayers** [comment]
:+1:

**Comment by ftwbzhao** [comment]
@LabLayers me too.

**Comment by skyscribe** [comment]
:+1: I second this also

**Comment by azat-co** [comment]
Still no emoji? :(

**Comment by andrei512** [comment]
👍 +1

**Comment by oldsand** [comment]
me too!!

**Comment by wolf99** [comment]
👍 +1

**Comment by rdooh** [comment]
👍

**Comment by raulfdm** [comment]
👍

**Comment by tatyderb** [comment]
👍

**Comment by lorensr** [comment]
Emoji characters show up for me in epub and mobi on Mac, but not in pdf. Instead, there's a wide white space:

![image](https://user-images.githubusercontent.com/251288/37311180-bdc377e4-261c-11e8-99a7-6b124aaf5a7b.png)

versus epub in iBooks:

![image](https://user-images.githubusercontent.com/251288/37310975-11cddb1e-261c-11e8-87cb-eb1325e23b3e.png)

**Comment by lorensr** [comment]
$100 bounty on this, if anyone's up for trying to implement it. 

Specifically, raw emoji characters showing up in PDFs—either in the default emoji of the platform, or always as apple emoji.
