### ISSUE TITLE
Wrong font of Chinese in pdf.

### ISSUE THREAD

**Issue by lizhixia** [GitbookIO/gitbook#1122]
There is a screenshot about a pdf from https://www.gitbook.com/book/llh911001/mostly-adequate-guide-chinese/details.
![2016-02-01 14 07 40](https://cloud.githubusercontent.com/assets/16068030/12710225/6ee4fd96-c8ef-11e5-8025-26f87ec09695.png)
Another picture from a pdf build with '$ gitbook pdf', the font is correct.
![2016-02-01 14 15 21](https://cloud.githubusercontent.com/assets/16068030/12710255/aa9682e2-c8ef-11e5-9efe-ca5f0e3e4874.png)
This question exists all of books with Chinese, I hope the question can be solved. Because not of all repositories of books can be find. Hope my English will not make you hard to understand.

**Comment by SamyPesse** [comment]
We just improved the font on GitBook.com for chinese:

Left: new font
Right: old font

![screen shot 2016-04-02 at 10 10 20](https://cloud.githubusercontent.com/assets/845425/14225235/65ee5344-f8bb-11e5-84d0-31b01dfb63e8.png)

**Comment by lizhixia** [comment]
Thanks your receive. Although improved the font, new font effect not at all pdf in gitbook, you should update all links about pdf download. This is a bug before solved it yet.

**Comment by SamyPesse** [comment]
No, authors have to update their books to improve the fonts in their PDFs, we'll not update all books.

**Comment by lizhixia** [comment]
Did all of the users of gitbook receive the message? If author don't update book, what should they do about the readers?
