### ISSUE TITLE
Could not reflect custom font size to PDF

### ISSUE THREAD

**Issue by nutti** [GitbookIO/gitbook#1123]
I'm writing custom `.css` file for PDF output.
However, font-size is not reflected on PDF when font-size is large.
Is there any limitation about font-size?
And, is there any way to handle large font size?

Here is example `pdf.scss` .

``` sass

$font_size_base: 0.01em;

.page {
    .section {
        h1 {
            text-align: left;
            font-size: $font_size_base + 100.0em;   // too big font-size
        }
        h2 {
            text-align: left;
            font-size: $font_size_base + 1.0em;       // ok
        }
        h3 {
            text-align: left;
            font-size: $font_size_base + 0.7em;       // ok
        }
        h4 {
            text-align: left;
            font-size: $font_size_base + 0.3em;       // ok
            font-weight: bold;
        }
    }
}
```

Any ideas?
Thanks!

**Comment by kongou-ae** [comment]
I have same issue. How can I fix this?

**Comment by nutti** [comment]
I think there is a limitation of PDF output.
Too big or small font size is changed to maximum or minimum size automatically.

Maybe this is not gitbook issue.
