### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#1125]
I can't run Gitbook desktop editor **v.5.0.0-beta.7 **

OS: Kubuntu 15.10 64-bit

![error_233](https://cloud.githubusercontent.com/assets/1071827/12795413/01d86c28-cacb-11e5-939d-dd36435ca889.png)

![error -2- _230](https://cloud.githubusercontent.com/assets/1071827/12795417/08a0b164-cacb-11e5-83e1-675a27c46bfc.png)

![there was an error checking for updates _231](https://cloud.githubusercontent.com/assets/1071827/12795556/ab881138-cacb-11e5-92c9-6218dcb63766.png)

![gitbook editor_232](https://cloud.githubusercontent.com/assets/1071827/12795634/f3515f6a-cacb-11e5-9ebd-cb32261bab57.png)

**Comment by SamyPesse** [comment]
I'm working on a new release to fix this :rocket:

**Comment by SamyPesse** [comment]
I've just released the 5.0.0-beta.8 :)

**Comment by KINGSABRI** [comment]
Downloaded and yeah, it's working fine 

Thanks man!

**Comment by rehmanzile** [comment]
@KINGSABRI I hit the same error. I don't see 5.0.0-beta.8 download link in [releases](https://github.com/GitbookIO/gitbook/releases). Please advise.
