### ISSUE TITLE
Remove social icons on gitbooks.io

### ISSUE THREAD

**Issue by nancym** [GitbookIO/gitbook#1126]
If I host a book on myusername.gitbooks.io, is it possible to remove the social icons that are in the upper right corner of the pages? If so, how? Thanks!

**Comment by nagim** [comment]
It's controlled by the [sharing plugin](https://plugins.gitbook.com/plugin/sharing).
This is a default plugin and it can be disabled using a `book.json` configuration:

```
{
    plugins: ["-sharing"]
}
```

Cheers,
Imre

**Comment by nancym** [comment]
Thanks. I put that in the book.json file of my "test" book*, saved the file, waited a while, and the social icons are still showing up. I did this all through the browser-based version of the GitHub Editor. I wonder if I need to "push" that update or do something else. I don't know much about git...

* https://nm.gitbooks.io/test/content/

**Comment by nancym** [comment]
Just figured out that `plugins` need to be `"plugins"` and then it worked!

**Comment by nagim** [comment]
I'm glad it worked!

**Comment by FabianTe** [comment]
Guess this should be closed.

**Comment by xiaoronglv** [comment]
it should be:

```json
{
   "plugins": ["-sharing"]
}
```
