### ISSUE TITLE
How to include a different file according to current language?

### ISSUE THREAD

**Issue by soulmachine** [GitbookIO/gitbook#1127]
I'm writing an algorithm book. The content of the book is language independent, but the code has two versions, Java and C++.

Currently my book structure is as the folowing:

    .
    ├── LANGS.md
    ├── book.json
    ├── java
    │   ├── SUMMARY.md
    │   └── chapter1
    └── cpp
        ├── SUMMARY.md
        └── chapter1

The content of `LANGS.md` is quite simple:

    * [Java](java)
    * [C++](cpp)

I want to reuse my markdown content, and I'm not willing to duplicate markdown files in `java` and `cpp` folders.

For example, if I can get current `language` in use, I can write the following markdown:

    {% if book.lang=java %}
      {% codesnippet "./myfile.java", language="java" %}{% endcodesnippet %}
    {% endif %}
    {% if book.lang=cpp %}
      {% codesnippet "./myfile.cpp", language="cpp" %}{% endcodesnippet %}
    {% endif %}

I use the plugin [codesnippet](https://plugins.gitbook.com/plugin/codesnippet) above.

**Comment by nagim** [comment]
You can use some HTML to create a tabbed example, so you can switch between the examples, like this:

```HTML
<div class="tabs">
    <ul class="tabs-nav">
        <li>
            <a data-toggle="tab">Java</a>
        </li>
        <li class="active">
            <a data-toggle="tab">C++</a>
        </li>
    </ul>
    <div class="tabs-content">
        <div class="tab-pane" id="java">Java Code</div>
        <div class="tab-pane active" id="cpp">C++ code</div>
    </div>
</div>
```

I'm not sure how to enable syntax highlighting for the C++ and Java codes, since they're not treated as Markdown text (since by default, Markdown cannot be nested in HTML), but I'm sure there's a workaround for that, too.

Cheers,
Imre

**Comment by SamyPesse** [comment]
@soulmachine I'll add the language as a template variable in GitBook v3 (#1109).

In the mid time, here is a solution:

Create a `book.json` in each folder `java`, `cpp`:

For example, in the `cpp` folder:

```js
{
     "variables": {
         "lang": "cpp"
    }
}
```

**Comment by soulmachine** [comment]
@SamyPesse Your way works for me, thanks :+1: 

@nagim I tried your way, markdown doesn't allow to embed HTML code, so it doesn't work, but still thank  you
