### ISSUE TITLE
Error including a markdown file in parent path

### ISSUE THREAD

**Issue by soulmachine** [GitbookIO/gitbook#1128]
My book structure is as the folowing:

```
.
├── test.md
├── LANGS.md
├── book.json
├── java
│   ├── SUMMARY.md
│   └── chapter1.md
└── cpp
    ├── SUMMARY.md
    └── chapter1.md
```

The content of `LANGS.md` is quite simple:

```
* [Java](java)
* [C++](cpp)
```

I want to share the `test.md` file between `cpp` and `java`, so in one file such as `cpp/chapter1.md`, I have the following code:

```
{% include "../test.md" %}
```

It seems gitbook can recognize `..` but somehow it throws out the following error:

```
Template render error: (/mnt/hgfs/mybook/cpp/chapter1.md)
  Error: EACCESS: "/mnt/hgfs/mybook/test.md" not in "/mnt/hgfs/mybook/cpp" (In file 'chapter1.md')
```

What does this error mean? How can I include a markdown file in the parent path `../` ?

**Comment by manico** [comment]
@soulmachine 
Did you manage to solve this?
