### ISSUE TITLE
Desktop GitBook Editor and Local files in Dropbox/OneDrive/etc

### ISSUE THREAD

**Issue by nancym** [GitbookIO/gitbook#1129]
I'd like to use the Desktop GitBook Editor on all my devices (Windows and Mac) and be able to keep the files in sync with Dropbox (or OneDrive or some other non-git sync service). The default local root directory is `~/GitBook`. How do I specify a different root directory, e.g., `~/Dropbox/GitBook`? The ideal would be to be able to have a device-specific local root directory because my devices are not all set up the same. I.e., my Dropbox folder is not `~/Dropbox` on all my devices. Thanks for any tips!

**Comment by nagim** [comment]
You already have a repository online, hosted on either gitbook.com or on GitHub I guess. Both of them are platform independent. Then you just clone your central repo to both of your machine.
When you start the Editor, you can choose from your available repositories.

**Comment by nancym** [comment]
Actually in my scenario, I would like to work on my book locally before putting it out on GitHub or GitBook or any public space. It would be great if the Desktop GitBook Editor let users specify the local root of a book without having to use git (which I, unfortunately, don't yet know, but will eventually learn). I think this would open up GitBook to a lot of people who don't know git. It would be a multi-platform FLOSS gratis Dreamweaver :smiley:

**Comment by nagim** [comment]
Then on the startup screen of Gitbook Editor, choose **Import**, then choose your book in the local Dropbox folder. Do it on both Mac and Win. Next time, you need just click on it to open.

![image](https://cloud.githubusercontent.com/assets/16205115/12869247/2d151a0c-cd1a-11e5-865d-c84a342545ae.png)

**Comment by derekderaps** [comment]
`Import` copies the gitbook directory so would not accomplish what the OP requested. You could delete the ~/GitBook directory and then symlink ~/GitBook to your desired path.

**Comment by HaykoKoryun** [comment]
@derekderaps I just did that, and then added the `.git` stuff in the linked directory to the project's .gitignore
