### ISSUE TITLE
Documentation on Creating Custom Themes

### ISSUE THREAD

**Issue by bijanebrahimi** [GitbookIO/gitbook#1130]
I'm developing a compatible gitbook-cli using python. what I'm looking for is documentation of how to create/be compatible with already existing themes. is there any documentations/instructions to show the structure of variables (such as progress ans suchs) available to themes?

I know one way is to look in already existing themes (Which I did) but still there should be some kinda documentation somewhere!

Update: @SamyPesse Any progress on documentation you mentioned [here](https://github.com/GitbookIO/gitbook/issues/566)

**Comment by bijanebrahimi** [comment]
Seriously, No one to answer?

**Comment by SamyPesse** [comment]
Sorry for the late response, themes will be released with GitBook v3 (https://github.com/GitbookIO/gitbook/pull/1109).

The documentation is not yet complete: https://github.com/GitbookIO/gitbook/blob/3.0.0/docs/themes.md

Feel free to contribute by commenting the v3 PR.
