### ISSUE TITLE
Book-Wide AsciiDoc Attributes

### ISSUE THREAD

**Issue by nancym** [GitbookIO/gitbook#1131]
In my AsciiDoc `.adoc` files, I always want to use some attributes such as `:hide-uri-scheme:`. What's the best way to do this? I'm currently pasting the attributes I like in to the header of all my `.adoc` files, but I'm guessing there's a better way. Maybe with an include (content referencing) or maybe in `book.json`? Thanks for any tips!

**Comment by Mogztter** [comment]
> Maybe with an include (content referencing)

That could work but currently GitBook does not support `include` macro.

> or maybe in `book.json`

Yes, I think this is a good idea.
Asciidoctor attributes can be passed to the API and it would be nice to be able to define "user attributes" in `book.json`.
