### ISSUE TITLE
change Chinese default font to "nato-sans"

### ISSUE THREAD

**Issue by xdite** [GitbookIO/gitbook#1134]
Hi. the pdf on gitbook.com has Chinese font-type consistency issue  #532

I saw you use

## Chinese / Mandarin

* cns11643-kai
* cns11643-sung
* moe-standard-kai
* moe-standard-song

 
Would you consider switch to nato-sans  font family? ( the ultimate chinese font solution invented by google )

http://www.google.com/get/noto/#/family/noto-sans-hant

**Comment by SamyPesse** [comment]
We just improved the font on GitBook.com for chinese:

Left: new font
Right: old font

![screen shot 2016-04-02 at 10 10 20](https://cloud.githubusercontent.com/assets/845425/14225235/65ee5344-f8bb-11e5-84d0-31b01dfb63e8.png)
