### ISSUE TITLE
How to use varialbes in string interpolation?

### ISSUE THREAD

**Issue by soulmachine** [GitbookIO/gitbook#1135]
Suppose I have file `book.json` which defines a variable:

    {
         "variables": {
             "suffix": "java"
        }
    }

Now I want to use the variable `book.suffix` in my markdown files:

    {% codesnippet "./code/hello-world.{ book.sufix }", language="{ book.sufix }" %}{% endcodesnippet %}

I want it to be translated to:

     {% codesnippet "./code/hello-world.java", language="java" %}{% endcodesnippet %}

But the code above actually will throw out errors.

**Comment by nagim** [comment]
I think it actually depends on the `codesnippet` plugin, if it accepts variables.

**Comment by SamyPesse** [comment]
You can do:

```
{% codesnippet "./code/hello-world."+book.sufix, language=book.sufix %}{% endcodesnippet %}
```

**Comment by soulmachine** [comment]
@SamyPesse Thank you so much :+1:
