### ISSUE TITLE
MathJax / Chrome / Vertical bar

### ISSUE THREAD

**Issue by vhuber** [GitbookIO/gitbook#1138]
Hi there,

If i write a latex formula such as $$A$$, in chrome, it will be rendered with a vertical bar on the right, but not with Firefox.
Here an example where I have written: $$\frac{A}{m^3}$$ 
![capture d ecran 2016-02-12 a 09 44 30](https://cloud.githubusercontent.com/assets/2920150/13002248/4195e996-d16d-11e5-9a0a-d8ec7adcedeb.png)

I'm pretty sure that is linked to https://github.com/mathjax/MathJax/issues/1300 and can be solved switching to mathjax 2.6 instead of 2.5.

**Comment by jarodmeng** [comment]
I'm having the same problem. Has this been fixed?

**Comment by beader** [comment]
+1. I'm having the same problem too.

**Comment by Chris1221** [comment]
Ditto here, could we perhaps update the [plugin](https://github.com/GitbookIO/plugin-mathjax) and point it to the right cdn in `index.js`? I've never worked with publishing packages on `npm` before but maybe it's easy to do as a temporary workaround.
