### ISSUE TITLE
support for checkboxes

### ISSUE THREAD

**Issue by torsday** [GitbookIO/gitbook#1148]
i.e.

``` markdown
- [ ] not checked
- [x] checked
```

**Comment by nagim** [comment]
Are you trying it in markdown?
I think markdown does not support it natively.
In AsciiDoc, it works, I get the following output:

✓ checked
✓ also checked
❏ not checked

In markdown, try to use this [plugin](https://plugins.gitbook.com/plugin/todo).

Cheers,
Imre
