### ISSUE TITLE
Message "Error processing comments: Error" for empty inline comments is not clear

### ISSUE THREAD

**Issue by show0k** [GitbookIO/gitbook#1150]
If a user leave an empty inline comment on a html gitbook page, there is a a tricky javascript alert popup with the message "Error processing comments: Error" which is not understandable...

**Comment by jedwards1211** [comment]
I'm getting this error regardless, haven't even tried to create comments https://github.com/GitbookIO/gitbook/issues/1258

**Comment by akarve** [comment]
I'm seeing this as well. I have not added any HTML comments in my gitbook source. Screenshot attached.
![screen shot 2017-07-13 at 4 24 01 pm](https://user-images.githubusercontent.com/1322715/28191919-01b46bf0-67e8-11e7-8b86-40acdb35d9b9.png)
