### ISSUE TITLE
Can not install plugins

### ISSUE THREAD

**Issue by iamchathu** [GitbookIO/gitbook#1151]
I'm using gitbook editor and i try to install plugins from gitbook editor as well as via editing the book.json and then using cli. But both cases cli says plugin install was successfull without error

```
info: 1 plugins to install
info: No version specified, resolve plugin advanced-emoji
info: install plugin advanced-emoji from npm (gitbook-plugin-advanced-emoji) with version 0.0.1
gitbook-plugin-advanced-emoji@0.0.1 node_modules\gitbook-plugin-advanced-emoji
info: >> plugin advanced-emoji installed with success

```

but when i try to gitbook serve of build it give me an error.

```
info: loading book configuration....OK
info: load plugin advanced-emoji ....ERROR
info: load plugin gitbook-plugin-highlight ....OK

Error: Error loading plugins: advanced-emoji. Run "gitbook install" to install plugins from NPM.

```

I tried installing

`npm install gitbook-plugin-advanced-emoji`

but still same error come.

**Comment by SamyPesse** [comment]
This error is also thrown when the plugin is invalid (js error during loading), GitBook v3 will improve this error message. 

try in a Node REPL (`node` command in the directory of your book):

```
require('gitbook-plugin-advanced-emoji')
```

**Comment by iamchathu** [comment]
```
C:\Users\Chathu\GitBook\Library\Import\basic_rummy\node_modules\gitbook-plugin-a
dvanced-emoji\index.js:16
                        page.sections.each(function (section)) {
                                                             ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
>

```

**Comment by SamyPesse** [comment]
This is an error in the `advanced-emoji` plugin, you should post the issue to the associated repository.

**Comment by iamchathu** [comment]
But I did again npm install and there is no error

```
{ website: { assets: './assets', js: [], css: [ 'emojify.css' ] },
  blocks: {},
  hooks: { 'page:before': [Function] } }
>
```

**Comment by iamchathu** [comment]
If i install via `npm install gitbook-plugin-advanced-emoji`

and try with node repl to include it there is no error

After that I tried to run gitbook build then it gave an error

```
info: loading book configuration....OK
info: load plugin gitbook-plugin-advanced-emoji ....ERROR
info: load plugin gitbook-plugin-highlight ....OK

Error: Error loading plugins: gitbook-plugin-advanced-emoji. Run "gitbook instal
l" to install plugins from NPM.
```

After that i run gitbook install

after that i tried again to build same error came. Then i try to require it via Node REPL but the it gave the error

**Comment by jebeck** [comment]
@iamchathu I think the difference between your results is that when you're doing `gitbook install` without a version you're getting the 0.0.1 of the plugin, but with `npm install` you get 0.1.6. If you specify the version in book.json as follows you should be able to successfully `require('gitbook-plugin-advanced-emoji')` in the repl:

```
{
    "plugins" : ["advanced-emoji@0.1.6"]
}
```

Unfortunately even having figured out this bit of inconsistent behavior, I'm getting the same error even making sure I have 0.1.6 installed and can `require` it successfully in the repl! Which makes it seem like it is *not* a problem with the plugin after all...

**Comment by iamchathu** [comment]
Got fixed by removing gitbook and gitbook cli and installing it again both.

**Comment by jebeck** [comment]
@iamchathu I don't have gitbook installed, only the CLI. Can you explain? I've uninstalled the CLI and reinstalled many times, and that's not helping for me.

**Comment by iamchathu** [comment]
List installed gitbbok versions:

`$ gitbook ls`

**Comment by jebeck** [comment]
That does list the CLI @iamchathu...there isn't a separate install for "gitbook" - the CLI is under the alias `gitbook`.

Anyway, it looks like I have a weird local environment issue. Still haven't figured it out for me, but my coworker can serve & build successfully with 1.0.1 of the CLI and 0.1.6 of the plugin (in node v0.12.x).

**Comment by jebeck** [comment]
Just as an update, the only thing that fixed this issue for me was the fact that I clean installed El Capitan on my system last weekend(!)

**Comment by iamchathu** [comment]
Glad to hear you fixed the issue.BTW Gitbook CLI and gitbook is two different things.

**Comment by jebeck** [comment]
Yeah I noticed GitBook being installed the first time I ran the CLI to serve my docs after reinstalling OS. I think the fact that the GitBook install is global and unconnected to the CLI install/uninstall is at the root of the problem. Comparing with a coworker, I had a really old GitBook (before the OS reinstall, which BTW was for other reasons!), and I saw no way to change that...
