### ISSUE TITLE
How to change font of PDF

### ISSUE THREAD

**Issue by iamchathu** [GitbookIO/gitbook#1153]
I need to change PDF font to Computer Modern Font. How to do that?

**Comment by andywenk** [comment]
This is not tested. But as far as I know, you can add the following to book.json

    "styles": {
        "website": "styles/website.css",
        "ebook": "styles/ebook.css",
        "pdf": "styles/pdf.css",
        "mobi": "styles/mobi.css",
        "epub": "styles/epub.css"
    }

Try to change the font on styles/pdf.css.

**Comment by yashaka** [comment]
@iamchathu, did you succeed?

**Comment by yashaka** [comment]
@iamchathu, did you succeed?
