### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by gristel** [GitbookIO/gitbook#1154]
Hi all.

I'm sorry if this has been asked before somewhere, but there's so much 'clutter' about styling a gitbook all over the net, so I thought I'd ask for information about the latest version here.

My question is quite simple, but I can't find a decent answer anywhere:
Are there elements that can't be styled?

In my case:
I'm trying to style `<hr>` but no matter what I try, I doesn't change.

Any information about this would be gratefully appreciated!

**Comment by nagim** [comment]
Hi,

How did you try it (and what style).
I managed to style it somewhat with CSS (not fully, for examle, no colors).

**Comment by gristel** [comment]
I tried styling the ```<hr>``` in the styles/website.css but no luck.
Right now i'm in the process of creating a new 'theme' by adapting all the .less stylesheets from the original theme into a new website.css file.
I will keep you posted here on any progress.

**Comment by noerw** [comment]
The [documentation](http://toolchain.gitbook.com/themes/) is really unclear (the key sentence is not finished..?!) about how to extend a style.
Where would i place custom stylesheets, without the need to create a new theme?

**Comment by nagim** [comment]
For me, placing a `website.css` in the *styles/* folder does the trick.
The key is to correctly define the classes in the CSS file that corresponds to the ones used in your book.

For example, I use 
```css
.book .book-body .page-wrapper .page-inner section.normal code {font-size: 100%;}
```
to increase font size in code tags.

Hope it helps.

**Comment by noerw** [comment]
well, and how "do i point at it in my `book.json`"?

**Comment by nagim** [comment]
```json
"styles": {
  "website": "styles/website.css"
}
```

**Comment by noerw** [comment]
does not work either with v3.0.3 and v2.6
https://github.com/GitbookIO/gitbook/issues/1348 seems related

**Comment by nagim** [comment]
@noerw, I looked at your website css, and instead of using just .glossary.term, please try this:
```css
.book .book-body .page-wrapper .page-inner section.normal a.glossary-term { }
```
