### ISSUE TITLE
Specify default theme?

### ISSUE THREAD

**Issue by kolodny** [GitbookIO/gitbook#1155]
I want to use "night" as the default theme for the gitbook, is there any way to do this?

**Comment by kolodny** [comment]
It seems that you can specify this in the book.json` file as follows:

```json
{
  "pluginsConfig": {
    "fontSettings": {
      "theme": "night"
    }
  }
}
```

**Comment by erlend-sh** [comment]
I tried this and it doesn't appear to be working.

https://erlend-sh.gitbooks.io/first-testbook/content/
https://github.com/erlend-sh/first-testbook/blob/master/book.json

**Comment by morizyun** [comment]
@erlend-sh I think it is right:

```json
{
  "pluginsConfig": {
    "fontsettings": {
      "theme": "night"
    }
  }
}
```
