### ISSUE TITLE
Adding a new generator in a plugin

### ISSUE THREAD

**Issue by Noamyoungerm** [GitbookIO/gitbook#1156]
I have a rather odd use-case where I'm required to embed a gitbook inside a larger application.

As part of that, I want to be able to add a custom generator to the gitbook build process in order to avoid cruft but still allow content editors to use the gitbook editor.

Is there any support for adding generators in a plugin?

**Comment by SamyPesse** [comment]
What kind of content do you want to generate ? There is already a json generator if you want to integrate contents into another app.

[GitBook v3](https://github.com/GitbookIO/gitbook/pull/1109) includes custom theming, if your goal is to generate some custom HTML for your application.

**Comment by Noamyoungerm** [comment]
I want to map each page to an HTML snippet (something like `page.sections.map(x => x.content).join('\n');`), and also output JSON (though I'm open to HTML) for the sidebar.

I thought about simply using the JSON output and parsing it for each page, and I'll do that if I must, but I'd prefer to directly output a simple format to use on the other side.

**Comment by SamyPesse** [comment]
Ok themes should be the right solution. This will be available with GitBook v3, an alpha will be released at the end of the week or beginning of next week.

You can take a look at an example of theme: https://github.com/GitbookIO/theme-official

Basically your `page.html` should be:

```
{{ page.content|safe }}
```

And you'll get only the content of the page.

BTW: the json format is changing with GitBook v3.

**Comment by Noamyoungerm** [comment]
OK - I think I've managed to get this working similarly to what you said. Thanks
