### ISSUE TITLE
Add tags for each chapter

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1158]
I found it's hard to find something we have write before,is it possible to include tags for chapter or lines,just like a blog post,that we can find some post more quickly.

**Comment by nagim** [comment]
You can use metadata for that.
In AsciiDoc, you use the `:keywords:` after the title, like this:

```asciidoc
= AsciiDoc Home Page
// Web page meta data.
:keywords:    AsciiDoc, DocBook, EPUB, PDF, ebooks, slideshow, slidy, man page
```

I don't know if it's supported in markdown, but it's worth a [try](http://hiltmon.com/blog/2012/06/18/markdown-metadata/).

Is this what you wanted?

**Comment by billryan** [comment]
@EasonWang01  I wrote a plugin to achieve this goal. Maybe it can help you.

https://github.com/billryan/gitbook-plugin-tags
