### ISSUE TITLE
OSX El Capitan Timed Crashes

### ISSUE THREAD

**Issue by rblades** [GitbookIO/gitbook#1160]
I am using the desktop app (version 4.2.3) for Mac El Capitan (version 10.11.3). I experience crashes that seem timed: about every 20 mins the screen goes blank and I am forced to reopen GitBook.

Anyway I could view an error log on my machine?

Cheers

**Comment by HeliumSquid** [comment]
To view the error log files, you must open the Console from the Application->Utilities.
