### ISSUE TITLE
best way to write docs for multiple libraries?

### ISSUE THREAD

**Issue by davis** [GitbookIO/gitbook#1161]
Hi, I am writing docs for an API and it's libraries.

The text in the docs would be the same, but with different code samples (js, python, php, etc). Should I use the LANGS.md to accomplish this? What other DRYer methods are there?

Thanks!

**Comment by nagim** [comment]
Hi,

You could check this (#1127), maybe it's close to what you want to achieve.

**Comment by davis** [comment]
ah, thanks! hopefully something nice can come in v3

**Comment by AaronO** [comment]
@davis, No you shouldn't use `LANGS.md` that's intended for translations into multiple human languages.

What you want is one document but with a widget that can render code samples from different languages. You can accomplish that through a plugin (I don't think one exists to do specifically that, but it shouldn't be too hard to write).

**Comment by nagim** [comment]
Aaron is right, and I found a [plugin](https://plugins.gitbook.com/plugin/codepen) that does just that.

**Comment by davis** [comment]
hmm, i didn't want to use codepen, .. in an ideal world i could do something like

~~~~~~
# Some documentation header

Some doc text. This is how you use the `edit()` function:

``js
edit('hello', {save: true});
``

``py
edit('hello', save=True)
``

~~~~~~

(I used double ticks instead of triple because I don't know how to escape them)

**Comment by davis** [comment]
and they could cycle through the different languages
