### ISSUE TITLE
v3.0.0 fails when it has spaces in the paths

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#1165]
On 2.x.x pages paths could have spaces and non-ASCII characters on their name and URL, but on v3.0.0-pre1 generation of the book fails, having 404 URLs when serving the site since the spaces are not urldecoded and Unicode characters are mangled, and generating a PDF only the summary is rendered.

**Comment by SamyPesse** [comment]
Can you post an example of SUMMARY so that I can add a test for it? Thank you

**Comment by piranna** [comment]
I've just added you as collaborator of the repo of my thesis, where I have problems. It's a private one because is not already published, this way you can get access and check it yourself in a "real world" project :-)

**Comment by piranna** [comment]
Also the external plugins are not working, but you can check this problem just by removing the `plugins` entry on the `book.json` file.

**Comment by dorako321** [comment]
i prepared 2 files `foobar.md` and `foo bar.md`. 

and i wrote SUMMARY.md

```
* [foobar](./foobar.md)

* [foo bar](./foo bar.md)
```

and i confirmed what i get an error when I click `foo bar.html` link.


then, i built book in debug mode. 

```
debug: copy asset foo bar.md
```

I think .md file shouldn't be treat as asset.

**Comment by piranna** [comment]
Thank you @dorako321 :-)

**Comment by SamyPesse** [comment]
Thanks guys! My latest commit (https://github.com/GitbookIO/gitbook/commit/4aa66338fce505566a2fe6ba6aee79ddf3f656a2) probably fix it, but I'll add some unit tests.

I'll release a new version later today.

@piranna Plugins compatibility will be improved during the pre releases (I want to make most plugins work without changes required on their side).

**Comment by piranna** [comment]
> @piranna Plugins compatibility will be improved during the pre releases (I want to make most plugins work without changes required on their side).

I think I was a bit quick, I say about the RC1 and since I've finished my thesis and there was some important bug fixes like the ones related to the glossary I wanted to use it... :-P If there will be a plugins legacy mode then I'll wait until 3.0 gets officially released :-)

**Comment by gsklee** [comment]
This is still the case. I added a new article and pointed its path to `1. Into Programming/Day 1`, and the book failed to resolve this path.
