### ISSUE TITLE
v3.0.0-pre1 rST parse error

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1166]
Hi,

I ran a build with the new release and it threw an error for reStructuredText files:
`ParseError: Parsing Error: Can't parse file "sdk.rst"`

Cheers,
Imre

**Comment by SamyPesse** [comment]
RST support is not added to GitBook v3 (https://github.com/GitbookIO/gitbook/blob/master/lib/parsers.js#L10).

RST is not used by a lot of people, not supported in the editor, depends on a binary, etc.

Why are you using RST instead of Markdown or AsciiDoc?

**Comment by nagim** [comment]
I left that file in for testing, I use AsciiDoc.
That's OK, I wasn't aware that it was excluded, thought it was just a hiccup and you should know about it.
