### ISSUE TITLE
Broken links in web view

### ISSUE THREAD

**Issue by larsyencken** [GitbookIO/gitbook#1171]
I came back to a book of mine, and found that subchapter styles had become broken.

The layout is like:

```
mychapter/README.md
```

And in `SUMMARY.md`

```
- [MyChapter](mychapter/README.md)
```

If you then run:

`gitbook serve`

and visit `http://localhost:4000/mychapter/index.html` then you get a page with a broken stylesheet. It's broken because it tries to reference `http://localhost:4000/_book/gitbook/style.css`, but it should instead be generating the link `http://localhost:4000/gitbook/style.css`.

**Comment by SamyPesse** [comment]
What command di you run ? in which folder ?

Can you paste the output of:

```
gitbook --version
gitbook versions:current (or gitbook current)
```

**Comment by larsyencken** [comment]
It fails for me with:

```
$ gitbook --version
2.1.2
$ gitbook current
GitBook version is 2.6.7
```

But I got things working again by adding to my `book.json`:

```
"gitbook": "3.0.0-pre.3"
```

Now it works just fine. It must be a bug you guys have already fixed. Thanks for following up!
