### ISSUE TITLE
3.0.0-pre.3 : ePub, mobi, PDF generators not outputting to correct location

### ISSUE THREAD

**Issue by nateberkopec** [GitbookIO/gitbook#1172]
`gitbook -v 3.0.0-pre.3 epub . some_other_dir/book.epub` wrote to the `some_other_dir` directory in v2.x. It does not in the prerelease - instead, it writes the file to the root of the book directory. JSON and web generators are not affected.

**Comment by SamyPesse** [comment]
Thanks, fixed in master

**Comment by nateberkopec** [comment]
:+1: Thanks for the quick fix - on a Saturday, no less!

**Comment by nateberkopec** [comment]
Can confirm that this is fixed in pre5.
