### ISSUE TITLE
Variable to access generator target?

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1175]
Is there a way to check what the current build target is? Something like

```less
{% if target.website %}
Welcome to the online documentation!
{% elif target.pdf %}
Welcome to the PDF documentation!
{% else %}
Welcome to the documentation!
{% endif %}
```

**Comment by SamyPesse** [comment]
With GitBook v2, it's possible using `gitbook.generator` (https://github.com/GitbookIO/gitbook/issues/120).

But with GitBook v3+, we are switching it under `output.name` (http://toolchain.gitbook.com/templating/variables.html).

`gitbook.generator` will still work, but is deprecated.
