### ISSUE TITLE
Unable to set custom domain

### ISSUE THREAD

**Issue by shinenelson** [GitbookIO/gitbook#1176]
Is it just me or can't anyone find the option to set custom domains anymore?

I referred to [this help article](http://help.gitbook.com/platform/domains.html), but even the screenshot on the page is different from the settings page on the new gitbook.com dashboard.

Was setting custom domains removed, disabled?

(or is it disabled specifically for individuals/organizations in the Free pricing plan? Even though the [help article](http://help.gitbook.com/platform/domains.html) said **a free feature on GitBook**)

**Comment by nagim** [comment]
Hi,

It's still there.
Follow these steps:

1. Sign in to gitbook.com and select your book.
2. You should see the following screen, click on the **Settings** button (red circle):

![image](https://cloud.githubusercontent.com/assets/16205115/13632631/efa9aed2-e5ea-11e5-8dea-56c7cecd0ce0.png)

3. In the **Settings** page, you should see, the menu below. Click on the **Domains** tab (again, red circle).

![image](https://cloud.githubusercontent.com/assets/16205115/13632685/36af1024-e5eb-11e5-96e5-7a26db21c35e.png)
 
4. Specify your domain.

Hope it helps.

Imre

**Comment by shinenelson** [comment]
Aha. I was looking in the wrong place. I was looking in the account settings.

Thanks for pointing it out @nagim.

The help article should be updated accordingly anyway.
