### ISSUE TITLE
Non-style includes for every page (website target)?

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1179]
Is there a way to include e.g. static content to multiple/all generated pages? Something like:

book.json

``` json
{
  "variables":
  {
    "lastUpdate": "2016-03-10T14:15:00.000Z"
  }
}
```

header.md

``` html
{% if book.lastUpdate %}
  <div>Last updated on {% book.lastUpdate %}</div>
{% endif %}
```

`<div>Last updated on 2016-03-10T14:15:00.000Z</div>` would need to appear above every page in all chapters in this example, as actual HTML of course (not escaped).

I don't want to `{% include "header.md" %}` manually on every page. Couldn't find anything in the documentation.

**Comment by nagim** [comment]
This is an interesting question and not just about static content, but also attributes (like audience, etc.), which could be used for single sourcing.
@SamyPesse, if I recall right, v3 support YAML frontmatter, maybe it could be used for this (define site-wide variables, etc.)?

**Comment by Simran-B** [comment]
To add some background: the actual use case for me would be to add a header, that allows users to switch between different (git)books and versions (it's an API documentation), and there's currently also a Google Custom Search search field up there, because the built-in search did not work well enough for our kind of content.

I would like to have the link to the currently shown book highlighted, to give a visual clue which part of the documentation you are currently looking at.

Our current implementation injects HTML via a JS script, but it's not that great because it disappears briefly on switches between books: https://docs.arangodb.com/ (*Docs* and *Cookbook*)

I'm open for suggestions. The problem with multiple gitbooks is, that links between different books do not work unless you use `.html` as extension, but there will be warnings/errors during build, because there may not be a generated `.html` from the original `.md` yet (and `.md` can't be used in links, because the remote file will be outside of the local book's spine).
