### ISSUE TITLE
Changes to my gitbook are being applied by another user

### ISSUE THREAD

**Issue by evancohen** [GitbookIO/gitbook#1182]
First off, who is @Nikitaw99? For some reason all of the changes applied to my repository are being applied on behalf of that user.

Screenshot of gitbook commit history:
<img width="1004" alt="screen shot 2016-03-11 at 9 32 44 pm" src="https://cloud.githubusercontent.com/assets/1198365/13721125/06ba9bbc-e7d1-11e5-8587-963ab21bfe6f.png">
Screenshot of same commit history on GitHub:
<img width="955" alt="screen shot 2016-03-11 at 9 33 08 pm" src="https://cloud.githubusercontent.com/assets/1198365/13721126/06bc3a30-e7d1-11e5-81aa-fa9ce5bbdbe2.png">

Pretty strange...

**Comment by nagim** [comment]
Have you checked the git config file of your repo? What's the username there?

**Comment by Nikitaw99** [comment]
What? I never actually made any changes to your gitbook... This is pretty strange to me...

**Comment by evancohen** [comment]
It's a private repository, that's probubly why. It's super bizarre - all of my changes are being associated with your user account. 

@nagim all commits coming from my machine are correctly attributed. The attribution only gets messed up when using the gitbook editor.

**Comment by AaronO** [comment]
@evancohen @Nikitaw99 That is very strange indeed. There's no way the editor magically came up with `Nikitaw99`'s email, so it must come from somewhere. 

If builds show up correctly on `gitbook.com` and in `git log`, it seems to be an issue with `github.com`, GitHub looks for a user matching the committer's email address when rendering commits. Is it possible that somehow @Nikitaw99 has one of your email addresses assigned to his GitHub account ?

Could you share the output of a `git log` on the repo or your gitbook ID ?

**Comment by Nikitaw99** [comment]
@AaronO  I have only 2 emails assigned to my account: 
`manahovman@gmail.com` and `anonymous@gitbook.com`

Also, how do I find my gitbook id?

**Comment by AaronO** [comment]
@evancohen @Nikitaw99 Ok this makes so much more sense.

@evancohen Are you using the GitBook desktop editor without authentication by any chance ? If the editor doesn't have an email for your user, it will commit them as `anonymous@gitbook.com`, builds on `gitbook.com` are identified as you since they come through the webhook which has your GitBook account's auth info.

@Nikitaw99 Could you remove the address `anonymous@gitbook.com` from your GitHub account ? That would prevent other people's commits as coming up from you and being logged as `anonymous@gitbook.com` instead.

Does that make sense to both of you now ?

**Comment by Nikitaw99** [comment]
@AaronO done, removed that email.

**Comment by evancohen** [comment]
@AaronO I was using the online editor, not the desktop editor - but there was no email address associated with my GitBook account (I signed up with GitHub). I've added it now.

You might want to create an `anonymous@gitbook.com` GitHub account just so people aren't confused by this in the future.

Thanks to both of you!

**Comment by ruchern** [comment]
On top of this, are there anyways to set Gitbooks to GPG sign commits?
