### ISSUE TITLE
Recipe for Open Source Documentation?

### ISSUE THREAD

**Issue by justin808** [GitbookIO/gitbook#1184]
@SamyPesse Is there any recipe for open source projects on best practices for gitbook integration?

I'm looking to integrate https://github.com/shakacode/react_on_rails/ with gitbooks.

My requirements:
1. Documents stored in `/docs` subdirectory of my github repo.
2. Any viewer can easily make edits and have edits go through the normal PR process.
3. Easy for any viewer to see versions of docs at different tags (for old releases) or for branches, to preview before accepting a PR.

Nice to have:
1. Ability to use the gitbook editing tools seamlessly with a branch used for a pull request for a doc change.

**Comment by SamyPesse** [comment]
With GitBook v3, we are working on a lot of improvements for the Documentation use case:

- Ability to use a `docs` folder (for example: [GitBook itself](https://github.com/GitbookIO/gitbook/tree/master/docs)).
- [Theming and layout customization](http://toolchain.gitbook.com/themes/)
- More customization possible for plugins
- Better search plugins (for example one supporting Algolia as a search backend)

[toolchain.gitbook.com](http://toolchain.gitbook.com/) itself is a GitBook hosted on GitBook.com

I'll write an article on the documentation about this, but the recipe will look like:

1. Create a book on GitBook.com linked to the GitHub repository
2. Create a `docs/` folder containing the project documentation
       - Do not use a branch specific to documentation
3. Write a `book.json` and `book.js` ([for example here is the one for the GitBook documentation](https://github.com/GitbookIO/gitbook/blob/master/book.js))

Main contributors of the project can use the web editor on GitBook.com (it'll edit the GitHub repository directly).
External contributors will be able to use their code editor to edit the markdown or the desktop editor.

(The editor does not support GitBook v3 yet).

**Comment by justin808** [comment]
@SamyPesse Thanks! Should we wait until you get the documentation on this?

We already have some of this setup for https://github.com/shakacode/react_on_rails/.

In your above comment you probably mean: Write a `book.json` **OR** `book.js`

**Comment by justin808** [comment]
@SamyPesse What do we need in our package.json, per this line from `book.js`:

```js
var pkg = require('./package.json');
```

**Comment by SamyPesse** [comment]
Yes, it's `OR` (I fixed it).

Your `book.json` can be simpler:

```js
{
    "root": "./docs"
}
```

We are including `package.json` in our case, so that we can use the version as a variable in the content.
