### ISSUE TITLE
"Pointing file" to filename with subfolder breaks build on v3.0

### ISSUE THREAD

**Issue by erlend-sh** [GitbookIO/gitbook#1186]
This only occurs when building with v3.0. You can see this bug in action here:

https://erlend-sh.gitbooks.io/jmewiki/content/

1. Click on any page in the Beginner chapter
2. Now click on any page
3. `_book` is now added to all links, so they break.

This only happens to pages in sub-folders, like this one:
https://github.com/erlend-sh/jmewiki/blob/master/beginner/hello_asset.md

Pages in the root folder are not affected, like this one:
https://github.com/erlend-sh/jmewiki/blob/master/sample_page.md

I've confirmed I can fix this problem by setting version back to v2.6.7 and rebuilding.

**Comment by SamyPesse** [comment]
I don't think it's happening with latest 3.0.0 pre versions. @erlend-sh can you confirm?

**Comment by erlend-sh** [comment]
Yup, seems fixed!
