### ISSUE TITLE
Unexpected Error when trying to load your book: Error Code 0:

### ISSUE THREAD

**Issue by shinenelson** [GitbookIO/gitbook#1189]
![screenshot from 2016-03-22 16-56-59](https://cloud.githubusercontent.com/assets/4771718/13950112/23f5bc9e-f04f-11e5-84d4-a46566b67586.png)

What could be the cause of this issue here?

**Comment by AaronO** [comment]
@shinenelson Our SSL cert expired a few minutes ago, they are now renewed and live in production, sorry for the inconvenience.

**Comment by kantlove** [comment]
This happens to me again today.
