### ISSUE TITLE
There was an error checking for updates.

### ISSUE THREAD

**Issue by thecristen** [GitbookIO/gitbook#1190]
When I open Gitbook Editor

> connect ECONNREFUSED 50.17.249.251:80

(the exact IP is different each time)

I suspect Gitbook doesn't like my proxy setup. I believe this is also what's interfering with me being able to Login using Gitbook. Note I can still create local books just fine.

**Comment by josephkandi** [comment]
Also they need be a setting to ignore updates, even if i cancel the dialog box, it keeps popping up, its annoying.

**Comment by martint028** [comment]
I meet this issues too.

**Comment by AaronO** [comment]
@martint028 Are you behind a proxy of sorts ? (corporate, school or state controlled)
