### ISSUE TITLE
page level variables

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1191]
Hi,

Is it possible to define page level variables? Or define a general variable and then override it on the pages I want to use a different value?

I would like to construct general includes, to be reused with minimal differences (for example, different product names) in multiple pages.

Thanks,
Imre

**Comment by SamyPesse** [comment]
This is possible with GitBook v3 and [YAML header](http://toolchain.gitbook.com/pages.html):

```
----
myvar: "Hello World"
----

# My Page

{{ page.myvar }}
```

**Comment by nagim** [comment]
Is it supported with AsciiDoc, too?
Do we have something similar in 2.x.x.?

**Comment by SamyPesse** [comment]
Yes it'll work with Asciidoc.

With GitBook v2, you can use `{% set myVar = "value" %}`, it'll be bind to the context of the page:

```
{% set myVar = "value" %}

This is {{ myVar }}
```

**Comment by nagim** [comment]
Thanks a lot!
