### ISSUE TITLE
Escaping `{{ ... | ... }}` syntax

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/gitbook#1193]
This syntax is not properly escaped. To reproduce, `gitbook init` and put this in `README.md`:

``````
# Introduction

```
{{ abc | xyz }}
```
``````

```
Template render error: (book/README.md)
  Error: filter not found: xyz
```

**Comment by laurelnaiad** [comment]
This is going to crop up a lot, as that syntax is common angular2 code. Is there a workaround for the time being?

**Comment by RobScottNet** [comment]
Using the GitBook [template escaping syntax](https://help.gitbook.com/format/templating.html) was a viable workaround for me.

```
{% raw %}
  this will {{ not be processed }}
{% endraw %}
```

**Comment by einsty** [comment]
To add more complexity to this case, i am working with content references and including README files from downstream projects that have the same issue as @Soreine had mentioned.  I understand that the GitBook template escape might work... but now I have to clutter my downstream READMEs with Gitbook syntax that shows up in Github README view... and that isn't cool.

**Comment by cmacdonnacha** [comment]
Any update on this issue? I'm getting this error: 

{code}Error: filter not found: translate{code}

with this code

{code}
```
<input type="text" placeholder="{{ 'Username' | translate }}" />
```
{code}
