### ISSUE TITLE
Markdown image URLs malformed in v3.0.0-pre.5

### ISSUE THREAD

**Issue by wildlyinaccurate** [GitbookIO/gitbook#1195]
I have some images in [my README.md](https://raw.githubusercontent.com/wildlyinaccurate/plait/master/README.md) like this:

```markdown
![stability-unstable](https://img.shields.io/badge/stability-unstable-yellow.svg?style=flat-square)
```

When these are compiled with v3.0.0-pre.5, the URL is missing a slash:

```html
<img src="https:/img.shields.io/badge/stability-unstable-yellow.svg?style=flat-square" alt="stability-unstable">
```

You can see the results in the [compiled README.md](https://github.com/wildlyinaccurate/plait/blob/2cdc3f466d514a01963e3393e8533442045a72bc/index.html#L468-L471).

**Comment by Jinjiang** [comment]
+1 I suffer the same. It's really terrible...
