### ISSUE TITLE
Syntax highlighting, C++ and parentheses within parentheses

### ISSUE THREAD

**Issue by mottosso** [GitbookIO/gitbook#1196]
Parentheses within parentheses throws the highlighter, both in the preview panel and in the final rendered page.

This works.

``` cpp
#include "test.h"
Test test(test)
```

This does not.

``` cpp
#include "test.h"
Test test(test())
```

The latter seemingly disables highlighting on the entire fenced block.

Ubuntu 15.10 and Windows 8 under Chrome.

**Comment by ShalokShalom** [comment]
Still the case?
