### ISSUE TITLE
Publish from a GitHub branch

### ISSUE THREAD

**Issue by minxomat** [GitbookIO/gitbook#1197]
Hi!

Much like GitHub Pages, I wish there was a way to publish from a single branch. An example:

- There's a GitHub repo foo/bar.
- A new gitbook is created 

Now, in order to manage the gitbook using a Git**Hub** repo, you'd have to create a *new* GitHub repo and sync it with your GitBook.

What I have in mind is a GitBook that syncs with GitHub, but only affects a single branch, so your GitHub repo looks something like this:

- foo/bar:`master` contains the code
- foo/bar:`gh-pages` contains the website (e.g.)
- foo/bar:`docs` contains the GitBook (i.e. what is now in the master branch of a GitBook repo)

This should be fairly easy to do. The GitHub syncing code is already in place and works splendid. So right where you'd now put your Git**Hub** repo link in your GitBook settings, there would be another input to set the specific *branch* to sync to (since `master` will most likely contain the code).

**Comment by SamyPesse** [comment]
This is already possible, GitBook.com can be configured to build only a specified branch:

- Create a new book linked to a GitBook
- Then in the book's settings:
    - Select only the branch `docs`
    - Also select it as a default branch
