### ISSUE TITLE
NoURLProtocolError: Protocol is required

### ISSUE THREAD

**Issue by kyrylkov** [GitbookIO/gitbook#1199]
My gitbook.com hosted GitBook stopped updating with the following error message:

> NoURLProtocolError: Protocol is required

There is no additional info in the logs.

How do I fix it?

**Comment by danedang** [comment]
the same error message.

had you solved the problem?

**Comment by sayidly** [comment]
the same error message, anyone knows how to solve it?

**Comment by sayidly** [comment]
Solved the problem. The issue happened because I use the plugin "sitemap", and the plugin **MUST** have the hostname something like this:
```
"sitemap":
        {
            "hostname": "https://example.com"
        }
```
You cannot leave empty or use `#`.   
In my case, I use `#`,  when I run `gitbook serve`, the error shows.

> NoURLProtocolError: Protocol is required
