### ISSUE TITLE
Add support for Python exercises

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#12]

**Comment by kernc** [comment]
@SamyPesse can you explain this issue's resolution? Are Python exercises supported now?

**Comment by SamyPesse** [comment]
Sorry I was starting cleaning up old issues. Since GitBook v2, exercises are done using an external plugin: https://github.com/GitbookIO/plugin-exercises

Python doesn't work, if somebody wants to make a PR, it should be on this plugin (and not GitBook itself).
