### ISSUE TITLE
Cannot get anchors working in SUMMARY.md

### ISSUE THREAD

**Issue by salfej** [GitbookIO/gitbook#1200]
Hello all,

I'm having trouble getting anchors to work in our gitbook. We're building using 3.0.0-pre.5, where anchors should be native, but I can't seem to get them working. We have lots of definitions, but we don't want to use the Glossary since many of the definitions are length and categorized by groups already. We're using it like this in our SUMMARY.md
```
* [File 1](test_book/sec_one.md)
  * [Subsection 1](test_book/sec_one.md#subsection)
```
This isn't working for us, but using something similar in another file like sec_two.md:
```
This is a link to [Subsection 1](sec_one#subsection) in File 1.
```
will work just fine. Is there something that I'm missing with the Summary? I thought anchors in the SUMMARY.md were supposed to be native in 3.0.0-pre-5. I've looked through all of the documentation, but the only one mention of anchors hasn't been enough to help me figure out this issue. 

http://toolchain.gitbook.com/pages.html#anchors

**Comment by Phenitei** [comment]
Same problem here. I also tried moving files at the same directory level to check if it wasn't a problem with linking across directories but that doesn't seem to be the case. I also remark that in the documentation [here](https://help.gitbook.com/format/chapters.html) there is no mark of being able to put anchors in the summary. Is this a bug or a missing future?

**Comment by salfej** [comment]
Well, we uninstalled node modules, uninstalled gitbook 2.6.5, so 3.0.0-pre.5 was the only available version, updated to node 5.x, reinstalled node modules, and served up our book again, and it's now recognizing anchors in the summary, but they won't scroll to the proper position in the referenced file, similar to this issue. https://github.com/GitbookIO/gitbook/issues/1163

**Comment by SamyPesse** [comment]
It should be working fine with latest pre versions.

**Comment by DrSensor** [comment]
not work with the latest gitbook :cry:
