### ISSUE TITLE
Support of git-lfs in gitbook.com

### ISSUE THREAD

**Issue by show0k** [GitbookIO/gitbook#1201]
[Git lfs](https://git-lfs.github.com/) is a git extension which allow to track large binary files (like pictures or video for documentation purpose) without having them in the git tree. Files are stored in the git tree as a text file with an HTTP link to the real file, and it is automatically downloaded with a `git pull` or `git clone` if git-lfs is setup correctly.  
Nowaday, if we use git-lfs with with gitbook.com builder, git-lfs tracked files are not fetch correctly.

**Comment by silviogutierrez** [comment]
Any chance of this getting implemented? Support for this would be tremendous: in the same repo as the code, we could have docs *and* corresponding large attachments (spreadsheets when needed, emails, etc) without blowing up the repo size. All versioned nicely.

**Comment by SamyPesse** [comment]
@silviogutierrez 

We'll soon release a brand new version of GitBook (https://beta.gitbook.com), and with the way the GitHub integration works on this new version, support of Git-LFS will not be needed, but **the large files stored on the LFS will works just fine** !

**Comment by silviogutierrez** [comment]
That's great new! Just a minor note: we can't actually use github.com and point our docs to our internal Atlassian Stash repo. I hope this pattern still works, as the Editor is super helpful.
