### ISSUE TITLE
How can I collapse directory?

### ISSUE THREAD

**Issue by tsai1993** [GitbookIO/gitbook#1205]
![firefox_screenshot_2016-04-02t01-44-21 448z](https://cloud.githubusercontent.com/assets/7903661/14223746/d3b2b98c-f8b7-11e5-8230-c30c9fbb483d.png)

I want to know how to collapse directory like that. I didn't find the answer on the documentation.

**Comment by nagim** [comment]
Hi,

It's a plugin ([expandable-chapters](https://plugins.gitbook.com/plugin/expandable-chapters)).

Cheers,
Imre

**Comment by tsai1993** [comment]
Thank you!
