### ISSUE TITLE
gitbook serve 2.1.2 not live reloading

### ISSUE THREAD

**Issue by josephkandi** [GitbookIO/gitbook#1206]
In a previous version i could live reload without having to refresh my browser each time i changed the book, now with version 2.1.2, i can't get live reload anymore.

Re-installed gitbook from npm thinking this could resolve the problem but nope.

I even used the --watch argument and still nothing. Live reload only works when i sync the book with gitbook.com

**Comment by show0k** [comment]
I have right now the the last version of gitbook updated from `gitbook update` (which call npm), and the livereload of gitbook serve is working for me.

**Comment by SamyPesse** [comment]
It's working in newer versions.
