### ISSUE TITLE
Styles overriding are not working properlly for multilingual books

### ISSUE THREAD

**Issue by show0k** [GitbookIO/gitbook#1208]
Two scenarios:
## A very simple book

```
|-- book.json
|-- SUMMARY.md
|-- README.md
`-- styles
    `-- website.css
```

My CSS of website.css is automatically loaded, everything works great.
## A simple multilingual book

```
|-- book.json
|-- LANG.md
|-- en
    -- SUMMARY.md
    -- README.md
`-- styles
    `-- website.css
```

And now, website.css is not loaded, even if I add it explicitly in the book.json.
**However** if I add the style folder inside  the en/ folder, it is working. So it seems that each language is a separated book for the style...

More tricky, if I add a pdf.css in the "styles" root folder, gitbook will try to build the pdf with a css and will not find it and will rise an error like `Error: ENOENT, no such file or directory '/tmp/tmp-516ufv7n4/styles/pdf.css'`. So the root styles folder is not totally useless, it produces bad behaviours !

**Edit: this is a duplicated from #788.** Could you at least document that until it is fixed ?

**Comment by hamishwillee** [comment]
Still an (irritating) issue.

**Comment by show0k** [comment]
To override this behavior, you can put the style folder in the lang folder like this:
|-- book.json
|-- LANG.md
|-- en
    -- SUMMARY.md
    -- README.md
    |-- styles
          -- website.css
