### ISSUE TITLE
Please offer an option to disable chapter auto-numbering in summary pane

### ISSUE THREAD

**Issue by Vdragon** [GitbookIO/gitbook#1210]
![_018](https://cloud.githubusercontent.com/assets/1192163/14309639/57517e8a-fc10-11e5-973f-f418f006ba5e.png)

Some users may prefer do the numbering themselves.

**Comment by nagim** [comment]
Hi,

Check #810 for a workaround.
FYI, this might not work in v3 since it removed the way of overriding the default behavior with CSS stylesheets (@SamyPesse, could you please confirm?).

Cheers,
Imre

**Comment by SamyPesse** [comment]
Sorry for the late response,

Chapter auto-nummering is disabled by default in GitBook v3.

**Comment by ChristophLabacher** [comment]
@SamyPesse How do I enable it manually? Can’t find anything about this in the docs …

**Comment by skyscribe** [comment]
@SamyPesse I get similar request, how can we enable it in v3?

**Comment by laloia** [comment]
Did anyone ever figure out how to enable the chapter auto-numbering?

**Comment by reimertz** [comment]
@ChristophLabacher @SamyPesse @laloia 

in your book.json
change `showLevel` to `false`.

example
```
{
  "gitbook": ">=3.2.1",
  "root": "_docs",
  "title": "reimertz awesome docz",
  "plugins": ["edit-link", "github"],
  "pluginsConfig": {
    "edit-link": {
      "base": "https://github.com/reimertz/reimertz.co/tree/master",
      "label": "Edit This Page"
    },
    "github": {
      "url": "https://github.com/reimerz/reimertz.co/"
    },
    "theme-default": {
      "showLevel": false,
      "styles": {
        "website": "build/gitbook.css"
      }
    }
  }
}
```

**Comment by maimunah1994** [comment]
How can I modify the numbering format to "1, 2, 3, 4, etc" ?
