### ISSUE TITLE
Unable to edit a book. No authentication provided.

### ISSUE THREAD

**Issue by fadieh** [GitbookIO/gitbook#1211]
I'm able to log in successfully into the app. I'm trying to edit a book which I created on an organisation I made from my Gitbook username (same as github) but I keep encountering this message when I try to get into the editor: 
"An unexpected occurred when trying to load your book: No Authentication Provided."
This keeps happening even when I create a new book in that same organisation.

**Comment by maoosi** [comment]
Same thing happening for me since this morning, I'm not anymore able to edit my books.

> "An unexpected error occured when trying to load your book: No authentication provided"

My Gitbook account is also linked to my Github account (shared username and authentication).
