### ISSUE TITLE
No math render with a book in a subdirectory 

### ISSUE THREAD

**Issue by LANTZT** [GitbookIO/gitbook#1212]
I used the `root` option, to transfer my book into a subdirectory of the main project repository, like this :

```
    "root": "./doc/book",
    "gitbook": "3.0.0-pre.5",
    "plugins": ["anchors","include-codeblock","include-highlight","mathjax-beta","ga","richquotes","toc","expandable-chapters","unicodecss"]
```

When the book is finally up on the Gitbook website, I browsed through it and everything was fine ... until I ran into math formulas.

It's seems that the expression are not evaluated by mathjax plugin
Ex: `\alpha` isn't display `α` but just `\alpha`.

I tried to use `{% math %}` instead of `$$` or to use an other math plugin ( like mathjax-beta or latex ) but it still not evaluated.
Any ideas ?

**Comment by SamyPesse** [comment]
It was fixed in the latest release of the `3.0.0`, first releases didn't install plugins correctly.
