### ISSUE TITLE
loadAsObject ?

### ISSUE THREAD

**Issue by wcandillon** [GitbookIO/gitbook#1213]
I'm trying to use gitbook 3.0 but I'm seeing this: 

```javascript
that.fs.loadAsObject
```

Where is this function implemented?

**Comment by jpreynat** [comment]
Hi @wcandillon,

The implementation for this function is in the `lib/models/fs.js` file.
https://github.com/GitbookIO/gitbook/blob/master/lib/models/fs.js#L249
