### ISSUE TITLE
Implement proper HTTP caching headers / responses

### ISSUE THREAD

**Issue by neothemachine** [GitbookIO/gitbook#1214]
Request headers:
```
GET https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/images/playground_temperature_coverage_with_values.png

Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Host:reading-escience-centre.gitbooks.io
If-Modified-Since:Fri, 08 Apr 2016 11:50:58 GMT
If-None-Match:"ff978264d6403563e6aa98bdbdbb3bfd"
Referer:https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/first-range.html
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
```

Response headers:
```
200 OK

Connection:keep-alive
Content-Length:132165
Content-Type:image/png
Date:Fri, 08 Apr 2016 11:55:07 GMT
Etag:"ff978264d6403563e6aa98bdbdbb3bfd"
Last-Modified:Fri, 08 Apr 2016 11:50:58 GMT
Server:GitBook.com
Via:1.1 vegur
X-Frame-Options:ALLOWALL
```

The server should not response with 200 and deliver the image again. Instead there should be 304 Not Modified with no content. This would greatly speed up things. All the things like Etag and Last-Modified are in place already, it's just a matter of then sending the right status code without response.

**Comment by AaronO** [comment]
@neothemachine Thanks for reporting this.

I'm not sure what you were using to send the request, but the server does indeed answer with a `304`, here's the `curl` command I used to try:

```
curl -i https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/images/playground_temperature_coverage_with_values.png \
-H 'Accept:image/webp,image/*,*/*;q=0.8' \
-H 'Accept-Encoding:gzip, deflate, sdch' \
-H 'Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4' \
-H 'Cache-Control:max-age=0' \
-H 'Connection:keep-alive' \
-H 'Host:reading-escience-centre.gitbooks.io' \
-H 'If-Modified-Since:Fri, 08 Apr 2016 11:50:58 GMT' \
-H 'If-None-Match:"ff978264d6403563e6aa98bdbdbb3bfd"' \
-H 'Referer:https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/first-range.html' \
-H 'User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36' \
| less
```

(The `etag` in `If-None-Match` contains quotes which may be misinterpreted by some clients and thus not sent to the server).

That said there were a few cases where our content host doesn't send `ETAGs`, because `nginx` stripped them when `gzip`ing the content (upgraded to a newer `nginx` to fix this).

I've fixed that along with a few other improvements to our `etag` and cache handling, will deploy soon :)

**Comment by neothemachine** [comment]
This is just copied out of the Chrome console. Same thing with Firefox.

**Comment by AaronO** [comment]
@neothemachine Thanks. 

I deployed a few fixes and improvements that are now live on `gitbook.com`, improving our http caching headers.

Give it a try and let me know what you think !

**Comment by neothemachine** [comment]
Looks good, thanks for the quick fix! :)
