### ISSUE TITLE
Ignore not working in  3.0.0-pre.5

### ISSUE THREAD

**Issue by LionelCons** [GitbookIO/gitbook#1215]
It seems that the files specified in the `.ignore` file (or friends) are not ignored in 3.0.0-pre.5.

`lib/output/base.js` contains:
```
    this.ignore = Ignore();
```

which creates a new `Ignore` object instead of using the one containing the `.ignore` patterns, that is `book.ignore`.

**Comment by SamyPesse** [comment]
Yes,

Can you make a PR with a failing test to reproduce this and a fix?

**Comment by SamyPesse** [comment]
I've started a PR to fix it: #1216
