### ISSUE TITLE
Gitbook Editor: default directory

### ISSUE THREAD

**Issue by gristel** [GitbookIO/gitbook#1218]
Hi.
I've searched for this, but can't seem to find the answer.
Is there any way to change the Gitbook Editor's default location when creating a new book?
Right now, on my mac, this is the Gitbook directory in my home directory.
I would like to change this to a directory in my ~/Documents.

Any hints on this?
Thanks!

**Comment by zhenglaizhang** [comment]
Please help make sure you have upgraded the Gitbook to latest version, and check the following menu:

```
File => "Change Library Path"
```

Sorry for that I didn't have mac in hand, the info above is got from the Gitbook Windows version, hope it helps.

**Comment by gristel** [comment]
Thank you!
So silly of me to overlook that :-(

**Comment by 7blink** [comment]
I am trying to do this on Linux.  When I change the path, Gitbooks will change it back to the ~/Gitbooks the next time I start the program.

**Comment by mikew** [comment]
How do you change this on macOS? There is no "File" menu, and the preferences have no option for "library path".

**Comment by sj82516** [comment]
I use mac os and I found it is under /Users/{User Name}/GitBook/Library/Import
