### ISSUE TITLE
Unavailable pages after publish

### ISSUE THREAD

**Issue by atorscho** [GitbookIO/gitbook#1219]
Hello,

I am sorry if that question is obvious, but I cannot make it available for reading after publishing the book.

<img width="289" alt="screen shot 2016-04-09 at 13 18 12" src="https://cloud.githubusercontent.com/assets/7644596/14403418/d7406f06-fe55-11e5-8a5a-fdb0e49abebc.png">

Thanks in advance.

**Comment by SamyPesse** [comment]
This is happening when the entries in the SUMMARY doesn't have corresponding files, or the files doesn't exist.

For example:

```md
# Summary

* Test
* [Test 2](hello.md)
```

`Test` and `Test 2` are gray if `hello.md` doesn't exist.
