### ISSUE TITLE
How i do add static images to book?

### ISSUE THREAD

**Issue by wapmorgan** [GitbookIO/gitbook#122]
I have static folder in my docs.
How i can add it to output dir with gitbook?

**Comment by jordangumm** [comment]
Within the base gitbook directory add a ./gitbook/images directory.  When you build, everything in that directory will be copied to ./_book/gitbook/images.

Referencing them is simple as well.  Just use:
```![Local Image](./gitbook/images/<image_file_name>)```

**Comment by KeranChen** [comment]
Hi, I am still confused about this. so my local directory looks like this 
```
chapter1.md
images   (this is a folder)
README.md
SUMMARY.md
```

and i refer to my images in my git book editor as 
![Local Image](./images/<image_file_name>)

this still not working... I wonder how to fix this.Thank you so much! :)

**Comment by KeranChen** [comment]
as 
```
![Local Image](./images/<image_file_name>)
```

**Comment by mikebotazzo** [comment]
For info, I changed my root folder in the ```book.json``` file, something like this:
```json
{
   "root": "./content"
}
```
And I figured out that to have the images copied in the ```_book/gitbook/images/``` folder after the ```gitbook build``` I needed to have the ```/gitbook/images``` folder inside the ```content``` folder. 

So with all my static images there,

 using ```![Local Image](./content/gitbook/images/<image_file_name>)``` works fine to me.

**Comment by nodox** [comment]
Is there an accepted answer?
