### ISSUE TITLE
Gitbook Editor: Working without git

### ISSUE THREAD

**Issue by sateffen** [GitbookIO/gitbook#1224]
Hey there,

I hope it's alright to ask here, I wasn't able to find a corresponding ticket.

I love the gitbook editor, it fits the needs for documenting software perfectly well, but there is one thing that bothers me: The git enforcement.

I would love to write the gitbook in a subdirectory of my own git repository, but not as submodule, not as git repository at all. Is there a chance to use the gitbook editor and work on a plain directory, without it being a git repository?

If there is no option to do so, is this planed? It would be a big help for documenting software projects.

**Comment by SamyPesse** [comment]
The GitBook Editor will always require a git repository.

But the solution to your problem is in GitBook v3: GitBook now supports an option `root` to put the book in a subdirectory of the repository.
For example if you have a `docs` folder, your repository will look like:

```
.git/
docs/
     README.md
     SUMMARY.md
book.json
```

With `book.json` containing:

```js
{
    "root": "./docs"
}
```

**Comment by sateffen** [comment]
Hey, sorry for this big delay, but the gitbook editor ignores this configuration?

I'm using gitbook editor 5.0.5, installed gitbook 3.0.3, using gitbook-cli 2.2.0, so it's pretty much everything up to date. I've got a book.json looking like:

```
{
    "root": "./docs",
    "title": "tool",
    "description": "A utility tool"
}
```

in a folder structure looking like:

```
.git/
docs/
    README.md
    SUMMARY.md
    ... other markdown files and folders
src/
    sourcecode
package.json
book.json
README.md <-- readme for the project, NOT for the gitbook
```

When opening the folder as gitbook in the editor, it'll open my project files, but won't recognize the *SUMMARY.md* file properly. It doesn't show any structure.

The file-structure in the lower left corner shows the complete folder as well, not only the root set in the book.json

the editor works, but to be honest, it's not doing what I expect, every frustrating.

Building the book with `gitbook pdf` from the project folder creates a correct book.pdf, just like expected.
