### ISSUE TITLE
gitbook 3.0.0-pre.7 error convert svg to png

### ISSUE THREAD

**Issue by tutorialonfree** [GitbookIO/gitbook#1225]
i use mingw64 console to run gitbook command, and it output
Error: Error converting C:\msys64\tmp\tmp-137440iK1gkwjixtc\assets\57d876d7.svg into C:\msys64\tmp\tmp-137440iK1gkwjixtc\assets\82869488.png
does anyone else has the same problem?

**Comment by SamyPesse** [comment]
This is an issue with [svgexport](https://github.com/shakiba/svgexport).

We are sometimes having the same issues with GitBook and Windows uni testing on AppVeyor.

Please test converting it directly using `svgexport`, and report the potential error to the svgexport repository:

```
svgexport C:\msys64\tmp\tmp-137440iK1gkwjixtc\assets\57d876d7.svg out.png
```
