### ISSUE TITLE
Display chosen content license to a conspicuous place for users 

### ISSUE THREAD

**Issue by rebeccawilliams** [GitbookIO/gitbook#1227]
I love that Gitbook makes it easy to choose the license of your content, but I want to make sure my readers see that license quickly and easily. I'd love if Gitbook would consider adding to this by default to a conspicuous place like the footer. 

Forgive me if it is displayed somewhere already and I missed it.

**Comment by SamyPesse** [comment]
Sorry for the late response.

Do you mean on GitBook.com book's homepages? or in the content itself ?

On GitBook.com, we can probably display it next to the tags on the sidebar.

**Comment by noerw** [comment]
is there a field in the `book.json` where i could specify a content license?
it would be great if that info would be added to the footer then.
