### ISSUE TITLE
/content broken, /content/ works

### ISSUE THREAD

**Issue by neothemachine** [GitbookIO/gitbook#1230]
https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content This is broken, it should probably redirect to https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/ or just return a 404, but not a broken page.

**Comment by SamyPesse** [comment]
Thank you, I'm adding an issue to our internal bug tracker for GitBook.com. I'm closing this one.
