### ISSUE TITLE
Can a plugin provide additional CSS?

### ISSUE THREAD

**Issue by uliska** [GitbookIO/gitbook#1233]
I am writing a plugin that generates HTML with CSS styling (syntax highlighting). 
Is it possible that a Gitbook plugin provides its own CSS and injects that in the book? As a workaround I provide the CSS file and ask the user (well, currently that's only me anyway ...) to include that CSS from within `book.json`, but of course it would be much nicer if that would be transparently handled.

**Comment by SamyPesse** [comment]
Yes, a plugin can provide custom CSS, See this example: https://github.com/GitbookIO/plugin-codetabs/blob/master/index.js#L31

**Comment by uliska** [comment]
Thanks, that's a cool feature!
