### ISSUE TITLE
Feature request: Separate readme.md's for /details page (About this book box) and Outputs (Web/PDF/MOBI/...)

### ISSUE THREAD

**Issue by drreen** [GitbookIO/gitbook#1234]
Hey guys

I like the feature of a custom readme! Yet I have an issue:

I want to use a custom internal(!) readme.md for the /details page of my private book. There I want to keep my styleguide and documentation for future writers who will join me on my project.

The issue is, that the same readme is also used in the Frontend output as well as in the Backend /details page.

Is there a way to use two different ones for each?

**Comment by SamyPesse** [comment]
This is currently not possible, since GitBook.com is using the output of the book to read the README (JSON output from GitBook).

I'm adding an issue to our internal bug tracker to think about this.
