### ISSUE TITLE
Keep section headings with following paragraph

### ISSUE THREAD

**Issue by cjnygard** [GitbookIO/gitbook#1235]
Would really like a way to ensure that page breaks do *not* occur between any section headings and the first paragraph of a heading.  I have a lot of code blocks and text paragraphs that are shown on the next page separate from the section heading.

**Comment by abeolson** [comment]
This is, I believe, a matter for the ebook converter (which it looks like is using [Calibre](https://github.com/kovidgoyal/calibre).)

There may be a way to accomplish is with themes or styling though.

**Comment by SamyPesse** [comment]
Closing in favour of #1247
