### ISSUE TITLE
Node versions for plugins?

### ISSUE THREAD

**Issue by cycomachead** [GitbookIO/gitbook#1237]
Is this still the correctly supported version of node?
https://github.com/GitbookIO/gitbook/blob/master/.travis.yml#L3

Is there a way for me to specify which version of node my plugin uses?
I'd really like to use some string interpolation features of 4.x, but wouldn't want to break things at the point that I end up publishing the plugin.

(And I probably could introduce a compile step via babel, but I'd like to avoid the headache if possible.)

**Comment by SamyPesse** [comment]
Since plugins are simply Noe modules, you can use the `engine` field in the `package.json`: https://docs.npmjs.com/files/package.json#engines

GitBook.com is currently using Node 0.12, but the new builder for GitBook v3 is using Node 5.9.0; and we'll start supporting only Node > 4 with GitBook v3.

**Comment by cycomachead** [comment]
> GitBook.com is currently using Node 0.12, but the new builder for GitBook v3 is using Node 5.9.0; and we'll start supporting only Node > 4 with GitBook v3.

Awesome, thanks! I'm hoping to make use of some ES6 features soon, so that's great to know.
