### ISSUE TITLE
.gitattributes file

### ISSUE THREAD

**Issue by Spomky** [GitbookIO/gitbook#1242]
Hi,

I tried to create a book based o the documentation on my Github repository: it always fails because documentation files are missing.
It seems that this is due to the presence of the .gitattributes file that allow Git to ignore unnecessary files during repository cloning.

**Comment by SamyPesse** [comment]
I'm not used to work with the `.gitattributes` file.

Can you paste me its content?

**Comment by Spomky** [comment]
Hi, 

You will find an example [in that project](https://github.com/Spomky-Labs/otphp).

**Comment by Spomky** [comment]
Is there any news about that issue?
Unfortunately book builds still fail.
