### ISSUE TITLE
Automatically create SUMMARY.md file

### ISSUE THREAD

**Issue by lisaluescher** [GitbookIO/gitbook#1243]
Hi,

I've got some *.md files with which I'd like to make a gitbook.
I've got a gulpfile which builds the gitbook into the folder "_book". What I'd like to have is that my gulpfile runs every evening to update the gitbook. 
Because everything is well automized I'd like to automize the "SUMMARY.md" file too. I found this https://www.npmjs.com/package/gitbook-summary in which exactly this is explained.
But the problem is that if I run the command "book sm" it structures all the folders in the summary file --> also the files in the folder _book in which the gitbook folder with the fonts, images and plugins is stored. So now my Summary file looks like this:

```
# Test

  * [Chapter 1](/chapter1.md)
  * [Chapter 2](/chapter2.md)

- Book
  - Gitbook
    - Fonts
      - Fontawesome
    - Images
    - Plugins
      - Plugin Fontsettings
      - Plugin Highlight
      - Plugin Search
```

What can I do?
And furthermore... how would the gulp task look like?

**Comment by lisaluescher** [comment]
And furthermore... how would the gulp task look like?

**Comment by abeolson** [comment]
@lisaluescher Seems like you should be asking on the [gitbook-summary repo](https://github.com/imfly/gitbook-summary), not here...

But to give you some pointers: Looking at gitbook-summary's [source code](gitbook-summary/bin/summary.js), there are ignore flags you could set with your ```book sm``` code to not inlcude the ```_book``` folder. 

```
program
  .command("summary")
  .alias("sm")
  .description("Generate a `SUMMARY.md` from a folder")
  .option("-r, --root [root]", "root folder, default is `.`")
  .option("-n, --bookname [bookname]", "book name, default is `Your Book Name`.")
  .option("-c, --catalog [catalog]", "catalog folders included book files, default is `all`.")
  .option("-i, --ignores [ignores]", "ignore folders that be excluded, default is `[]`.", list)
  .option("-u, --unchanged [unchanged]", "unchanged catalog like `request.js`, default is `[]`.")
  .option("-o, --outputfile [outputfile]", "output file, defaut is `./SUMMARY.md`")
```

**Comment by lisaluescher** [comment]
Ok thanks.
It worked with the ignores attribute :) I guess I just overlooked it somehow.
