### ISSUE TITLE
Using summary file from subdir does not work anymore on 3.0

### ISSUE THREAD

**Issue by omnidan** [GitbookIO/gitbook#1244]
Config:

``` js
{
  "gitbook": "3.0.0-pre.9",
  "structure": {
    "summary": "docs/README.md"
  },
  "plugins": ["edit-link", "prism", "-highlight", "github", "anker-enable"],
  "pluginsConfig": {
    "edit-link": {
      "base": "https://github.com/omnidan/redux-undo/tree/master",
      "label": "Edit This Page"
    },
    "github": {
      "url": "https://github.com/omnidan/redux-undo/"
    }
  }
}
```

Output:

```
ConfigurationError: Error with book's configuration: config.structure.summary does not match pattern "^[0-9a-zA-Z ... ]+$"
```

**Comment by nagim** [comment]
You have to specify the folder of the documents in `book.json`, if you're not using the root folder:

```json
{
    "root": "./docs"
}
```

**Comment by omnidan** [comment]
@nagim Thanks for the reply! I tried this, but unfortunately it doesn't seem to work for me.

With the `root` option specified in `book.json`, I get the following error:

```
Error: Couldn't locate plugins "edit-link, prism, github, anker-enable", Run 'gitbook install' to install plugins from registry.
```

Without it, but keeping `README.md` as summary (which isn't the correct file - it should be `docs/README.md`), it works fine.

**Comment by prudhomm** [comment]
idem here `root` does not seem to work and we get the same message ?
@omnidan what did you do actually to make it work ?

**Comment by omnidan** [comment]
@prudhomm Unfortunately, I still did not get this to work 😞

**Comment by paulkogel** [comment]
Running into the same issue when updating gitbook to 3.0.0 in [Redux's book.json](https://github.com/reactjs/redux/blob/master/book.json).
Added `"root": "./docs"`, still getting the same error.

**Comment by paulkogel** [comment]
ah sorry, my mistake, forgot to adjust the summary path. all working for me now.
