### ISSUE TITLE
no index.html on 2.x.x (2.6.7)

### ISSUE THREAD

**Issue by omnidan** [GitbookIO/gitbook#1245]
On `2.6.7` (latest `2.x.x` version), gitbook is not generating an `index.html` file, however, on `2.4.3` it still works fine.

On `2.4.3` links don't work correctly, though (when going to a subpage, the links in the sidebar point to `../../_book/index.html` when it should be `../index.html` or `/index.html`. You can check out this issue here: http://redux-undo.js.org/ (click on FAQ and then "Read Me")

Config:

```js
{
  "gitbook": "2.x.x",
  "structure": {
    "summary": "docs/README.md"
  },
  "plugins": ["edit-link", "prism", "-highlight", "github", "anker-enable"],
  "pluginsConfig": {
    "edit-link": {
      "base": "https://github.com/omnidan/redux-undo/tree/master",
      "label": "Edit This Page"
    },
    "github": {
      "url": "https://github.com/omnidan/redux-undo/"
    }
  }
}
```

**Comment by SamyPesse** [comment]
GitBook doesn't support a configuration `structure.summary` or `structure.readme` not in the root directory.

With GitBook v3, we are introducting the `root` option to use a folder like `docs` as root folder of your book:

```
{
    "root": "./docs",
    "structure": {
        "summary": "README.md",
        "readme": "intro.md"
    }
}
```
