### ISSUE TITLE
headings at end of page

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#1247]
On 2.6.7, when generating a PDF there are some cases where a section header is shown at the bottom of the page and its content in the next one, getting it ugly since the header should be moved to the next page too. I believe this was solved before but maybe only for first-level sections and not for several nested sub-sections, so I ask to do it for the full hierarchy.

**Comment by SamyPesse** [comment]
This is kind of tricky to solve, since `ebook-convert` is not reliable with page breaks.

When you're talking about "section header", do you mean the first header of a page?

**Comment by piranna** [comment]
> This is kind of tricky to solve, since ebook-convert is not reliable with page breaks.

I know, but maybe it would be possible by grouping all the headers (when there are several nested levels without an introduction paragraph for each one of them) with the first paragraph block that appear.


> When you're talking about "section header", do you mean the first header of a page?

No, the first header of a page is used as title, I'm talking about the subsequent ones, where this only works (worked?) for first level ones (sections of the page) but it's not working for nested ones (sub-sections headers).

**Comment by piranna** [comment]
I think CSS [page-break-after: avoid](https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/#page-breaks) is just what we were looking for here, the given example for the headers just fix the problem we have here.

**Comment by cjnygard** [comment]
Related to #1235 perhaps?

**Comment by piranna** [comment]
Yes, we are talking about the same thibg.

**Comment by oxid-filla** [comment]
I have pictures after headings. That results often to a headline in the middle of a page and the picture on the next. I tried to solve it with (styles/pdf.css):
```
h1, h2, h3, h4, h5 {
  page-break-after: avoid;
}
```

But its not helping.
