### ISSUE TITLE
Parsing problem?

### ISSUE THREAD

**Issue by samdutton** [GitbookIO/gitbook#1249]
On http://toolchain.gitbook.com/pages.html there is a problem with the text:

![image](https://cloud.githubusercontent.com/assets/205226/14748485/e0df7758-08b1-11e6-8269-023490201c24.png)

Source looks OK.

**Comment by nagim** [comment]
Hi,

The source you looked at is version 3.0.0-pre.9, where it has been corrected, but the published version you checked online is 3.0.0-pre.5, so the fixed version is just not published yet.

Cheers,
Imre

**Comment by samdutton** [comment]
Ah — good news, thanks!
