### ISSUE TITLE
Include pages, but hide them in navigation?

### ISSUE THREAD

**Issue by CoDEmanX** [GitbookIO/gitbook#1251]
I wonder if it's possible to add "hidden" pages.

My current configuration consists of 3 separate Gitbooks, but there's a lot of trouble with that. Cross-links between books do not work unless you link to `page.html` instead of `page.md`, but there will be a "... outside spine" warning and no actual check if the target exists AFAIK. As PDF or ePUB, the cross-links will probably be broken - at least you will not be able to jump between multiple ebooks.

A great solution would be to merge all three books into one, hide the pages of the two formerly separated books in the regular navigation, but still have them rendered to html in the build process, so that you can access them if you know the right URL path. An even better solution would be to have sub-books with their own navigation, but only the navigation of the active sub-book should show.

What are my options in current Gitbook?

**Comment by fabdrol** [comment]
+1
