### ISSUE TITLE
gitbook mv chapter1/foo.md chapter2/foo.md

### ISSUE THREAD

**Issue by crguezl** [GitbookIO/gitbook#1252]
It will be convenient to have a command `gitbook mv chapter1/foo.md chapter2/bar.md` to move  a file from a place to another in such a way that all references to `chapter1/foo.md` will be changed - not only in the `SUMMARY.md` but in all its appearances - to `chapter2/bar.md`.

It will be useful if additionally accepts options for directories and to work recursively.

**Comment by SamyPesse** [comment]
This is a good idea, I'm open for it, but the implementation might be tricky: changing references in the markdown is not easy (it requires to render back to markdown); it might become easier to implement once GitBook switch to [markup-it](https://github.com/GitbookIO/markup-it).

**Comment by crguezl** [comment]
Thanks a lot! It will be great!! :smile:
