### ISSUE TITLE
How to specify a favicon?

### ISSUE THREAD

**Issue by Tiliavir** [GitbookIO/gitbook#1254]
I'm quite happy with the  default layout, but I want to have my custom favicon - is there a way to do that?

I saw, that it is possible to create an own theme. Is that the way to go? This could also be something that should be mentioned in the documentation ...

I've placed the question here, since the [default theme](https://github.com/GitbookIO/theme-default) does not seem to specify a favicon at all and since there is a [test in this repo ensuring, that the favicon exists](https://github.com/GitbookIO/gitbook/blob/ba182ce8e430f08bd8c60865b9c853875a3d6483/test/output-website.js#L25)...

**Comment by SamyPesse** [comment]
Sorry for the late response.

The default theme does have a [favicon](https://github.com/GitbookIO/theme-default/blob/master/_layouts/website/layout.html#L10). There is no option currently to specify a favicon, but I'm wiling to merge a PR to add one.

**Comment by aleung** [comment]
I found a workaround to overwrite the default gitbook favicon.

Place your favicon file to `<book_root>/gitbook/images/favicon.ico`.

**Comment by dtolb** [comment]
Created a plugin based on @aleung 's workaround: https://www.npmjs.com/package/gitbook-plugin-custom-favicon
