### ISSUE TITLE
symlinks don't seem to work

### ISSUE THREAD

**Issue by jedwards1211** [GitbookIO/gitbook#1261]
I'm trying to figure out a way to share pages about JSON schema for my API between the separate books for my JS and Python API documentation.

I tried using `git subtree add --prefix schema ...` and then using a symlink from `docs/api/schema -> ../../schema`, but the link to `/docs/api/schema/README.md` is disabled in the table of contents.

Is there any way to get symlinks to work?

**Comment by jedwards1211** [comment]
Okay, I discovered that I could use `git subtree add --prefix docs/api/schema` to avoid needing to symlink, but still, it seems like symlinks would be worth supporting.

**Comment by SamyPesse** [comment]
Symlinks should be fixed in GitBook v3, but for your wanted use-case, it's not the best solution.

Currently the best solution is to use **Conrefs**: http://toolchain.gitbook.com/templating/conrefs.html

But it requires creating a file with only one line:

```md
{% include "git+https://github.com/GitbookIO/documentation.git/README.md" %}
```

I'll open an issue about supporting conrefs in the `SUMMARY.md`.

**Comment by jedwards1211** [comment]
Okay, I wasn't sure if include tags can reference content outside of the file tree.  Thanks!

**Comment by jedwards1211** [comment]
@SamyPesse recently the HELP link started going to a separate page than the toolchain documentation (I seem to remember it went to a book about things like this?)  And I can't seem to find links to `toolchain.gitbook.com` anywhere on `gitbook.com`.  I had no idea of its existence until you included that link.  What's going on?  Is the pre-3.0.0 toolchain documentation available anywhere?
