### ISSUE TITLE
Error with 3.0.0-pre.12

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1266]
Hi,

Ran a build with the new pre, and the previous issue is fixed, however, there are new ones:
- link anchors in lists (asciidoc) no longer work. For creating an anchor on a list item the following syntax is used: `* [[anchor]]listitem`. But it gives the following error message: `TypeError: Cannot call method 'charAt' of undefined`
- the plantuml plugin does not work properly (instead of the image, only the `<img src...` will appear). Asciidoc only, works in markdown.
- absolute filepaths for conrefs not working, only accepts relative paths
- getting strange `TypeError: Cannot read property 'children' of undefined` for [this file](https://raw.githubusercontent.com/nagim/test_2/master/test/test.adoc). This usually appears if I begin a chapter with h2 instead of h1, but here I cannot figure out why it comes up. For some reason, only works if I remove everything except the h1. Worked with the previous builds.

Thanks,
Imre

**Comment by SamyPesse** [comment]
Please next time, open different issues for each bugs, so that we can close each one with a commit.

For bugs 1) and 3), if you are using GitBook.com, in your book settings page adds the environment variable `DEBUG=true`; if you are building the book locally, append `--debug` to your command. It will give us the complete stack trace.

I'm not sure I understand the bug 2), the `<img` has not `src` ?

**Comment by nagim** [comment]
Sorry, I will do accordingly next time.
I should have been mire specific regarding 2).
Instead of the image, this is what appears on the page:
`<img src="http://www.plantuml.com/plantuml/svg/UDhZSip9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rO0LOr5LN92VLvpAnOLcM5u-K5sHGY9sGo6ARNHr8QeJSQc66Wu089Gwdm00" />`

Thanks!

**Comment by nagim** [comment]
Hi,

Ran the builds with debug mode on.

Bug 3) is connected to a plugin:
```
TypeError: Cannot read property 'children' of undefined
TypeError: Cannot read property 'children' of undefined
    at Object.<anonymous> (/tmp/book/node_modules/gitbook-plugin-anchor-navigation/index.js:25:42)
    at exports.each (/tmp/book/node_modules/cheerio/lib/api/traversing.js:294:24)
    at insertAnchors (/tmp/book/node_modules/gitbook-plugin-anchor-navigation/index.js:11:18)
    at Function._.each._.forEach (/tmp/book/node_modules/underscore/underscore.js:153:9)
    at Object.module.exports.hooks.page (/tmp/book/node_modules/gitbook-plugin-anchor-navigation/index.js:84:15)
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/callHook.js:48:29
    at /root/.gitbook/versions/3.0.0-pre.12/lib/utils/promise.js:21:20
From previous event:
    at callHook (/root/.gitbook/versions/3.0.0-pre.12/lib/output/callHook.js:53:10)
    at callPageHook (/root/.gitbook/versions/3.0.0-pre.12/lib/output/callPageHook.js:13:12)
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/generatePage.js:65:24
```

Strange, as this was working before, and it has no problem with other files.

Bug 1) stack trace:
```
TypeError: Cannot call method 'charAt' of undefined
TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at normalize (/root/.gitbook/versions/3.0.0-pre.12/lib/utils/location.js:39:17)
    at Object.toAbsolute (/root/.gitbook/versions/3.0.0-pre.12/lib/utils/location.js:54:13)
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/modifiers/resolveLinks.js:26:30
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/modifiers/editHTMLElement.js:11:16
    at /root/.gitbook/versions/3.0.0-pre.12/lib/utils/promise.js:35:16
    at /root/.gitbook/versions/3.0.0-pre.12/lib/utils/promise.js:21:20
From previous event:
    at Object.onPage (/root/.gitbook/versions/3.0.0-pre.12/lib/output/website/onPage.js:41:6)
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/generatePages.js:27:30
From previous event:
    at /root/.gitbook/versions/3.0.0-pre.12/lib/output/generatePages.js:26:10
    at /root/.gitbook/versions/3.0.0-pre.12/lib/utils/promise.js:21:20
```

Hope it helps!

Thanks,
Imre

**Comment by nagim** [comment]
Thanks, fixed 1).
2), 3), 4) are still there.

Imre

**Comment by SamyPesse** [comment]
Do you have a stack trace (using `DEBUG=true` or `--debug`) for bug 4) ?

**Comment by nagim** [comment]
Sorry, I made a mistake, the stack trace I included couple of comments above as bug 3) was in fact for bug 4).

**Comment by nagim** [comment]
For bug 2) (plantuml rendering), it works in markdown, but not in asciidoc.
The way I see, in asciidoc, there is a trailing `/` at the end of the `<img>` tag.
