### ISSUE TITLE
ReferenceError: page is not defined (In file 'README.md')

### ISSUE THREAD

**Issue by AllieRays** [GitbookIO/gitbook#1269]
If I try to create a book.json file for plugins I get the following error. 
`- ReferenceError: page is not defined (In file 'README.md')`
- If I remove the book.json file the build works fine. 
- I've tried removing the book.json file and adding it back in. 
- I've also tried removing / trying different plugins.  

With book.json 
![screen shot 2016-05-04 at 12 30 37 pm](https://cloud.githubusercontent.com/assets/5032852/15021301/083e2d80-11f4-11e6-960a-8647218a8281.png)

without book.json
![screen shot 2016-05-04 at 12 31 05 pm](https://cloud.githubusercontent.com/assets/5032852/15021314/1971067c-11f4-11e6-8732-0770cd7aa5cb.png)

**Comment by SamyPesse** [comment]
Can you paste me the content of your `book.json`?

**Comment by AllieRays** [comment]
Currently I don't a book.json file but if I just add the plugin ungrey and print links I get:

![screen shot 2016-05-05 at 9 41 26 pm](https://cloud.githubusercontent.com/assets/5032852/15062045/37ef8620-130a-11e6-803d-a1c2a7ce1f03.png)

![screen shot 2016-05-05 at 9 41 15 pm](https://cloud.githubusercontent.com/assets/5032852/15062046/3a83d85a-130a-11e6-80c8-ca4d530265e7.png)

![screen shot 2016-05-05 at 9 42 39 pm](https://cloud.githubusercontent.com/assets/5032852/15062052/4f8fb28c-130a-11e6-8632-19049ca9009a.png)

**Comment by SamyPesse** [comment]
I've added the environment variable `DEBUG=true` to your book. Once the bug appears again, paste me the build link (and we'll have a complete stack trace to investigate).
