### ISSUE TITLE
Pipe character confuses table processing

### ISSUE THREAD

**Issue by mattharden** [GitbookIO/gitbook#1270]
In the following table:

| character | name |
| --- | --- |
| `+` | plus |
| `-` | minus |
| `|` | vertical bar |

Other markdown processors such as github's seem to recognize that the vertical bar inside the backticks is not a table column separator but should be taken literally. Gitbook treats the backticks as column data and the vertical bar as a separator.

**Comment by SamyPesse** [comment]
This is something that will be fixed once GitBook switch from Kramed to [markup-it](https://github.com/GitbookIO/markup-it).

markup-it is not yet ready yet, but it will be in the coming release of GitBook (probably `3.0.0` stable or `3.1.0`).

**Comment by SamyPesse** [comment]
It should be fixed in `3.2.0-pre.0`.

**Comment by paulyoung** [comment]
I'm seeing this issue with the following markdown:

| Name | Regex |
|---|---|
| Foo | `(bar|baz|quux)` |

I tried `3.2.0-pre.0`, `3.2.2`, and `4.0.0-alpha.3`
