### ISSUE TITLE
How to add new parser?

### ISSUE THREAD

**Issue by inetfuture** [GitbookIO/gitbook#1271]
I want to integrate gitbook with raml, currently it bails out with error `FileNotParsableError: "openApi/openApi.raml" file cannot be parsed`, how can I add a new parser to fix it?

**Comment by SamyPesse** [comment]
GitBook currently doesn't make it possible to add a new parser, and we'll probably not make it possible.

What is your use-case for RAML in GitBook? Maybe a plugin can help you better than a new parser.

**Comment by inetfuture** [comment]
I use [raml2html](https://github.com/raml2html/raml2html) to generate html from raml, and I just want the generated html be part of the book, user can navigate from left menu tree, and its content can be shown in right as a page.

I think it's a common use case, build some html with a dedicated tool, then plugin it into the book seamlessly.

**Comment by SamyPesse** [comment]
It can be done using a plugin, for example we could have a block `{% raml filename="myFile.raml" %}{% endraml %}`.
