### ISSUE TITLE
nunjucks comments inside _layouts files are not stripped out with 3.0.0-pre.12

### ISSUE THREAD

**Issue by inetfuture** [GitbookIO/gitbook#1274]
https://mozilla.github.io/nunjucks/templating.html#comments it's not working

```
{% block javascript %}
{# comment #}
{% endblock %}
```

**Comment by inetfuture** [comment]
Write it in this way works:

```
{# comment #}
{% block javascript %}
{% endblock %}
```

I'm not sure if this is nunjucks' problem.

**Comment by SamyPesse** [comment]
In GitBook v3, we changed comments for themes (and `_layouts` folder) to use same as for Markdown/AsciiDoc content:

```
{### Comment ###}
```

(It avoids conflicts with heading's ID in Markdown: `# My Head {#id}`).

**Comment by inetfuture** [comment]
Is it documented somewhere? I feel frustrated.
