### ISSUE TITLE
PDF preview

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1276]
Is it possible to preview the markdown as PDF?

Because it's hard to know exactly where the content will be slicing to next page. 

And for some code block using ``` ,when the code inside is too long which will be cut,how to solve it?

Thanks for reply!

**Comment by SamyPesse** [comment]
This is something that we cannot easily done. The PDF generation is not entirely under GitBook's control, we are using `ebook-convert` which is not perfect.

Code blocks being spitted is an annoying bug of `ebook-convert` which doesn't respect the `page-break: avoid;` CSS rules.
