### ISSUE TITLE
Printing Code examples

### ISSUE THREAD

**Issue by AllieRays** [GitbookIO/gitbook#1280]
When we print a book with larger code examples, the code should wrap around, not add a scroll bar.  I am having a really hard time over writing this with custom styling. 
Here is an example from the gitbook documentation pdf: https://gitbookio.gitbooks.io/documentation/content/format/configuration.html

https://www.gitbook.com/download/pdf/book/gitbookio/documentation

Example of a printed pdf: 
![screen shot 2016-05-06 at 3 38 20 pm](https://cloud.githubusercontent.com/assets/5032852/15084361/e79ab068-13a0-11e6-829a-0b5a4ab48b63.png)

**Comment by SamyPesse** [comment]
It has been fixed by @bartvde in the upcoming GitBook v3 (https://github.com/GitbookIO/theme-default/commit/4c91f0928bcb26dd42647b35742dd05e024af7b0).
