### ISSUE TITLE
Specify Output Filenames when generating pdf/ebooks

### ISSUE THREAD

**Issue by cycomachead** [GitbookIO/gitbook#1284]
Is it possible to specify output filenames? Gitbook seems to just give files `<repo-name>.pdf` and I'd like to change that.

**Comment by SamyPesse** [comment]
`gitbook pdf`, `gitbook epub` and `gitbook mobi` accepts 2 arguments:

- The path of the book
- The output filename

For example to generate a `test.pdf`:

```
$ gitbook pdf ./ ./test.pdf
```

**Comment by cycomachead** [comment]
Thanks, is there a way to control this on gitbook.com?
