### ISSUE TITLE
Math output using mathjax is broken in 3.0.0pre13 

### ISSUE THREAD

**Issue by prudhomm** [GitbookIO/gitbook#1286]
@SamyPesse I have split the big keywords file and thanks to #1262 now the book is generated however the math rendering is totally broken

here is the result on our book
http://book.feelpp.org/content/QuickReference/keywords.html

**Comment by prudhomm** [comment]
some more info. It seems that some math formula are displayed but not all
http://book.feelpp.org/content/QuickReference/Integrals/integrate.html

and html tag `<script>` is shown. Perhaps an `escaping` problem ?

**Comment by SamyPesse** [comment]
It's working with Markdown, but not with AsciiDoc, I'm investigating and I'll fix the issue (in GitBook or the mathjax plugin).
