### ISSUE TITLE
Summary entry formatting

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1290]
Hi,

Does the summary file accept any formatting?
It would be useful to highlight chapters that have been modified / not yet revised / out of date, etc.
I tried standard formatting of the link texts, but it won't render.

Thanks,
Imre

**Comment by SamyPesse** [comment]
No, only list/links are parsed from the summary.

Concerning the `has been modified`, `out of date`, etc; I think it'll be better to have a smart plugin to do this job using the Git history.

**Comment by nagim** [comment]
Thanks for the quick reply.
Only problem, the `not yet revised` / `out of date` info does not depend on the status of the files in git, it depends on decision/evaluation of the chapter, therefore it needs to be marked manually.
For the modified files, the plugin is a good idea.

**Comment by SamyPesse** [comment]
The other solution is something we are thinking about using for an API documentation theme, is using the YAML header:

Let's say my SUMMARY is:

```
# Summary

* [Page](page.md)
```

And `page.md`:

```md
----
tags:
    - out-of-date
    - not-yet-revised
----
```

These metadata will be accessible by plugins/themes as `page.tags === ['out-of-date', not-yet-revised']` (any metadata from the YAML header is stored in `page.*`).

Currently when generating a page, the theme only has access to the metadata of the current page, but this is something we can change.

**Comment by nagim** [comment]
Exactly what came into my mind as well (just edited my previous comment) :smile: 
I have not yet created plugins and have no time currently, but this looks like the way to go.

Thanks a lot for your insights!
Imre
