### ISSUE TITLE
Bug in math rendering in included files: it is not rendered and the latex shows up

### ISSUE THREAD

**Issue by prudhomm** [GitbookIO/gitbook#1293]
@SamyPesse when you include a file in another one and if it contains math, the math are not rendered.
we work with asciidoc files

eg consider the file `tutu.adoc`
```
{% include toto.adoc %}
```

and `toto.adoc`
```
$$-\Delta u = f$$
```

then the math are not rendered when generating `tutu.html` 
it will show `-\Delta u = f`

**Comment by SamyPesse** [comment]
Ok I see the issue, `{% math %}` works in included files, but shortcuts `$$...$$` are not replaced when including a file.

I'll fix it as soon as possible.

**Comment by LeBron-Jian** [comment]
@SamyPesse   

May I ask if the repair was successful? I still encounter this issue now
