### ISSUE TITLE
Import file does not work

### ISSUE THREAD

**Issue by Abel-Torres** [GitbookIO/gitbook#1296]
The specified syntax is:
  {{./myfile.md}}

* It is ignored in the preview window.
* Running gitbook build command fails when it encounters the request to import the file. The error states that the dot used in the path specification is an unexpected token.
* Requesting a nonexistent file does NOT produce an error or generate any sort of message. A missing file is just ignored.

**Comment by SamyPesse** [comment]
You are using the wrong syntax, Importing a file is done using:

```
{% include "./myfile.md" %}
```

**Comment by Abel-Torres** [comment]
Look at the documentation:
https://ganiutomo.gitbooks.io/gitbook-documentation/content/book/variables.html


Import files
In the same way, files can be imported:
# This is a test:

{{ ./file.md }}

**Comment by nagim** [comment]
Hi,

You are referring to a forked version of the documentation, which was done by somebody more than   1 year ago, so it's quite outdated.

The official documentation maintained by the GitBook guys can be found here:
http://toolchain.gitbook.com

The part you are interested in:
http://toolchain.gitbook.com/templating/conrefs.html

Cheers,
Imre
