### ISSUE TITLE
Possible to have multiple 'versions' of a book in the same repo?

### ISSUE THREAD

**Issue by cycomachead** [GitbookIO/gitbook#1298]
Essentially, I'd like to have a normal version of my book, and an abridged version which has a few chapters removed (and some stuff reordered).

It doesn't seem like GitBook supports selectively choosing a different SUMMARY to build with or a different book.json, but I could be wrong. 
- Can I abuse the LANG file for this?
- Use a subdirectory with a different book.json and SUMMARY ? I'm not sure if the '../' references will work in a book.json file (and this first requires me to get the book compiling on 3.0)

Thanks for the help!

**Comment by BeanMr** [comment]
expect this feature also.
my case is hoping the book in the repo can be published in Chinese&Chinese-english Version.
How can i achieve the task？

Thanks for the help!
