### ISSUE TITLE
3 pre.14: All items start with level 1.x

### ISSUE THREAD

**Issue by cycomachead** [GitbookIO/gitbook#1301]
When I view the level numbers, everything starts at a 1.x level but the summary file doesn't have any nesting. To my eyes it looks just like there's an extra "1." before every item.
<img width="320" alt="screen shot 2016-05-12 at 2 20 45 am" src="https://cloud.githubusercontent.com/assets/1505907/15209922/a9dcf5e6-17e8-11e6-9500-b700792b1f73.png">

**Comment by SamyPesse** [comment]
This is because GitBook v3 includes the concept of "Parts":

```md
# My Summary

## My First part

* An article
* An other in part 1

## My Second part

* An article in part 2

----

* An article in an untitled part
```

@todvora was also worried about these new levels.

I can probably improve the calcul of level to remove the `1.` when there is only one part in the summary.

**Comment by cycomachead** [comment]
Yeah, I just saw that.

> I can probably improve the calcul of level to remove the 1. when there is only one part in the summary.

That sounds like what I was thinking. I was looking at drafting a PR to do the same.

**Comment by SamyPesse** [comment]
I'm working on fixing some other issues/bugs, It'd be great if you can post a PR for this, otherwise I'll fix as soon as I fixed the critical bugs.

**Comment by cycomachead** [comment]
So I was thinking about this, and maybe my approach of detecting on section isn't the best way to go...

What if I have a summary file

```
# Summary
* chapter
* chapter
## Links
* Link 1
* Link 2
```

This would still have 2 parts, but it seems like the numbering is actually intended to be 1, 2... and so on.

Perhaps the better way to go about this would be a config variable, "includePartsInSectionNumber", which could default to `true`, but could be set to `false`. If it's `false` then all parts would have a single numbering equivalent to the pre-parts feature, but you could use parts as headings / organization.

**Comment by lionpeloux** [comment]
Hello,

Is this issue fixed ? I'm on the latest 3.2.2 and still got the pb for a book with no parts, the numbering starts at 1.1

Tanks

**Comment by linesh-simplicity** [comment]
@lionpeloux 

Try to put the following configuration in the `book.json` file on your gitbook project's root and see if it's what you want: 

```json
{
    "gitbook": ">=3.1.0",
    "pluginsConfig": {
        "theme-default": {
            "showLevel": true
        }
    }
}
```

**Comment by THWJ** [comment]
@linesh-simplicity  it doesn't work.

**Comment by lionpeloux** [comment]
Yes, same for me.

**Comment by maimunah1994** [comment]
@linesh-simplicity it doesn't work for me too. I am using the latest version 3.2.2 . The chapter numbers starts from 1.1 , 1.2 , 1.3 :(

**Comment by maimunah1994** [comment]
@linesh-simplicity it doesn't work for me too. I am using 3.2.2 and chapter numbering starts from 1.1

**Comment by gdolle** [comment]
Doesn't work also for me.  

@SamyPesse Maybe we could just add an option in the plugin config to hide the part numbering `showPartLevel` for example.
I guess we don't necessarily want to show part numbers (even with several parts) with the current display style (numbers are not shown for parts).

```js
{
    "gitbook": ">=3.1.0",
    "pluginsConfig": {
        "theme-default": {
            "showLevel": true,
            "showPartLevel": false
        }
    }
}
```

What do you think ?

**Comment by dibyaghosh** [comment]
Is it still on the roadmap to remove the leading 1. on single part summaries?

**Comment by zq99299** [comment]
啥时候能解决哇。现在的 1.1 太难受了
When can solve wow. Now 1.1 too uncomfortable

**Comment by soulmachine** [comment]
When can this bug be fixed? The leading `1.x` is ugly

**Comment by jarronshih** [comment]
++

**Comment by zhangjikai** [comment]
I change the gitbook file to solve this problem. Go to `<user_home>/.gitbook/version/3.x.x/lib/models` and open `summaryPart.js`, then modify the code at 51 line as following : 
```js
 // return SummaryArticle.create(article, [level, i + 1].join('.'));
 return SummaryArticle.create(article, [i + 1].join('.'));
```

**Comment by beepony** [comment]
same question for me, hope to fix it soon

**Comment by shubheksha** [comment]
Still facing this issue. Is there no way to have the numbering start at `1` in a book with no parts? @SamyPesse

**Comment by eyechen** [comment]
wait..

**Comment by ilicmarko** [comment]
Still not fixed!

**Comment by zq99299** [comment]
@ilicmarko  都在搞新版本了。 旧版网站都不推了。 这个bug在新版本中不存在了； 但是新版没有离线编辑器，不能本地运行。

**Comment by crifan** [comment]
same here.

```
➜ backup_restore node -v
v10.4.0
➜ backup_restore npm -v
6.1.0
➜ backup_restore gitbook --version
CLI version: 2.3.2
GitBook version: 3.2.3
```

Please fix it ASAP !!!

那就郁闷了。希望还是能尽快修复这个问题啊。

**Comment by Jasonvvei** [comment]
Same here, it’s so ugly
