### ISSUE TITLE
Images/files Relative path issue

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#1304]
Hello guys, 
The relative path in gitbook editor is really a continuous issue. I can't mention a relative path for an image or a file like 
`[](../images/other/myimage.png)`

After publishing, the gitbook can't find the image as a link gets broken [example](http://rubyfu.net/content/en/index.html) 

I don't know why the editor insists to make a copy of the image in its current directory if I select the image from hard-drive. This behavior makes no sense and messes up the file structures 

I can see the number of the issues you guys are working on it and I understand it doesn't get solved by a few clicks. 

When I don't see an update for long time I always expect big changes ;)

**Comment by SeaDude** [comment]
If its any help: https://www.gitbook.com/book/seadude/linking/details

MANY examples of linking in this "treatise"!

**Comment by DonRichards** [comment]
Relative Links in general seem to be an issue. Summary.md links to folder. Once you click the URLs are no longer working. You'd need to navigate back to the Main readme and click from there event tho the Table of Contents is available everywhere.
