### ISSUE TITLE
Authentication is broken

### ISSUE THREAD

**Issue by jonathanpberger** [GitbookIO/gitbook#1305]
Hi,

When trying to clone a book that exists on github.com, auth repeatedly fails. I'm able to successfully auth into both Github and Gitbook via their websites, but I'm unable to auth using the Gitbook Editor. HALP!

Thanks,
JPB

**Comment by jonathanpberger** [comment]
UPDATE! I realized I had two-factor auth turned on in Github, which was screwing up the Gitbook Editor's attempts to auth. Closing.

**Comment by kataras** [comment]
Why closed? I have two-factor auth on but gitbook app can't authenticate me, this is not a desired behavior..

**Comment by rpanier** [comment]
same problem here
