### ISSUE TITLE
Links to .html files on 3.0.0-pre.15 lead to blank page

### ISSUE THREAD

**Issue by jeffmohr** [GitbookIO/gitbook#1312]
Running into an odd issue on pre.15 that I haven't seen before. We have .html files that contain page redirects for guides that we have renamed. What seems to happen now is that we are taken to an empty html page when you click on any of these links:

<img width="848" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1107862/15405300/2c077e56-1db6-11e6-90d0-9361873a33fe.png">

If you then click refresh, it loads the page as expected (either activates the redirect or displays the content of the html page - did some testing here to make sure it wasn't the redirect that was causing this and it happens with any html content).

Any idea what might be going on here?

**Comment by SamyPesse** [comment]
Correct me if I'm wrong: You have pure HTML files in your book source, then you have links to these HTML files in your markdown content?

The potential issue that I see is related to the AJAX loading, when you click a link in the book, it tries to load the file using AJAX and only update the body, but it will fail if the file has not been generated by GitBook.
Priori to v3.0.0, it was only using AJAX for links in the sidebar.

**Comment by SamyPesse** [comment]
I was able to reproduce the bug, I'm fixing it.

**Comment by jeffmohr** [comment]
Thanks @SamyPesse! What's the best way to pull in the latest version of the theme? Doesn't seem like I'm able to get the latest changes right now. I'm explicitly using `"theme": "theme-default";` and `gitbook install` didn't seem to do the trick.

**Comment by jeffmohr** [comment]
Nevermind, adding it as a plugin enabled me to pull the latest version in. Thanks again!
