### ISSUE TITLE
File save is too slow for me!!

### ISSUE THREAD

**Issue by aleen42** [GitbookIO/gitbook#1315]
When I want to save files each time, I should wait for a long time, because the editor has stopped to wait for saving.

**Comment by KINGSABRI** [comment]
Same as #1303, slowness in opening and saving for a not small book

**Comment by aleen42** [comment]
Is there any blocked processes resulting in it? The same problem won't happen in the old version editor 4.x.

**Comment by SamyPesse** [comment]
Closed in favour of #1303.

We are working on fixing it.
