### ISSUE TITLE
'Add to dictionary' functionality?

### ISSUE THREAD

**Issue by kulshekhar** [GitbookIO/gitbook#1317]
Is it possible to add new words to the built-in dictionary for a given language? This would be particularly helpful when writing technical books where a lot of valid words/acronyms aren't necessarily standard dictionary words.

**Comment by SamyPesse** [comment]
The next release of the editor will use the system spellchecker, so adding terms to your system's dictionary will work for the editor.

We plan on release this version in the coming weeks.

**Comment by thomasbiesaart** [comment]
Has this feature been released yet?

**Comment by jeremy-wilson** [comment]
Any word? It really bugs me that I have all these proofreading errors for words not in the dictionary. Hard to write a technical book when many of the words don't validate as correct.
