### ISSUE TITLE
The TOC has no number anymore

### ISSUE THREAD

**Issue by colingonglin** [GitbookIO/gitbook#1323]
I have noticed that the TOC has no number anymore.
Is this a regression or work as design? My TOC is big, so without the number it's hard for my readers to find specified chapter.

**Comment by SamyPesse** [comment]
This is disabled by default, but you can enable it by changing your `book.json`:

```js
{
    "pluginsConfig": {
        "theme-default": {
             "showLevel": true
        }
    }
}
```

**Comment by THWJ** [comment]
thank you very much, it works.
