### ISSUE TITLE
Bug for relative image when switching page

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#1326]
The AJAX navigation is causing a bug for relative image when changing page:

1. Go to https://samypesse.gitbooks.io/how-to-create-an-operating-system/content/chapter9/
2. Click on another page in the summary
3. Go back to the "Memory management" chapter
4. Image are not displayed anymore!

**Comment by SamyPesse** [comment]
It looks like it's only happening in Safari.

**Comment by jpreynat** [comment]
Safari doesn't seem to resolve the good URL for images at page change:

If switching from page `content/chapter9/` to page `content/chapter8/`, Safari will try to load the image `content/chapter8/image.png` at URL `content/chapter9/image.png`.
