### ISSUE TITLE
TOC links are not disabled for non-existing documents 

### ISSUE THREAD

**Issue by farcaller** [GitbookIO/gitbook#1331]
I have gitbook 3.0.2.

Taking a clean repo, I used `gitbook build` to generate the html. The link to chapters that don't exist are actual links, clicking them results in 404.

The render produced by gitbook website generates `<span>`s that are grayed out and not clickable.

Is this a regression or misconfiguration?

**Comment by farcaller** [comment]
When will this reach the builder on gitbook.com?

**Comment by jpreynat** [comment]
@farcaller: This has already been deployed on gitbook.com.

**Comment by farcaller** [comment]
I can still reproduce a regression: given this [SUMMARY.md](https://raw.githubusercontent.com/farcaller/nbtb/develop/SUMMARY.md), it renders [this](https://farcaller.gitbooks.io/nbtb/content/v/f7579730e31da9753d59f00446697eb81cff5ce3_1/). There is no way to determine if the link is actually a link as it used to be with the old version of gitbook (grayed out text and cursor change).
