### ISSUE TITLE
Anchor links in TOC don't scroll the page

### ISSUE THREAD

**Issue by akbr** [GitbookIO/gitbook#1337]
Concise example here: https://akbr.gitbooks.io/anchor/content/

Code here: https://github.com/akbr/anchor-test

Any insight?

**Comment by SamyPesse** [comment]
This is working for me on Safari (9.1.1 on El Capitan); if I click on "Anchor One" or "Anchor Two", it scrolls the page.

What browser are you using?

**Comment by akbr** [comment]
I'm using the most recent version of Chrome (v51.0.2704.63 m) on Windows 10.

To clarify: Clicking the anchor link doesn't scroll the page, but browsing directly to it (e.g., by clicking here: [https://akbr.gitbooks.io/anchor/content/#one](https://akbr.gitbooks.io/anchor/content/#one)) does.

**Comment by SeaDude** [comment]
Visiting https://akbr.gitbooks.io/anchor/content/, clicking on Anchor one or Anchor two in the TOC scrolls beautifully for me. Back and forth no problem. 

Firefox on Ubuntu 16.04

**Comment by jeffmohr** [comment]
I'm getting the same issue on Chrome (Version 50.0.2661.102) with OS X 10.10.5.

This used to be workaround code but seems like it no longer does the trick with Gitbook V3.

```
var target = window.location.hash;

window.location.hash = "";

$(document).ready(function() {
    setTimeout(function() {
        document.location.hash = target;
    }, 50);
});
```

**Comment by jeffmohr** [comment]
@SamyPesse any chance the fancy slower scroll that is used when clicking on an anchor link in the summary might be the culprit? And is there a way to disable that functionality?

**Comment by jeffmohr** [comment]
Odd, just another thing I stumbled upon was disabling the "anchors" plugin and adding "heading-anchors" seemed to resolve things for me.

**Comment by SeaDude** [comment]
If its any help: https://www.gitbook.com/book/seadude/linking/details 

There are MANY ways to link in Gitbook
