### ISSUE TITLE
Custom filters not available on pdf_footer

### ISSUE THREAD

**Issue by markomanninen** [GitbookIO/gitbook#1340]
It looks like custom filters from custom theme plugins are not available on pdf_footer template. Is it by design?

```
Template render error: (/Users/marko/Documents/gits/creativepowerofthefloweroflife/node_modules/gitbook-plugin-theme-creative/_layouts/ebook/pdf_footer.html)
Error: filter not found: dateparse
```

Filter works on other book project markdown pages. Filter template looks like:

`Updated: {{ file.mtime|dateparse("m/d/Y") }}`

and hook attached to the filter is:

```
filters: {
        dateparse: function(time, format) {
            return new Date(Date.parse(time)).format(format);
        }
}
```

Note: format function is an extension to Date object, not native...

**Comment by markomanninen** [comment]
I noticed there is a date filter, which uses moment.js, that I can use instead of my own dateparse filter, likewise:

`{{ file.mtime|date("MM/DD/YYYY") }}`

but format syntax is a bit different and I think custom fulters should work on plugin / theme templates...

**Comment by egoroschenya-sc** [comment]
+1, see also #1437
