### ISSUE TITLE
Some problems about plugins in engine 3.0.3

### ISSUE THREAD

**Issue by aleen42** [GitbookIO/gitbook#1342]
Hello, the function `head:end` of `book.html` has been deprecated? and what can I use instead?

**Comment by SamyPesse** [comment]
You can use the template files, create a `_layouts/website/page.html`:

```
{% extends template.self %}

{% block head %}
    {{ super() }}
    

    <!--- Add Your things here -->
{% endblock %}
```

You can also create this file (`_layouts/website/page.html`) directly in your book.

**Comment by aleen42** [comment]
And how can I access the `pluginConfigs` in a page.html?
