### ISSUE TITLE
Need a more obvious affordance to close comment sidebar

### ISSUE THREAD

**Issue by appsforartists** [GitbookIO/gitbook#1346]
Leaving a comment opens the Comments sidebar, which shifts the book content behind the Table of Contents sidebar.  There is not an obvious way to close the sidebar (and the Close button actually resolves the comment thread, as reported in #1345).

Clicking the comment count badge closes the sidebar, but this is not nearly obvious enough.  There should be a stronger affordance to close the sidebar and/or opening the Comments sidebar should close the Table of Contents.  (Perhaps change the treatment of the Comments sidebar to make it more clear that it's a drawer, and include [an arrow button](https://design.google.com/icons/#ic_keyboard_arrow_right) to close it.)

It's a bit ridiculous that you can't read the content and the comments simultaneously on a 15" display.

**Comment by sbaggott** [comment]
+1 to this. I kept closing comments and wondering why they didn't show up afterwards, until I realized what it actually does...
