### ISSUE TITLE
Closing a comment thread should be undoable

### ISSUE THREAD

**Issue by appsforartists** [GitbookIO/gitbook#1347]
Especially since it's too easy to close a comment thread accidentally (#1345), it should be easy to undo.

**Comment by nagim** [comment]
This one can be done.
Go to your book on gitbook.com, click on **Discussions** tab and click on **Closed**.
Find the comment thread that's been closed and click on it.
There's a **Reopen discussion** button at the bottom, click on it and it's restored.

**Comment by appsforartists** [comment]
That's way too complicated.

There ought to be a [snackbar](https://www.google.com/design/spec/components/snackbars-toasts.html#) that says "Comment thread marked as resolved.  UNDO", where clicking UNDO reopens the discussion.
