### ISSUE TITLE
Cannot get latex / maths symbols to display in 'published' books

### ISSUE THREAD

**Issue by thacker7** [GitbookIO/gitbook#1356]
Everything looks fine in edit mode.
But in 'published' books, just see raw characters 
e.g. $$y = ax +b$$

https://drewbuchan.gitbooks.io/test-markdown-and-latext/content/

what am i doing wrong?

**Comment by Yemolai** [comment]
Same in here:
https://yemolai.gitbooks.io/aprenda-c-na-pratica/content/capitulo_1.html
(at the list in the end I use some math expressions inside the bullet list)

the expressions aren't being parsed inside published books and are being displayed raw as this:

$$2,3\times10^{-308}$$ a $$1,7\times10^{308}$$

**Comment by nagim** [comment]
Hi,

Could you paste your `book.json` content?

Imre

**Comment by thacker7** [comment]
Hi Imre

I think this is it.
Thanks
Andrew

**Comment by nagim** [comment]
Don't see anything, must be left out?

**Comment by thacker7** [comment]
Sorry, you've lost me now. What else can I do to illustrate the problem?

**Comment by nagim** [comment]
You have a file name book.json in your book repo. Could you please open it
and copy-paste the content?
On Jun 6, 2016 2:17 PM, "thacker7" <notifications@github.com> wrote:

Sorry, you've lost me now. What else can I do to illustrate the problem?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GitbookIO/gitbook/issues/1356#issuecomment-223942359>,
or mute the thread
<https://github.com/notifications/unsubscribe/APdFOyV3NmR7KuB0wkLP35TYlaNDIzTOks5qJA_QgaJpZM4ItkBg>
.

**Comment by thacker7** [comment]
Okay, here it is. It is one of the plug-ins on your site.

{
    "plugins": [
        "autocover"
    ],
    "pluginsConfig": {}
}

**Comment by nagim** [comment]
OK, depending on what syntax your're using, you must add the `mathjax` or `katex` plugin to your book config (`book.json`):

```json
"plugins": [
        "autocover",
        "mathjax"
    ],
"pluginsConfig": {}
}
```

Run a build with the new config, it should be fine.

**Comment by act65** [comment]
same issue here.

**Comment by yeasy** [comment]
Well, seems some equation cannot be generated successfully in pdf, but can be shown in the html page content.

Like $$\frac{a}{b}$$.

**Comment by codekiln** [comment]
Same issue here - any update on this? 

books.json: 
```
{
  "plugins": [
    "mathjax",
    "include-codeblock",
    "ace"
  ],
  "pluginsConfig": {
    "include-codeblock": {
      "template": "ace",
      "unindent": true,
      "theme": "monokai"
    }
  }
}
```

Math looks great in edit mode, but in regular mode, all math is omitted.

I think I figured out that if you do Command R to refresh without cache in chrome, then it reloads the math in the published version, so maybe mathjax is using a cache.

**Comment by chrisjake** [comment]
I have same issue as @codekiln - latex does not display immediately in chrome but it appears on refresh.

**Comment by pbeltran** [comment]
Are there any updates here?
Same issue, latex renders beautifully in edit mode, but not in read mode or pdf (not even refreshing)

**Comment by pbeltran** [comment]
@thacker7 please could you tell us how did you got rendered math expressions in your book?

**Comment by WeiFoo** [comment]
Same issue. I even couldn't find book.json file on the website. new to gitbook

**Comment by xingdl2007** [comment]
Same issue in published book, just see raw math expressions, but edit/read mode is ok.

**Comment by Yemolai** [comment]
I had the same issue and solved it by editing the book.json file to include "mathjax" on plugins.

`book.json`
```
{
"plugins": ["autocover", "mathjax"],
"pluginsConfig": {}
}
```

**Comment by robie2011** [comment]
same issue: https://robertrajakone.gitbooks.io/mse2017hs/content/math.html

**Comment by auroneboss** [comment]
Is there still updated? I have the similar issue. And I find when I use "gitbook build" and "gitbook install" in my local repo, it never recognizes my book.json whatever it includes. 
Here is my book.json
`{
    "plugins": [
        "mathjax"
    ],
     "pluginsConfig": {}
}`
But I clone a repo from user athacker, when I use “gitbook build”, it reminds me to install mathjax.
Here is his book.json
`{
    "plugins": [
        "mathjax"
    ],
    "pluginsConfig": {}
}`
I nearlly give up. I have waste much time on it. Damn.
