### ISSUE TITLE
page.next should lead to actual next page, not next summary article

### ISSUE THREAD

**Issue by jpreynat** [GitbookIO/gitbook#1359]
Currently, generated `page.next` leads to the next article in summary.
When the next article is inside the same page (i.e. links contains a hash), we get stuck on the same page for navigation in `theme-default`.

**Comment by SamyPesse** [comment]
It can't be fixed, even if `page.next` includes the hash: the right navigation will scroll to the hash, but you'll still be stuck since no different page (with a different `page.next` has been fetched).
