### ISSUE TITLE
TypeError: content.replace is not a function

### ISSUE THREAD

**Issue by hanjoosten** [GitbookIO/gitbook#1360]
Today I have done some minor updates of [the documentation of Ampersand](https://www.gitbook.com/book/ampersandtarski/documentation), and I get [this build error](https://www.gitbook.com/book/ampersandtarski/documentation/build/5753d19a230b1f10005d0b5a). 

I reversed some of my own updates, but that didn't help. Whatever I do, the automatic build seems broken, which is beyond my knowledge. I would appreciate any help!

Some probably helpful info:
`Report Infos Book: ampersandtarski/documentation, Book ID: 55dd74e98538910f00270d76, Build ID: 5753d19a230b1f10005d0b5a, Version a2f919ec26cd688fdb4df647662a4310c2701ac3 and Stack gitbook/builder:1.5.3.`

**Comment by hanjoosten** [comment]
I saw that it is possible to choose a builder. Therfor, I tried the legacy builder. This builds OK. So there is something wrong with GitBook version is 3.0.3, that was not broken in GitBook version is 2.6.7
Until this is resolved, I have to use GitBook version is 2.6.7

**Comment by hanjoosten** [comment]
Hi @SamyPesse , any news yet? Is there anything more info you need?

**Comment by SamyPesse** [comment]
It's the same issue as #1374

I'm taking a look right now to debug and fix it for the next release.

**Comment by hanjoosten** [comment]
:+1:
