### ISSUE TITLE
Working in sub-directory

### ISSUE THREAD

**Issue by sateffen** [GitbookIO/gitbook#1361]
Like said in [this issue](https://github.com/GitbookIO/gitbook/issues/1224), the editor seems to ignore my book.json:

I'm using gitbook editor 5.0.5, installed gitbook 3.0.3, using gitbook-cli 2.2.0, so it's pretty much everything up to date. I've got a book.json looking like:

```
{
    "root": "./docs",
    "title": "tool",
    "description": "A utility tool"
}
```

in a folder structure looking like:

```
.git/
docs/
    README.md
    SUMMARY.md
    ... other markdown files and folders
src/
    sourcecode
package.json
book.json
README.md <-- readme for the project, NOT for the gitbook
```

When opening the folder as gitbook in the editor, it'll open my project files, but won't recognize the *SUMMARY.md* file properly. It doesn't show any structure.

The file-structure in the lower left corner shows the complete folder as well, not only the root set in the book.json

the editor works, but to be honest, it's not doing what I expect, every frustrating.

Building the book with `gitbook pdf` from the project folder creates a correct book.pdf, just like expected.

Any ideas?

Edit: I just saw, that you use a similar config of mine in this repository, but the gitbook editor ignores this as well.

**Comment by SamyPesse** [comment]
The current GitBook Editor doesn't support the `root` option and `GitBook v3`.

We are publishing an alpha version of the next GitBook Editor which fixes this. It will be release as stable in the coming weeks.

If you are using the desktop editor, send me an email at samy@gitbook.com and I can add you to the alpha.

**Comment by ryanwalls** [comment]
Would be nice to keep issues like this open until they are fixed so people can subscribe/track the progress.  I'm new to gitbook, but have been stuck on this for a few hours now.  Just happened to stumble on this closed issue.

**Comment by StudentForever** [comment]
hi

any update on this issue ?

thanks

**Comment by eddyerburgh** [comment]
Hi, I'm also interested in serving from docs/

**Comment by DRogue1337** [comment]
+1

**Comment by darknoon29** [comment]
Yes i would prefer to use a docs folder instead of the root too.

**Comment by antonioalegria** [comment]
Bump on this, would like to use this with the editor.

**Comment by EdisonValentimLopes** [comment]
HI.... I'm absolutelly beginner, but I need to edit "book.json" file to include  "mathjax plugin". Please, how to do this. thanks

**Comment by teone** [comment]
@SamyPesse any news on the desktop editor?

I downloaded it today, but look to not support yet the `root` option.
I get the error: `Could not load your book. Check your book.json for errors`, here is the content of my `book.json`:
```
{
  "title": "XOS-GUI User Documentation",
  "root": "./docs"
}
```
