### ISSUE TITLE
absolute url-path in navigation

### ISSUE THREAD

**Issue by ralphdd** [GitbookIO/gitbook#1362]
Hey,
in version 2.1.0 the href for navigation have an absolute paths (like ABC/index.html).
Since version 3.x the path looks like ABC/ . So offline browse (whole book to zip for mail) isn't possible. Because no browser knows that always index.html is the startpage in each folder. 
Is there a option to change this in book.json? 

Thanks

**Comment by Simran-B** [comment]
There is more broken than that: I have a link like `ABC/foo.html` but it doesn't work either. I have to drag it manually to the address bar in Chrome to go there.

Gitbook 3.1.0 that is. A lot of stuff appears to be broken in 3.x...

**Comment by ralphdd** [comment]
Is it possible to change gitbook generation that README-files are always generated to */index.html in navigation? Or to make this optional with a parameter in book.json?

Thanks

**Comment by ralphdd** [comment]
Ok, I think nobody is interested. But if someone have the same problem. 
I created a plugin for this, based on Gitbook Sample Plugin. I include JQuery and this code to included js-file:

`

$(document).ready(function(){
			$('a').not('[href^="http"],[href^="https"],[href^="mailto:"],[href*=".html#"],[href$=".html"]').each(function() {
					$(this).attr('href', function(index, value) {
							if (value.substr(0,1) !== "/") {
									//value = window.location.pathname + value;
									value =  value;
							}
							return value + "index.html" ;
					});
			});
` 

with this code my navigation runs offline and i can create a zip from my gitbook to share offline.

**Comment by zekedroid** [comment]
Same issue except we host our gitbook in S3 so the Introduction is broken as it points to `./` instead of `./index.html`. Just like @ralphdd I tried adding a script, which looks like this:

```var q = document.querySelector('body > div > div.book-summary > nav > ul > li:nth-child(1) > a');
q.href = `./index.html`;```

However, I have no way of running this on every page and gets overriden once the user navigates away from the first page.

Is there a way to run a script on every page? Does a gitbook plugin accomplish that?

**Comment by SamyPesse** [comment]
I'll add an option in GitBook v4 to disable the directory urls ("/" instead of "/index.html").

In the mid time you can use this script, but it'll not be compatible with GitBook v4.

**Comment by CharlesWiltgen** [comment]
> I'll add an option in GitBook v4 to disable the directory urls ("/" instead of "/index.html").

@SamyPesse, do you happen to have an update on this? (Thank you! 🤘)
