### ISSUE TITLE
Unable to type a piece of code as is

### ISSUE THREAD

**Issue by pankajroark** [GitbookIO/gitbook#1364]
I'm trying to put this:
def generate[P <: Platform[P]](source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ \* 2).write(sink)

but gitbook editor, both online and the desktop version show it as:
<img width="765" alt="screen shot 2016-06-07 at 10 14 52 am" src="https://cloud.githubusercontent.com/assets/664454/15867573/d2a5530a-2c98-11e6-9b11-462855bdc6f9.png">

It doesn't show the part inside parens. The preview looks ok though.

**Comment by pankajroark** [comment]
hmm... even github does the same. Let me try pasting it as code here:
`def generate[P <: Platform[P]](source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ * 2).write(sink)`

**Comment by pankajroark** [comment]
To summarize I'm trying to put this as code in gitbook editor:
`def generate[P <: Platform[P]](source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ * 2).write(sink)` 
but it shows as:
<img width="765" alt="screen shot 2016-06-07 at 10 14 52 am" src="https://cloud.githubusercontent.com/assets/664454/15867723/5abf2482-2c99-11e6-98c8-7a2e6095dce6.png">

on the screen.

**Comment by nagim** [comment]
Try escaping the some characters by preceding them with a backtick. This works on github:

`def generate\[P <: Platform[P]](source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ * 2).write(sink)`

Renders as:
def generate\[P <: Platform[P]](source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ * 2).write(sink)

**Comment by pankajroark** [comment]
I tried different escapings, this one seems to work but the backslash shows up in preview as well:
def generate[P <: Platform[P]]\(source: P#Source[Int], sink: P#Sink[Int]): TailProducer[P, Int] = source.map(_ * 2).write(sink)

**Comment by nagim** [comment]
I assume you're writing in markdown, right?
The problem is that this resembles to the link syntax in markdown, that's why your escaping works.
The backslash appearing: I'm pretty sure it appears in the editing window (left side), not the live preview (right side, see my screenshot):

![image](https://cloud.githubusercontent.com/assets/16205115/15886402/3872c694-2d5d-11e6-86a9-211b299da321.png)


I tested it and it won't appear in the build.
