### ISSUE TITLE
Add custom meta tags to generated HTML

### ISSUE THREAD

**Issue by sarus** [GitbookIO/gitbook#1365]
Is there anyway to add custom meta tags to the output HTML from gitbook?

As an example I would like to apply something like:

```
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
```

I imagine there are other uses for `meta` tags that would be useful if they could be configured in book.json or some other place.

Thanks!

**Comment by miguelmota** [comment]
Any update?
