### ISSUE TITLE
How to use a custom theme hosted on Github?

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1368]
I derived a custom theme from `theme-default`, added an option to `book.json`:

``` json
{
  ...
  "plugins": ["-search", "-sharing"],
  "theme": "git://github.com/Simran-B/gitbook-plugin-theme-arangodb.git",
  ...
}
```

then built the book using gitbook-cli@2.2.0 and Gitbook 3.1.0, but I still see it loading the `theme-default` plugin instead of mine.

What's the proper way to specify the a Github URL of a gitbook theme plugin?

**Comment by SamyPesse** [comment]
Can you test using GitBook 3.0.3? It's maybe a regression in GitBook 3.1.0.

**Comment by SamyPesse** [comment]
The theme should be specified as a plugin:

```
{
  ...
  "plugins": ["-search", "-sharing", "git://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"]
  ...
}
```

Also test using GitBook v3.0.3, there might be a regression for plugins listing in 3.1.0.

**Comment by Simran-B** [comment]
The docs imply that there's a separate key and say nothing about adding it to the plugin list:
https://toolchain.gitbook.com/config.html#theme

I'll retry in a minute.

**Comment by SamyPesse** [comment]
Oh yes, it's an error (I'm fixing it), we've started pre versions of GitBook v3 with this idea.

**Comment by Simran-B** [comment]
I'm running into an error with 3.0.3 and

```json
  "plugins": ["-search", "-sharing", "anchorjs", "piwik",
    "git://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"],
```

> info: installing plugin "git://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"
>
> Error: Unsupported URL Type: gitbook-plugin-git://github.com/Simran-B/gitbook-plugin-theme-arangodb.git@*

It either doesn't understand Github URLs at all, or it might need to be written differently...

- **https**://github.com/Simran-B/gitbook-plugin-theme-arangodb.git ?
- Simran-B/gitbook-plugin-theme-arangodb ?

**Comment by SamyPesse** [comment]
Sorry I've missed it:

```js
  "plugins": ["-search", "-sharing", "anchorjs", "piwik",
    "git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"],
```

**Comment by Simran-B** [comment]
Still barking with 3.0.3:

> info: installing plugin "git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"
> 
> Error: Unsupported URL Type: gitbook-plugin-git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git@*

**Comment by orangeturtle739** [comment]
Maybe try this: https://github.com/GitbookIO/gitbook/issues/1093?

**Comment by CoDEmanX** [comment]
I did try that (git+https...), see my last post. It appears to be broken.

**Comment by Simran-B** [comment]
I did try that (git+https...), see my last post. It appears to be broken.

**Comment by orangeturtle739** [comment]
```
{
    "plugins": [
        {
            "name": "theme-arangodb",
            "version": "git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git"
        }
    ]
}
```

Not just `git+https`?

**Comment by Simran-B** [comment]
Interesting, I didn't see this name + version thing. I will give that a shot. It would be odd though if this is the proper way to write it.

**Comment by Simran-B** [comment]
Using `{"name": ..., "version": "git+https://github.com/..."}`makes `gitbook install` actually work, although it says it would use NPM:

> info: install plugin "theme-arangodb" (git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git) from NPM with version git+https://github.com/Simran-B/gitbook-plugin-theme-arangodb.git

This should be documented, or changed so that git+https URLs can be directly used in the plugin list.
