### ISSUE TITLE
Search index created despite search plugin being turned off

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1369]
I disabled the search plugin in `book.json`:

```json
{
  "plugins": ["-search"]
}
```

and no magnify icon is found in the toolbar of the generated website, but unlike with Gitbook 2.x, the search index seems to be created although it's pointless:

![image](https://cloud.githubusercontent.com/assets/7819991/15904107/fc03842a-2daf-11e6-92f2-c2d9ba5887ce.png)

I'm using Gitbook 3.1.0. How can I fully disable the search?

**Comment by SamyPesse** [comment]
Can you test using GitBook 3.0.3? It's maybe a regression in GitBook 3.1.0

**Comment by Simran-B** [comment]
Same with 3.0.3, but `["-search", "-lunr"]` seems to do the trick.

**Comment by SamyPesse** [comment]
Yes, I forgot that we split it into 2 plugins, other search backend can be implemented (example: [algolia](https://github.com/GitbookIO/plugin-algolia)).
