### ISSUE TITLE
Chapter enumeration broken (showLevel in theme-default)

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1370]
I enabled `showLevel` in `book.json`...

``` json
  "pluginsConfig": {
    "theme-default": {
        "showLevel": true
    },
```

...  and the enumerations are shown, but they are all sub-lists of a non-existing level 1:

![image](https://cloud.githubusercontent.com/assets/7819991/15908243/f2c73b02-2dc0-11e6-825d-f40595b026a8.png)

How to fix that? It should show

**1.** Introduction
**2.** Getting Started
etc.

`SUMMARY.md`:

``` md
* [Getting Started](GettingStarted/README.md)
  * [Installing](GettingStarted/Installing/README.md)
  * [Using the Web Interface](GettingStarted/WebInterface.md)
* [Scalability](Scalability/README.md)
* [Data model & modeling](DataModeling/README.md)
  * [Concepts](DataModeling/Concepts.md)
  * [Databases](DataModeling/Databases/README.md)
  * [Collections](DataModeling/Collections/README.md)
* [Indexing](Indexing/README.md)
  * [Index Basics](Indexing/IndexBasics.md)
  * [Which index to use when](Indexing/WhichIndex.md)
  * [Index Utilization](Indexing/IndexUtilization.md)
```

**Comment by Simran-B** [comment]
I think this is actually caused by the added support for parts in the summary. If there's no part, all pages are considered to be belong to a fictional part 1 (thus the preceding **1.**).

If no parts are used, then they shouldn't be considered in enumerating the pages.

**Comment by noerw** [comment]
see https://github.com/GitbookIO/gitbook/issues/1301
