### ISSUE TITLE
Handling sub-blocks: documentation incomplete

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1371]
There should be at least one more paragraph below the code example I figure:

![image](https://cloud.githubusercontent.com/assets/7819991/15911626/e8b85ac8-2dd0-11e6-96e3-f6755774c7f1.png)

https://toolchain.gitbook.com/plugins/blocks.html#handling-sub-blocks

**Comment by attekei** [comment]
Could this be completed, or could at least someone tell that are sub-blocks currently supported?

Thanks to the GitBook developer team for a platform that is super easy to extend!

**Comment by Simran-B** [comment]
I found something regarding sub-blocks in the code, but I'm not sure what it actually does. It looks like you can pass an array of strings with the block names when registering the parent block. But will this make the renderer process these blocks and leave non-registered ones untouched? How can you figure what block is the parent block in the code of the child block?

**Comment by Simran-B** [comment]
Still lacking explanation on how to use sub-blocks, or if they are even supported:

https://github.com/GitbookIO/gitbook/blob/master/docs/plugins/blocks.md#handling-sub-blocks

@SamyPesse can you shed some light on this matter?

**Comment by murej** [comment]
Any movement on this? I'm trying to make it work, would love to at least understand if it is implemented in any way

**Comment by AaronO** [comment]
@murej @Simran-B @attekei These are implemented. Can you elaborate on what you're trying to achieve because they might not map well to what you're trying to implement ?

**Comment by murej** [comment]
Thanks for the quick reply! I want to create a simple columned layout. I've managed to make the following nearly work:
```
{% grid %}
  {% col 1 %}First
  {% col 1 %}Second
  {% col 3 %}{% video %}/assets/video.mp4{% endvideo %} // <-- not rendering block
{% endgrid %}
```
```
module.exports = {
  blocks: {
    grid: {
      blocks: ['col'],
      process: function(parentBlock) {
        var columns = '';
        console.log(parentBlock.blocks);
        parentBlock.blocks.forEach((block) => {
          columns += `<div style="flex: ${block.args[0]};">${block.body}</div>`;
        });

        return `<div style="display: flex;">${columns}</div>`;
      }
    }
  }
}
```

The problem I have left now is that it does not render blocks within sub-blocks...any ideas how to bypass that limitation?

**Comment by fragsalat** [comment]
Hey there. Is there any solution for this?
I've created a new block which wraps an image but the image is not parsed anymore.

```md
{% myblock %}
![Local Image](./images/<image_file_name>)
{% endmyblock %}
```

The block process function is called correctly and the output is ok but it's not handling the other stuff anymore.

Any idea?
