### ISSUE TITLE
Jupyter notebooks in gitbook

### ISSUE THREAD

**Issue by darribas** [GitbookIO/gitbook#1373]
Is it possible to integrate [Jupyter notebooks](http://jupyter.org/) with `gitbook`? I'm thinking the most straightforward way would be to convert the notebook into a stripped down HTML file and then have `gitbook` take it instead of a markdown one to be processed with the rest of the book (which could be written in markdown).  When I've tried this, I get:

``` node
[~/Desktop/test_book] $ gitbook build
info: 6 plugins are installed 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 4 pages 
info: found 4 asset files 
error: error while generating page "chapter-1/sub2.html": 

FileNotParsableError: "chapter-1/sub2.html" file cannot be parsed
[~/Desktop/test_book] $ 
```

Is there an easy way to get this working? I think it'd be super powerful!

**Comment by KelSolaar** [comment]
Found that issue while looking if integration was possible. It is something I would be definitely keen on seeing happening.

**Comment by dragon788** [comment]
Sounds like using nbconvert is the way to go. https://github.com/menpo/menpo-notebooks/issues/29#issuecomment-224915092
