### ISSUE TITLE
"GitBook module lodash doesn't exist"

### ISSUE THREAD

**Issue by canadaduane** [GitbookIO/gitbook#1376]
Whenever I load the following book (in a web browser), I see an error in the console, `Uncaught Error: GitBook module lodash doesn't exist`. I believe this has something to do with comments not working on the page as well. View the error console when you load this gitbook site:

http://www.bookofmormonorigins.com/ 

This does not occur locally when I run `gitbook serve`.

I've removed all plugins, and the problem persists.

**Comment by SamyPesse** [comment]
Error in the `comments` plugin, it has been fixed.

**Comment by andineck** [comment]
I get the same error. has the new version been published to npm already?

**Comment by canadaduane** [comment]
The issue was fixed for our book. I can't confirm if it was due to the fix
being published to npm, however.

**Comment by LiJohnson** [comment]
me too
