### ISSUE TITLE
deprecation notices triggered by gitbook itself

### ISSUE THREAD

**Issue by noerw** [GitbookIO/gitbook#1383]
When writing a [plugin](https://github.com/noerw/gitbook-plugin-localized-footer), i noticed that when adding the hook `'page:before'` deprecation warnings are triggered, although i never call any of these properties/functions myself:

```
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "book" property is deprecated, use "this" directly instead 
warn: "options" property is deprecated, use config.get(key) instead 
```

running `gitbook@3.1.0`

**Comment by leandro-costa** [comment]
maybe those messages are issued by 'fs'
```
var fs = require('fs'),
    footerString = '',
    hasFooterFile;
```
