### ISSUE TITLE
I am wondering about the version info? 

### ISSUE THREAD

**Issue by liuyanshi** [GitbookIO/gitbook#1384]
![](http://ww3.sinaimg.cn/large/006ghwUWgw1f4sof2jdulj30dy052gmr.jpg)
As the image shows , the command `gitbook -V` and `git current` show different version of gitbook??

**Comment by nagim** [comment]
The 2.2.0 is the version of the CLI, the 3.1.1 is the gitbook version.

**Comment by SeaDude** [comment]
Thanks @nagim : A little more clarity will help me: 

`gitbook version` or `gitbook -V` = version of "Gitbook CLI Toolchain"
'gitbook ls`          = version of "Gitbook"
`npm view gitbook version` = version of ?

Questions: 
1. What is the difference between "Gitbook" and the "Gitbook CLI Toolchain"
2. Why does `npm view gitbook version` give a different version than `gitbook version` ? 
3. What does `gitbook update` actually update? 
4. Is there a command to check the version of Offline Editor?

**Comment by nagim** [comment]
Hi,

In general:
GitBook is the toolchain for generating static sites from files written in lightweight markup languages.
GitBook CLI is just that: CLI. An interface that let's you interact with GitBook using the command line. It enables using commands like `gitbook serve` or `gitbook build`. If a new command is needed to be able to execute something, the CLI will be updated.

* `gitbook version` and `gitbook -V` will return the CLI version
* `gitbook ls` - lists the locally installed versions of gitbook (generator), the currently active is denoted with a `*`
* `npm view gitbook version` will give the highest version of gitbook currently available (published) on npm. `gitbook version` will yield the CLI version. `gitbook current` will give the currently active local version of gitbook (generator)
* `gitbook update` will update your locally installed gitbook (generator) instance. It will install the latest from npm
* No, there are no such command to check the Editor version, I think. It can be checked from the Editor itself.

Hope it's more clear now.

**Comment by SamyPesse** [comment]
With latest `gitbook-cli`, `gitbook -V` will also prints the GitBook version being used.

You can use `gitbook ls-remote` to list available versions.
