### ISSUE TITLE
does gitbook support a custom domain like xxx.me?

### ISSUE THREAD

**Issue by AlanCheen** [GitbookIO/gitbook#1386]
such as : yifeiyuan.me

I have set custom domain,but it seems not work

Thank you!

**Comment by SamyPesse** [comment]
Yes it should work fine. Did you point your DNS to `gitbooks.io` (https://help.gitbook.com/books/can-i-use-custom-domain.html) ?

**Comment by SamyPesse** [comment]
It looks like you didn't:

![screen shot 2016-06-15 at 19 00 39](https://cloud.githubusercontent.com/assets/845425/16089463/7ffc43ea-332b-11e6-8dbd-ae4e3f1fd5b1.png)

**Comment by AlanCheen** [comment]
Finally i know how to set DNS,it works~
Thanks for your reply!
