### ISSUE TITLE
anchor does not work 

### ISSUE THREAD

**Issue by snowdream** [GitbookIO/gitbook#1393]
Node: v5.4.0
gitbook cli: 2.2.0
gitbook: 3.1.1

gitbook:    https://snowdream86.gitbooks.io/awesome-android/content/
github: https://github.com/snowdream/awesome-android

The problem:
1. the summary does not well shown
1. the anchor does not work

**Comment by nagim** [comment]
Hi,

Looking into your files, I noticed that you are defining anchors using the `name` attribute (`<a name="anchorname"></a>`).
Try using the `id` attribute instead (`<a id="anchorname"></a>`), it will work.

Imre

**Comment by snowdream** [comment]
solved,thank you.@nagim
