### ISSUE TITLE
Theme extend not working

### ISSUE THREAD

**Issue by letmaik** [GitbookIO/gitbook#1399]
I am trying to extend the default theme, following the instructions at https://toolchain.gitbook.com/themes/. However, the extension doesn't seem to be picked up.

My extension: https://github.com/covjson/cookbook/blob/master/_layouts/layout.html
What I want to extend: https://github.com/GitbookIO/theme-default/blob/master/_layouts/layout.html

I don't see my extended code in the HTML output anywhere. What's wrong here? I ran this locally but also on gitbook.com (https://reading-escience-centre.gitbooks.io/coveragejson-cookbook/content/)

**Comment by neothemachine** [comment]
It's working now, no idea why.

**Comment by Taras-S** [comment]
Its magic, dude

**Comment by kjhenner** [comment]
@letmaik Any chance you're using multiple languages? I ran into this issue myself and realized that the _layouts directory has to be within the language directory (e.g. /ja_jp/_layouts) or a simlink from within the language directory to a _layouts in the root directory. Not sure if this is documented. I didn't see it anywhere.

**Comment by letmaik** [comment]
Nope, just a single language. See the repo I linked to.

**Comment by AaronO** [comment]
@letmaik Where you trying to extend the theme to add branding, e.g: a custom header bar (with logo and custom links) ? Or something completely different ?

We noticed that branding was such a common need, but painful to do (manually changing HTML/template files), so we built out-of-the-box branding into our new release (currently in beta: https://beta.gitbook.com/)

**Comment by letmaik** [comment]
No, it was about including a piece of JS on every page.

**Comment by AaronO** [comment]
@letmaik If that's what you're looking for JS, there are plugins that allow that with minimal configuration changes.

What kind of JS if you don't mind me asking ? (looking to better understand your original need so we can maybe solve it with a 1st-party solution if it makes sense)

**Comment by letmaik** [comment]
I'm embedding the book as an iframe and want to have a way to navigate to a specific book page via URL anchors. I got it working in one direction already, but not the other. For example, the URL https://covjson.org/cookbook/#first-domain dynamically loads the specific book page inside an iframe. But then the problem is that the URL doesn't update when you navigate inside the book. And for that I need to include some JavaScript in the book which communicates the current page to the host page so that it updates the hash anchor.
