### ISSUE TITLE
parse summary error

### ISSUE THREAD

**Issue by xNok** [GitbookIO/gitbook#1400]
When you use the following SUMMARY.md [from gitbook documentation](http://toolchain.gitbook.com/pages.html)

```
# Summary

### Part I

* [Writing is nice](part1/writing.md)
* [GitBook is nice](part1/gitbook.md)

### Part II

* [We love feedback](part2/feedback_please.md)
* [Better tools for authors](part2/better_tools.md)
```

You get the following table of content/summary

```
Table of Contents

Part I
Introduction
Writing is nice 
GitBook is nice 

Part II
We love feedback
Better tools for authors
```

**Comment by SamyPesse** [comment]
What's wrong with this table of contents?

**Comment by xNok** [comment]
The **Introduction** corresponding to the main README.md is added by default into the part I. This comportement seem quite strange to me.
