### ISSUE TITLE
Translation of Table of Contents does not work

### ISSUE THREAD

**Issue by bkolbe** [GitbookIO/gitbook#1408]
I have downloaded the version 3.1.1 and have book.json containing "language":"de". But the PDF hast still table of contents instead of Inhaltsverzeichnis.
What am i doing wrong.
I have double checked the config file with other languages. In html header i can find the right language but the strings are not translated.

**Comment by tonytonyjan** [comment]
I've opened some similar issues few days ago, but they are all closed without any response, feeling extremely difficult to report a bug to gitbook team.

https://github.com/GitbookIO/gitbook/issues/1421
https://github.com/GitbookIO/gitbook/issues/1412

**Comment by SamyPesse** [comment]
@tonytonyjan Sorry, I'll look into it today or tomorrow.

**Comment by xldrkp** [comment]
I experienced exactly the same problem with "de".
