### ISSUE TITLE
Error to edit book

### ISSUE THREAD

**Issue by leonardoaraujosantos** [GitbookIO/gitbook#1409]
![errorgitbook](https://cloud.githubusercontent.com/assets/898383/16380747/be91271c-3c70-11e6-9687-2e24f76189d7.png)
Hi guys I'm having problems to edit my book after my last update, the link is here
https://www.gitbook.com/book/leonardoaraujosantos/artificial-inteligence/edit

It says unexpected error 0, while opening the book

Actually it seems that this happens with everybook that I try to edit

**Comment by AaronO** [comment]
@leonardoaraujosantos Hey Leonardo, following up here from your Zendesk ticket.

Can you do a hard refresh of the editor page ?

(I'm not seeing any authentication requests/errors in our logs related to your account)

**Comment by AaronO** [comment]
@leonardoaraujosantos Just wanted to specify, that it is indeed an authentication issue somewhere, your content is all there. Let me know when you've been able to give that a try and hopefully we'll have something meaningful come up in the logs :)

**Comment by scar-sheepmiemie** [comment]
@AaronO The same here...I found some posts several months ago, and I tried to rename the book, it did not work.
https://www.gitbook.com/book/scar-sheepmiemie/growing-every-day-/edit

**Comment by AaronO** [comment]
@scar-sheepmiemie @leonardoaraujosantos Can you copy a screenshot of your browser's JS console ?

That should tell us what the error is, it seems like it's happening due to a cache/auth/browser issue.

**Comment by scar-sheepmiemie** [comment]
@AaronO Sure! Here it is.
![gitbook-cant load book-js screen shot](https://cloud.githubusercontent.com/assets/5073613/16386026/13149e5e-3c44-11e6-892c-bb152d84454f.png)

**Comment by leonardoaraujosantos** [comment]
Hi I take now the screenshoot (Sorry for the delay)

![javascripterror](https://cloud.githubusercontent.com/assets/898383/16386512/d46a7bc0-3c88-11e6-88e1-fff82f38ca4f.png)

**Comment by leonardoaraujosantos** [comment]
Guys I've also tried on a different browser, still the same error

**Comment by AaronO** [comment]
@scar-sheepmiemie @leonardoaraujosantos Thanks a lot for the reports, this should be quite easy to fix.

It's caused by a misconfiguration of the `nginx` server in front of our `git-server`, I deployed an update earlier today that added `http2` support, give me 15-30mn to fix and update this.

**Comment by scar-sheepmiemie** [comment]
@AaronO Sounds great! Thanks!

**Comment by AaronO** [comment]
@leonardoaraujosantos @scar-sheepmiemie Ok, just deployed an update, can you guys try again ?

Hitting https://git.gitbook.com/ directly should also be good enough to try

**Comment by leonardoaraujosantos** [comment]
Guys for me it worked! Everything is back to normal

**Comment by AaronO** [comment]
@leonardoaraujosantos Perfect :) Sorry for the inconvenience, thanks for helping to fix this !

**Comment by leonardoaraujosantos** [comment]
Thank you! Was super cool to help investigate the problem.

**Comment by scar-sheepmiemie** [comment]
Wow, so quick! It works again! Thanks!
