### ISSUE TITLE
Branch selection shows nothing but master.

### ISSUE THREAD

**Issue by turbo** [GitbookIO/gitbook#1410]
I run into this problem again and again, sometimes it works, sometimes it doesn't.

I want to publish a Gitbook from a branch (not master), here's what I did:
- Create new book
- Integrate with GitHub repo (successfully)
- Edit in the `docs` branch and commit (successfully)
- Build _fails_, because I can't select any branch but `master`

This is how the editor looks like (I can edit and commit to `docs`, just like I want):

![docs](https://cloud.githubusercontent.com/assets/8023543/16385626/e08182f0-3c8d-11e6-8bd0-5b4596550820.png)

...and the GitHub repo gets updates, so integration works just fine.

But I cannot switch the building branch, because the settings dropdown doesn't list the actual branches:

![settings](https://cloud.githubusercontent.com/assets/8023543/16385730/35f92d1e-3c8e-11e6-963f-ce4edb8be966.png)

I had this issue once before with another Gitbook, but that resolved itself randomly. Now I'm stuck here, again.

**Comment by nagim** [comment]
Unfortunately, it has some delay updating the list of branches.

**Comment by SamyPesse** [comment]
Is it working now?

**Comment by Wilfred** [comment]
I'm seeing exactly the same issue on https://www.gitbook.com/book/wilfredh/ag-el/settings
