### ISSUE TITLE
Markdown: trailing mailto: link markup are wrongly translated

### ISSUE THREAD

**Issue by Vdragon** [GitbookIO/gitbook#1411]
Hi GitBook developers, 
I made a page with a e-mail address at the end:
![_023](https://cloud.githubusercontent.com/assets/1192163/16399110/310a3a68-3d02-11e6-9c80-d5cfb022082e.png)

in ReText editor it is translated as:

```
<p>Please contact the following e-mail address for any problems about the use of the copyright material:<br>
<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#86;&#100;&#114;&#97;&#103;&#111;&#110;&#46;&#84;&#97;&#105;&#119;&#97;&#110;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;">&#86;&#100;&#114;&#97;&#103;&#111;&#110;&#46;&#84;&#97;&#105;&#119;&#97;&#110;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;</a></p>
```

But in [GitBook build](https://vdragon.gitbooks.io/undertale_unofficial_novel/content/English/) it turns out to be:

```
<h2 id="intellectual-property-conflict-resolution-policy">Intellectual Property Conflict Resolution Policy</h2>
<p>Please contact the following e-mail address for any problems about the use of the copyright material:  </p>
<vdragon.taiwan@gmail.com>
</vdragon.taiwan@gmail.com>
```

The URL markup is wrongly translated to a tag.

source repo: https://github.com/Vdragon/UNDERTALE_Unofficial_Novel

**Comment by SamyPesse** [comment]
It looks like it's working with the new parser.

Can you paste me the markdown source of a failing page?

**Comment by Vdragon** [comment]
@SamyPesse It's still available on the link above, but I created a copy anyway...
https://gist.github.com/Vdragon/4da96a7884a34d261a5000f9f215edfa

**Comment by Vdragon** [comment]
Oops I thought you're asking HTML source, here's the Markdown source:
https://gist.github.com/Vdragon/212b825890cf568f3e3a8e2f3368e82e
