### ISSUE TITLE
How to set default locale?

### ISSUE THREAD

**Issue by tonytonyjan** [GitbookIO/gitbook#1412]
I knew that Gitbook supports multi-languages by adding a `LANGS.md` and creating sub directory for each language, but I wonder if there is any way to set default locale.

I am going to write my book only in Japanese, even though I set `"language": "ja"` in `book.json`, the web UI is still in English. Did I miss anything?

**Comment by SamyPesse** [comment]
The default locale is the first language listed in the `LANGS.md`, for example in the following content it will be English:

```
# Languages

* [English](en)
* [French](fr)
```

**Comment by tonytonyjan** [comment]
Please don't close this, this is really an unsolved issue.

My question is as same as @dcormier [asked in slack](https://gitbook-community.slack.com/archives/general/p1464890128000836).

**Comment by tonytonyjan** [comment]
@SamyPesse 

I am not writing multi-languages. I have tried to created a folder `ja`  and a `LANGS.md` but in vain. The UI is still in English, and the web root became a nonsense page asking me to choose a language (there is only one language, I am not writing multi-languages.).

**Comment by hems** [comment]
Indeed it would be ideal to have a default locale and let people choose the other locales from a slick drop down in a corner, perhaps with flags ? 

is it too much to ask ? 😃
