### ISSUE TITLE
Add plugin preview on editor

### ISSUE THREAD

**Issue by leonardoaraujosantos** [GitbookIO/gitbook#1415]
Guys is possible to have the plugin output (for example ace code plugin) on the editor?

For instance if we type something like....

{%ace edit=true, lang='c_cpp'%}
// This is a hello world program for C.
# include <stdio.h>

int main(){
  printf("Hello World!");
  return 1;
}
{%endace%}

Output on the editor.....

![editorpluginout](https://cloud.githubusercontent.com/assets/898383/16411468/175a613e-3d1f-11e6-8db4-30bda1465435.png)

Output after publish
![codeoutace](https://cloud.githubusercontent.com/assets/898383/16411422/ec28f818-3d1e-11e6-97f1-ff94623d1910.png)

**Comment by TuningGuide** [comment]
That would be really helpfull.
