### ISSUE TITLE
em-dash is broken

### ISSUE THREAD

**Issue by farcaller** [GitbookIO/gitbook#1416]
Previously, `---` would insert `—` and `--` would insert `–`. It either got broken recently (don't see this behavior in today build) or it was never supported and I'm imagining things from another markdown parser.

Can it be fixed? Those two are important typography symbols.

`...` and ``` ``...''``` transformations are also useful.

**Comment by SamyPesse** [comment]
GitBook never supported smartypants.

It can be implemented by a plugin, for example using [typogr](https://www.npmjs.com/package/typogr).

Closing this issue, I'll take a look if I have time to build this plugin.

**Comment by nathanwebb** [comment]
Just to save anyone's time - I've added a typogr plugin, which works well for me.

to enable, just add "typogr" to the list of plugins in book.json
