### ISSUE TITLE
Can not search Chinese charater?

### ISSUE THREAD

**Issue by marchtian** [GitbookIO/gitbook#1419]
Hi!
I use Gitbook to build web pages with Chinese, it's so cool . 
When I try to search any Chinese charater like '关于', no result matching.
Is this a bug? Or what should I do?
Thanks!

**Comment by nagim** [comment]
Hi,

The default search backend (lunr) does not support searching Chinese characters.
However, there's a plugin for that, check that out: https://plugins.gitbook.com/plugin/search-jieba

**Comment by marchtian** [comment]
It's OK now, thanks!

**Comment by qqbuby** [comment]
It looks good to me. @marchtian 

https://github.com/gitbook-plugins/gitbook-plugin-search-pro
