### ISSUE TITLE
RTL table of contents

### ISSUE THREAD

**Issue by prp-e** [GitbookIO/gitbook#1420]
When I checked pdf output, I noticed that Table of Content is LTR, I also checked options, and language of my book was "Persian". 
Now, what can I do?

**Comment by SamyPesse** [comment]
RTL is not supported for the Table of Contents, I'll take a look as soon as possible to fix this.

**Comment by boustanihani** [comment]
Any updates on this :) ?

**Comment by Eng-Fouad** [comment]
Any updates regarding this?

**Comment by Eng-Fouad** [comment]
https://gist.github.com/Eng-Fouad/1b769d85b3dc7e8e1b774db3cda24b13
