### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by tonytonyjan** [GitbookIO/gitbook#1421]
I found there is an [_i18n folder](https://github.com/GitbookIO/theme-default/tree/master/_i18n) in default theme, how can I make use of them? I can't find any document about it.

My question is as same as @dcormier [asked in slack](https://gitbook-community.slack.com/archives/general/p1464890128000836).

**Comment by Lin-Buo-Ren** [comment]
L10N is documented [here](https://toolchain.gitbook.com/languages.html)

**Comment by tonytonyjan** [comment]
@Lin-Buo-Ren I knew that page, but it's not what I'm looking for. What you mentioned is i18n for content, not UI (such as search field placeholder, footer wording, font name, etc).

 I am pretty sure there hasn't been a document about it yet.

**Comment by SamyPesse** [comment]
You can set the language using `language` option in the `book.json` (http://toolchain.gitbook.com/config.html).

For example to use french:

```
{
    "language": "fr"
}
```

For multi-lingual books, this option is set automatically according to the `LANGS.md` file.

**Comment by tonytonyjan** [comment]
@SamyPesse Should this be a bug? I wonder.

```
$ gitbook --version
CLI version: 2.3.0
GitBook version: 3.1.1
```

![](https://i.imgur.com/dMJFdPQ.png)
![](https://i.imgur.com/hAhY3pC.png)
