### ISSUE TITLE
Website or PDF output?

### ISSUE THREAD

**Issue by carlosdelfino** [GitbookIO/gitbook#1424]
I need at a certain point of my book to identify the output format, if website I uses iframes to display circuits.io website information of AutoDesk, if the format is PDF will use a  image in place, how can I do this?

ps. Great project, I hope to have many books written one day.

**Comment by SamyPesse** [comment]
Currently integrating an iframe can be done using HTML in your markdown:

```
<iframe src="..." />
```

But on PDF, it will fail to display. A solution might be a plugin to conditionally display the iframe on website and a fallback image (maybe an auto screenshot of the page) with a link on PDF.

I don't have time right now to implement such a plugin, but I've added the tag `plugin-idea` to keep a record of it.

**Comment by carlosdelfino** [comment]
Who can develop plugins?
What steps should I follow to learn how to develop them?

Was it possible the variable output.name and output.format be reading too? so suffice query them with a {% if output.format == "pdf" %} to choose you want to render.

Thank you.

**Comment by noerw** [comment]
Anyone can. Here are the (still incomplete?) docs: https://developer.gitbook.com/plugins/

For renderer adaptive output have a look at the [youtubex plugin](https://github.com/ymcatar/gitbook-plugin-youtubex/blob/master/index.js)
