### ISSUE TITLE
Accessing variables from book.json in templating is not clear

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/gitbook#1425]
http://toolchain.gitbook.com/templating/variables.html

It is quite clear that `config` contains the whole `book.json`. But it is not clear what `book` contains, especially that it can be used to access the `variables` property of `book.json`.

**Comment by vanthome** [comment]
for me this feature does not seem to work at all.
I have this in book.json:

```
  "variables": {
    "applicationName": "xxx"
  },
```
and `{{applicationName}}` does not get expanded accordingly.

**Comment by panva** [comment]
doesn't work for me either, i have to reference these like `{{ book.applicationName }}`

**Comment by cpsubrian** [comment]
I ran into this, and `{{config.[whatever]}}` worked for me. The docs are either out-of-date or something is broken, but this was a workaround for me.
