### ISSUE TITLE
Variable support in gitbook 3

### ISSUE THREAD

**Issue by retohugi** [GitbookIO/gitbook#1426]
Hi

We've been generating a dynamic summary file with the help  of variables. Example:

Example SUMMARY.md:

```
* [Introduction](README.md)

{% set dir = "sub-chapters" %}
{% include "./sub-chapters/SUMMARY.md" %}
```

Where the sub-chapters/SUMMARY.md contains:

```
# Summary

* [some content]({{ dir }}/README.md)
```

This results in one summary in the index file containing the summary content of both summary files.

It seems like the variable `dir` is not replaced anymore in Gitbook 3. Can you confirm if this is a bug or intended behaviour for Gitbook 3 (it works great with 2.6). Any workarounds or alternative ways to get the same result are much appreciated.

cheers, reto

**Comment by postwait** [comment]
I'm on version 3.3.2 and I can't even get the include work.


SUMMARY.md
```
# Summary

 * Modules
{% include "./modules/inventory.md" %}
```

modules/inventory.md
```
# Modules

   * [module1](modules/module1.md)
   * [module2](modules/module2.md)
```

The individual modules never show up in my summary and are thusly absent from the book.

**Comment by mblakele** [comment]
related: #1504
