### ISSUE TITLE
Error: Reference Can not be updated

### ISSUE THREAD

**Issue by carlosdelfino** [GitbookIO/gitbook#1429]
At some time I migrated one Github project for GitBook (https://www.gitbook.com/book/git-na-pratica/git-na-pratica).

I do not know why at the time, I did the migration to make it integrated, today decided to join the project between the two tools, but at the end of the configuration always get the following error message when I try to save the online editor:

Reference Can not be updated

Message Screen:
![captura de tela 2016-07-06 12 49 07](https://cloud.githubusercontent.com/assets/369056/16624919/fd8b9fce-4378-11e6-99e5-e201f09089a0.png)

**Comment by nagim** [comment]
Do you happen to have the files opened in another editor or tool at the same time?

**Comment by carlosdelfino** [comment]
Yes always work with two screens open, but never had problems like this.

I did some reconfigurations, how to remove and add the settings of GitHub and everything returned to normal onte in the late afternoon, but I opened a new issue number #1433 for today to begin my work with the book I found that I lost everything, but Interestingly, yesterday to close the day was all there properly.
