### ISSUE TITLE
Support for AsciiDoc admonition paragraphs

### ISSUE THREAD

**Issue by DanielSWolf** [GitbookIO/gitbook#1430]
[Admonitions](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference) are a great AsciiDoc feature that allows you to highlight some text in a meaningful way. They are meant to look something like this:

![image](https://cloud.githubusercontent.com/assets/5963162/16645695/f9100fe0-4425-11e6-9118-f1ac59f11b55.png)

Instead, GitBook renders them like this, which is rather useless:

![image](https://cloud.githubusercontent.com/assets/5963162/16645726/3143467a-4426-11e6-9343-b4a2574f7d94.png)

It shouldn't be hard to get these admonitions to look better:
- Hide the table borders (except for the middle line)
- Assign a fixed width to the left cell
- Instead of writing "Note", "Tip", etc., use these unicode characters in a large text size:
  - NOTE: ℹ (INFORMATION SOURCE)
  - TIP: 💡 (ELECTRIC LIGHT BULB)
  - IMPORTANT: ☝ (WHITE UP POINTING INDEX)
  - WARNING: ⚠ (WARNING SIGN)
  - CAUTION: ⚡ (HIGH VOLTAGE SIGN)

**Comment by erixtekila** [comment]
That may be of interest 
https://github.com/erixtekila/gitbook-plugin-richquotes

**Comment by nagim** [comment]
Or this: https://plugins.gitbook.com/plugin/callouts

**Comment by DanielSWolf** [comment]
Thanks, that looks interesting. Still, given that admonition paragraphs are part of the AsciiDoc standard, I'd have hoped that they work out of the box.

**Comment by msavy** [comment]
@DanielSWolf As it looks like the fixes for this issue aren't going to be merged any time soon, I've [created the asciidoc-admonition-icons GitBook plugin](https://plugins.gitbook.com/plugin/asciidoc-admonition-icons) to restore the Asciidoc(tor) admonition paragraph icons. 

Its default styling is almost identical to the standard Asciidoctor theme, with some minor colour changes to better match the GitBook style. 

You can, of course, [override the glyphs and styling in configuration](https://github.com/msavy/gitbook-plugin-asciidoc-admonition-icons/#configuration). Check out the docs for more on that.

- GitBook plugin page: https://plugins.gitbook.com/plugin/asciidoc-admonition-icons
- GitHub repo: https://github.com/msavy/gitbook-plugin-asciidoc-admonition-icons/
