### ISSUE TITLE
Loss of content, how to recover?

### ISSUE THREAD

**Issue by carlosdelfino** [GitbookIO/gitbook#1433]
Loss of content, how to recover?

Yesterday I made some edits to the book I'm writing that can be seen in this link where are intact: http://ilp.carlosdelfino.eti.br/v/cb274e0792d118101520540268c0ba1aa46971c2/capitulo38.html

But now to go do not think these changes is as if there were, although they can be seen at the link above, and only see the contents of the chapter in question, and perhaps others in the same situation as the log github two days ago .

What happened? how can I retrieve the contents of the version on this link: http://ilp.carlosdelfino.eti.br/v/cb274e0792d118101520540268c0ba1aa46971c2/

Maybe I did something wrong, or perhaps a mistake tool, yesterday intervened in the very settings, including downloading a copy for my machine with the git tool, but this always fighting when sending to the server.

Is there how to recover?

**Comment by carlosdelfino** [comment]
Good afternoon everyone.

I managed to rescue the stuff I lost, so I'll replace everything in place with this material. I need to use it tonight during class that will teach.

I would like to find out what may have been wrong, it was my mistake and how to avoid it. I have been keeping a local bakcup of my work using Gitbook desktop.

but once I appreciate this tool and prabenizo the excellent work.

**Comment by qizheng3** [comment]
Exactly the same issue!! I lost all the stuff I added yesterday (~8 hrs work). That was way too terrible!
