### ISSUE TITLE
ParseError: KaTeX parse error: Expected 'EOF', 

### ISSUE THREAD

**Issue by carlosdelfino** [GitbookIO/gitbook#1436]
Good evening, please

what's wrong in the text below, it can be found in the link https://www.gitbook.com/book/cursoarduino/introducao-a-linguagem-de-programacao/edit#/edit/master/questoessobrealgoritmoportugol.md, I'm using Katex to format my formulas and get an error in the x line, the error is after the text:

```
1. Faça um Algoritmo para caclular o estoque médio de uma peça, sendo que **ESTOQUEMÉDIO = (QUANTIDADE MÍNIMA + QUANTIDADE MÁXIMA) / 2**.

2. Construa um algoritmo que:
  1. Leia a cotação do Dólar.
  2. Leia um valor em Dólares.
  3. Converta esse valor para Real.
  4. Mostre o resultado.

3. Construa um algoritmo para pagamento de comissão de vendedores de peças, levando-se em consideração que sua comissão será de 5% do total de venda e que você tem os seguintes dados:

4. Calcular e exibir a média ponderada de 2 notas dadas. (nota1 = peso 6 e nota2 = peso 4)

5. Converter uma temperatura em Fahrenheit para Celsius e mostrar o resultado:

$$
 F=(C * 1.8) + 32
$$ $$
 C = (F -32 ) / 1.8 
$$$$
 K = C + 273.15
$$

6. Reajustar um salário em 17,75%

7. Calcular o desconto de 23% sobre o preço de um produto.
```

error:
Template render error: (/tmp/book/questoessobrealgoritmoportugol.md)
  ParseError: KaTeX parse error: Expected 'EOF', got 'á' at position 22: ajustar um salá̲rio em 17,75%

**Comment by nagim** [comment]
I think you're not using the $$ limiters correctly, so it thinks that the `6. Reajustar um salário em 17,75%` also belong to the formula, where the `á` character is not supported.

Try delimiting your formulas like this:

```
$$
 F=(C * 1.8) + 32
$$

$$
 C = (F -32 ) / 1.8 
$$

$$
 K = C + 273.15
$$
```

Hope it helps!

**Comment by nagim** [comment]
If this doesn't work, check the raw content line in the file, looks like this:

`6. Reajustar um sal&aacute;rio em 17,75%`

You can try and change this to a real `á` character.

**Comment by carlosdelfino** [comment]
I avoided the line jump to avoid the spacing and loss list numeration.

I've done the setting for use of `&acute;` the text font.

But it is a failure in word processing, as it should not do analysis of texts outside the delimiters also realized that if internal accents formulas occur the same mistakes.

```
5. Converter uma temperatura em Fahrenheit para Celsius e mostrar o resultado:

$$
 F=(C * 1.8) + 32
$$  $$
 C = (F -32 ) / 1.8 
$$ $$
 K = C + 273.15
$$ 

6. Reajustar um sal&aacute;rio em 17,75%
```
