### ISSUE TITLE
Extended filters and blocks can not apply to template files

### ISSUE THREAD

**Issue by ioslh** [GitbookIO/gitbook#1437]
At first I want to add a description meta tag to every page, which is based on the content of current `page.content`, so I may need to extend the default template file( by adding an extra  `_layouts/website/page.html` file )  and add a customized filter to substring the `page.content`, or to do some more complex convertions, but then after several times of trial I found EXTENDED FILTERS AND BLOCKS CAN NOT APPLY TO TEMPLATE FILES, they are only valid in markdown files.

I was wondering am I doing something wrong? or are you meant to do it that way? Looking forward to your answer. thank you.

( For your convenient testing, I created a [repo](https://github.com/ioslh/for-gitbook-test) which includes the least required files; I tried to add a `youtube` tag in a markdown file, it works; But when I move the `youtube` block tag into a html template file, build failed because `unknown block tag: youtube`)

My English is very poor, hope I expressed myself appropriately

**Comment by akshayrawat** [comment]
Is there a way to apply filters on templates, layouts rather than just markdown files?

>
CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by egoroschenya-sc** [comment]
+1

**Comment by capripot** [comment]
+1

**Comment by capripot** [comment]
@SamyPesse Does the `_layout` files get crushed through [createTemplateEngine](https://github.com/GitbookIO/gitbook/blob/master/packages/gitbook/src/output/createTemplateEngine.js#L31) that includes the plugin filters?

**Comment by capripot** [comment]
@ioslh @egoroschenya-sc #1804 fixes the problem

**Comment by cmacdonnacha** [comment]
@capripot  is this in the latest release?
