### ISSUE TITLE
how can I display the list of number? 

### ISSUE THREAD

**Issue by fangge** [GitbookIO/gitbook#1439]
update to the gitbook 3.0, I found that the list of number has disappeared, how can I get it back?

**Comment by zhangzq** [comment]
up. I need it too. @fangge

**Comment by cheogo** [comment]
me too ...

**Comment by SamyPesse** [comment]
Are you talking about the number in the Table of Contents ?

**Comment by ilovesusu** [comment]
I need the directory number
eg:
1.0 xxx
    1.1 xxx 
2.0 xxx
What do I need to do?
