### ISSUE TITLE
Gitbook Editor 6.0.3 review 

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#1440]
Hi @all

First, contrgrats for the complet new shape shifting and fixing long list of bugs. As I said before, when you don't show updates for long time that means you're working on something big.

### System Information

* Ubuntu 16.4 TLS
* Gitbook desktop editor 6.0.3 
* Create a new book \(local repository only\)

Here the list of issues I've notice

#### Creating sub-chapter disapeared

* I can't create sub-chapter anymore, even creating a new-chapter doesn't gets reflected in SUMMRY.md
* Creating a new chapter dosn't create a new file but chapter keeps existing after closing gitbook editor 
* File and folder tree in the sidebar disapeared

#### Create a new File, Folder and Summary  
Nothing gets created on the local disk

#### Spellchecking & Proofreading
Spellchecking & Proofreading are not working, both are enabled

#### Can't find files 
I can't see 
- book.json 
- Imported images
  - when I import and image it says it's in `/assets/cluster9.png`. Whoever there is not folder created 

Note, on the top bar, File button shows all created file, folders, /assests/images but nothing on the local disk 

When I open Rubyfu book (written via older versions) the sub-chapters appear but I dont check anything out to avoid damaging the project structure.

Thanks!

**Comment by nagim** [comment]
Hi,

I think it's better if you create issues on the feedback channel (https://github.com/GitbookIO/feedback), you got better response there and you can also check if some of your observations have already been reported.

**Comment by SamyPesse** [comment]
@KINGSABRI Awesome feedback, please copy/paste it to the [feedback](https://github.com/GitbookIO/feedback) repository.

**Comment by KINGSABRI** [comment]
@nagim @SamyPesse 
Done, I didn't know about feedback repo, sorry. 

https://github.com/GitbookIO/feedback/issues/82
