### ISSUE TITLE
Table of contents, the chapter numbers are incorrect

### ISSUE THREAD

**Issue by mberthouzoz** [GitbookIO/gitbook#1441]
The table of contents is incorrect. A 1 is added before the correct chapter number.

The line displayed :

Resume                   1.1
Chapiter 1               1.2

The line expected :

Resume                   1
Chapiter1                2

**Comment by nutti** [comment]
I had same problem.

I think this commit makes this problem.
https://github.com/GitbookIO/gitbook/commit/50a132cb2c0b0666b3b067e32d37e10bfb9e50da
