### ISSUE TITLE
Tables too big in pdf

### ISSUE THREAD

**Issue by pcha** [GitbookIO/gitbook#1442]
Hello, I have the a book with some tables very large and when I export to pdf I can't view the full table. There is a way to shrink the table so that it can be fully visible?
Is possible fix it in the future is important becaus we have a private book that export to pdf and send to the users.
You can see this in 
https://decidir.gitbooks.io/documentacion/content/ComoMeIntegro/FlujoTransaccional/PedidoAutorizacion/Requerimiento/
If ypu export this book to pdf, you can see the table in tha page 24
Best Regards!
Pablo.

**Comment by moxiegirl** [comment]
+1 we have the same problem

**Comment by porschuetz** [comment]
![screen shot 2017-04-04 at 22 04 53](https://cloud.githubusercontent.com/assets/1228101/24676363/fb6e451c-1982-11e7-8bec-c0e1502abfcb.png)

**Comment by porschuetz** [comment]
difficult to automate

**Comment by Dana-awake** [comment]
Commercial products manage; why can't we?
