### ISSUE TITLE
small images fill up entire page width in pdf

### ISSUE THREAD

**Issue by jgngo** [GitbookIO/gitbook#1444]
I have small images (200px width) that render normally in html but in the pdf version, it expands to fill the entire page width, making it look pixelized. Is there a configuration to make retain the original image size in the pdf file?

**Comment by jgngo** [comment]
The solution I have found so far is to use <img src="image.png" width="200px" /> instead of the normal markdown syntax.

**Comment by njleonzhang** [comment]
you solution can not work for my doc
