### ISSUE TITLE
Q: Support for named markdown images

### ISSUE THREAD

**Issue by simov** [GitbookIO/gitbook#1447]
Things like:

[![travis-ci](https://img.shields.io/travis/simov/purest/master.svg?style=flat-square)](https://travis-ci.org/simov/purest)

``` md
[![travis-ci]][travis]

  [travis-ci]: https://img.shields.io/travis/simov/purest/master.svg?style=flat-square (Build Status - Travis CI)
  [travis]: https://travis-ci.org/simov/purest
```

As you can see this is rendered correctly in GitHub, the image above have a title and it can be clicked. This doesn't seem to work with latest GitBook:

```
CLI version: 2.3.0
GitBook version: 3.2.0
```

**Comment by SamyPesse** [comment]
I've opened an issue on our markdown parser:  https://github.com/GitbookIO/markup-it/issues/17
