### ISSUE TITLE
Gittbook can't push or pull.

### ISSUE THREAD

**Issue by bmw9t** [GitbookIO/gitbook#1448]
I've got my gitbook synced up with a github repo. The sync command just hangs up, but, when I try to push from the Gitbook editor to the github repo I get a couple error messages that might be more helpful - "Cannot read property 'getName' of null." Sometimes the push error is "cannot push nonfastforwardable reference." Always one or the other, and I can't quite tell why I get one sometimes and not the other.

I first noticed the problem this afternoon - seemed to be working fine this morning. I'm running version 6.0.4, and best I can tell the book was building from the linked github account until I downloaded the updates today.

The GitHub repo is - https://github.com/bmw9t/introduction-to-text-analysis
The GitBook repo is - https://bmw9t.gitbooks.io/introduction-to-text-analysis/content/data_cleaning/problems_with_data.html

Thanks! Happy to provide any other info you might want.

**Comment by bmw9t** [comment]
Ah nevermind! I sorted it out. Couldn't get it working from within the gitbook editor, but I went to the Import repo in the terminal where it lived on my drive. From there I was able to pull things down manually and push back up with the standard git commands. So things are sync'd now. Not sure how things went wonky.

**Comment by fruch** [comment]
having the same issue
