### ISSUE TITLE
Setting image size and alignment in markdown

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/gitbook#1451]
Is it possible to set the size in gitbook markdown, or only in HTML?

I could not figure it out, and standard markdown syntax for controlling image size didn't work for me.

**Comment by fedorov** [comment]
Also, can someone help - is it possible to align the image? I can't figure out how to do that in either markdown or HTML 👎

**Comment by fedorov** [comment]
Related issue- images are not sized properly in the desktop editor application (OS X 10.10.5), editor 6.2. All details should be clear from the screenshot below. Same content shown in raw, desktop app rendered, and web rendered

![pasted image at 2016_07_25 02_55 pm](https://cloud.githubusercontent.com/assets/313942/17113686/cc174672-5279-11e6-888f-ec79bbdc3a2b.png)

**Comment by mirko77** [comment]
+1

**Comment by TriKro** [comment]
Agreed. If this is not possible it makes Gitbook non-competitive for anything other than technical manuals.

**Comment by fedorov** [comment]
On a somewhat related note, it would be nice to be able to see larger image on click, in a popup or something, as an extra feature.... let me know if I should submit this as a separate feature suggestion.
