### ISSUE TITLE
Repository corrupt

### ISSUE THREAD

**Issue by caiosantarossa** [GitbookIO/gitbook#1454]
Hi, we are trying to clone the repository (https://git.gitbook.com/sensedia/api-suite-2-0.git) but is returning the error below:

```
remote: error: object file objects/13/0753893afc42bc2307609443417ed553852369 is empty
remote: fatal: loose object 130753893afc42bc2307609443417ed553852369 (stored in objects/13/0753893afc42bc2307609443417ed553852369) is corrupt
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
```

As we don't have access to the files on the gitbook server how can we fix this issue?

**Comment by josevahljr** [comment]
Hey guys,
Same problem! Do you suggest any workaround?
tkz

**Comment by adueck** [comment]
Hey Guys,

I had a very similar problem, I could clone the repo but it was empty/non-accessible. 

I have a workaround though! 🎉 

- Click on the `updates` tab on the navbar
- Click on the commit number for the latest commit (or whatever you want to revert to)
- Click on the `Download Source` button

There you go.
