### ISSUE TITLE
Can't chance pointer of a file

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#1457]
![screen shot 2016-07-20 at 23 16 43](https://cloud.githubusercontent.com/assets/1536079/17005057/119256e0-4ed0-11e6-8351-9744148e9449.png)

I can't edit the path of the pointer file. It looks locked somehow. Version 6.1.1

Also, I just realised the file under secondary folders are not created in the right folder. I think that's also a bug...

Thank you in advance!

**Comment by SamyPesse** [comment]
You can click on the `X` to replace the link, we should probably improve this (switch it to edit mode when you click on the whole input).

I'm not sure I understand `Also, I just realised the file under secondary folders are not created in the right folder. I think that's also a bug...`, can you detail a little more (how to reproduce?).

**Comment by SamyPesse** [comment]
Also can you move these issues to https://github.com/GitbookIO/feedback/issues :)

**Comment by cesards** [comment]
Oh man, sorry! it was late :-P 👍 I will raise the issue on GitbookIO if it's necessary :)
