### ISSUE TITLE
Incorrect pointer to next article

### ISSUE THREAD

**Issue by mizunashi-mana** [GitbookIO/gitbook#1463]
In https://toolchain.gitbook.com/pages.html#anchors case, prev and next articles are such as:
- Introduction <- Part I -> Writing is nice
- Introduction <- Writing is nice -> Writing is nice
- Introduction <- GitBook is nice -> Writing is nice

sample: https://mizunashi-mana.gitbooks.io/gitbook-anchor-parts/content/
In this sample case:
- First2 <- Second -> Second1
- First2 <- Second1 -> Second1
- First2 <- Second2 -> Second1
- First2 <- Second3 -> Second1

Is this correct behavior?  I think this act is not useful...

GitBook support anchor pointing on summary, right?

I suggest that prev and next articles should be:
- First <- Second -> Third
- First <- Second2 -> Third
- Third <- Third3 1

That moving can be provided just to ignore anchor points on searching prev and next articles.

**Comment by kuon** [comment]
I also stumbled onto this issue, which makes anchor point unusable:(
