### ISSUE TITLE
Left 2 buttons in header disappear after customize the summary width

### ISSUE THREAD

**Issue by skyscribe** [GitbookIO/gitbook#1464]
### What is the current behavior?
I use default theme and modified the summary pane width with below website.css
```css
.book-summary {
    width: auto
}
```

After that, 2 buttons of the header pane disappear such that I'm not able to hide the summary pane.
Git book version used is:
```bash
CLI version: 2.3.0
GitBook version: 3.1.1
```

### What is the expected behavior?

The header button as part of the book body shall be still accessible from top left corner.

**Comment by zekedroid** [comment]
Yeah that's expected. Look at how the two divs (`.book-summary` and `.book-body`) are put side by side: they're position absolute and the latter uses `300px` on the `left`. Meaning if you where to manually change the width of the summary, it would not change where the body is relative to it.

A solution would be to look at modifying how these two are put side by side (use float?).

I briefly tried with this but it doesn't quite work. You could try expanding on it:

```
.book-summary {
    width: auto;
    height: 100vh;
    float: left;
    position: relative;
}

.book-body {
    position: relative;
    float: left;
}

.body-inner {
    position: relative;
}
```

**Comment by skyscribe** [comment]
Thanks @zekedroid for the time and comment!

I solved this problem eventually by using the splitter plugin, although I didn't get time to try your css yet.
