### ISSUE TITLE
gitbook.js:3 xmlhttprequest cannot load

### ISSUE THREAD

**Issue by EdenStack** [GitbookIO/gitbook#1469]
when I upgrade `gitbook` to 3.x+ ,local build html have a `gitbook.js:3 xmlhttprequest cannot load` error, it seems that it caused by cross origin, but when I use `gitbook build --gitbook=2.6.7`, every thing is all right, is it a bug ?

**Comment by gubler** [comment]
This is a bug (?) in the default theme's javascript. I have opened an issue in that project for this problem: GitbookIO/theme-default#28

**Comment by yeluolei** [comment]
same problem for me.
