### ISSUE TITLE
svg conversion for epub/pdf fails

### ISSUE THREAD

**Issue by noerw** [GitbookIO/gitbook#1473]
### current behaviour

with `gitbook 3.2.0` and `svgexport 0.3.2` (which has to be installed separately, and is only hinted at by an errormessage of a failed PDF build), the SVG conversion fails

```
Error: Error converting /tmp/tmp-4992C2LYB34ZoZUI/de/779c1afe.svg into /tmp/tmp-4992C2LYB34ZoZUI/de/bc0d77af.png
```

The affected file is a shields.io badge, and may be converted manually just fine:

```
wget https://img.shields.io/badge/method-GET-brightgreen.svg
svgexport method-GET-brightgreen.svg method-GET-brightgreen.png
```
### expected behaviour

SVG conversion should be an included dependency, and most of all; should not fail.

**Comment by noerw** [comment]
welp, never mind.
The conversion does not fail for the shields.io badges.
It fails for a url-referenced file, which is not available ([`https://img.shields.io/badge/method-GET-.svg`](https://img.shields.io/badge/method-GET-.svg)).
While this definitely is an issue to be solved by the user, gitbooks errorhandling could be better I believe:

- check HTTP code when getting external resources, and outputting a warning at that point
- replace unavailable images with (a) placeholders or (nothing), but continue the build

**Comment by c0001** [comment]
**Even if you used local svg file it couldn't convert to png on `gitbook pdf ./`.**
