### ISSUE TITLE
Github Editor: Reference refs/remotes/origin/master not found

### ISSUE THREAD

**Issue by kristianmandrup** [GitbookIO/gitbook#1477]
### What is the current behavior?

I can't find a guide for how to get started. I can't figure out how to link my Gitbook Editor book to github.
### What is the expected behavior?

Should be easy to get started and link to a github repo!

I found this [guide](https://tomjn.com/2014/06/25/gitbooks-github/). He also complains that he encountered stumbling blocks getting started. 

In my Gitbook editor I try to set my _Repository Settings_

Primary remote repository (origin)

https://github.com/kristianmandrup/amazing-aurelia-book.git

I think I have to enter the https url?

But when I sync I always get this error:

`Reference refs/remotes/origin/master not found` 

What does that even mean!? Please provide a proper error message which hints at how to fix the problem, such as how to provide a proper github identifier. Thanks :)

**Comment by kirtan403** [comment]
I had the same issue. But, it is simple. Just make your initial commit on the repo and it will work. When you create a new project, initially repo is empty and no master branch will be there. That is why there will  be error. Just create an empty .gitignore file and commit. Now, you are good to go. Hope it will solve your problem.

**Comment by sarus** [comment]
Have the same error when attempting to switch to a different local branch and then saving the book.
