### ISSUE TITLE
Error 0 of Gitbook editor

### ISSUE THREAD

**Issue by xmtsui** [GitbookIO/gitbook#1480]
### What is the current behavior?

<img width="1224" alt="dingtalk20160803222518" src="https://cloud.githubusercontent.com/assets/1542690/17369121/8979cdec-59c9-11e6-9f3e-b1e6a5aad366.png">
Gitbook editor 6.2.1
OS X 10.11.6
### What is the expected behavior?

should open normally
#### For GitBook.com

its a private project

---

The GitBook Team

**Comment by derekey** [comment]
I got the same problem.


GitBook Editer 6.3.3/osx-10.11.6

**Comment by derekey** [comment]
```
rm -rf ~/Library/Application\ Support/gitbook-editor
```

And it seems work.
