### ISSUE TITLE
Cannot paste from clipboard with keyboard shortcut on mac.

### ISSUE THREAD

**Issue by walshbr** [GitbookIO/gitbook#1483]
Using 6.2.1
### What is the current behavior?

Copying/cutting a block of text. The text will not paste using command V on mac. In each case, the text is stored in the clipboard - I can paste it in other applications/windows. And it cuts correctly in the sense that it disappears from the document. But the clipboard will not paste using the shortcut. Does, however, paste if you use the edit menu's paste command.
### What is the expected behavior?

How do you think, or how would you like it should behave.
 Would expect it work as keyboard shortcut as well as menu command.
#### For GitBook.com

Provide, if possible, your username and the URL of the concerned book.
## bmw9t - https://bmw9t.gitbooks.io/introduction-to-text-analysis/

The GitBook Team

**Comment by pelted** [comment]
I can confirm this is true for the GitBook Editor.

**Comment by cesards** [comment]
+1 It happens to me as well. It's kind of annoying.

**Comment by bmw9t** [comment]
FWIW, a workaround that I've found for this for most cases: 

The paste seems to go through if you paste to a blank line with a blank line on either side. The paste seemed to fail most often in cases where I was pasting into markdown URLs. If I framed the URL with brackets and parentheses first, I wouldn't be able to paste inside of them. Making a few extra blank lines so I could paste, pasting, and then deleting the extra lines to make it look as intended seemed to do the trick.

**Comment by Master-Wang** [comment]
It happens to me, too. It doesn't work when pressed CMD + V, but right-click paste work.

**Comment by dieforfree** [comment]
+1.
macOS 10.12.1 
GitBook Editor 6.3.3

**Comment by tomcam** [comment]
+1
macOS 10.11.16
Web editor

**Comment by jkuhnregnier** [comment]
+1 
macOS 10.11.6
Web editor

Even right click and paste doesn't work for me!
