### ISSUE TITLE
Cannot insert new sections in between existing sections without breaking the entire books order.

### ISSUE THREAD

**Issue by adamdahan** [GitbookIO/gitbook#1487]
I am using the gitbook-cli and I noticed that you can't insert a brand new section in between existing sections of your gitbook. I initially thought I can just modify the SUMMARY. but that isn't the case at all. 

STR: 

(P.S) I am using Atom. 
- Just insert a new section in between existing sections of a book 
- modify the summary

= book section ordering broken (section pages will appear in sections they should not be in).

**Comment by nagim** [comment]
What do you mean by sections? New files? Or a new heading in an existing file? Could you post some examples (summary file part, etc.), it's easier to help.
