### ISSUE TITLE
Assets have to be copied for multi language books

### ISSUE THREAD

**Issue by cloudlena** [GitbookIO/gitbook#1491]
### What is the current behavior?

I am writing a multi-language book. To add custom styles, templates or assets, they somehow have to be present in all language folders. If I add them in the root folder, Gitbook can't find them.
### What is the expected behavior?

I would like to place assets like images in an `assets` folder in the root folder instead of having to have an `assets` folder in each language folder separately. Am I doing something wrong or is that currently not possible?

**Comment by noerw** [comment]
see https://github.com/GitbookIO/gitbook/issues/1348
