### ISSUE TITLE
can not build files in sub directory

### ISSUE THREAD

**Issue by passionke** [GitbookIO/gitbook#1494]
### What is the current behavior?

my env 
- CLI version: 2.3.0 
- GitBook version: 3.2.0 
- nodejs :v0.12.7

My gitbook folders :

--- book.json
    | README.md
    | SUMMARY.md
    | feature
                  | test.md

and the content in README.md is 

```
[test](/feature/test.md)
```

then I use gitbook build to generate site.

in tthe generated index.html, the html code is 

```
<p><a href="feature/test.md">test</a></p>
```

My OS is mac osx 10.11.5
### What is the expected behavior?

In the orther case, when I add all md files in root, then gitbook build works fine.

in my opinion, gitbook build will build all the .md files, 
WHY I can not use sub folder?

**Comment by shawnferry** [comment]
I just extracted my gitbook into a submodule...it's less than ideal but it fixes all the build issues that I was having
