### ISSUE TITLE
Escaping `/` in Summary links

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/gitbook#1499]
To reproduce: build this version of https://github.com/GitbookIO/help.gitbook.com/commit/e872df9f58a5d63f1f1e65df7c6b8a68a10a0711

The Summary contains escaped characters `(`, `)` and `/`. However the escaped `/` are rendered to "\/" instead of "/".

``` md
* [Can I use GitBook to publish an F.A.Q \/ Help center?](basics/for-faq-documentation.md)
```

is rendered to

"Can I use GitBook to publish an F.A.Q \/ Help center?"

**Comment by camdenb** [comment]
How is this a bug? Seems like the intended behavior.
