### ISSUE TITLE
Dear Gitbook creators, stop breaking the editor

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#1505]
First of all, I really think you guys have you done a very great job creating this editor. I would even donate if it was possible. I've been playing around with it and creating a book for almost two years (basically from the beginning).

I always tried to report what I saw it was wrong, in general not big deal stuff, but seriously, I think you messed up kind of badly when you came up with the 6th version of the editor. I'm not trying to be rude or mean, just trying to make a constructive criticism:

I think the most important change and the worst in my opinion, is the new **editor preview**. I can imagine this product was created mainly for technical stuff, which is awesome because it doesn't exist anything like this. Most of Markdown editors have the editor + preview view, like MacDown:

![screen shot 2016-08-28 at 00 54 11](https://cloud.githubusercontent.com/assets/1536079/18030736/05fa3a70-6cba-11e6-8335-b97a6fad81a0.png)

But you unified this views in a rich editor, which is bad for several reasons:
- Every time I try to copy paste any kind of text from anywhere, it keeps the style, which is not what I wanted. I wanted to save the text, which is bad because I have to double copy the text to any code editor like Atom (EditText keeps is a rich editor as well) and then copy it to the Gitbook Editor.
- It could generate some extra noise anyone want, like bold spaces `** **` or similar. The best about any Markdown editor is the control you have over it.
- Code copy paste is broken. Every time I try to copy code from another site, like StackOverflow, it is erased when I try to edit it. More over, **copy paste from clipboard is broken, at least in Mac**. It just doesn't work
- I usually control the space between texts, using the html tag `<br>`, but using these tags`<>` is also broken.
- Rich editor code blocks are not coloured anymore. Is that due to any specific reason?

A part from all reasons mentioned, why do I see my older files in the old style (editor + preview) and the new ones with the new "code rich" editor? I haven't found any where I could change a setting to change the view, which is a bit annoying. Am I missing anything? Is there any chance you could implement a switcher or similar?
#### Reference links

Also, is there any reason why reference links doesn't work?

Imagine I have a table of contents, linking to a specific sub-reference

```
- [Reference1](#reference1)

// Code.

### Reference1
```

(this wouldn't work)

Neither if I need to use meta-tags

```
-[This is what I want to show here](#resumed-stuff)

<a name="resumed-stuff">
### This is what I want to show here
```

<br>
#### Tree files

I haven't understood how I am suppose to write sub-articles. I was one of the guys I suggested a few years ago there should be the chance to write sub-sections, but the way the editor creates files is still weird to me. If an article has sub-articles, should I create a folder and rename the file as `README.md` in that folder? Should I leave the name of the article `article.md` and the inside the `article` folder create the rest of sub-articles? For now I'm using the first option.

I had an issue in previous versions of the editor, because it didn't create the files in their root folders, but it is solved in the last version of the editor 👍 

<br>
### TL/DR

I am also Software Engineer, and I am empathetic enough to know you are doing a hard work here, but you should improve your Continuous Delivery. The only reason I updated the Editor it was because I got those annoying "Update" pop-ups telling me every half an hour, to update the editor to the last version.

Please, for future versions, if you make a **Beta Editor** at least let the users know they have the chance to use it, because I'm pretty sure there will be annoyed customers (people who have actually paid for the service) because of this.

Sorry if I'm missing anything in particular, but I just needed to share my opinion with you, but even if you created the Rich editor feature because of customers demand, you should let the customer decide what editor or preview to use.

Thank you for everything, seriously. It's a great tool.
Sincerely, César.

**Comment by drreen** [comment]
Any news on this one?

The bug with adding line breaaks when copy & pasting is super annoying :(

**Comment by jakeoung** [comment]
I also strongly prefer a raw text editor. The rich editor is very uncomfortable when I type latex codes.

**Comment by johnblommers** [comment]
On both OS X and Linux version the very basic Find function is missing. The keyboard shortcut is there but it fails to do anything at all. Nor is there a Find function in the Edit menu. The developers are slowly smothering the life out of GitBook Editor. It is now unusable without the simple Find function.

**Comment by hellozoella** [comment]
I had the same problem. Nearly gave up using it as I couldn't find the markdown view. It's so annoying! 
They put markdown edit entrance into the right bottom question mark icon, which I have to say is inconvenient.

**Comment by johnblommers** [comment]
Thanks for the useful comment, hellozoella. One may also reach the settings via the question mark icon and the keyboard settings are there and, on OS X, command F is shown for Find. But nothing happens on pressing those keys. It's too bad. 

I keep an old copy, GitBook 1.1.0 on hand. It still works and it's a pleasure to use despite its youthfullness. It still lets me edit my original ebooks, which the new Gitbook editors cannot handle for some reason.

**Comment by alexjlockwood** [comment]
Holllyyyyy shoot. @hellozoella thank you for pointing that out. Been trying to figure out how to edit markdown for the longest time.

I second making that button more discoverable. Like WAAAY more discoverable. I never would have thought to look in there. Typically a "question mark" icon means "send feedback" or "help" or something like that. Even replacing it with something like a settings gear would probably be way better.

**Comment by reinette** [comment]
What @johnblommers said: I was using 1.1.0 for ages, but it's started being crashy with the latest OSX, so I thought I'd switch. It's not bad, but I keep getting frustrated with the editor and wanting markdown. This thread came up when I googled for it, heaven knows it's nowhere in the menus or help of the actual program. Thank GOODNESS I've found it, but there is no way I would have ever clicked that ? on my own.

**Comment by jamesskyoung** [comment]
Thought I'd give this a try... Couldn't figure out how to save (still don't know how) -- although I did accidentally come across the ? to select edit in markdown ... 
Not going to waste my time on this.  Perhaps they should use Gitbooks to improve their docs...  hmmm just an idea.  Bye gitbooks.
