### ISSUE TITLE
BIG BIG PROBLEM! Gitbook shows a ONE-MONTH-AGO version

### ISSUE THREAD

**Issue by colingonglin** [GitbookIO/gitbook#1508]
Gitbook should always show the lastest version. But my gitbook show a version one month ago.

I'm using legacy version 2.6.7

https://www.gitbook.com/book/gonglin/requirementsspecification

**Comment by colingonglin** [comment]
And as you can see the pics below, the one month ago's version is listed on the top of the version list and my lastest checkin is listed on the last of the list.
![image](https://cloud.githubusercontent.com/assets/12727213/18083355/60a466d6-6ed5-11e6-849f-9274f40174fc.png)

![image](https://cloud.githubusercontent.com/assets/12727213/18083368/6df5e5f8-6ed5-11e6-839b-b8caad531dad.png)

**Comment by SamyPesse** [comment]
This is a display issue on Safari (What browser are you using?).

I've moved this issue to https://github.com/GitbookIO/feedback/issues/161

**Comment by colingonglin** [comment]
The order of the list is not important but the actual display of my book.
When I open my book, the content of the book is a one month ago version.

**Comment by colingonglin** [comment]
I'm using the Microsoft Edge. You are right after I used Chrome the content and the "updates" list are OK.

Please notice if you are using Edge, the content will also be wrong.

**Comment by SamyPesse** [comment]
It might a caching issue. I'm investigating.

**Comment by colingonglin** [comment]
I don't think it's a caching issue. I read my book everyday. If I'm reading my cache, it should be yesterday's version, not a month ago.

**Comment by jpreynat** [comment]
Hi @colingonglin,

I see that you have made updates to your book today.
Do you still encounter this error?

**Comment by colingonglin** [comment]
It's OK now.

**Comment by jpreynat** [comment]
Glad to hear it.
Thanks for your feeback.

Kind regards,
Johan
