### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by maxheld83** [GitbookIO/gitbook#151]
As I mentioned in #134 I (and I think a lot of other scholars) have been waiting for something like gitbook to come along for a very long time.
This might just be one of the missing pieces to the puzzle of online scientific publishing.
PDFs, no matter how well structured and meta-data-ed always felt a little awkard online, with people having to download them and all.

Still, academic publishing as over decades (nay, centuries) developed many helpful conventions (theorem numbering, glossaries, acronyms, – you name it) that don't sit easily with markdown.

Fortunately, we _have_ one markup language that has implemented _all_ of these things already: LaTeX.
Of course, much of the typesetting genius (and baggage) of TeX becomes redundant once you publish to a static website.
But still, the _conventions_ have all been implemented, and people know who to write in this markup (not to mention legacy projects).

So here's my (long-winded) question: any chance gitbook might evolve to be a front-end to LaTeX, too? Maybe via Pandoc?

Am I making sense?

**Comment by znmeb** [comment]
There are already WYSIWYG front-ends for LaTeX, LyX and TeXmacs. I personally use LyX. LyX can export XHTML, which you can probably push into Pandoc to get Markdown, though I haven't tried it.

There is also the RStudio/RMarkdown/knitr/pandoc toolchain for making HTML and PDFs; it can render to Markdown in just about all of the dialects. 

So there are lots of hacks that might work, but I'd try LyX export to XHTML first if you want to publish LaTeX to the web.

**Comment by aepstein** [comment]
Pandoc + HTML is good, but AsciiDoc + docbook seems like a much better route to generate high quality books.  By using Asciidoc for the gitbook, I was able to compile a nice LaTeX-based PDF this way and the results looked very good for my needs:

```
#!/bin/bash
perl -p -e 's/\d+\.\s+link:(.+).adoc\[.+\]/$1.adoc/g' SUMMARY.adoc > summary
echo "" > compiled.adoc;
for file in $(cat summary);
do cat "$file" >> compiled.adoc;
printf "\n\n" >> compiled.adoc;
done;
asciidoctor -b docbook compiled.adoc -d book;
dblatex compiled.xml --param toc.section.depth=1 \
  --param insert.xref.page.number=yes \
  --param table.in.float=0;
```

Any thoughts about that?

**Comment by qinix** [comment]
+1 for LaTeX support

**Comment by znmeb** [comment]
The good folks at RStudio now have Bookdown ... you write in R Markdown and get a website in a GitBook-like styling, Bootstrap styling or their own "Tufte HTML" styling. PDFs are done via pandoc and the system LaTeX, although for best results you want to use XeLaTeX.

**Comment by urosjarc** [comment]
# gitbook-plugin-build

<br>

[![npm release][npm]][npm-url]
[![Travis][travis]][travis-url]
[![Coverage Status][coverage]][coverage-url]
[![Dependency Status][dep]][dep-url]
[![Codebeat badge][codestyle]][codestyle-url]
[![Docs Status][docs]][docs-url]
[![Join the chat][chat]][chat-url]

> Extends gitbook build system with pandoc converter.

[![Patreon User][support]][support-url]
[![Twitter User][twitter]][twitter-url]

[npm]: https://img.shields.io/npm/v/gitbook-plugin-build.svg
[npm-url]: https://www.npmjs.com/package/gitbook-plugin-build
[travis]: https://img.shields.io/travis/urosjarc/gitbook-plugin-build.svg
[travis-url]: https://travis-ci.org/urosjarc/gitbook-plugin-build
[coverage]: https://img.shields.io/codacy/coverage/574f24efb20948afac9ba998f3d159c3.svg
[coverage-url]: https://www.codacy.com/app/urosjarc/gitbook-plugin-build
[codestyle]: https://img.shields.io/codacy/grade/27e38bb72bdc4476b2e87e9926df0485.svg
[codestyle-url]: https://www.codacy.com/app/urosjarc/gitbook-plugin-build
[dep]: https://david-dm.org/urosjarc/gitbook-plugin-build.svg
[dep-url]: https://david-dm.org/urosjarc/gitbook-plugin-build
[docs]: http://inch-ci.org/github/urosjarc/gitbook-plugin-build.svg?branch=master
[docs-url]: http://inch-ci.org/github/urosjarc/gitbook-plugin-build
[chat]: https://badges.gitter.im/Join%20Chat.svg
[chat-url]: https://gitter.im/urosjarc/gitbook-plugin-build?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
[support]: https://img.shields.io/badge/patreon-urosjarc-green.svg?style=social
[support-url]: https://patreon.com/urosjarc/
[twitter]: https://img.shields.io/twitter/follow/urosjarc.svg?style=social&label=follow
[twitter-url]: https://twitter.com/intent/follow?screen_name=urosjarc

<br>

## Description

**GPP** (gitbook-plugin-build) extends [gitbook](https://www.gitbook.com/)
build system with [pandoc](http://pandoc.org/) converter. Pandoc is your
swiss-army knife when it comes to coverting files. **GPP** use pandoc
build system to convert and compile your book in variety of formats:

* **TeX formats**: LaTeX, ConTeXt, LaTeX Beamer slides
* **HTML formats**: XHTML, HTML5, and HTML slide shows using Slidy, reveal.js, Slideous, S5, or DZSlides.
* **Word processor formats**: Microsoft Word docx, OpenOffice/LibreOffice ODT, OpenDocument XML
* **Ebooks**: EPUB version 2 or 3, FictionBook2
* **Documentation formats**: DocBook, TEI Simple, GNU TexInfo, Groff man pages, Haddock markup
* **Page layout formats**: InDesign ICML
* **Outline formats**: OPML
* **PDF via LaTeX**
* **Lightweight markup formats**: Markdown (including CommonMark), reStructuredText, AsciiDoc, MediaWiki markup, DokuWiki markup, Emacs Org-Mode, Textile

Writing books with this plugin will be peace of cake. And here cake is **not a lie**!

<br>

## Homepage
For more informations please visit projects official homepage.
> [https://urosjarc.github.io/gitbook-plugin-build](https://urosjarc.github.io/gitbook-plugin-build)

<br>

## License
Copyright © 2016 Uroš Jarc

MIT License
