### ISSUE TITLE
Access Keys can not be deleted

### ISSUE THREAD

**Issue by colingonglin** [GitbookIO/gitbook#1510]
Access Keys can not be deleted. It's not convenient. 
For example, I have 10 access keys. But now I don't need 9 of them. I must disable all the 9 keys.

When I want to see which one is enabled, I must find the one enabled key out of 10.

**Comment by colingonglin** [comment]
Another problem is I can't change the key in the URL now.

**Comment by SamyPesse** [comment]
Thank you for the feedback :) Please post these issues in the feedback repository: https://github.com/GitbookIO/feedback/issues

Closing this here, but we'll add a priority milestone to the issue in `feedback`.
