### ISSUE TITLE
Insert link doesn't work ?

### ISSUE THREAD

**Issue by yyrr001** [GitbookIO/gitbook#1512]
![image](https://cloud.githubusercontent.com/assets/16753656/18159876/4ed47dc2-705d-11e6-8fcc-846458edd5db.png)
![image](https://cloud.githubusercontent.com/assets/16753656/18159903/620da22e-705d-11e6-860c-85d4dede7d53.png)
by clicking this link, I can't jump to the position and even not fresh this page!

Any help would be appreciated. Thanks in advance.

**Comment by yyrr001** [comment]
Oh, I find the solution.
Maybe the v3.1.0 Builder result in this.
So I changed to v2.6.7 and it works.

**Comment by nagim** [comment]
You should consider using the `id` attribute instead of the `name` attribute, because `name` attribute is not supported in HTML5.

**Comment by yyrr001** [comment]
Thank you very much. The key point may lie on this.

**Comment by nagim** [comment]
I remember that somebody also had problems with anchors and switching to the `id` attribute solved it.

**Comment by SamyPesse** [comment]
@yyrr001 this is not the perfect solution to add anchor ID, GitBook supports a markdown syntax for it:

```md
## My Heading {#theid}

A link to my [heading](#theid).
```

The new editor will soon let you edit these ID easily.
