### ISSUE TITLE
Default branch can not register

### ISSUE THREAD

**Issue by helo717** [GitbookIO/gitbook#1513]
Steps to Reproduce:

browser: chrome
gitbook -V: 3.1.1?
 
■ Step 1
<img src="http://convibase.jp/cb/tmp/WS000016.png" width=300 style="border:solid 0px #000000">

■ Step 2
<img src="http://convibase.jp/cb/tmp/WS000017.png" width=300 style="border:solid 1px #000000">

■ Step 3 - new branch "suzuki" selected
<img src="http://convibase.jp/cb/tmp/WS000018.png" width=300 style="border:solid 1px #000000">

■ Step 4
<img src="http://convibase.jp/cb/tmp/WS000019.png" width=300 style="border:solid 1px #000000">

■ Step 5 - "suzuki" branch can not register
<img src="http://convibase.jp/cb/tmp/WS000020.png" width=300 style="border:solid 1px #000000">

**Comment by SamyPesse** [comment]
Thank you, this is a duplicate of https://github.com/GitbookIO/feedback/issues/165

Please post these issues in the feedback repo: https://github.com/GitbookIO/feedback/issues
