### ISSUE TITLE
Support Nunjucks Comments

### ISSUE THREAD

**Issue by mjrussell** [GitbookIO/gitbook#1514]
First of all, thank you for the great tool! It has been extremely helpful for me and my team in building some customer facing documentation.

One issue I found is that commenting in nunjucks does not seem to work (the comments appear in the generated source). The reference for comments is [here](https://mozilla.github.io/nunjucks/templating.html#comments) and the output looks like:
`{# My Comment #}` in the generated HTML and PDF.

**Comment by ztl8702** [comment]
+1 for this.
Very frustrating when you cannot comment/write documentation in your templates.

**Comment by SamyPesse** [comment]
GitBook supports the nunjuck comments with another syntax: https://github.com/GitbookIO/gitbook/blob/master/lib/models/templateEngine.js#L90

(because otherwise, it was conflicting with the markdown syntax).

**Comment by ztl8702** [comment]
Ohh... Thanks!

**Comment by ztl8702** [comment]
I would suggest improve documentation on this.

**Comment by ztl8702** [comment]
Still somewhat buggy: comments doesn't seem to be working in top-level markdown files (those that are not included by other files).

top-level.md

```markdown
{### comment 1 ###}
{% include './a.md' %}
{% for i in [1,3,4] %}{{i}}{% endfor %}
```

a.md

```markdown
{### comment 2 ###}
Template
```

The output (top-level.html) will look like:
![1](https://cloud.githubusercontent.com/assets/2714446/18242776/512f9cbe-739b-11e6-8f9b-6232ac2a840f.PNG)

But `{% for %}` some how works.

**Comment by ztl8702** [comment]
Created a new issue on this: #1519

**Comment by mjrussell** [comment]
Yeah same as @ztl8702
