### ISSUE TITLE
Nunjucks comments not working in "top-level" markdown files

### ISSUE THREAD

**Issue by ztl8702** [GitbookIO/gitbook#1519]
Nunjucks comments doesn't seem to be working in top-level markdown files (those that are not included by other files).

top-level.md

``` markdown
{### comment 1 ###}
{% include './a.md' %}
{% for i in [1,3,4] %}{{i}}{% endfor %}
```

a.md

``` markdown
{### comment 2 ###}
Template
```

The output (top-level.html) will look like:
![1](https://cloud.githubusercontent.com/assets/2714446/18242776/512f9cbe-739b-11e6-8f9b-6232ac2a840f.PNG)

But `{% for %}` some how works.

Gitbook version: 3.2.0
OS: Windows 10

**Comment by mjrussell** [comment]
Same behavior here `{### ... ###}` syntax doesn't comment but creates weird headings

**Comment by ztl8702** [comment]
Any updates?
