### ISSUE TITLE
Unnecesary steps to check for education discount info.

### ISSUE THREAD

**Issue by lopezm94** [GitbookIO/gitbook#1526]
Hello, I'm a college student and really interested in using GitBook for research projects.

To access the current education discounts information you need to contact support, and response time is a bit slow (which I understand). Is there any reason to hide the discounts from the main website? I don't event know if it might be possible to obtain some private repositories for free.

![pricing](https://cloud.githubusercontent.com/assets/14032787/18370131/065c5334-762b-11e6-8c05-3f8dc6e606c4.png)

**Comment by AndlsH** [comment]
Did you have an answer from them?
I want to know if students can create private books for free, or if we can host gitbook books in private repos on github. 👀

**Comment by AndlsH** [comment]
It is interesting that I just made a book private without a subscription!
Simply go to the setting page of a book, scroll to the buttom, click `Make private`. 
I am not sure if this has anything to do with my github plan... 😃
