### ISSUE TITLE
gitbook build local website: one page can't jump to other page

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#1527]
When i use the command `gitbook build` to build local website for a book, one page can't jump to other page. But, it works well by `gitbook serve`. How to solve it? 

My GitBook is version 3.2.0.

**Comment by erlem** [comment]
Same problem. Have you an solution ? Thank you

CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by erlem** [comment]
I find. It's a problem with version 3.*. With version 2.6.7, it's works!

`gitbook fetch 2.6.7`

See the documentation: [https://github.com/GitbookIO/gitbook-cli](https://github.com/GitbookIO/gitbook-cli)
