### ISSUE TITLE
Opening the books on web is very slow

### ISSUE THREAD

**Issue by mingrammer** [GitbookIO/gitbook#1528]
The rendering time at opening the book is very long .. 
It's like a infinite loading. 

Please fix that problems ..

**Comment by SamyPesse** [comment]
For a book hosted on GitBook.com or with a local build?

**Comment by mingrammer** [comment]
on gitbook.com

**Comment by SamyPesse** [comment]
The editor or the reading website ? Can you paste me the link?

**Comment by mingrammer** [comment]
The reading. I registered the custom domain, so the link is https://wiki.mingrammer.com
But, in this time, the page is loaded more faster than about 30 minutes ago .. strange ..
