### ISSUE TITLE
Content Disappears in Safari

### ISSUE THREAD

**Issue by walshbr** [GitbookIO/gitbook#1530]
I'm using Safari 9.1.3.
The book in question is bmw9t.gitbooks.io/introduction-to-text-analysis/content/
I noticed it first on this page - https://bmw9t.gitbooks.io/introduction-to-text-analysis/content/data-cleaning/zotero.html

But I think I saw it on other pages as well. The content all loads fine and everything seems to be normal. But then, after a while, the page switches from having all the content loaded correctly to having only a table of contents and a blank window in the right pane, where the page's content should be. I've attached screenshots. The only thing I can find that seems to trigger this is resizing the window, but even then the resizing does not always appear to do it. So I've been unable to find a direct cause. The only css I have for my book is this in website.css:

```
/* CSS for website */
img{
max-height:500px;
}

.img-right{
float: right;
padding-left: 13.6px;
}

.medium{
    max-width: 280px !important;
}

#ocr-image{
    max-width: 165.275px;
    padding-left:0px;
    margin-left: 13.6px;
}

#prism-licensing{
    max-width: 280px;
}

.clear{
 clear:both;
}
```

Sorry I can't be more specific, if you have any suggestions as to other configurations to check or code to list I am happy to do so.

**Comment by galtenberg** [comment]
Same thing happens for me. Not even resizing the window, even just moving the mouse will cause the main content to disappear (but not the TOC sidebar).

**Comment by leksilo** [comment]
Same here. Safari 10.0.2. It's possibly limited to pages whose content is longer than the window. Moving the mouse makes the page's content to disappear.

**Comment by Tmthetom** [comment]
Same with iPhone and any GitBook page.

**Comment by azrael25** [comment]
Same bug with Safari 10.0.3 but only when window width less than 1150px.

**Comment by henryiii** [comment]
Same issue on Safari on my Mac and iOS. Resizing the page (Mac) restores the content briefly. It happens on almost all GitBook pages, even official ones.

**Comment by agentlewis** [comment]
Ditto iPhone 7 plus  iOS 10.3.2

**Comment by gooderist** [comment]
Same issue on Safari 10.1.2

Content appears normal if you comment out `float: left` on the navigation class.

**Comment by Goldflower** [comment]
Same issue on Safari 11. Seriously?

**Comment by hromek** [comment]
Same issue with Safari 11.0 (13604.1.38.1.6)

**Comment by eeeps** [comment]
Could it be this: https://bugs.webkit.org/show_bug.cgi?id=140560 ?

**Comment by ThomasHagenJohansen** [comment]
@GitBook Can we expect this to be fixed in the new version you just released?

@gooderist So, commenting out float: left on the navigation class will fix the issue?

**Comment by gooderist** [comment]
@ThomasHagenJohansen Make the issue go away on Safari, yes. Fix is a word I reserve for when I can explain why the issue goes away. That task I leave for a better man :)

**Comment by AaronO** [comment]
@ThomasHagenJohansen It does appear to be resolved in the v2 (see https://betadocs.gitbook.com in Safari)

![image](https://user-images.githubusercontent.com/949223/38302277-5cc32c44-3802-11e8-87c6-d130ebacedbb.png)
