### ISSUE TITLE
Why hooks for summary data deprecated

### ISSUE THREAD

**Issue by billryan** [GitbookIO/gitbook#1532]
I wrote a plugin https://github.com/billryan/gitbook-plugin-tags to generate tags for GitBook recently, without summary hooks, the author has to create a markdown page named `tags.md` and put it to the end of `SUMMARY.md`. I found that there was https://github.com/GitbookIO/gitbook/pull/354 but had been removed since [2.0.0-alpha1](https://github.com/GitbookIO/gitbook/blob/master/CHANGES.md#200-alpha1).

Is there any other better method to implement this feature without summary hooks?

**Comment by petehouston** [comment]
@SamyPesse is there any plan for summary hook?

**Comment by kalinchernev** [comment]
I'd also share my surprise to see the summary side being in-flexible. A hook would be useful to at least respect some tag from the Summary.md file to place an attribute or a label next to the chapters.
A scenario would be to mark some chapters in progress or completed.

**Comment by winniehell** [comment]
My guess is that the reasoning for removing the hooks was the same as for the `page:*` hooks:

> Hooks for page (page:*) are now deprecated, plugins should extend filters and blocks instead

Unfortunately it looks like for `theme-default` it is only possible to extend (and rewrite/copy) the whole summary block and not only parts of it.

**Comment by winniehell** [comment]
I came up with a crazy solution for modifying the summary from a plugin:

`plugin/index.js`

```javascript
module.exports = {
    hooks: {
        config: function(config) {
            config.variables.filterSummary = (summary) => {
              summary.parts[0].articles[0].title = 'A new title';
            };

            return config;
        }
    }
};
```

`plugin/_layouts/website/page.html`
```javascript
{% extends template.self %}

{{ book.filterSummary(summary) }}
```

### Result

![bildschirmfoto vom 2017-11-04 01-49-37](https://user-images.githubusercontent.com/1652293/32400605-7360aade-c102-11e7-9425-e101fddda5d4.png)
