### ISSUE TITLE
Links to downloads Fail on Gitbook

### ISSUE THREAD

**Issue by DonRichards** [GitbookIO/gitbook#1539]
### What is the current behavior?

Link to resource is not working within Gitbooks but works fine in Github. 

**_Note:_** Using Gitbooks as a web service only. Nothing local installed. Also I simplified the URLs in this issue for clarity. Actual file names and URLS are much longer and are a the bottom of this issues ticket.

**Folder Structure of the File in relation to the ZIP it's trying to point to**

```
~/github/Islandora_manual/modules/tests
.
├── newspaper_ingest.md
└── test_files/
    └── batch.zip
```

**From the Markdown file is a relative link to "Ingest ZIP"**
~/github/Islandora_manual/modules/tests/newspaper_ingest.md

``` md
* [Ingest ZIP](test_files/batch.zip)
```
### What is the expected behavior?

From Github: Click on link "Ingest ZIP" and it works
URL:
_https://github.com/utkdigitalinitiatives/Islandora_manual/blob/master/modules/tests/test_files/batch.zip_

From Gitbooks: Click on link "Ingest ZIP" and it fails 
URL:
_https://utkdigitalinitiatives.gitbooks.io/islandora-manual/content/modules/tests/test_files/test_files/batch.zip_

The issue is obvious. Gitbook is adding a directory redundantly **./test_files/test_files/.**

---
#### For GitBook.com

https://utkdigitalinitiatives.gitbooks.io/islandora-manual

It has a link to the Github Repo on the main README

---

**Here is a URL to the link in question. "Test File:"**

https://utkdigitalinitiatives.gitbooks.io/islandora-manual/content/modules/tests/book_batch_ingest.html

**Github Version: "Test File:"**

https://github.com/utkdigitalinitiatives/Islandora_manual/blob/master/modules/tests/book_batch_ingest.md

**Comment by wihoho** [comment]
Is there anyone handling this problem? We need this feature. Thanks.

**Comment by fancyboynet** [comment]
same here

**Comment by lukejanicke** [comment]
Still an issue. Clicking on links to files (for download) goes to a GitBook "Page Not Found" page. It seems GitHub is treating all URLs as pages and not recognising (or allowing) downloadable file hosting. Would that be right?

**Comment by eMPee584** [comment]
Yes major bummer, wasted hours on this. Should at least be DOCUMENTED!

**Comment by bb2qqq** [comment]
2018-03-31 Still got the same issue here.

**Comment by DonRichards** [comment]
Workaround is to use relative not absolute values.

**Comment by bb2qqq** [comment]
@DonRichards , can you give an example of how relative value works? That would be very helpful to me and others who reached to this post. I didn't work out what exactly you mean by "relative values".

**Comment by DonRichards** [comment]
@bb2qqq Let's  say this is our folder structure. Starting from `batch_ingest.md` I want to point the user to the file `find_me.md`

```
~/github/Islandora_manual
.
├── Basic\ Image\ Structure.png
├── CONTRIBUTING.md
├── GLOSSARY.md
├── IslandoraCommunity.md
├── LICENSE
├── README.md
├── SUMMARY.md
├── _book
│   ├── CONTRIBUTING.md
│   ├── GLOSSARY.html
│   ├── IslandoraCommunity.md
│   ├── LICENSE
│   ├── basics
│        ├── README.md
│        └── tests
│             ├── find_me.md
│             └── batch_ingest.md

```

Normally I would use link an absolute path like this in the markdown file

#### Does not work
```terminal 
 Link: [FOUND](book/basics/test/find_me.md)
```

#### Works
```terminal 
 Link:  [FOUND](find_me.md)
```

**Comment by vtimonov** [comment]
I found another workaround for such cases. Just use html markup, like:

`<a href="/chapter4/jenkins/p/pipeline/files/docker/Dockerfile" download target="_blank">Dockerfile</a>`

**Comment by Midacts** [comment]
@vtimonov This actually did kick off a download.
For me, it shows "Failed - No file".

**Comment by vtimonov** [comment]
@Midacts make sure that all the paths are written using a slash (full path in a project), ` <a href="/chapter4/jenkins/p/pipeline/files/docker/chrome_launcher.sh" download target="_blank">chrome_launcher.sh</a>` For me, the links work after building a book `gitbook build . public`

**Comment by Midacts** [comment]
i tried that as well.   : <
Still downloads a file and shows "Failed - No file".

**Comment by Midacts** [comment]
@vtimonov I think the problem was I was trying to download a .msg outlook email message. Chrome or my antivirus must be not allowing it to be downloaded.

Your proposed fix does work though.
