### ISSUE TITLE
Table cells do not render markdown or HTML syntax

### ISSUE THREAD

**Issue by zlargon** [GitbookIO/gitbook#1541]
I have had my book's gitbook version updated from 2.6.7 to 3.2.0. However, I find that table cells do not render markdown or HTML syntax in the new version.

How can I fix this problem?
Thanks.
## Version

OS version: OS X El Capitan 10.11.6
Gitbook CLI version: 2.3.0
GitBook version: 3.2.0
## Original Markdown Source

https://github.com/zlargon/git-tutorial/blob/master/file/rename.md
## Published Book Link

https://zlargon.gitbooks.io/git-tutorial/content/file/rename.html
## 2.6.7-build ↓

![v2 6 7](https://cloud.githubusercontent.com/assets/2791834/18823072/ecff1e5a-83e8-11e6-9b73-4584177eedd5.png)
## 3.2.0-build ↓

![v 3 2 0](https://cloud.githubusercontent.com/assets/2791834/18823073/f665e78a-83e8-11e6-92f1-b5ddd545e38b.png)

**Comment by aisuhua** [comment]
I have the same problem after i updated the gitbook to 3.2.0. The markdown or html syntax  can not parse , and output the label directly. But this is ok in older version.

**Comment by Tiliavir** [comment]
Same here for links in tables - thanks for testing ...

**Comment by edmundojr** [comment]
I ran into the same problem here, using version 3.2.1.

Markup:
```markdown
| HTTP Method             | POST                                         |
|-------------------------|----------------------------------------------|
| URL                     | _https://example.com_                        |
| Query Parameters        | **N/A**                                      |
| Request representation  | [Article Entity](/api-entities/api-article/) |
| Response representation | [Status Entity](/api-entities/api-status/)   |
| Success Response Code   | **201 Created**                              |
```

Output:
![screen shot 2016-09-30 at 08 41 50](https://cloud.githubusercontent.com/assets/213251/18984329/cf757dbc-86e9-11e6-929b-44ee22f9023d.png)

**Comment by bananaappletw** [comment]
I can't reproduce it.
I think this issue is been solved on `3.2.2`.
After gitbook release 3.2.2, rollback `gitbook-markdown` to `1.3.2`.
If I was wrong, please correct me.

**Comment by SamyPesse** [comment]
Yes it correct it till we fix the issue in `markup-it`.

**Comment by edmundojr** [comment]
I've updated the version to `3.2.2` and it's fixed.

Thank you lads! 👍

**Comment by bananaappletw** [comment]
I think it's could be closed.
Decided by owner.

**Comment by SamyPesse** [comment]
I'm keeping this issue open as we'll rollback to `markup-it` with version 4.0.0.
