### ISSUE TITLE
Authentication failure with git

### ISSUE THREAD

**Issue by milancurcic** [GitbookIO/gitbook#1542]
### What is the current behavior?

I am able to log in and edit my book in the browser. I used Github credentials to register/log-in. However I am not able to clone my book repo using git:

```
$ git clone https://git.gitbook.com/milancurcic/uwincm-manual.git
Cloning into 'uwincm-manual'...
remote: Authentication has failed (Invalid user, password or access token)
fatal: Authentication failed for 'https://git.gitbook.com/milancurcic/uwincm-manual.git/'
```

My Github credentials are not accepted when trying to clone using git.
### What is the expected behavior?

My Github credentials should be accepted when cloning using git.
#### For GitBook.com

milancurcic
https://www.gitbook.com/book/milancurcic/uwincm-manual

**Comment by milancurcic** [comment]
The issue still persists. Thanks!

**Comment by younestouati** [comment]
Had the same issue when trying to move my gitbook project to github. Finally worked when I use an api key for authentication instead, as suggested here: https://github.com/GitbookIO/gitbook/issues/660 . You have to generate the API token under Application / Tokens under your Account Settings on gitbook.com. There is also a page called password under the Security pane on the same page. I think you may be able to do regular username/password authentication if you set up a password in there, but I haven't tried. My guess is that the problem we  ran into is, that we used our github account when signing up for gitbook. But when migrating to github, we will need a gitbook-specific password, which has to be set up first.

**Comment by wzt3309** [comment]
I have the same problem when I clone from the gitbook 
`git clone https://git.gitbook.com/wzt3309/algorithm-learn.git.`
But when I clone by this way
`git clone https://myUserName:myPassword@git.gitbook.com/wzt3309/algorithm-learn.git.`
then everything is ok

**Comment by rraadd88** [comment]
The issue still persists.
