### ISSUE TITLE
confused about `gitbook help` output

### ISSUE THREAD

**Issue by lili21** [GitbookIO/gitbook#1546]
```
build [book] [output]         build a book
```

Two question here.
1. What if I only pass one argument, is it the `book` ? and the output still default value `_book`
2. If I run this command with arguments( one or two), does `book.json` config file still effect ?

**Comment by nagim** [comment]
You can freely omit both of the arguments, it will build fine with the default settings. It will generate to the `_book` folder.
Yes, `book.json` will be used.
