### ISSUE TITLE
unexpected token: :

### ISSUE THREAD

**Issue by AdoBeatTheWorld** [GitbookIO/gitbook#1547]
Template render error: (/tmp/book/64-测试.md) [Line 111, Column 26]
  unexpected token: :

occured in this line:
> 之前的模板中，我是用来{{::property}}替代{{property}}。 {{::property}}是AngularJS中单向数据绑定的方法。当模板中使用的属性的值在初始绑定之后后续不会进行更改的时候，单向数据绑定是再理想不过的了

build log on gitbook:
https://www.gitbook.com/book/adobeattheworld/learning_ionic_cn_zh/build/57f301ea4d73bc0f00f52f70

**Comment by nagim** [comment]
Escape the `{{` and `}}` characters by enclosing them in `{% raw %}` `{% endraw %}`.

**Comment by AdoBeatTheWorld** [comment]
Thank you, perfectly solved.
