### ISSUE TITLE
gitbook pdf generate too big filesize?

### ISSUE THREAD

**Issue by lightning-li** [GitbookIO/gitbook#1548]
I use Gitbook version 3.2.1 and CLI version 2.3.0, when I use `gitbook pdf ./ ./random.pdf` command to generate pdf file, I find pdf file is over 20M, but the file has only 9 pages and no images, my book.json about pdf is 

```
"pdf": {
        "fontSize": 8,
        "footerTemplate": null,
        "headerTemplate": null,
        "margin": {
            "bottom": 36,
            "left": 62,
            "right": 62,
            "top": 36
        },
        "pageNumbers": false,
        "paperSize": "a4"
    },
```

my username is lightning-li, url is http://lightning-li.gitbooks.io/fabric-code-analysis

when I use online download pdf button on my gitbook website，it is only 332KB

**Comment by MarsLuo** [comment]
+1

**Comment by Leon1108** [comment]
+1

**Comment by lihome** [comment]
+1
If my book contains only ASCII code, then will generate the little pdf file.
So, I guess the cause by character set. but I have no solution.

**Comment by yyxiakun** [comment]
+1 
I have the same  problem

**Comment by bulletRush** [comment]
+1
I have the same problem

**Comment by realzhangm** [comment]
Have the same problem. Generated 40M pdf file while only 9 pages.

**Comment by jaywhj** [comment]
+1 have the same problem, why?
