### ISSUE TITLE
Integration into the existing project

### ISSUE THREAD

**Issue by voodee** [GitbookIO/gitbook#1554]
I'm trying to create documentation in the existing project. Example structure: 
![Example structure](http://image.prntscr.com/image/305084f6269e45218bdc80e96bd4f5b3.png)
I want to gitbook made only .md files in "_book" folder. But it copies all files (including .css, .js) in the folder "_book". 

How do I get into the folder "_book" сopy only the correct files?

**Comment by SamyPesse** [comment]
You can create a `.bookignore` file (same format as `.gitignore` or `.npmignore`).

For exemple to not coput the `.scss` files:

```
# .bookignore

*.scss
```
