### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by scottming** [GitbookIO/gitbook#1555]
### Url
- [theHandbookofCEC · GitBook](https://www.gitbook.com/book/scottming/thehandbookofcec/details)
- [scottming/theHandbookofCEC: 认知英语课参考手册](https://github.com/scottming/theHandbookofCEC)
### Version

```
$ gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.0
$ system_profiler SPSoftwareDataType
      System Version: OS X 10.11.6 (15G1004)
```
### Question

When I use `gitbook serve`，at 454 Line，Return a error

```
error: error while generating page "Model.md":

Template render error: (/Users/Scott/Documents/BooksRepo/tstbook/Model.md)
  SyntaxError: Invalid or unexpected token
```

That is ok when I delete a word, and add a word is error. That's funny.

Is it a bug?

**Error**
![](http://7xjuve.com1.z0.glb.clouddn.com/161007-gitbook_error01.png)
http://7xjuve.com1.z0.glb.clouddn.com/161007-gitbook_error01.png

**Ok**
![](http://7xjuve.com1.z0.glb.clouddn.com/161007-gitbook_error02.png)

**Error**
![](http://7xjuve.com1.z0.glb.clouddn.com/161007-gitbook_error03.png)

**Ok**
![](http://7xjuve.com1.z0.glb.clouddn.com/161007-gitbook_error04.png)

**Comment by 13space** [comment]
用TextMate 可以看到隐藏字符……删了就好了

**Comment by deleyva** [comment]
Hi! How did you know which line was causing the error?

**Comment by lonieHu** [comment]
怎么看是哪行炸了
