### ISSUE TITLE
net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by aleen42** [GitbookIO/gitbook#1557]
Recently, I have found that my book always throw an error of connection closed. Is that the problem of my network status, or any else? Here is one page of my book: https://aleen42.gitbooks.io/personalwiki/content/Programming/JavaScript/high_performance/data_access/data_access.html

**Comment by aleen42** [comment]
![image](https://cloud.githubusercontent.com/assets/9573300/19217716/085f7732-8e14-11e6-9b15-530ee70b090b.png)

As shown above, resources are load failed when their loading time is over than 32.

**Comment by aleen42** [comment]
It seems that this is the problem of Chrominum.

**Comment by aleen42** [comment]
That's the problem of your server side. Do you have set some timeout parameters?

**Comment by aleen42** [comment]
Although I load pictures from my GitHub project, I still cannot change the loading process of the following three files:

![image](https://cloud.githubusercontent.com/assets/9573300/19219297/3043f3d0-8e42-11e6-93da-04531754acf9.png)

So, please fix it!!

**Comment by aleen42** [comment]
Hello, anyone can help me? To avoid loading image resources from Gitbook, I have written a plugin ,named [`gitbook-resources`](https://github.com/aleen42/gitbook-resources), for loading from Github. However, I cannot change where to load of some files like `search_index.json`. Why setting a timeout when loading resources, which will throws `net::ERR_CONNECTION_CLOSED` error in the console line when I try to load a large json file?

**Comment by AaronO** [comment]
@aleen42 Can you share a link to your book ?

Those load times seem really bad. Where are you located ?

Is your book private by any chance ? That would explain why your resources aren't cached by our CDN and why the response times are so long.

Our CDN has a ~15s TCP timeout, since it handles a large volume of requests we don't want to keep idle/unused connections around

**Comment by aleen42** [comment]
@AaronO, the book is at: https://aleen42.gitbooks.io/personalwiki/content/

**Comment by aleen42** [comment]
@AaronO please don't close connection in a short time, or my book will break down.
