### ISSUE TITLE
Translate documentation?

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/gitbook#1560]
We could make this documentation multilingual. The problem is we don't have any translators. So we would not be able to keep all versions up to date with the English reference version.

Nonetheless, we could list translated versions with their last time updated, so that people know if a translation is likely to be out-of-date:

---
# Choose a language
- [English]() (Last update: 07/10/2016)

Translations:
- [Korean]() (Translated from 01/10/2016 version)
- [Spanish]() (Translated from 20/09/2016 version)
- Etc.

---

These dates would need to be maintained by hand. Translators should always specify the date of the published English version their translation was based on.

If we don't do that, we rather not integrate any translation into the official documentation, but simply list external links for translations.

(Following an issue on the old documentation https://github.com/GitbookIO/documentation/issues/46)

**Comment by aleen42** [comment]
Is there any Chinese version? I can do it for GitBook. To prove my skill of translating, here is my [translation works](https://aleen42.gitbooks.io/personalwiki/content/translation/translation.html).

**Comment by Vdragon** [comment]
I would recommend using Git commit to specify which version they are in, thus translator can catch up upstream's modification by tracing future commits.

**Comment by Vdragon** [comment]
Also I am willing to translate the documentation to Chinese(Taiwan).

**Comment by tinydew4** [comment]
I have translated the documents of latest version into Korean.
* [한국어](https://tinydew4.gitbooks.io/gitbook/content/ko/) (Translated from 14/10/2016)

or wording in english.
* [Korean](https://tinydew4.gitbooks.io/gitbook/content/ko/) (Translated from 14/10/2016)
