### ISSUE TITLE
Book html content not updated, all builds successful. 

### ISSUE THREAD

**Issue by Struki84** [GitbookIO/gitbook#1565]
On saving the content, the books html content is not updated to the latest successful build.

Book in question: https://simunstrukan.gitbooks.io/legacy-app/content/

My username: simunstrukan, 
Email: simun.strukan@gmail.com

All the updates have the "ok" flag, and when I go directly to preview the latest build, it is rendered properly: https://simunstrukan.gitbooks.io/legacy-app/content/v/330b5af2abd03373ae731f66e51913b2c63e6834_1/

**Comment by wxflogic** [comment]
How did you solve it? I have the same problem.

**Comment by AaronO** [comment]
@wxflogic Can you share a link to your project ?

**Comment by wxflogic** [comment]
@AaronO Sure! [Here](https://wxflogic.gitbooks.io/logic/content/chapter06.html) it is. The newest chapter could be updated properly. But old chapters seem can not be updated at all.

**Comment by AaronO** [comment]
@wxflogic should be good now if you refresh

**Comment by wxflogic** [comment]
@AaronO Yes, it is! Thank you so much!
