### ISSUE TITLE
Collaborator is not able to edit a public book

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/gitbook#1567]
### What is the current behavior?

I have a public gitbook. I do have collaborators that have no issues editing it. I am adding a new collaborator. That collaborator signs into gitbook using github authentication. I added that collaborator by the id as it shows on his gitbook page. On the dashboard of my gitbook, I do have him listed as a collaborator. On his dashboard, the collaborator is able to see the shared gitbook, and has the Edit button. However, when he clicks Edit, he is getting error below.

![image](https://cloud.githubusercontent.com/assets/313942/19450912/4b17b290-9479-11e6-8ab2-1631ef0a6ac9.png)

cc: @fladedavid
### What is the expected behavior?

My collaborator should be able to edit the shared book.
#### For GitBook.com

The book is under an individual, not an organization, account.

https://www.gitbook.com/book/fedorov/rsna2016-qirr-dicom4qi/details

**Comment by fedorov** [comment]
Guys, my collaborators are unable to edit the book. Is this a known issue? Can someone help?

**Comment by fedorov** [comment]
More info - adding user as a collaborator to the github repository of the gitbook does not fix the issue.

**Comment by crguezl** [comment]
Mya be is related to this: [Two-factor auth turned on in Github produces problems authenticating in gitbook](https://github.com/GitbookIO/gitbook/issues/1305)
