### ISSUE TITLE
Customize PDF font sizes

### ISSUE THREAD

**Issue by akshayrawat** [GitbookIO/gitbook#1569]
I would like the customize the font sizes of headers in the generated PDF. I believe this is not possible via CSS. Instead its to be done via the `font-size-rescaling` option to `ebook-convert`. 
- https://manual.calibre-ebook.com/conversion.html#font-size-rescaling
- https://manual.calibre-ebook.com/generated/en/ebook-convert.html#cmdoption-ebook-convert--font-size-mapping

gitbook doesn't build a `--font-size-mapping` option when calling `ebook-convert`, so defaults get used. It would be nice if this option when set by the author gets used.

**Comment by yashaka** [comment]
@akshayrawat 

Here is the workaround:

Find the latest gitbook installed at your system (I use mac os) at something like: `~/.gitbook/3.2.3`. Copy it to whatever folder of your choice. For example to `./mygitbook`
Then set it as default gitbook version to be used by gitbook-cli: `gitbook alias ./mygitbook latest`
Then find in the `./mygitbook/lib/output/ebook/getConvertOptions.js` the following code:
```javascript
            return options = extend(options, {
                '--chapter-mark':           String(pdfOptions.chapterMark),
                '--page-breaks-before':     String(pdfOptions.pageBreaksBefore),
                '--margin-left':            String(pdfOptions.margin.left),
                '--margin-right':           String(pdfOptions.margin.right),
                '--margin-top':             String(pdfOptions.margin.top),
                '--margin-bottom':          String(pdfOptions.margin.bottom),
                '--pdf-default-font-size':  String(pdfOptions.fontSize),
                '--pdf-mono-font-size':     String(pdfOptions.fontSize),
                '--paper-size':             String(pdfOptions.paperSize),
                '--pdf-page-numbers':       Boolean(pdfOptions.pageNumbers),
                '--pdf-sans-family':        String(pdfOptions.fontFamily),
                '--pdf-header-template':    headerTpl,
                '--pdf-footer-template':    footerTpl
            });
```

Edit it correspondingly. Add more calibre options if you need them. Do not forget to update your book.json with corresponding pdf.* properties. 

Happy hacking ;)
