### ISSUE TITLE
Unable to build all of my gitbooks

### ISSUE THREAD

**Issue by jakeoung** [GitbookIO/gitbook#1571]
### What is the current behavior?

Whenever I try to build my gitbooks, I got the following error:

`HTTP ERROR 404: "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/execute?id=</code> was not found on this server.  <ins>That’s all we know.</ins>\n"
`

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).

### What is the expected behavior?

I want to build. Even if I remove most of my contents, it fail to build.

For example, I created a new gitbook ( https://www.gitbook.com/book/jakeoung/test ). However, I couldn't build....

#### For GitBook.com

ID: jakeoung
https://www.gitbook.com/book/jakeoung/test

**Comment by aleen42** [comment]
Maybe the path of `execute` is wrong with a status 404.

**Comment by jakeoung** [comment]
How can I change the path of `execute` correctly? Actually, I only edited online, not on my local repository.

**Comment by aleen42** [comment]
@jakeoung Actually, you can't, because this is an error of Gitbook, and what you can do is only to wait for fixing. Notice that: I also have the same problem.

**Comment by dorry-terryli** [comment]
I have the same problem.

**Comment by swennemans** [comment]
Same problem :)

**Comment by djvulee** [comment]
Same problem too

**Comment by dbalakirev** [comment]
Same.

**Comment by swennemans** [comment]
Seems to be fixed.
