### ISSUE TITLE
Absolute path links are rewritten to be relative

### ISSUE THREAD

**Issue by mdekstrand** [GitbookIO/gitbook#1573]
### What is the current behavior?

When creating a link to an absolute path (e.g. `/apidocs/<some JavaDoc URL>`) in one of my content files, such a link is rewritten to be relative.

This rewriting is also done if I emit the absolute path from a `page` hook.
### What is the expected behavior?

I would like explicit absolute paths in links to be left as-is, or at least have the link rewriting behavior configurable.
### Additional Context

I am using GitBook to generate a manual that lives as a subdirectory of my main site (https://mooc.lenskit.org/documentation/); the root page is a landing page, and the JavaDoc and other resources live side-by-side with the GitBook manual.

This issue means that I must specify full absolute URLs, with protocol, to link to one of these parallel pages, which makes it harder to move the book content from the staging location for the version in development to the final location at release.

**Comment by hynek** [comment]
Sorry for spamming an old issue but I've run into the exact same problem and I've found a semi-good solution that might help people who are brought here by Google:

Write the URLs relative in the first place. So if you write in `/apidocs/endpoint.html` about `https://server/endpoint/`, make the link `../endpoint/`.

**Comment by timaschew** [comment]
This is fixed in my fork: https://github.com/timaschew/gitbook
