### ISSUE TITLE
Changes to styles/website.css do not trigger live reload

### ISSUE THREAD

**Issue by moxiegirl** [GitbookIO/gitbook#1574]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.
### What is the current behavior?
1. Add a `styles/website.css` to the book structure
2. Run `gitbook serve`
3. Note in Dev tools that the .css is picked up
4. Change the `styles/website.css` file.
    Live reload is not triggered
### What is the expected behavior?

If I change the .css it should trigger a live reload just as  it does when I change a content file.

---

The GitBook Team

**Comment by vjpr** [comment]
Any word on this?
