### ISSUE TITLE
Feature: support pull requests

### ISSUE THREAD

**Issue by iangilman** [GitbookIO/gitbook#1583]
I see you have support for multiple branches, but I don't see any way to diff branches or create pull requests. Have I overlooked something?

At any rate, while pull requests are overkill for some forms of collaborative writing, I think they would be crucial for others. For instance, imagine using Gitbook for policy documents or even legislation… People can make branches with their proposed changes and others can view the diff and comment line by line.

At the very least, being able to diff two branches would be a good thing!

**Comment by OndrejM** [comment]
It would be nice to have this.

Right now, what we do is create a separate book for every fork which we send pull requests from, and paste a link to the generated site into the pull-request comment. It works, but unnecessary if gitbooks already built pull requests in the target book.

**Comment by AaronO** [comment]
@OndrejM ouch, that workflow sounds painful ... :(

The good news is that we've been working on this specific feature over the past ~10 days and plan to ship something by the end of next week (next Wednesday is our target).

We're calling them "Change Requests" (name might change), the goal is to provide a structured async collaboration workflow that works for less technical people too, here's some info:
- Can create change requests from the editor
- Can (re)view, merge and discuss change requests from your book's dashboard
- Branches are transparently created and deleted upon merge (commits are still preserved of course)
- Nice rich diffs (WYSIWYGish diffs \o/)
- Each "change request" has it's own discussion thread
- Can easily preview final output

**Comment by iangilman** [comment]
Wonderful! Sounds like just like what I was hoping for :-)

**Comment by fedorov** [comment]
10 month later, and at least for us, mirroring the GitBook on GitHub, and making pull requests to the GitHub repo is still the only practical approach. "Change requests" do not generate email notifications, and do not provide interface for highlighting changes.
