### ISSUE TITLE
Escaped pipe character not handled correctly when rendering a table.

### ISSUE THREAD

**Issue by sam-falvo** [GitbookIO/gitbook#1584]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

Given the following table:

```
|fn4|Operation|Mnemonic|
|:-:|:-:|:-:|
|0000|Xrs1 + Xrs2|ADD|
|0001|Xrs1 << Xrs2|SLL|
|0010|Xrs1 < Xrs2 (signed)|SLT|
|0011|Xrs1 < Xrs2 (unsigned)|SLTU|
|0100|Xrs1 ^ Xrs2|XOR|
|0101|Xrs1 >> Xrs2 (unsigned)|SRL|
|0110|Xrs1 \| Xrs2|OR|
|0111|Xrs1 & Xrs2|AND|
|1000|Xrs1 - Xrs2|SUB|
|1001|undefined||
|1010|undefined||
|1011|undefined||
|1100|undefined||
|1101|Xrs1 >> Xrs2 (signed)|SRA|
|1110|undefined||
|1111|undefined||
```

It renders the line reading `0110` incorrectly.  The pipe is intended to represent the bitwise-OR operator of a C-like pseudocode, not a table column separator.

*> GitBook version being used (`gitbook -V`) and the system infromations (OS and version).*

$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
$ uname -a
Linux enif 3.19.0-66-generic #74-Ubuntu SMP Tue Jul 19 15:07:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### What is the expected behavior?

I'd like to see the pipe character appear in the table cell, and not denote a separate column in this case.

Thanks.

**Comment by paulyoung** [comment]
I'm still seeing this issue in the latest alpha, as mentioned here: https://github.com/GitbookIO/gitbook/issues/1270#issuecomment-273512106

**Comment by peterflynn** [comment]
This was supposedly fixed in the March 2017 version of Markdown (see https://stackoverflow.com/a/17320389/1172352), but it's still buggy in Gitbook as of October 2018.  Is Gitbook using a version of Markdown that's 18 months out of date?
