### ISSUE TITLE
Unable to link to plain HTML file from SUMMARY.md

### ISSUE THREAD

**Issue by pgraham** [GitbookIO/gitbook#1585]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

1. Create a plain HTML file inside of an existing book:

        + docs/
           + my-chapter/
              - plain-html-file.html

2. Add a link to the HTML in SUMMARY.md

        ```SUMMARY.md
        * ...
        * [An unprocessed HTML page](my-chapter/plain-html-file.html)
        * ...
        ```

3. Run `gitbook build`

### What is the expected behavior?

Build artifact will be produced with a link to the plain, unprocessed HTML file.
Actual behaviour is the following error message:

    FileNotParsableError: "my-chapter/plain-html-file.html" file cannot be parsed

#### For GitBook.com

Local book. For a bit of context about why this would be useful, I am trying to add a style guide to my docs and need absolute control over the HTML and CSS included in the page. This would provide an escape of sorts from Gitbook's HTML structure and CSS.

----

The GitBook Team

**Comment by bandantonio** [comment]
Currently this is possible via [otherlink](https://www.npmjs.com/package/gitbook-plugin-otherlink) plugin:

```
* [title A](path/to/file-a.md)
* [title B](ref://path/to/file-a.html)
```
