### ISSUE TITLE
syncing GitBook and GitHub

### ISSUE THREAD

**Issue by benchoufi** [GitbookIO/gitbook#1593]
Hi, I experienced a lot of problems when syncing GitBook and GitHub. So that, I decided to go from scratch : I created a test GitBook consisting of one single line. Then, I created a GitHub repo. I got to the GitBook settings page clicking the Sync your content with GitHub`. The problem is that it broke my GitBook and I couldn't open it anymore. 

So I decided, to go again from scratch, created a GitBook and followed [these instructions](https://help.gitbook.com/github/how-can-i-export-to-repo.html)
It did push the content of my GitBook to a newly created GitHub repo. But it did not sync them, I mean that when I update my GitBook content, it doesn't update the GitHub repo. Could you help plz ?

Best regards,
nowami

**Comment by logself1988** [comment]
Hi nowami,
That's strange, can you sync the content of GitHub to your GitBook?
Anyway, pls remember to link between GitHub and GitBook following [this](https://www.gitbook.com/blog/releases/github-integration)
