### ISSUE TITLE
Double curly braces usage in LaTeX context confuses the toolchain with its templating syntax

### ISSUE THREAD

**Issue by brlin-tw** [GitbookIO/gitbook#1597]
Not sure if this issue should be landed in LaTex plugin or toolchain itself...

### What is the current behavior?
Curly braces is also commonly used in LaTeX to separate elements, recently I got build failure with the message "Template render error: (&lt;filename&gt;) [&lt;location&gt;]  expected variable end" with the error-triggering source looks like:

```
* $$ \overrightarrow{V_{boatE}} = \sqrt{{V_{bW}}^2 + {V_{NE}}^2 } $$
```

It seems that the double opening curly braces after \sqrt confuses GitBook toolchain to believe it's a template syntax.

### What is the expected behavior?
The content in the LaTeX code shouldn't be considered to contain GitBook templating syntax

#### For GitBook.com
Username: Lin-Buo-Ren
Book: https://www.gitbook.com/book/lin-buo-ren/ntoucs-physics-course-open-source-project (commit 29521)

**Comment by mblakele** [comment]
Try using `{% raw %}` before the latex examples and `{% endraw %}` at the end. If you don't use templates at all then you can make those the first and last lines of the chapter.
