### ISSUE TITLE
Inline commnets do not work: missing required parameter title

### ISSUE THREAD

**Issue by pavolloffay** [GitbookIO/gitbook#1598]
Hello,

I'm unable to create a inline comment in our Gitbook [1] in JS console there is an error `"{"error":"Missing required parameter \"title\"","code":400}"` in the respose from the server.

Source code of our Gitbook is here [2].

[1] Gitbook: https://hawkular.gitbooks.io/hawkular-apm-user-guide/content/
[2] GH repo: https://github.com/hawkular/hawkular-apm-user-guide

Could you please help us with this?

**Comment by pavolloffay** [comment]
I have also created an issue in plugin-comment repository. #11

**Comment by SamyPesse** [comment]
It was an issue with our CDN, it has been fixed and it should work now 🚀
