### ISSUE TITLE
TwoFactor authentification makes it impossible to publish

### ISSUE THREAD

**Issue by Michal-Visuality** [GitbookIO/gitbook#1599]
I have two-factor enabled and it is impossible to publish the book to repository. The program just keep asking me for username/pwd:(

Version 6.2.1 on MacOs Sierra

**Comment by NoahJaehnert** [comment]
+1, I am having the same issue. Cannot publish to a github repo if two factor authentication is turned on in GitHub.

**Comment by simobasso** [comment]
you have to use a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
