### ISSUE TITLE
Joining page together in PDF

### ISSUE THREAD

**Issue by simonech** [GitbookIO/gitbook#1603]
Now when I generate a PDF I get a page break at the end of each source file. Is it possible to just append them one behind the other without putting a new source file in a new page?
I didn't find a way to configure this in the `book.json` file

**Comment by fishbar** [comment]
you means one part of the pic in the prev page, and another part in the next page ?

**Comment by simonech** [comment]
I mean, now when building a PDF I get a new page for every file in the source. But I need new pages only at the beginning of each chapter, not whenever i decided to split my chapter in multiple files

**Comment by marekjagielski** [comment]
@simonech have you find some workaround to this issue? I tried play with pdf.css like:
```
page-break-after: avoid;
page-break-inside: avoid;
```
but without a success.

**Comment by mgw-wjp** [comment]
@fishbar Hi，I have this problem too, how do you solve?

**Comment by simonech** [comment]
I moved to pandoc:)
