### ISSUE TITLE
Provide .tar.gz download of Gitbook Editor for non-debian systems (such as Fedora)

### ISSUE THREAD

**Issue by ge0ffrey** [GitbookIO/gitbook#1614]
On this page:
  https://www.gitbook.com/editor/linux
I downloaded Gitbook Editor for linux, which is .deb file.

Being on Fedora, I can't use the .deb file, so I turned it into an rpm with `alien -r gitbook-editor-6.2.1-linux-x64.deb`, but when I installed that I got "nothing provides libffmpeg.so()(64bit) needed by gitbook-editor-6.2.1-2.x86_64". Just providing a simple `.tar.gz` too, would probably make this easier to run on any linux platform.

**Comment by rvestal** [comment]
I do not use Ubuntu or Debian either. I use CentOS. Is there a tar.gz or an rpm that we could use instead? Alien cannot convert this deb to what is needed to get it working.

**Comment by Wardormeur** [comment]
Hi guys,
We had the same issue on Fedora 25.
Our workaround, probably more a debug of the process rather than a "pure" solution was to use `alien --generate debfile` to get the binary and deps. This will extract a folder which contains the binary which will be in ./gitbook-xx/opt/gitbook-editor/editor. (Pretty sure you can simply extract it as a tar without alien, it seems to be an archive.)
When running it, you may have errors indicating you're missing libs.
In our case, libssl.1.0.0 and libcrypto.1.0.0 were missing. dnf didn't returned any version available to installation for me and I didn't feel like looking into fedora 22 repos to get the corresponding one .. A `locate libname´ told us that this lib was provided elsewhere, spotify in my case.
Symlink time... `sudo ln -s pathToLib /usr/lib64/libName`
After that, the editor seemd to work fine

**Comment by dennisotugo** [comment]
[http://www.bt0.ninja/openssl-1-0-in-fedora-x86_64-2324-and-25/](http://www.bt0.ninja/openssl-1-0-in-fedora-x86_64-2324-and-25/ ) 
It fixes this issue for fedora users

**Comment by Shokodemon** [comment]
[gog@localhost gitbook]$ sudo rpm -i openssl-lib-compat-1.0.0i-1.fc25.x86_64.rpm 
	package openssl-lib-compat-1:1.0.0i-1.fc25.x86_64 is already installed
[gog@localhost gitbook]$ sudo rpm -i gitbook-editor-7.0.12-2.i386.rpm 
error: Failed dependencies:
	ld-linux.so.2 is needed by gitbook-editor-7.0.12-2.i386
	ld-linux.so.2(GLIBC_2.1) is needed by gitbook-editor-7.0.12-2.i386
	ld-linux.so.2(GLIBC_2.3) is needed by gitbook-editor-7.0.12-2.i386
	libX11.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libXcomposite.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libXcursor.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libXdamage.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libXext.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libXfixes.so.3 is needed by gitbook-editor-7.0.12-2.i386
	libXi.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libXrandr.so.2 is needed by gitbook-editor-7.0.12-2.i386
	libXrender.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libXss.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libXtst.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libasound.so.2 is needed by gitbook-editor-7.0.12-2.i386
	libasound.so.2(ALSA_0.9) is needed by gitbook-editor-7.0.12-2.i386
	libatk-1.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.0) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.1) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.1.2) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.1.3) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.2) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.2.3) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.3) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.3.2) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.3.4) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.4) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.6) is needed by gitbook-editor-7.0.12-2.i386
	libc.so.6(GLIBC_2.7) is needed by gitbook-editor-7.0.12-2.i386
	libcairo.so.2 is needed by gitbook-editor-7.0.12-2.i386
	libcups.so.2 is needed by gitbook-editor-7.0.12-2.i386
	libdbus-1.so.3 is needed by gitbook-editor-7.0.12-2.i386
	libdl.so.2 is needed by gitbook-editor-7.0.12-2.i386
	libdl.so.2(GLIBC_2.0) is needed by gitbook-editor-7.0.12-2.i386
	libdl.so.2(GLIBC_2.1) is needed by gitbook-editor-7.0.12-2.i386
	libexpat.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libffmpeg.so is needed by gitbook-editor-7.0.12-2.i386
	libfontconfig.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libfreetype.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libgcc_s.so.1 is needed by gitbook-editor-7.0.12-2.i386
	libgcc_s.so.1(GCC_3.0) is needed by gitbook-editor-7.0.12-2.i386
	libgcc_s.so.1(GCC_4.0.0) is needed by gitbook-editor-7.0.12-2.i386
	libgcc_s.so.1(GLIBC_2.0) is needed by gitbook-editor-7.0.12-2.i386
	libgconf-2.so.4 is needed by gitbook-editor-7.0.12-2.i386
	libgdk-x11-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libgdk_pixbuf-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libgio-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libglib-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libgmodule-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libgobject-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libgtk-x11-2.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libm.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libm.so.6(GLIBC_2.0) is needed by gitbook-editor-7.0.12-2.i386
	libm.so.6(GLIBC_2.1) is needed by gitbook-editor-7.0.12-2.i386
	libnspr4.so is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.10) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.11) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.11.1) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.12) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.12.1) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.12.3) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.12.4) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.2) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.3) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.4) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.5) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.6) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.7) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.8) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.9) is needed by gitbook-editor-7.0.12-2.i386
	libnss3.so(NSS_3.9.2) is needed by gitbook-editor-7.0.12-2.i386
	libnssutil3.so is needed by gitbook-editor-7.0.12-2.i386
	libnssutil3.so(NSSUTIL_3.12) is needed by gitbook-editor-7.0.12-2.i386
	libnssutil3.so(NSSUTIL_3.12.3) is needed by gitbook-editor-7.0.12-2.i386
	libpango-1.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libpangocairo-1.0.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0 is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.0) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.1) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.12) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.2) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.2.3) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.3.2) is needed by gitbook-editor-7.0.12-2.i386
	libpthread.so.0(GLIBC_2.3.3) is needed by gitbook-editor-7.0.12-2.i386
	librt.so.1 is needed by gitbook-editor-7.0.12-2.i386
	librt.so.1(GLIBC_2.2) is needed by gitbook-editor-7.0.12-2.i386
	libsmime3.so is needed by gitbook-editor-7.0.12-2.i386
	libsmime3.so(NSS_3.10) is needed by gitbook-editor-7.0.12-2.i386
	libsmime3.so(NSS_3.2) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6 is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(CXXABI_1.3) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(CXXABI_1.3.5) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4.10) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4.11) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4.14) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4.15) is needed by gitbook-editor-7.0.12-2.i386
	libstdc++.so.6(GLIBCXX_3.4.9) is needed by gitbook-editor-7.0.12-2.i386


please provide a tar gz

**Comment by patdec** [comment]
Hello.

The same for me. I'm on Fedora 27 and I can't install Gitbook :(

**Comment by lyshie** [comment]
Try this one, tested on Fedora 26/27.

https://gist.github.com/lyshie/330b84d8c2c1b4f397d85f5ec752b859
