### ISSUE TITLE
Relative Internal Links Not Converted to HTML Or Scoped To 'Content'

### ISSUE THREAD

**Issue by Undistraction** [GitbookIO/gitbook#1620]
Having issues with relative internal links when using gitbook.com.

My book is called Example.

# Inside Editor

- I have an article called **alpha_article.md**
- I have another article called **beta_article.md**
- Inside **alpha_article.md** I would like to link the text **Beta** to **beta_article.md**
- I select **Beta** and add a link, setting the path to **../beta_article.md**
- I click on this link and choose **Open**
- **beta_article.md** opens correctly

# Inside Read

- I open **https://me.gitbooks.io/example/content/alpha_article.html**
- I click on the text **Beta** 
- I get a 404 with the URL: **https://me.gitbooks.io/example/beta.md**
- I also get a 404 If I manually input the URL to use a .html suffix: **https://me.gitbooks.io/example/beta.html**
- I can open the page with **https://me.gitbooks.io/example/content/beta.html**

So it seems that the relative link is:

1. Not converted to **.html**
2. Not scoped to **content**

**Comment by nagim** [comment]
How does your folder structure look like?

**Comment by Undistraction** [comment]
My folder structure is totally flat.

# Files Tree
- alpha.md
- beta.md

**Comment by nagim** [comment]
If they are on the same level, then don't set it as `../beta.md`, only `beta.md`. The `../` means that the references file should be one levél up.

**Comment by Undistraction** [comment]
Thanks. Should have tried that, but thought that it was correct because I could open the right file in the editor with the `../` version.

I'm using the web interface via gitbook.com which I assume is the latest version.

**Comment by nagim** [comment]
No problem, relative links can be tricky. If you haven't specified the version in `book.json` the you must be using the latest (3.2.2) version. This means you can use absolute links instead of relatíve, which means less room for error.
