### ISSUE TITLE
How to extend theme from book source (layout customization)?

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1622]
As described in [Theming](https://toolchain.gitbook.com/themes/)...

> Extend/Customize theme in a book
>
> Authors can extend the templates of a theme directly from their book's source (without creating an external theme). Templates will be resolved in the _layouts folder of the book first, then in the installed plugins/themes.

... I tried to extend the default theme, but couldn't get it to work.

I created a folder `_layouts` in my book root path and put a file `layout.html` inside with the following content:

```
{% extends template.self %}

{% block body %}
    This is the block body!
    {{ super() }}
{% endblock %}
```

If I build my book and inspect the resulting HTML code, I can't find `This is the block body!` anywhere.

    gitbook build . ../../books/Manual --gitbook=3.2.2

What is the proper way to do this? I would prefer not to publish the theme.

I'm essentially looking for a replacement for the `"body:start"` hook, which does not seem to work anymore with Gitbook 3.x.

CLI version: 2.3.0
GitBook version: 3.2.2
node v5.10.1

**Comment by cimi** [comment]
After following the steps from the documentation on theming I am hitting the same issue.

I have a `_layouts` directory in the root of my project, in the same directory as `book.json`. Whenever I change a file in `_layouts` the book re-generates (i.e. if I am running the server in watch mode) but there is no effect on the generated content.

I've tried both `_layouts/website/page.html` as suggested in the documentation and `_layouts/layout.html` as @Simran-B tried above to no effect. I've even tried invalid syntax, imbalanced tags etc. and it doesn't seem to affect anything, which leads me to think the template files are not even being parsed. 

Running `gitbook serve --log=debug` outputs nothing related to templating / themes. I've tried this with the following themes: default, official, faq, API.

**Comment by cimi** [comment]
@SamyPesse @AaronO ping

I don't want to pester you guys, the product's great and I'm happy using it the way it is! One thing I want to make sure though is the fact that either myself or the documentation is not missing something obvious.

**Comment by daylightstudio** [comment]
I'm running into a similar issue as described above.

**Comment by kjhenner** [comment]
@cimi Any chance your book has multiple languages? I noticed that the _layouts has to be in the language directory rather than the root directory (or symlinked)

**Comment by cimi** [comment]
@kjhenner Nope - just one. My setup is pretty standard, here's my `book.json`:

```json
{
    "root": "./docs",
    "title": "Documentation",
    "plugins": [
      "-sharing",
      "-fontsettings",
      "-highlight",
      "prism",
      "callouts",
      "mermaid-gb3",
      "katex",
      "page-toc",
      "collapsible-menu"
    ]
}
```
