### ISSUE TITLE
Tables that are too wide are cut off

### ISSUE THREAD

**Issue by ackerleytng** [GitbookIO/gitbook#1626]
CLI version: 2.3.0
GitBook version: 3.2.0
I'm running this on Ubuntu 16.04.

When there are too many columns in a table, the table gets cut off when displayed. I think the solution to this would be to have extremely wide tables scroll sideways.

**Comment by borisschapira** [comment]
Same issue here. As far as I understand the project, we would have to create a gitbook plugin implementing a JS solution, for example https://github.com/filamentgroup/tablesaw, and put html tables instead of the default markdown one.

Could one of the experimented developer confirm, before I spend time on this?

**Comment by Soreine** [comment]
@ackerleytng Do you have an example (or a screenshot) of the issue?
@borisschapira Before going for dynamic tables using JS, it could be a good idea to experiment with pure HTML, using CSS and scroll attributes, as suggested by @ackerleytng. Dynamic solutions are often more complex than needed, and are not valid for PDF exports. Maybe a plugin could allow to reduce the font size and padding on a per-table basis. It would be simple and flexible.

Related on the PDF side: https://github.com/GitbookIO/gitbook/issues/1442

**Comment by borisschapira** [comment]
@Soreine There are two issues, in fact.

1. how to display table on the generated website. If the answer is "horizontal scrolling", it must be allowed in JS. If not, see 2.
2. how to display tabular data into documents when there is not enough width. The CSS from the mobile view of tablesaw can help with that.

**Comment by ackerleytng** [comment]
Here's the README.md page:

```
# Introduction

| a | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | lorem ipsum    | c |
|---|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|---|
| x | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | dolor sit amet | z |
```

And here's the result

![cut-off](https://cloud.githubusercontent.com/assets/2399902/21332326/916dab88-c682-11e6-89cb-3adec95d05dc.png)

**Comment by zxdy** [comment]
Same issue. is there any update？

**Comment by egpbos** [comment]
+1

**Comment by Arnold134777** [comment]
Same issue. is there any update？

**Comment by zenoven** [comment]
+1

**Comment by chrisjake** [comment]
I've fixed this issue (with my tables at least) with css:

`.markdown-section table {
    table-layout: fixed;
    display:block;
    overflow-x: auto;
}`

Haven't noticed any undue effects yet. Tested on Chrome for windows and chrome for ipad. Just add the above to your website.css in the styles folder.

**Comment by Dana-awake** [comment]
Hmmm, works for online help, but not in PDF.

**Comment by BlackUmbrella** [comment]
same issue for PDF. (+1)

**Comment by xiaohaoliang** [comment]
+1

**Comment by StevenLi-DS** [comment]
@chrisjake I initialized a book but only saw two.md files README and SUMMARY. Am I missing something?
