### ISSUE TITLE
error: tree.sha .... is not a valid blob

### ISSUE THREAD

**Issue by joreg** [GitbookIO/gitbook#1629]
### What is the current behavior?
Our gitbook has been working fine for a few years now. But today when i edited and then published a page i got a red error popup in the bottom right corner of firefox that says: 
 tree.sha ... is not a valid blob
and no commit is created. 

the book is using ascidoc and markdown for different pages. and we've linked it to a private github repository. if i make the same changes in the github repo directly, the html rendering updates correctly. 
#### For GitBook.com
https://www.gitbook.com/book/vvvv/the-gray-book/details

is there anything i can do about this?

**Comment by Soreine** [comment]
@joreg I could not reproduce the bug locally. Have you tried editing from another browser ? 

If possible, after getting the error, open the browser console, and send me its content at nicolas@gitbook.com:

- Using Firefox: open the console with <kbd>Ctrl+Shift+K</kbd> (<kbd>Command+Option+K</kbd> on OSX), right-click, Select-All, right-click, Copy, and paste the whole thing in the email
- Using Chrome: open the console with <kbd>Ctrl+Shift+J</kbd> (<kbd>Ctrl+Shift+J</kbd> on OSX), right-click, Save as..., and send the saved `.log` file.

If we can't find the root of the problem, I can also try editing your book live, and debug on my side, if you will allow it.

**Comment by joreg** [comment]
oui, you got mail!

**Comment by om64** [comment]
I've got exactly the same problem as Soreine under Firefox. So I tried with Chrome and it worked.

**Comment by AmberWilkie** [comment]
I am also having this problem, but it's not working in Chrome.

**Comment by AaronO** [comment]
@Soreine Any conclusion on this issue ? Is it with the `editor` or `git-server` ?

**Comment by Soreine** [comment]
@AmberWilkie can you tell me on which book you're having this bug?

**Comment by AmberWilkie** [comment]
This one: https://github.com/CraftAcademy/caac_precourse

Turns out I could work on it fine in Safari... never got it to work in Chrome on master or any other branch.

**Comment by Soreine** [comment]
Do you have any pending changes on Chrome? You can tell so if the Publish button is blue on opening the editor. Or by looking in the files view, if any file has a yellow or green margin (have a look inside directories too).
If yes, I would like to know what files have pending changes, and if some of them are big files (such as images)?

**Comment by leiyunhe** [comment]
@Soreine I've got the same question, using chrome. 
https://www.gitbook.com/book/leiyunhe/learnpythonnotes/details


![gitbooktreeisnotvalidblob](https://cloud.githubusercontent.com/assets/22088422/21793749/100dba34-d72f-11e6-8a22-67e8e697eee5.png)

**Comment by AmberWilkie** [comment]
The button is blue and there are 8 pending changes in 8 files - none of
them are particularly large. Some of them are extremely small files with
just a couple paragraphs of text.

I don't have files with pending changes left because I was able to make the
updates in Safari - I just copied over from the Chrome browser.


*Amber Wilkie*
www.amberwilkie.com
0720.08.27.07 | Instagram <http://www.instagram.com/amberwphoto>

**Comment by Soreine** [comment]
@joreg @AmberWilkie @leiyunhe @om64 
Thanks a lot for your help. We have narrowed down the cause. It comes from submodules in the git repository, that the Editor does not handles right. I'm working on a fix. Please notify me if some of you are not using submodules in your git repositories.

**Comment by joreg** [comment]
@Soreine no submodules in our repo

**Comment by Soreine** [comment]
@joreg thank you, could you please open the web editor (if relevant, using the browser where you're having the problem), open the browser console, enter this `JSON.stringify(appStore.getState().repository.repoState.toJS())` and copy-paste me the full result?
It might be large, or private, so don't hesitate to email it at soreine@gitbook.com

**Comment by Soreine** [comment]
A huge thank you to everyone. We have found the root of the problem now. We are on our way to release a new version of the Editor. In the process, you will lose the un-published changes on your browsers. If some of it was important, let me know, and I will help you recover it.
