### ISSUE TITLE
Switch input lead to Browser break

### ISSUE THREAD

**Issue by seanutf** [GitbookIO/gitbook#1630]
Hi, I'm a Chinese editor.  So I have a little English. I'm not sure I can expression all my opinion. When I open website and load the cache in last I'm edited. I move the cursor to the  last and focus，then I trying switch Input. In this case, the Browser is break. So I don't know what's happened. It only occur in  
Mac 10.12.1 Chrome 55.0.2883.87 . At last, Thank you!

**Comment by Soreine** [comment]
Hello @seanutf 
If I understand well, you go to edit your book with the online Editor, you move your cursor at the end of your document, and you start writing and the browser breaks. I have a few question:

- By "strying switch Input", do you mean you switch input mode to write Chinese characters?
- How precisely the browser breaks? Does it stop responding completely?

Can you try writing there and tell me if you have the same problem ? http://slatejs.org/

**Comment by seanutf** [comment]
Yes,It's complete stop when I switch input mode to write Chinese characters.

**Comment by Soreine** [comment]
> It only occur in Mac 10.12.1 Chrome 55.0.2883.87
Do you mean it works on a Windows machine ? Or does it work with Firefox, or Safari, but not with Chrome ?

I have tried to reproduce the bug, on Chrome, using Pinyin input method for Simplified Chinese, but the browser did not crash. If it's not writing characters that break the browser, but simply switching input mode, what do you do exactly to switch input mode ?

**Comment by seanutf** [comment]
On Windows,it's work. On Mac , Chrome is crash, I'm try to edit in Safari,but it can't focus. To switch input mode, I just press Cap Lock on 2016 New Mac Pro.

**Comment by AaronO** [comment]
@seanutf Any chance you could record what you're doing and upload a video of it ? (to youtube or something)

That would help us understand and debug the issue.

**Comment by seanutf** [comment]
Nothing for Chrome or Mac. When Chrome crash, I reopen it. open my book, press Cap Lock for Simplified Chinese, then it crash again.

**Comment by seanutf** [comment]
@Soreine @AaronO

**Comment by seanutf** [comment]
@Soreine @AaronO Sorry,I misled you. It's doesn't matter to switch input mode.Today,I I found The reason for this issue is  a label in my text.Like this:
> 让开发者在DrawableContainers里引用<vector>
> 可以在DrawableContainers里使用<vector>，但在23.3.0版本时收回了。 
So, if I want to this label in my text, not in code, what I should do?  Finally, thank you for your help.
