### ISSUE TITLE
How to resize image in the markdown of Gitbook

### ISSUE THREAD

**Issue by datafibers** [GitbookIO/gitbook#1631]
Just wonder How to resize image in the markdown of Gitbook?

**Comment by Soreine** [comment]
You can use HTML or a plugin to do that, for example:

```md
# Heading

Here is an 200x100 image:

<img src="http://image.com/image.png" width="200" height="100" />
```

See existing issues on this topic:
- https://github.com/GitbookIO/gitbook/issues/1488
- https://github.com/GitbookIO/gitbook/issues/1451

**Comment by SamyPesse** [comment]
But we are having discussion about supporting this in Markdown: https://github.com/GitbookIO/markup-it/issues/24

**Comment by datafibers** [comment]
I thought it does not work since it does not render in online editor. It turns out that it shows correctly once published. Thanks a lot.

**Comment by fruch** [comment]
use img tag only work on pdf version, on the published html it's getting stuck and can't read it

**Comment by fruch** [comment]
this feels so 1990, that we have to manually resize the images... really annoying, does being a paying customer helps in that regard ?

**Comment by nelsonam** [comment]
I have the same question. I need to resize screenshots for a software documentation project. Any updates on this?
