### ISSUE TITLE
 Please tell me about licensing.

### ISSUE THREAD

**Issue by helo717** [GitbookIO/gitbook#1632]
I am contracting Organization now. It is the following plan.
(Unlimited private books at $ 14 / month for your first 2 users, $ 7 / month for each additional user)

The member of this Organization is zero, but people have three people.
In this case, will the payment be $ 21 ($ 14 + $ 7)?

Nice to meet you.

**Comment by CharlesWiltgen** [comment]
Apologies if I'm misunderstanding your question, but the [GitBook pricing page](https://www.gitbook.com/pricing) confirms a price of $21/month for 3 users.
