### ISSUE TITLE
Chinese markdown problem for NEW version.

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1633]
### What is the current behavior?

I can't reproduce the problem,but the new version gitbook often markdown uncontrolled.

### What is the expected behavior?

NEW VERSION UI is good,but new auto markdown is bad.

**Comment by Soreine** [comment]
Hello, thank you for reporting the issue. If I understand well, you have issues with writing Markdown directly in the Document mode (WYSIWYG, no preview mode)? Could you then provide a precise example, where typing markdown does not work as expected ?

**Comment by Soreine** [comment]
Also, why does it relate to Chinese in particular?

**Comment by EasonWang01** [comment]
Finally,it might not relative to chinese,but the no preview mode,so change back to the document is fine.
