### ISSUE TITLE
The following code didn't show syntax hightlight at all.

### ISSUE THREAD

**Issue by cwchentw** [GitbookIO/gitbook#1636]
I wrote a book about programming recently.  However, I found a strange bug: the seemly normal code snippet didn't show syntax highlight at all:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
     const int SIZE = 10;

     // Allocate memory for array.
     int* a = (int*) malloc(SIZE * sizeof(int));

     // Shared the address of a to a1
     int* a1 = a;

     // Set the value in a
     for (int i = 0; i < SIZE; i++) {
        int j = i + 1;
        a[i] = j * j;
     }

      // Free the memory of a
      free(a);
      a = NULL;

      // Now a1 becomes dangling pointer.
      // It is undefined to accessing data via a dangling pointer.
      printf("%d\n", a1[3]);

      return 0;
}
```

After some trials, I found a smaller code snippet that repeated the bug:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
    int* a = (int*) malloc(SIZE * sizeof(int));
}
```

If I removed the "sentence", the gitbook succeed to show highlight again.

I thought it was a bug because I copied this code snippet to a brand new gitbook project and the code snippet still failed to show any highlight.  All my other code snippet didn't repeat this bug.

Some information:

CLI version: 2.3.0
GitBook version: 3.2.2
OS: Mac OS X 10.11.3

Still thanks to Gitbook Team for this great publishing platform.

**Comment by johnlinp** [comment]
The problem can be solved by installing the latest highlight plugin:

```
npm install gitbook-plugin-highlight@2.0.3
```

instead of using the native plugin, it will use the plugin in `node_modules`.
