### ISSUE TITLE
Very Lag if Article content too large for NEW VERSION

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1637]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

OLD version no this problem.But in NEW version.

Very Lag if Article content too large

https://easonwang01.gitbooks.io/web_advance/content/react.html

when editing I need to wait 5 sec then typing for each char.

but other article works fine. 

### What is the expected behavior?

no lag

#### For GitBook.com

Provide, if possible, your username and the URL of the concerned book.

----

The GitBook Team

**Comment by Soreine** [comment]
Indeed. Thank you for the example
Moved to https://github.com/GitbookIO/feedback/issues/281
