### ISSUE TITLE
buid failed with 'autocover'

### ISSUE THREAD

**Issue by hgwang** [GitbookIO/gitbook#1643]
when I submit the code, it's build failed:
```
GitBook version is 3.2.1 
Tweaking book.json
Installing plugins
info: installing 2 plugins using npm@3.9.2 
info:  
info: installing plugin "advanced-emoji" 
info: install plugin "advanced-emoji" (*) from NPM with version 0.2.1 
handbook@0.0.1 /tmp/book
└─┬ gitbook-plugin-advanced-emoji@0.2.1 
  └── emojify.js@1.1.0 

info: >> plugin "advanced-emoji" installed with success 
info:  
info: installing plugin "autocover" 
info: install plugin "autocover" (*) from NPM with version 2.0.1 
- nan@1.2.0 node_modules/gitbook-plugin-autocover/node_modules/canvas/node_modules/nan
- canvas@1.1.6 node_modules/gitbook-plugin-autocover/node_modules/canvas
- lodash@2.4.1 node_modules/gitbook-plugin-autocover/node_modules/lodash
- q@1.0.1 node_modules/gitbook-plugin-autocover/node_modules/q

Error: EXDEV, rename '/tmp/book/node_modules/gitbook-plugin-autocover'
```
this is *book.json* config:

```
{
    "gitbook": "3.2.1",
    "plugins" : ["advanced-emoji"]
}

```

**Comment by kxxoling** [comment]
Seems I got the same issue but I haven't set it in book.json, and the preview of my book got broken:

![gitbook cover issue](https://cloud.githubusercontent.com/assets/1227139/23553033/bb4469ae-0059-11e7-9032-2cbc5bb2d8fd.png)

I can only remember that I set a cover for the book below but not the upper one. So I guess there's something wrong with the cover image setting which I cannot find how to remove it now.

**Comment by Soreine** [comment]
@hgwang We are investigating the reason why the plugin autocover is being installed in the first place.

@kxxoling The issue with the book icon is a bug on GitBook.com that we are going to fix. It is not related with your builds failing.
