### ISSUE TITLE
PDF build fails

### ISSUE THREAD

**Issue by onshek** [GitbookIO/gitbook#1644]
### What is the current behavior?

I want to convert .md into PDFs, and I followed <https://toolchain.gitbook.com/ebook.html>:

> Download the Calibre application. After moving the calibre.app to your Applications folder create a symbolic link to the ebook-convert tool:

> 
`$ sudo ln -s ~/Applications/calibre.app/Contents/MacOS/ebook-convert /usr/bin`

Then I got this:

```
HF:The-North-Book wonderful$ sudo ln -s ~/Applications/calibre.app/Contents/MacOS/ebook-convert /usr/bin
Password:
ln: /usr/bin/ebook-convert: File exists
HF:The-North-Book wonderful$ PATH
-bash: PATH: command not found
HF:The-North-Book wonderful$ gitbook pdf ./ ./mybook.pdf
info: 7 plugins are installed 
info: 6 explicitly listed 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 26 pages 
info: found 0 asset files 

InstallRequiredError: "ebook-convert" is not installed.
Install it from Calibre: https://calibre-ebook.com
```

While I do have installed calibre 2, so I don't know where the problem is.Can someone help me?

### What is the expected behavior?

convert .md into PDFs normally

#### For GitBook.com

This is the book:
<https://ipreacher.gitbooks.io/the-north/content/>
<https://github.com/ipreacher/The-North-Book>

**Comment by siegerts** [comment]
Make sure that is the actual path to `ebook-convert`.

I had to mod my symlink to `/Applications/calibre.app/Contents/MacOS/ebook-convert` less the `~`  home dir.

You'll  may need to remove and/or update your link accordingly.
