### ISSUE TITLE
Can't web editing in Safari

### ISSUE THREAD

**Issue by coffeed-jason** [GitbookIO/gitbook#1645]
Some problems in Safari browser on MacBook. It occurs when 'document mode' is turned off. Specifically, Gitbook editor isn't activated and hasn't mouse cursor. In this status, I couldn't edit gitbook md file. However, when Document Mode is turend on, Editor is working well. This is limited in safari browser(version 10.0.2) so it is working in chrome browser.

**Comment by Soreine** [comment]
Fixed in 6.4.2
