### ISSUE TITLE
gitbook build fails

### ISSUE THREAD

**Issue by wangbinlml** [GitbookIO/gitbook#1650]
I want to build .md(or gitbook serve),Then I got this error:
RangeError: Maximum call stack size exceeded.

I don't know where the problem is.Can someone help me?

gitbook version is:

CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by nagim** [comment]
Please paste here the full log, as this can be caused by a couple of things.

**Comment by wangbinlml** [comment]
@nagim thanks

[root@app1 hbb_api_docs]# gitbook build
info: loading book configuration....OK 
info: load plugin gitbook-plugin-expandable-chapters ....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: >> 5 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 
RangeError: Maximum call stack size exceeded

**Comment by nagim** [comment]
Sorry, I forgot this: could you run the build with the `--debug` option (`gitbook build --debug`)? It gives more detailed log.

**Comment by wangbinlml** [comment]
@nagim  i run command is gitbook build ./ --log=debug --debug ,got this error log

info: 7 explicitly listed 
info: loading plugin "expandable-chapters"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 394 pages 
info: found 90 asset files 

........


debug: write parsed file web/album/save_photo.md to web/album/save_photo.html 
debug: processing web/album/student_photos.md 81% 
debug: start parsing file web/album/student_photos.md 
debug: render template web/album/student_photos.md 
debug: use file parser markdown for web/album/student_photos.md 
debug: call hook page 
debug: index page web/album/student_photos.md 
debug: write parsed file web/album/student_photos.md to web/album/student_photos.html 
debug: processing web/album/time_range.md 81% 
debug: start parsing file web/album/time_range.md 
debug: render template web/album/time_range.md 
debug: use file parser markdown for web/album/time_range.md 
debug: call hook page 
debug: index page web/album/time_range.md 
debug: write parsed file web/album/time_range.md to web/album/time_range.html 
debug: processing web/album/update.md 81% 
debug: start parsing file web/album/update.md 
debug: render template web/album/update.md 
debug: use file parser markdown for web/album/update.md 
debug: call hook page 
debug: index page web/album/update.md 
debug: write parsed file web/album/update.md to web/album/update.html 
debug: processing web/album/update_photo.md 81% 
debug: start parsing file web/album/update_photo.md 
debug: render template web/album/update_photo.md 
debug: use file parser markdown for web/album/update_photo.md 
debug: call hook page 
debug: index page web/album/update_photo.md 
debug: write parsed file web/album/update_photo.md to web/album/update_photo.html 
debug: processing web/album/upload_photos.md 82% 
debug: start parsing file web/album/upload_photos.md 
debug: render template web/album/upload_photos.md 
debug: use file parser markdown for web/album/upload_photos.md 
debug: call hook page 
debug: index page web/album/upload_photos.md 
debug: write parsed file web/album/upload_photos.md to web/album/upload_photos.html 
debug: processing web/album/year_photos.md 82% 
debug: start parsing file web/album/year_photos.md 
debug: render template web/album/year_photos.md 
debug: use file parser markdown for web/album/year_photos.md 
debug: call hook page 
debug: index page web/album/year_photos.md 
debug: write parsed file web/album/year_photos.md to web/album/year_photos.html 
debug: processing web/approvals/approvals.md 82% 
debug: start parsing file web/approvals/approvals.md 
debug: render template web/approvals/approvals.md 
debug: use file parser markdown for web/approvals/approvals.md 
debug: call hook page 
debug: index page web/approvals/approvals.md 
debug: write parsed file web/approvals/approvals.md to web/approvals/approvals.html 
debug: processing web/approvals/list.md 82% 
debug: start parsing file web/approvals/list.md 
debug: render template web/approvals/list.md 
debug: use file parser markdown for web/approvals/list.md 
debug: call hook page 
debug: index page web/approvals/list.md 
debug: write parsed file web/approvals/list.md to web/approvals/list.html 
debug: processing web/approvals/save.md 83% 
debug: start parsing file web/approvals/save.md 
debug: render template web/approvals/save.md 
debug: use file parser markdown for web/approvals/save.md 
debug: call hook page 
debug: index page web/approvals/save.md 
debug: write parsed file web/approvals/save.md to web/approvals/save.html 
debug: processing web/approvals/update.md 83% 
debug: start parsing file web/approvals/update.md 
debug: render template web/approvals/update.md 
debug: use file parser markdown for web/approvals/update.md 
debug: call hook page 
debug: index page web/approvals/update.md 
debug: write parsed file web/approvals/update.md to web/approvals/update.html 
debug: processing web/attendancewarn/attendancewarn.md 83% 
debug: start parsing file web/attendancewarn/attendancewarn.md 
debug: render template web/attendancewarn/attendancewarn.md 
debug: use file parser markdown for web/attendancewarn/attendancewarn.md 
debug: call hook page 
debug: index page web/attendancewarn/attendancewarn.md 
debug: write parsed file web/attendancewarn/attendancewarn.md to web/attendancewarn/attendancewarn.html 
debug: processing web/attendancewarn/detail.md 83% 
debug: start parsing file web/attendancewarn/detail.md 
debug: render template web/attendancewarn/detail.md 
debug: use file parser markdown for web/attendancewarn/detail.md 
debug: call hook page 
debug: index page web/attendancewarn/detail.md 
debug: write parsed file web/attendancewarn/detail.md to web/attendancewarn/detail.html 
debug: processing web/attendancewarn/save.md 84% 
debug: start parsing file web/attendancewarn/save.md 
debug: render template web/attendancewarn/save.md 
debug: use file parser markdown for web/attendancewarn/save.md 
debug: call hook page 
debug: index page web/attendancewarn/save.md 
debug: write parsed file web/attendancewarn/save.md to web/attendancewarn/save.html 
debug: processing web/commons/modifypassword.md 84% 
debug: start parsing file web/commons/modifypassword.md 
debug: render template web/commons/modifypassword.md 
debug: use file parser markdown for web/commons/modifypassword.md 
debug: call hook page 
debug: index page web/commons/modifypassword.md 
debug: write parsed file web/commons/modifypassword.md to web/commons/modifypassword.html 
debug: processing web/commons/settings.md 84% 
debug: start parsing file web/commons/settings.md 
debug: render template web/commons/settings.md 
debug: use file parser markdown for web/commons/settings.md 
debug: call hook page 
debug: index page web/commons/settings.md 
debug: write parsed file web/commons/settings.md to web/commons/settings.html 
debug: processing web/contract/contract.md 84% 
debug: start parsing file web/contract/contract.md 
debug: render template web/contract/contract.md 
debug: use file parser markdown for web/contract/contract.md 
debug: call hook page 
debug: index page web/contract/contract.md 
debug: write parsed file web/contract/contract.md to web/contract/contract.html 
debug: processing web/contract/contractCount.md 85% 
debug: start parsing file web/contract/contractCount.md 
debug: render template web/contract/contractCount.md 
debug: use file parser markdown for web/contract/contractCount.md 
debug: call hook page 
debug: index page web/contract/contractCount.md 
debug: write parsed file web/contract/contractCount.md to web/contract/contractCount.html 
debug: processing web/contract/contractList.md 85% 
debug: start parsing file web/contract/contractList.md 
debug: render template web/contract/contractList.md 
debug: use file parser markdown for web/contract/contractList.md 
debug: call hook page 
debug: index page web/contract/contractList.md 
debug: write parsed file web/contract/contractList.md to web/contract/contractList.html 
debug: processing web/contract/deleteContract.md 85% 
debug: start parsing file web/contract/deleteContract.md 
debug: render template web/contract/deleteContract.md 
debug: use file parser markdown for web/contract/deleteContract.md 
debug: call hook page 
debug: index page web/contract/deleteContract.md 
debug: write parsed file web/contract/deleteContract.md to web/contract/deleteContract.html 
debug: processing web/contract/saveContract.md 85% 
debug: start parsing file web/contract/saveContract.md 
debug: render template web/contract/saveContract.md 
debug: use file parser markdown for web/contract/saveContract.md 
debug: call hook page 
debug: index page web/contract/saveContract.md 
debug: write parsed file web/contract/saveContract.md to web/contract/saveContract.html 
debug: processing web/contract/updateContract.md 86% 
debug: start parsing file web/contract/updateContract.md 
debug: render template web/contract/updateContract.md 
debug: use file parser markdown for web/contract/updateContract.md 
debug: call hook page 
debug: index page web/contract/updateContract.md 
debug: write parsed file web/contract/updateContract.md to web/contract/updateContract.html 
debug: processing web/antiepidemic/antiepidemic.md 86% 
debug: start parsing file web/antiepidemic/antiepidemic.md 
debug: render template web/antiepidemic/antiepidemic.md 
debug: use file parser markdown for web/antiepidemic/antiepidemic.md 
debug: call hook page 
debug: index page web/antiepidemic/antiepidemic.md 
debug: write parsed file web/antiepidemic/antiepidemic.md to web/antiepidemic/antiepidemic.html 
debug: processing web/antiepidemic/antiepidemicCount.md 86% 
debug: start parsing file web/antiepidemic/antiepidemicCount.md 
debug: render template web/antiepidemic/antiepidemicCount.md 
debug: use file parser markdown for web/antiepidemic/antiepidemicCount.md 
debug: call hook page 
debug: index page web/antiepidemic/antiepidemicCount.md 
debug: write parsed file web/antiepidemic/antiepidemicCount.md to web/antiepidemic/antiepidemicCount.html 
debug: processing web/antiepidemic/antiepidemicList.md 86% 
debug: start parsing file web/antiepidemic/antiepidemicList.md 
debug: render template web/antiepidemic/antiepidemicList.md 
debug: use file parser markdown for web/antiepidemic/antiepidemicList.md 
debug: call hook page 
debug: index page web/antiepidemic/antiepidemicList.md 
debug: write parsed file web/antiepidemic/antiepidemicList.md to web/antiepidemic/antiepidemicList.html 
debug: processing web/antiepidemic/deleteAntiepidemic.md 87% 
debug: start parsing file web/antiepidemic/deleteAntiepidemic.md 
debug: render template web/antiepidemic/deleteAntiepidemic.md 
debug: use file parser markdown for web/antiepidemic/deleteAntiepidemic.md 
debug: call hook page 
debug: index page web/antiepidemic/deleteAntiepidemic.md 
debug: write parsed file web/antiepidemic/deleteAntiepidemic.md to web/antiepidemic/deleteAntiepidemic.html 
debug: processing web/antiepidemic/saveAntiepidemic.md 87% 
debug: start parsing file web/antiepidemic/saveAntiepidemic.md 
debug: render template web/antiepidemic/saveAntiepidemic.md 
debug: use file parser markdown for web/antiepidemic/saveAntiepidemic.md 
debug: call hook page 
debug: index page web/antiepidemic/saveAntiepidemic.md 
debug: write parsed file web/antiepidemic/saveAntiepidemic.md to web/antiepidemic/saveAntiepidemic.html 
debug: processing web/antiepidemic/updateAntiepidemic.md 87% 
debug: start parsing file web/antiepidemic/updateAntiepidemic.md 
debug: render template web/antiepidemic/updateAntiepidemic.md 
debug: use file parser markdown for web/antiepidemic/updateAntiepidemic.md 
debug: call hook page 
debug: index page web/antiepidemic/updateAntiepidemic.md 
debug: write parsed file web/antiepidemic/updateAntiepidemic.md to web/antiepidemic/updateAntiepidemic.html 
debug: processing web/enrolstudents/delete.md 87% 
debug: start parsing file web/enrolstudents/delete.md 
debug: render template web/enrolstudents/delete.md 
debug: use file parser markdown for web/enrolstudents/delete.md 
debug: call hook page 
debug: index page web/enrolstudents/delete.md 
debug: write parsed file web/enrolstudents/delete.md to web/enrolstudents/delete.html 
debug: processing web/enrolstudents/enrolstudents.md 88% 
debug: start parsing file web/enrolstudents/enrolstudents.md 
debug: render template web/enrolstudents/enrolstudents.md 
debug: use file parser markdown for web/enrolstudents/enrolstudents.md 
debug: call hook page 
debug: index page web/enrolstudents/enrolstudents.md 
debug: write parsed file web/enrolstudents/enrolstudents.md to web/enrolstudents/enrolstudents.html 
debug: processing web/enrolstudents/findProvinceAndCity.md 88% 
debug: start parsing file web/enrolstudents/findProvinceAndCity.md 
debug: render template web/enrolstudents/findProvinceAndCity.md 
debug: use file parser markdown for web/enrolstudents/findProvinceAndCity.md 
debug: call hook page 
debug: index page web/enrolstudents/findProvinceAndCity.md 
debug: write parsed file web/enrolstudents/findProvinceAndCity.md to web/enrolstudents/findProvinceAndCity.html 
debug: processing web/enrolstudents/list.md 88% 
debug: start parsing file web/enrolstudents/list.md 
debug: render template web/enrolstudents/list.md 
debug: use file parser markdown for web/enrolstudents/list.md 
debug: call hook page 
debug: index page web/enrolstudents/list.md 
debug: write parsed file web/enrolstudents/list.md to web/enrolstudents/list.html 
debug: processing web/enrolstudents/save.md 88% 
debug: start parsing file web/enrolstudents/save.md 
debug: render template web/enrolstudents/save.md 
debug: use file parser markdown for web/enrolstudents/save.md 
debug: call hook page 
debug: index page web/enrolstudents/save.md 
debug: write parsed file web/enrolstudents/save.md to web/enrolstudents/save.html 
debug: processing web/enrolstudents/update.md 89% 
debug: start parsing file web/enrolstudents/update.md 
debug: render template web/enrolstudents/update.md 
debug: use file parser markdown for web/enrolstudents/update.md 
debug: call hook page 
debug: index page web/enrolstudents/update.md 
debug: write parsed file web/enrolstudents/update.md to web/enrolstudents/update.html 
debug: processing web/group/addschoolwork.md 89% 
debug: start parsing file web/group/addschoolwork.md 
debug: render template web/group/addschoolwork.md 
debug: use file parser markdown for web/group/addschoolwork.md 
debug: call hook page 
debug: index page web/group/addschoolwork.md 
debug: write parsed file web/group/addschoolwork.md to web/group/addschoolwork.html 
debug: processing web/group/group.md 89% 
debug: start parsing file web/group/group.md 
debug: render template web/group/group.md 
debug: use file parser markdown for web/group/group.md 
debug: call hook page 
debug: index page web/group/group.md 
debug: write parsed file web/group/group.md to web/group/group.html 
debug: processing web/group/schoollist.md 89% 
debug: start parsing file web/group/schoollist.md 
debug: render template web/group/schoollist.md 
debug: use file parser markdown for web/group/schoollist.md 
debug: call hook page 
debug: index page web/group/schoollist.md 
debug: write parsed file web/group/schoollist.md to web/group/schoollist.html 
debug: processing web/schoolintroduce/detail.md 90% 
debug: start parsing file web/schoolintroduce/detail.md 
debug: render template web/schoolintroduce/detail.md 
debug: use file parser markdown for web/schoolintroduce/detail.md 
debug: call hook page 
debug: index page web/schoolintroduce/detail.md 
debug: write parsed file web/schoolintroduce/detail.md to web/schoolintroduce/detail.html 
debug: processing web/schoolintroduce/save.md 90% 
debug: start parsing file web/schoolintroduce/save.md 
debug: render template web/schoolintroduce/save.md 
debug: use file parser markdown for web/schoolintroduce/save.md 
debug: call hook page 
debug: index page web/schoolintroduce/save.md 
debug: write parsed file web/schoolintroduce/save.md to web/schoolintroduce/save.html 
debug: processing web/schoolintroduce/schoolintroduce.md 90% 
debug: start parsing file web/schoolintroduce/schoolintroduce.md 
debug: render template web/schoolintroduce/schoolintroduce.md 
debug: use file parser markdown for web/schoolintroduce/schoolintroduce.md 
debug: call hook page 
debug: index page web/schoolintroduce/schoolintroduce.md 
debug: write parsed file web/schoolintroduce/schoolintroduce.md to web/schoolintroduce/schoolintroduce.html 
debug: processing web/schoolintroduce/update.md 90% 
debug: start parsing file web/schoolintroduce/update.md 
debug: render template web/schoolintroduce/update.md 
debug: use file parser markdown for web/schoolintroduce/update.md 
debug: call hook page 
debug: index page web/schoolintroduce/update.md 
debug: write parsed file web/schoolintroduce/update.md to web/schoolintroduce/update.html 
debug: processing web/securityevent/delete.md 91% 
debug: start parsing file web/securityevent/delete.md 
debug: render template web/securityevent/delete.md 
debug: use file parser markdown for web/securityevent/delete.md 
debug: call hook page 
debug: index page web/securityevent/delete.md 
debug: write parsed file web/securityevent/delete.md to web/securityevent/delete.html 
debug: processing web/securityevent/detail.md 91% 
debug: start parsing file web/securityevent/detail.md 
debug: render template web/securityevent/detail.md 
debug: use file parser markdown for web/securityevent/detail.md 
debug: call hook page 
debug: index page web/securityevent/detail.md 
debug: write parsed file web/securityevent/detail.md to web/securityevent/detail.html 
debug: processing web/securityevent/list.md 91% 
debug: start parsing file web/securityevent/list.md 
debug: render template web/securityevent/list.md 
debug: use file parser markdown for web/securityevent/list.md 
debug: call hook page 
debug: index page web/securityevent/list.md 
debug: write parsed file web/securityevent/list.md to web/securityevent/list.html 
debug: processing web/securityevent/save.md 91% 
debug: start parsing file web/securityevent/save.md 
debug: render template web/securityevent/save.md 
debug: use file parser markdown for web/securityevent/save.md 
debug: call hook page 
debug: index page web/securityevent/save.md 
debug: write parsed file web/securityevent/save.md to web/securityevent/save.html 
debug: processing web/securityevent/securityevent.md 92% 
debug: start parsing file web/securityevent/securityevent.md 
debug: render template web/securityevent/securityevent.md 
debug: use file parser markdown for web/securityevent/securityevent.md 
debug: call hook page 
debug: index page web/securityevent/securityevent.md 
debug: write parsed file web/securityevent/securityevent.md to web/securityevent/securityevent.html 
debug: processing web/securityevent/update.md 92% 
debug: start parsing file web/securityevent/update.md 
debug: render template web/securityevent/update.md 
debug: use file parser markdown for web/securityevent/update.md 
debug: call hook page 
debug: index page web/securityevent/update.md 
debug: write parsed file web/securityevent/update.md to web/securityevent/update.html 
debug: processing web/statistics/activity/albumList.md 92% 
debug: start parsing file web/statistics/activity/albumList.md 
debug: render template web/statistics/activity/albumList.md 
debug: use file parser markdown for web/statistics/activity/albumList.md 
debug: call hook page 
debug: index page web/statistics/activity/albumList.md 
debug: write parsed file web/statistics/activity/albumList.md to web/statistics/activity/albumList.html 
debug: processing web/statistics/activity/momentCount.md 92% 
debug: start parsing file web/statistics/activity/momentCount.md 
debug: render template web/statistics/activity/momentCount.md 
debug: use file parser markdown for web/statistics/activity/momentCount.md 
debug: call hook page 
debug: index page web/statistics/activity/momentCount.md 
debug: write parsed file web/statistics/activity/momentCount.md to web/statistics/activity/momentCount.html 
debug: processing web/statistics/activity/momentList.md 93% 
debug: start parsing file web/statistics/activity/momentList.md 
debug: render template web/statistics/activity/momentList.md 
debug: use file parser markdown for web/statistics/activity/momentList.md 
debug: call hook page 
debug: index page web/statistics/activity/momentList.md 
debug: write parsed file web/statistics/activity/momentList.md to web/statistics/activity/momentList.html 
debug: processing web/statistics/activity/thumbupsList.md 93% 
debug: start parsing file web/statistics/activity/thumbupsList.md 
debug: render template web/statistics/activity/thumbupsList.md 
debug: use file parser markdown for web/statistics/activity/thumbupsList.md 
debug: call hook page 
debug: index page web/statistics/activity/thumbupsList.md 
debug: write parsed file web/statistics/activity/thumbupsList.md to web/statistics/activity/thumbupsList.html 
debug: processing web/statistics/attendance/getAbsencesList.md 93% 
debug: start parsing file web/statistics/attendance/getAbsencesList.md 
debug: render template web/statistics/attendance/getAbsencesList.md 
debug: use file parser markdown for web/statistics/attendance/getAbsencesList.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAbsencesList.md 
debug: write parsed file web/statistics/attendance/getAbsencesList.md to web/statistics/attendance/getAbsencesList.html 
debug: processing web/statistics/attendance/getAtteDetail.md 93% 
debug: start parsing file web/statistics/attendance/getAtteDetail.md 
debug: render template web/statistics/attendance/getAtteDetail.md 
debug: use file parser markdown for web/statistics/attendance/getAtteDetail.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAtteDetail.md 
debug: write parsed file web/statistics/attendance/getAtteDetail.md to web/statistics/attendance/getAtteDetail.html 
debug: processing web/statistics/attendance/getAtteList.md 94% 
debug: start parsing file web/statistics/attendance/getAtteList.md 
debug: render template web/statistics/attendance/getAtteList.md 
debug: use file parser markdown for web/statistics/attendance/getAtteList.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAtteList.md 
debug: write parsed file web/statistics/attendance/getAtteList.md to web/statistics/attendance/getAtteList.html 
debug: processing web/statistics/attendance/getAttendanceData.md 94% 
debug: start parsing file web/statistics/attendance/getAttendanceData.md 
debug: render template web/statistics/attendance/getAttendanceData.md 
debug: use file parser markdown for web/statistics/attendance/getAttendanceData.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAttendanceData.md 
debug: write parsed file web/statistics/attendance/getAttendanceData.md to web/statistics/attendance/getAttendanceData.html 
debug: processing web/statistics/attendance/getAttendanceDataForClass.md 94% 
debug: start parsing file web/statistics/attendance/getAttendanceDataForClass.md 
debug: render template web/statistics/attendance/getAttendanceDataForClass.md 
debug: use file parser markdown for web/statistics/attendance/getAttendanceDataForClass.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAttendanceDataForClass.md 
debug: write parsed file web/statistics/attendance/getAttendanceDataForClass.md to web/statistics/attendance/getAttendanceDataForClass.html 
debug: processing web/statistics/attendance/getAttendanceList.md 94% 
debug: start parsing file web/statistics/attendance/getAttendanceList.md 
debug: render template web/statistics/attendance/getAttendanceList.md 
debug: use file parser markdown for web/statistics/attendance/getAttendanceList.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAttendanceList.md 
debug: write parsed file web/statistics/attendance/getAttendanceList.md to web/statistics/attendance/getAttendanceList.html 
debug: processing web/statistics/attendance/getAttendanceRate.md 95% 
debug: start parsing file web/statistics/attendance/getAttendanceRate.md 
debug: render template web/statistics/attendance/getAttendanceRate.md 
debug: use file parser markdown for web/statistics/attendance/getAttendanceRate.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAttendanceRate.md 
debug: write parsed file web/statistics/attendance/getAttendanceRate.md to web/statistics/attendance/getAttendanceRate.html 
debug: processing web/statistics/attendance/getAttendanceStatistics.md 95% 
debug: start parsing file web/statistics/attendance/getAttendanceStatistics.md 
debug: render template web/statistics/attendance/getAttendanceStatistics.md 
debug: use file parser markdown for web/statistics/attendance/getAttendanceStatistics.md 
debug: call hook page 
debug: index page web/statistics/attendance/getAttendanceStatistics.md 
debug: write parsed file web/statistics/attendance/getAttendanceStatistics.md to web/statistics/attendance/getAttendanceStatistics.html 
debug: processing web/statistics/attendance.md 95% 
debug: start parsing file web/statistics/attendance.md 
debug: render template web/statistics/attendance.md 
debug: use file parser markdown for web/statistics/attendance.md 
debug: call hook page 
debug: index page web/statistics/attendance.md 
debug: write parsed file web/statistics/attendance.md to web/statistics/attendance.html 
debug: processing web/statistics/attendanceList.md 95% 
debug: start parsing file web/statistics/attendanceList.md 
debug: render template web/statistics/attendanceList.md 
debug: use file parser markdown for web/statistics/attendanceList.md 
debug: call hook page 
debug: index page web/statistics/attendanceList.md 
debug: write parsed file web/statistics/attendanceList.md to web/statistics/attendanceList.html 
debug: processing web/statistics/activity.md 96% 
debug: start parsing file web/statistics/activity.md 
debug: render template web/statistics/activity.md 
debug: use file parser markdown for web/statistics/activity.md 
debug: call hook page 
debug: index page web/statistics/activity.md 
debug: write parsed file web/statistics/activity.md to web/statistics/activity.html 
debug: processing web/statistics/statistics.md 96% 
debug: start parsing file web/statistics/statistics.md 
debug: render template web/statistics/statistics.md 
debug: use file parser markdown for web/statistics/statistics.md 
debug: call hook page 
debug: index page web/statistics/statistics.md 
debug: write parsed file web/statistics/statistics.md to web/statistics/statistics.html 
debug: processing web/statistics/teacher_attendance/attendance.md 96% 
debug: start parsing file web/statistics/teacher_attendance/attendance.md 
debug: render template web/statistics/teacher_attendance/attendance.md 
debug: use file parser markdown for web/statistics/teacher_attendance/attendance.md 
debug: call hook page 
debug: index page web/statistics/teacher_attendance/attendance.md 
debug: write parsed file web/statistics/teacher_attendance/attendance.md to web/statistics/teacher_attendance/attendance.html 
debug: processing web/statistics/teacher_attendance/getTeacherAtteDetail.md 96% 
debug: start parsing file web/statistics/teacher_attendance/getTeacherAtteDetail.md 
debug: render template web/statistics/teacher_attendance/getTeacherAtteDetail.md 
debug: use file parser markdown for web/statistics/teacher_attendance/getTeacherAtteDetail.md 
debug: call hook page 
debug: index page web/statistics/teacher_attendance/getTeacherAtteDetail.md 
debug: write parsed file web/statistics/teacher_attendance/getTeacherAtteDetail.md to web/statistics/teacher_attendance/getTeacherAtteDetail.html 
debug: processing web/statistics/teacher_attendance/getTeacherAtteList.md 97% 
debug: start parsing file web/statistics/teacher_attendance/getTeacherAtteList.md 
debug: render template web/statistics/teacher_attendance/getTeacherAtteList.md 
debug: use file parser markdown for web/statistics/teacher_attendance/getTeacherAtteList.md 
debug: call hook page 
debug: index page web/statistics/teacher_attendance/getTeacherAtteList.md 
debug: write parsed file web/statistics/teacher_attendance/getTeacherAtteList.md to web/statistics/teacher_attendance/getTeacherAtteList.html 
debug: processing web/yunpan/filelist.md 97% 
debug: start parsing file web/yunpan/filelist.md 
debug: render template web/yunpan/filelist.md 
debug: use file parser markdown for web/yunpan/filelist.md 
debug: call hook page 
debug: index page web/yunpan/filelist.md 
debug: write parsed file web/yunpan/filelist.md to web/yunpan/filelist.html 
debug: processing web/yunpan/countfile.md 97% 
debug: start parsing file web/yunpan/countfile.md 
debug: render template web/yunpan/countfile.md 
debug: use file parser markdown for web/yunpan/countfile.md 
debug: call hook page 
debug: index page web/yunpan/countfile.md 
debug: write parsed file web/yunpan/countfile.md to web/yunpan/countfile.html 
debug: processing web/yunpan/creatfolder.md 97% 
debug: start parsing file web/yunpan/creatfolder.md 
debug: render template web/yunpan/creatfolder.md 
debug: use file parser markdown for web/yunpan/creatfolder.md 
debug: call hook page 
debug: index page web/yunpan/creatfolder.md 
debug: write parsed file web/yunpan/creatfolder.md to web/yunpan/creatfolder.html 
debug: processing web/yunpan/deletefile.md 98% 
debug: start parsing file web/yunpan/deletefile.md 
debug: render template web/yunpan/deletefile.md 
debug: use file parser markdown for web/yunpan/deletefile.md 
debug: call hook page 
debug: index page web/yunpan/deletefile.md 
debug: write parsed file web/yunpan/deletefile.md to web/yunpan/deletefile.html 
debug: processing web/yunpan/deletefolder.md 98% 
debug: start parsing file web/yunpan/deletefolder.md 
debug: render template web/yunpan/deletefolder.md 
debug: use file parser markdown for web/yunpan/deletefolder.md 
debug: call hook page 
debug: index page web/yunpan/deletefolder.md 
debug: write parsed file web/yunpan/deletefolder.md to web/yunpan/deletefolder.html 
debug: processing web/yunpan/creatfile.md 98% 
debug: start parsing file web/yunpan/creatfile.md 
debug: render template web/yunpan/creatfile.md 
debug: use file parser markdown for web/yunpan/creatfile.md 
debug: call hook page 
debug: index page web/yunpan/creatfile.md 
debug: write parsed file web/yunpan/creatfile.md to web/yunpan/creatfile.html 
debug: processing web/yunpan/folderlist.md 98% 
debug: start parsing file web/yunpan/folderlist.md 
debug: render template web/yunpan/folderlist.md 
debug: use file parser markdown for web/yunpan/folderlist.md 
debug: call hook page 
debug: index page web/yunpan/folderlist.md 
debug: write parsed file web/yunpan/folderlist.md to web/yunpan/folderlist.html 
debug: processing web/yunpan/query.md 99% 
debug: start parsing file web/yunpan/query.md 
debug: render template web/yunpan/query.md 
debug: use file parser markdown for web/yunpan/query.md 
debug: call hook page 
debug: index page web/yunpan/query.md 
debug: write parsed file web/yunpan/query.md to web/yunpan/query.html 
debug: processing web/yunpan/revisefile.md 99% 
debug: start parsing file web/yunpan/revisefile.md 
debug: render template web/yunpan/revisefile.md 
debug: use file parser markdown for web/yunpan/revisefile.md 
debug: call hook page 
debug: index page web/yunpan/revisefile.md 
debug: write parsed file web/yunpan/revisefile.md to web/yunpan/revisefile.html 
debug: processing web/yunpan/revisefolder.md 99% 
debug: start parsing file web/yunpan/revisefolder.md 
debug: render template web/yunpan/revisefolder.md 
debug: use file parser markdown for web/yunpan/revisefolder.md 
debug: call hook page 
debug: index page web/yunpan/revisefolder.md 
debug: write parsed file web/yunpan/revisefolder.md to web/yunpan/revisefolder.html 
debug: processing web/yunpan/yunpan.md 99% 
debug: start parsing file web/yunpan/yunpan.md 
debug: render template web/yunpan/yunpan.md 
debug: use file parser markdown for web/yunpan/yunpan.md 
debug: call hook page 
debug: index page web/yunpan/yunpan.md 
debug: write parsed file web/yunpan/yunpan.md to web/yunpan/yunpan.html 
debug: processing web.md 100% 
debug: start parsing file web.md 
debug: render template web.md 
debug: use file parser markdown for web.md 
debug: call hook page 
debug: index page web.md 
debug: write parsed file web.md to web.html 
debug: call hook finish 
debug: write search index 

RangeError: Maximum call stack size exceeded

Thanks for your help .

**Comment by nagim** [comment]
Thanks!
Could you please try to put this into the `pluginsConfig` section in `book.json` and try the build again?

```json
"lunr": {
             "maxIndexSize": 1000000000
         }
```
