### ISSUE TITLE
Relative links broken over HTTPs

### ISSUE THREAD

**Issue by hhkaos** [GitbookIO/gitbook#1684]
As you can see in [this book](https://hhkaos.github.io/awesome-arcgis//front-end/technologies/), if you click over **Angular** relative link it does nothing.

If you open the console you will see this error:

> Mixed Content: The page at 'https://hhkaos.github.io/awesome-arcgis/front-end/technologies/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://hhkaos.github.io/awesome-arcgis/front-end/technologies/angular/'. This request has been blocked; the content must be served over HTTPS.

![2017-01-21_1137](https://cloud.githubusercontent.com/assets/826965/22173829/5a2b8324-dfce-11e6-83d8-513c3f411233.png)

[This is the original markdown file](https://raw.githubusercontent.com/hhkaos/awesome-arcgis/master/front-end/technologies/README.md).

I'm using:
> **GitBook version**: 3.2.2
**OS X Yosemite** (10.10.5)
**Tested in**: Chrome 55.0.2883.95 (64-bit), Firefox (50.0) & Safari (10.0.2)

Thanks in advance.

**Comment by hhkaos** [comment]
I found out that it wasn't working because I wasn't linking to the **README.md**, doing so it works. Is this the expected behaviour?

Thanks

**Comment by justin808** [comment]
I'm having the same issue:

I have been trying to do this with https://github.com/shakacode/react_on_rails, and the created links point to a markdown file and the gitbook site renders the file as raw text.

Please see the following:

* https://github.com/shakacode/react_on_rails  - github source
* Search for "Code Splitting" which points to https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/code-splitting.md

* Now try on the gitbook https://shakacode.gitbooks.io/react-on-rails/content/
* Search for "Code Splitting" which points to: https://shakacode.gitbooks.io/react-on-rails/content/docs/additional-reading/code-splitting.md

The gitbook case is suboptimal compared to just using github.com.

**Comment by hhkaos** [comment]
@justin808 in your case the application also display an error when clicking the link:

![2017-02-21_1741](https://cloud.githubusercontent.com/assets/826965/23174584/24c55e10-f85d-11e6-886c-c9e2bb39e514.png)

Did you checked that?

**Comment by justin808** [comment]
@hhkaos The problem is that I'm linking to Markdown, which works perfectly on the plain github site!
