### ISSUE TITLE
PDF doesn't generate GLOSSARY

### ISSUE THREAD

**Issue by hashborgir** [GitbookIO/gitbook#1685]
HTML output contains highlighted terms, link to the GLOSSARY page w/ the term. In PDF, there is no highlighting, no linking, and no glossary page rendered/generated. 

CLI version: 2.3.0
GitBook version: 3.2.2

https://gitlab.com/hashborgir/PDF-Compiled-Books/raw/master/DMT-Navigating-The-Other-Side-By-Hash-Borgir.pdf

**Comment by metcalfc** [comment]
Hit this as well in 3.2.2.
