### ISSUE TITLE
Could you fix the lag problem? What's wrong with the new gitbook version?

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1686]
Why the old gitbook works fine,but new one so lag?

### What is the current behavior?

when content is too big,it will cause lag when typing.

### What is the expected behavior?

no lag.

**Comment by cesards** [comment]
What is the state of this issue? It's still happening on the new editor.

**Comment by EasonWang01** [comment]
How can I enter to the new version of Gitbook and edit my old book after going to https://www.gitbook.com? I only saw the  legacy.gitbook.com link on the top.

**Comment by EasonWang01** [comment]
I have a billing plan in the old Gitbook but not saw my active bill plan in the new version. Is it not connected?
