### ISSUE TITLE
Gitbook Editor switches back to "Master" branch after 2 seconds

### ISSUE THREAD

**Issue by yaroslavvb** [GitbookIO/gitbook#1701]
After I select Branch to origin/new, it will let me edit it for a few seconds, then it automatically switches back to Master branch. Edits made during those few seconds seem lost. Here's the screenshot of selection widget I was using.

<img width="341" alt="screenshot 2017-02-05 18 33 45" src="https://cloud.githubusercontent.com/assets/23068/22632858/add56c7e-ebd1-11e6-85a4-d80cba614748.png">

macos: 10.12.2
gitbook editor: 6.6.2
book: https://www.gitbook.com/book/yaroslavvb/imperative/details

I'm giving this issue a shot, although from the github issues list it seems there's isn't maintainance going on

**Comment by yuchuanxi** [comment]
i have the same bug
