### ISSUE TITLE
does not generate anchor tag for git-ignored .md file

### ISSUE THREAD

**Issue by mateodelnorte** [GitbookIO/gitbook#1702]
Hi there. I'm generating a book where at least one of the .md files is git ignored from my repository. 

For some reason, the cli doesn't generate an anchor tag for these files. 

```
<li class="chapter " data-level="1.2.1" data-path="plugins/loop-things/README.md">
                <span>
                    my file
        </span></li>
```
is generated instead of one like 
```
<li class="chapter active" data-level="1.1" data-path="./">
                <a href="./">
                    Introduction
                </a>
        </li>
```
<img width="175" alt="screen shot 2017-02-06 at 12 09 55 pm" src="https://cloud.githubusercontent.com/assets/554847/22657757/9481d43a-ec65-11e6-80e2-70bda54ea221.png">

Am I doing something wrong or is this not supported?

**Comment by mateodelnorte** [comment]
I actually phrased this poorly. These files are in my repo, however they're also in .gitignore. 

So the links should easily be navigable. Not sure why anchor tags aren't being generated.

**Comment by mateodelnorte** [comment]
If I remove the .gitignore entry marking this file as ignored, gitbook correctly creates anchor tags. 

I'm creating a tool, similar to Lerna, that allows you to (instead of having a monorepo) have a metarepo which composes many other repos: https://github.com/mateodelnorte/meta. Similar to Lerna, meta will link all of your dependent code (if needed) and allow you to run commands against your fully project of projects. Having a meta repo instead of a monorepo ends up being a big benefit for systems (as opposed to libraries), where you want each individual service to have its own repo. 

I'm listing all this out to show I have a real use case for having .md files that are .gitignored to be included and correctly linked in the top level. In my case, I have a metarepo and I'd like child repositories' docs to be compiled into the top level tool's documentation.

**Comment by JennieJi** [comment]
+1  
I found this as well.   
I think this does not make sense at all since I want to generate some markdown from jsdoc and include them in gitbook. As those markdown files are generated, I do not want to include them in git at all.
