### ISSUE TITLE
GLOSSARY don't work with Chinese characters

### ISSUE THREAD

**Issue by yuchuanxi** [GitbookIO/gitbook#1703]
Hi, I'm trying the GLOSSARY.md . It works well. but it no work with chinese.

glossary.md:
```md
## Term
Definition for this term

## Another term
With it's definition, this can contain bold text
and all other kinds of inline markup ...

## 小土豆
小土豆是个很土很逗的逗比
```

article md:
```md
# Article 1

这是一个小土豆的故事

这是一个*小土豆*的故事

这是另一个Term的故事

这是另一个**Term**的故事

这是另一个~~Term~~的故事

这是另一个*Term*的故事

这是另一个`Term`的故事
```

thank you very much

**Comment by kogakure** [comment]
I can confirm, all non-ascii characters get ignored, e.g. the German word **Ära** or **Fuß**. In my case I have a term of **Fu** in my glossary and my word will be marked with boundaries inside the word, like this: _Fu_ß.

**Comment by indoorsNB** [comment]
same problem :(

**Comment by jfoboss** [comment]
same problem with Russian Language :(

**Comment by EternallLight** [comment]
For Russian Language, it is still not working in Gitbook 3.2.3.

**Comment by juhuan** [comment]
hope to resolve

**Comment by juhuan** [comment]
@yuchuanxi 我连英文都不能用诶，兄弟

**Comment by yuchuanxi** [comment]
@juhuan 我好久没用这个了。。可以尝试着自己fork debug改下代码

**Comment by kntmr** [comment]
same problem in the Japanese language in GitBook 3.2.3.
