### ISSUE TITLE
Cannot use next and previous buttons after clicking on link

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/gitbook#1708]
With a summary like so:

```md
* [Introduction](README.md)

* [page1](page1/README.md]
    *[subpage1](page1/subpage1/README.md)
```

When clicking a link to page1 from the introduction, you will end up at `mygitbook.com/page1` no matter if there's a closing slash or not. Since there is no trailing slash in the URI you end up at, clicking on the next button will actually not lead you to `mygitbook.com/page1/subpage1/` as expected. Instead, you will end up at `mygitbook.com/subpage1/` which is not a valid page. 

What I'm looking for is a solution where clicking links will lead me to `mygitbook.com/page1/` and not `mygitbook.com/page1`. Is there a simple fix for that?

Alternatively, would it be possible for GitBook to always add a  trailing backslash to internal links?

A live example is at https://docs.starcounter.io/ where clicking the link "tutorial"  and then clicking next will indeed not work.

**Note**: When building locally this is not a problem, only when it's hosted online

**Comment by warpech** [comment]
One solution is to provide absolute links:

```
* [Introduction](/README.md)

* [page1](/page1/README.md]
    *[subpage1](/page1/subpage1/README.md)
```

But such links will not work because the branch prefix at the beginning of the URL.

**Comment by warpech** [comment]
Another possible solution, use `<base>` HTML tag:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

All the relative URLs will be then resolved according to `<base href="https://docs.starcounter.io/">` or <base href="/v/Develop/"> as you wish.

The `base` tag must be inserted anywhere in the page, for example in the TOC or in the header.

**Comment by Mackiovello** [comment]
> All the relative URLs will be then resolved according to <base href="https://docs.starcounter.io/"> or as you wish.

Thank you for your suggestions! I didn't manage to make it work this way. Instead, I just added a script that appends a backslash to relative links with no trailing backslash.

**Comment by Mackiovello** [comment]
This issue is solved by [this](https://www.npmjs.com/package/gitbook-plugin-link-fixer) plugin. Just set the option `link` to your base URI, and the relative links will get their trailing backslashes back.

It's not fully optimized yet, although, it does work.

**Comment by AaronO** [comment]
@Mackiovello That's a bug, links in your `SUMMARY.md` should always be absolute (relative to the root of your project)

**Comment by Mackiovello** [comment]
> @Mackiovello That's a bug, links in your SUMMARY.md should always be absolute (relative to the root of your project)

The bug seems to be that trailing backslashes on relative links in the content are removed. For example, with a page containing an element like this `<a href="/my/relative/link/">link</a>`, the last backslash will be removed during build so that the element that is actually stamped looks like this: `<a href="/my/relative/link">link</a>`. I don't think it has to do with the SUMMARY.md.

**Comment by Mackiovello** [comment]
Further investigation:
When running locally, the server returns 301 and allows the redirection from `\guides` to `\guides\` to works. Remotely, it returns 302 and the redirect does not work.
![301](https://cloud.githubusercontent.com/assets/19392292/23210758/55203970-f8ff-11e6-8243-23c444cc659b.PNG)
![302](https://cloud.githubusercontent.com/assets/19392292/23210760/5693d2da-f8ff-11e6-95d8-2ec9179169ca.PNG)

@AaronO

**Comment by Mackiovello** [comment]
It doesn't seem to have to do with the templating engine since encapsulating in `{% raw %}` doesn't fix the problem. The HTML is also correct after parsing from Markdown. Tried this by using the following:

```js
module.exports = {
    hooks: {
        "page": function(page) {
            console.log(page.content);
        }
    }
};
```
The error has to come from something that is done after the parsing itself.

**Comment by Mackiovello** [comment]
Closing as no longer relevant
