### ISSUE TITLE
Http error 504; "" while publishing an update

### ISSUE THREAD

**Issue by velneo** [GitbookIO/gitbook#1709]
### What is the current behavior?

 When I try to publish changes in my book, it creates al the versions (epub, json, pdf...) except the website an the error is http: ERROR 504: ""

Just edit my book "manual de referencia de Velneo", change something and publish it.

### What is the expected behavior?

 I wish my book where published...

**Comment by chaoqing** [comment]
I got the same problem when I pushed to gitbook.com:

```
HTTP ERROR 504: ""                         ERROR OUTPUT
```

But it worked when I built in local:
```
root@e5483f6827ac:/mnt# gitbook build . /srv/html/
info: 9 plugins are installed 
info: 8 explicitly listed 
info: loading plugin "katex"... OK 
info: loading plugin "scripts"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 990 pages 
info: found 7 asset files 
info: >> generation finished with success in 4393.9s !
```

I think it might be because I added a lot of pages in single commit and your build system failed while waiting too long time.
