### ISSUE TITLE
Generate PDF file

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1710]
### What is the current behavior?

In the old gitbook version there is an PDF generate button,that can easily click it then download PDF file,but in NEW gitbook version that button disappeared.

Then I trying to using a npm module https://www.npmjs.com/package/gitbook-pdf  but there are dependency problem,what method is recommended to generate a PDF file?calibre?Thanks

**Comment by Soreine** [comment]
Hi @EasonWang01 

I suppose you are talking about the Download button on GitBook.com
You need to enable Ebooks in your book's options, then trigger a new build. After that, the Download button will be available again.

To generate PDF locally, see the documentation https://toolchain.gitbook.com/ebook.html

**Comment by EasonWang01** [comment]
thanks!
