### ISSUE TITLE
Random error when running gitbook build and serve commands

### ISSUE THREAD

**Issue by kingvagabond** [GitbookIO/gitbook#1719]
### What is the current behavior?
OS: MS Windows 7
Node version: v6.9.5
gitbook version 3.2.2 - always run gitbook update command

Issue: when run gitbook build command, or gitbook serve command, it reports error like:

Error: ENOENT: no such file or directory, stat '[my_gitbook_project_folder]\_book\gitbook\gitbook-plugin-lunr\lunr.min.js'

or 
Error: ENOENT: no such file or directory, stat '[my_gitbook_project_folder]\_book\gitbook\gitbook-plugin-highlight\ebook.css'

It can show different file error each time. That's interesting.

No URL for the book yet.

### What is the expected behavior?

Expect behavior: It worked fine until today. The gitbook can be compiled and hosted.

**Comment by kingvagabond** [comment]
This issue looks quite random. Today I tried again, gitbook build command works fine now, but gitbook serve still gets the same issue.

**Comment by kingvagabond** [comment]
Even if I delete _book folder, run gitbook init and then gitbook build, it still complains that css or js file in _book folder does not exist. I don't understand it.

**Comment by boldfacedesign** [comment]
I upped my node version to 7.2.0 and this bug has gone away. Look like there's some work to fix this on older node versions needed.
