### ISSUE TITLE
Cannot edit files online (only show "edit metadata" page)

### ISSUE THREAD

**Issue by xiaokeai666123** [GitbookIO/gitbook#1724]
### What is the current behavior?
Three days ago, it seemed that we I edit some previous files online. If I opened a file, then it showed the "edit metadata" page.

**Comment by SamyPesse** [comment]
What is the url of your book ?

**Comment by liuyang89116** [comment]
> https://liuyang89116.gitbooks.io/operating-system/content/

This is the url of my gitbook. I cannot now do further online editing of the existing files.
