### ISSUE TITLE
Gitbook terminates with very obscure EISDIR error when using GFM-style fragment references in your SUMMARY.md

### ISSUE THREAD

**Issue by GerHobbelt** [GitbookIO/gitbook#1730]
### What is the current behavior?

Add a fragment reference in your SUMMARY.md like so:

```
* [First Principles: Parsing Theory](#Theory)
```

and `gitbook build --log=debug --debug` fails with a `EISDIR` error, while the output provides **zero info** on what to do **nor any hint** where one might want to start looking: not even the slightest hint SUMMARY.md (or *any* MarkDown file in the collection at all!) is the culprit, in conjunction with gitbook *not* supporting github flavored MarkDown as advertised here: https://toolchain.gitbook.com/syntax/markdown.html#links (quoting: 

> "Links can point to relative paths, **anchors** or absolute urls." (\<-- emphasis mine)

Debug output of the run:

```
$ gitbook build --log=debug --debug
debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "C:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\jison\book-using-jison-beyond-the-basics\_book"
info: 7 plugins are installed
info: 6 explicitly listed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
error: error while parsing page ".":

Error: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)

$
```

#### Environment where this was observed:

```
Win64/10
NodeJS 6

$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
```

### What is the expected behavior?

Well, whatever you are willing to give me, but for starters: **not** an error report **while running in full debug drag (`--log=debug --debug`)** which is on the same information level as the dinosaur "syntax error" or "core dumped" failure messages of old. This is VERY unhelpful debug output.

Particularly in debug mode, I don't mind having to wade through several pages of debug output, which would provide me with way more opportunity to dig this up/out than the actual output produced by gitbook.

The current approach quite upsets me as you are driving me into a brick wall right off the bat, not allowing me any decent opportunity to perform some kind of error diagnosis. 

**I found out this is due to my `SUMMARY.md` and the lack of anchor reference support (see also #1551) in gitbook**, thanks to a lot of luck and maybe some google foo. This has cost me dearly in time and effort, not because of any kind of information overload (which I can filter using `grep` or whatever tools I happen to use) but because you ... give me *nothing* to work with!

The next phase for me was a hard and permanent process / choice:

- load gitbook, sprinkle `console.log / printf` debug trace lines all over your sources and pray I don't need all day to dig up which chunk of the code barfs up

- or kick gitbook to the curb and switch to another system that will at least attempt to be helpful to me when things don't work as expected (metalsmith + plugins was considered before). I chose to use gitbook because its documentation suggested it came closest to the feature set I need for this project, while the alternatives out there would have required (much?) more setup work.

> Thank you for giving us your feedback!
> -- The GitBook Team

You're welcome. I hope you seriously rethink your approach to debug output as the current behaviour of the tool does it a great *dis*service towards using it again or suggesting it to others: the error at hand is a very easy one to make (the bug is due to gitbook not supporting a link syntax which is advertised all over the net, e.g.: https://gist.github.com/asabaylus/3071099 and http://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown).  The *reported* error is so far off (and without **any** stack trace to help me dig through your code and get a hint via **RTFC**), it's only because google found me several predecessors over the years with the same symptoms and issue #1551 (**closed! and then re-opened only because of a side note!**) when I thought "WTF!?" and turned the `SUMMARY.md` into this:

```
* [First Principles: Parsing Theory](gitbook-is-buggered.md#Theory)
...
```

by editor's global find&replace (my actual SUMMARY.md has many links/references like this one as I'm used to github et al supporting it without a fuss), after which `gitbook build` **did complete**, or rather: did run for quite a bit longer, until it hit the next snag in my MD file(s) -- funny that next issue comes from code produced by the earlier `gitbook init`! (that file was originally generated as `methods.md` and then renamed and the demo code kept around for hints until I go and clean up):

```
$ gitbook build --log=debug --debug
debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "C:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\jison\book-using-jison-beyond-the-basics\_book"
info: 7 plugins are installed
info: 6 explicitly listed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 7 pages
info: found 1 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-theme-default\_assets\website
debug: copy resources from plugin C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-fontsettings\assets
debug: copy resources from plugin C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-sharing\assets
debug: copy resources from plugin C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-lunr\assets
debug: copy resources from plugin C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-search\assets
debug: copy resources from plugin C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-highlight\css
debug: copy asset ".gitignore"
debug: generate page "README.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page README.md
debug: generate page "Introduction.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page Introduction.md
debug: generate page "1_Goal.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page 1_Goal.md
debug: generate page "2_Basics.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page 2_Basics.md
debug: generate page "3_Diving_Into_JISON.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page 3_Diving_Into_JISON.md
debug: generate page "4_The_Real_Meat_Advanced_Topics.md"
debug: calling hook "page:before"
debug: calling hook "page"
debug: index page 4_The_Real_Meat_Advanced_Topics.md
debug: generate page "A_JISON_Specifics_Reference.md"
debug: calling hook "page:before"
error: error while generating page "A_JISON_Specifics_Reference.md":

Template render error: (C:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\jison\book-using-jison-beyond-the-basics\A_JISON_Specifics_Reference.md) [Line 327, Column 2]
  unknown block tag: method
Template render error: (C:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\jison\book-using-jison-beyond-the-basics\A_JISON_Specifics_Reference.md) [Line 327, Column 2]
  unknown block tag: method
    at Object.exports.prettifyError (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\nunjucks\src\environment.js:469:27)
    at Obj.extend.renderString (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\nunjucks\src\environment.js:327:21)
    at Promise.apply (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\q\q.js:1165:26)
    at Promise.promise.promiseDispatch (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\q\q.js:788:41)
    at C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\q\q.js:1391:14
    at runSingle (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\q\q.js:137:13)
    at flush (C:\Users\Ger\.gitbook\versions\3.2.2\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by naaando** [comment]
Also happens with me.

**Comment by yuriipolishchuk** [comment]
Have the same issue
