### ISSUE TITLE
Fail to download GitBook Editor for OS X all the time

### ISSUE THREAD

**Issue by CaliosD** [GitbookIO/gitbook#1731]
### What is the current behavior?

I'm so depressed to find it hard to download GitBook Editor from [here](https://www.gitbook.com/editor).
I've tried to download tons of times, from Chrome to Safari, from local network to VPN network, but nothing worked. Each time it fails at about 20/56.2M when downloading.

### What is the expected behavior?
 I wonder what can I do to download this file...... :(

Thanks in advance.

**Comment by zengyee** [comment]
neither for Linux version as well

**Comment by bandantonio** [comment]
@CaliosD @zengyee 

Ubuntu 17.04:
* Vivaldi 1.10.867.38 (Stable channel) (64-bit) - OK
  ![vivaldi](https://user-images.githubusercontent.com/16765690/29418794-0601e5e4-8376-11e7-900b-92f14ac17194.png)
* Chrome 60.0.3112.78 (Official Build) (64-bit) - OK
  ![chrome](https://user-images.githubusercontent.com/16765690/29418793-0600bbf6-8376-11e7-9711-43988d19cd78.png)
