### ISSUE TITLE
Book variable does not resolve as expected

### ISSUE THREAD

**Issue by moxiegirl** [GitbookIO/gitbook#1740]
### What is the current behavior?

I've defined a book variable.  I reference it in an .md file, the variable does not resolve.

```
{
    "gitbook": "3.x.x",
    "plugins": [ "page-toc", "otherlink", "expandable-chapters", "addcssjs"],
     "pluginsConfig": {
       "selector": ".markdown-section h2,.markdown-section h3"
          },
    "links": {
        "sidebar": {
				},
    "variables": {
            "releaseNumber": "0.17"
      }
		}
}
```

Reference:

{{ book.releaseNumber }}

### What is the expected behavior?

The variable should resolve to `0.17` in my generated html.

ENV:

$ gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by nagim** [comment]
This is solved, the problem was in the `book.json`.

**Comment by pietrop** [comment]
What was the problem?

**Comment by hamishwillee** [comment]
Just tested this and it works. Problem in my case was the [book variables documentation](https://toolchain.gitbook.com/templating/variables.html#book-variables) below which I copy-pasted into book.json:
```
{
  variables: {
    hello: "everyone"
  }
}
```
The thing is that json expects key-value everywhere. The following worked:
```
{
  "variables": {
    "hello": "everyone"
  }
}
```
