### ISSUE TITLE
Print layout for Crown Quarto size PDF?

### ISSUE THREAD

**Issue by annegentle** [GitbookIO/gitbook#1745]
### What is the current behavior?

Looking at PDF options in https://toolchain.gitbook.com/config.html I do not see an option for Crown Quarto layout (7.44 x 9.68 in).
CLI version: 2.3.0
GitBook version: 3.2.0

### What is the expected behavior?
I'd like to be able to add crownquarto as a PDF output option.

I'd be happy to work on this to add Crown Quarto. Is this part of Calibre or Gitbook?

**Comment by dusty** [comment]
I have a pull request in for custom sizes on the 3.2.2 version.  You could try that solution as a work around.

https://github.com/GitbookIO/gitbook/pull/1694

**Comment by annegentle** [comment]
Have a working method; closing Issue. Thanks @dusty.
