### ISSUE TITLE
Manual sync with GitHub doesn't work

### ISSUE THREAD

**Issue by wimpers** [GitbookIO/gitbook#1747]
I'm having issues with the sync between github and gitbook. Even the manual sync doesn't work for  https://github.com/openvstorage/volumedriver . I tried unlinking and linking the book back but no success. It keeps saying checking.

**Comment by steric85** [comment]
Same issue here!

**Comment by jayvdb** [comment]
I've used it a few times, and it works for me.
Maybe retest?

**Comment by wimpers** [comment]
Back in sync
