### ISSUE TITLE
Running some code when the page changes

### ISSUE THREAD

**Issue by estraschnov** [GitbookIO/gitbook#1750]
Hello,

I need to run some code each time the page content changes. How can I do this? Where is the best place to set this up?

Thanks

**Comment by bandantonio** [comment]
I suppose this may suit your needs. 
Each time you upgrade content, you need to re-build your gitbook docs. So, you can place your code before re-build operation in package.json:

```
{
  "name": "GitBook",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "docs:code": "<simple custom code>",
    "docs:prepare": "npm run docs:code && gitbook install && gitbook serve",
    "docs:build": "gitbook build"
  },
  "devDependencies": {
    "gitbook-styleguide": "^7.9.3"
  }
}
``` 
In such a case, you can type `npm run docs:prepare` and it will execute your custom code, install all dependencies and plugins (if necessary) and launch a preview for newly generated docs.

See example [here](https://medium.com/@gpbl/how-to-use-gitbook-to-publish-docs-for-your-open-source-npm-packages-465dd8d5bfba#c826)
