### ISSUE TITLE
gitbook install appears to do nothing

### ISSUE THREAD

**Issue by boldfacedesign** [GitbookIO/gitbook#1754]
### What is the current behavior?

I want to install a theme from https://plugins.gitbook.com/

I run `gitbook install theme-api` as the docs suggest

result: `info: nothing to install!`

### What is the expected behavior?

the theme is installed and can be used via `book.json`

**Comment by bandantonio** [comment]
It seems that you're trying to launch `gitbook install` incorrectly or from a wrong directory. 
Actually, there are two cases: when gitbook is installed in root directory or in a sub-directory. 

**First case:** 
```
~/gitbook
|- book.json
|- README.md
|- SUMMARY.md
```
book.json:
```
{
    "plugins": ["theme-api"]
}
```

In this case, you can simply launch `gitbook install`:
```
antonio@antonio:~/gitbook$ gitbook install
info: installing 1 plugins using npm@3.9.2 
info:  
info: installing plugin "theme-api" 
info: install plugin "theme-api" (*) from NPM with version 1.1.2 
~/gitbook
└─┬ gitbook-plugin-theme-api@1.1.2 
  ...
  ├── q@1.4.1 
  └── q-plus@0.0.8 

info: >> plugin "theme-api" installed with success
```

**Second case:** 
Here you can choose whether to leave `book.json` in root directory or put it inside a sub-directory

Root directory:
```
~/gitbook
|- book.json
|- docs
   |- README.md
   |- SUMMARY.md
```
book.json:
```
{
    "root": "./docs",
    "plugins": ["theme-api"]
}
```
After `gitbook install`:
```
antonio@antonio:~/gitbook$ gitbook install
info: installing 1 plugins using npm@3.9.2 
info:  
info: installing plugin "theme-api" 
info: install plugin "theme-api" (*) from NPM with version 1.1.2 
~/gitbook
└─┬ gitbook-plugin-theme-api@1.1.2 
  ...
  ├── q@1.4.1 
  └── q-plus@0.0.8 

info: >> plugin "theme-api" installed with success
```
```
~/gitbook
|- book.json
|- node_modules
|- docs
   |- README.md
   |- SUMMARY.md
```

Sub-directory:
```
~/gitbook
|- docs
   |- book.json
   |- README.md
   |- SUMMARY.md
```
book.json:
```
{
    "plugins": ["theme-api"]
}
```
Here you can use: 
* If you are in `~/gitbook` directory: `gitbook install docs`
* If you are in `~/gitbook/docs` directory: `gitbook install`.

After `gitbook install docs`:
```
gitbook install docs
info: installing 1 plugins using npm@3.9.2 
info:  
info: installing plugin "theme-api" 
info: install plugin "theme-api" (*) from NPM with version 1.1.2 
/home/antonio/test.git/gitbook/docs
└─┬ gitbook-plugin-theme-api@1.1.2 
...
  └── q-plus@0.0.8 

info: >> plugin "theme-api" installed with success 
```
```
~/gitbook
|- docs
   |- node_modules
   |- book.json
   |- README.md
   |- SUMMARY.md
```

If you launch `gitbook install` whereas all your files are located in `docs` sub-directory, you will receive `info: nothing to install!` notification.
