### ISSUE TITLE
sharing markdown content between books

### ISSUE THREAD

**Issue by insanum** [GitbookIO/gitbook#1755]
If I use an `include` pointing to a file outside the book's root I get a file out of scope error:

```
{% include "../../foo/bar.md" %}
```

This error is thrown by the `isInRoot()` check here:
https://github.com/GitbookIO/gitbook/blob/master/packages/gitbook/src/utils/path.js#L10

My books are local so I simply modified this function to always return true. Not the best solution but OK for now.

For those of you that share content between books, what is the best practice? I going to assume the quick answer will be run a preprocessor script that copies the needed files under the book dir. I'd like to avoid that as all of this is managed under git and I need to keep the barrier of entry as low as possible for the users of my repo.

**Comment by AaronO** [comment]
@insanum The `include` directive supports git urls (will pull in files from the repo as needed)

Sharing content inside a project or across multiple projects is definitely a common need we see quite frequently, it's all possible on a technical level with the `include` directive, but I don't think it's simple nor intuitive at a UX / product level.
