### ISSUE TITLE
Why macOS will crash when typing but not windows?

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1758]
MacBook pro: 3.1Ghz  16GB

Windows:  2.8Ghz 4GB

### What is the current behavior?

After search I found that many software both web and desktop will crash on Mac version but windows works fine.

In Gitbook,large content will lags in both windows and MacOS,but MacOS will also crash when typing but for less RAM of windows will not.

### In conclusion

Is this problem cause by memory leak for Mac system?

I have saw some issue reply from both Apple and Chrome,but they 
pass the buck to each other.

**Comment by etiennedesign** [comment]
Could it be related to this issue?
https://github.com/GitbookIO/gitbook/issues/1670

**Comment by EasonWang01** [comment]
Both might relative to memory leak when typing,but this case is when editing article.

**Comment by etiennedesign** [comment]
Oups sorry, i misread, i thought your issue was about typing in the Search bar.
