### ISSUE TITLE
Alert plugin proposal

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#176]
Hi! I'm starting to use Gitbook, it's a great piece of software.

Before Gitbook I used [Leanpub](https://leanpub.com/) to write a book from Markdown. Gitbook has almost everything I need and it's easier but I miss a feature.

In Leanpub I can do this:

``` markdown
W> ## This is a Warning
W>
W> Warnings are generated by using `W>` at the beginning of lines.
```

And it is rendered as an alert like this:

![screenshot from 2014-04-28 13 25 27](https://cloud.githubusercontent.com/assets/3072779/2816823/375ebb84-ced0-11e3-95d8-5766afa71d18.png)

My suggestion is about adding this feature to Gitbook. 

Personally I don't like to write that artificial markdown so I propose to write the alert in this way:

``` markdown
> **Warning**: write something
```

When Gitbook detect the string `> **Warning**` the paragraph will be rendered as a warning [Bootstrap alert](http://getbootstrap.com/components/#alerts) with a Font-Awesome icon. Same with notes, tips or urgen alert.

Multi-language problem? There should be an config.json option to change the keywords.

**Comment by erixtekila** [comment]
@orlade You'd propose a PR?. Thanks
