### ISSUE TITLE
Underscore in links wrapped into italic markdown tags breaks the link

### ISSUE THREAD

**Issue by pkuczynski** [GitbookIO/gitbook#1761]
### What is the current behavior?

The following code:

```
_This is my text: [link](http://www.mydomain.com/path/my_file_-abc-def.html)_
```

Is rendered in italic as: `This is my text: [link](http://www.mydomain.com/path/my_file-abc-def.html)_`

### What is the expected behavior?

Should be rendered as italic _This is my text: [link]()_.

### Env

* CLI version: 2.3.0
* GitBook version: 3.2.2
* macOS Sierra

**Comment by bandantonio** [comment]
Try asterisks instead of underscores:
```
*This is my text: [link](http://www.mydomain.com/path/my_file_-abc-def.html)*
```
in such a way, your link is rendered exactly as you expected:

*This is my text: [link](http://www.mydomain.com/path/my_file_-abc-def.html)*
