### ISSUE TITLE
met the error toooooooo.....

### ISSUE THREAD

**Issue by ryotlee** [GitbookIO/gitbook#1762]
###  can't reload....?

> Starting server ...
Serving book on http://localhost:4000
Restart after change in file README.md
Stopping server events.js:160   throw er; // Unhandled 'error' event

**Comment by Mackiovello** [comment]
Would it be possible to provide a more descriptive headline? If I understand it correctly, it's the issue where you try to make changes to the GitBook while the local server is running and it fails to restart? 

A better headline would be "Local server fails to restart after updating markdown document"
