### ISSUE TITLE
Help! I cannot find raw mode in Gitbook editor 7.0.12

### ISSUE THREAD

**Issue by greatdreams** [GitbookIO/gitbook#1763]
Dear friend:
    I am using gitbook editor 7.0.12 to edit my document in my macbook. I cannot find raw mode in the editor, is the function missing?

**Comment by nagim** [comment]
Look for the ? icon in the bottom right corner. Click on it and select **Edit Markdown**.

**Comment by SamyPesse** [comment]
We moved this feature to the bottom-right corner (under `?`). We'll probably rename this menu and make it more obvious.

**Comment by AaronO** [comment]
@greatdreams Can you share the scenarios where you need to switch to raw mode ? (That would be helpful feedback to see what we can improve on the default document mode)

**Comment by greatdreams** [comment]
@SamyPesse Thank you very much, as you say,  I've found it.

**Comment by greatdreams** [comment]
@AaronO I am leading a small software developing team with twenty developers. In our team, all guys are very familiar with markdown syntax and they love writing their technical or design  documents with raw markdown syntax while there's a preview in Gitbook editor. They want more control. As Gitbook editor-version 6.x toggle document mode or raw mode through the menu item `AA document mode ` right and top, we hope the latest edition of editor can provide similar user experience.

**Comment by AaronO** [comment]
@greatdreams Appreciate the feedback, can you elaborate on :
> They want more control

The document mode supports markdown shortcuts (titles, codeblocks, lists, ...).

If you could provide specific scenarios where `raw mode` provides "more control" over document mode that would be super helpful. Thanks

**Comment by greatdreams** [comment]
@AaronO In most cases, the document mode is enough like MS word. However, sometimes, our programmer find that there is a blank line or no indentation,  but it may be not so easy to fix it fast for them  in document mode.  In raw mode, they can fix it fast with looking for markdown syntax.  In addition, we can use latex syntax for math formula directly in raw mode.
