### ISSUE TITLE
generator,navigation,book property is deprecated

### ISSUE THREAD

**Issue by JackChan1999** [GitbookIO/gitbook#1767]
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "book" property is deprecated, use "this" directly instead 
warn: "options" property is deprecated, use config.get(key) instead

**Comment by yeasy** [comment]
+1

**Comment by LiJuejie** [comment]
+1

**Comment by yingshaoxo** [comment]
+1

**Comment by smslit** [comment]
+1

**Comment by fotock** [comment]
+1
