### ISSUE TITLE
Content reference to another GIT does not include images

### ISSUE THREAD

**Issue by jgerken** [GitbookIO/gitbook#1768]
I am trying to import a markdown file from another git repository into my GitBook using the content reference feature as described in the documentation

`{% include "git+https://github.com/GitbookIO/documentation.git/README.md#0.0.1" %}`

(my actual URL differs as the data is in a private repository) When I build the book, the text is imported but all images are missing. The code for the images in the imported markdown file is

`![Helpdesk Workflow](images/configuration/JIRA-workflow.png)`

The images folder is of course contained in the other git repository and relative to the markdown file.

For the first test, I created a GitBook using `gitbook init` and added the include into the generated README.md. I did not change anything else from the default settings. Did I miss a configuration which is required to make images work in content reference?

### Versions

| Program | Version |
| - | - |
| GitBook CLI | 2.3.0 |
| GitBook        | 3.2.2 |
| macOS Sierra | 10.12.4 |

The book is not publicly available.

### What is the current behavior?

Images are not imported from the other git repository.

### What is the expected behavior?

Images are imported from the other GIT repository, copied to the right location in the Gitbook directory structure and are shown in the Gitbook.

**Comment by deleyva** [comment]
It happens the same to me. I'm really interested in this thread.
