### ISSUE TITLE
Add web annotation support in documentation

### ISSUE THREAD

**Issue by kevchn** [GitbookIO/gitbook#1775]
### What is the current behavior?
No web annotations

### What is the expected behavior?
Similar to: https://jekyllrb.com/docs/extras/#web-highlights-and-commenting

**Comment by bandantonio** [comment]
Can't you use [Glossary](https://toolchain.gitbook.com/lexicon.html) for highlighting? And as far as I can see, commenting is available for GitHub-hosted projects.

**Comment by kevchn** [comment]
I think that Glossary allows annotations by publishers but not by readers for their own use-- I was more looking toward highlights/floating comments that readers could make
