### ISSUE TITLE
Gitbook doesn't work well with github markdown 

### ISSUE THREAD

**Issue by zhaoyi0113** [GitbookIO/gitbook#1777]
I have a github repository and I imported it into my gitbook repository. After doing this, I found that all links don't work at all. In my github I use below syntax creating a link
```
[Shards](shards/shards.md)  
```
But this doesn't work in gitbook. Is there a way to make gitbook compatible with github so I can import my repository directly from github and continue working from there. Otherwise I have to re-write the structures in gitbook.

**Comment by Mackiovello** [comment]
I'm certain that this actually works since I'm using it every single day. 

I'm suspecting that you've added the text as plain text, could that be the case? 

When adding files ending with `.md`, GitBook should properly parse it.

**Comment by zhaoyi0113** [comment]
You can take a look at this repo. https://github.com/zhaoyi0113/MongoDB-Training. You can click on the `Shards` link in GitHub and it will redirect to `shards.md` file correctly. But if you look at https://www.gitbook.com/book/zhaoyi0113/mongodb/details and click the `Shards` link, it will open shards.md as a plain text file on browser.

**Comment by nagim** [comment]
Because you need to include shards.md in the SUMMARY.md as well (https://toolchain.gitbook.com/pages.html), otherwise it won't get parsed.

**Comment by Mackiovello** [comment]
> Because you need to include shards.md in the SUMMARY.md as well (https://toolchain.gitbook.com/pages.html), otherwise it won't get parsed.

Why is this? Is there a way to circumvent it and parse pages that are not in the `SUMMARY.md` file? 

Relevant to https://github.com/GitbookIO/feedback/issues/467

**Comment by AaronO** [comment]
@Mackiovello Do you have examples of pages that would be relevant to link to but not relevant for the user to be able to access themselves via the Table of Contents ?

**Comment by Mackiovello** [comment]
> @Mackiovello Do you have examples of pages that would be relevant to link to but not relevant for the user to be able to access themselves via the Table of Contents ?

Yes. For example, we have a style guide page for the documentation. It wouldn't make sense to have it in the TOC but you want to have it in the gitbook so you can see the custom CSS in the book.

The most common case if is one page is outdated. You don't want to delete it since then the link to it gets broken, so you would instead want to remove it from the TOC and keep the link and a warning at the top of the page.

In general, they are pages that you want to have accessible in the book but not easily reachable from within the book.

**Comment by zhaoyi0113** [comment]
add a summary page works for me. Thanks.
