### ISSUE TITLE
Parse error in code block within list items

### ISSUE THREAD

**Issue by johnlinp** [GitbookIO/gitbook#1780]
CLI version: 2.3.0
GitBook version: 3.2.2

### What is the current behavior?

For the following markdown:

<pre>
1. example code 1
```
#include &lt;stdio.h&gt;
void foo();
```
2. example code 2
```
#include &lt;stdio.h&gt;

void foo();
```
</pre>

It shows:
https://johnlinp.gitbooks.io/gitbook-issue/

### What is the expected behavior?

I expect to see:
https://gist.github.com/johnlinp/2f2f692f7ac5fcc57d4208cea32eae48

**Comment by bandantonio** [comment]
Separate code blocks with additional lines:

~~~
1. example code 1

```
#include <stdio.h>
void foo();
```

2. example code 2

```
#include <stdio.h>

void foo();
```
~~~
Or even better: additional indentation for code blocks so they are treated as a part of ordered lists

~~~
1. example code 1

  ```
  #include <stdio.h>
  void foo();
  ```

2. example code 2

  ```
  #include <stdio.h>

  void foo();
  ```
~~~

Actually, separating elements one from another using additional spaces is one of the existing best practices for Markdown formatting.

**Comment by johnlinp** [comment]
Thanks for the explanation, I will close this issue.
