### ISSUE TITLE
How to configure anchor tag?

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/gitbook#1781]
I would like to be able to have a list of URLs on the top of the page, with each individual URL pointing to the sections within the same page. The idea is to have a FAQ page, with the list of questions easily accessible on top of the page.

I can make links with the pointers to the sections on top of the page, but the problem is that currently the anchor tag is auto-generated, and is basically concatenation of the section name separated by `-`. This results in very long anchor tags, which have to be manually updated if the section title is updated (and it can be quite long, since in my situation, section title will be an FAQ question verbatim).

Is there a way to assign an anchor tag for a section heading of text?

**Comment by bandantonio** [comment]
Try to use headings as follows:

```
# Hello {#id}
```

where `id` is your manually created anchor. 

For more examples you can check the main GitBook documentation, [Markdown chapter](https://github.com/GitbookIO/gitbook/blob/master/docs/syntax/markdown.md): all the sections within it are organized using "manual" anchors.

**Comment by fedorov** [comment]
Thank you @bandantonio, and sorry for not looking more diligently for the answer myself.

Also thanks to @nagim who pointed me to the page-toc plugin: https://plugins.gitbook.com/plugin/page-toc.
