### ISSUE TITLE
How to customize description for SEO?

### ISSUE THREAD

**Issue by kiwenlau** [GitbookIO/gitbook#1787]
As we all know, meta data **description** is very important for SEO. However, GitBook generated empty description. How can I customize it?

```html
 <meta name="description" content="">
``` 

I tried to create a template html file in **_layouts/website/page.html**

```html
{% block head %}
    <meta name="description" content="this is the description">
    {{ super() }}
{% endblock %}
```

it works, but the empty description still exists, so I get two description in the head:

```html
<meta name="description" content="">
<meta name="description" content="this is the description">
```

This is not good because the search engine may ignore the second description. Therefore, I only want to customize the first one. How can I accomplish that?

**Comment by Saturate** [comment]
This description is defined on each page with frontmatter:


page.md
```
---
description: This is a short description of my page
---

# This is my page
something in this page.

```

**Comment by kiwenlau** [comment]
@Saturate THX. It works. Looks like a good solution for me.

**Comment by DhavalKapil** [comment]
@Saturate what if I need to show the same description on each page? Is there any better technique than to write this at the start of every file? It seems that description is not read from `book.json`.

**Comment by promethe42** [comment]
+1 on @DhavalKapil 
Despite what [the doc](https://toolchain.gitbook.com/config.html) says, the `description` field is not read from `book.json`.
