### ISSUE TITLE
Cannot get content to appear before TOC in the SUMMARY.md file

### ISSUE THREAD

**Issue by GregTMobile** [GitbookIO/gitbook#1790]
I am trying to add a cover sheet to the TOC of a book I created with GitBook. Right now, the TOC is the first chapter appears in the PDF. in the Summary.md file.

I tried adding content at the start of the file, prior to the TOC items, but I am still getting the TOC first and not the content that I added before the TOC listing in the SUMMARY.md file

I am editing the book with the Atom editor on a Mac Book Pro running macOS Sierra, version 10.12.4

<img width="1440" alt="screen shot 2017-05-01 at 11 31 38 am" src="https://cloud.githubusercontent.com/assets/24709060/25584542/79b5ef88-2e64-11e7-98e6-e6760bbcb6f0.png">

**Comment by Mackiovello** [comment]
You'll have to do it in the `SUMMARY.html` file. Look here to see what we did to include a drop down before the TOC: https://github.com/Starcounter/Docs/blob/Develop/_layouts/website/summary.html

More info can be found in the [GitBook docs](https://toolchain.gitbook.com/templating/)
