### ISSUE TITLE
Anchors with special characters are broken

### ISSUE THREAD

**Issue by zandaqo** [GitbookIO/gitbook#1791]
Hi,

As of version 3.2.2, Gitbook doesn't handle special characters like `+` and `.` in anchors. We came upon this while trying to integrate jsdoc-to-markdown that generates such anchors and discussed it [here](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/125). While using special characters in ids isn't a popular thing, it is still technically allowed by the standards, so it would be nice to have them in Gitbook.

**Comment by JennieJi** [comment]
So disappointing that such a long time passed, no progress?

**Comment by peterflynn** [comment]
This means that Gitbook cannot correctly handle the output of tools like jsdoc2md -- see jsdoc2md/jsdoc-to-markdown#125.
