### ISSUE TITLE
Nested blocks truncate content

### ISSUE THREAD

**Issue by alexpearce** [GitbookIO/gitbook#1795]
### What is the current behavior?

Nested blocks cause the content to be truncated, only showing the content that comes before the first nested block.

Given this `README.md` in an otherwise standard GitBook (just `gitbook init`):

```markdown
# Introduction

{% markdown %}
Foo

{% markdown %}
Bar
{% endmarkdown %}

Baz
{% endmarkdown %}
```

Then after `gitbook build`, the HTML output is the following:

```html
<h1 id="introduction">Introduction</h1>
<p>
Foo
</p>
```

### What is the expected behavior?

The contents within  the nested block(s) should be rendered, along with the contents after. In the above example I would expect:

```
<h1 id="introduction">Introduction</h1>
<p>
Foo
</p>
<p>
Bar
</p>
<p>
Baz
</p>
```

---

A less silly use-case is using math inside a block:

```markdown
# Introduction

{% markdown %}
Foo

{% math %}
x = y
{% endmath %}

Baz
{% markdown %}
```

I found the problem when `markdown` was some custom block, from a plugin, but the behaviour is the same.

**Comment by prichmp** [comment]
I have the same issue. I've created a custom plugin (section, sectionheader, sectionbody) but it is not rendering any content within section. I'm trying to use the following:

```
{% section  %}
  {% sectionheader %}
  <h2>System Code</h2> <span class="required">Required</span> 
  {% endsectionheader %}
  {% sectionbody %}
  - **Description:** The system code
  - **Start:** 1 **End:** 1 **Length:** 1
  - **App Required:** REQUIRED
  - **Sub Required:** REQUIRED
  - **Reject Code:** 500
  - **Type:** ALPHANUMERIC
  {% endsectionbody %}
{% endsection %}
```

In addition the argument to the foldable-section blocks.process method is the following:

`{ name: null, body: '\n  ', args: [], kwargs: {}, blocks: [] }`
