### ISSUE TITLE
Navigation bar does not work in build

### ISSUE THREAD

**Issue by milen151** [GitbookIO/gitbook#1798]
### What is the current behavior?

When 

gitbook build 

The navigation on the left hand side does not work. (Even though the links seem fine.)

Version: CLI 2.3.0
GitBook: 3.2.2

OS: OpenSuse Leap 42.2 (but I originally heard from a user of Mac OS)

Any book will do.

### What is the expected behavior?

The pages should switch when the items of the navigation bar are clicked.

**Comment by natke** [comment]
Are you loading the page from files, or serving it via http?

I had the same problem when i was loading via files. If you have a look at the Web Developer console, you might see this error: 

XMLHttpRequest cannot load file:///xxx.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by milen151** [comment]
Dear natke,

Thank you! Yes, I was loading files. So, I will check how it goes via http. It will suit me perfectly of that works.

Best Regards,
Milen
