### ISSUE TITLE
Follow conventions to save cached versions appropriate location

### ISSUE THREAD

**Issue by Siilwyn** [GitbookIO/gitbook#1802]
No idea why you would cache versions 'globally' like this in the first place but...
Instead of placing the cached files in the home directory it should be placed in the [appropriate directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) per OS.

### What is the current behavior?
Saving everything in `~/.gitbook`.

### What is the expected behavior?
Saving everything in the appropriate directory per OS, e.g. for Linux: `~/.cache/gitbook`.

See same issues in other tools: [greenkeeper](https://github.com/greenkeeperio/rc/pull/3), [atom](https://github.com/atom/atom/issues/8281), [js-v8flags](https://github.com/js-cli/js-v8flags/issues/37), [electron-download](https://github.com/electron-userland/electron-download/issues/24).

**Comment by AaronO** [comment]
@Siilwyn It's more of a "content directory" than a "cache directory".

**Comment by Siilwyn** [comment]
It has different content per version?
Btw. I moved it to the CLI repository: https://github.com/GitbookIO/gitbook-cli/issues/62
