### ISSUE TITLE
What are the Windows PDF building instructions?

### ISSUE THREAD

**Issue by Lupus590** [GitbookIO/gitbook#1803]
### What is the current behaviour?
I've followed the instructions [provided](https://toolchain.gitbook.com/ebook.html) as best as I could (basically following commonalities between the OSX and Linux instructions, i.e. install calibre)  and currently get `Error: Error with command "svgexport"`

The svgexport that I downloaded via npm doesn't appear to work.

I also had to download and install ebook-convert, I think. I didn't keep good track.

All installs were done via npm.

### What is the expected behaviour?
Clear instructions on the link above which allows me to install, perhaps pointing to a different source for svgexport.

> P.S. My Grammarly plugin says that you guys have spelt behaviour wrong in your issue template, it might be a British/American English thing though.

**Comment by lupus590** [comment]
I might have worked this out, give me two minutes.

**Comment by c0001** [comment]
* I also appear the phonomenon you've got.

>And I also can't solve this problem.

**Comment by lupus590** [comment]
A thought I have just had, if users have Windows 10 then they can follow the Linux instructions on the Windows Subsystem For Linux thing. I would rather have a working Windows native method.

**Comment by lupus590** [comment]
I GOT IT WORKING!!!

* I installed GitBook via [Choco](https://chocolatey.org/) `choco install gitbook-cli`
* I installed calibre via Choco `choco install calibre` which added its install location to the path (according to the [official GitBook instructions](https://toolchain.gitbook.com/ebook.html) you only need `ebook-convert.exe` on the path)
* I installed this via NPM as instructed in the readme: https://github.com/shakiba/svgexport

I was about to post a variation of these steps onto the documentation (via a pull request) but noticed that the Linux instructions are now gone, I'm not going to do so now as I'm confused on that.
