### ISSUE TITLE
parse code block error, failed to compile, but other markdown parsers work well.

### ISSUE THREAD

**Issue by walker-zheng** [GitbookIO/gitbook#1807]
#### or maybe code block should not be parsed.
``` bash
$ gitbook -V # nodejs on windows 7, running on mingw64
CLI version: 2.3.0
GitBook version: 3.2.2
$ gitbook build
error: error while generating page "Format.md":
Template render error: (folly\folly\docs\Format.md) [Line 37, Column 25]
  unexpected token: }}
```
``` cpp
// To insert a literal '{' or '}', just double it.
std::cout << format("{} {{}} {{{}}}", 23, 42);
// => "23 {} {42}"
```

**Comment by bandantonio** [comment]
Stupid question, but have you tried to wrap up this code block in triple backticks ` ``` `?

**Comment by nagim** [comment]
Try to escape the {{ }} parts (as this overlaps with the templating engine syntax and it will try to parse it).
Wrap the code block like this:

    ```
    {% raw %}
    code comes here
    {% endraw %}
    ```

**Comment by walker-zheng** [comment]
@bandantonio it's  folly/docs, of course, code block is in triple backticks ```; I just didn't paste that all.
@nagim your idea works, but i don't want add anything in code blocks.
