### ISSUE TITLE
Programming summary using plugins.

### ISSUE THREAD

**Issue by bhaskarmelkani** [GitbookIO/gitbook#1809]
Hi,
I want to program the summary using plugins. Is there a way that I can modify summary object like I do for page object using **'page'** and **'page:before'** hooks.

I found the solution here in the [PR#354](https://github.com/GitbookIO/gitbook/pull/354).

The PR got merged, but I guess after some time the functionality got totally removed.
Any suggestions for how to achieve the same.

Thanks :)

**Comment by julianxhokaxhiu** [comment]
Hi, I am the author of the *summary* plugin for GitBook. Maybe this is what are you searching for? https://plugins.gitbook.com/plugin/summary
