### ISSUE TITLE
The magic of render angular code

### ISSUE THREAD

**Issue by cipchk** [GitbookIO/gitbook#1813]
As you can see [in this book](https://cipchk.gitbooks.io/angular-practice/content/qa.html)

[This is the original markdown file.](https://raw.githubusercontent.com/cipchk/angular-practice/master/qa.md)

![qq 20170619114829](https://user-images.githubusercontent.com/2987467/27268887-3484cb76-54e5-11e7-8867-3c1bb78130c5.png)

Thanks in advance.

**Comment by Mackiovello** [comment]
The double curly bracket syntax `{{}}` crashes with the templating engine as documented here: https://toolchain.gitbook.com/templating/#escaping

Just wrap the code block in `{% raw %}` and `{% endraw %}`

If it solves the problem, please close this issue

**Comment by cipchk** [comment]
I hope I can change it `{{}}` ? can you?

**Comment by Mackiovello** [comment]
What do you mean? I don't understand

**Comment by cipchk** [comment]
thank you.
