### ISSUE TITLE
Alt-text for images after PDF-Conversion

### ISSUE THREAD

**Issue by manfredsteger** [GitbookIO/gitbook#1814]
**Story**: As a researcher and university lecturer i want to produce offline materials (mainly PDFs) from my online materials (gitbook) for all kind of students. The PDFs have to pass some accessibility rules and one important is an alt-text for every single image.

**Feature-Request**: Please integrate a feature that automatically integrates the HTML <img> alt Attribute to the PDF image. 

Thank you very much.

**Comment by cycomachead** [comment]
Late to the party, but you can probably accomplish what you need by using the plugin image-captions

Http://github.com/todvora/gitbook-plugin-image-captions

It will also display the caption below, by default but you could hide that with CSS if you wanted to.
