### ISSUE TITLE
Windows only "Template render error expected variable end"

### ISSUE THREAD

**Issue by samit4me** [GitbookIO/gitbook#1827]
```PowerShell
error: error while generating page "docs/api/ShallowWrapper/containsAllMatchingElements.md":

Template render error: (D:\Development\enzyme\docs\api\ShallowWrapper\containsAllMatchingElements.md) [Line 30, Column 25]
  expected variable end
```

Experiencing the above error on Windows 10 _(macOS has zero issues)_ when running `gitbook serve` on docs containing a JSX block with Object literal props (e.g. `style={{ fontSize: 13 }}`), see **Example 1**. 

After reading the [templating section](https://toolchain.gitbook.com/templating/) of the docs, I update the code block to make use of the escaping tags and it worked, see **Example 2**.

My issues are:

1. Why does **Example 1** work on macOS but not Windows?
1. Should **Example 1** work on Windows or at all?
1. Does it have something to do with line endings (e.g CRLF on Windows) https://github.com/GitbookIO/gitbook-markdown/issues/2?

### Example 1:
```JSX
const wrapper = shallow((
  <div>
    <span className="foo">Hello</span>
    <div style={{ fontSize: 13 }}>Goodbye</div>
    <span>Again</span>
  </div>
));
```

### Example 2:
```JSX
const wrapper = shallow((
  <div>
    <span className="foo">Hello</span>
    <div style={% raw %}{{ fontSize: 13 }}{% endraw %}>Goodbye</div>
    <span>Again</span>
  </div>
));
```

**Comment by yangheng** [comment]
@samit4me  
If your code contains templating syntax such as {{ this }} (see templating), you can disable templating with a {% raw %}{% endraw %} block:+

For example: 
   
{% raw %}
```js
var Dialog = require('ysp-interior-components').Dialog;
module.exports = React.createClass({

  getInitialState: function() {
    return { open: false };
  },

  handleClick: function() {
      this.setState({
        open: !this.state.open
    });
  },

  render: function() {
      return (
      <div>
        <AMUI.Button onClick={this.handleClick}>点我显示弹窗</AMUI.Button>
        {this.state.open &&
          <Dialog config={{status: "real"}}>
            <h4 className="modal-title">Modal 标题</h4>
            <span onClick={this.handleClick} className="icon icon-close modal-icon"></span>
            <div className="modal-body">Hello, Modal 内容</div>
          </Dialog>}
      </div>
    );
  }
});
```
{% endraw %}
