### ISSUE TITLE
pdf.margin without effect

### ISSUE THREAD

**Issue by reaseno** [GitbookIO/gitbook#1828]
I put the following in my book.json: 
 "pdf": {
    "fontSize": 14,
    "fontFamily": "Verdana",
    "margin": {
      "right": 10,
      "left": 10,
      "top": 10,
      "bottom": 10
    }
  }

Changes in fontSize and fontFamily does have effects on the created PDF, but not the margin settings. Could you please tell me, why is that so?

CLI version: 2.3.2
GitBook version: 3.2.2
calibre (calibre 3.4)

**Comment by cntgfy90** [comment]
maybe because you can't take inner object in double quotes as the properties that belong to this inner object
Or maybe you should place semicolon after the first closin curly brace which belongs to the margin object

**Comment by menedas** [comment]
No, its not a json error. Using single quotes leads to errors.
Example here is the same:
http://www.chengweiyang.cn/gitbook/customize/book.json.html

**Comment by warren-bank** [comment]
I'm about 99.99% sure that the `ebook-convert` binary is ignoring these options..

according to [their docs](https://manual.calibre-ebook.com/generated/en/ebook-convert.html):

* common margin settings include:
  * `--margin-left`
  * `--margin-right`
  * `--margin-top`
  * `--margin-bottom`

* pdf specific margin settings can be used to override:
  * `--pdf-page-margin-left`
  * `--pdf-page-margin-right`
  * `--pdf-page-margin-top`
  * `--pdf-page-margin-bottom`

these values can be confirmed in [onFinish.js](https://github.com/GitbookIO/gitbook/blob/master/lib/output/ebook/onFinish.js):
```javascript
/**
    Generate the ebook file as "index.pdf"

    @param {Output}
    @return {Output}
*/
function runEbookConvert(output) {
    var logger = output.getLogger();
    var options = output.getOptions();
    var format = options.get('format');
    var outputFolder = output.getRoot();

    if (!format) {
        return Promise(output);
    }

    return getConvertOptions(output)
    .then(function(options) {

// https://manual.calibre-ebook.com/generated/en/ebook-convert.html
if (format.toLowerCase() === 'pdf') {
  options["--pdf-page-margin-left"]   = options["--margin-left"]
  options["--pdf-page-margin-right"]  = options["--margin-right"]
  options["--pdf-page-margin-top"]    = options["--margin-top"]
  options["--pdf-page-margin-bottom"] = options["--margin-bottom"]
}

        var cmd = [
            'ebook-convert',
            path.resolve(outputFolder, SUMMARY_FILE),
            path.resolve(outputFolder, 'index.' + format),
            command.optionsToShellArgs(options)
        ].join(' ');

console.log('cmd =', cmd)
process.exit(1)

        return command.exec(cmd)
        .progress(function(data) {
            logger.debug(data);
        })
        .fail(function(err) {
            if (err.code == 127) {
                throw error.RequireInstallError({
                    cmd: 'ebook-convert',
                    install: 'Install it from Calibre: https://calibre-ebook.com'
                });
            }

            throw error.EbookError(err);
        });
    })
    .thenResolve(output);
}
```
