### ISSUE TITLE
Don't restart the server while rebuilding the book

### ISSUE THREAD

**Issue by CaledoniaProject** [GitbookIO/gitbook#1829]
### Version in use

```
%> gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.2
```

### What is the current behavior?

When the content is updated, gitbook would stop the server then start it again.

Is it possible to change this behavior? Update the _book folder without kill & restart the websocket server?

```
%> gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 49 pages
info: found 32 asset files
info: >> generation finished with success in 10.6s !

Starting server ...
Serving book on http://localhost:4000
Restart after change in file dev/api/context.md

Stopping server
info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 49 pages
info: found 32 asset files
info: >> generation finished with success in 9.7s !

Starting server ...
Serving book on http://localhost:4000
```

**Comment by ndbroadbent** [comment]
+1, these restarts are happening way too frequently for me. Is there any way to prevent this?

**Comment by ndbroadbent** [comment]
@iwsed Yes the "stopping server" part is also taking a really long time for me. I know this project isn't maintained anymore, but it's working pretty well for me, so I might try to fix this.

**Comment by ndbroadbent** [comment]
Hi everyone, I fixed the performance issues and GitBook is a lot faster for me during development: https://github.com/GitbookIO/gitbook/pull/2127

You can try out my branch by adding it to your `package.json`: `"gitbook": "FormAPI/gitbook#fix-serve-performance"`

Then run `npm install` (or `yarn install`), and set up an alias: `gitbook alias ./node_modules/gitbook 3.2.3`
