### ISSUE TITLE
Links present in documents were not working

### ISSUE THREAD

**Issue by electricmind007** [GitbookIO/gitbook#1830]
### What is the current behavior?
I am creating a document using gitbook plugin to publish it using github pages. I have created README.md and SUMMARY.md files with the appropriate content. I have some .md files which is referenced in SUMMARY.md file. In that .md file, I am having a link to another .md file. When I am doing gitbook build, the .md file referenced in SUMMARY.md is showing correctly and can be navigated. But, when I am checking the .md file link inside another .md file, it is not working due to .md file extension is not converted into .html. Also the .md file which i have mentioned is having spaces. I am using Gitbook3.2.2 version and gitbook-cli version is 2.3.0.

### What is the expected behavior?
All the links (.md links) provided in any .md file should be converted into .html

Please help me to get the issue resolved at the earliest.

**Comment by muyun12** [comment]
I have the same problem
