### ISSUE TITLE
Keep updating for hours

### ISSUE THREAD

**Issue by cifangmao** [GitbookIO/gitbook#1841]

**Comment by TReagle** [comment]
Seems to be working now

**Comment by dotSlashLu** [comment]
Mine too, is Gitbook out of service?
I think it could be caused by time zone. It used to be well editing by desktop clients, but fails this time with web client. I saw the page saying the update I just submitted was started 8 hrs before and I'm in GMT+8.

**Comment by hamishwillee** [comment]
Me too. Happened overnight - local build 6 seconds, gitbook build 4333+ seconds. Got a "failed build" report on website last night, but it had actually built.

Perhaps useful debug, is that even though the submit time is about right (3.15 locally) the note that this was done 5 hours ago is wrong - did it a few minutes ago.
![image](https://user-images.githubusercontent.com/5368500/29599733-1362f694-8815-11e7-9869-8ae2d506b4ac.png)

I have tried this with a number of different repos, both new ones, and ones that have worked well in the past, and with minor changes.

This the test case: https://www.gitbook.com/book/hamishwillee/minimal-test-book-for-testing-gitbook-changes/activity?branch=test_embed_code

**Comment by hamishwillee** [comment]
Seems to be working well today after fix from Gitbook.
