### ISSUE TITLE
Multiple books shares the same custom domain?

### ISSUE THREAD

**Issue by nantas** [GitbookIO/gitbook#1842]
Hi I'm wondering if it's possible to set multiple gitbooks to use the same custom domain.

For example I have a domain `www.mybooks.com`, and 3 books named `book1`, `book2`, `book3`

How can I set them up so I can access each book with `www.mybooks.com/book1`, `www.mybooks.com/book2` etc?

For github pages you can set custom domain to the homepage of user/organization and any repo with gh under the user/org will have their website hosted at `username.github.io/reponame`.

Do we have anything similar for gitbook?

Thanks in advance!

**Comment by splix** [comment]
I have the same question. 

@nantas did you find a way to do that?
