### ISSUE TITLE
Navigation broken in static builds

### ISSUE THREAD

**Issue by rorywalsh** [GitbookIO/gitbook#1844]
### What is the current behavior?

I'm using the very latest alpha version of gitbook. The navigation sidebar in static builds does not work. It does when I run `gitbook serve`. 

### What is the expected behavior?

I would expect it to work the same in a static build as it does on a server.

**Comment by AaronO** [comment]
@rorywalsh Can you specify your exact version number ?

**Comment by rorywalsh** [comment]
Of course, it's 4.0.0-alpha.6
I tried rolling back to earlier versions but I get the same issue. I'm
embarrassed to say I've been using v1 all this time! Even in a very basic
project I have issue with a static build.

**Comment by AaronO** [comment]
v1 really ? wow ... :D

`v3` is the current stable `gitbook` (CLI) release so I recommend using that. The sidebar should work. 
`v4` will likely be leapfrogged with a `v5`.

`v4` explored some interesting ideas, but we ultimately took a different direction with more radical improvements to the product: [beta.gitbook.com](https://beta.gitbook.com/)

**Comment by rorywalsh** [comment]
I just install versions 3.2.3 and I still have the same issues, `gitbook
serve` still works just fine.

**Comment by rorywalsh** [comment]
Just another thing I noticed, the link that appears on a mouse over in the browser status bar seems to be the correct link, for example:

`file:///home/User/Docs/_book/file_structure_and_syntax.html`

Right-clicking and opening in new tab works, but clicking directly doesn't?

**Comment by LPGhatguy** [comment]
If you open up your browser dev tools, you'll see an error like this in Chrome:

> Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

The way that Gitbook's navigation works means that it can't function when accessed via a `file://` URL.

**Comment by rorywalsh** [comment]
Which makes it impossible to build static sites? Or? Apologies, this is not
my domain..
