### ISSUE TITLE
[ BUG ] Placing any structure file in .gitignore ignores the file from being used during build time

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GitbookIO/gitbook#1845]
### What is the current behavior?

Placing any structure file inside of `.gitignore` ignores the file during build time. This was unexpected and not documented. 

First of all the environment informations:
```shell
$ gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3
```
and this is the content of my `.gitignore`
```shell
$ cat .gitignore
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Typescript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# Current Project
SUMMARY.md
```
Why is it in ignore? Because I am auto-generating my SUMMARY.md file through my own plugin ( https://github.com/julianxhokaxhiu/gitbook-plugin-summary ). Therefore I do not need to commit it.

When I run `gitbook serve` or `gitbook build`, as of now I get this:
```
$ gitbook build
warn: no summary file in this book
info: 8 plugins are installed
info: 7 explicitly listed
info: loading plugin "summary"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 1 pages
info: found 1 asset files
gitbook-plugin-summary: SUMMARY.md generated successfully.
info: >> generation finished with success in 1.1s !
```

Notice the `warn: no summary file in this book`. Also, this is my `book.json`
```json
{
  "language": "en",
  "direction": "ltr",
  "plugins": [
    "summary"
  ]
}
```

### What is the expected behavior?

The `SUMMARY.md` file for eg. is ignored through commits, BUT is used during `gitbook serve` or `gitbook build`.

### Where is the bug living precisely?
Debugging your code, I found out that the bug lives on this line:
https://github.com/GitbookIO/gitbook/blob/master/lib/parse/findParsableFile.js#L27
when the API `book.isContentFileIgnored(found)` is called. This basically uses the [ignore](https://www.npmjs.com/package/ignore) package, which also gets the list from `.gitignore`. Maybe you should "force whitelist" your structure files.

**Comment by julianxhokaxhiu** [comment]
Any update on this?

**Comment by christophetd** [comment]
Noticing the same behavior here, any update?

**Comment by vdanchenkov** [comment]
.bookignore can be used to override this behaviour
