### ISSUE TITLE
My Account has been suspended , please help me .

### ISSUE THREAD

**Issue by JackChan1999** [GitbookIO/gitbook#1849]
When I login in my gitbook account, It say that My Account has been suspended.

I don't known why and what can I do?

what hanppened about my account ? I don't do anything bad.

My username is alleniverson , email is 815712739@qq.com.

Someone can help me, thanks very much.

**Comment by krystofspl** [comment]
This happened to me as well, my docs are lost now :-(

**Comment by sdwio** [comment]
Same problem here, just registered using my github account, immediately suspended.

**Comment by AaronO** [comment]
@sdwio Replied to your Zendesk ticket and unlocked your account, you should be good.

**Comment by sdwio** [comment]
I am good and stunned by the _support within minutes_. Thanks.

**Comment by ProNibs** [comment]
I, too, was immediately suspended from Gitbook after signing in with my Github account and adding my e-mail address.

**Comment by howdoicomputer** [comment]
Same. Just happened to me. @AaronO Christmas gift?

**Comment by AaronO** [comment]
@howdoicomputer Deploying an update now, to tone down the spam filter's aggressiveness.

Update is currently going through CI (so should be live in 10-15mn give or take), I'll unlock your account from our admin dashboard once that's live.

**Comment by AaronO** [comment]
@howdoicomputer Voilà, deploy is live and I've unlocked your account, you should now be able to login again.

Sorry about that and enjoy the holidays ! 🎄🎄🎄

**Comment by ProNibs** [comment]
@AaronO Hey pal, I’m still locked out too! :(

My Zendesk # is 7142. Would greatly appreciate a fix or at least some answer.

**Comment by Soreine** [comment]
@ProNibs @krystofspl I have unlocked your account. Sorry for the inconvenience.

**Comment by kreetrapper** [comment]
I had the exact same issue on the beginning of December. I have tried the contact form on the gitbook site (request 7044 and 7394), but so far to no avail. I would be grateful, if you could unlock my account as well.
