### ISSUE TITLE
Every chapter starts with 1

### ISSUE THREAD

**Issue by DJviolin** [GitbookIO/gitbook#1853]
```sh
$ gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3
$ node -v && npm -v
v8.4.0
5.0.4
```

I have the following summary:

```mk
# My project

* [Preface](README.md)

* [Chapter 1](c01/README.md)
    * [Sub-chapter](c01/sub.md)

* [Chapter 2](c02/README.md)
    * [Sub-chapter](c02/sub.md)
```

I want the following numbering in my `Table of Contents`:

```
0. Preface
1. Chapter 1
    1.1. Sub-chapter
2. Chapter 2
    2.1. Sub-chapter
```

However what I got:

```
1.1. Preface
1.2. Chapter 1
    1.2.1. Sub-chapter
1.3. Chapter 2
    1.3.1. Sub-chapter
```

**Comment by LPGhatguy** [comment]
Markdown can be picky with lists. Have you tried changing the list in your `SUMMARY` to have no blank lines between the entries?

**Comment by DJviolin** [comment]
Deleting the blank lines doesn't change anything. Now I use `----`  separator between the chapters to have at least this structure:

```
# My project

* [Preface](README.md)

----

* [Chapter 1](c01/README.md)
    * [Sub-chapter](c01/sub.md)

----

* [Chapter 2](c02/README.md)
    * [Sub-chapter](c02/sub.md)
```

But this is still not what I want:

```
1.1. Preface
2.1. Chapter 1
    2.1.1. Sub-chapter
3.1. Chapter 2
    3.1.1. Sub-chapter
```

I want this numbering:

```
1. Preface
2. Chapter 1
    2.1. Sub-chapter
3. Chapter 2
    3.1. Sub-chapter
```

**Comment by biomystery** [comment]
same here

$ node -v && npm -v                                    |                                                                                          
v8.3.0                                                                                    |                                                                                          
5.5.1 

gitbook -V                                           |                                                                                          
CLI version: 2.3.2                                                                        |                                                                                          
GitBook version: 3.2.3

**Comment by crifan** [comment]
same here. 

> ➜  backup_restore node -v
> v10.4.0
> ➜  backup_restore npm -v
> 6.1.0
> ➜  backup_restore gitbook --version
> CLI version: 2.3.2
> GitBook version: 3.2.3



Please fix it ASAP !!!
