### ISSUE TITLE
Github linking attributes commits to a random github user 

### ISSUE THREAD

**Issue by Maestro501** [GitbookIO/gitbook#1855]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?
When I publish an edit to a book linked to one of my github organisation repository through gitbook web editor, the commit to github repository gets attributed to a random github user (who does not even have access to my organisation)
![screen shot 2017-09-11 at 4 36 28 pm](https://user-images.githubusercontent.com/6448634/30265684-7006794e-970f-11e7-93a7-42c01785b06f.png)

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).
1. Create a book from existing github repository (in my case, an organisation's repository)
2. Create an edit through web editor, and publish the content
3. Go back and see the linked commit on github repository

- gitbook version: I'm only using web interface, so not sure how I can find out
- OS: MacOS Sierra 10.12.3
- Browser: Chrome v60

### What is the expected behavior?
That the commit either gets attributed to the github account connected to my gitbook account, or to gitbook integration generated commit somehow?

#### For GitBook.com

Provide, if possible, your username and the URL of the concerned book.

This is only observable in my private github repository, so this is not available.

**Comment by Maestro501** [comment]
Actually, the book is available here.
https://www.gitbook.com/book/maestro501/metisa-js/details

**Comment by AlexHartveld** [comment]
I have the same issue, and the same user who is attributed. Maybe he was the developer and they didn't find a solution yet?

**Comment by Maestro501** [comment]
Not sure. Could not see any connection between him and Gitbook from his profile though.
I decided not to use their source control and editor for now.

**Comment by AaronO** [comment]
@Maestro501 What's the email you have in your `git log` for those commits ?

**Comment by AaronO** [comment]
@Maestro501 Were you using the Desktop Editor ?

If so and you hadn't connected it to your GitBook account, commits are authored with the `ghost@gitbook.com` email.

Somehow GitHub resolves commits with that "ghost" email to @marshyski (when it displays the commit log on GitHub.com).

I created a project to reproduce this: https://github.com/AaronO/git-ghosts/commits/master

![image](https://user-images.githubusercontent.com/949223/30368382-497b17a4-9871-11e7-976c-979b5ab520a9.png)

So to clarify, nobody had access to your data or modified it. It's simply that GitHub is resolving all commits made with the `ghost@gitbook.com` email to that user.
