### ISSUE TITLE
Gitbook Editor for Linux: Does not start in Debian 9 (Stretch) x64. Openssl error.

### ISSUE THREAD

**Issue by parijathakumar** [GitbookIO/gitbook#1862]
On Debian-9 (Stretch) x64, I was able to install the downloaded x64 deb of gitbook-editor-7.0.12. But when I try to start I get error "the git manager process has crashed". When I started from terminal, I could see the error messages. The first one is regarding mising libssl.so.1.0.0 and the second one was about missing libcrypto.so.1.0.0 both of which I could pass through by symlinking to default versions installed on my system. Further, I get an error saying " version OPENSSL_1.0.0 not found". The default openssl of Debian Stretch is '1.1' it seems. What can I do now ? It seems some similar problems are affecting Arch Linux users as well.

Can anyone help me to fix this issue ?

**Comment by freundallein** [comment]
You can install libssl1.0.0, worked for me
`wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb`
`dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb`
