### ISSUE TITLE
can one integrate jQuery and Javascript?

### ISSUE THREAD

**Issue by slackmoehrle** [GitbookIO/gitbook#1870]
We have a lot of docs in Markdown and use MKDocs, currently. Evaluating Gitbook and it seems great so far. However, one thing that isn't obvious is if we can embed jQuery and Javascript into our markdown. Currently we do something like this:

```
 <div class="langs">
  <ul>
    <li><a href="#" id="tab-cpp">C++</a></li>
    <li><a href="#" id="tab-js">Javascript</a></li>
  </ul>
</div>
  <div class="tab-cpp tab_content">
```
```cpp
  auto mySprite = Sprite::create("mysprite.png");
```
```
  </div>

  <div class="tab-js tab_content">
```
```javascript
  var mySprite = new cc.Sprite(res.mySprite_png);
```
```
  </div>

```

and in HTML files we include links to the necessary css and js files to make this all work.

Here is a working example: http://cocos2d-x.org/docs/programmers-guide/sprites/index.html

**Comment by nagim** [comment]
Sure, you can embed it (I frequently use bootstrap code in my docs). But this behavior is supported out of the box by the [API theme](https://github.com/GitbookIO/theme-api).

**Comment by slackmoehrle** [comment]
Thanks. I have things working pretty well now, except with one issue. I use JQuery to allow the user to switch reading language from English to Chinese. Like:
```html
<div class="langs">
  <ul>
    <li><a href="#" id="tab-en">English</a></li>
    <li><a href="#" id="tab-zh">中文</a></li>
  </ul>
</div>
  <span class="tab-en tab_content">

## English content goes here

  </span>

  <span class="tab-en tab_content">

## Chinese content goes here

  </span>
```

and it works. Like:

<img width="1105" alt="screen shot 2017-09-28 at 7 26 21 am" src="https://user-images.githubusercontent.com/7491758/30964325-d283ea5e-a41e-11e7-8df5-c3c90a39c152.png">

Except for one thing. It fails to recognize the </span> so my tabs don't work correctly.

Like:

<img width="1092" alt="screen shot 2017-09-28 at 7 28 59 am" src="https://user-images.githubusercontent.com/7491758/30964307-c33d1b6a-a41e-11e7-9c07-42efb507799c.png">
