### ISSUE TITLE
the gitbook editor is loading with error

### ISSUE THREAD

**Issue by jipengzhu** [GitbookIO/gitbook#1873]
# loading error
I create a new book and the gitbook editor is loading all the time.

I find the error with the developer tool, but i don't what’s the reason of it

![2017-10-01 21 20 35 2](https://user-images.githubusercontent.com/29984300/31054942-5c1a4240-a6ef-11e7-88a1-d21c71347483.png)

the error is here : 
1. Uncaught SyntaxError: Unexpected token  in JSON at position 378
2. [2017-10-01T13:11:50.850Z] [init] info: running desktop version
3. Uncaught TypeError: Parameter 'url' must be a string, not undefined

part of code :
1. if(!util.isString(t))throw new TypeError("Parameter 'url' must be a string, not "+typeof t) 

# build failed
The build task #57fa209723 has running for a few weeks.
I have received some failed task mail in the past time, but i could not find a way to cancel it.

#1865 
![2017-10-01 21 34 45](https://user-images.githubusercontent.com/29984300/31055140-05715f16-a6f2-11e7-865f-de59b279968d.png)

**Comment by Lin-Buo-Ren** [comment]
I found a workaround to avoid the "loading error" issue, the JSON error appeared to be a Unicode issue in the GitBook website's book info, if you change the "Title" field in the book's setting page to something without non-ASCII the book will be loadable in local GitBook editor.

**Comment by jipengzhu** [comment]
@Lin-Buo-Ren 
Thank you very much. It solves my problem.

But I still want to know why.

the situation is that 
1. I create two books at the same time
2. one is named as "Linux 基础手册"
3. another is named as "Python 基础手册"
4. They has the same unicode character
5. "Linux 基础手册" is ok to open
6.  but "Python 基础手册" is not ok

**Comment by Lin-Buo-Ren** [comment]
Check for all the fields in the book info settings, it might not be the Title field that will trigger this issue
