### ISSUE TITLE
Custom css file is not used.

### ISSUE THREAD

**Issue by hbr** [GitbookIO/gitbook#1876]
I have put a file named "website.css" in the subdirectory "styles" of my gitbook. The css file has the contents

    h1: {border-style: double;}
    h2: {border-bottom-style: solid;}

The css file is not used when I start `gitbook serve` and view the content with my browser. The same happens when I go to the gitbook website.

I have my content on a gitbook project (see https://github.com/hbr/alba-lang-description).

What can I do to convince gitbook to use my custom css file?

I use

CLI version: 2.3.0
GitBook version: 3.2.2

on a macbook pro high sierra.

Thanks for any hint.

**Comment by Saturate** [comment]
This does not seem like valid CSS to me.

```
h1: {border-style: double;}
h2: {border-bottom-style: solid;}
```

Try with 

```
h1 {border-style: double;}
h2 {border-bottom-style: solid;}
```

**Comment by hbr** [comment]
Thanks. I have been blind.
