### ISSUE TITLE
description is not read from book.json

### ISSUE THREAD

**Issue by JMLX42** [GitbookIO/gitbook#1877]
### Current behavior

The [documentation](https://toolchain.gitbook.com/config.html) states that the description of the book can be set by filling the `description` field in `book.json`. But when this field is filled, the generated `index.html` still features an empty description tag and there is no trace of the actual description:

```
<meta name="description" content="">
```

### Expected behavior

The generated HTML page should feature the actual description as set in the `description` field of `book.json`.

### Workaround

Place the description in `README.md`:

```
---
description: Your description here...
---
```

**Comment by rootsongjc** [comment]
I hope can set the whole gitbook with the same  description on every single page rather than set the page one by one.
