### ISSUE TITLE
book.json configuration

### ISSUE THREAD

**Issue by SeungKiLeeSMU** [GitbookIO/gitbook#1882]
Hi, I am a user who've just started using gitbook. While I am amazed at its functionality and UX, I have ran into problem in configuring it.

When I create a book and try to style it, I can not because I can't ever find the book.json file for customization. I tried creating the file, but I can't configure it successfully.

If possible, could you please inform me the following?

1. How and Where is book.json file created?
2. If I have to create it myself, where should I place it?
3. Is there a book.json example I can look at to learn more about this?

thank you. Please let me know once you get a chance.

**Comment by vikrambajaj22** [comment]
Did you ever find the book.json file?
