### ISSUE TITLE
Modify title and add suffix?

### ISSUE THREAD

**Issue by CaledoniaProject** [GitbookIO/gitbook#1886]
By default gitbook generate titles like this `<title>MyTitle · GitBook</title>`

I'm wondering if I can change the suffix, without changing all markdown documents? aka the ` · GitBook` part

**Comment by AndrewBelt** [comment]
I have the same problem because the title is not being extracted from `README.md`.

As a workaround, you can add
```json
  "title": "My Title",
```
to your `book.json`.
