### ISSUE TITLE
How to remove title of the book link from gitbook?

### ISSUE THREAD

**Issue by Qiplex** [GitbookIO/gitbook#1888]
Hello,

Just discovered gitbook service today. It's pretty awesome! Exactly what I needed to host documentation.

I published my gitbook at custom domain http://help.qiplex.com/ It's empty so far. 

How can I remove very first link - _Qiplex Help Center_, which is the title of the book? 

<img width="398" alt="screen shot 2017-10-19 at 21 29 15" src="https://user-images.githubusercontent.com/32670415/31787527-be856a1c-b514-11e7-8cbd-c7312f81608e.png">

It seems like there is no such link in `SUMMARY.md`
```
 $ cat SUMMARY.md

# Summary

* [Introduction](README.md)
* [Apps](apps.md)
  * [Organize My Files](organize-my-files.md)
    * [Using Filters](organize-my-files/filters.md)
    * [Custom Destinations](organize-my-files/custom-destinations.md)
    * [Auto Organizing](organize-my-files/auto-organizing.md)
    * [Multiple Folders Organizing](organize-my-files/organizing-multiple-folders-organizing.md)
    * [Recursive Organizing](organize-my-files/recursive-organizing.md)
    * [Undo Changes](organize-my-files/undo-changes.md)
```

Thanks!

**Comment by rafapetter** [comment]
I'm sure it's not the best solution, but it will work if you don't use custom links on your sidebar. Hopefully someone with a better knowledge can give us a better solution.

Until then... on your book.json, set sidebar to false:

```
"links": {
    "sidebar": false
}
```

**Comment by leithlin** [comment]
you can hide it by using css

**Comment by HenryXi** [comment]
I use `"sidebar": false` and fail to remove the link.
