### ISSUE TITLE
why is gitbook automatically installing livereload plugin 

### ISSUE THREAD

**Issue by neptunian** [GitbookIO/gitbook#1891]
I don't want to make this call on my site but all my html files have a call to the live reload plugin.
my book.json does not make any reference to this plugin.  how can i remove it from my files?  i only have 2 plugins listed in my book.json but when i serve the site, it seems to be installing many plugins including livereload.  the problem is my production version has a call to this js file and its slowing down the site.

**Comment by tristanpendergrass** [comment]
@neptunian I ran into this, but I was able to solve it. Try running `gitbook build` before deploying.

I believe when you run ```gitbook serve``` it builds a `_book/` which contains the livereload plugin. But if you run ```gitbook build``` it builds a `_book/` which does not contain that plugin. I'm guessing `server` is intended to be run when you're doing local development and `build` for when you're about to push to production. It would be nice if the docs mentioned this difference though, I had to guess it.

**Comment by neptunian** [comment]
@tristanpendergrass  thanks a lot

**Comment by meloseven** [comment]
you can run like this:
`gitbook serve --no-live --port 5000`

**Comment by meloseven** [comment]
You can run like this:

> gitbook serve --no-live --port 5000

**Comment by meloseven** [comment]
You can run like this:
```
gitbook serve --no-live --port 5000
```
