### ISSUE TITLE
can pdf output use pdf image files instead?

### ISSUE THREAD

**Issue by stevepowell99** [GitbookIO/gitbook#190]
one of the great things about using markdown via pandoc is the ability to include vector graphics in pdf or similar format rather than pngs or jpgs. I produce a lot of techinical graphs and the user usually wants to enlarge them onscreen, but in the gitbook-produced pdf they would just get big pixels. 
Is there any way to incorporate vector graphics in gitbook?

**Comment by SamyPesse** [comment]
This issue will be fixed in the 2.0.0 release (#562).
