### ISSUE TITLE
How to add a green checker?

### ISSUE THREAD

**Issue by dharmarooms** [GitbookIO/gitbook#1900]
How to add a green checker read/unread ?

![2017-10-30 2 52 52](https://user-images.githubusercontent.com/33027199/32150001-cb80d6be-bd1d-11e7-94fc-1bec5e6ca3a5.png)

**Comment by Saturate** [comment]
It was a feature in an old version, now it's most likely a plugin. If you link to the docs that you took a screenshot of it will be easier to find it.

**Comment by ld0574** [comment]
So wanna this pulgin
