### ISSUE TITLE
Gitbook Pdf does not work incompatible library Qtwidgets. 

### ISSUE THREAD

**Issue by Charliemowood** [GitbookIO/gitbook#1901]
### What is the current behavior?

Running `gitbook pdf`. Does not convert. 

Errors: 

`EbookError: Error during ebook generation: Conversion options changed from defaults`

```ImportError: dlopen(/Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so
  Reason: Incompatible library version: QtWidgets.so requires version 5.6.0 or later, but QtWidgets provides version 5.5.0
```

### What is the expected behavior?

Should Convert to pdf.

**Comment by mjhea0** [comment]
Any updates?

**Comment by Charliemowood** [comment]
@mjhea0 yes I solved this by: reimaging my mac. My theory was that by installing Sonic Pi, I had the wrong version QTwidgets set up.

**Comment by mjhea0** [comment]
Thanks for the quick response @Charliemowood. Turned out to be a brew issue. An old keg was linked.
