### ISSUE TITLE
generates broken links to index.html

### ISSUE THREAD

**Issue by benzaita** [GitbookIO/gitbook#1913]
### What is the current behavior?

* Add a link to `[part1](part1/README.md)` in `SUMMARY.md`
* Generate static files

Gitbook generates the "part1" link as `part1/` (and not `part1/index.html`). This assumes that the HTTP server serving these files will serve `index.html` by default.

However, this is *not* the case in every HTTP server.

### What is the expected behavior?

Gitbook should generate links to `README.md` as `index.html`.

**Comment by AaronO** [comment]
@benzaita That would lead to "ugly" URLs for most users.

Our hosting ([gitbook.com](https://www.gitbook.com)) and any modern HTTP handles mapping `/` to `/index.html`.

What HTTP server are you using ? I can't think of any modern/popular HTTP server that doesn't support it (S3, nginx, apache, ... all support it)

**Comment by benzaita** [comment]
@AaronO  Technically you are correct, but it's a matter of policy, not feasibility.

May I suggest to add this as a configuration?
