### ISSUE TITLE
Some hyperlinks do not work

### ISSUE THREAD

**Issue by aborruso** [GitbookIO/gitbook#1923]
Hi,
in this book (https://goo.gl/wK3hd6) there is an hyperlink to a CSV file, but it does not work properly

![image](https://user-images.githubusercontent.com/30607/32981576-8e3ff050-cc77-11e7-9587-0c6cd89a22fe.png)

If I left click with my mouse on it nothing happens, if I use I right click to "save the link as ..." the download starts. The the hyperlink is right but why the download does not start with left click?

Thank you

**Comment by kmxz** [comment]
As shown above, I created https://github.com/GitbookIO/theme-default/pull/62 which exactly fixes this problem.
