### ISSUE TITLE
Link to next page broken when navigation links to section in a page 

### ISSUE THREAD

**Issue by hamvocke** [GitbookIO/gitbook#1926]
Let's take a `SUMMARY.md` like this:

```
* [Page 1](page1.md)
* [Page 2](page2.md)
    * [Section 1](page2.md#section-1)
    * [Section 2](page2.md#section-2)
* [Page 3](page3.md)
```

If I render my gitbook and go to _page 1_ I can navigate from _page 1_ to _page 2_ perfectly fine using the arrow on the right side (next page).

Once I'm on _page 2_, clicking the right arrow doesn't take me to _page 3_ as I'd expect. Instead it takes me to _section 1_ of _page 2_ and I'm stuck there.

You can reproduce this behaviour in gitbook's own [documentation](https://toolchain.gitbook.com/syntax/markdown.html) (try clicking the right arrow and see where this gets you).

Can we get this behaviour fixed so that using the arrows works as expected?

CLI version: 2.3.2
GitBook version: 3.2.3

**Comment by alnf** [comment]
Thanks a lot for posting this! I have the identical issue with same CLI and GitBook versions.

**Comment by AaronO** [comment]
@hamvocke @alnf Would a mini TOC (inside the page) be a better fit to your needs ?
(Allowing the user to easily navigate to sub-titles inside a page)

If so, that's one of the many other improvements we've implemented in the upcoming product release (https://beta.gitbook.com)

You can see it in action here: https://betadocs.gitbook.com/team-admin/saml

**Comment by alnf** [comment]
@AaronO Cute! I like the new feature.

Regarding the issue - is it troublesome to implement? If yes, maybe mentioning the limitation in the docs will help at least, because at first I thought smth was wrong with my code. But overall, here I agree with @hamvocke when he writes about "expected" behavior of the arrows.
