### ISSUE TITLE
gitbook

### ISSUE THREAD

**Issue by ng-work** [GitbookIO/gitbook#1927]
请问下怎么去掉跳转到gitbook.com的菜单，还有怎么把type to search 转成中文，把Introduction 去掉
![1511494039586](https://user-images.githubusercontent.com/22250220/33194355-7c65e406-d10a-11e7-914c-2ef1b8fb5de8.jpg)

**Comment by k00ni** [comment]
Could you translate your issue to English?

**Comment by anselmbradford** [comment]
According to google translate:

> I would like to ask how to remove the jump to gitbook.com menu, as well as how to type to search into Chinese, the Introduction removed

@ng-work see https://github.com/GitbookIO/gitbook/issues/1404
