### ISSUE TITLE
TypeError: attributes.toJS is not a function

### ISSUE THREAD

**Issue by insanity54** [GitbookIO/gitbook#1929]
Gitbook has been failing to build my book updates with this error:

```
error: error while generating page "README.md": 

Template render error: (/root/.gitbook/versions/3.2.3/node_modules/gitbook-plugin-search/_layouts/website/page.html)
  Template render error: (/root/.gitbook/versions/3.2.3/node_modules/gitbook-plugin-theme-default/_layouts/website/summary.html) [Line 4, Column 46]
  TypeError: attributes.toJS is not a function
```

This problem has been going on for about two weeks and five `git push`es. I'm not using GitBook CLI so I can't run `gitbook -V`. but from the [build output](https://www.gitbook.com/book/insanity54/nanowrimo/build/5a07fc5be108650031c7cf3f), the server seems to be running 3.2.3. 

At first I thought this was due to some erroneous input at the start of my SUMMARY.md as seen in this commit https://github.com/insanity54/nanowrimo2017_practice/blame/f6e61e4b75c01267fb6d33491ef7b11b6629ba03/SUMMARY.md#L1. Upon further inspection, that erroneous input had been there for many commits before, and was not causing the GitBook builds to fail.

Another suspect is README.md, as that is a file noted in the GitBook build error. I can't see why that file would be causing the GitBook build to fail, as it had not been modified on the commit which started the chain of failures.

Here's my GitBook URL. https://www.gitbook.com/book/insanity54/nanowrimo/details

I'm not sure what to do next to debug this error.

**Comment by BabOuDev** [comment]
+1

**Comment by BabOuDev** [comment]
OK, I found out it's happening when you do not have anybecause

**Comment by insanity54** [comment]
That fixed it. Thanks very much!

**Comment by beeman** [comment]
I had the same issue, in my case the problem was that the file ended in '---'.
