### ISSUE TITLE
Hello! My account has been suspended, but I don't know on what reason.

### ISSUE THREAD

**Issue by rmalkevy** [GitbookIO/gitbook#1930]
Hello) 

My account has been suspended, but I don't know on what reason.
I had written to support 3 October about this problem. But I didn't receive answer. 
Request on Zendesk - 6628.

I spent few month for translating materials about programing computer graphics. 
And I want to restore this book - https://rmalkevy.gitbooks.io/computer-graphic-for-unit-students

Best regards

**Comment by AlexPixelant** [comment]
Hi,
I have same issue. Every time I try to access my account it shows me "Your account has been suspended". I have tried to contact support (zendesk ticket: 6943 ) but I didn't receive any reply from them.

Who can help me?

**Comment by EasonWang01** [comment]
I wonder is Gitbook team still alive.
Because all the mail and issue got no response since 2017.
