### ISSUE TITLE
Gitbook.com: Changes in the web-editor are not available in the read/book view

### ISSUE THREAD

**Issue by k00ni** [GitbookIO/gitbook#1934]
First of all, thanks for this webservice. It seems like a great tool for publishing content. I would like to use it to publish my research work. Therefore the following issue is very unfortunate.

### What is the current behavior?

I changed multiple files in my book. That is the view in the web-editor:

![bildschirmfoto vom 2017-12-05 12-37-14](https://user-images.githubusercontent.com/381727/33605288-5b7d24b8-d9b9-11e7-801a-faa5df281470.png)

In the README.md i added the **Contribution** section. And i pressed the Publish button.

But when i open the overview or **read**-view of the book, it doesn't have that section:

![bildschirmfoto vom 2017-12-05 12-37-26](https://user-images.githubusercontent.com/381727/33605313-7d0d3eb0-d9b9-11e7-87a0-dc6cf97c7c4d.png)

The updates section of the book seems outdated, because the last build seemed from more than an hour ago. Even i made changes a couple minutes ago.

![bildschirmfoto vom 2017-12-05 12-37-38](https://user-images.githubusercontent.com/381727/33605351-a9e07722-d9b9-11e7-9a88-cb8158279750.png)

### What is the expected behavior?

Changes in the web-editor are getting (quickly) published in the read-view of the book. If there is a delay, because of publishing or something like that, a short notice would be helpful.

#### For GitBook.com

* **Username:** https://www.gitbook.com/@k00ni
* **Book:** https://www.gitbook.com/book/k00ni/from-barrier-to-icf/details

**Comment by k00ni** [comment]
It would be great if anyone of the gitbook Team could at least give me a hint, what to do here.

**Comment by baotonglu** [comment]
Have you fixed this problem? I'm facing the same problem as you!

**Comment by k00ni** [comment]
No, unfortunately. I got no response from the Gitbook team and did found no solution. I switched to another service, which almost covers all my needs (no git, but coop-functions). Never had such problems with a service.
