### ISSUE TITLE
git clone of a book results in "The requested URL returned error: 500"

### ISSUE THREAD

**Issue by k00ni** [GitbookIO/gitbook#1935]
### What is the current behavior?

* I created an account at gitbook.com using Github OAuth login
* I reset my password
* Running `git clone https://git.gitbook.com/k00ni/from-barrier-to-icf.git` locally results in the error: 
```
  remote: fork/exec /usr/bin/git: cannot allocate memory
  fatal: unable to access 'https://git.gitbook.com/k00ni/from-barrier-to-icf.git/': 
  The requested URL returned error: 500
```
* I tried my username (k00ni) and my email as `username` in git
* I use git with version `2.7.4` locally

### What is the expected behavior?

A simple clone of the repository, without any errors.

I am wondering, if i could register my public key on the server to avoid providing my username/password.

#### For GitBook.com

* Username: https://www.gitbook.com/@k00ni
* Book: https://www.gitbook.com/book/k00ni/from-barrier-to-icf/details

**Comment by andy6804tw** [comment]
same problem

**Comment by inits** [comment]
how to resolve it  ?

**Comment by k00ni** [comment]
I got no response from the Gitbook team and did found no solution. I switched to another service, which almost covers all my needs (no git, but coop-functions).
