### ISSUE TITLE
My account has been suspended

### ISSUE THREAD

**Issue by jzyken** [GitbookIO/gitbook#1940]
Firstly I singed in GitBook with this GitHub account. After entering my email address in corresponding field in settings I was logged out. And now I have no access to my account. I have tried to send a mail to support, but I did not receive a reply. Maybe contact form is broken.

**Comment by DukeGJ** [comment]
my account also suspended,my email : michael.guojing@gmail.com,
i hope someone can solve my problem @weitzman

**Comment by howdoicomputer** [comment]
Yeah, looks like GitBook suspends your account if you change your email address. I have a copy of all my docs locally so I can just move to a different service if needed but dang.

**Comment by Soreine** [comment]
Sorry about that, we have toned down our spam protection as a result.

@jzyken it seems you have made another account. You might want to transfer everything from the now unlocked first account and delete it.

@DukeGJ I have unlocked your account. Thank you for your patience.

**Comment by DukeGJ** [comment]
it's work now, thank you @Soreine

**Comment by Mondo114** [comment]
I am having the same issue
