### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by filipemeneses** [GitbookIO/gitbook#1944]
### What is the current behavior?

- Create a branch `docs`
- Type something (line break is more visible) 
- Save it
- Throws error `Cannot read property 'map' of null

> Using MacOS 10.12.6
> Using GitBook 7.0.12

![image](https://user-images.githubusercontent.com/10226292/34060934-114acd3e-e1cd-11e7-8db4-367dcf35b0f5.png)
![image](https://user-images.githubusercontent.com/10226292/34061077-ae6c02a4-e1cd-11e7-8604-1d26cdee56a0.png)

### What is the expected behavior?

Should've saved my changes and enable the sync option

#### For GitBook.com

Username: filipemeneses
URL: https://filipemeneses.gitbooks.io/fatec-api

**Comment by martinfrnka** [comment]
have exactly the same issue and cannot sync or push to gitbook

**Comment by raojunbo** [comment]
had  your problem solved ?

**Comment by filipemeneses** [comment]
I haven't tried to use the desktop version again, the web version is working fine.

**Comment by martinfrnka** [comment]
My problem was in wrong way to create and sync new book.

The correct way is first to create book online on gitbook and then open desktop client and connect the client to gitbook account. After that, I can see the book in the book list, open the book, edit it and sync changes to gitbook.

This way errors are gone.
