### ISSUE TITLE
Suggestion to enable markdown editor in GitBook Editor from GitBook -> Preferences -> Editor Settings

### ISSUE THREAD

**Issue by dotm** [GitbookIO/gitbook#1955]
### What is the current behavior?
The current edit markdown (enable markdown) is put in the question mark button at the right bottom corner of the screen. And it is very not intuitive.
It has been discussed here: #1721

### What is the expected behavior?
My suggestion is to create a checkbox to 'Enable Markdown Editor' from the menu bar GitBook -> Preferences -> Editor Settings, since that place is more intuitive.
Just put the new checkbox below the checkbox that's already there (e.g. Spellchecking).

**Comment by benjamin-rood** [comment]
Or, alternatively, in **View → Show Raw Markdown**, would be more intuitive, and in line with other editors.
