### ISSUE TITLE
My account has been suspended

### ISSUE THREAD

**Issue by bc-lee** [GitbookIO/gitbook#1956]
I created a account in GitBook using this Github account. I made a book and tried to sync with Github repo, then my Gitbook account is logoutted and it says "Your account has been suspended". Did I something wrong?

Zendesk Ticket No: 7141 but I can't access to the ticket.

**Comment by kreetrapper** [comment]
I had the same issue on the beginning of December. Tried to log in on gitbook.com using my github account, but after some other errors it now always says "your account has been suspended". I have tried the contact form on the gitbook site (request 7044 and 7394), but so far I have received no response. I would be grateful, if someone from gitbook could solve this.

**Comment by cfw011566** [comment]
Hi, My account has been suspended.
I tried to sign in legacy.gitbook.com and get "Your account has been suspended"
Could you help me on this?
