### ISSUE TITLE
Discontinued Editor?

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#1961]
I'm going to talk straight away because I'm quite pissed again. I've been using this editor for a long time and I'm paying 10 dollars a month to help breaking this editor quite often. Now I see this editor is totally discontinued. Am I right? I don't see any branches with new changes at all. Could you confirm you are working to fix issues and make this editor stable?

**Comment by AaronO** [comment]
@cesards No, the editor is not discontinued.

We've spent the past few months working on a major new release ([beta.gitbook.com](https://beta.gitbook.com/)) that ships at the end of the month.

It's the largest release to date, essentially a GitBook v2, with substantial improvements across the board including the editor (bug fixes, reliability and performance improvements, 1st class support for "rich content" [hints, embeds, api methods], ...)

The goal of this release is to provide a much simpler (and more stable) product experience
