### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by eilgin** [GitbookIO/gitbook#1962]
Okay, this issue isn't technical at all but i'm having quite a lot of performance problems regarding the markdown rendering. It takes a **LOT** a RAM (>3GB) to execute your editor and it feels laggy every time i type in a "large" file (a couple of hundred lines).
Moreover file saving takes too much time than necessary (seconds whereas it's only a few kB!).

Besides, It seems to me that the team behind this project does not contribute anymore (see the [graph](https://github.com/GitbookIO/gitbook/graphs/contributors)). If you look at the commit log ([master](https://github.com/GitbookIO/gitbook/commits/master) or even the [4.x.x](https://github.com/GitbookIO/gitbook/commits/4.x.x) branch) you'll only see "bump" commits or doc updates that dated back to early 2017.

It's too bad if this project is dead: it's probably one of the few open-source doc generator from mk with a cool theme.

**Comment by AaronO** [comment]
@eilgin We've been working on a major new release ([beta.gitbook.com](https://beta.gitbook.com/)), shipping at the end of this month.

It includes substantial stability and performance improvements to the editor (and is a much simpler product across the board).

The code for the platform / editor is private, which is why you don't see any public activity.
You can see some public activity on open-source components like `markup-it` ([GitbookIO/markup-it](https://github.com/GitbookIO/markup-it))

Are you using `gitbook.com` ? (or desktop/local ?)

If you have an org on `gitbook.com`, I could give you early access to the new release.

**Comment by eilgin** [comment]
Great news!

We're using gitbook and host it on GCS. We were mainly using the editor but switch back to vim/atom/vscode since it's unusable now.

**Comment by Honghe** [comment]
I use gitbook both private and gitbook.com.
And Meet some bugs of Gitbook Editor. 
Gitbook Editor is pretty.

**Comment by aleung** [comment]
@AaronO You said:
> The code for the platform / editor is private

Does it mean that the new gitbook release will be available only to `gitbook.com` hosting users?

We're using gitbook locally. Will it stays on v3.2.2 forever?

**Comment by tekmosis** [comment]
> @AaronO You said:
> 
> > The code for the platform / editor is private
> 
> Does it mean that the new gitbook release will be available only to `gitbook.com` hosting users?
> 
> We're using gitbook locally. Will it stays on v3.2.2 forever?

They've not made this obvious but they've switched to a SAAS business model and nothing I've read talks about keeping it open source. You should consider this project dead, look into an alternative like Docusaurus.

**Comment by eilgin** [comment]
@tekmosis wow, thanks for the link. This looks promising (and backed by fb). And yeah, it seems there's not so much activity around the open-sourced gitbook :/ (we've switched to docbox since).

**Comment by vladyslav2** [comment]
@AaronO @tekmosis any ideas why you have so many broken links on the github docs?
https://slack.gitbook.com/ - slack link is broken
and basically every second link from https://toolchain.gitbook.com/ is not doing what its suppose to do

are you moved to SASS completely and ditch old stuff?
