### ISSUE TITLE
Unable to upgrade account to new GitHub integration to continue editing book

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#1970]
## Category

maybe a bug, or my mistake doing. About Gitbook Setting for Github

## What is the current behavior?

I see below notice as screenshot 1, but when I push the ```upgrade```, it show me 403 forbidden page as screenshot 2.

![e1.png](https://i.loli.net/2018/01/17/5a5f1573ac72a.png)

![e2.png](https://i.loli.net/2018/01/17/5a5f160f970e0.png)

## What is the desired behavior?

Should not show me any error. 

## Additional information

- GitBook Editor: @cmmei & @tsai1993
- Operating System : Windows 10 and Ubuntu 16.04
- (Web) Browser version : Chrome 63
- (Desktop) Version of the Editor : 7.0.12
- For GitBook.com:
    - my username : cmmei
    - the URL of the book : https://www.gitbook.com/book/lrc/lrc/details

**Comment by norbertfuhs** [comment]
I followed this guide provided by Gitbook to host my book via GitHub on my machine: 
https://help.gitbook.com/books/how-can-i-use-git.html

If you take a look at your [GitHub Settings Applications](https://github.com/settings/installations)

Does it show Gitbook like this?

![github](https://user-images.githubusercontent.com/17197786/37914502-a1903214-3117-11e8-823f-a06ec176f678.png)
