### ISSUE TITLE
Math stylization $$x$$ renders in preview but not in live build

### ISSUE THREAD

**Issue by nmwalsh** [GitbookIO/gitbook#1971]
### What is the current behavior?

When using $$SAMPLE_TEXT$$ format for math stylization, the code builds and renders properly in the live in-browser editor. However, after the changes are published and the build passes, it shows as plaintext with the dollar signs and the sample text.

### What is the expected behavior?

Text with $$EXAMPLE_TEXT$$ format should render with math stylization in the public build of the gitbook.

#### URL for live site with issue:

https://docs.datmo.com/guides/automating-stat-logging.html

(have since remove the $$'s so that they aren't showing on our live docs). Example of the improper rendering attached below.
![screen shot 2018-01-26 at 4 52 24 pm](https://user-images.githubusercontent.com/10050819/35466518-4db0fd5e-02b9-11e8-8e2c-37c8cb8e387a.png)

**Comment by LeBron-Jian** [comment]
I found that  add the katex plugin to mybook config (book.json):
```
{
  "plugins": [
    "katex"
  ],
  "pluginsConfig": {
    "katex": {}
  }
}
```

Run a build with the new config, it should be fine.  But it doesn't work when I use mathjax. Anyway, it's OK now
