### ISSUE TITLE
Sidebar not visible in Github Pages

### ISSUE THREAD

**Issue by prefontaine** [GitbookIO/gitbook#1977]
### What is the current behavior?

I've created my Gitbook using the online tool, and it links and synchs with the gh-pages branch of my repo: 

But when I view my pages version the sidebar is not visible: https://loupdesign.github.io/StoryEngine/

### What is the expected behavior?

I'd expect to see the sidebar, like the version at https://loup.gitbooks.io/storyengine/content/

#### For GitBook.com

@loup is Gitbook username
@loupdesign is GitHub username

**Comment by FichteFoll** [comment]
For me, the sidebar requires JavaScript to be rendered. Check whether you have that disabled.
