### ISSUE TITLE
My GitHub integration is so messed up I don’t even know where to start

### ISSUE THREAD

**Issue by lukejanicke** [GitbookIO/gitbook#1979]
If anyone can help me untangle this mess, I will be forever in your debt. I have a personal account and an organisation on both GitBook and GitHub. The names match on both sites (**lukejanicke** and **qiaodao**). I only want to connect my GitBook organisation to my GitHub organisation.

### Personal settings

- I am the only owner of my organisation.
- Installed GitHub apps — none
- Authorized GitHub apps — none
- Authorised OAuth apps — GitHub Desktop, Netlify (no GitBook)

### Organisation settings

- Third-party access — GitBook approved (can’t delete the record, can only GRANT/REVOKE)
- Installed GitHub Apps — none
- Developer settings
  - OAuth apps — none
  - GitHub apps — none

### Personal settings

*No relevant settings.*

### Organisation settings

- GitHub
  - Books: “GitBook is ready to sync your books with GitHub.”
    - After clicking **Create a book from GitHub**, the _Create a new book_ page has an **Install GitHub integration** blue button, which leads back to the GitHub settings page.
  - Integration: “Installed on the **qiaodao** GitHub account to host and edit your books on GitHub.”
  - Danger Zone: Clicking on **Uninstall GitHub integration** leads to a GitHub 404 page.
- People: “This organization is linked to the qiaodao GitHub organization. Existing and new GitBook users will be automatically added as collaborators.’
  - Clicking on **Unlink from qiaodao** redirects me back to the GitHib settings page (above) where the **Uninstall GitHub integration** button still leads to a GitHub 404 page.

What a mess. I have to abandon GitBook if is this is not resolved. I need to move my online books to a GitHub repository for collaboration purposes.

**Comment by norbertfuhs** [comment]
I also host my Gitbook via GitHub the only way I could get I working correctly with the Editor was following this guide provided by Gitbook:

[How can I use Git to update my book? ](https://help.gitbook.com/books/how-can-i-use-git.html)

Maybe this helps if not not please comment.
