### ISSUE TITLE
Gitbook is deprecated now?

### ISSUE THREAD

**Issue by blling** [GitbookIO/gitbook#1994]
There is no active matainable, is gitbook deprecated for now?

**Comment by timaschew** [comment]
duplicate https://github.com/GitbookIO/gitbook/issues/1808

**Comment by FibreFoX** [comment]
And even on the other issue, no progress visible.

**Comment by norbertfuhs** [comment]
As far as it looks Gitbook isn't depracted at all.

The team behind Gitbook is working on Version 4 and not all repos are public as mentioned in in #1808 

If you installed the [gitbook-cli](https://github.com/GitbookIO/gitbook-cli)

And  run gitbook ls-remote

You can check and see the latest Gitbook Version is pre : 4.0.0-alpha.6 which isn't released yet.

**Comment by aleung** [comment]
The open source GitBook has been deprecated. It's now [legacy](https://legacy.gitbook.com/).
