### ISSUE TITLE
The book is not indexed by crawlers

### ISSUE THREAD

**Issue by maksimyurkov** [GitbookIO/gitbook#2003]
### What is the current behavior?

The contents of the book are missing in the search result of Google.
(book published ~2 month ago)

### What is the expected behavior?

Availability the content of the book in the search result Google.

#### For GitBook.com

Max
[https://www.gitbook.com/book/maksimyurkov/web-components-in-webtutor/details](https://www.gitbook.com/book/maksimyurkov/web-components-in-webtutor/details)

**Comment by norbertfuhs** [comment]
Hi first I would try to follow  [Search Engine Optimization: improving your web profile](https://tomcam.gitbooks.io/gitbook-tutorial/content/seo.html) provided by Gitbook.

There is also an plugin to customize the keywords of your Gitbook content
[easyseo-7dtime](https://plugins.gitbook.com/plugin/easyseo-7dtime)

Maybe this helps to solve your issue.

**Comment by maksimyurkov** [comment]
Hi, norbertfuhs! Thanks for the info.

In search of a solution to the problem, I added a book in Google Webmasters.
And there saw such a picture.

![](https://imgur.com/a/UOdRJ)

That is, Google went to all pages, but did not index them, because in response he received a header(X-Robots-Tag: noindex) indicating that the page should not be indexed.
[Read more here.](https://support.google.com/webmasters/answer/93710?hl=en)

I checked and really, GitBook gives this header(noindex) on every page. If you go back to the page again (F5), the header disappears, but after a while it reappears.

![](https://imgur.com/a/GKTpc)

In general, the question is why the server sends this header. Something tells me that I'm not alone in this problem.

**Comment by maksimyurkov** [comment]
ALARM !!!

I decided to check the availability of this header(X-Robots-Tag: noindex) in other books.
I check books that was created 1 week, 1 month, 1 year, 2 year / ago. (here i stopped [https://www.gitbook.com/explore?page=5063&lang=all](https://www.gitbook.com/explore?page=5063&lang=all))
All that books have now header(X-Robots-Tag: noindex).

That is, all books from this period of time (more than half of all books) are not indexed by search engines and, accordingly, are absent in search results.
Only the cover is indexed, all other pages are not.

I do not know if any of the developers of GitBook read Issues now, but if anyone can pass, then pass on this information, since this problem leads to very serious consequences, or rather has already resulted, since half of the content is simply missing from the search results now.

**Comment by norbertfuhs** [comment]
Trust me they read the issues.. the team behind Gitbook is currently working hard on their next release [https://beta.gitbook.com/](https://beta.gitbook.com/) 

They look on issues with 3.2.3 but currently they have lot of work todo..
