### ISSUE TITLE
github sync gitbook

### ISSUE THREAD

**Issue by BD7IWD** [GitbookIO/gitbook#2010]
I was able to set up gitbook to connect to github but the book could not be synchronized. Github is updated, gitbook is not updated synchronously, what is the reason?

**Comment by jfq3** [comment]
I have the same problem, even after forcing an update.

**Comment by ssyijiu** [comment]
me too.

**Comment by MaicolBen** [comment]
how can I force synchronization?

**Comment by duncanhunter** [comment]
any updates?
