### ISSUE TITLE
SUMMARY include files outside root folder

### ISSUE THREAD

**Issue by prid** [GitbookIO/gitbook#2015]
I would like to have a summary file like follows:

```
# Summary

* [First chapter](../../draft/1.md)
* [Second chapter](../../draft/2.md)
```

Now the bug is that the built files are also outside the `_book` folder because of the relative link. 

Is there anyway to escape `../` with symbols like `_/` so to fix the problem?

The reason of doing this is that, with this functionality (referring to files outside root folder) supported, I can have multiple books using shared markdown source files (I like to put all my markdown files in one single folder and sort the structures using SUMMARY.md instead of filesystem).

**Comment by istiti** [comment]
i can't unserstand your problem

**Comment by qx-juilliard** [comment]
Try building a book that includes files in parent folders relative to SUMMARY.md

**Comment by istiti** [comment]
@qx-juilliard you speak to me ? 

 is there repro of this issue

**Comment by istiti** [comment]
i see your problem thanks and effectively it not works.
i think this is by design and your requirement is another way to do it.

Did you tried multilingual approach of gitbook but adapt it in your usecase.

(imo I prefer filesystem structure instead all in one folder)
