### ISSUE TITLE
In China，can not sign in to www.gitbook.com with GitHub

### ISSUE THREAD

**Issue by l10178** [GitbookIO/gitbook#2020]
This is not a bug. but...

### What is the current behavior?
In China, when sign in to GitBook , you will see the error message, "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
Click sign in with "GitHub" button, nothing happends.  Please see the picture.
![can_not_sign](https://user-images.githubusercontent.com/18532857/38765513-b8349f0e-3ff5-11e8-8cc0-008d2e55bf3e.PNG)

Can not access www.googleapis.com in China.

### What is the expected behavior?
Do not use googleapis. 这真不是一个bug，但是希望考虑下中国用户, please。thank you.

**Comment by wanghaifen** [comment]
how to deal it that you can sign in whit github?
