### ISSUE TITLE
Unable to Link Gitbook to Github's organization/repo

### ISSUE THREAD

**Issue by desimaniac** [GitbookIO/gitbook#2021]
Unable to Link Gitbook to GitHub's organization/repo. 

Get's stuck at the `Exporting content (0%), it may take a few minutes...`. 

![image](https://user-images.githubusercontent.com/5501908/38781431-f592f0f8-40a9-11e8-9fa1-7c021455c146.png)

Left it there for a greater part of the day and it never movies. 

Tried Unlinking Github and retrying. Tried multiple browsers. Also tried deleting and recreating the repo. Permissions are granted (in Github), so not sure why it's stuck there. 

It only adds one initializing readme.md file to the repo.

**Comment by jackalsin** [comment]
Almost the same situation. I stuck in the
>  *Importing* content

**Comment by desimaniac** [comment]
I've since learned that it will do that if there are no edits. So if you edit a page and full it in, it souls start syncing.

**Comment by jackalsin** [comment]
@desimaniac What do you mean by **So if you edit a page and full it in**?

Do you mean I cannot import the content from an existing GitHub Repo to Gitbook?

**Comment by chryzsh** [comment]
@desimaniac's solution worked for me. I just had to make one edit and save, then the importing of a Github repo to my book worked.
