### ISSUE TITLE
Where can I find my "old" gitbooks?

### ISSUE THREAD

**Issue by tcloaa** [GitbookIO/gitbook#2026]
Besides `legacy.gitbook.com.`, where can I find my gitbooks on the new webpage?

Or it is totally a different project?

**Comment by chris-trotter** [comment]
Indeed I have also have this question. Not intuitive at all. Seems there's been no migration over to the new platform. All old projects have been mothballed at legacy.gitbook.com. I unfortunately can't understand how to even use the new product.

**Comment by AaronO** [comment]
@tcloaa @chris-trotter We're working on a migration path for v1 users with single-user accounts.

(v1 organizations can't migrate their content over, but we haven't yet implemented something for single-user accounts)


In the meantime, if you have a single-user account, you should continue using [legacy.gitbook.com](https://legacy.gitbook.com)

**Comment by tcloaa** [comment]
Hi, Any update on the **migration path** for v1 users?
