### ISSUE TITLE
Error: EPERM: operation not permitted, open/mkdir 

### ISSUE THREAD

**Issue by localdevm** [GitbookIO/gitbook#2033]
### What is the current behavior?

**System** : Windows 10 Education 64-bit (10.0, Build 16299)
**Gitbook** : v3.2.3
**Node**:  v8.11.1

Upon issuing the `gitbook serve` command, the gitbook gets served to localhost:4000. Upon saving any changes made to the gitbook files, gitbook crashes while writiting the changes to the /book folder.

### What is the expected behavior?

The changes are written to the /book folder and gitbook automatically re-serves itself.

#### For legacy.gitbook.com
Private repository.

**Comment by themaawaa** [comment]
### Temporary fix/hack

1. Delete `book.json` and `/book` files present in the repository.
2. Upon serving gitbook for the first time, delete the generated `/book` folder.

Note: this has to be done everytime the `gitbook serve` command is issued.
