### ISSUE TITLE
File edition / deletion

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#2034]
### Behaviour

There is no way of editing/deleting files/sections of the book.

![screen shot 2018-05-02 at 12 11 29 pm](https://user-images.githubusercontent.com/1536079/39535470-fb48b77a-4e01-11e8-8cc4-8741791c083f.png)

You can only edit the page's name.

### Expected

As it was possible in the old editor, I'd like to be able to edit/delete file names.

**Comment by AaronO** [comment]
@cesards Once you're in edit mode, you can easily change any page's path (essentially renaming the file):

![image](https://user-images.githubusercontent.com/949223/39535662-cb3d09e0-4e34-11e8-938e-a90bc96ed7c9.png)

**Comment by cesards** [comment]
@AaronO I was going to close the issue by myself. I didn't see that option before, but you were very fast responding. Thank you so much!!
