### ISSUE TITLE
Code line shortcut clash

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#2035]
### Behaviour

The shortcut linked to "code line" usage in the previous Gitbook version was `Command + Shift + 9`. In the current one is `Command + Shift + 6` which clashes with Mac OS screenshots shortcuts.

<img width="660" alt="screen shot 2018-05-02 at 3 49 40 pm" src="https://user-images.githubusercontent.com/1536079/39545860-79b09286-4e20-11e8-9fd6-0af8933ad4cd.png">

![screen shot 2018-05-02 at 3 43 57 pm](https://user-images.githubusercontent.com/1536079/39545892-973d43a8-4e20-11e8-9712-bf5a09cebf14.png)

### Expected

As an advanced MacOS user and a developer, It would be easy just disabling that shortcut from the Mac preferences (moreover it's not very useful), but maybe you should consider going back to the previous shortcut in order to avoid the annoyance of some Gitbook users.

Thank you in advance.

**Comment by chryzsh** [comment]
There is a difference between code line and code block here too. It seems that the clode block functionality was removed in the new version. At least cmd+shift+9 does nothing, even after disabling the hotkey in MacOS.

**Comment by cesards** [comment]
@chryzsh My mistake. I meant to say code line instead of a code block. 

> Edit: Turns out that reading the documentation can be a good idea. ``` + enter to make a code block.

It turns out that you should try to be a better professional. I recommend you start reading **[this](https://en.wikipedia.org/wiki/Code_of_conduct)**.

**Comment by chryzsh** [comment]
Haha I’m sorry. In retrospect I see how I come across as rude towards you. Trust me, it was purely ment as a reflection upon myself. :) hope we’re all good

**Comment by cesards** [comment]
No worrites 👍 Forgiven you are ;-)
