### ISSUE TITLE
in China,Gitbook edit can not sign up

### ISSUE THREAD

**Issue by ciyeer** [GitbookIO/gitbook#2044]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).

### What is the expected behavior?

How do you think, or how would you like it should behave.

#### For legacy.gitbook.com

Provide, if possible, your username and the URL of the concerned book.

----

The GitBook Team

**Comment by Javioustlj** [comment]
I tried to sign up with my github acount,; A network error (such as timeout, interrupted connection or unreachable host) has occurred.

**Comment by HaidongSong** [comment]
I tried to sign up with my github acount,; A network error (such as timeout, interrupted connection or unreachable host) has occurred.
