### ISSUE TITLE
Gitbook Editor can not login with github?

### ISSUE THREAD

**Issue by Pasoul** [GitbookIO/gitbook#2050]
### What is the current behavior?

when i try to login with github, it warns  the following：

Please note that GitHub no longer supports your web browser.
We recommend upgrading to the latest Google Chrome or Firefox.

so It makes me unable to click the authorization button。
`gitbook -V 7.0.12`
`os -V  10.12.6`

**Comment by HaidongSong** [comment]
# 一样的效果我，难道是因为gitbook官网更新，导致，这gitbook效率也太低啦

**Comment by MichaelTuchman** [comment]
I went to gitbook.com on Chrome and tried to login with my github username and password, but the prompt just kept repeating 'method requires authentication'.  Even when I try to create a new account and password, it gives me the same error, which it shouldn't for a new account.

**Comment by Henry-Cheng** [comment]
Same here. The latest gitbook editor version is built on 17 March 2017.
Is this editor still maintained?

**Comment by YoungJaeChoung** [comment]
I read the article about update (https://docs.gitbook.com/v2-changes/important-differences)

Desktop app
The new version does not currently have a desktop editor app. Our efforts are concentrated on the web version so we can focus on quality and reliability first. We are considering releasing a Desktop app in the future, but we have no public release-date at this time.

(I also really want to use desktop app, editor)
