### ISSUE TITLE
Import from Github - hangs

### ISSUE THREAD

**Issue by psychemedia** [GitbookIO/gitbook#2051]
### What is the current behavior?

On using gitbook.com, import from github starts to quickly import files, then hangs with a message of the form `Importing content (95%), it may take a few minutes...`. (Percentage given is typically in the 90s.)

If I disconnect the repo then reconnect it, the same thing happens again.

### How do you think, or how would you like it should behave.

Import should complete, not hang

**Comment by DannyBen** [comment]
> **How do you think, or how would you like it should behave.**
> Import should complete, not hang

Heh :smile: Sticking it to the "Issue Templates" are we?
I am also experiencing this from time to time - for me it got stuck on 0%.
