### ISSUE TITLE
Cannot log into new gitbook webiste

### ISSUE THREAD

**Issue by MichaelTuchman** [GitbookIO/gitbook#2075]
Logged with Chrome to gitbook.com.  It did not accept my username/password for github when I clicked the button 'Login with GitHub'.  Same for  the button 'Login with Google'

**Comment by YoungJaeChoung** [comment]
me too. I tried same action on Chrome, Explore, and Firefox.

The buttons 'login with google, github and gitbook account' all failed.

(But in the same day  with other computer, I succeed login)
