### ISSUE TITLE
Gif support in the new editor

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#2081]
Copying and pasting a gif in the editor and not being animated I guess it's kind of understanding, but the gif is not being animated after changes are saved and published.

I guess the worst part of the issue is that whenever we introduce an image to the editor since we are not able to introduce external sources  `![ ](http://externalsource.com/image.gif)` and the editor copies the image locally, it's a destructive change, which means that if anytime this issue is fixed, I have to go back and copy paste all my gifs again.

Here is a screen recording of me saving changes in my book and going back to the page in "preview" mode:

![2018-07-02 09 40 52](https://user-images.githubusercontent.com/1536079/42167499-3ff9bd7e-7ddc-11e8-9788-0ec3d4a4d5ba.gif)

I guess the expected behavior here is to show the gifs properly.

Thanks!

PS: I found an issue opened in relation to this topic, but since I was using the new web editor I thought it was a different case scenario:

https://github.com/GitbookIO/gitbook/issues/1954

**Comment by AaronO** [comment]
@cesards If you're copy/pasting in the browser it won't work, because the browser only copies the current "frame" of your GIF (which is annoying for other apps like Slack and co).

Uploading GIFs work if you drag and drop the file from your local PC or upload it using the command palette.

**Comment by cesards** [comment]
Gotcha. 

I created the issue since some live preview markdown editors for mac that I use, allow to do that.
