### ISSUE TITLE
Template render error: unknown block tag: hint

### ISSUE THREAD

**Issue by rimduhui** [GitbookIO/gitbook#2085]
gitbook version
<img width="699" alt="2018-07-05 5 54 41" src="https://user-images.githubusercontent.com/17869203/42313022-b011d658-807c-11e8-95e8-32fca50eb31b.png">

error message
<img width="669" alt="2018-07-05 5 54 53" src="https://user-images.githubusercontent.com/17869203/42313027-b2b3da64-807c-11e8-9852-a13a8b057b10.png">

I worked my documents only at web editor. As I need to convert my doc to pdf for printing, I cloned my doc to local. Every commands caused errors like second picture.

Is it possible to edit local??

Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).

### What is the expected behavior?

How do you think, or how would you like it should behave.

#### For legacy.gitbook.com

Provide, if possible, your username and the URL of the concerned book.

----

The GitBook Team

**Comment by xingjianhui** [comment]
I have the same error
```
$ gitbook build
info: 15 plugins are installed
info: 7 explicitly listed
info: loading plugin "redirect"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 68 pages
info: found 0 asset files
error: error while generating page "introduction.md":

Template render error: (/apps/growingio-docs/introduction.md) [Line 11, Column 2]
  unknown block tag: page
```
if you have this problem solution,
please give me solutions.
thanks

**Comment by ipy** [comment]
This can be solved by adding the hints plugin.

**Comment by akiko-pusu** [comment]
@ipy Thanks above information! 
I'm new of Gitbook. I saw the same situation and reached at this topic with googling.

**Comment by mitjafelicijan** [comment]
> This can be solved by adding the hints plugin.

How do you add hints plugin?

I did the following and i still have this problem.

```
gitbook install
info: nothing to install!
```

![screenshot 2018-12-10 at 02 11 39](https://user-images.githubusercontent.com/296714/49705759-0141a600-fc21-11e8-8b09-444b9b21fc9f.png)

**Comment by WujieRen** [comment]
@mitjafelicijan You need to add a file named book.json under the root path of your book, and edit the file to  add the following：
`{
    "plugins": ["hints"]
}`
[More Infomation](https://plugins.gitbook.com/plugin/hints)
