### ISSUE TITLE
Configure different theme

### ISSUE THREAD

**Issue by BjoernSchotte** [GitbookIO/gitbook#209]
Add the possibility of configuring a custom theme during build process / with book.json.

Goal: to create custom site layout themes for a book.

**Comment by xtrasmal** [comment]
@SamyPesse  Ok I will not create another theme and will stick what is there right now. Is there a way to change the "Table of contents" to "Inhoudsopgave"? The audience, in this case, is Dutch.

**Comment by AaronO** [comment]
@xtrasmal Yes, the easiest and best way for everyone to benefit would be to provide a translation :)

The default theme has already quite a few translations provided by the community: https://github.com/GitbookIO/gitbook/tree/master/theme/i18n

Send us a PR with the dutch translation in a new `nl.json` file and once that's merged `Table of Contents` (and other parts) will automatically be translated for books written in dutch.

**Comment by martindale** [comment]
Instructions on how to configure a theme properly aren't clear.  Can clarity be provided?

**Comment by martindale** [comment]
After several concerted efforts to customize the theme, I've created #2055.  This is blocking for us, hoping for a resolution.
