### ISSUE TITLE
Big red security warning in Chrome

### ISSUE THREAD

**Issue by Koslun** [GitbookIO/gitbook#2095]
### What is the current behavior?
When loading anything on the `www.gitbook.com` domain, excluding sub-domains, Chrome instead shows a big red screen that the site is dangerous, blocking any access by default. Where you have to do a few clicks to actually come through.

Here's the Google report: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.gitbook.com%2F&hl=en-US. At the time of writing the stat us "This site is unsafe".

Present on Chrome for Windows, Mac OS X and Ubuntu on the same network here in Stockholm, Sweden. Using Chrome for Android it still seems to not mention anything.

### What is the expected behavior?

No big red warning.

**Comment by jamcha-aa** [comment]
The same problem happened to Firefox and Vivaldi. Reports are also the same with @Koslun.

**Comment by Soreine** [comment]
Thank you for reporting this. We are aware of the security warning provided by Google. It was triggered by a few books created by malicious users, containing spam content and links to unsafe sites. 

We've blocked the books and users in question. We've also reached out to Google to get this fixed, it's under review. The situation should come back to normal soon.

The GitBook platform as whole is still safe to use. And it’s safe to visit the great majority of the books on GitBook as well. We take this opportunity to remind everyone that the content of books hosted on GitBook come from our users, and that you, as a reader, should stay attentive to the legitimacy of the books you browse, just like you would do on the rest of the Web.

**Comment by cwbuege** [comment]
Just throwing a comment out there so when it's fixed and this thread is updated, I'll get notified and can check out gitbook.com.

**Comment by jamcha-aa** [comment]
Warnings disappeared. Thank you for swift responses.

**Comment by Koslun** [comment]
@cwbuege you could also just hit the subscribe button on the issue and throw in a 👍 emoji to other comments to show interest.

Anyway, also see that it is resolved. Thanks for fast response here.
