### ISSUE TITLE
New gitbook has a huge lag when typing ona mid size file.

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#2097]
### Current behavior

A huge lag when typing on the editor. It makes practically impossible the edition.

Here is a gif (it's a long gif, so you can actually notice the delay)

![2018-07-19 16 27 49](https://user-images.githubusercontent.com/1536079/42968603-c668cc9a-8b71-11e8-8193-2a4880e2c174.gif)

The file I'm editing has 1200 lines, which is not very much. There are only 2 images included in the preview file. The file size is 35Kb.

### What is the expected behavior?

Not having this lag, which makes the edition impossible.

I'm currently using the new web editor, but the problem is linked to a problem with the old one as well"https://github.com/GitbookIO/gitbook/issues/1686

**Comment by Crackvignoule** [comment]
I'm experiencing terrible freezes every ~30s it's really annoying.

**Comment by Crackvignoule** [comment]
This is absolutely not completed btw, shame on you
