### ISSUE TITLE
I cant login gitbook.com through GitBook Editor in windows

### ISSUE THREAD

**Issue by 0xtaosu** [GitbookIO/gitbook#2103]
I wanna get the GitBook Editor in windows so I download from github.Howerver,I cant login my gitbook.com account after I submit.

**Comment by lustigdev** [comment]
Same on Mac

**Comment by l10178** [comment]
大概是被墙了吧

**Comment by lustigdev** [comment]
My issue was caused by 2 Factor Authentication. 

Instead of entering the password when prompted, enter the token provided by Github. 

This was not caused by Gitbooks.
