### ISSUE TITLE
Add ability to move page groups

### ISSUE THREAD

**Issue by kettanaito** [GitbookIO/gitbook#2114]
Hi. This is not a bug, but rather a missing functionality report.

### What is the current behavior?

At the moment there is no way to move/change order of page groups.

This limits the comfort when using GitBook, as in order to move groups now you need to manually create/delete them until you get the desired result.

### What is the expected behavior?

I think it is reasonable to have an ability to move page groups on demand.

**Comment by timothylong** [comment]
I would also add that moving existing pages into new or existing groups is a reasonable expectation as well. Currently, you need to recreate pages in the group you want it in.

**Comment by kettanaito** [comment]
I believe the latest release includes reworked mechanics of page groups, and supports moving page groups.
