### ISSUE TITLE
Searching after migration does not seem to work

### ISSUE THREAD

**Issue by joachimjonkers** [GitbookIO/gitbook#2118]
### What is the current behavior?
Searching on docs.chatlayer.ai returns no results, no matter what the query is. Even if it's clearly included in a page title / content. 
This behaviour has occurred since we've moved from legacy.gitbook.com.
I'm not getting any in-browser console errors. The issue seems to be present on multiple OS's and browsers.

### What is the expected behavior?
For the search to return the relevant results

**Comment by travis5491811** [comment]
I also noticed this while checking out the project to use with a opensource book I'd like to write. I tested it with the "Learn Javascript" on the readme page. I clicked the link to visit the example, clicked read, and then searched for the word `loosely` from the first page. The word can't be found if i'm on the "Types" page where it first occurs and it can't be found if I'm on any other page.
