### ISSUE TITLE
Unauthorized New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

### ISSUE THREAD

**Issue by NeoTim** [GitbookIO/gitbook#2119]
Unauthorized
New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).

### What is the expected behavior?

How do you think, or how would you like it should behave.

#### For legacy.gitbook.com

Provide, if possible, your username and the URL of the concerned book.

----

The GitBook Team

**Comment by kevinojt** [comment]
I'm new to Gitbook. I tried to sign in with my Github account and got the 401 message.
Chrome 69.0.3497.100 in MacOS 10.14.
https://legacy.gitbook.com/book/bagder/http2-explained/details

**Comment by luffyzhao** [comment]
gitbook -V

**Comment by luffyzhao** [comment]
I used  Google account appeared 401 when I logged in
i used my gitbook account  appeared "Invalid username/email or password"  when i logged in

gitbook -V
```
CLI version: 2.3.2
GitBook version: 3.2.3
```

**Comment by jankalfus** [comment]
+1 I just created an account on the new version of GitBook and I'm getting this error message. This really sucks as I'm unable to add any comments in the docs here: https://basarat.gitbooks.io/typescript/content/docs/getting-started.html When I click the "Sign in to comment" link, I'm getting redirected to legacy.gitbooks.com. Selecting "Sign in with Google" results in the following error message.

![image](https://user-images.githubusercontent.com/12714276/50425794-c88b0900-087d-11e9-810a-542425847117.png)

**Comment by dongyuanxin** [comment]
+1. I'm new to Gitbook. I tried to sign in with Google account but got 401.
And error message is: 
```
Unauthorized
New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com
```
And use it on windows 10.

**Comment by NY1024** [comment]
I have encountered the same problem, has the problem been solved yet?

**Comment by MorryNiu** [comment]
same problem here, any way to solve it?

**Comment by hingWHT** [comment]
same problem

**Comment by chaihongjun** [comment]
sign in with github
yeah the same:
![qq 20190118180056](https://user-images.githubusercontent.com/12774598/51379732-0dd3eb00-1b4b-11e9-8a18-48aad7b3ca97.png)

**Comment by DRoppelt** [comment]
Same here. 

Account on www.gitbook.com exists, but I cannot use that account to login into legacy.gitbook.com. Trying to login via "use github" leads to the 401 with a hint to www.gitbook.com.

**Comment by qianshanding** [comment]
same here.

> CLI version: 2.3.2
> GitBook version: 3.2.3

> 10.14 (18A391)

**Comment by gt510** [comment]
The same.

**Comment by HuangZhenyang** [comment]
same problem.

**Comment by wow-222** [comment]
still the case(New accounts should be created on the new version of GitBook)

**Comment by ACommonChinese** [comment]
same case

**Comment by unlimitbladeworks** [comment]
same problem

**Comment by croakzh** [comment]
same case

**Comment by dariushazimi** [comment]
same problem
os: macOS Mojave
git version 2.19.0
Created a new account on gitbook.com site.
Logged in succesfully on gitbook.com
downloaded the client.
Can't login.
Tried to login with github and google but both have the same issue.

`401
Unauthorized
New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com`


![image](https://user-images.githubusercontent.com/622048/54960240-38b73280-4f32-11e9-8b2e-2d37936cd3bd.png)

**Comment by dariushazimi** [comment]
Has anyone been able to figure out what the issue is?
same problem
os: macOS Mojave
git version 2.19.0
Created a new account on gitbook.com site.
Logged in successfully on gitbook.com
downloaded the client.
Can't login.
Tried to login with github and google but both have the same issue.

401 Unauthorized New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

**Comment by MeowsQAQ** [comment]
> sign in with github
> yeah the same:
> ![qq 20190118180056](https://user-images.githubusercontent.com/12774598/51379732-0dd3eb00-1b4b-11e9-8a18-48aad7b3ca97.png)

+1

**Comment by aagz** [comment]
Same problem.
logged through github.
Verified account with my phone.
![image](https://user-images.githubusercontent.com/46520039/55388639-50974380-553c-11e9-8285-e2215062ce35.png)

**Comment by huangtingting827** [comment]
same case
