### ISSUE TITLE
Can't log in, the error is 401 -- "Unauthorized"

### ISSUE THREAD

**Issue by SanDiegoXu** [GitbookIO/gitbook#2125]
When I want to log in with my Github on  Gitbook Editor, the error is coming:

`
401
Unauthorized
New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com
`

I have sign in with my Github in `https://www.gitbook.com/`, why I can't log in on Github Editor?

Plelease give me some suggestions.
Thank you.

**Comment by anselleeyy** [comment]
I have encountered the same problem too. Did you find any ways to solve that?

**Comment by MicroKibaco** [comment]
I have encountered the same problem too. Did you find any ways to solve that?

**Comment by luffe0601** [comment]
the old gitbook is https://legacy.gitbook.com/
the new gitbook is https://www.gitbook.com/book/

when i use GitBook Editor ,it login  legacy.gitbook,
a bad way T_T GitBook Editor not support new gitbook

if you want to use GitBook Editor to edit a book on offline, try other way

**Comment by MicroKibaco** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
