### ISSUE TITLE
what theme does docs.gitbook.com use?

### ISSUE THREAD

**Issue by 5onion** [GitbookIO/gitbook#2135]
I like the right navigation  "CONTENT" on https://docs.gitbook.com.
What theme does docs.gitbook.com use?  Is it open source? thanks.

**Comment by ogxn** [comment]
This is the main theme for the closed-source **v2** Gitbook.  If you want to use it, you'll have to wait until they open-source it or have them host it.  You can go [here](https://www.gitbook.com)...
