### ISSUE TITLE
where is book.json

### ISSUE THREAD

**Issue by drinkingcode** [GitbookIO/gitbook#2143]
#### environment
```
Nodejs version : 10.12.0
Cli version : 2.3.2
Gitbook version : 3.2.3
```

#### question
There was not `book.json` in current dirctory after i type `gitbook init`. Just only found `README.md` and `SUMMARY.md`. So where is `book.json` ?

----
Is there anyone who meet the same problem ?

**Comment by bestony** [comment]
the `book.json` need create by manually

**Comment by drinkingcode** [comment]
@bestony thanks for your tips
