### ISSUE TITLE
Sidebar - closing subchapters

### ISSUE THREAD

**Issue by 13abylon** [GitbookIO/gitbook#215]
Will it be possible to close the subchapters in the sidebar?

E.g. We have Chapter number 1,2 and 3. If I click on 2 then and only then it will be possible to see the subchapter 2.1, 2.2 and so on.

I think it would be nicer to watch if you have a large documentation.

**Comment by 13abylon** [comment]
I would also love to see this plugin. 
I don't know if it is written, because the plugin page is broken :(

**Comment by SamyPesse** [comment]
I'll fix this in the coming week, in the mid time the list is available on NPM: https://www.npmjs.com/search?q=gitbook
