### ISSUE TITLE
Bug: GitBook Web Site is Died for Eastern Europe and Russia

### ISSUE THREAD

**Issue by SmolinsCo** [GitbookIO/gitbook#2152]
**Another users with same problem:** https://gitbook.canny.io/feature-requests/p/fix-for-russian-users

I am created my space on https://www.gitbook.com/ from PC in another country. Now my customers want to open it from their PCs and they can't. Pages are loading, but their content don't. 

I researched the problem. It is with CDN. blobscdn.gitbook.com domain points to 46.101.223.47 which is unavailable in Easter Europe and Russia. 

# Solution for readers
Add the following record:
```
138.68.13.200 blobscdn.gitbook.com
```
to end of *C:\Windows\system32\drivers\etc\hosts* file

After it, page content loading!

But many customers without IT skills can't do such thing.
**I love GitBook. I want use GitBook. I planning buy it for 35$/month, in future - migrate to 300$/month (to achieve the priority support).**
I will be SHOULD use another service if problem willn't be fixed.

# Possible solutions for GitBook team
- Stop using 46.101.223.47 server
- Use this server, but another IP instead of 46.101.223.47
- Allow us to register on https://legacy.gitbook.com

**Comment by ubercola** [comment]
Gitbook, please fix it. Now for my customers i use legacy static html generator (gitbook-cli) and publish docs at my own host.

IP 46.101.223.47 can be pinged, but not availabe on http/https

**Comment by mashdot** [comment]
Just discovered this issue, when a new client reported they could not see the documentation. Rather embarrassing for me, and not sure if I want to try and get the client to fiddle around with their hosts file.
