### ISSUE TITLE
gitbook pdf cause of svg data

### ISSUE THREAD

**Issue by Anudorannador** [GitbookIO/gitbook#2154]
I know that if inserting svg image file, and want to export pdf, first is that convert svg to png via `svgexport`.

BUT, I use the plugin `mermaid-cli`,  this plugin will generate `img` tags in HTML files under `_book` folder. The tag is some like:

```html
<img src="data:image/svg+xml;base64,PHN2ZyBpZD0ibWVybWF ... C9nPjwvc3ZnPg==">
```

Using raw data...

SO, when I use the command `gitbook pdf ./ output.pdf`, an error occurs:

```
error: error while generating page "FlowSequenceDiagram.md":

Error: Source is not a PNG data-uri
Error: Source is not a PNG data-uri
    at Object.convertInlinePNG (/home/anudorannador/.gitbook/versions/3.2.3/lib/utils/images.js:43:66)
    at /home/anudorannador/.gitbook/versions/3.2.3/lib/output/modifiers/inlinePng.js:34:31
    at /home/anudorannador/.gitbook/versions/3.2.3/lib/utils/fs.js:112:16
    at _fulfilled (/home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:834:54)
    at /home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:796:13)
    at /home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:604:44
    at runSingle (/home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:137:13)
    at flush (/home/anudorannador/.gitbook/versions/3.2.3/node_modules/q/q.js:125:13)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

is there some plugin or what i can do during the runtime so that convert the raw svg data to png ???

**Comment by Anudorannador** [comment]
Resolved.

**Comment by Anudorannador** [comment]
@shrmrf  here is my [`Dockerfile`](https://gist.github.com/Anudorannador/f7aebde46c4212264b37661860274582) and [`gitlab-ci.yml`](https://gist.github.com/Anudorannador/f8fc29ad2d93268a24a94f0d3a6d8fb4) to compile gitbook to pdf.

I think that you should read them, and modify something to adapt.

**Comment by shrmrf** [comment]
@Anudorannador thanks for the `Dockerfile`... Do you have an idea of the _real_ cause of the issue?

I resolved it by installing tools as a `sudo` _user_ in my [`Dockerfile`](https://github.com/shrmrf/gitbook-docker/blob/develop/Dockerfile). I was getting strange errors with `phantomjs` installations otherwise.

_I'm not even a novice in the `node`/`npm` ecosystem, so I might've done something really stupid in my `Dockerfile` above_

**Comment by Anudorannador** [comment]
@shrmrf If you won't export PDF, anything is OK with gitbook.

*BUT* if you want to export PDF, gitbook doesn't support SVG, so `svgexport` is needed. It's a very bad solution, because the PNG created by `svgexport` is very fuzzy and, as you know, png is not kind of vector diagram ...

then `svgexport` need [`phantomjs`](https://github.com/ariya/phantomjs) which is deprecated! So when you install `svgexport`, npm will figure out that `phantomjs` is deprecated and prevent installing otherwise you must pass the parameter `--unsafe-perm` to force install, that's why I use the command to install it:

```
RUN npm install -g svgexport --unsafe-perm
```

Besides that, calibre-ebook is used for converting html to PDF. Let's say, first gitbook converts the Markdown files to HTML files, and then converts all SVG files to PNG files, and last converts them to PDF via calibre-ebbok.

BTW, [`ebook-convert`](https://www.npmjs.com/package/ebook-convert) that you mentioned is used under MAC(not by Docker env).

It seems that Gitbook is going to be deprecated... I don't know : ) IF NOT, I think they will find a better solution for handling SVG and converting to PDF.

My suggestion is that use [sphinx](http://www.sphinx-doc.org/en/stable/), but you need to learn another markup language  [reStructuredText](http://docutils.sourceforge.net/rst.html). Markdown's goal is that to be convenient to write doc, and intended to convert to HTML only, but reStructuredText is well designed to be converted to all kind of format, latex(which can export PDF), html, man pages and etc.
