### ISSUE TITLE
bibtex bibliography not showing up in gitbook.io

### ISSUE THREAD

**Issue by viogp** [GitbookIO/gitbook#2167]
The gitbook bibliography is empty and no bibtex references are appearing in my gitbook.io (https://msm.gitbook.io/msm/references). I've tried different plug-ins:

* bibtex-citations-and-references
* bibtex-indexed-citation
* bibtex-cite
* bibtex

When I do locally `gitbook serve` (CLI version: 2.3.2, GitBook version: 3.2.3, Windows 10)the bibliography appears correctly and there's no error message. Once I go to the gitbook.io, there's no error message but the references appear empty.

**Comment by zurdors** [comment]
I have the same problem. I tried those 4 plugins and it did not work.
