### ISSUE TITLE
can't load our gitbook in chrome

### ISSUE THREAD

**Issue by ethhub-io** [GitbookIO/gitbook#2171]
### What is the current behavior?

In Chrome (or Brave) I cannot get past our landing page for our Gitbook. I can get to https://www.gitbook.com/@ethhub/spaces but when I open https://docs.ethhub.io/ which is our page, it just sits loading forever (with a general outline of what the page would look like in the background). 

### What is the expected behavior?

I should be able to open the page in Chrome and have been able to in the past. It actually works in Safari.

**Comment by ogxgit** [comment]
Can't reproduce with Chrome.

**Comment by ogxn** [comment]
Can't reproduce in Chrome.

**Comment by ogxn** [comment]
This is the repository for the old version of Gitbook.  Please talk to Gitbook support, somehow.

Also, I cannot confirm this with other (legacy or v2) documentation sites.
