### ISSUE TITLE
Any new release?

### ISSUE THREAD

**Issue by aleen42** [GitbookIO/gitbook#2176]
Dear Gitbook team,

Is there any 4.x releases, where I can build my book locally with themes like https://docs.gitbook.com/? I have tried to used 4.0.0-alpha.6, but found that there were some errors during walking through my old `SUMMARY.md`, resulting in finding only 1 page to build. In comparison, it works in 3.2.0.

--------

Sincerly,
aleen42

**Comment by aleen42** [comment]
For most developers, Gitbook client toolchain is the most important feature for GitBook

**Comment by piranna** [comment]
I agree, the new online-only website is useless.

**Comment by chaihongjun** [comment]
i prefer to the cli

**Comment by piranna** [comment]
@addisonschultz, how is that this got closed as "completed"? Does we have now an official offline CLI again?

**Comment by addisonschultz** [comment]
Hi @piranna ! 

As the last version of GitBook was deprecated a few years back, we've been working on some exciting stuff in the meantime, to make the most current version of GitBook more collaborative - and return to some of our roots as an open source product. 

This repo now contains an Open Source version of the rendering portion of GitBook. You can read the updated repo's readme to learn more! 

You can also visit us at https://gitbook.com/ to learn more about our current product offering. 

We'll be doing more communication of these changes to our user base very soon! I was cleaning up some of the old issues in the meantime. Sorry for the confusion!

**Comment by piranna** [comment]
We need an offline, npm installable CLI we can extend ourselves. Anything besides that, specially cloud silos, is useless to me. I understand the clean-up part, but you have closed A LOT of really needed issues that should have been fixed instead.
