### ISSUE TITLE
Gitbook not synching

### ISSUE THREAD

**Issue by vladola** [GitbookIO/gitbook#2184]
### What is the current behavior?

I change git repo -> I don't see any change in gitbook

### What is the expected behavior?

gitbook and github to have 2 way sync

My book is private.

----

The GitBook Team

**Comment by alexandre** [comment]
Same problem here. Actually, I also receive a message about an error on YAML parsing...
This message says the team was already notified, but  I don't know how to get the current status of this issue/error.

**Comment by denitsa-cm** [comment]
I have the same problem. Made a commit to the repo an hour ago and it hasn't synced into gitbook.

Private gitbook (https://subscription-people.gitbook.io/librarymanager) tracking `dev` branch
