### ISSUE TITLE
I can't login through gitbook editor app(Gitbook ON MAC)

### ISSUE THREAD

**Issue by yujiye** [GitbookIO/gitbook#2188]
I have been install the "Gitbook"  on my Mac ,

but I can't login!
<img width="691" alt="image" src="https://user-images.githubusercontent.com/744134/52320301-8838b200-2a09-11e9-9cbf-8cfb5acb9395.png">

**Comment by orhanco** [comment]
same here with macOS Mojave 10.14.1

**Comment by Hutton86** [comment]
me too
