### ISSUE TITLE
Support for versioning books

### ISSUE THREAD

**Issue by whatthejeff** [GitbookIO/gitbook#220]
Many open source projects provide versioned documentation. For example, the [python documentation](https://docs.python.org/) has a version drop down at the top of each page. This might be a nice feature for gitbook. Seems it could work very similar to the way multi-language support works.

**Comment by haosdent** [comment]
+1

**Comment by FickleLife** [comment]
It's been a while - did this make it into gitbooks in the end?

**Comment by groundnuty** [comment]
I too follow this issue with hope!

**Comment by SamyPesse** [comment]
If your book is hosted on GitBook.com, you can use the plugin [version](https://plugins.gitbook.com/plugin/versions) to display a dropdown to select redirect to an old version of the content.

**Comment by OndrejM** [comment]
You can easily support versions in gitbooks now, just mark your versions with a tag or put them on a different branch, and you can access them with `/v/tag` suffix. The [version](https://plugins.gitbook.com/plugin/versions) plugin would put a combobox with version selector.

We are using this for [documentation of our Payara opensource project](https://payara.gitbooks.io/payara-server/content/).
I would consider closing this issue, it's resolved to me.

**Comment by vickychijwani** [comment]
@SamyPesse @OndrejM I haven't looked deeply into the plugin, but how much effort do you think it would take to make it work with self-hosted GitBooks? The plugin could look at, for example, tags in the local repository to access a list of versions, if I understand correctly.

I'd be willing to send some PRs but it looks like the plugin is closed source.

**Comment by nagim** [comment]
@vickychijwani It's not closed, you can find the repo here: https://github.com/GitbookIO/plugin-versions

**Comment by vickychijwani** [comment]
Ah, thanks for point that out. That repo is not linked from [NPM](https://www.npmjs.com/package/gitbook-plugin-versions) or the [Gitbook Plugin page](https://plugins.gitbook.com/plugin/versions). Possibly because of a missing `repository` field in `package.json`.
