### ISSUE TITLE
Publish new version to NPM?

### ISSUE THREAD

**Issue by alukach** [GitbookIO/gitbook#2201]
Looking at the tags of this repo, it seems that Gitbook version `4.0.0` is in alpha at time of writing.  However, `npm` only has Gitbook version `2.6.9` published (six months ago).  

### Backstory
Version `2.6.9` has its dependencies hardcoded:

https://github.com/GitbookIO/gitbook/blob/67479a8789fdc9ac4740c31d0f27d6899d7b89d8/package.json#L14-L18

This causes some problems, for example version `1.1.0` uses `lodash`:

https://github.com/GitbookIO/plugin-search/blob/21bb20146d51529f7685318c1287e0183a3f1fa2/assets/search.js#L3

This (for whatever reason) is causing an error around a missing dependency:

```
Uncaught Error: GitBook module lodash doesn't exist
    at gitbook.js:4
    at Array.map (<anonymous>)
    at window.require (gitbook.js:4)
    at search.js:1
(anonymous) @ gitbook.js:4
window.require @ gitbook.js:4
(anonymous) @ search.js:1
```

Perhaps this is an issue in itself worthy of another issue, but I was thinking just upgrading `gitbook-plugin-search` would solve the problem.

I look at the `help.gitbook.io` and, based on looking at its [`gitbook-plugin-search` source](https://help.gitbook.com/gitbook/gitbook-plugin-search/search.js) I can see that it's using a more up-to-date version of the plugin. 

### The Point

Is there any reason version 3.x of this project hasn't been published to npm? This would be the easiest way to allow people to use more-modern versions of plugins (thus ideally avoiding issues) without needing to explicitly upgrade each plugin they use via `npm`.

**Comment by nagim** [comment]
3.2.3 is the last 3.x version published.

It's just chronologically 2.6.9 is the most recent, because the 2.x branch needed some fixes recently.

**Comment by alukach** [comment]
@nagim Ah, this is helpful to know. I was going off of the NPM badge in the readme and I admit that I didn't event try to see if NPM would install a 3.x version.  Upgrading versions did indeed solve my issues.  Thanks.
![image](https://user-images.githubusercontent.com/897290/55507210-64ae7400-5614-11e9-85e2-0187ab80fd88.png)
