### ISSUE TITLE
Gitbook not getting updates  from GitHub

### ISSUE THREAD

**Issue by TNgidi** [GitbookIO/gitbook#2203]
### Current behaviour?

I am accessing GitBook on the browser, on Mac OS Mohave with browser Google Chrome. 
The problem is that when i push changed to the GitHub repository connected to GitBook the changes do not show on GitBook. The reflect to the files on GitHub but not on GitBook. I have tried disconnecting and reconnecting the repository, when reconnecting it got the updated files, but when i made changes and pushed to GitHub again the changes made it to GitHub, but not all the way to GitBook. 

### Expected behaviour?

I think GitBook is supposed automatically to get changes pushed to GitHub 

#### For legacy.gitbook.com
https://manuals.disarm.io/  is the URL to our GitBook account and all the books there do not get updates from GitHub. My username is thokozani-r-ngidi

The GitBook Team
Out team is DiSARM

**Comment by nurse-the-code** [comment]
Why was this issue closed? What was the resolution?

**Comment by addisonschultz** [comment]
Hi @nurse-the-code: Sorry - this issue is related to the now deprecated version of GitBook - This repo is now home to the most recent version of GitBook - the open source code for rendering GitBook content
