### ISSUE TITLE
User selection on payload properties in OpenAPI spec

### ISSUE THREAD

**Issue by martinezdylan** [GitbookIO/gitbook#2246]
## Bug description

The current user-selection is less than ideal from a UX perspective when double-clicking a property of a path in an OpenAPI spec rendering. Double-clicking the property name will select also the type or schema (doesn't seem to happen on required properties). Also, for `object` types, it expands when you click the property name - perhaps we should prevent the default action on text selection & only expand when you click the box around it (denoting the cursor as pointer when it's available). This will be smoother.

## How to reproduce

1. Navigate to https://docs.gitbook.com/content-editor/blocks/openapi#pet
2. Attempt to copy `id` property name in the Body (it will select `integer` as well)
3. Attempt to copy `name` property name in the Body (it will only select name)
4. Attempt to copy `tags` property name in the Body (it will select `array` as well as expand the card)

## Additional context
N/A

**Comment by SamyPesse** [comment]
Nice idea 👍 fixed by https://github.com/GitbookIO/gitbook/pull/2249

You can give it a try at https://2e11bda3.gitbook-open.pages.dev/docs.gitbook.com/content-editor/blocks/openapi#pet
