### ISSUE TITLE
"Include" extenal content

### ISSUE THREAD

**Issue by blackfalcon** [GitbookIO/gitbook#226]
It would be great if we could use a syntax like `{{path/to/markdown.md}}` to allow for reusable content, notes and code examples.

**Comment by show0k** [comment]
This issue can be closed ; as far as I know it is [already included in gitbook](https://help.gitbook.com/format/conrefs.html).

You can do
```
{% include "./test.md" %}
{% include "git+https://github.com/GitbookIO/documentation.git/README.md#0.0.1" %}
```

**Comment by AaronO** [comment]
It is indeed. This was added with gitbook `1.0.0` if I recall correctly :)

**Comment by show0k** [comment]
This a little off topic question, but why don't you let include files from HTTP requests with a syntax like
{% include "https://raw.githubusercontent.com/GitbookIO/documentation/master/README.md" %}
?
If the git repo is fat, it can be very slow to import the file. And by the way, if you find interesting to use a VCS, SVN allow to pull file by file, it is convenient to use it on GitHub repo for fetching a file.

**Comment by eroller** [comment]
Does this feature still work? Can someone link to the updated documentation for it? The previous link from @show0k isn't working.

**Comment by addisonschultz** [comment]
@eroller This feature is from an old version of GitBook which has now been deprecated. The most up to date documentation on a feature similar to this can be found here: https://docs.gitbook.com/creating-content/reusable-content

**Comment by eroller** [comment]
thanks! do you have an example of the github sync results with markdown that uses the include directive?

is it like this?

```md
!include relative_path/reusable_content.md
```

**Comment by addisonschultz** [comment]
Apologies! I think the example snippet there got removed. I’ve updated the docs, but you can reference it using this syntax:

`{% include "../../.gitbook/includes/reusable-block.md" %}`
