### ISSUE TITLE
RTL / BiDi support

### ISSUE THREAD

**Issue by whatthejeff** [GitbookIO/gitbook#227]
It might be nice if the default theme had support for right-to-left / bi-directional text for handling Arabic, Hebrew, etc.

**Comment by mabouchalkha** [comment]
Any updates?

**Comment by SamyPesse** [comment]
This will be released in the next version of GitBook 2.0.0 (https://github.com/GitbookIO/gitbook/commit/55a7b99b4d4b4902bed0d53fb1b219b0c5f4584a).

Feel free to translate GitBook for your language: https://github.com/GitbookIO/gitbook/tree/version/2.0/theme/i18n

To enable RTL for a language: https://github.com/GitbookIO/gitbook/blob/version/2.0/theme/i18n/ar.json#L2

**Comment by a-moses** [comment]
PR #877  for hebrew
