### ISSUE TITLE
cover.jpg does not show on the gitbook and exported pdf file

### ISSUE THREAD

**Issue by mudongliang** [GitbookIO/gitbook#2307]
[Our repository](https://github.com/hust-open-atom-club/linux-insides-zh) does have a cover.jpg for the cover page, however, it does not show on the gitbook and exported pdf file.

**Comment by SamyPesse** [comment]
This is not a supported feature. You can use a cover on a page by setting it using the GitBook online editor or by defining it in the frontmatter of your Markdown files:

```markdown
---
cover: image.png
---
```
