### ISSUE TITLE
https://github.com/GitbookIO/gitbook/issues/2321#issue-2303493182

### ISSUE THREAD

**Issue by Eloutmanixx** [GitbookIO/gitbook#2322]
## Bug description

_Please describe._  
_If this affects the front-end, screenshots would be of great help._

## How to reproduce

1.
2.
3.

**Comment by addisonschultz** [comment]
Closing issue in reference to issue mentioned in title.

**Comment by Eloutmanixx** [comment]
Hlleo

**Comment by Eloutmanixx** [comment]
Hello thanks
