### ISSUE TITLE
LaTeX in SVG images is not rendered correctly in published books but looks fine in private view

### ISSUE THREAD

**Issue by cr0mll** [GitbookIO/gitbook#2351]
## Bug description
LaTeX embedded in SVG images is rendered verbatim in the published book, but gets rendered correctly when viewing the book via the app.gitbook.com domain. 

Essentially, this is what gets published:

![Bad LaTeX](https://github.com/GitbookIO/gitbook/assets/89641199/400fddd8-fe49-41b4-b3df-d369a9f7555e)

This is what it is supposed to look like and how it looks in the book preview from app.gitbook.com:

![Correct LaTeX](https://github.com/GitbookIO/gitbook/assets/89641199/5a14303e-faeb-48e5-afec-08b990dd8a68)

## How to reproduce

1. Embed LaTeX into an SVG image (in this case, I use draw.io, but anything works)
2. Embed SVG in gitbook via app.gitbook.com.
3. Merge your edits into your book and visit the page where you uploaded the SVG image. The LaTeX will be broken in the published version.

## Additional context
All SVGs are created in draw.io with Extras -> Mathematical Typesetting enabled. You can find countless other examples as well as the SVG images themselves on the link of the book and its repository (look mainly under Cryptography because most LaTeX containing images are there).

[GitBook](https://cyberclopaedia.gitbook.io/cyberclopaedia)

[Repository](https://github.com/cr0mll/cyberclopaedia)

**Comment by SamyPesse** [comment]
It's now working on my side on https://cyberclopaedia.gitbook.io/cyberclopaedia/cryptography/private-key-cryptography/block-ciphers, I see the same output as in the app or on GitHub https://github.com/cr0mll/cyberclopaedia/blob/main/docs/Cryptography/Private-Key%20Cryptography/Block%20Ciphers/Resources/Images/Block%20Cipher%20Encryption.svg

If it's still not working on yours, what browser are you using?
