### ISSUE TITLE
Font embed in PDF and EPUB

### ISSUE THREAD

**Issue by saturngod** [GitbookIO/gitbook#246]
I wrote plugin for font embed in website. My plugin , look like following.

``` javascript
module.exports = {
    book: {
        assets: "./book",
        js: [
        ],
        css: [
            "mybook.css"
        ]
    }
};
```

However, mybook.css is not working in PDF and Epub. I want to use my own font in PDF and EPUB.

**Comment by jolestar** [comment]
+1

**Comment by iamchathu** [comment]
Is this fixed now?
