### ISSUE TITLE
"Test it" tool does not autocomplete the information for the selected API.

### ISSUE THREAD

**Issue by YoonsooChang** [GitbookIO/gitbook#2525]
## Bug description

https://github.com/user-attachments/assets/b85c2db2-afa8-489a-826b-783bbdb02bb5

 Whenever I open the API client tool,  information such as URL, Query parameter, request body, etc. of the selected API is created empty. It appears to be a server rendering error that occurs when using Next.js.
The API client tool works in the local version, but the issue appears to be occurring at the production level, as is my application integrated with a Github repository, and also in the official Gitbook API Docs.

Is this perhaps related to the following issue in gitbook/integration?
https://github.com/GitbookIO/integrations/issues/569

**Comment by amritk** [comment]
hey @YoonsooChang we just [merged](https://github.com/GitbookIO/gitbook/pull/2539) an updated version of the client, give it a try and let us know if this is still an issue

**Comment by yoonsoo-chang** [comment]
Thanks for update! @amritk. I tried new version on Gitbook Apps, and it worked well.

**Comment by YoonsooChang** [comment]
Thanks for update! @amritk. I tried the new version on Gitbook Apps, and it worked well.
