### ISSUE TITLE
Scalar Client isn't creating the OpenAPI requests properly

### ISSUE THREAD

**Issue by martinezdylan** [GitbookIO/gitbook#2550]
## Bug description

The scalar client requests via 'Test it' aren't creating the requests based on the OpenAPI spec. See below:

<img width="1512" alt="Screenshot 2024-10-23 at 12 12 26 PM" src="https://github.com/user-attachments/assets/c9960a01-9bc9-4ad9-8eb9-ebcb89d7bad1">

## How to reproduce

1. Navigate to [https://docs.libum.io/nexum/symxchange/api-reference/persistent/informationservice](https://docs.libum.io/nexum/symxchange/api-reference/persistent/informationservice)
2. Click 'Test it'
3. We'd expect to see the OpenAPI request already pre-filled in the Scalar client where we then just have to add auth

## Additional context
This seems to be an almost consistent issue. It'll be fixed, in then all of a sudden with I suppose front-end changes it'll break again. Can we add some stability here or at least QA that this works before upstreaming changes? It's tough claiming we have interactive API docs to later discover they don't function.

**Comment by addisonschultz** [comment]
@amritk is this maybe related to yesterday’s PR? https://github.com/GitbookIO/gitbook/pull/2539

**Comment by amritk** [comment]
Yes this client is really old, the new one in the PR is much improved!

**Comment by amritk** [comment]
Yes this client is really old, the new one in the PR is much improved!

@martinezdylan the new client also works directly from an openapi spec instead of this current one which depends on specific data + transforms that keep breaking. So it should alleviate your concerns!

**Comment by martinezdylan** [comment]
Okay amazing, thanks for putting together that PR. I'll keep an eye for when it gets checked in 🔥

**Comment by SamyPesse** [comment]
#2539 has been merged, closing this issue

**Comment by marclave** [comment]
hi @martinezdylan i just wanted to formally apologize for the stability bugs! like @amritk mentioned we had to rollback our *new api client* to the old one due to performance issues, luckily we have fixed those and the new client is live!

moving forward it will be incremental improvements, and lots of neat features 😎 

appreciate your patience!

**Comment by martinezdylan** [comment]
No worries at all, really appreciate the effort here. Thanks @marclave & @amritk for the work and incredible project - we love what y'all are doing 😎
