### ISSUE TITLE
Redo not working, undo works badly

### ISSUE THREAD

**Issue by dzorogh** [GitbookIO/gitbook#2614]
## Bug description

**Redo** keybind (^+⇧+Z) not work.
And **Undo** doing weird things every time: removing spaces in previous paragraph, doing nothing, removing multiple lines of text. 

## How to reproduce

1. Write some text 
2. Press Undo
3. Text removed
4. Press Redo
8. Text not reverted

**Comment by Sahityaaryan** [comment]
@dzorogh Try (ctrl + z) for undo and (ctrl + y)  for a redo. It's working in my case, but I am also using a windows laptop, I think for mac it will also be the same

**Comment by emmerich** [comment]
@dzorogh We do support cmd+shift+z for redo on Mac, it's based on your `window.navigator`. Are you on Apple + can you run that command (`window.navigator`) in your console and tell us the output?

**Comment by dzorogh** [comment]
> @dzorogh We do support cmd+shift+z for redo on Mac, it's based on your `window.navigator`. Are you on Apple + can you run that command (`window.navigator`) in your console and tell us the output?

I have Windows 11 and Chrome 131

userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
platform: "Win32"

**Comment by dzorogh** [comment]
Sometimes it is working, sometimes not.

**Comment by emmerich** [comment]
@dzorogh I double-checked on our side, and tested a few other popular editors. It looks like supporting both cmd+shift+z and cmd+y on both Windows and Mac is pretty common. We'll push a fix today that makes sure both of these shortcuts work regardless of your OS.
