### ISSUE TITLE
Add ability to generate site maps

### ISSUE THREAD

**Issue by bguiz** [GitbookIO/gitbook#270]
... in [this format](https://support.google.com/webmasters/answer/183668)

**Comment by AaronO** [comment]
@bguiz @bebraw This would be great to have, it would help for book's SEO. We need to figure how that would work with relative and absolute URLs, books with custom domains and those without.

Maybe we can't generate a static `sitemap.xml` that would work perfectly for all those cases, but we should be able to generate it on our side, on `gitbook.com`.

If you guys have thoughts on how we could make this work with a static `sitemap.xml` and relative URLs, let me know !

**Comment by erlend-sh** [comment]
:+1:

**Comment by SamyPesse** [comment]
Already implemented as a plugin: https://plugins.gitbook.com/plugin/sitemap

**Comment by erlend-sh** [comment]
Wonderful! Is there an example of a book.json with multiple plugins enabled somewhere? I can't seem to get the formatting right.
