### ISSUE TITLE
Variable width for the summary column

### ISSUE THREAD

**Issue by emmanuel-keller** [GitbookIO/gitbook#271]
First, congratulations for this great work. Here at OpenSearchServer we plan to move our documentation on Gitbook.

We have a table of content with more 3 levels. Here is an example on your site:
http://gallarotti.gitbooks.io/Sitecore-MVC-the-Community-Book/

The default width of the summary column is too small.  It seems that the value is fixed. Can you make it variable by adding an entry in the book.json file ?

**Comment by sirtet** [comment]
This is something very annoying i noticed on different books.
Chapter-titles get wider than the left sidebar really fast, and end up with ellipses.

The table of ontents, index, or whatever the left column with chapters is called, should have a variable (draggable) width, at least on desktop view.

**Comment by jjloomis** [comment]
This was driving me nuts too. One solution: 

1. Create styles/websites.css (you can do this by clicking the upper-right drop-down arrow in the web or desktop editor. Select Stylesheets > For website.)

2. Open websites.css and add this to it:

```
.book-summary ul.summary li a, .book-summary ul.summary li span {
  white-space: normal;
}
```
