### ISSUE TITLE
PDF: code blocks are impossible to select and copy/paste?

### ISSUE THREAD

**Issue by toto88x** [GitbookIO/gitbook#290]
I'm writting a technical book with gitbook that has a lot of code blocks.

When the book is in PDF, I can't properly select with my mouse a code block. It means that it's impossible to copy and past some code from the book. 

That's a deal breaker for any technical book.

**Comment by thormagnusson** [comment]
Is there really no solution to this? - I've been having this issue in a book about coding I'm working on (and copying-pasting from the PDF is essential). Can't believe it hasn't been solved two years later.

**Comment by eljefe6a** [comment]
I ended up switching to Pandoc which didn't have this issue.

**Comment by thormagnusson** [comment]
So you're not hosting your book on GitBook then? - I was hoping to host the book on GitBook and readers could choose the format (PDF, eBook, HTML, etc.)

**Comment by eljefe6a** [comment]
Nope

**Comment by irontribe** [comment]
I find copy and paste are disabled  when using Safari on MacOS anytime I'm working in Markdown view. Does not seem to be a Chrome problem.
