### ISSUE TITLE
PDF: code blocks are truncated if too long

### ISSUE THREAD

**Issue by toto88x** [GitbookIO/gitbook#299]
I use the latest version of gitbook (0.5.2).

When I export my book to PDF, I can no longer see the lines that are too long in code blocks. For example, see: 

![image](https://cloud.githubusercontent.com/assets/7666922/3211124/1b1959c2-ef03-11e3-8cec-6c7a37321d37.png)

That's a really annoying issue. When that happens, we should simply add a new line, to make sure that all the text is visible.

**Comment by adimania** [comment]
I am facing this issue on gitbook.com. Any solution so far?

**Comment by muzhi1991** [comment]
I also have met this problem...is there any solution?

**Comment by dkotrada** [comment]
any solution?

**Comment by adimania** [comment]
moving away from gitbook worked for me. Now I am using stackedit, which is a general markdown editor. Less features but the ones that are there actually work.

**Comment by willin** [comment]
![edbd4f5a-9237-447b-be37-0bdbb29b125e](https://cloud.githubusercontent.com/assets/1890238/17961737/2119395e-6ae0-11e6-91b6-43c937eeb95f.png)


same problem v3.1
