### ISSUE TITLE
duplicated title

### ISSUE THREAD

**Issue by guoqiao** [GitbookIO/gitbook#320]
For my markdown files, I following the structure in the git doc, only two levels.

However, when I use 'gitbook mobi' to build my files in to a mobi, the title appears twice in each page.

To test, I clone this repo: https://github.com/rocodev/rails-102
and build this repo into a mobi, I also got two titles on each page.

Looks like something wrong with my gitbook version or ebook-convert?
Does any one have the same problem with me?

**Comment by TomasKulhanek** [comment]
Same problem. The duplicate title of chapter appears also in PDF. An older gitbook release 1.5.0 produce PDF seems not to have such issue.

**Comment by hspencer** [comment]
It seems that gitbook.com won't allow to compile it with v1.5.0. I tried to hide the double titles with css, but anyone knows is there is a special class for the h1s derived from the summary, being different from the h1s from the content? I dont want to make them all dissapear.

**Comment by iBobik** [comment]
Happens also with epub. Some readers will display title twice, iBooks will render blank page before chapter but wil not display title twice.

Like usual, chapters are defined in SUMMARY.md and chapter files begins with a headings (the same like in summary):
```
Title of the chapter
====================
```

Epub files will have html files with title section like:
```
  <body class="calibre">

<div class="page">

        <h1 class="book-chapter2" id="calibre_toc_2">Title of the chapter</h1>
        <div class="section">
            <h1 id="příběh-první" class="calibre17">Title of the chapter</h1>
```
First h1 have display: none in CSS, so will not be visible in most readers, but some of them ignores it and renders heading twice.
