### ISSUE TITLE
Convert to PDF - Need to install ebook-convert from Calibre

### ISSUE THREAD

**Issue by quanghoc** [GitbookIO/gitbook#333]
I had this on SO

http://stackoverflow.com/questions/24339276/gitbook-error-on-need-to-install-ebook-convert-from-calibre

The CLI is available

```
$ ebook-convert

Usage: ebook-convert input_file output_file [options]

Convert an ebook from one format to another.
```

But I still got error below when converting to PDF

```
Need to install ebook-convert from Calibre
```

The error may be something else but I can't find the log or figure out why.

Mac 10.9.3
I have both Xcode 5 and 6-Beta. Maybe that's why?

**Comment by tobegit3hub** [comment]
Thanks @kaelzhang and it saves me time :+1:

**Comment by 7Moses** [comment]
@kaelzhang,

Thanks!

**Comment by alanguir** [comment]
@sks worked perfectly, thank you for posting

**Comment by chusiang** [comment]
@kaelzhang ++

It's work on Mac OS X 10.10.5

     ln -s /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/local/bin

**Comment by JimmyPeng4iOS** [comment]
thxxxxxxxxxxxxxxxxxxxxxxx @sks

**Comment by andyczerwonka** [comment]
I'm running on Ubuntu and I get this error. I did install ebook-convert from npm.

**Comment by JimmyPeng4iOS** [comment]
First:
cd /xxx/xx/xx
and:
export PATH=$PATH:/Applications/calibre.app/Contents/MacOS
Then:
gitbook pdf 

hope helpful~! XD

**Comment by neove** [comment]
@kaelzhang thanks

**Comment by jpb-c1** [comment]
> export PATH=$PATH:/Applications/calibre.app/Contents/MacOS

Welp, it's 2018, I had trouble getting `gitbook` to find `ebook-convert`, and explicitly linking the path (after manually DL'ing `Calibre 3.20.0`—homebrew only had 3.19) is finally what it took to make gitbook stop barfing.

**Comment by AnalyzePlatypus** [comment]
@sks still works great.
(Calibre's "Install Command Line Tool" option seems to have been removed)
