### ISSUE TITLE
export to Word format 

### ISSUE THREAD

**Issue by simonech** [GitbookIO/gitbook#339]
Itb would be cool if it was possible to generate also Word documents (unfortunately traditional publishing companies need Word)

**Comment by chenryn** [comment]
+1

**Comment by Casyfill** [comment]
+1

**Comment by bweir** [comment]
Why was this closed?

**Comment by FickleLife** [comment]
Any update on how to output to docx?

**Comment by zixun** [comment]
Any update on how to output to docx?

**Comment by simonech** [comment]
The single `page` doesn't work anymore.
I gave up using gitbook, using pandoc now

**Comment by yanhaijing** [comment]
+1
