### ISSUE TITLE
Single page export doesn't work anymore

### ISSUE THREAD

**Issue by simonech** [GitbookIO/gitbook#341]
The format page, which is explained in the readme, doesn't work with the latest version

**Comment by yeasy** [comment]
Why removing this feature? 
It's really useful!
Any progress on it?
Thanks!

**Comment by simonech** [comment]
Is someone even looking at those issues? it's 2 years? Or is this project now dead as OSS and just focused on providing features for the SaaS offering?

**Comment by yeasy** [comment]
I'm using pandoc to generate pdf now.

**Comment by simonech** [comment]
From markdown? And correctly processes code snippets and all markdown styles?
