### ISSUE TITLE
Allow HTML pages, text files, php files, etc

### ISSUE THREAD

**Issue by weitzman** [GitbookIO/gitbook#351]
I have a [directory of example files in my repo](https://github.com/drush-ops/drush/tree/master/examples) that I'd like to link to in my book. The pages end in extensions like .inc, .php, .html, .ini, etc. The behavior I would love is for gitbook.io to serve  those pages as unmodified text/plain responses, [similar to Github's 'raw' mode](https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.drush.ini). I think this is safe for gitbook.io, and achieves the user expectatation of being able to copy/paste the whole response. Obviously, no book navigation would be shown when following such a link.

**Comment by johnlindquist** [comment]
@AaronO Can you still import external code snippets with this {{some_file.php}} syntax? I can't find it anywhere in the documentation and I cannot get it to work for me.

**Comment by gdad-s-river** [comment]
I have the same question @AaronO , If I have external snippets of code that I want to import in my gitbook, it is possible? In other words my question is if I can do something like jsDoc with Gitbook?

**Comment by SamyPesse** [comment]
@gdad-s-river @johnlindquist I published a plugin for this: https://plugins.gitbook.com/plugin/codesnippet

Example:

```
{% codesnippet "./myfile.js" %}{% endcodesnippet %}
```
