### ISSUE TITLE
Relative link with anchor not updated from .md to .html

### ISSUE THREAD

**Issue by jewzaam** [GitbookIO/gitbook#355]
Book with two chapters, second chapter references a specific heading in the other chapter.  See example below.

chapter1/README.md
```
# Heading 1
text

# Heading 2
More text
```

chapter2/README.md
```
[This link works.](../chapter1/README.md)

[This link does not work.](../chapter1/README.md#heading-2)
```

**Comment by jakecleary** [comment]
:+1: Would be super useful.

**Comment by aniav** [comment]
I am also interested in this :zap:

**Comment by aniav** [comment]
Oh I believe this has been fixed already. Just checked that. Thank you! :+1:

**Comment by SamyPesse** [comment]
Yes it should work with gitbook 2.0.0 :)

**Comment by joaomilho** [comment]
It doesn't appear to work in the summary (to me it creates disabled links):

Here's the summary:

```
# Table of contents

* [home](/README.md)
* [Concepts](/docs/concepts.md)
  * [Using JSON for rendering](/docs/concepts.md#using-json-for-rendering)
```

And I have `"version": "2.1.3"`.

**Comment by joaomilho** [comment]
I use second level headings (##) in these anchors 'though. Is this the problem?

**Comment by hepstr** [comment]
Doesn't seem to work in the summary for me either. I create the anchors in the .md source with `<a name="whatever"></a>`.

**Comment by willlarche** [comment]
@joaomilho , I tested it on third level and it worked.

**Comment by renato67** [comment]
@willlarche I tried it but it does't work for me. Can you send an example? this is my code:
 
```
 * Funzionalità di base](utilizzo_dellapplicativo_di_back_office/funzionalita_di_base.md)
    * [Pulsantiera](utilizzo_dellapplicativo_di_back_office/funzionalita_di_base.md##Pulsantiera)
```
this is an H2 link, but also H1 link doesn't work

TIA

Renato

**Comment by jessepinho** [comment]
@renato67 Note that you have two `#`s in your link, so that could be part of the problem.
