### ISSUE TITLE
Gitbook serve does not process book.json

### ISSUE THREAD

**Issue by jnhuynh** [GitbookIO/gitbook#371]
Running `gitbook serve` and `gitbook serve --config book.json` from within the gitbook directory does not work. I've tried copying the example config from [here](https://github.com/GitbookIO/gitbook). It seems to just ignore the file.

When I rename the `book.json` to `book.js` it _sort of_ works by outputting the following ambiguous error:

```
Press CTRL+C to quit ...

Live reload server started on port: 35729
Starting build ...

/Users/jnhuynh/some-book/book.js:3
    "title": null,
           ^
Successfully built!

Starting server ...
Serving book on http://localhost:4000
```

Providing a string value for the "title" key does not change anything. It still shows an error on the "title" key.

Below are my node, npm, and gitbook versions.

```
$ node --version
v0.10.26
$ npm --version
1.4.3
$ gitbook --version
0.6.0
```

**Comment by DanaReilly** [comment]
@rdsoze I'm having the same issue –would you mind specifying what you mean by fixing the 'relative config file path'?

Cheers,
Dana

**Comment by ivereninov** [comment]
@AaronO I've encountered the same issue. book.json does not affect build at all when building both locally and on gitbook.com.  Here is a link to my book.json https://github.com/emlid/Documentation/blob/master/book.json

**Comment by juaalta** [comment]
@ivereninov You need to add one } at the end of links.

Your book.json
```
{
    "links": {
        "sidebar": {
            "Custom link name": "https://customlink.com"
        },
}
```

Correct book.json 

```
{
    "links": {
        "sidebar": {
            "Custom link name": "https://customlink.com"
             },
        }
}
```

**Comment by ivereninov** [comment]
@juaalta  Thanks! I have changed it, but it did not made any difference. The build succeeds, but there is no link.
