### ISSUE TITLE
Removing links with config file not working

### ISSUE THREAD

**Issue by minthemiddle** [GitbookIO/gitbook#385]
The config file `book.json` is not working for me.

I have the standard config with a `repository` folder in which I have a `book.json` file. When I build the book with `gitbook build repository/ -o out/ --config repository/book.json`, it does not remove the links as I configured.

Is it an issue? Or am I doing something wrong?

Here is my file tree:

```
.
├── out
│   ├── gitbook
│   ├── index.html
│   ├── manifest.appcache
│   └── search_index.json
└── repository
    ├── README.md
    ├── SUMMARY.md
    └── book.json
```

And the `book.json`:

```
{

    // Links in template (null: default, false: remove, string: new value)
    "links": {
        // Link to home in the top-left corner
        "home": null,

        // Links in top of sidebar
        "about": false,
        "issues": false,
        "contribute": false,

        // Sharing links
        "sharing": {
            "google": false,
            "facebook": false,
            "twitter": false
        }
    }

}
```

**Comment by matthewford** [comment]
I also ran into this issue - removing all comments from the `book.json` file worked for me see https://github.com/GitbookIO/gitbook/issues/371

**Comment by achton** [comment]
I also cannot get the links removed. The `plugins` option works correctly, but other options I have tried, including `links` have no effect at all.

**Comment by SamyPesse** [comment]
@achton what version are you using ?

**Comment by achton** [comment]
@SamyPesse I use 1.5, installed globally via `npm install`. It is quite clear that the `book.json` is actually being read, just that some parts of the config file are not being merged properly. If I alter the `lib/generate/config.js` and override the default config there, I can remove the links. But obviously this is not a solution.

**Comment by LeoYuan** [comment]
Any progress now?

**Comment by chriswburke** [comment]
sharing should be under the "pluginsConfig" object

```
"pluginsConfig": {
        "sharing": {
            "google": false,
            "facebook": false,
            "twitter": false
        },
}
```

**Comment by sarus** [comment]
This is now in its own plugin.  Took me a while to figure this out but here's the plugin page that has the configuration options:

https://github.com/GitbookIO/plugin-sharing

**Comment by zxdposter** [comment]
{
    "plugins": ["-sharing"]
}
