### ISSUE TITLE
How to change "Introduction" text in summary column?

### ISSUE THREAD

**Issue by minthemiddle** [GitbookIO/gitbook#388]
When you build a website from your repository, the summary in the left column (`includes/book/summary.html`) contains the h1 of all files that are in `SUMMARY.MD`. However, for the main `README.MD`, which renders to `index.html`, there is a hard-coded `Introduction` link (see screenshot below).

Where in the source code can I change that text? The book is non-english, so I need a different text there.

And is it planned to change the code so that it also takes the h1 text?

![bildschirmfoto 2014-07-31 um 12 24 40](https://cloud.githubusercontent.com/assets/1950766/3762949/f04b815c-189c-11e4-92ae-2955afee75b5.png)

**Comment by andrei512** [comment]
@AaronO Thank you!!!!!

**Comment by soulmachine** [comment]
@AaronO this trick is nice, thanks :+1:

**Comment by jimmycuadra** [comment]
Can you please add this to the documentation on https://toolchain.gitbook.com/?

**Comment by beeth0ven** [comment]
@AaronO that's an interesting trick.
