### ISSUE TITLE
Version 1.0 remove offline browsing

### ISSUE THREAD

**Issue by erixtekila** [GitbookIO/gitbook#405]
@AaronO as discussed here https://github.com/GitbookIO/gitbook/commit/899a53a8237853b69770055e604d18e664202d43

Would you mind explain why you find offline browsing not interesting, please ?

**Comment by abdulhannanali** [comment]
Just a heads up to people coming to this post, now you can use ServiceWorker, it's not hard to generate one using `sw-precache` on your computer to host all the assets.
