### ISSUE TITLE
require() - name conflict with node/node-webkit

### ISSUE THREAD

**Issue by tonka3000** [GitbookIO/gitbook#409]
Hy,

i have problems launching a book with node an node-webkit. the problem is the require-function from node vs the different require-function from requirejs. RequiredJS seems to support it's own namespace - please integrate that if it is possible.
Launching a book in it's own app would be a cool feature :-) .

Thanks in advance
Greetings
Tonka

**Comment by kylebrowning** [comment]
Ive been trying to do this with electron to no avail.

@SamyPesse Any insight?

**Comment by SamyPesse** [comment]
Why not simply create a window with `node-integration` set to `false` ?

```js
var BrowserWindow = require('browser-window');

var win = new BrowserWindow({
    width: 800,
    height: 600,
    show: false,
    'node-integration': false
});
win.on('closed', function() {
    win = null;
});

win.loadUrl('./mygitbook/index.html');
win.show();
```

(this is also possible with node-webkit).

**Comment by SamyPesse** [comment]
You can also embed it into a node window with https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md

**Comment by kylebrowning** [comment]
Ahh, i was setting 'node-integration': false in my package.json but adding it to the window works.

Thanks!

**Comment by SamyPesse** [comment]
You're welcome :)
