### ISSUE TITLE
Can't switch between languages in editor - edit: it's due to dropdown menus not working

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#410]
I want to translate a book and prepared it for this (folders with all necessary files and LANGS.md). But the editor don't show any language under book -> languages.

When I preview the book as Website-Version, the languages appear and all works fine.

Windows 7 32 Bit, latest editor. Git version 1.9.4.

Edit: It's not due to the languages. I can't open recent books too. Because the dropdown menus doesn't appear.

**Comment by tomde** [comment]
Still not fixed? I am also experiencing this problem.

**Comment by jayvdb** [comment]
It looks like this is still not working

**Comment by jayvdb** [comment]
However, in the editor, at the bottom right hand corner is a language selector which does switch languages.
