### ISSUE TITLE
Only a notice for users in China,a special version with Chinese support

### ISSUE THREAD

**Issue by codepiano** [GitbookIO/gitbook#415]
As you know,Gitbook use [lunr.js](https://github.com/olivernn/lunr.js) to genereate search index of the site.
Unfortunately,this module don't support Chinese,and the author don't want to support multiple language search in one library ethier.
So I forked the repo and add Chinese support.Replace Gitbook's default module with the forked one.
If you want your site support Chinese search,you can use my repo forked from Gitbook.
I will merge the latest commits of Gitbook and improve it for Chinese users.
current:
1. add chinese search support
2. add search keyword highlight
3. add sharing in qrcode
4. add sharing to qq/qzone/qq microblog (acctually is qq connect)

the repo is here:
[Gitbook](https://github.com/codepiano/gitbook)
[lunr.js](https://github.com/codepiano/lunr.js)

由于Gitbook使用了  [lunr.js](https://github.com/olivernn/lunr.js) 来生成内容索引，lunar.js不支持中文且作者没有支持的意愿，所以我fork了一个仓库，添加了中文的支持。
如果你想对gitbook生成的页面添加中文搜索支持，可以使用我fork修改过的Gitbook，我会持续的合并Gitbook和lunr.js最新的提交，并且添加一些对中国用户有用的功能。
目前添加的功能有：
1. 支持中文搜索 需要生成所有文章内容的json格式索引文件，内容过多的话需要注意文件的体积
2. 支持搜索后关键字高亮
3. 支持二维码
4. 支持分享到qq好友和qq群
   - 分享到qq直接跳转至qq connect分享页面，该页面也可实现分享到qq空间和qq微博的功能
   - 需要在配置文件中设置相关选项为true

**Comment by gengdaoping** [comment]
How to search chinese use lurn.js
