### ISSUE TITLE
Autogenerate SUMMARY.md according to headlines and headers in *.md files

### ISSUE THREAD

**Issue by noisy** [GitbookIO/gitbook#422]
I want to use gitbook as documentation generator in mobi format. Almost every github repository has content in README.md file, since this is what user see as first thing on the repository page.

It would be amazing if I could:

```
git clone git@github.com/cool_project.git
gitbook mobi ./cool_project
```

regardless if SUMMARY.md is available or not.

In my opinion, this autogenerated SUMMARY.md by default **should not** be saved as file. It should used only to generate ebook.

**Comment by mstade** [comment]
Presumably, `README.md` would take the role of `SUMMARY.md` *only* when the latter does not exist. If such is the case then, again presumably, the headings would make for a good summary list – i.e. the following:

```markdown
# Some title
Lorem ipsum ...

## Sub-heading
Lorem ipsum ...

# Another title
...
```

Would turn into the following list:

```markdown
- [Some title](README.md#some-title)
  - [Sub-heading](README.md#sub-heading)
- [Another title](README.md#another-title)
```

It'd really only be meaningful, I think, on projects where `README.md` has grown rather large, [such as this one][1]. Even then, the output might not be great. It seems like a fair bit of work for a feature that has little potential gain, to be honest. The overhead of creating a `SUMMARY.md` is negligible, and I'd reckon there are more questions than immediate answers as to how `README.md` would be a reasonable substitute.

[1]; https://github.com/apenwarr/redo
