### ISSUE TITLE
optional Github links

### ISSUE THREAD

**Issue by fdschneider** [GitbookIO/gitbook#426]
Back from vacation, I just updated gitbook from 0.5.2 to 1.0.2 and found the page without all the github links (About the author, issues, edit and contribute). There is no mention of that in the CHANGES.md or version history, but apparently they were removed in v0.7..  Is that right? 

I am using gitbook to build a collaborative knowledgebase within a project and the "edit" and "issues" direct link were exactly what I needed. 

I switched back to a previous version for now. But couldn't the links remain an optional feature to be activated via the book.json (maybe as a smaller "edit" button in the corner of the page)?

**Comment by rahul286** [comment]
You can add github links using https://www.npmjs.com/package/gitbook-plugin-edit-link
