### ISSUE TITLE
Highlighting Rows In Code Blocks

### ISSUE THREAD

**Issue by eljefe6a** [GitbookIO/gitbook#433]
I have code blocks in my book that I want to have highlighted. I've searched around and can't find it in GitBook. It is in [Remark](https://github.com/gnab/remark), another markdown-based viewer. In that program, you can have an "*" at the beginning of a code block to highlight it.

[This slide](http://remarkjs.com/#8) in Remark's example shows their code highlighting. There are three lines with a lighter gray that are marked. Does GitBook have something similar?

**Comment by makaimc** [comment]
hey @eljefe6a @gladson @toto88x @SamyPesse, I ran into the same issue so I created a plugin to do highlighting within code blocks. This plugin doesn't rely on Prism.JS - that dependency didn't seem necessary here.

[GitBook plugin](https://plugins.gitbook.com/plugin/code-highlighter)
[NPM package](https://www.npmjs.com/package/gitbook-plugin-code-highlighter)
[Source on GitHub](https://github.com/makaimc/gitbook-plugin-code-highlighter)

This is my first NPM package and GitBook plugin (most of my coding is in Python & Swift nowadays) so there are some rough edges to work out. For example, the code definitely needs tests and a couple of configuration options. However, the current plugin version (1.0.6) should be fine for a straightforward highlighting case requested in this issue ticket.
