### ISSUE TITLE
bring back "edit on github" link

### ISSUE THREAD

**Issue by fdschneider** [GitbookIO/gitbook#445]
This is a feature request. 

From v0.7 the direct links to GitHub were removed (See issue #426). 
However, especially for multi-author books, the link that brought you to the GitHub editor with the current page opened as markdown document, was extremely useful. 
There was no need for expert authors, who never worked with git or GitHub, to install an appropriate editor, learn some git, or navigate on the GitHub platform to the site they want to edit. 

I understand that this is not useful for single author or finished books. So make it optional. How about a pen button in the corner of each page? That would facilitate adding content.

**Comment by rahul286** [comment]
I just published a gitbook plugin to solve this - https://github.com/rtCamp/gitbook-plugin-edit-link

You can use it. :-)

Also if you find any bug in plugin, please let me know. I am new to gitbook/npm.
