### ISSUE TITLE
Relative Paths In Summary

### ISSUE THREAD

**Issue by eljefe6a** [GitbookIO/gitbook#449]
I am using relative paths in my GitBook summary and the files are not found or added to the resulting book.

Here is an example of the SUMMARY.MD:

```
* [Lab Notes](../../exercises/general/notes.md)
```

Does GitBook not support relative paths?

**Comment by Javix** [comment]
Any updates for `3.1.1` version for OS X ? I'm using:
````
CLI version: 2.3.0
GitBook version: 3.1.1
```
and still can't reference SUMMARY.md from another chapters like that: `../SUMMARY.md`.

**Comment by juliencarnot** [comment]
I'm still reproducing this too, somebody found a workaround?
