### ISSUE TITLE
Installation and Execution on Ubuntu 14.04

### ISSUE THREAD

**Issue by ytisf** [GitbookIO/gitbook#453]
On Ubuntu 14.04 64bit there is an issue with _libudev0_. Dynamic linking of that shared library causes it not to be found _libudev.0.so_. 

``` bash
james ~/Sources/gitbook > ./start.sh 
gitbook/GitBook: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

Solution is to create a symbolic link:

``` bash
sudo ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0
```

Static version of it or another check to see where libudev is and at whichi version will provide a solution.

**Comment by samwilson** [comment]
I got a similar error on Ubuntu 16.04:

> gitbook-editor: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Solved it with `sudo apt install libgtk2.0-0:i386`.

Then got:

> gitbook-editor: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

So installed that: `sudo apt install libxtst6:i386` as well.

**Comment by MAccadia** [comment]
I got the same errors too. I fixed it by installing 64bit .deb package (https://www.gitbook.com/editor/linux-64-bit/download). The « Download for Linux » button in https://www.gitbook.com/editor made me download the 32bit package.
