### ISSUE TITLE
Cover.jpeg not included on PDF

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#457]
I'm using the autocover plugin to generate a custom cover, but this is not being used on the generated PDF book, that I think it should.

**Comment by piranna** [comment]
Bulk clossing so much open important issues, is that because you are finally killing open source version of Gitbook? Just setting the repo as private is faster and less annoying than receiving throusand of "closed" issues emails...

**Comment by addisonschultz** [comment]
Hi @piranna you can find an explanation and what's to come here: https://github.com/GitbookIO/gitbook/issues/2176#issuecomment-2017635960
