### ISSUE TITLE
book cover thumbnail does not display in kindle reader (mobi) but does display in ibooks (epub)

### ISSUE THREAD

**Issue by nicholascloud** [GitbookIO/gitbook#461]
I have included a `cover_small.jpg` image in my repo's root, of size 200x262 (per the documentation). When I generate a mobi file and then open it in kindle reader, the thumbnail is not displayed. When I generate an epub and open it in ibooks the thumbnail is displayed correctly.

Is there a DPI or color-depth restriction for the thumbnail?

**Comment by kcladyz** [comment]
I went to list view then back to grid view and the thumbnails appeared
