### ISSUE TITLE
Don't set main README.md file as 'introduction' on the index

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#476]
README.md is added automatically, that not something so bad, but it's also added on the index as an introduction, that maybe it's not what you want, for example when using it to show info about how to generate the book. In my case (a degree thesis) I have a separate introduction chapter, so having it twice on the index looks ugly.

**Comment by petermichaux** [comment]
I don't understand why the README.md file is required and why it is automatically included as the first item in the Table of Contents with the string "Introduction". I think it would be better that the README.md file is not included by default. It is very easy for authors to include it in the SUMMARY.md file if they want the README.md file included in some way. Much more flexible too.

**Comment by piranna** [comment]
+1 to @petermichaux

**Comment by gbonanome** [comment]
+1 to this feature, maybe an option inside `book.json`

**Comment by CristianCantoro** [comment]
See also https://github.com/GitbookIO/gitbook/issues/392.

**Comment by piranna** [comment]
I've found this problem also affect the Glossary, being it shown in english while the other entries of my table of contents are in spanish...

**Comment by SamyPesse** [comment]
Just add `"language": "sp"` to your book.json file.

**Comment by piranna** [comment]
Oh, great, thank you! :-)
