### ISSUE TITLE
Hyperlinks on printed PDFs

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#477]
When printing a PDF with hyperlinks there's no way to know where they were pointing to. Add an option to show them on foot-notes or at an appendix, something similar to the glosary.md file.

**Comment by mvilrokx** [comment]
+1

**Comment by piranna** [comment]
So, also killing print versions, nice (not).

**Comment by addisonschultz** [comment]
@piranna We still offer PDF export in our newest version of GitBook: https://docs.gitbook.com/published-documentation/customization/space-customization#pdf-export

**Comment by piranna** [comment]
This issue is NOT about PDF generation, but about having visible URLs when printing the URL on paper. Normal link in PDF are just blue text when printed with no reference to the actual URL, I needed to create my own plugin to fix that.
