### ISSUE TITLE
Feature request: Button to clear search

### ISSUE THREAD

**Issue by CoDEmanX** [GitbookIO/gitbook#479]
It would be nice to have an "x" button to clear the search phrase, similar to the green "check"-icons.

It would also emphasize that there's a filter applied to the navigation, which is not always obvious (if the search input field is visible but empty, the "x" should be hidden).
# **Monkey patch**

(does not hide the "x" if input is empty but otherwise feature-complete)

Insert this before `.book-search input`:

```
<a id="clear-search" href="#">&times;</a>
```

CSS:

```
#clear-search {
    display: inline;
    position: absolute;
    top: 12px;
    right: 9px;
    font-size: 18pt;
    line-height: 18pt;
    color: #364149; // needs to be updated on theme change
}

#clear-search:hover {
    color: #008cff; // needs to be updated on theme change
    text-decoration: none;
}
```

Edit existing style rule of input element:

```
    .book .book-summary .book-search input {
        padding-right: 22px;
    }
```

JS to clear input and force a re-filter:

```
$('#clear-search').on('click', function(event){
    event.preventDefault();
    $('.book-search input').val("").trigger("keyup");
});
```

**Comment by Serdaro** [comment]
+1 to above. Additionally, when a header is added to the static site, the search field is located into the header. I need to press the Search button, so that the field slides into its expected location.
