### ISSUE TITLE
Image Captions

### ISSUE THREAD

**Issue by jdittrich** [GitbookIO/gitbook#486]
**User Story**: As a writer I want to caption my illustrations and images in my book in order to give further explanations or draw a connection to the main text.

**Implementation Suggestion:** Pandoc wraps images in a `div` (or `figure`) and inserts a `p` or `figcaption` for the caption. The Caption is generated from the images alt text: `![this will be the caption](path/to/image.png)` See:  http://johnmacfarlane.net/pandoc/README.html#fnref4

**Comment by matugm** [comment]
I need this too :+1:

**Comment by bmesuere** [comment]
+1

**Comment by kmelve** [comment]
+1

**Comment by a-mitani** [comment]
Yeah, I need it, too.
+1

**Comment by piranna** [comment]
I'm using https://github.com/todvora/gitbook-plugin-image-captions for this.

**Comment by manfredsteger** [comment]
Would be a good feature for screenreaders too. In the PDF-version of a gitbook, there is no image alt-text.
