### ISSUE TITLE
error links generated from SUMMARY.md when path is 2 or more level deep in Windows

### ISSUE THREAD

**Issue by cnDelbert** [GitbookIO/gitbook#493]
I wrote the following in my SUMMARY.md

    - [PHP简介](Introducing PHP/index.md)
      - [历史](Introducing PHP/History/index.md)
        - [背景](/Introducing PHP/History/background.md)
        - [早期版本的PHP](/Introducing PHP/History/early_versions_of_php.md)
      - [PHP的优势](Introducing PHP/Advantages of PHP/index.md)

The links are right when it comes out for the first time. After I clicked on one of the links above, the link would be `..\../Introducing PHP/History/index.html` style.

The `..\../path/to/file` works fine when in the Windows environment while it will go wrong once in *nix system.

I uploaded my book to github and I had to modify the url to make sure the page not to be error 404.

As `/` works fine in Windows, I suggest to use the `/` as the split of the path.

**Comment by renkun-ken** [comment]
I have got similar problem on this. My summary looks like

```
# Summary

* [Acknowledgment](acknowledgment.md)
* [Quick start](quick-start/README.md)
    * [What is R](quick-start/what-is-r.md)
    * [Why R](quick-start/why-r.md)
    * [Install R](quick-start/install-r.md)
```

However, the rendered urls are all like `quick-start\index.html`, `quick-start\what-is-r.html` which are all problematic when I commit to `gh-pages` on GitHub and breaks nearly all accessibility of texts from the contents on the left.

This problem does not appear in GitBook v1.x.

**Comment by SamyPesse** [comment]
@renkun-ken are you building on windows ?

BTW: you should use [gitbook.com](https://www.gitbook.com), it integrates perfectly with GitHub
