### ISSUE TITLE
Allow two sections have the same subsection name

### ISSUE THREAD

**Issue by jiangchuanheglobal** [GitbookIO/gitbook#500]
I have two sections in a chapter, both has a subsection sharing the same name. Like, for example,

1.1 section1

```
1.1.1 summary
```

1.2 section2

```
1.2.1 summary
```

But, I can't create section "1.2.1 summary" because there is already "summary.md" file in that directory.
so, I need to manually resolve this. Is there a elegant way to solve this in Gitbook Editor?

**Comment by sebelk** [comment]
Sorry for the stupid question, but how can I do that?

**Comment by sebelk** [comment]
Nevermind.... editing SUMMARY.md it's the answer :)
