### ISSUE TITLE
include glossary.md to pdf

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#505]
the glossary.md file is not addesd automatically to the pdf output. It should be added at the end of the pdf in a similar way it's done with the table of content, but also added links on the referenced text.

**Comment by skyscribe** [comment]
@piranna Is this issue resolved from your side? Can I understand this as fixed in v3.2.0 (latest tag)?

I specified my book.json with `gitbook : >= 3.2.0` unfortunately still no glossary generated, though terms are highlighted.

**Comment by piranna** [comment]
Yes, it's already fixed since version 2-something.

**Comment by skyscribe** [comment]
@piranna Thanks, do you enable some specific settings or the glossary is just included by default?

**Comment by piranna** [comment]
I don't remember doing nothing special, I think it should work by default
if it finds a GLOSSARY.md file.
