### ISSUE TITLE
add number of page to the table of contents

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#507]
When adding the table of contents on the PDF, it's being shown only the title of the chapters and sections and links to them, but it's not shown the page number. Add it so when printing the PDF is possible to know what's the page to look for.

**Comment by piranna** [comment]
How could I be able to add this feature myself? For the on-screen PDF view this is not a bad sense although there are the in-document links, too...

**Comment by fazo96** [comment]
This is an actual problem because when the PDF is printed the links of course won't work, so a setting in the config. file to choose to show the page number would be nice.

The data is there, by changing the html of the compiled summary one could add a tag containing the page number and with CSS move it to the side.

I could try to do that but I don't have much time and don't really know where this part is handled in the codebase.

**Comment by piranna** [comment]
A similar problem happens with the links, that should be added as foot notes.

**Comment by bweir** [comment]
1+ this is absolutely needed for print.

**Comment by borisschapira** [comment]
Has anyone found a solution to this ? Are you using gitbook 2.6.7 ?

**Comment by piranna** [comment]
> Are you using gitbook 2.6.7 ?

Yes, I'm always using the latest one, and this bug is still there :-(

**Comment by piranna** [comment]
Any update on this? My thesis director has dictated that it's mandatory I **must** have this on the thesis... :-/

**Comment by bweir** [comment]
It's hard to imagine that this feature isn't already there. I've never seen a table of contents in my life that didn't have page numbering. =(

**Comment by thomasbiesaart** [comment]
I want to prepare my book for print but it doesn't make much sense to print without page numbers in the toc

**Comment by drreen** [comment]
Has anyone found a workaround or plugin for that?

**Comment by bweir** [comment]
Not me. Maybe if we make enough noise someone involved in the project will provide the official stance on this!

**Comment by yeasy** [comment]
+1!

**Comment by rabevers** [comment]
This issue was opened on Nov 23, 2014, is there any progress?

I really need this. Without it Gitbook is no longer an option.

If anyone has any pointers on how/where this can be fixed, please share so I can have a look and maybe help fix it.

**Comment by gdbooks** [comment]
Just want to add a bump. This would be REALLY USEFUL!

**Comment by rabevers** [comment]
This one is extremely high on my wish list too. Someone has been able to do so by changing the pdf generation from calibre to wkhtmltopdf.

I got it working but it took some effort, Take a look at.
[https://github.com/GitbookIO/gitbook/issues/1223](https://github.com/GitbookIO/gitbook/issues/1223)
and
[https://github.com/GitbookIO/gitbook/issues/1470](https://github.com/GitbookIO/gitbook/issues/1470)

**Comment by yeasy** [comment]
Great work!

**Comment by qgeissmann** [comment]
+1

**Comment by daniellauyu** [comment]
过了这么多年了，gitbook还是没解决这个问题，为什么首页的目录页码不对，而且标题也不是自定义的。

**Comment by manhnt9** [comment]
I need this too, please consider to implement. Thanks developers.
