### ISSUE TITLE
Cannot publish book through web editor

### ISSUE THREAD

**Issue by tdiesler** [GitbookIO/gitbook#510]
When I save a change to wildfly-camel it shows up on the [github repository](https://github.com/wildflyext/wildfly-camel-book) and on the [history page](http://snag.gy/YEHit.jpg)

The book is however not published and I get

```
Error 404
This book has not been published yet
```

when I try to [view the book](https://www.gitbook.com/book/wildflyext/wildfly-camel).

**Comment by mcandre** [comment]
I'm a new GitBook user, and I'm seeing the same error "This book has not been published yet". What should I do?

**Comment by AaronO** [comment]
@mcandre Yep, your builds were failing (since you were missing your `SUMMARY.md` and `README.md` files). Good that you got that fixed :+1:

**Comment by deniseOme** [comment]
How did you solve this issue @rockywang101 ? I'm facing the same problem and would be great to hear how you have sorted it, if anything.
