### ISSUE TITLE
PDF Table of Contents Output

### ISSUE THREAD

**Issue by eljefe6a** [GitbookIO/gitbook#523]
The README.md for GitBook no longer talks about the PDF `"toc": false` property. It appears to be ignored now. Is there a new setting to turn it off?

**Comment by hackhowtofaq** [comment]
Any news about this?

**Comment by pparavicini** [comment]
I am using gitbook to create a template for writing proposals, which are rather short, and deliver them in pdf.  The Table Of Contents is a bit overkill. 

+1 for the ability to suppress it via configuration.
