### ISSUE TITLE
YouTube link issue in PDFs

### ISSUE THREAD

**Issue by mehan** [GitbookIO/gitbook#526]
When you generate a PDF from a GitBook that contains links to YouTube videos (i.e. a static image with a link to the video), the link only works if you click at the very bottom of the image but does not work if you click anywhere else in the body of the image.

**Comment by mehan** [comment]
Just gave you read access to the book repo, which you'll find here:

https://github.com/generalassembly-studio/MOB-book

A copy of the PDF is here:

https://drive.google.com/open?id=0B4xBTbyHI9AXTk9ObWJ3RWZsX0k&authuser=0

Thanks!

**Comment by SamyPesse** [comment]
Which version of GitBook was used to generated this pdf ?

You may be interested in taking a look at https://github.com/GitbookIO/plugin-youtube

I think the bug come from the fact that neither `<img>` or `<a>` is of type `display: block`, I can fix this in the youtube plugin.

**Comment by mehan** [comment]
This was generated using version 1.5.0. I will definitely give that plug-in a shot. Thanks!

**Comment by SamyPesse** [comment]
That plugin requires GitBook 2.0.0. If you're using GitBook.com, you can switch the version used in your book settings.

**Comment by mehan** [comment]
If I switch the version on Gitbook.com to v2.0, can I still manually build using the v1.5 toolchain? If not, I might just wait for the v2.0 toolchain release.

**Comment by SamyPesse** [comment]
When you select `v2.0` as current builder, your next builds will be done using GitBook 2.0.0; you can switch back to `v1.5` if you have some bugs.

The `v2.0` is going to become the stable release in the coming weeks.
