### ISSUE TITLE
Broken Unicode Font in PDF version

### ISSUE THREAD

**Issue by nuhil** [GitbookIO/gitbook#532]
When user downloads a PDF version of a book which is written other than english such as "বাংলা - Bengali" language, then its showing broken fonts on the downloaded PDF file. 
Example: http://howtocode-com-bd.gitbooks.io/-python/

Any workaround for getting rid off this? I can provide Bengali fonts if needed to be integrated with your generator.

**Comment by nuhil** [comment]
@AaronO We the guys of http://www.howtocode.com.bd/ would love to hear when it goes to production as all of its books are based on gitbookIO :)

Thanks Again!

**Comment by tobegit3hub** [comment]
The environments of gitbook.com and my computer are different. I can generate the pdf with Chinese well but there're problems when I download from gitbook.com. @AaronO are you sure the fonts of Chinese are in production environment?

**Comment by tumluliu** [comment]
There is still problem with Chinese fonts in pdf downloaded directly from gitbook. The font size of main text is fairly small. And the characters look weird as they were rendered with multiple different chinese fonts.

**Comment by nicolasmei** [comment]
I have the same issue with Chinese fonts.  can I set a different fonts?

**Comment by billryan** [comment]
For Chinese character, [adobe-fonts/source-han-sans](https://github.com/adobe-fonts/source-han-sans) would be a better choice, and it is necessary to differentiate between simplified Chinese and traditional Chinese.

**Comment by moonbingbing** [comment]
@AaronO @billryan I have the same problem with Chinese fonts in PDF. Is there a plan to use another Chinese font? I think http://wenq.org/wqy2/index.cgi?MicroHei(en) is better choice. thx

**Comment by billryan** [comment]
@moonbingbing For CJK fonts, I recommend Google NotoSansCJK fonts and it performs perfect now. The disadvantage of this CJK fonts is the generated PDF consumes too much disk space(50MB for 700 pages PDF).

I wrote some scripts to build static files(PDF, EPUB, MOBI) with NotoSansCJK fonts on travis. You can see it from https://github.com/billryan/algorithm-exercise/blob/master/.travis.yml#L33 to https://github.com/billryan/algorithm-exercise/blob/master/.travis.yml#L43

**Comment by billryan** [comment]
I built a dockerfile to fix this annoying Unicode fonts rendering issue(PDF). You can test your own proper fonts in the dockerfile. Hit [billryan/docker-gitbook](https://github.com/billryan/docker-gitbook) for more details.

I will open another issue regarding Unicode fonts selection and provide more details about fontconfig next week.

@AaronO 

The Chinese fonts you installed are **non-free** and not proper for both Simplified and Traditional Chinese.

> cns11643-kai
> cns11643-sung
> moe-standard-kai
> moe-standard-song

Since you installed a lot of fonts in your OS, the fonts in the PDF behaves weird if you do not provide proper fontconfig configuration files.

I will provide a detailed solution and configuration files after some test cases with the docker container.

**Comment by AaronO** [comment]
@billryan Happy to get your help on this issue :+1: 

We should improve our default Chinese fonts, so I'm open to any pull requests on that matter :)

**Comment by Vdragon** [comment]
@AaronO 

These fonts:

```
cns11643-kai
cns11643-sung
moe-standard-kai
moe-standard-song
```

are fonts designed by Taiwan government.  While it's indeed non-free(but re-distributable), it is quite the proper serif-like font for Traditional Chinese(Taiwan region).  The cns11643 fonts provides more rare Chinese glyphs than moe-standard fonts, however their ASCII glyphs are ugly, so you should first prefer other proper serif fonts(such as Liberation Serif) then fall back to these fonts.

For sans-serif font you should use Google Noto Sans/Adobe Source Han Sans, as it's both standard-driven and free fonts

**Comment by raheems** [comment]
Any interest to add the SolaimanLipi Bangla font? The Lohit is not a standard font for publications in Bengali. Thanks.

**Comment by mimehedi166** [comment]
hello guys,
I think i found the solution of this problem. i've tried some library (dompdf, TCPDF,FPDF,mPDF) which support PHP but not all of them are work properly. I didn't find any unicode support with dompdf, 
tcpdf worked but the fonts are broken. so i tried mPDF and it gave me my expected output. 
i'm using this library to my laravel project. To using mPDF with laravel project you need to follow the documentation of laravel-mpdf.
 link: https://github.com/niklasravnsborg/laravel-pdf

after installed the library successfully what you have to do this following steps for other language or bangla support.
1. first download the fonts for your supported language (i.e: for bangla i've downloaded solaimanLipi.ttf) and keep it to your fonts folder inside the resources folder. if there is no fonts folder just create it.
2.In config/pdf.php file add these codes inside of return array

```
'font_path' => base_path('resources/fonts/'),
	'font_data' => [
		'examplefont' => [
			'R'  => 'ExampleFont-Regular.ttf',    // regular font
			'B'  => 'ExampleFont-Bold.ttf',       // optional: bold font
			'I'  => 'ExampleFont-Italic.ttf',     // optional: italic font
			'BI' => 'ExampleFont-Bold-Italic.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,    
			'useKashida' => 75, 
		]
		// ...add as many as you want.
	]
```

examplefont is your attribute name whatever you want to use. but inside this attribute paste your font name.
```
Example:
'bangla' => [
			'R'  => 'SolaimanLipi.ttf',    // regular font
			'B'  => 'SolaimanLipi.ttf',       // optional: bold font
			'I'  => 'SolaimanLipi.ttf',     // optional: italic font
			'BI' => 'SolaimanLipi.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,   
			'useKashida' => 75, 
		]
```

now in your view file use this CSS Scripts:
```
<style>
body {
	font-family: 'examplefont', sans-serif;
}
</style>
```

In Your Controller:
```
function generate_pdf() {
	$data = [
		'foo' => 'bar'
	];
	$pdf = PDF::loadView('pdf.document', $data);
	return $pdf->stream('document.pdf');
}
```

Hints: pdf.document is your view file name.
Use PDF at the top in your namespace

If you follow this step correctly ,it will work 100%.
**This is my output**
![sample](https://user-images.githubusercontent.com/7956469/38669805-fdd758f0-3e68-11e8-99a8-e1f1ed1988a5.PNG)

N.B: This is my first post. if i did any mistakes to write review in correct format please consider it and take it lightly. 
Thank You, 
Mahabubul Islam Mehedi

**Comment by babu12f** [comment]
@mimehedi166  not working in laravel 5.6 what can i do?
