### ISSUE TITLE
Is it possible to add internal links?

### ISSUE THREAD

**Issue by balinterdi** [GitbookIO/gitbook#535]
I was wondering if there is a way to add links pointing to other sections in the same book. Ideally, all sections (marked as headers in the markdown source) could be targets, but it would already be great to being able to jump to the beginning of other chapters.

This surely makes sense for the html and pdf versions, not 100% sure about epub and mobi.

**Comment by simonschaufi** [comment]
For me internal links are broken if used in a subdirectory in an example.md file linking to example2.md file. Can somebody verify that?

**Comment by despiegk** [comment]
have same issue, can't get internal links to work

**Comment by SeaDude** [comment]
Call me slow, but I had to play with links for a long time to get them right. Here is a gitbook example of using internal links successfully. 

https://seadude.gitbooks.io/linking/content/


Most links DO NOT however, render in PDF just like @balinterdi mentioned in 2014. Am I just missing something about links or is this still an issue? Thoughts on this @SamyPesse?

**Comment by justin808** [comment]
I have been trying to do this with https://github.com/shakacode/react_on_rails, and the created links point to a markdown file and the gitbook site renders the file as raw text.

Please see the following:

* https://github.com/shakacode/react_on_rails  - github source
* Search for "Code Splitting" which points to https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/code-splitting.md

* Now try on the gitbook https://shakacode.gitbooks.io/react-on-rails/content/
* Search for "Code Splitting" which points to: https://shakacode.gitbooks.io/react-on-rails/content/docs/additional-reading/code-splitting.md

The gitbook case is suboptimal compared to just using github.com.

**Comment by simoneluijckx** [comment]
Hi @SeaDude ,
I've been trying your example of: 
Relative Internal Link to a heading in the SAME article:
Syntax:
`  [heading](#test)`
Format:
`  [link text](#<heading-name>) `

I can't get it to work unfortunately. Are there other ways to use internal linking? 
Or do I need to add a code for internal linking to my book?

**Comment by SeaDude** [comment]
Hey whats up simoneluijckx,

I haven't viewed this gitbook in a long time! I'm glad people are getting use of it.

Here is the actual Markdown. Paste this **near the top** of your article.

```
* ##### Relative Internal Link to a [heading](#test) in the SAME article:
* Syntax: [heading](#test)
* Format: [link text](#<heading-name>)
```

This will link to an H1 heading named # Test. Put this Markdown **near the bottom** of the same article. Put enough white space between the Markdown above and this heading so you can see it scroll when the link is clicked.

`# Test`

As long as there are no other headings (H1, H2, H3, etc.) with the SAME name (# Test), Clicking the link in the example at the top of the page should link you down to the # Test heading.

Hope this helps,

**Comment by simoneluijckx** [comment]
@SeaDude Thanks for your reply! 

I'm afraid I don't get it. Do I have to paste this exact line: 

`* ##### Relative Internal Link to a [heading](#test) in the SAME article:`

or only this:

`* ##### [heading](#test)`

I tried both, but they don't work for me.

**Comment by SeaDude** [comment]
You paste the first snippet near the top of a test page. Then, paste the
second snippet waaaayyyy down the bottom of page.

The top, should have created a link to the bottom (relative, internal link)

**Comment by curiousPup** [comment]
can anyone please tell how to do the same with alphanumeric data? eg Version 18.02
