### ISSUE TITLE
Get modified date of a file as a variable

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#536]
It would be great to get access to the "last modified" date in the markdown file as a variable. For example: `{{ modified }}`.

**Comment by mottosso** [comment]
Any progress on this? This would be a terrific feature.

In my use case, it'd be preferable as a toggle/setting of sorts for a footer note. Else I would attach it to the bottom of each page manually, but could potentially forget or accidentally remove it.

**Comment by SamyPesse** [comment]
It's already implemented: https://github.com/GitbookIO/gitbook/blob/master/lib/template.js#L431

Example:

```md
Last modification: {{ file.mtime }}
```

You'll probably need a plugin that implement a `date` filter if you want to display it.

**Comment by mottosso** [comment]
Sweet! Thanks @SamyPesse!

**Comment by RenaudILTIS** [comment]
Is this feature available? In my case, I wanted to show in the book (for example in the readme.md text, or in the summary.md) the date of the last update of the book. Could you explain me the how to this?
Thank you.
