### ISSUE TITLE
"Variables for templating" are not passed to swig templates

### ISSUE THREAD

**Issue by rahul286** [GitbookIO/gitbook#544]
I am building a custom theme and my book.json looks like below:

```
{
    "theme": "../rtcamp/",

    "variables": {
        "rtGitPath": "https://github.com/rtCamp/rtbiz/edit/master/docs/user",
        "rthello": "TEST"
    }
}
```

I have a line in my file `rtcamp/templates/book/includes/header.html` as below:

```
<a href="{{ rtGitPath }}/master/{{ _input }}" class="pull-right"  target="blank">Edit on Github {{ rthello }}</a>
```

Above link is showing correct path value for built-in variable `{{ _input }}` but variables declared in `book.json` showing empty values.

**Comment by SamyPesse** [comment]
Variables are accessibles in the book content not in the theme.

For example, in your README.md:

```
# This is a {{ rthello }}

```

**Comment by rahul286** [comment]
Oh. Is there any way to pass theme variables from `book.json`.

I am basically trying to modify default theme to add "Edit with Github" link (ref: #445)

Problem is every gitbook has different github repo. So I hardcode github repo path in theme, I have to modify theme per gitbook we are working on. :|

**Comment by SamyPesse** [comment]
I think this should be implemented as a plugin, it's not recommanded to edit a theme. A plugin can extend the html, javascript and css, and get some configurations from book.json.

**Comment by rahul286** [comment]
Thanks. I will try it via plugin. 

With theme, I had more control. I will give plugin a try. Thanks again. :-)

**Comment by SamyPesse** [comment]
A plugin is the best idea ;) it makes it easy for other people to reuse it, ... Feel free to ask me for help for creating this plugin (you can contact me at samy@gitbook.com).

**Comment by rahul286** [comment]
Sure. I had some misconception about plugin and themes. I tried to everything via theme and then wishes to bundle my customization as plugin.

Some notes about work so far https://gist.github.com/rahul286/51f757ff115c37ba0513 . Nothing much at the moment. Basically, I am noting down every piece of useful info and wish to write a mini-gitbook about "customizing gitbook" based on those notes (or send PR to http://help.gitbook.io/ ).

Thanks for sharing your email address. I will try my best to not trouble you much. :-)

**Comment by rahul286** [comment]
Thanks @SamyPesse 

Because of you, I manage to release my first npm package and first gitbook plugin - https://github.com/rtCamp/gitbook-plugin-edit-link

I hope other users will find it useful. :-)
