### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by ytisf** [GitbookIO/gitbook#549]
Please enable Checkbox support for such syntax:
```
- [x]  Empty Checkbox. 
- [x] Completed Checkbox
```

- [ ] Empty Checkbox. 
  -  [ ] Subcheckbox
- [x] Completed Checkbox

**Comment by cesards** [comment]
+1 to this. It is very useful

**Comment by juange87** [comment]
:+1:

**Comment by acabunoc** [comment]
+1

**Comment by LiJohnson** [comment]
:+1:

**Comment by KINGSABRI** [comment]
:+1:

**Comment by AdrianKoshka** [comment]
This would be awesome

**Comment by danleavitt0** [comment]
+1

**Comment by haofu** [comment]
+1

**Comment by SamyPesse** [comment]
Moving this issue to https://github.com/GitbookIO/feedback/issues/116
