### ISSUE TITLE
Markdown styles not rendering in Glossary

### ISSUE THREAD

**Issue by stevenschmatz** [GitbookIO/gitbook#550]
In the editing view, this is not a problem. All markdown styles are rendered on the preview of the online editor.

However, once the book goes live, the styles are in plaintext.

![screen shot 2015-01-12 at 9 52 37 am](https://cloud.githubusercontent.com/assets/5354479/5704562/c85da3f2-9a40-11e4-9df3-c76c0a06107e.png)

[Example](http://stevenschmatz.gitbooks.io/stats-250/content/GLOSSARY.html#percentiles)

**Comment by torsday** [comment]
+1
