### ISSUE TITLE
Having trouble getting "GLOSSARY" to work

### ISSUE THREAD

**Issue by znmeb** [GitbookIO/gitbook#557]
I'm using a command line workflow - my book is in a Git repo, I edit files, do 'gitbook build' on my workstation and when I'm happy with the results I do a 'git push' to publish on GitBook.com. URL is <https://www.gitbook.com/book/znmeb/osjourno-robust-power-tools-for-digital-journalis>

When I look at the book with 'gitbook serve' or 'gitbook pdf', the glossary isn't there. But I can see it on the website in the editor!

**Comment by AaronO** [comment]
Hi @znmeb, the glossary is accessible through a button in the header (see attached screenshot):

![screen shot 2015-01-16 at 11 48 04 am](https://cloud.githubusercontent.com/assets/949223/5775084/b454bba6-9d75-11e4-95d6-17a07b52b298.png)

Your glossary is here : http://znmeb.gitbooks.io/osjourno-robust-power-tools-for-digital-journalis/content/GLOSSARY.html

Terms defined in the Glossary are then auto-highlighted throughout the book (definitions are then displayed whenever hovered).

Maybe we could do a better job and making the glossary more visible/accessible.

I would love to hear your thoughts on how we could improve this !

**Comment by SamyPesse** [comment]
@AaronO You should add your answer to the documentation as reference of the glossary
