### ISSUE TITLE
Proposal for GitBook 2.0.0

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#558]
# Proposal for GitBook 2.0.0:

This issue is just a list of my proposals for the version 2.0 of gitbook. Please specify the section (1, 2, ..) when commenting.

I think all of this can be implement very fast (I can do it for a release next week).

------

### 1. GitBook CLI and local versions

Books should accept a `version` configuration in the `book.json` to define which version they want to use. `gitbook-cli` package should be able to download from npm the specific version of GitBook in a folder (for example `~/.gitbook/versions`) and use the specific version of gitbook needed by the book (or the latest one).
I know this doesn't look like the best solution for node developers, but since 90% of GitBook authors are not node-developers or just want to use GitBook.com, this `version` configuration in the book.json will let them specify the version without knowing anything about node.

**Example of book.json**:

```
{
	"version": "2.0.x"
}
```

**Process when running `gitbook build ./`**:

The `gitbook` bin comes from a `gitbook-cli` node package.
1. It will read for the `version` in the `book.json` (default is `*`)
2. If the folder `~/.gitbook/versions/:version` doesn't exist, it will download it using `npm install`
3. `gitbook-cli` will obtain a list of available commands from the `gitbook` package (:warning: the list of commands should not be defined in `gitbook-cli`)
4. And start the command `build`

------

### 2. Templates and Plugins

Extending markdown syntax for a plugin is currently not easy (by regexp...). The markdown syntax is not easy to extend without conflicts.

Plugins should not extend the markdown syntax but instead extend a templating syntax on top of the markdown file.

For example (using the jinga2, swig, twig, nunjucks syntax), a plugin could easily extend the templating syntax to add this:

```
# My math formula:

{% math %}
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi
{% endmath %}
```

We are already using some parts of this syntax for importing variables and files.

Using a templating syntax on top of the markdown syntax could allow some use case, like this one from the GitHub documentation (https://github.com/blog/1939-how-github-uses-github-to-document-github):

```
{% if site.audience != '11.10.340' %}

This new feature...

{% endif %}
```

**Advantages:**
- Much more easy and cleaner for the plugins to extend the syntax
- Support for variables, import (content references), conditions, ...
- We can add support for Asciidoc in the future without changing the plugins

-----

### 3. Content reference

A conref allows you to write a chunk of text once and reuse it throughout the site. (The idea was borrowed from the [DITA standard](http://dita.xml.org/arch-conref).)

By using the templating syntax, we can add support for content reference:
- Inside the same book, using `{% import "./test.md" %}`
- From other books, using something like `{% import "gitbook.com/test/test2/test.md#0.3.0" %}

With something like [nunjucks](http://mozilla.github.io/nunjucks/) (supported by mozilla), we can easily add support for 2. and 3.).

-----

### 4. i18n support

This is related to #64 and #504.

There is a PR for this from @winniehell: https://github.com/GitbookIO/gitbook/pull/556

I'll merge this PR in the coming days.

-----

### 5. Option to ignore README.md

This is related to #392 and #476.

-----

### 6. Styling of ebook and website

This is done by: #555.

-----

### 7. Nice URLs

Allow nice urls ( `README.html` => `/` (really `/index.html`))

-----

### 8. Have plugins declare config in manifest

This is useful both for validation options, and potentially building web ui or a GUI to manage plugin config.

**Comment by znmeb** [comment]
My two wish list items are

1. ssh for git pull / push to the GitBook.com repositories
2. being able to use a local copy of the editor on my workstation either as an "nw" enabled desktop app or as a web app.

**Comment by AaronO** [comment]
@znmeb 

2. Is actually already implemented (and existed before [GitBook.com](https://www.gitbook.com) ;) )

1. I think SSH support could be nice. But right now we have `http` combined with `tokens` which provides a similar solution without having to worry about firewall issues etc ... (even for GitHub `https` is the recommended transport). Maybe people aren't aware of being able to use `https` + tokens and we should make that more aware/obvious.

What are your thoughts on `1.` ?

**Comment by winniehell** [comment]
> 1. GitBook CLI and local versions

Did you have pre-compiled binaries for major operating systems in mind? This would solve the hassle around installing node.js on Windows (at least on the user side of the world). Extra large :+1: if that is your intention. The use case of having non-disclosure GitBooks (which you can clearly not post on GitBook.com) would benefit tremendously from that.

**Comment by AaronO** [comment]
@winniehell That's possible, but I think it's better go with the [desktop editor](https://github.com/GitbookIO/editor) for that use case.

And actually non-disclosure books are supported with GitBook.com since you can have private books. And we've got an enterprise solution coming out very soon that runs behind the firewall.

**Comment by znmeb** [comment]
@AaronO OK ... I figured out how to use the tokens with the desktop editor app and Gitbook.com, but not with command line Git. Is that documented somewhere?

I couldn't find the html version of the editor - I just installed the binary release. If I install the editor with a git clone do I get the html version?

My workflow is a mix of desktop and command line but I am trying to migrate everything to Docker, which means web apps for the most part. I've got command-line Gitbook running in Docker; see https://bitbucket.org/znmeb/osjourno-gitbook. The remaining piece is to get a web version of the editor in the Dockerfile

**Comment by winniehell** [comment]
@AaronO Sounds all great to me!

> desktop editor

I already had a look at the editor (which currently has a bug on Windows) and it seems to be exactly the right tool for the task. But in that case it should include the versioning feature mentioned above as well, shouldn't it?

> private books on GitBook.com

Depending on the content, hosting somewhere else is not an option.  :cake:

> enterprise solution

Can't wait for it! :+1: 
...though I secretly doubt that Microsoft Officers are willing to spend money on "text files"/"text editor".

**Comment by AaronO** [comment]
@winniehell The enterprise version isn't the editor, but the whole GitBook.com platform.

So you get an all in one solution that hosts all your documentation and allows your employees to collaborate effectively together. You get teams, great git/github enterprise integration etc ... It doesn't aim to replace Microsoft Word, but rather help companies organize the big mess that is their documentation (in surprisingly many cases).

**Comment by gbonanome** [comment]
Regarding section 6 (Styling of ebook and website, a great feature), #555 has changed the documentation and this can lead to some confusion for people trying to implement it today. 2.0.0 release has a ship date? If not, can we update the documentation to say that custom style is not yet in production?

**Comment by SamyPesse** [comment]
I'm working locally on the new version, I' hopping to be able to present a fully working version in the next 5 days.
I'm going to update the readme in the midtime.

**Comment by winniehell** [comment]
> 5. Option to ignore README.md

@SamyPesse Are you already working on that? Otherwise I'd try to do so. :hammer:

**Comment by SamyPesse** [comment]
Yes, I already done it in the new version, I'll push it as a PR in the coming days.

**Comment by winniehell** [comment]
(That's a strange behavior of GFM to start numbering with 1 inside a quote...)

**Comment by SamyPesse** [comment]
I posted a presentation of my PR: https://github.com/GitbookIO/gitbook/pull/562
