### ISSUE TITLE
Gitbook Build ERROR

### ISSUE THREAD

**Issue by DanaReilly** [GitbookIO/gitbook#561]
I ran gitbook build -v to identify the source of the error, and this is the result:

Danas-Macbook-Air:wdi-fundamentals danareilly$ gitbook build -v
Starting build ...
TypeError: Cannot read property 'type' of undefined
    at Parser.tok (/usr/local/lib/node_modules/gitbook/node_modules/kramed/lib/kramed.js:1111:25)
    at Parser.parse (/usr/local/lib/node_modules/gitbook/node_modules/kramed/lib/kramed.js:1003:17)
    at Function.Parser.parse Æas parserÅ (/usr/local/lib/node_modules/gitbook/node_modules/kramed/lib/kramed.js:990:17)
    at Indexer.text (/usr/local/lib/node_modules/gitbook/lib/generate/site/search_indexer.js:38:19)
    at Indexer.bound Æas textÅ (/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:729:21)
    at Indexer.addSection (/usr/local/lib/node_modules/gitbook/lib/generate/site/search_indexer.js:48:21)
    at bound (/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:957:21)
    at Function.map (/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:3508:27)
    at Indexer.add (/usr/local/lib/node_modules/gitbook/lib/generate/site/search_indexer.js:63:7)
    at Indexer.bound Æas addÅ (/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:729:21)

This issue started when I installed the gitbook-plugin-js-sequence-diagram globally... in general, external plugins have not been working and neither have quizzes or exercises (just Mathjax for some strange reason).

Any guidance would be appreciated!

**Comment by AaronO** [comment]
Hi @DanaReilly,

Could you share a link to your book if it's on [GitBook.com](https://www.gitbook.com) or a link to the source if it's on GitHub ?

If neither is an option, could you share your `book.json` and `SUMMARY.md` ?

**Comment by DanaReilly** [comment]
Thank you for your prompt response!

The book is not publicly accessible, so I can share the two files:

book.json:

{
    "generator": "site",
    "title": "WDI Fundamentals",
    "description": null,
    "plugins": ["quizzes", "exercises", "jsfiddle", "toconsole", "richquotes"],
    "pluginsConfig": {
        "fontSettings": {
            "theme": "sepia", "night" or "white",
            "family": "serif" or "sans",
            "size": 1 to 4},
        "richquotes": {
            "todos" : true},
        "toconsole": {
          "buttontext": "Evaluate in console"},
        "jsfiddle":{
            "tabs":["result","js","css", "html"],
            "height":500,
            "widht":500
          }
    },
    "variables": {},
    "links": {
        "sidebar": {
            "Custom link name": "https://customlink.com"
        },
        "sharing": {
            "google": null,
            "facebook": null,
            "twitter": null,
            "weibo": null,
            "all": null
        }
    },
    "pdf": {
        "pageNumbers": false,
        "fontSize": 12,
        "paperSize": "a4",
        "margin": {
            "right": 62,
            "left": 62,
            "top": 36,
            "bottom": 36
        },
        "headerTemplate": null,
        "footerTemplate": null
    }
}

SUMMARY.md:

# Summary

* [Welcome](README.md)
   * [Get Started](get_started.md)
* [Think like a Programmer](01_chapter/README.md)
   * [How Your Computer is Organized](01_chapter/02_lesson.md)
       * [Quiz](01_chapter/03_quiz.md)
       * [Exercise](01_chapter/04_exercise.md)
   * [Navigate using the Command Line](01_chapter/05_lesson.md)
       * [Quiz](01_chapter/06_quiz.md)
       * [Exercise](01_chapter/07_exercise.md)
   * [Manipulate files using the Command Line](01_chapter/08_lesson.md)
       * [Quiz](01_chapter/09_quiz.md)
       * [Exercise](01_chapter/10_exercise.md)
   * [Unit 1 Homework](01_chapter/11_assessment.md)
   * [Cheat Sheet](01_chapter/12_cheatsheet.md)
* [Developer Workflow](02_chapter/README.md)
   * [What is Version Control?](02_chapter/02_lesson.md)
       * [Quiz](02_chapter/03_quiz.md)
       * [Exercise](02_chapter/04_exercise.md)
   * [Introducing Git](02_chapter/05_lesson.md)
       * [Quiz](02_chapter/06_quiz.md)
       * [Exercise](02_chapter/07_exercise.md)
   * [Github](02_chapter/08_lesson.md)
       * [Quiz](02_chapter/09_quiz.md)
       * [Exercise](02_chapter/10_exercise.md)
   * [Unit 2 Homework](02_chapter/11_assessment.md)
   * [Cheat Sheet](01_chapter/12_cheatsheet.md)
* [Elements of a Computer Program](03_chapter/README.md)
   * [Expressions and Evaluations](03_chapter/02_lesson.md)
       * [Quiz](03_chapter/03_quiz.md)
       * [Exercise](03_chapter/04_exercise.md)
   * [Variables](03_chapter/05_lesson.md)
       * [Quiz](03_chapter/06_quiz.md)
       * [Exercise](03_chapter/07_exercise.md)
   * [True or False?](03_chapter/08_lesson.md)
       * [Quiz](03_chapter/09_quiz.md)
       * [Exercise](03_chapter/10_exercise.md)
   * [Unit 3 Homework](03_chapter/11_assessment.md)
   * [Cheat Sheet](01_chapter/12_cheatsheet.md)
* [Control Flow in JavaScript](04_chapter/README.md)
   * [Control Flows](04_chapter/02_lesson.md)
       * [Quiz](04_chapter/03_quiz.md)
       * [Exercise](04_chapter/04_exercise.md)
   * [Conditionals and Loops](04_chapter/05_lesson.md)
       * [Quiz](04_chapter/06_quiz.md)
       * [Exercise](04_chapter/07_exercise.md)
   * [Unit 4 Homework](04_chapter/09_assessment.md)
   * [Cheat Sheet](04_chapter/12_cheatsheet.md)
* [Functional JavaScript](05_chapter/README.md)
   * [Functions](05_chapter/02_lesson.md)
       * [Quiz](05_chapter/03_quiz.md)
       * [Exercise](05_chapter/04_exercise.md)
   * [Unit 5 Homework](05_chapter/05_assessment.md)
   * [Cheat Sheet](05_chapter/06_cheatsheet.md)
* [Complex JS Data Types](06_chapter/README.md)
   * [Arrays and Associations](04_chapter/01_lesson.md)
       * [Quiz](04_chapter/02_quiz.md)
       * [Exercise](04_chapter/03_exercise.md)
   * [Unit 5 Homework](04_chapter/04_assessment.md)
   * [Cheat Sheet](06_chapter/05_cheatsheet.md)
* [Next Steps](07_chapter/README.md)
* [Glossary](GLOSSARY.html)

Thank you for your help.

**Comment by DanaReilly** [comment]
@AaronO I fiddled with my book.json file and got the gitbook to successfully build.

Thanks for getting back to me so quickly!
