### ISSUE TITLE
Pagination on gitbook.com not working

### ISSUE THREAD

**Issue by Dariusch** [GitbookIO/gitbook#564]
Hello,

I noticed a pagination problem. While on https://www.gitbook.com/search?q=language%3Aen there is a paginator at the bottom of the page which is not working.
The paginator is referencing to https://www.gitbook.com/search?page=1 while overriding the query.

Manually adding the page parameter seem to work: https://www.gitbook.com/search?q=language%3Aen&page=1 

just fyi

**Comment by SamyPesse** [comment]
Thanks :) I'll fix this error
