### ISSUE TITLE
Document how to create, deploy and use custom themes?

### ISSUE THREAD

**Issue by davidascher** [GitbookIO/gitbook#566]
Some pages on the web talk about using plugins, some say that themes need to be npm modules with the `gitbook-theme-*` name convention, some say to use npm to install themes, some imply to use `gitbook install` to install them.

I'm happy to be a guinea pig if it helps.  I'd like to make a theme which is not likely useful as is for anyone else, but can be public and open source.

**Comment by SamyPesse** [comment]
I'm working on the version 2.0.0 that will bring important changes to plugins (https://github.com/GitbookIO/gitbook/pull/562).

I'll then finish to write the documentation to include infos about plugins and themes. (https://github.com/GitbookIO/documentation/tree/version/2)

**Comment by davidascher** [comment]
Wonderful. Looking forward to it.

**Comment by erlend-sh** [comment]
Custom themes would be huge. With more documentation-oriented themes available, GitBook could easily compete with the likes of [ReadMe.io](http://readme.io/). In my opinion it would be far superior thanks to its fat-free editor and tight GitHub integration.

**Comment by bijanebrahimi** [comment]
I'm developing a compatible gitbook-cli using python. what I'm looking for is documentation of how to be compatible with already existing themes. is there any documentations/instructions to show the structure of variables available to themes?

I know one way is to look in already existing themes (Which I did) but still there should be another standard way.
