### ISSUE TITLE
Images missing in EPUB

### ISSUE THREAD

**Issue by znmeb** [GitbookIO/gitbook#570]
My book (https://www.gitbook.com/book/znmeb/osjourno-tools/) has some images in it that are Imgur links to screenshots. The online version has the images, the PDF has them and the MOBI has them but the EPUB doesn't seem to have them. This is with the online build; I haven't tried building locally yet.

**Comment by znmeb** [comment]
This looks like a Calibre problem. I can reproduce it locally on my workstation using 'gitbook epub' and 'gitbook mobi'. Calibre is Fedora's Calibre - 2.15.0. 

I'll probably switch to images stored with the text rather than fetched from Imgur given this bug, so it's not terribly urgent to get a fix.

**Comment by SamyPesse** [comment]
In the new version 2.0.0, I'm handling svg images correctly (download and conversion). I'll add the download for the external images in the ebook format.

**Comment by znmeb** [comment]
These are PNGs (screenshots), not SVGs. There will be some SVGs in the final book, though.

**Comment by SamyPesse** [comment]
I understood, the new version will support all the cases:

For an ebook:
- local svg -> convert it to png
- remote svg -> download it -> convert it to png
- remote png/jpg/gif/.. -> download it
