### ISSUE TITLE
retina version of favicon

### ISSUE THREAD

**Issue by clkao** [GitbookIO/gitbook#575]
our favicon needs an upgrade for retina display.

![2015-02-02 8 27 29](https://cloud.githubusercontent.com/assets/69736/6000538/f5e9ca46-ab19-11e4-9e5c-6b8d1c66062b.png)

**Comment by AaronO** [comment]
:+1: 

We have a repo with all the logos here: https://github.com/GitbookIO/logos, I'll add the `favicon.ico` there and then you can make sure it works nicely for retina displays :)

BTW, I have a pending PR (that I should merge), that changes the logo (with a few corrections IMHO) : https://github.com/GitbookIO/logos/pull/1.

Let me know what your thoughts are and if that sounds good to you !

**Comment by lgzhang** [comment]
??????????????????????

------------------ 原始邮件 ------------------


    
        发件人: AaronO  <notifications@github.com>;
    
    
        发送时间: 2015-02-02 20:33:50
    
    
        收件人: GitbookIO/gitbook  <gitbook@noreply.github.com>; 
    
    
        抄送: (无); 
    
    
        主题: Re: [gitbook] retina version of favicon (#575)
    

   We have a repo with all the logos here: https://github.com/GitbookIO/logos, I'll add the favicon.ico there and then you can make sure it works nicely for retina displays :)  BTW, I have a pending PR (that I should merge), that changes the logo (with a few corrections IMHO) : GitbookIO/logos#1.  Let me know what your thoughts are and if that sounds good to you !  —Reply to this email directly or view it on GitHub.

**Comment by wcandillon** [comment]
+1

**Comment by AaronO** [comment]
@wcandillon What resolution would it need to be ?

The logo's with their `svg` sources and output `png`s are all open here : https://github.com/GitbookIO/logos.

(You need `svgexport` and imagemagick to build)

**Comment by wcandillon** [comment]
I just get the gitbook package from npm, do I need to update the version?
