### ISSUE TITLE
Confused about plugin

### ISSUE THREAD

**Issue by poppinlp** [GitbookIO/gitbook#579]
I add this to `book.json`:

```
// others config...
plugins: ["ga"]
```

And i run `gitbook install ./` or `gitbook install --config book.json ./`.
But plugin ga not installed, otherwise a plugin named `mathjax` installed.

Then i install plugin ga by `npm install gitbook-plugin-ga`. I can see it in node_modules dir.
I run `gitbook build --config book.json -o book ./`, but plugin ga not work.
I havn't see any error log, but actually i have no config for plugin ga and there should be a error log as "Need to option 'token' for Google Analytics plugin".
So this means plugin not be called at all. 

Very confused about this and want some help. THX.

**Comment by kmelve** [comment]
I had the same problem. I fixed it by validating and fixing my book.json-file. If it’s not validated, your build will just ignore it.

**Comment by SamyPesse** [comment]
@kmelve this bug has been fixed in the 2.0.0 (currently in alpha°, now if the book.json is not valid, the build will failed with a message.

**Comment by poppinlp** [comment]
@kmelve 
Thanks. That's really help.

@SamyPesse 
Add some explanation for this in RAEDME.md for current Version 1.x.x may be better?
