### ISSUE TITLE
Build Error; Still Failing: nasirkhan/bengali-wikipedia-user-guide 

### ISSUE THREAD

**Issue by nasirkhan** [GitbookIO/gitbook#583]
I am writing a book at https://www.gitbook.com/book/nasirkhan/bengali-wikipedia-user-guide/ and here is the Github repo https://github.com/nasirkhan/wikipedia-guide. 

recently i am getting build errors like the following 
```
The build 4138f61 of your book nasirkhan/bengali-wikipedia-user-guide has failed in 9.469 seconds.

Access your build details to fix it and publish a new version. Check out the list of common errors.
```

I have added the screenshot of the email and the build details page.
Email:
![screenshot-mail google com 2015-02-05 02-43-03](https://cloud.githubusercontent.com/assets/396987/6049367/fc5c3526-ace0-11e4-8392-5c865a7e5227.jpeg)
Build Details:
![screenshot-www gitbook com 2015-02-05 02-42-38](https://cloud.githubusercontent.com/assets/396987/6049366/fc50aaee-ace0-11e4-8689-03582f7b7de3.jpeg)

**Comment by SamyPesse** [comment]
We are taking a look at this error

**Comment by AaronO** [comment]
@nasirkhan Hi, your error is really very strange, it seems to be coming from Amazon's S3 service, we're actively looking into it.

Sorry for the inconvenience, we'll keep you updated.

**Comment by AaronO** [comment]
@nasirkhan The bengali filenames are causing a piece of infrastructure code to crash (`git` in fact). This a really strange/rare edge case, I'm working on a fix right now, that should be shipped today or tomorrow. (utf-8 is indeed handled correctly, but this is even stranger than that).

Sorry for the inconvenience @nasirkhan, I'll update as soon as there's news !

**Comment by nasirkhan** [comment]
Thanks for looking into it.

it was really strange for me too. because as you seen that it builds a part
of the book and the suddenly stopped, even i reverted all the changes of
the Summary.md but it is still failing.

--
Nasir Khan
http://nasirkhn.com

**Comment by AaronO** [comment]
@nasirkhan I've now deployed a fix to production. All now works as expected :)

To test, I cloned your repo and created a dummy book using your source (see screenshot), that now works :) (it failed before obviously):

![screen shot 2015-02-05 at 3 02 18 am](https://cloud.githubusercontent.com/assets/949223/6053730/7abba9e0-ace3-11e4-8dd1-d4bc30f695cb.png)

So next time you push code it should build as expected :)

**Comment by AaronO** [comment]
@nasirkhan Another thing that I noticed is that your `SUMMARY.md` is wrongly structured, you have :

```
# Index

*[Intro](README.md)
*[ভূমিকা](manuscript/ভূমিকা.md)
*[উইকিপিডিয়া - কী ও কেনো](manuscript/উইকিপিডিয়া - কী ও কেনো.md)
*[বাংলা উইকিপিডিয়া](manuscript/বাংলা উইকিপিডিয়া.md)
*[উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো](manuscript/উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো.md)
```

When you should have : 

```
# Index

* [Intro](README.md)
* [ভূমিকা](manuscript/ভূমিকা.md)
* [উইকিপিডিয়া - কী ও কেনো](manuscript/উইকিপিডিয়া - কী ও কেনো.md)
* [বাংলা উইকিপিডিয়া](manuscript/বাংলা উইকিপিডিয়া.md)
* [উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো](manuscript/উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো.md)
```

You need the space between `*[` => `* [`, because otherwise it's not considered a `markdown` list. (`markdown` considers list elements lines that start with `*`, so that's why it needs the extra space, if you have `*[` it will get confused and won't consider it a list element, and then `gitbook` won't recognize it).

**Comment by AaronO** [comment]
@nasirkhan With all that, everything should work as expected on [GitBook.com](https://www.gitbook.com) :)

One small thing I noticed though, is that `chrome` doesn't seem to "like" the bengali URLs locally (when testing with `gitbook serve`), but don't worry everything works well in production ! :tada: 

**P.S:** That was a pretty hard bug! One of the hardest (most obscure so far) ... ^^ Sorry for the inconvenience caused. And please let me know if you have any other questions !

**Comment by nasirkhan** [comment]
@AaronO thanks for solving the issue. :smile: 

I changed the `SUMMARY.md` in different ways when i found each push is failing.
