### ISSUE TITLE
Glossary is too greedy

### ISSUE THREAD

**Issue by kmelve** [GitbookIO/gitbook#588]
It seems that the glossary parser is too greedy in version 2.0.0.

The term in the glossary

    # Variabler
    Variabler er et annet…

HTML-dump from the website-version:

    <a href="GLOSSARY.html#variabler" class="glossary-term" title="Variabler er et annet ord for egenskaper eller kjennetegn i det utvalget som undersøkes. Dersom utvalget betsår av personer vil altså variabler være egenskaper hos disse. For eksempel kjønn, alder, bosted og inntekt. Med variablenes verdier mener vi de mulige egenskapene (verdiene) enhetene kan ha på én variabel. For eksempel gis variabelen «kjønn» to mulige verdier; mann eller kvinne.">variabler kan det være interessant å undersøke for å identifisere mulige sammenhenger og påvirkningsforhold.</a>

![screen shot 2015-02-06 at 06 29 14](https://cloud.githubusercontent.com/assets/1131579/6074939/8ac15f92-adc9-11e4-8601-75fcfde91f9c.png)

**Comment by SamyPesse** [comment]
Ok, the problem is coming from here https://github.com/GitbookIO/gitbook/blob/version/2.0/lib/utils/page.js#L25

I need to add better testing for this then fix the problem.

**Comment by SamyPesse** [comment]
Fixed, it will be in the next alpha version (tonight or tomorrow).
