### ISSUE TITLE
2-way integration between GitBook and GitBook

### ISSUE THREAD

**Issue by thenasko** [GitbookIO/gitbook#591]
Is there a way to integrate 2-ways between gitbook and github. I have a number of collaborators, and some of them prefer the simple GitBook editor, and some the more advanced git interface. I can't find a way to make GitBook push its changes to github after saving from the online editor.

Any help would be greatly appreciated. Thanks in advance!

**Comment by SamyPesse** [comment]
Take a look at http://help.gitbook.com/github.html

If you linked a GitHub repository to your GitBook, the online editor will edit directly the GitHub repository

```
webeditor -> github api -> github repo -> webhook -> gitbook build -> pdf,website, mobi, epub
```

Are you talking about the old editor or the webeditor ?

If you're talking about the old editor, they should not publish to GitBook directly from it but instead use something like [GitHub for Mac](https://mac.github.com) or [GitHub For Windows](https://windows.github.com).

**Comment by thenasko** [comment]
Thanks, I think the issue was with lack of permissions. Actually, I ran into another issue which was a little confusing.

I updated the permissions, reconnected the gutbhub repo, and added the hook. At that point, the web editor told me the "repository is empty". It seems that the web backend didn't populate the new github repository using the old gitbook one. Instead it showed me a black slate. Fortunately, I had a copy of the old repository on my machine and fixed the issue, but I think this would be a scary experience for some users.

**Comment by justin808** [comment]
@thenasko Can you please share some details on the lack of permissions? I'm still a bit foggy in if 2-way integration works and/or is a good idea. For example, I don't want a zillion commits to the master branch on my open source project for every edit. I'd like public edits to go through a PR process, as is currently done on github.

**Comment by thenasko** [comment]
The problem I had run into is I had to permission my collaborators both from GitBooks and through GitHub. I am not sure if GitBook changed the workflow so far, but that was the case last year when I tried.

Regarding your comment about "zillion commits", my understanding is that the current editor performs a commit for every save you make. If you want to aggregate the smaller commits or just make larger ones, you can go use git directly.
