### ISSUE TITLE
github integration does not work after change book owner

### ISSUE THREAD

**Issue by kedych** [GitbookIO/gitbook#593]
This is my gitbook: https://www.gitbook.com/read/book/ndc/newtaiwan
I have integrated with this: https://github.com/white-book/newtaiwan

The owner was me, everything works very well. After changing the owner, I got this problem:

I can see the content in both editor and github, however, I edit the book, click save, nothing build.

I am sure that the modified content is sync with github. I can see the commit history at github.

The book shows the original content. In the "book history" shows nothing build.

Could you please tell me how to solve the problem?

Best regards,
Kedy

**Comment by SamyPesse** [comment]
Hi

You can try add back the "webhook" at https://www.gitbook.com/book/ndc/newtaiwan/settings/github

The problem was that the webhook in your GitHub settings was using the old book url instead of the one with the new owner.
