### ISSUE TITLE
Navigating to Glossary fails

### ISSUE THREAD

**Issue by johnlindquist** [GitbookIO/gitbook#595]
2.0.0alpha6

Glossary hovers work correctly, but when you click, it takes you to the wrong address:
http://localhost:4000/chapters/GLOSSARY.html#find
when it should be
http://localhost:4000/GLOSSARY.html#find

![image](https://cloud.githubusercontent.com/assets/36073/6092966/4c07a182-aeb2-11e4-96df-3d9d24251e94.png)

**Comment by johnlindquist** [comment]
Also, the rendered .pdf is completely empty. Not sure if this is related, or if I should open a new issue.

**Comment by SamyPesse** [comment]
Please open an issue another issue for the PDF :+1:
