### ISSUE TITLE
gitbook pdf generates empty glossary

### ISSUE THREAD

**Issue by johnlindquist** [GitbookIO/gitbook#596]
2.0.0 alpha 6

Clicking on term defined in the glossary worked, but the glossary page was empty

![image](https://cloud.githubusercontent.com/assets/36073/6094652/9fc1a046-aef0-11e4-9e22-706d51c2380e.png)

My glossary in case it matters: https://gist.githubusercontent.com/johnlindquist/82b31f2efee2df2b6a98/raw/5388c5001e762afa05719b624cc695819ef98573/gistfile1.md

**Comment by SamyPesse** [comment]
Fixed in `2.0.0-alpha.7`, it will be live in gitbook.com in less than an hour

**Comment by johnlindquist** [comment]
Confirmed fixed in 2.0.0-alpha.7. Thanks!
