### ISSUE TITLE
Infinite redirect in Gitbook

### ISSUE THREAD

**Issue by jerryinfinity** [GitbookIO/gitbook#598]
Hi,

I am a collaborator to the thenasko/mathematics-in-the-world book. I can open the web dashboard, but going to the editor results in an infinite redirect. Would it be possible to look into the issue? There are two other people on my team who are also running into this.

Thanks in advance!

Best,
Jerry

**Comment by SamyPesse** [comment]
I'm looking at the issue, please next time contact us at https://www.gitbook.com/contact for issues related to the gitbook.com platform :)

**Comment by SamyPesse** [comment]
Ok, I understand the error, it looks like your GitHub account linked to your GitBook account doesn't have access to write the GitHub repository.

I'm goign to fix the redirection loop and add an error message in this case, but the owner of the github repo: thenasko/mathematics-in-the-world needs to give you write access on GitHub.
