### ISSUE TITLE
Cannot fetch gitbook

### ISSUE THREAD

**Issue by sebgoa** [GitbookIO/gitbook#60]
Hi, I am trying to reinstall gitbook on a fresh ubuntu 12.04 and I get this:
# npm install gitbook -g

npm http GET https://registry.npmjs.org/gitbook

npm ERR! Error: failed to fetch from registry: gitbook
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /opt/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-58-generic
npm ERR! command "node" "/usr/bin/npm" "install" "gitbook" "-g"
npm ERR! cwd /opt
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: gitbook
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/npm-debug.log
npm not ok

strange...

**Comment by YxAc** [comment]
Thanks the above info.
