### ISSUE TITLE
"add summary entry" for file produces error

### ISSUE THREAD

**Issue by JackDougherty** [GitbookIO/gitbook#600]
I continue to receive this error on GitBook 2.0 using Chrome browser, both in my existing and brand-new books

1) Create a new file in the file tree
2) Right-click the new file to "add summary entry" to table of contents
3) Open the new entry in TOC, and error appears: "There is no existing file associated with this entry." See screenshot

![add-summary-entry-error](https://cloud.githubusercontent.com/assets/649719/6098670/550b5082-afb4-11e4-9d2b-121dd1df3ddd.png)

**Comment by SamyPesse** [comment]
A summary entry needs to be associated with a file (which contains the chapter content). Since you created an entry in the summary, when you want to open it, the editor ask it to enter an name for the file and it will create the file for you.

**Comment by AaronO** [comment]
@JackDougherty @SamyPesse While it's technically correct, I think the point here is that it's not terribly intuitive and slightly confusing.
