### ISSUE TITLE
Some chapters redirect to a 404 error

### ISSUE THREAD

**Issue by hgducharme** [GitbookIO/gitbook#603]
As of just recently, a few of my book's chapters when clicked on redirect to a 404 page. Everything has been fine and all of a sudden this started happening.

I have my gitbook integrated with github if that is relevant in any way.

**Comment by SamyPesse** [comment]
What is your gitbook url ?

**Comment by hgducharme** [comment]
[Link to online book](http://hgducharme.gitbooks.io/sql-basics/content/index.html)

[Link to repository](https://github.com/hgducharme/SQL-Basics)

**Comment by SamyPesse** [comment]
It looks like the problem is not coming from gitbook, for example:

The first entry in the summary (https://github.com/hgducharme/SQL-Basics/blob/master/SUMMARY.md) is pointing to a file tat doesn't exist:

```
* [Basic Syntax](select_statements/README.md)
```

Even in GitHub, the link are giving a 404: https://github.com/hgducharme/SQL-Basics/blob/master/select_statements/README.md

Let me know if I don't understand correctly the issue (with an exemple or chapter that exists but is giving a 404).

**Comment by hgducharme** [comment]
Thank you, I should have picked up on this earlier.

**Comment by hgducharme** [comment]
I'm pretty sure I fixed the problem, however it appears to still be redirecting to a 404. 

I went into the online edit page for my book and made sure the path for each chapter linked to the correct `.md` file. I also did the same for all the links in the `SUMMARY.md`. I then did a `git push` to my gitbook account and updated the build. Is there anything i'm missing? The links still direct to the old path (i.e. the path to the files that don't exist.)

**Comment by SamyPesse** [comment]
Yes it looks like the problem is coming from the `&` in the url: `http://hgducharme.gitbooks.io/sql-basics/content/table_variabes_&_set_operators/README.html`

I'll add an issue on GitBook.com to support this.

In the mid time, if you want your book to work, you can replace `&` by `and`.

**Comment by hgducharme** [comment]
I want to note that I have two chapters with the `&` operator in the name, and only the `table_variables_&_set_operators` chapter links to a 404. 

As opposed to the chapter `subqueries_in_the_from_&_select_clause` which correctly links to the right file path.
