### ISSUE TITLE
What's difference between the four type when create a new book?

### ISSUE THREAD

**Issue by leohxj** [GitbookIO/gitbook#604]
I can't found any illustration about the type.

When I create a new book, what type do I choose?

The type are: basic, science, exercise, quizzes.

**Comment by AaronO** [comment]
@leohxj Choosing one or the other won't affect what you can write ultimately with your book.

But they provide a starting point with some example content as well as some plugins relevant to what you're doing pre-installed.

If you chose `science` for example you get `plugin-mathjax` pre-installed and some content with some basic math formulas. Similar idea for `exercise` (programming exercises) and `quizzes`).

`basic` is really just the simplest GitBook with one chapter to start with.

So they're just convenient starting points to help you get started better/quicker :)

**Comment by leohxj** [comment]
@AaronO Got it! Thanks.
