### ISSUE TITLE
Support possibility to fork books hosted on gitbook

### ISSUE THREAD

**Issue by friedger** [GitbookIO/gitbook#606]
Readers of a book should have the possibility to fork a book, edit it online and send a pull request.

Might be feasible with github based books and hosted on gitbook.io

**Comment by gamefroot-developer** [comment]
What do the gitbook developers think about this? Any chance we can bump this into the DEFINITELY AWESOME to have Milestone?

**Comment by michael-collins** [comment]
Would also really like to have this feature. I will be making many derivatives of my own book over time.
