### ISSUE TITLE
"Introduction", "Table of Contents" and "Glossary" are hardcoded on PDF

### ISSUE THREAD

**Issue by mariomelo** [GitbookIO/gitbook#607]
Although these two sections can be translated if I insert them in the **SUMMARY.md**, the pdf is always in English.

**Comment by SamyPesse** [comment]
Are you using the `2.0.0-alpha` ?

If yes, it's working fine for me, just specify a language in the book.json (except if your book is multilingual).

**Comment by mariomelo** [comment]
Yep. I'm using 2.0.0-alpha.7. Thanks for your answer!

How do I set a default language?

**Comment by SamyPesse** [comment]
In your `book.json`:

```
{
     "language": "fr"
}
```

**Comment by mariomelo** [comment]
Thanks a lot, @SamyPesse!

**Comment by SamyPesse** [comment]
You're welcome :+1:

**Comment by mariomelo** [comment]
Hum, just a little thing: The **Glossary** title is always in english. It shows just right at the TOC, but the section title still in english.

Just a tiny thing, I guess.

**Comment by SamyPesse** [comment]
Fixed by 4079de95879fa340ed36c2678ba918a837123683

**Comment by SamyPesse** [comment]
Fixed in `2.0.0-alpha.8`
