### ISSUE TITLE
Gitbook Domain configure help page shows 404 error

### ISSUE THREAD

**Issue by nasirkhan** [GitbookIO/gitbook#610]
Quick tip — Add your custom domain names here then point your DNS to GitBook.
http://help.gitbook.com/book/domains.html show 404 error

**Comment by SamyPesse** [comment]
Thank you, I fixed it, it will soon be in production, in the mid-time here
is the correct link: http://help.gitbook.com/platform/domains.html

On Sat, Feb 14, 2015 at 8:35 PM, Nasir Khan Saikat <notifications@github.com
> wrote:

> Quick tip — Add your custom domain names here then point your DNS to
> GitBook.
> http://help.gitbook.com/book/domains.html show 404 error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/610>.
>



-- 
Samy Pessé
GitHub <https://github.com/SamyPesse> | Twitter
<https://twitter.com/SamyPesse> | LinkedIN
<http://www.linkedin.com/in/samypesse/>

**Comment by nasirkhan** [comment]
thanks for the update :)
