### ISSUE TITLE
content reference doesn't work in 2.x.x on gitbook.com

### ISSUE THREAD

**Issue by jgabios** [GitbookIO/gitbook#614]
I am editing a book online and I do this in a page:
{% include "git+https://github.com/ethereum/cpp-ethereum.wiki.git/Building-on-Ubuntu.md" %}
in order to include this page:
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu
I get the source in the preview
{% include "git+https://github.com/ethereum/cpp-ethereum.wiki.git/Building-on-Ubuntu.md" %}

**Comment by SamyPesse** [comment]
The preview is not handling content reference and templating syntax.

If you're building with the builder version 2.0.0, it will work fine during build.
