### ISSUE TITLE
Pandoc via LaTeX as PDF maker

### ISSUE THREAD

**Issue by maxheld83** [GitbookIO/gitbook#616]
following up on #307, the Rmarkdown R package also includes an impressive function to make PDFs (via Pandoc and genuine LaTeX) – they are, I have to say, a lot prettier than the PDF generated by gitbook.io.

I am again not sure how feasible running LaTeX on your backend would be, but this sure would make very, very nice PDFs – and it takes any markdown as input (because Rmarkdown is just a superset). 

Anyway, I really dig the idea that rmarkdown might become the new standard for more complex, technical/scientific writing, irrespective of what kind of output you like at the end of the day.

Would be nice to see a marketplace/platform like gitbook.io leverage this tech.

**Comment by znmeb** [comment]
For a quick hack, you can use RMarkdown to generate a "knitted" document as regular Markdown, which you can then render with GitBook. That's the approach I'm taking for the moment, until I see how the resulting books look.

My experience with ebook toolchains is that everything works for HTML, but that you either get a good-looking PDF or you get a good-looking EPUB and MOBI, but not both. It's the same issue the responsive web design folks have trying to build something that works on an iPhone 1, a big iPad and a 1280x800 laptop.

**Comment by maxheld83** [comment]
yeah, that's my experience, too @znmeb .
I wonder though, whether `rmarkdown` and `knitr` might finally change that; `rmarkdown` can make *really* pretty, full-blown LaTeX documents.

I was wondering whether @SamyPesse might be interested in using this toolchain (rmarkdown) as a backend; should be relatively easy to have it read in the options and structure set in `SUMMARY.md`, and then just make a properly typeset book.

I can see one big disadvantage and I have no idea how severe it would be for the hosted part of gitbook.io – LaTeX takes up a lot of space in a VM, and LaTeX is a resource hog.

**Comment by znmeb** [comment]
FWIW I'm planning on spending some time tomorrow getting an RMarkdown - knitr - Pandoc EPUB and EPUB3 test case working. It turns out that if you compile R from source, it can now make EPUB and MOBI versions of the manuals via Calibre! See section 2.3 in http://cran.rstudio.com/doc/manuals/r-release/R-admin.epub for the details. 

My test case will include EpubCheck and maybe FlightCrew as well. I'm not sure where it'll be posted - probably on BitBucket somewhere in https://bitbucket.org/znmeb/osjourno/src/103e1469f49dc35903b0bf4339ac760a38f2d928/4Experimental/

**Comment by maxheld83** [comment]
Just changed the title: `RMarkdown` is obviously only a wrapper to Pandoc and LaTeX, so this isn't really about `RMarkdown` at all.
Still, I'd love to see better, pro-grade PDF output from Gitbook, and LaTeX via Pandoc have essentially accomplished this. (Problem being, of course, how to do this serverside, since LaTeX is huge and a pain).

**Comment by aepstein** [comment]
Some framework for multiple PDF backends would be useful.  Asciidoctor -> dblatex also makes a high quality book and open up a number of asciidoc/docbook features absent from the markdown toolchain.

**Comment by urosjarc** [comment]
# gitbook-plugin-build

<br>

[![npm release][npm]][npm-url]
[![Travis][travis]][travis-url]
[![Coverage Status][coverage]][coverage-url]
[![Dependency Status][dep]][dep-url]
[![Codebeat badge][codestyle]][codestyle-url]
[![Docs Status][docs]][docs-url]
[![Join the chat][chat]][chat-url]

> Extends gitbook build system with pandoc converter.

[![Patreon User][support]][support-url]
[![Twitter User][twitter]][twitter-url]

[npm]: https://img.shields.io/npm/v/gitbook-plugin-build.svg
[npm-url]: https://www.npmjs.com/package/gitbook-plugin-build
[travis]: https://img.shields.io/travis/urosjarc/gitbook-plugin-build.svg
[travis-url]: https://travis-ci.org/urosjarc/gitbook-plugin-build
[coverage]: https://img.shields.io/codacy/coverage/574f24efb20948afac9ba998f3d159c3.svg
[coverage-url]: https://www.codacy.com/app/urosjarc/gitbook-plugin-build
[codestyle]: https://img.shields.io/codacy/grade/27e38bb72bdc4476b2e87e9926df0485.svg
[codestyle-url]: https://www.codacy.com/app/urosjarc/gitbook-plugin-build
[dep]: https://david-dm.org/urosjarc/gitbook-plugin-build.svg
[dep-url]: https://david-dm.org/urosjarc/gitbook-plugin-build
[docs]: http://inch-ci.org/github/urosjarc/gitbook-plugin-build.svg?branch=master
[docs-url]: http://inch-ci.org/github/urosjarc/gitbook-plugin-build
[chat]: https://badges.gitter.im/Join%20Chat.svg
[chat-url]: https://gitter.im/urosjarc/gitbook-plugin-build?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
[support]: https://img.shields.io/badge/patreon-urosjarc-green.svg?style=social
[support-url]: https://patreon.com/urosjarc/
[twitter]: https://img.shields.io/twitter/follow/urosjarc.svg?style=social&label=follow
[twitter-url]: https://twitter.com/intent/follow?screen_name=urosjarc

<br>

## Description

**GPP** (gitbook-plugin-build) extends [gitbook](https://www.gitbook.com/)
build system with [pandoc](http://pandoc.org/) converter. Pandoc is your
swiss-army knife when it comes to coverting files. **GPP** use pandoc
build system to convert and compile your book in variety of formats:

* **TeX formats**: LaTeX, ConTeXt, LaTeX Beamer slides
* **HTML formats**: XHTML, HTML5, and HTML slide shows using Slidy, reveal.js, Slideous, S5, or DZSlides.
* **Word processor formats**: Microsoft Word docx, OpenOffice/LibreOffice ODT, OpenDocument XML
* **Ebooks**: EPUB version 2 or 3, FictionBook2
* **Documentation formats**: DocBook, TEI Simple, GNU TexInfo, Groff man pages, Haddock markup
* **Page layout formats**: InDesign ICML
* **Outline formats**: OPML
* **PDF via LaTeX**
* **Lightweight markup formats**: Markdown (including CommonMark), reStructuredText, AsciiDoc, MediaWiki markup, DokuWiki markup, Emacs Org-Mode, Textile

Writing books with this plugin will be peace of cake. And here cake is **not a lie**!

<br>

## Homepage
For more informations please visit projects official homepage.
> [https://urosjarc.github.io/gitbook-plugin-build](https://urosjarc.github.io/gitbook-plugin-build)

<br>

## License
Copyright © 2016 Uroš Jarc

MIT License
