### ISSUE TITLE
per-paragraph comments

### ISSUE THREAD

**Issue by maxheld83** [GitbookIO/gitbook#617]
Especially for scientific work, per-paragraph comments would be fantastic, maybe with selected visibility.
I think medium.com has really nailed this one in terms of UI/UX.

**Comment by bebraw** [comment]
You could probably implement this as a plugin. Perhaps start hacking on top of something like [gitbook-plugin-reveal](https://github.com/mrpotes/gitbook-plugin-reveal) and [SideComments.js](http://aroc.github.io/side-comments-demo/). On `gitbook-plugin-reveal` side you would need to change it to render HTML per paragraph `SideComments.js` expects. Ie. just detect paragraph using marked lexer and inject like `gitbook-plugin-reveal` does. In addition you will need to implement a backend according to `SideComments.js` API unless you can find a ready one somewhere.

**Comment by SamyPesse** [comment]
This is something, we are still considering to improve the "reviews" feature of gitbook.com. I'll probably do it one day as a plugin.
