### ISSUE TITLE
2.0.0 published as 'latest'

### ISSUE THREAD

**Issue by steveklabnik** [GitbookIO/gitbook#618]
Sorry for not being mega familliar with NPM, but it appears that you've pushed the latest alpha incorrectly in some way. https://twitter.com/steveklabnik/status/570255057477894147 has the details.

**Comment by SamyPesse** [comment]
Oh damn ... Sorry ... I just fixed it.

```
$ npm view gitbook dist-tags
{ latest: '1.5.0', alpha: '2.0.0-alpha.9' }
```

**Comment by steveklabnik** [comment]
It's all good :) I wasn't aware of this `npm` behavior either.
