### ISSUE TITLE
typos on http://enterprise.gitbook.com (bottom)

### ISSUE THREAD

**Issue by maxheld83** [GitbookIO/gitbook#619]
says:

> Univeristies
> GitBook is great for writing papers of all sorts and event support TeX !

should be:

> *Universities*
> GitBook is great for writing papers of all sorts and *even supports* TeX !

(also, that tex support is not quite ready yet, right?)

**Comment by AaronO** [comment]
@maxheld83 Thanks, it's fixed (and in production).

LaTeX isn't supported, however TeX (math subset) fully is (through `mathjax` for now), the `2.0.0` release brings `mathjax` support to eBooks (`pdf`, `epub`, `mobi`) by rendering the formulas to SVGs and then to PNG :)

**Comment by maxheld83** [comment]
right, of course, I confused `TeX` with `LaTeX` – wishful thinking. (Or maybe I'd just be a nightmare).

**Comment by AaronO** [comment]
@maxheld83 `LaTeX` isn't bad per say, I think it has a lot of inherent complexity that makes it an unpleasant markup language to work with, powerful but unpleasant.

I think there's lots of cool things we can do with GitBook by striking that right balance of power and simplicity.

Maybe it makes sense to support `LaTeX` at some point, our backend is flexible enough to allow for that. Maybe I'm a bit too reluctant but I want to make sure we don't add unnecessary complexity and then again there would have to be some value that we would bring to `LaTeX` users.

**Comment by maxheld83** [comment]
agreed @AaronO – and I think there's a case to be made that maybe, with great stuff like RMarkdown and Pandoc out there, people shouldn't even use LaTeX as a markup anymore for most of the use cases.
I think it'll be unsurpassed for *typesetting* for some time, but for that purpose, it would suffice to live in the background.

Anyway – native Rmarkdown support as per #307  would be great for the academic market (myself included).
