### ISSUE TITLE
Need the theme i18n file in en

### ISSUE THREAD

**Issue by nasirkhan** [GitbookIO/gitbook#620]
I want to add Bengali (bn) for the theme, but there is no English file from where i can translate https://github.com/GitbookIO/gitbook/tree/version/2.0/theme/i18n. Can you please tell me where can i get the base En file?

**Comment by SamyPesse** [comment]
The en translation is inlined since it's the default message. You can search in the templates folder: `{% i18n`.

**Comment by SamyPesse** [comment]
For example: https://github.com/GitbookIO/gitbook/blob/version/2.0/theme/templates/website/glossary.html#L3

**Comment by AaronO** [comment]
@nasirkhan I gathered them for you : https://github.com/GitbookIO/gitbook/blob/5ec8a1f18c881a3bc17924ba103241f387eb0289/theme/i18n/en.json

I think it will be useful and make additional translations significantly easier :+1:

**Comment by nasirkhan** [comment]
submitted a Pull Request #621 to ad Bengali.
In the help doc it is not mentioned, how to configure the language in `book.json`. could you please tell me or update the doc please?

**Comment by SamyPesse** [comment]
You should set `language` in your book.json, If you're using gitbook.com and specify the language in your book settings, it will already be set during build.
