### ISSUE TITLE
How to change  default listening port when use gitbook to serve a site?

### ISSUE THREAD

**Issue by wanglf** [GitbookIO/gitbook#622]
When issue the command gitbook serve, server will listen at tcp port 4000.  How to customize the port ?
Case is that: when serving two books at same time, a collision happens.

**Comment by zaynetro** [comment]
`gitbook --port 3000 serve`

**Comment by destroyerofbuilds** [comment]
Using `gitbook-cli`:

```bash
./node_modules/.bin/gitbook --port 8989 serve

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Server.listen (net.js:1257:5)
    at Server.listen (/home/user/hbetts/.gitbook/versions/2.0.1/node_modules/tiny-lr/lib/server.js:154:15)
    at Promise.apply (/home/user/hbetts/.gitbook/versions/2.0.1/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/home/user/hbetts/.gitbook/versions/2.0.1/node_modules/q/q.js:741:41)
    at /home/user/hbetts/.gitbook/versions/2.0.1/node_modules/q/q.js:1304:14
    at flush (/home/user/hbetts/.gitbook/versions/2.0.1/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

This happens for all ports.

**Comment by wanglf** [comment]
Please check if port is already used by other service. 
> netstat -an | grep 8989

**Comment by prcweb** [comment]
I get collisions too - it looks like it's also starting up a live reload server each time on the same port:

1st call (gitbook --port 3000 serve):

Live reload server started on port: 35729

2nd call (gitbook --port 3001 serve):

... Uhoh. Got error listen EADDRINUSE :::35729 ...

I'm not sure how to get round this.

**Comment by Bodawpaya** [comment]
me too
I try
`gitbook --port 3000 serve`  ~> `Got error listen EADDRINUSE`
`gitbook --port 3001 serve` ~> `Got error listen EADDRINUSE`
`sudo gitbook --port 4000 serve` ~> `Got error listen EADDRINUSE`

**Comment by Bodawpaya** [comment]
I solved this problem using --lrport option
`gitbook --lrport 9999 serve`

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by ochukai** [comment]
thx @ruenin

**Comment by guihua** [comment]
@tw-statics thx

**Comment by ikingye** [comment]
gitbook --lrport 35730 --port 4001 serve

**Comment by ikingye** [comment]
gitbook --lrport 35730 --port 4001 serve
gitbook --lrport 35731 --port 4002 serve
gitbook --lrport 35732 --port 4003 serve
gitbook --lrport 35733 --port 4004 serve

**Comment by zjsen668** [comment]
thx @ruenin

**Comment by deleyva** [comment]
It was @ikingye answer the one that worked for me.

**Comment by Vivianluolita** [comment]
> 我使用--lrport选项解决了这个问题
> `gitbook --lrport 9999 serve`

Error: ENOENT: no such file or directory, stat 'C:\Users\61697\Desktop\lyj-todo\lyj-notes\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js' @tw-statics 可同时我报了这个错怎么办，有没有解决方法了
