### ISSUE TITLE
Version 2.0-alpha9: Nunjucks template interfering with sample code

### ISSUE THREAD

**Issue by ludovicofischer** [GitbookIO/gitbook#625]
If you write a programming book and your sample code contains `{{` and `}}`, gitbook interprets it as a template variable. This leads to parts of the sample disappearing or errors. One solution would be to allow the user to  nunjucks syntax, but would that work with plugins? http://mozilla.github.io/nunjucks/api.html#customizing-syntax

**Comment by SamyPesse** [comment]
There is a discussion about this started by @AaronO : https://github.com/GitbookIO/gitbook/pull/562#issuecomment-74573722

I don't know what is the best solution to solve this, templating is important for a number of users, @AaronO is against using `{% raw %}`, customizing template syntax seems pretty extreme, ...

**Comment by AaronO** [comment]
@ludovicofischer @SamyPesse I'm not against `{% raw %}` it's obviously necessary in some ambiguous cases.

However I think `{{ x }}` should fallback to `{{ x }}` if `x` is not defined, rather than ` ` (empty) since it's such a common use case.

**Comment by SamyPesse** [comment]
Ok, but this solution is really tricky since templating is not just printing variable as `{{ x }}`. Like I told you in the PR 2.0.0, just do a PR for this if you have a good idea on how to handle this correctly.

**Comment by k88hudson** [comment]
Not escaping the content of code blocks by default is pretty non-standard behaviour IMO, particularly for projects that are porting docs from markdown on github
