### ISSUE TITLE
allow link / upload to custom PDF

### ISSUE THREAD

**Issue by maxheld83** [GitbookIO/gitbook#626]
I'd like to "bring my own" PDF (made with RMarkdown / LaTeX), instead of the PDFs produced by gitbook.

Any chance we can have this as an option?

Maybe even link to whatever binary I have uploaded to a github release?

(I LOVE this project. Now I just have to get back to work and, you know, actually keep writing my book).

**Comment by SamyPesse** [comment]
No, we'll not add this as an option, we need to improve the PDF output.

But you can easily use an "hack" to do this: make a plugin that uses the "finish" hook to replace the output PDF by another file. It will work fine on gitbook.com ;)
