### ISSUE TITLE
Footnote 'links' opening new page [target="_blank"]

### ISSUE THREAD

**Issue by sirselim** [GitbookIO/gitbook#628]
First off thanks for the great software! Secondly, I'm quite new to this so it is possible I may be missing something obvious so my apologies in advance if this is a stupid question.

I've just moved over to a new laptop with a fresh install and as such have pulled the latest gitbook 2.0.0-alpha.9, on my old machine I was using 2.0.0-alpha.5.

After updating I've noticed that footnotes are no longer behaving as they were, they are in fact opening a new page upon clicking (both the footnote and it's return).

I'm using the below for footnotes which has been OK until now:
```
Using a footnote. [^fn1]

[^fn1]: my footnote
```
Upon inspecting the rendered html I notice that `target="_blank"` is now added to all links where as before the footnote links (tagged by: `<sup><a href=.... >..</a></sup>`) were exempt from this apparently.

My current work around is a bit of a hack using sed to find and replace the offending strings in all files recursively:
```sh
#!/usr/bin/bash
find ../_book -type f -exec sed -i 's/ target="_blank">fn/>fn/g' {} +
find ../_book -type f -exec sed -i 's/in the text." target="_blank">/in the text.">/g' {} +
```
Wondering if anyone else is noticing this or if it is something quirky with my new setup (quite possible as it's a fresh siduction install).

Any insight is much appreciated.

**Comment by SamyPesse** [comment]
The problem is coming from here: https://github.com/GitbookIO/gitbook/blob/version/2.0/lib/utils/page.js#L189

GitBook considers anchor links as absolute links.

I'm going to fix this right now.
