### ISSUE TITLE
Adding research notes to book project

### ISSUE THREAD

**Issue by BjoernSchotte** [GitbookIO/gitbook#629]
In book projects, you often do research before and when you're writing. Normally, I clip everything (notes, PDFs, screenshots etc) I need into Evernote, but that requires switching forth and back between Evernote (or any other tool) and gitbook infrastructure.

Of course one could create a research/ folder in the repo and add all the notes, PDF files etc. in there.

But, especially in WIP books, it would be great if an author could make his research accessible in the compiled book. This makes it more interactive, with the possibility for the public to add notes through comments (with the disqus plugin), make videos viewable (with plugin-youtube) etc.

These section(s) should be separated from the PDF/eBook, but available inside the web version as separate links and rendered content.

What do you think?

**Comment by SamyPesse** [comment]
One solution could be to use a conditional summary in GitBook 2.0.0.

I can make the generator name (`website`, `json` or `ebook`) accessible in the template context (https://github.com/GitbookIO/gitbook/blob/version/2.0/lib/template.js#L320), then your summary can be something like:

```
# My Summary

* [An article](article.md)
{% if gitbook.generator == "website" %}
* [Research Notes](./notes/README.md)
    * [My Node](notes/1.md)
{% endif %}
```

What do you think?

**Comment by BjoernSchotte** [comment]
Sounds great!
