### ISSUE TITLE
Difference between Gitbook 1.5.0 on Github and NPM

### ISSUE THREAD

**Issue by 13abylon** [GitbookIO/gitbook#630]
While playing with gitbook I noticed that the Gitbook Version 1.5.0 on Github is slightly different than the version on github. 
![image](https://cloud.githubusercontent.com/assets/1833374/6522260/4af50bfe-c3e3-11e4-8805-a8add4397f2e.png)

As you can see on the image the npm installation has a folder `themes/templates/book`. In github the folder structure is `themes/templates/website`. 
Is this intended?

**Comment by SamyPesse** [comment]
No it's not different than GitHub (tag 1.5.0): https://github.com/GitbookIO/gitbook/tree/1.5.0/theme/templates

I changed after that the folder name to follow the generator name.

**Comment by 13abylon** [comment]
I see. I looked at the master branch :)
