### ISSUE TITLE
Define languaje on book.json

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#632]
Now that we have i18n support, we could add a lang attribute in book.json defining the default languaje of the book (instead of english) so all the hardcoded texts like table of contents or glossary could be localized. This could help https://github.com/GitbookIO/gitbook/issues/504

**Comment by SamyPesse** [comment]
This is already done: `"language": "fr"`

I need to add it to help.gitbook.com

**Comment by piranna** [comment]
Yes, I saw it on the other issue, thank you! :-)

2015-03-07 14:34 GMT+01:00 Samy Pessé <notifications@github.com>:

> This is already done: "language": "fr"
>
> I need to add it to help.gitbook.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/632#issuecomment-77689462>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux
