### ISSUE TITLE
Code blocks are not shown

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#633]
In gitbook 2.0, when using a code block, markdown formated text and some template tags are shown. Probably this is related to the change to Kramed:

```
`{%	raw	%}	 bash	npm	install	 	{%	endraw	%}	 {%	raw	%}`
```

```
{%	endraw	%}	 {%	raw	%}`bash
PDF
npm	run	build
Sitio	web
npm	run	serve	`{%	endraw	%}``
```

This should be shown as

```bash
npm	install
```

```bash
# PDF
npm	run build
# Sitio web
npm	run serve
```

**Comment by SamyPesse** [comment]
What version are you using? it looks like you are using a version that is not released yet (I'm still working on it).

**Comment by piranna** [comment]
2.0.0, seems it's the one you need to set to get the latests code on master branch.

**Comment by piranna** [comment]
Thank you ;-)
