### ISSUE TITLE
 Error: unexpected token: }}

### ISSUE THREAD

**Issue by gantoday** [GitbookIO/gitbook#637]
sorry to trouble you one more time.but i have tried everything and couldn't fix it by myself.

https://github.com/GitbookIO/gitbook/issues/636

in this page you said that the problem is made by my system,i changed system to the lastet version ubuntu,and it could output Chinese now.but i meet new problem:

```$ gitbook epub ./
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: >> 0 plugins loaded 
info: start generation with epub generator 
info: clean epub generatorOK 
info: processing README.md 0% 
info: processing source/homestead.md 2% 
info: processing source/artisan.md 4% 
info: processing source/billing.md 6% 

Error: unexpected token: >```

my book source files: https://github.com/gantoday/laravel-docs-zh

please help me,many thanks.

**Comment by SamyPesse** [comment]
This should be fixed in `2.0.0-beta.1`

**Comment by gleicon** [comment]
Hi, is beta.1 the current repo ? If so I tried it again today but this bug is not fixed. I did as per instructions on the repo (cloning repo + gitbook versions:link 2.0.0-beta.1 ./gitbook). Any ideas or temporary workarounds ? It's code with Jinja2 template markings so a bit hard to switch from {{ }} inside ``` (code block) ``` ....Thanks

**Comment by SamyPesse** [comment]
The latest version is `2.0.0-beta.5`,  `{{` and `}}` are used by the templating engine (http://help.gitbook.com/format/templating.html), with the latest versions we are escaping code blocks.

You can also use: `{% raw %} {{ and }}  {% endraw %}` to escape these templating controls.

**Comment by gleicon** [comment]
I'm trying to link beta.5 to test before escaping everything with {% raw%} but I get this:

🍕 🍺 parvati:tmp gleicon$ gitbook versions:link 2.0.0-beta.5 ./gitbook

Error: EEXIST, symlink '/Users/gleicon/tmp/gitbook'

Any ideas ? I got from a fresh npm install to test this, maybe I need something else (not familiar with node.js and npm nowadays).

Thanks !
