### ISSUE TITLE
Generator doesn't work in windows

### ISSUE THREAD

**Issue by cloudwu** [GitbookIO/gitbook#639]
When I run `gitbook pdf` in windows, generator stopped by error:

```
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x
info: OK
info: >> 0 plugins loaded
info: start generation with pdf generator
info: clean pdf generatorOK
info: processing README.adoc 0%

Error: (C:\Users\Cloud\.gitbook\versions\2.0.0-alpha.9\theme\templates\ebook\page.html)
Error: template not found: C:\Users\Cloud\layout.html
```

Windows 7 64bit
node.js version is v0.12.0
gitbook 2.0.0-alpha9

**Comment by krishnaIndia** [comment]
Windows 7 64bit
node.js version is v0.12.0
gitbook 2.0.0-alpha9

Even am facing a similar issue.


Error: (C:\Users\<USERNAME>.gitbook\versions\2.0.0-alpha.9\theme\templates\website\page.html)
 Error: template not found: C:\layout.html

**Comment by SamyPesse** [comment]
I setup ci tests for Windows using Appveyor, I'll fix this issue.

**Comment by SamyPesse** [comment]
As soon as https://github.com/mozilla/nunjucks/pull/391 is merged, this will be good.
