### ISSUE TITLE
Unable to gitbook build - Cannot read property 'solutionNodes' of undefined

### ISSUE THREAD

**Issue by billy3321** [GitbookIO/gitbook#640]
I'm trying use gitbook.io to build my gitbook, which on github here: 

https://github.com/JRF-tw/shadow_of_justice

but it get error:

    Cannot read property 'solutionNodes' of undefined

May you please help me to find out where the problem is? Thank you.

**Comment by SamyPesse** [comment]
What is the link to the failing build ?

**Comment by billy3321** [comment]
https://www.gitbook.com/book/jrf-tw/shadow_of_justice/build/54feffa8e5afb6030055be56

Here it is.

**Comment by SamyPesse** [comment]
I switch your book to use GitBook 2.0.0 (in the book settings), and it works fine with the new version.

GitBook 2.0.0 will become the default version in the coming weeks.

The bug is coming from the quizzes parsing in GitBook 1.5.0, but in 2.0.0 quizzes parsing is only done in the quizzes plugin.

**Comment by billy3321** [comment]
Thanks!!
