### ISSUE TITLE
Table of Contents Not Displaying Correctly in Book Details Page

### ISSUE THREAD

**Issue by fvcproductions** [GitbookIO/gitbook#641]
So the details page for the GitBook I'm working on is located [here](https://www.gitbook.com/book/fvcproductions/cs-and-english/details).

The problem I'm having is that the Table of Contents on this details page is not displaying in the correct order. That is, all the subsections are scattered around and the main chapters are not in correct order. See screenshot below. 

![screenshot 2015-03-11 22 26 05](https://cloud.githubusercontent.com/assets/4284691/6611062/b3fe3eb4-c83d-11e4-8bce-db753cca2f59.png)

The repository is located [here](https://github.com/fvcproductions/GitBook) and is to up to date although the book itself is not actually integrated with GitHub.

I'm not sure what to change in order for the TOC to display in the correct order.

Any help would be much appreciated.

**Comment by SamyPesse** [comment]
It's fixed and I rebuild your book to fix it.

**Comment by fvcproductions** [comment]
Thank you!
