### ISSUE TITLE
Custom landing page has encountered an error

### ISSUE THREAD

**Issue by overtrue** [GitbookIO/gitbook#642]
When I enter any custom content, click the "Save" will prompt an error "Parameter 'url' must be a string, not undefined"：

![image](https://cloud.githubusercontent.com/assets/1472352/6613585/298da9bc-c8ca-11e4-875f-899a655aa19d.png)

http://overtrue.gitbooks.io/building-web-apps-with-laravel5/

please help me,thanks!

**Comment by SamyPesse** [comment]
Thanks I'm looking into the issue, next time for issues related to gitbook.com please contact us using: https://www.gitbook.com/contact

**Comment by overtrue** [comment]
OK， Thanks!
