### ISSUE TITLE
Setting author in book.json

### ISSUE THREAD

**Issue by wapmorgan** [GitbookIO/gitbook#649]
I propose add a configurable option like `author` in book.json to avoid pasting it in book title.

**Comment by CoDEmanX** [comment]
This option is not documented!
http://help.gitbook.com/format/configuration.html

**Comment by rschiang** [comment]
It should be noticed that on GitBook.com, there is no way to specify author's name other than your account name, the generator also ignores what `book.json` specifies.

Not sure if reporting the issue here is acceptable?
