### ISSUE TITLE
GitHub integration should have a caution, and can be made simpler

### ISSUE THREAD

**Issue by erlend-sh** [GitbookIO/gitbook#652]
First and foremost, thanks for a fantastic product. GitBook is a huge step forward for collaborative book editing, and I wish you all the best of luck onwards.

I've just started playing around with GitBook, and the biggest gotcha I've encountered thus far is the GitHub integration. Once it's working it's smooth, but the *transition* needs work.

1. **Add a caution:** Just like you've been nice enough to emphasise your hazardous options in the "Danger Zone", there should be a clear caution on the `/settings/github` page, not just in the docs.

2. **Transition is awkward:** Unless I misunderstood something, moving to GitHub involves the following:
 a. Enter valid repository and add deployment webhook
 b. Create a .gitignore containing the GitBook defaults
 c. Re-enter any docs you may have started working on.

Step A and C are probably unavoidable, but Step B (including the handy default pages + summary.md) could perhaps be automated? I.e. if either the proper .gitignore, README.md or SUMMARY.md is missing, the editor can offer to make these for you. Would save me a lot of effort every time I create a new book to be hosted on GitHub.

**Comment by gonter** [comment]
To perform steps b and c, create the github repository, then clone your *gitbook* repo on your local machine, add the github repo as an additional remote and push to the github repo.  This should do the trick without loosing any work.

However, the integration could be simpler.

GG

**Comment by erlend-sh** [comment]
I hadn't realised this was possible:

http://help.gitbook.com/github/transferring_to_github.html

That makes it considerably easier. Migration path would of course be even smoother if this was all doable within the comfort of the Gitbook interface as described above, but it's perfectly sufficient in its current state.
