### ISSUE TITLE
when editing a tall page, the preview scrolls to the top

### ISSUE THREAD

**Issue by lookfirst** [GitbookIO/gitbook#653]
If I'm editing a tall page, as soon as I type something on the editor side, the preview pane scrolls to the top of the page. I'd prefer the preview pane to stay where it is. =)

I have the sync option turned on.

**Comment by SamyPesse** [comment]
What browser are you using?

**Comment by lookfirst** [comment]
Latest chrome

**Comment by lookfirst** [comment]
Version 41.0.2272.89 (64-bit)

**Comment by lookfirst** [comment]
osx
