### ISSUE TITLE
markdown preview performance

### ISSUE THREAD

**Issue by lookfirst** [GitbookIO/gitbook#654]
If you put a lot of images on a page in the browser version of the editor, the performance of the page slows down considerably.

It appears as though one issue around the preview is that it redraws the entire DOM for the preview every single time a key is pressed.

Instead of redrawing the entire DOM every time, how about employing a diff/patch system like what React does? One idea would be to use [virtual-dom](https://github.com/Matt-Esch/virtual-dom#diff-computation) to do this.

I'd submit a pull request, but I can't seem to find the online editor source code. I found the desktop app, but that appears to be another version of the codebase.

**Comment by imf** [comment]
I have this same issue!

**Comment by SamyPesse** [comment]
@lookfirst Thank you for pointing me to **virtual-dom**, I'm currently integrating it in the previewer for the new release and performance are improved (for images, math preview, ..).

Thank you :+1: :beers: :heart:

**Comment by AaronO** [comment]
@SamyPesse We should have some benchmarks on large documents and it's possible that slow performance is coming from the `markdown => html` conversion rather than the dom rendering being slow. In which some simple debouncing etc might work for larger docs.

**Comment by lookfirst** [comment]
I'm glad @AaronO 's comment was deleted. :smile:

If any performance tests happen, they should happen on vdom alternatives. I just found another one...

https://github.com/fiduswriter/diffDOM

the demo is pretty neat (note the video stays playing)...

http://fiduswriter.github.io/diffDOM/demo/index.html

**Comment by lookfirst** [comment]
Theoretically, you could also use React, but I think that might not be worth downloading the whole framework for this one feature... http://facebook.github.io/react/docs/glossary.html

**Comment by SamyPesse** [comment]
It's already implemented using **virtual-dom**, it's working very well and it's fixing an issue for people who have a lot of maths in their pages.

**Comment by lookfirst** [comment]
@SamyPesse Great! Does this also fix https://github.com/GitbookIO/gitbook/issues/653 ? You can turn off whatever is causing the page to scroll cause now the dom won't be wiped out each time. The page should stay where it is on its own.

How do I get access to use this stuff? =)

**Comment by SamyPesse** [comment]
I don't think it's fixing #653. We are scrolling the preview to sync it with the editor.

We'll release the new version tomorrow :)

**Comment by lookfirst** [comment]
Right, but now you only need to do the sync when the editor changes it's scroll position, not when people type.
