### ISSUE TITLE
Uploading a cover.jpg doesn't provide feedback or update the cover.

### ISSUE THREAD

**Issue by imf** [GitbookIO/gitbook#655]
Steps:

Create a cover.jpg
Upload it  through Edit...Edit Book Cover.

Expected behavior: 1. Some feedback of a successful upload, and 2. cover updated in various views of the book.
Actual behavior: Progress spinny spins briefly, then stops with no error output or confirmation.

Note also that it took me a while to even figure out where this feature was exposed. Being able to edit inline where it tells me with a tool tip to make a cover.jpg would be nice, as would just being able to have a cover.jpg in the root of my repo.

**Comment by imf** [comment]
Apparently the update happened, but was not reflected in real time elsewhere in the UI. A later reload (many minutes later) showed that the cover had been updated. Again better feedback would help a lot here.

Note that so far I do like the product a lot.

**Comment by imf** [comment]
Note also that if you import the .MOBI produced into Kindle (e.g. Kindle for Mac) the cover thus created doesn't show up in the library view, but rather just shows up as a section in the book.

**Comment by SamyPesse** [comment]
Thank you for the feedback, we will release a great new version of the editor in the coming days, I'll fix this in this release.

Please post another issue for the mobi cover
