### ISSUE TITLE
Introduction links to Error 404 page

### ISSUE THREAD

**Issue by neomatrix369** [GitbookIO/gitbook#656]
Similar to this issue reported on https://github.com/GitbookIO/documentation/issues/17, but in our case the markdown pages are suffixed with a 'null' text at the end of the url for e.g. http://help.gitbook.com/README.htmlnull

Could this be address quickly please, as most of our links are generated from markdown pages. 

Link to our book: http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/

**Comment by neomatrix369** [comment]
This is a bug, and can I request you to address this bug asap, as you would help our community massively if you addressed this issue.

Its also affecting your documentation page and those of many others who have similar markdown pages generated off GitBooks.io.

**Comment by SamyPesse** [comment]
@neomatrix369 This is working fine for me (it has been fixed 2 days ago: https://github.com/GitbookIO/gitbook/issues/651)

**Comment by neomatrix369** [comment]
Okay thats great its fixed, I was only followingup on it as I didn;t receive any notification of it being fixed, as you can see I reported it 5 days go - https://github.com/GitbookIO/documentation/issues/17.

But thanks again, I'll take off the comment from our front page.

**Comment by SamyPesse** [comment]
Perfect :star2:  sorry for this bug
