### ISSUE TITLE
Issue when adding a collaborator !

### ISSUE THREAD

**Issue by neomatrix369** [GitbookIO/gitbook#657]
Just the other day we struggled getting write rights to a collaborator who first signed in via Github, and then via Gitbook and neither worked.

Although both accounts had write rights in my admin panel.

This is an impediment for a book that i written by a community of developers. Could this be addressed quickly, please.

Maybe you can check from the log activities on the account to see what must have transpired.

Link to our book: http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/

**Comment by SamyPesse** [comment]
What is the url of the book ? If you don't want to share it, contact us at https://www.gitbook.com/contact

**Comment by neomatrix369** [comment]
Just added to the description, sorry not doing it in the first instance.

**Comment by SamyPesse** [comment]
Your book source is hosted on GitHub (neomatrix369/adoptopenjdk-getting-started-kit), your collaborators have right-access on GitBook but maybe not on GitHub (they need both, since the web-editor is directly editing the GitHub repository).

**Comment by neomatrix369** [comment]
Okay so I ave to make them a collaborator on github as well ?

**Comment by SamyPesse** [comment]
Yes, they need to be able to push on GitHub. The error message they got has probably not clear enough, I'll try to improve this to make easier to understand.

**Comment by neomatrix369** [comment]
Yes UX is important, I can post images of the error message, so it might help you:

![error-useralreadyexists-connected-to-this-github-account](https://cloud.githubusercontent.com/assets/1570917/6719731/9840614e-cdb4-11e4-9d49-26f49c6f0bbc.png)
![error-useralreadyexists-connected-to-this-github-account2](https://cloud.githubusercontent.com/assets/1570917/6719732/98443062-cdb4-11e4-81c7-774d6f802251.png)
![you-dont-have-permission-to](https://cloud.githubusercontent.com/assets/1570917/6719733/98451b44-cdb4-11e4-98ea-ca7d3457ea62.png)

These three messages appeared for one of the collaborators.

**Comment by SamyPesse** [comment]
The two first error are related to http://help.gitbook.com/account/duplicate.html
The last one is related to the permissions on GitHub.com (what i told you before).

I'm working on improving the UX for this.

**Comment by mikebgx** [comment]
Hi Samy,

As per your conversation with Mani, I deleted my 2 (3?) accounts to start again, it won't let me, seems to have remembered my email address from an earlier attempt. Looks like we've added lots of cases for your unit tests :-)

![pastedgraphic-13](https://cloud.githubusercontent.com/assets/6433208/6720724/b012d596-cdbd-11e4-8b95-d4fea9274133.png)

**Comment by SamyPesse** [comment]
@mikebgx this user already exists: https://www.gitbook.com/@mikebgx

You should be able to login to this account (reset the password if needed), then try linking your GitHub account, if it's not working, logout then login with GitHub and delete the account, then login back with `mikebgx`.

**Comment by mikebgx** [comment]
Thanks I can login now.

**Comment by SamyPesse** [comment]
You're welcome :)
