### ISSUE TITLE
Unable to gitbook build - Cannot read property 'solutionNodes' of undefined

### ISSUE THREAD

**Issue by badboy315** [GitbookIO/gitbook#658]
I'm trying use gitbook.io to build my gitbook on gitbook.com,  which on github here:

failde here: https://www.gitbook.com/book/badboy315/pythoncamp0/build/550a141b7206f20300d5478e
==========================

Tweaking book.json
Installing plugins
Install plugins in /tmp/book
Install plugin autocover from npm (gitbook-plugin-autocover) with version *
Install plugin mathjax from npm (gitbook-plugin-mathjax) with version *
gitbook-plugin-mathjax@0.0.6 node_modules/gitbook-plugin-mathjax
Successfully installed plugins!
Building Site, will upload
Starting build ...
Cannot read property 'solutionNodes' of undefined

===========================

**Comment by SamyPesse** [comment]
Same as #640 , I rebuild your book with GitBook 2.0.0: https://www.gitbook.com/book/badboy315/pythoncamp0/build/550a7d510a0cb30300f7fc83
