### ISSUE TITLE
Let gitbook process .md files outside of SUMMARY.md

### ISSUE THREAD

**Issue by achton** [GitbookIO/gitbook#659]
It seems to me that there is no way to create pages that are not part of the `SUMMARY.md`?

Ie. from `README.md` I would like to create a `[link to a page](./core-update.md)` where `core-update.md` is not part of the `SUMMARY.md`.

What happens is that the link itself is altered to link to the corresponding .html output file, but in reality the .md file itself is moved into the output dir, eg:

```
-rw-rw-r-- 1 aw aw    10 Mar 18 22:58 core-update.md
-rw-rw-r-- 1 aw aw 15016 Mar 18 22:58 faq.html
-rw-rw-r-- 1 aw aw 14862 Mar 18 22:58 git.html
drwxrwxr-x 2 aw aw  4096 Mar 18 22:58 ng
-rw-rw-r-- 1 aw aw 14861 Mar 18 22:58 README.html
```

How can I create pages that do not appear in the summary?

**Comment by aschempp** [comment]
I do have the same problem. I would probably be able to provide a pull request for that, but I have no idea what the best approach would be? I think simply processing all markdown files is not the ideal solution. Should we configure the additional files in the `book.json`? Or add something to the summary that is not added to the navigation?

**Comment by jonjack** [comment]
Would be a useful feature I think. Similar issue [here](https://github.com/GitbookIO/gitbook/issues/81) was closed.

**Comment by ClintH** [comment]
:+1:

**Comment by solacerg** [comment]
:+1:

**Comment by mweststrate** [comment]
:+1:

**Comment by luisherranz** [comment]
ouch!

👍

**Comment by ekristen** [comment]
bump .. +1 to this

**Comment by jsntn** [comment]
+1

**Comment by bandantonio** [comment]
+1 This is a highly requested feature for me

**Comment by jmmiracle** [comment]
we need this feature too.change the validation rules of  summary.md. allow empty dir name

**Comment by nilswald** [comment]
+1
a possible solution could be to at least follow (and process) all links in the book

**Comment by rafecolton** [comment]
A workaround is to add them to `SUMMARY.md` and hide them with CSS, but it's kind of ugly:

```css
.summary .chapter[data-path="file.html"] {
  display: none;
}
```

**Comment by AaronO** [comment]
I see there's a lot of interest here in this issue, can you provide a few user-stories so we can better understand the use case and if it makes sense support it out of the box without any hacks.

**Comment by bandantonio** [comment]
@AaronO Below is our real world case that we cannot implement due to this limitation. 
Currently we have API-related documentation and we created a step-by-step guide describing how to configure test environment, so people can play around with API requests. We want to just include this guide somewhere in the body as a hyperlink and refer to it from another gitbook page as a source of additional information. This guide is not intended to be listed in SUMMARY as a separate section according to the existing doc structure. 

I think there are many other examples when some pages should not be included in SUMMARY, but they should be somewhere in text. By adding some secondary pages in SUMMARY with the only purpose to make them available throughout gitbook (as currently there is no other workaround) can make a real mess in structure and mislead readers.

**Comment by rafecolton** [comment]
> I think there are many other examples when some pages should not be included in SUMMARY, but they should be somewhere in text. By adding some secondary pages in SUMMARY with the only purpose to make them available throughout gitbook (as currently there is no other workaround) can make a real mess in structure and mislead readers.

@AaronO our use case matches the above sentiment pretty exactly. Being able to exclude pages from the nav while still compiling them helps to balance the length of the side nav with the length of individual pages. 

I recently wrote a page where one section under an H2 was about 3 times as long as the other sections on the page. I split it out into its own page so the canonical page flowed better, but that separate page is only relevant in the context of the canonical page from which it was split. So someone might be given direct access to the sub page or might click into it from the canonical, but they would never need to access it from elsewhere in the book. Given that, I didn't want to make the nav any longer than it has to be.

**NOTE:** There are also use cases for *not* compiling select pages. For example, if we want to include raw markdown into a different layout such as in https://github.com/rafecolton/presentation-tool. It would be helpful to also retain the ability to *not* compile certain pages. Probably better to assume all pages need to be compiled and provide an explicit way to leave a page as markdown.

**Comment by thenathanjones** [comment]
My use case is I'm using Gitbook for documentation of a source code repository, one of the bits of documentation is some Architecture Decision Records. I want to be able to link to them from the top level of the section, but I don't want them in the summary. At the moment, there are only a couple, but over time there could be hundreds which would make the sidebar useless.

**Comment by luisherranz** [comment]
Same use case for us. Sometimes we want to link to articles which we don't want to be in the summary.

**Comment by larsyencken** [comment]
Another use case: you want to use a Gitbook to organise and structure a huge number of files, far more than the summary could easily allow in TOC format. Then each subchapter would ideally have many files which Gitbook would discover and compile.

**Comment by sbkg0002** [comment]
👍

**Comment by emersonp** [comment]
Not being able to include pages in a book unless you reference it in the table of contents makes for a very shallow book. Also requested.

**Comment by sbkg0002** [comment]
Anyone experience with an alternative?

Op 8 nov. 2017 18:40 schreef "Parker Harris Emerson" <
notifications@github.com>:

**Comment by tuga1975** [comment]
Have anyone further details about the issue? In my case, I have a simple table with several links to other .md files. I do not want to put these files at the ToC because doesn't make sense and is going to pollute the ToC.

**Comment by sbkg0002** [comment]
Same problem here, but no solution I'm afraid.

Op 30 nov. 2017 13:15 schreef "tuga1975" <notifications@github.com>:

**Comment by kmahyyg** [comment]
Related Issue: #81 

I hope that the official could use `summary.yaml` instead of  `summary.md`, and allow users to add `hidden` tag to make it work.

**Comment by dougio** [comment]
My workaround comes from @rafecolton 's answer. 
I created a folder called hide, put markdown files in the folder, and add style like this:
```css
.summary .chapter[data-path^="hidden/"] {
  display: none;
}
```
