### ISSUE TITLE
I can't push to gitbook master

### ISSUE THREAD

**Issue by marshallshen** [GitbookIO/gitbook#660]
I followed instructions on Gitbook but got following errors (I checked my account setting and SSH key is set up correctly)

I'm using this Github account for integration.

Thanks.

````
git remote add gitbook https://git.gitbook.com/marshallshen/ruby-api-best-practices.git
git push -u gitbook master

fatal: unable to access 'https://git.gitbook.com/marshallshen/ruby-api-best-practices.git/': The requested URL returned error: 403
`````

**Comment by SamyPesse** [comment]
There is no SSH key with GitBook (only https is supported for now, not ssh). The error 403 is because the credentials (username/password) are invalid.

If you not prompted to enter it, you can append the username/password to the url like this:

```
https://username:apitoken@git.gitbook.com/marshallshen/ruby-api-best-practices.git
```

Let me know if that works.

**Comment by AaronO** [comment]
@marshallshen You can also store your credentials in a `~/.netrc` file so you don't need to enter them each time.

Something like :

```
machine git.gitbook.com
    login YOUR_USERNAME_or_EMAIL
    password YOUR_PASSWORD
```

**Comment by marshallshen** [comment]
@SamyPesse @AaronO 
This worked:

    https://username:apitoken@git.gitbook.com/marshallshen/ruby-api-best-practices.git

Thanks bunch guys!

**Comment by gschenk** [comment]
@SamyPesse is ssh going to be implemented? I've stumbled over it like the OP while trying it out. It's a bit surprising that some of the most fundamental git functionality is missing. I can see though, that  other than github, you might aim more for a online workflow.

@AaronO I'm not certain if storing credentials plain, un-encrypted, on ones drive is a practice one ought to suggest. I've not used git with ssh yet, does it accept salted password hashes in lieu of the plain text passwords?
