### ISSUE TITLE
Editor right edge text is cut off

### ISSUE THREAD

**Issue by lookfirst** [GitbookIO/gitbook#661]
screenshot: http://take.ms/gZMf8

no amount of changing the width separator between the two panels seems to make a difference.

it seems to happen more on wider browser windows.

**Comment by SamyPesse** [comment]
The editor has a `max-width: 900px;`, but if the editor settings `Soft Wrap` is set to `Free` it should not be an issue.

I limited the width to avoid on big screen having the editor taking the all page (for example when the preview and the sidebar are hidden).

I can easily add an option to disable the `max-width` (full-page editor)

**Comment by lookfirst** [comment]
The editor setting in the screenshot is set to 'free'.

**Comment by SamyPesse** [comment]
Ok, I successfully reproduced the issue, I'm working on it.

**Comment by lookfirst** [comment]
Yea! Thanks! Can't wait for the next release. =) With this issue, scrolling issue and virtual-dom fixed, I will be a very happy camper.

**Comment by SamyPesse** [comment]
I posted an issue on ace for this: https://github.com/ajaxorg/ace/issues/2409

**Comment by SamyPesse** [comment]
It's fixed in production :)
