### ISSUE TITLE
404 Page cannot be solved.

### ISSUE THREAD

**Issue by fengguang22** [GitbookIO/gitbook#662]
I pushed to Gitbook successfully while Book History of my book shows the same good records. However, Error 404 pages exist.

[The 404 page is here](http://fengguang22.gitbooks.io/learn-to-be-pythonic/content/source/part1/1.html).

Thank you.

**Comment by SamyPesse** [comment]
I fixed your summary (SUMMARY.md) and switch the builder to 2.0.0; it's now working.

**Comment by fengguang22** [comment]
Thank you very much. I have compared your fix and my original text. I have got the difference. Thanks.
