### ISSUE TITLE
Hangs on `clean website generator`

### ISSUE THREAD

**Issue by d4nyll** [GitbookIO/gitbook#668]
I am using version `2.0.0-beta.5` and attempting to write a multilingual book. I set it up with just one language, for testing, like this:

```
./
└── en
    ├── section-1
    ├── section-2
    ├── section-3
```

If I ran `gitbook build ./ ~/`, I get the following results:

```
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: >> 0 plugins loaded 
info: Parsing multilingual book, with 1 lanuages 
info: Preparing language book en 
info: loading book configuration....OK 
info: >> 0 plugins loaded 
info: start generation with website generator 
info: clean website generator
Error: EACCES, readdir '/home/daniel/.cache/dconf
```

When I ran the same command with `sudo gitbook build ./ ~/`. `, no errors are thrown but it hangs up on `info: clean website generator` and unable to progress.

I am able to generate the book without errors using `gitbook build ./`, where I did not specify an output directory.

**Comment by SamyPesse** [comment]
`gitbook build ./ ~/` will remove the content of your home directory!!

You should run: `gitbook build ./ ~/mybook/` to store the output in `~/mybook`.

But I'll advise you to run `gitbook build ./` and to get the output from `./_book`.
