### ISSUE TITLE
Do not replace contents of output directory

### ISSUE THREAD

**Issue by d4nyll** [GitbookIO/gitbook#669]
As stated on #668, running `gitbook build ./repository ./outputFolder` (which was in the docs before 65fdbe7) will **_replace**_ the contents of the `outputFolder` with the book. This was confusing for me as the expected behaviour, for me, would be for `gitbook` to _create_ a new directory in the output directory I specified and put the book there.

I still like the option to specify an output directory though.

**Comment by Anahkiasen** [comment]
Same issue here, I want to serve file with my book, currently I have to copy them over through a script to avoid them being erased every time
