### ISSUE TITLE
No amount of Saving gets rid of spurious 'This page is asking you to confirm that you want to leave' prompt

### ISSUE THREAD

**Issue by mcandre** [GitbookIO/gitbook#670]
Immediately after my GitBook saves, either through a manual button press or Command/Control + s, or by autosave, with no further edits, I expect the website to let me leave without complaining about unsaved data.

This problem happens for me in Firefox 36, on Mac OS X, in case relevant.

**Comment by SamyPesse** [comment]
The fix will be live in the next release :+1:

**Comment by mcandre** [comment]
@SamyPesse Thank you!
