### ISSUE TITLE
Invalid use of backslash in url breaks all contents online

### ISSUE THREAD

**Issue by renkun-ken** [GitbookIO/gitbook#674]
I update from v1.5.0 to v2.0.0 and my `SUMMARY.md` looks like 

```
# Summary

* [Acknowledgment](acknowledgment.md)
* [Quick start](quick-start/README.md)
    * [What is R](quick-start/what-is-r.md)
    * [Why R](quick-start/why-r.md)
    * [Install R](quick-start/install-r.md)
```

but the links of contents are now all generated as 

```
* [Acknowledgment](./acknowledgment.html)
* [Quick start](./quick-start\index.html)
    * [What is R](./quick-start\what-is-r.html)
    * [Why R](./quick-start\why-r.html)
    * [Install R](./quick-start\install-r.html)
```

which breaks all links with the use of `\` instead of `/`. 
I don't know why the url generator suddenly works in this way. [View](http://renkun.me/learnR/)

This issue may be duplicate of https://github.com/GitbookIO/gitbook/issues/493 but it has nothing to do with 2+ levels but every url of content item of level 2 is not correctly rendered. I try to use `/quick-start/README.md` or `./quick-start/README.md` and many possible combinations but none of them work.

All source code of my gitbook is hosted at https://github.com/renkun-ken/learnR.

Will appreciate if anybody knows how to fix it.

**Comment by SamyPesse** [comment]
@renkun-ken are you building on windows ?

BTW: you should use gitbook.com, it integrates perfectly with GitHub

**Comment by renkun-ken** [comment]
@SamyPesse, I'm build on windows. Actually, I use RMarkdown and knitr to produce `.md` files and then gitbook renders them to html. I'll try and see if gitbook.com works well with this workflow.

**Comment by SamyPesse** [comment]
Fixed by 3065742b73ae6ad0f8aa75eb0eafcdd8e395a108

**Comment by renkun-ken** [comment]
Thanks for the fix! I try to use the latest commit of gitbook following https://github.com/GitbookIO/gitbook#how-to-use-the-latest-commit-from-gitbook-in-gitbook-cli. I cloned gitbook in my workspace folder and when I run (both with and without admin)

```
gitbook versions:link 2.0.0 ./gitbook
```

I got

```
Error: EPERM, symlink 'C:\Users\Kun\.gitbook\versions\2.0.0'
```

**Comment by SamyPesse** [comment]
Take a look at https://github.com/joyent/node/issues/6342 and
http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7

On Sat, Mar 28, 2015 at 4:28 PM, Kun Ren <notifications@github.com> wrote:

> Thanks for the fix! I try to use the latest commit of gitbook following
> https://github.com/GitbookIO/gitbook#how-to-use-the-latest-commit-from-gitbook-in-gitbook-cli.
> I cloned gitbook in my workspace folder and when I run (both with and
> without admin)
>
> gitbook versions:link 2.0.0 ./gitbook
>
> I got
>
> Error: EPERM, symlink 'C:\Users\Kun\.gitbook\versions\2.0.0'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/674#issuecomment-87246578>.
>



-- 
Samy Pessé
GitHub <https://github.com/SamyPesse> | Twitter
<https://twitter.com/SamyPesse> | LinkedIN
<http://www.linkedin.com/in/samypesse/>

**Comment by renkun-ken** [comment]
Thanks for the information! I followed the instructions and changed the group policy of creating symbol link (my use account is admin itself, explicitly add myself to the allowed users of the policy) and `gpupdate`/log-out-in/restart to apply the group policy. Re-execute the command and get the same error...
