### ISSUE TITLE
Table of content displayed in wrong order 

### ISSUE THREAD

**Issue by nasirkhan** [GitbookIO/gitbook#675]
The table of content is displaying in wrong order. Attached a screenshot about the issue. 

![screenshot-www gitbook com 2015-03-28 12-56-05](https://cloud.githubusercontent.com/assets/396987/6880148/7bd5bf4c-d54b-11e4-984c-c8e22b9ada4e.png)

**Comment by SamyPesse** [comment]
what is the url to the book?

**Comment by nasirkhan** [comment]
https://www.gitbook.com/book/nasirkhan/bengali-wikipedia-user-guide

**Comment by SamyPesse** [comment]
This has been fixed in a previous release (your book has built using `2.0.0-alpha.9`), I rebuild it using the latest release (`2.0.0`).
