### ISSUE TITLE
Template doesn't work 

### ISSUE THREAD

**Issue by KengoTODA** [GitbookIO/gitbook#676]
Hello, thanks for your great product!

Today I found one unexpected behavior for me. Gitbook v2.0.0 doesn't inject variable values to [template](http://help.gitbook.com/format/templating.html) which is placed into three back-ticks block. Previously (v2.0.0 beta) it worked, but released v2.0.0 doesn't work well.

### Example:

* [.md file](https://raw.githubusercontent.com/KengoTODA/what-is-maven/91b8eece27a1ef58092fcbb45c95a607bfd265d0/primer/dependency.md)
* [converted HTML](http://kengotoda.gitbooks.io/what-is-maven/content/primer/dependency.html)

**Comment by SamyPesse** [comment]
Templating is now escaping in code blocks (since https://github.com/GitbookIO/gitbook/issues/625).

One solution for you can be to use directly html:

```
<pre><code class="lang-xml">
<dependency><!-- このプロジェクトはJUnit バージョン{{book.version.junit}}に依存している -->
  <groupId>junit</groupId>
  <artifactId>junit</artifactId>
  <version>{{book.version.junit}}</version>
  <scope>test</scope>
</dependency>
</code></pre>
```

**Comment by KengoTODA** [comment]
@SamyPesse Thanks, I will try.
