### ISSUE TITLE
Provide statistics like word count etc during build process

### ISSUE THREAD

**Issue by BjoernSchotte** [GitbookIO/gitbook#677]
Provide statistics like word count, chars w/o spaces etc, either during build process or with separate cli tool that's able to count the stats betweens commits/changesets (not sure if the latter should be provided by commit hooks).

**Comment by clarklab** [comment]
+1

Is anyone aware of a way to get a simple word count while writing? My book is being split up into blog posts (by target word count), and it's really help to be able to keep track as I write.

Currently I'm having to stop and copy/paste to a counter, which seems kinda silly. Anyone?

**Comment by SamyPesse** [comment]
The next version of the editor will include a words/characters counter in the status bar.

We can easily make a plugin that prints the number of words/characters at the end of the build.

**Comment by clarklab** [comment]
Related: word count for entire book?

**Comment by dgreis** [comment]
word count for entire book would be very useful

**Comment by ryanmurakami** [comment]
It's simple, but I made a word count plugin for the gitbook CLI. https://plugins.gitbook.com/plugin/word-count
