### ISSUE TITLE
deployment webhook get problem

### ISSUE THREAD

**Issue by billy3321** [GitbookIO/gitbook#679]
I create a organize sdparty and create 2 books: sdparty-program and sdparty-policy.

https://www.gitbook.com/book/sdparty/sdparty-program/
https://www.gitbook.com/book/sdparty/sdparty-policy/

I need to use deployment webhook to published a version, but it always get error. The error message is:

```
Error: Not Found .
```

Please help me to solve this problem, thank you.

**Comment by SamyPesse** [comment]
The error is happening when trying to add a webhook?

**Comment by billy3321** [comment]
Yes, it is happening at that time.

**Comment by SamyPesse** [comment]
I'm looking this issue, but the error seems to come from GitHub API, so my guess is that you don't have permissions on GitHub to add a webhook to these GitHub repositories, or the authorization given to GitBook doesn't allow adding webhook to these repositories.

**Comment by billy3321** [comment]
How to check the permission on github?

I'm sure I have permission to push content to the repository.

https://github.com/sdparty/sdparty-policy-gitbook
https://github.com/sdparty/sdparty-program-gitbook

**Comment by SamyPesse** [comment]
Do you have permissions to access https://github.com/sdparty/sdparty-policy-gitbook/settings/hooks ?

If yes, it's also possible to add webhook by hand, send me an email at samy[at]gitbook.com and I'll give you the url to add as a webhook.

**Comment by billy3321** [comment]
Yes, I can access that page.
I sent an email to you, thank you.

**Comment by billy3321** [comment]
OK, the webhook works. Thank you!

**Comment by aisapatino** [comment]
@SamyPesse I'm having the same problem trying to add a webhook through the book settings interface - `Error: Not found`

It's a public repo: https://github.com/aisapatino/sjfnw-docs and I do have permissions to add a web hook. Mind if I email you for the webhook url also?

**Comment by gabriel** [comment]
I'm having a similar issue `Error: Not Found`. Is there a workaround or?

**Comment by hellorocky** [comment]
I'm having a similar issue `Error: Not Found.` Mind if I email you for the webhook url also? https://github.com/hellorocky/ansible-zh
