### ISSUE TITLE
no images via markdown or adoc

### ISSUE THREAD

**Issue by joreg** [GitbookIO/gitbook#681]
helos,

i've been playing for quite a while trying to display an image in either an .md or .adoc file. 

it works in both cases as long as the image url is a http resource. if i upload an image into the books root directory and reference it like so:
**image::jo.png[test]**

it does not work. i see the "test" text in the output, but not the image. any ideas what i could be doing wrong?

also when pressing the "insert image" button while in an .adoc i get the .md image syntax inserted.

**Comment by SamyPesse** [comment]
What is your book url or github repository ?

**Comment by joreg** [comment]
sorry for late answer. hm..it is private for now.

a thing to note: when i have an image referenced in README.md in the root it shows up when viewed via github (as they also render the README.md). but in the same file viewed via gitbook, the image does not show up.
