### ISSUE TITLE
Domain Name Setting Error

### ISSUE THREAD

**Issue by billy3321** [GitbookIO/gitbook#682]
I have 2 books on gitbook

https://www.gitbook.com/book/sdparty/sdparty-policy/details
https://www.gitbook.com/book/sdparty/sdparty-program/details

and setting the domain name to 

http://policy.sdparty.tw
http://program.sdparty.tw

and I setting the dns as following

policy.sdparty.tw CNAME to www.gitbook.com
program.sdparty.tw CNAME to www.gitbook.com

But the program.sdparty.tw setting works, policy.sdparty.tw not work.

Is there has anything wrong?

**Comment by SamyPesse** [comment]
I removed it and added it back and it's now working: http://policy.sdparty.tw and http://policy.sdparty.tw/content/
