### ISSUE TITLE
Hooks available

### ISSUE THREAD

**Issue by brenoc** [GitbookIO/gitbook#684]
Most of the plugins are deprecated or not working because of the hooks. I'm trying to figure out which hooks are available to update them, but there's no information about that in the docs.

I've looked into the source and now there's just those ones available?

"init", "finish", "finish:before", "page", "page:before"

**Comment by SamyPesse** [comment]
Yes `[init", "finish", "finish:before", "page", "page:before"]` are working.

`page:*` are marked as deprecated because it's better if plugin start using `blocks` instead. But `page` and `page:before` will probably stay at the end (useful in some cases).

**Comment by brenoc** [comment]
Thanks, @SamyPesse!

Can you describe when this hooks are called? `init` and `finish` are related to the build process? `finish:before` is before what?

**Comment by SamyPesse** [comment]
Im' going to update the documentation to answer this question :)

**Comment by brenoc** [comment]
Great! Thanks :)

Let me know when you do it, please.

**Comment by SamyPesse** [comment]
Done: http://help.gitbook.com/plugins/hooks.html

Feel free to contribute to it: https://github.com/GitbookIO/documentation/blob/master/plugins/hooks.md

**Comment by uliska** [comment]
Now we have only 10 weeks later and one of the mentioned hooks doesn't seem to work anymore. `page:before` is said to be deprecated and `TypeError: Cannot read property 'path' of undefined` happens.

I don't fully see the reasoning behind removing this kind of hook.
OK, we should use blocks for giving access to enhanced content. This works well for letting authors *insert* items that can be parsed and constructed with JavaScript. But I (as the book maintainer) would also like to insert elements without requiring the authors to insert blocks. For example I would like to add code at the bottom of each page (for example displaying credits retrieved from the Git history). And if I don't have (or at least don't see) the option of creating templates that are automatically inserted/parsed the idea of a hook in which I can access the `page.content` seems like a practical, well, hook.

**Comment by gsouf** [comment]
@SamyPesse In your previous comment on april 2d the link are dead.

Can you update please ?

**Comment by SamyPesse** [comment]
The documentation is available at http://developer.gitbook.com/plugins/hooks.html

**Comment by SamyPesse** [comment]
@uliska @bbatsche `page`, `page:before` will no longer signal as deprecated(https://github.com/GitbookIO/gitbook/commit/a4422593f20b9e410f13841cc20b8b9a1632eab0), we will update the docs to advice devs to use blocks instead: these hooks are useful but requires to work on a `string` (parse the html, ...).

**Comment by SamyPesse** [comment]
@uliska the error `TypeError: Cannot read property 'path' of undefined` happens when your hook doesn't return anything (it should return the `page` object)
I'm going to improve this.
