### ISSUE TITLE
The search function is not support Chinese.

### ISSUE THREAD

**Issue by Svtter** [GitbookIO/gitbook#687]
You could check this by http://svtter.gitbooks.io/book_acm/content/

**Comment by bborysenko** [comment]
Same for Russian. It will be very cool to add multi-language search support.

**Comment by derekya** [comment]
Can this be worked around? In desperate need of Chinese search functionality ...

**Comment by xunuo** [comment]
use this plugin : 
https://github.com/gitbook-plugins/gitbook-plugin-search-pro
:100:

**Comment by derekya** [comment]
Hi Snow,

Do you develop this plugin? Thanks, you are a life saver!


Best wishes,

Derek


2015-10-17 13:05 GMT+08:00 snow <notifications@github.com>:

**Comment by xunuo** [comment]
Thanks :)

**Comment by hitsumabushi** [comment]
Same for Japanese.

**Comment by doggy8088** [comment]
When I removed the "search" plugin, the PDF output turn into problem. :cry: 

```
{
    "plugins": [
        "-search"
    ]
}
```

At first, the "Table of Content"'s format is gone.

![image](https://cloud.githubusercontent.com/assets/88981/14686406/1f8597a0-076b-11e6-989d-ee931d402483.png)

Second, all the section title become duplicated.

![image](https://cloud.githubusercontent.com/assets/88981/14686434/38831c5a-076b-11e6-9564-86b3fbe7232e.png)

Is there any way to fix that?
