### ISSUE TITLE
Creating book within a subdirectory in my repo

### ISSUE THREAD

**Issue by MattKunze** [GitbookIO/gitbook#688]
I'd like to use gitbook to edit documentation for our projects, and it would be nice to point the editor to a subdirectory within the repository to separate the book content from the rest of the code. I've tried setting the *structure* property in *book.json*:

```json
{
  "gitbook": ">=2.0.0",
  "title": "Test Book",
  "structure": {
    "readme": "docs/readme.md",
    "summary": "docs/summary.md",
  }
}
```

But I'm getting build errors when I push stating that `No README file` was found (this in an empty test repo, so there's not a root readme at the moment). Is there a way that I can make gitbooks use `docs` as the root folder for the book?

**Comment by SamyPesse** [comment]
I'll test this locally, is your book hosted on GitHub (so that I can test directly with it) ?

But it's best practise to use a separate repository for the documentation ;)

**Comment by MattKunze** [comment]
http://github.com/DataSplice/ds-test

There's no content at the moment, I was just trying to get the structure to work. I added a root README, and now it's complaining about SUMMARY. So it seems like it's ignoring the `structure` settings.

**Comment by SamyPesse** [comment]
It looks like the github repo is private, can you send me a zip at samy[at]gitbook.com with your base structure.

**Comment by MattKunze** [comment]
Sorry, I wrote the wrong repo - it's `book-test`

**Comment by MattKunze** [comment]
And I should mention I'm using Github integration through the GitBook web portal: https://www.gitbook.com/book/datasplice/ds-test (that's why I got the names confused, I'll be consistent once I get to real content :)

The errors are coming from the hooked builds that are triggered when I push to the github repo

**Comment by SamyPesse** [comment]
Ok, there is a problem on gitbook.com:

Locally, building your book is failing with an error in the `book.json`:

```
Samys-iMac:book-test-master samypesse$ gitbook build ./
info: loading book configuration....
Error: /Users/samypesse/Downloads/book-test-master/book.json: Unexpected token }
```

But on gitbook.com, before running `gitbook build`, we are modifying the `book.json` to add author, title, etc; but then we are writing a valid `book.json` (without the `structure` of your incorrect book.json).

If you fix the error in your book.json at line 7 (you can test it online at http://jsonlint.com/), then the build will work.

**Comment by SamyPesse** [comment]
But, gitbook is not meant to be used for building into a subdirectory, so all your paths in SUMMARY will need to contain `./docs` and the url will be `https://www.datasplice.gitbook.com/ds-test/content/docs/page.html` instead of `https://www.datasplice.gitbook.com/ds-test/content/page.html`.

I'll advised you to use a separate repository for your documentation.

**Comment by MattKunze** [comment]
Doh, stupid mistake, thanks for pointing that out :blush:

Regarding having a separate repo for the documentation, I'd really like to have the documentation integrated with the rest of the codebase. This way a single PR can implement changes, update the documentation, etc. rather than having to split things across multiple projects. We'll play around with it and see if we can come up with a workflow that works well for.

**Comment by SamyPesse** [comment]
We can easily add an option `root` to use a subdirectory, example:

```js
{
    "root": "./docs",
}
```

@AaronO what do you think?

**Comment by MattKunze** [comment]
+1 from me. We're looking to use this across all of our repositories to provide a consistent mechanism for documentation

**Comment by MattKunze** [comment]
The online editor doesn't seem to respect the `structure` settings in book.json, when modifying the table of contents it creates a root `SUMMARY.json` and manages the list from there. The build is using the redirected summary correctly, so I can manually update it to get the final output working.

**Comment by masterkorp** [comment]
Is this "root" feature implemented yet ?

I would like to have a gitbook in a subdirectory of my repo too.

**Comment by AaronO** [comment]
@SamyPesse @MattKunze @masterkorp I think this is a good idea, especially for projects with documentation alongside the code of a larger project, it would be really convenient.

I think having it as a `root` option is good. Ideally we should favor convention over configuration, so we have two options:

### Conventions
* Check book at a list of predefined folders in order: `./SUMMARY.md`, `./docs/SUMMARY.md` `./book/SUMMARY.md`

## Configuration
* Require the user to set `root` in their `book.json`

I think it would be nice if we could have the convention strategy as the default (rather than requiring people to create a `book.json` simply to define `root`) and many people with docs alongside their code probably have it in a folder called `docs` anyway.

**Comment by masterkorp** [comment]
@AaronO :+1:

**Comment by MattKunze** [comment]
I haven't been able to get this to work reliably with the existing tools as mentioned - the online editor does not work very well using this layout, and the automated build tools fail. I had to move on to other things, so I haven't had a ton of time to try to come up with possible workarounds.

I'd probably lean towards the `root` element in `book.json` myself - convention is always nice, but it's hard to take an opinionated stance about exactly where the docs should live I think (not to mention internationalization and other concerns).

**Comment by danrichards** [comment]
Native sub-directory support would be nice as you could include documentation with your repos, then devs could just hotkey file open a *.md file and have the documentation at their disposal in their IDE. 

@MattKunze if you're using PHP, a nice work-around would be creating a separate repo for your docs as a @SamyPesse suggested. then adding your gitbook repo to the `require-dev` key in your `composer.json` file.

**Comment by xGeek** [comment]
Is the "root" feature implemented yet ?

**Comment by MattKunze** [comment]
> @MattKunze if you're using PHP, a nice work-around would be creating a separate repo for your docs

We don't use PHP, but there are any number of ways we can manage multiple repos for the content. The issue is you'd lose the ability to combine code and documentation changes in the same PR so it gets merged together. It would be awesome to have code changes, unit tests, documentation, etc for a feature contained in a single mergable unit.

**Comment by bryannaegele** [comment]
I would like to see the root feature. We want our docs to be in a subdirectory for our workflow. 

Any update on the status here @SamyPesse ?

**Comment by jstejada** [comment]
+1

**Comment by orlade** [comment]
+1. You can hack it a bit with NPM scripts, a la `"build": "cd ./docs && gitbook build ."`, but it's ugly and it only goes downhill from there.

**Comment by weltenbauer** [comment]
+1 Any news on that @SamyPesse ?

**Comment by SamyPesse** [comment]
Fixed in GitBook v3 (it will be released tomorrow) :beers: :fireworks: 

GitBook itself will have its documentation as a gitbook in the repository: https://github.com/GitbookIO/gitbook/tree/3.0.0/docs

You'll just have to create a [.gitbook](https://github.com/GitbookIO/gitbook/blob/3.0.0/.gitbook) file (it will work on GitBook.com as well).

**Comment by bryannaegele** [comment]
That is very welcome news! Thanks @SamyPesse

**Comment by weltenbauer** [comment]
Great! Thank you...

**Comment by GreatBigBore** [comment]
@SamyPesse Those links are broken. I think I've found the doc at https://github.com/GitbookIO/gitbook/tree/master/docs, but could you let me know if I'm looking in the wrong place?

**Comment by wcandillon** [comment]
I am also interested by this feature.

**Comment by SamyPesse** [comment]
This is implemented in GitBook v3: http://toolchain.gitbook.com/structure.html#subdirectory using the `root` configuration:

```js
{
    "root": "./docs"
}
```

**Comment by bryannaegele** [comment]
@SamyPesse it's working well from command line but the TOC for one is not handling this feature in the editors (online or web).

**Comment by weltenbauer** [comment]
Great news @SamyPesse. Is there a schedule to release v3 to GitBook.com?
