### ISSUE TITLE
Custom pages via book.json

### ISSUE THREAD

**Issue by 13abylon** [GitbookIO/gitbook#689]
Hello together,

I recently found out that I can add custom stylesheets to the gitbook via

```
"styles": {
  "website": "styles/website.css"
}
```

That's great so I can slowly remove `"theme": "./localtheme"` from `book.json`. There is only one problem:
I've also modified `website/includes/summary.html`. Can I somehow tell `book.json` to use my `summary.html` instead of the given one from gitbook?

**Comment by miljan-aleksic** [comment]
This should be possible extending the default theme `_layouts` folder, at least in recent versions.
