### ISSUE TITLE
Are these all langs available ?

### ISSUE THREAD

**Issue by awrelll** [GitbookIO/gitbook#690]
warn: Language 'ro' is not available as a layout locales (en, ar, bn,
de, en, es, fa, fr, it, no, pl, pt, ru, zh-cn, zh-tw)

**Comment by SamyPesse** [comment]
You can contribute to add your language by doing a PR to: https://github.com/GitbookIO/gitbook/tree/master/theme/i18n

These languages are used to change the layout locale (search placeholder, tooltip for actions, ...).
