### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by awrelll** [GitbookIO/gitbook#695]
Hello,
I get this error and my build always fails.

Downloading source
Extracting source
Current version is 2.0.1
Tweaking book.json
Installing plugins
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: 1 plugins to install 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Building Site, will upload
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: Parsing multilingual book, with 9 lanuages 
info: Preparing language book en 
info: Preparing language book cn 
info: Preparing language book es 
info: Preparing language book it 
info: Preparing language book de 
info: Preparing language book fr 
info: Preparing language book ro 
info: Preparing language book jp 
info: Preparing language book kr 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: loading book configuration....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 

Error: ENOENT, lstat '/tmp/book/ro'v

This is the book

http://ethereumbuilders.gitbooks.io/guide/

It still displays that message in french :) 

Any clue ?!

thanks so much guys

**Comment by 13abylon** [comment]
If this is still an error, which os do you use? 
And whats your node and npm version?

**Comment by awrelll** [comment]
we're over it.
All fine now.
Thanks!
