### ISSUE TITLE
Is it possible to add internal absolute links?

### ISSUE THREAD

**Issue by pajtai** [GitbookIO/gitbook#697]
How can one make an absolute internal link?

If I'm in the file `/foo/bar.md`, and I write the following:

```
[my link](/absolute/link/to/file.md)
```

The link that is created is to:

```
/foo/absolute/link/to/file.html
```

and not:

```
/absolute/link/to/file.html
```

Absolute links are important because they are easier to update site wide than relative links when there are large scale folder restructurings.

**Comment by timaschew** [comment]
This is fixed in my fork: https://github.com/timaschew/gitbook
