### ISSUE TITLE
Why Chinese characters are converted to numeric references in markup?

### ISSUE THREAD

**Issue by photino** [GitbookIO/gitbook#702]
I am writing a Chinese book using Gitbook 2.0.1. It is quite weird that all the Chinese characters in Markdown files are converted to numeric references, such as the phrase `开发环境` is converted to `&#x5F00;&#x53D1;&#x73AF;&#x5883;` (see a snapshot of the HTML code). I am not sure whether other unicode characters are converted too. 

![gitbook](https://cloud.githubusercontent.com/assets/3446306/7111200/3cdc50c0-e1ef-11e4-931c-bfec4d344b92.png)

I would like to know why this conversion is necessary. Personally, I dislike this conversion.

**Comment by XadillaX** [comment]
Me too.
