### ISSUE TITLE
gitbook serve command has some problems.

### ISSUE THREAD

**Issue by huangyong-git** [GitbookIO/gitbook#703]
When I execute `gitbook serve` command, output some errors:

```
Template render error: unexpected token: #
```

Belowing is my code:

```
<script type="text/x-handlebars-template" id="product_table_template">
    {{#if data}}
        <table class="table table-hover" id="product_table">
```

I found gitbook can not render `{{#if data}}`, why?

**Comment by bebraw** [comment]
Have a look at [templating section](http://help.gitbook.com/format/templating.html) of the documentation.

You should use something like this:

```
{% if data %}
  <table class="table table-hover" id="product_table">
  ...
  </table>
{% endif %}
```

**Comment by sbusso** [comment]
Same problem here with `{{> }}`. Any solution ? I can't find workaround in templating section as this about inside code.

**Comment by sbusso** [comment]
ok fixed with `{% raw %}``{{> world }}``{% endraw %}`
