### ISSUE TITLE
Variables don't expand inside code blocks

### ISSUE THREAD

**Issue by japgolly** [GitbookIO/gitbook#707]
I'd like to do this: *(ignore pipes on the left)*

```
|  ```scala
|  libraryDependencies += "com.github.japgolly.scalacss" %% "core" % "{{book.ver}}"
|  ```
```

to create this
```scala
libraryDependencies += "com.github.japgolly.scalacss" %% "core" % "0.1.0"
```

but instead it creates this
```scala
libraryDependencies += "com.github.japgolly.scalacss" %% "core" % "{{book.ver}}"
```

**Comment by SamyPesse** [comment]
Code blocks are escaped (https://github.com/GitbookIO/gitbook/issues/625).

You can use this as a working solution:

```
<pre><code class="lang-scala">
|  libraryDependencies += "com.github.japgolly.scalacss" %% "core" % "{{book.ver}}"
|</code></pre>
```

**Comment by japgolly** [comment]
Oh awesome, thank you :)

**Comment by Possum3D** [comment]
Thanks for the hack. However, it is not working well on a multiline code sample:
```
<pre><code class="lang-sh">
curl "{{book.apiroot}}/accounts/{{account_id | default('YOUR_ACCOUNT_ID')}}" \
- H "Authorization: Bearer {{account_id | default("YOUR_ACCESS_TOKEN")}}" \
--data-binary '{name: "{{alert_name}}"}'
</pre></code>
```
lines starting with \- are interpreted in markdown, which breaks the html apart. until now, I tried escaping, but with no result; 

Also, I noted that if a blockquote is in your page, everything is escaped; but if it is included, then variables are interpreted. all in all, I think this is too bad that code blocks are now escaped. Maybe we could just put a variable in book to indicate the strategy we want there ? Do you have suggestion for my specific use case ?
