### ISSUE TITLE
Specify gitbook version in package.json

### ISSUE THREAD

**Issue by destroyerofbuilds** [GitbookIO/gitbook#710]
Can I specify the version of `gitbook` in my project's `package.json` file instead of in a `book.json` file?

I would like to do the following:

```
npm install -g gitbook-cli
```

Followed by specifying the gitbook version for my project, from within the giitbook project folder, like so:

```
npm install gitbook@2.0.0 --save
```

Now I would expect that running `npm install` inside of my gitbook project would install version 2 of gitbook (within the traditional `node_modules` folder), and that running `gitbook` (the CLI tool) would build my gitbook project using the locally installed, version 2, version of gitbook.

**Comment by SamyPesse** [comment]
We can add support for local package inside https://github.com/GitbookIO/gitbook-cli (the issue should be posted there).
