### ISSUE TITLE
Make section headers clickable

### ISSUE THREAD

**Issue by mcandre** [GitbookIO/gitbook#713]
As a reader, I want section headers (`# ...`) to be clickable, so that I can quickly get a section's permalink without having to inspect the HTML code.

GitHub's markdown renderer does this, for example.

https://github.com/mcandre/vcdetect#examples

**Comment by brenoc** [comment]
That can be achieved with http://plugins.gitbook.com/plugin/anchors. It uses a deprecated hook so it gives a lot of warnings, but it works though.

**Comment by brenoc** [comment]
Oh, I agree it should be a native feature!
