### ISSUE TITLE
If book.json structure.readme is set, no `index.html` gets generated

### ISSUE THREAD

**Issue by bebraw** [GitbookIO/gitbook#715]
1. Check out [my book](https://github.com/survivejs/webpack_react)
2. Install the cli and hit `gitbook build`
3. Note that `_book/index.html` is missing!

If you remove the `structure` section from `book.json`, index.html gets generated.

Note that the tool seems to find the custom readme just fine. If you break the path, it will give an error. Now it just fails to generate index silently.

**Comment by bebraw** [comment]
I figured out what's going on with this. It actually generates `index.html`. It just goes to wrong place. It seems to respect the original path of `readme`. Ie. in my case the index appears below `_book/manuscript`. You can see the problem at `Book.prototype.contentPath` though I suspect a fix would go on a higher level at structure handling.

**Comment by SamyPesse** [comment]
Yes, `structure.*` was not really designed to use other folder but more to use other filenames in the root folder.

I'll run some tests on this.

**Comment by bebraw** [comment]
Any luck? Do you want me to look into it?

**Comment by bebraw** [comment]
Sorry to poke you again. The book [is out](http://survivejs.com/) and I would love to distribute it through gitbook.io too without resolving to hacks on my side. :+1:
