### ISSUE TITLE
Support Cover in SVG format

### ISSUE THREAD

**Issue by edsiper** [GitbookIO/gitbook#716]
Having support for a Cover in SVG would help to makes easier when generating covers for different sizes and targets.

**Comment by AaronO** [comment]
@edsiper I implemented SVG support a while back (https://github.com/GitbookIO/plugin-autocover/pull/5), I need to take some time and bump that into production.

I also wanted to take the opportunity to improve the design of our automatically generated covers.

**Comment by edsiper** [comment]
that is great!.

One question, can we use SVG images and have safe PNG outputs in the content ?

**Comment by AaronO** [comment]
Yes, that's one of the features @SamyPesse implemented in the `2.0.0` release ! So you can already use that today ;)

**Comment by AaronO** [comment]
@edsiper It will use SVGs on the web but rasterize them for PDFs and ePubs, etc ...

**Comment by edsiper** [comment]
thanks. I am closing the ticket.
