### ISSUE TITLE
Set the site base URL

### ISSUE THREAD

**Issue by mitchchn** [GitbookIO/gitbook#718]
I am trying to serve a gitbook from `https://myhost/book/` instead of the site root. How feasible would it be to add a config option so that links and assets would resolve with `/book/` or another path instead of `/`?

**Comment by yayajacky** [comment]
I was trying to do the same, and found that you can serve the built book folder "_book" with Apache in subdirectory:

Say if you have /var/www/html as the DocumentRoot, and you want the site base URL to be:
https://www.example.com/book

You can do so by moving '_book' (the result of running gitbook build) to
/var/www/html/book

**Comment by wsdo** [comment]
location /doc {
          index index.html index.htm index.php default.html default.htm default.php;
          alias /home/wwwroot/shudong/gitbook-redux/_book;
        }
