### ISSUE TITLE
Relative links inside a page don't get transformed into links ending with html on windows version 2.0.1

### ISSUE THREAD

**Issue by simonschaufi** [GitbookIO/gitbook#721]
```
* [Array](../myfolder/array.md)
```
this link inside a myfolder/README.md doesn't get transformed into a link ending with .html. Instead the md file is linked. On mac this works.

**Comment by SamyPesse** [comment]
You are using version `0.3.3` of GitBook ? The latest version is `2.0.0`.

**Comment by simonschaufi** [comment]
I installed gitbook via gitbook-cli a few days ago and this is what i get:
```
$ gitbook --version
0.3.3
```

**Comment by SamyPesse** [comment]
Ok, this is the version of `gitbook-cli`, run `gitbook versions:print` to get the actual version of gitbook, it should give you `2.0.1` (the latest one).

Currently, links are converted to html only if present in the SUMMARY.md, there is a topic about this: https://github.com/GitbookIO/gitbook/issues/81

**Comment by simonschaufi** [comment]
```
$ gitbook versions:print
Current version is 2.0.1
```

**Comment by simonschaufi** [comment]
actually the file is also present in SUMMARY.md but it still doesn't work

**Comment by SamyPesse** [comment]
Do you have a link to your book ? (gitbook or github)

**Comment by simonschaufi** [comment]
https://github.com/plobacher/neosdocumentation/

**Comment by SamyPesse** [comment]
What is the file where the link is not working?

**Comment by simonschaufi** [comment]
i just updated my last comment.

**Comment by SamyPesse** [comment]
The problem is probably coming from https://github.com/GitbookIO/gitbook/blob/master/lib/utils/page.js#L196 since on windows `path.join` use `\` (and `/` on mac/linux).

I'll add some unit tests and fix it.

**Comment by simonschaufi** [comment]
yeah problably! Thanx for looking into it!

**Comment by simonschaufi** [comment]
http://stackoverflow.com/questions/12722865/using-path-join-on-nodejs-on-windows-to-create-url

**Comment by simonschaufi** [comment]
thanx! when is version 2.0.2 to be expected?

**Comment by SamyPesse** [comment]
Probably next week, in the mid time: you can do:

```
gitbook versions:uninstall 2.0.1
git clone https://github.com/GitbookIO/gitbook.git ./gitbook
gitbook versions:link 2.0.1 ./gitbook
````

**Comment by simonschaufi** [comment]
unfortunately this fails on windows also:
```
$ gitbook versions:link 2.0.1 ./gitbook
Error: EPERM, symlink 'C:\neosdocumentation\gitbook'
```
