### ISSUE TITLE
Problems with adding images

### ISSUE THREAD

**Issue by FabLabFaenza** [GitbookIO/gitbook#722]
I tried to add an image in relative path mode, but it doesn't seem to work!!
Is there a workaround or am i writing it wrong?

    ######CAPITOLO 4

       ![Image5](/img/figura5.jpg)

**Comment by SamyPesse** [comment]
Please try:

```md
######CAPITOLO 4

   ![Image5](img/figura5.jpg)
```

**Comment by FabLabFaenza** [comment]
doesn't seem to work aswell! D:

**Comment by SamyPesse** [comment]
Do you have a link to your book (GitHub or GitBook) ?

**Comment by FabLabFaenza** [comment]
yup, here it is.

    https://github.com/FabLabFaenza/Guida-a-Cura

**Comment by SamyPesse** [comment]
In which file are you trying to add an image ?

**Comment by FabLabFaenza** [comment]
it/capitolo4/interfaccia.md

**Comment by SamyPesse** [comment]
Os so the path should be:

```md
![fig. 6](../../img/figura6.jpg)
```
