### ISSUE TITLE
Missing Hook 'page:after'

### ISSUE THREAD

**Issue by rahul286** [GitbookIO/gitbook#724]
We are using hook 'page:after' in our code for gitbook plugin - https://www.npmjs.com/package/gitbook-plugin-edit-link

It seems the hook we were using is removed. 

> Hook 'page:after' 'used by plugin 'gitbook-plugin-edit-link' has been removed or is deprecated 

Sorry if I missed related announcement or documentation. Is this replaced by new hook?

I tried `page:before` and only `page` but both gave similar error. Can you please suggest alternative?

**Comment by leesei** [comment]
Use template block tags, see #793.

**Comment by todvora** [comment]
Hi @leesei ,
but what if you want to modify the page itself, without adding any tags? The [edit-link](https://www.npmjs.com/package/gitbook-plugin-edit-link) plugin adds some navigation to the page layout. I am using this hook in plugin [image-captions](https://www.npmjs.com/package/gitbook-plugin-image-captions) to replace images with figcaption. There is no need of any custom tag, just a possibility to modify already rendered page. Adding custom tag would mean unnecessary work for users without any real benefit. 

Thanks, Tomas

**Comment by leesei** [comment]
I see. I was answering generally to why the warning is shown and the official alternative, not to some specific use case.
I agree to your concern and that could be another issue discussing whether template blocks can really replace page hooks. I have yet to look into GitBook 2.x source to look for alternatives.
