### ISSUE TITLE
Full page reading mode

### ISSUE THREAD

**Issue by erlend-sh** [GitbookIO/gitbook#725]
Some people prefer having a single, exhaustive page of documentation, without the need for any previous/next clicking. I imagine 3 different reading options (could be added in the Textsize/Font/Colorscheme menu):
- Page view (current)
- Chapter view: e.g. 1 through 1.12 in [Format](http://help.gitbook.com/format/index.html) rendered as one page. ex: `/format/index-chapter.html`
- Book view: The entire book rendered in one page. ex: `http://help.gitbook.com/index-book.html`

**Comment by SamyPesse** [comment]
I believe this also related to #566; we need to find a great convention to define theme that are hosted in the book source (like for `styles/website.css`).

An idea could be to host the theme in the book source at:
`theme/index.html`, `theme/summary.html`, `theme/glossary.html`, `theme/langs.html`

But these themes will for sure nt be compatible with the interactive feature and interactive plugins.

**Comment by ertugrulcetin** [comment]
+1
