### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by Yegorov** [GitbookIO/gitbook#726]
Some problem in windows 8, when i generate to pdf.
![e](https://cloud.githubusercontent.com/assets/2566462/7337302/0f703fa4-ec2e-11e4-9bab-442b2f1e82bb.PNG)
How generate pdf?

**Comment by BugBuster1701** [comment]
You need ebook-convert, a part of Calibre
http://calibre-ebook.com/download

**Comment by SamyPesse** [comment]
Yes, windows is not returning an error code: https://github.com/GitbookIO/gitbook/blob/master/lib/generators/ebook.js#L115
