### ISSUE TITLE
ePub validation errors related to headers

### ISSUE THREAD

**Issue by mattakins** [GitbookIO/gitbook#727]
GitBook is amazing, thanks. There are issues with generating a valid ePub specifically related to colons (:) used in headers. Here is the error list I get when I run a GitBook ePub through ePub Check:
![screen shot 2015-04-26 at 1 24 06 pm](https://cloud.githubusercontent.com/assets/8516886/7339334/9fd93a08-ec17-11e4-8f11-7a35faf0531b.png)

All errors are the same, and it seems that all point to headers that include either a hyperlink with display text (e.g. [hyperlink](http://google.com/))or a header that includes a colon (e.g. Step 1: Do this). Both types involve colons and seem to generate an invalid header ID because of the colons which is flagged as an error in ePub Check. I am not sure if other special symbols used in headers result in this error as well.

Currently the only workaround is to not use colons or hyperlinks in headers or to manually edit the ePub HTML files. It seems like different header IDs must be generated when headers include colons or other special symbols that result in errors in order to pass the check.

**Comment by AaronO** [comment]
@mattakins Are you using AsciiDoc or Markdown ? If you're using Markdown, this shouldn't happen.

We normalize header IDs here: https://github.com/GitbookIO/kramed/blob/master/lib/renderer.js#L51

That replaces `:` and all other punctuation with `-`.

**Comment by SamyPesse** [comment]
Closed in favor of #888
