### ISSUE TITLE
Is it possible to have a custom footer on the PDF version of book?

### ISSUE THREAD

**Issue by ciarant** [GitbookIO/gitbook#728]
I'd like to include a small logo in the footer on every page on the PDF version of a book but not on the html version.

Is this possible? Any pointers on how I might achieve this?

I'm using git book version 2.0.1

Thanks a million.

ct

**Comment by SamyPesse** [comment]
You can use this option in the `book.json`: https://github.com/GitbookIO/gitbook/blob/master/lib/configuration.js#L261

But it'll probably not work with an image/html

**Comment by ciarant** [comment]
Thanks for getting back to me on this. Unfortunately, as you predicated, it didn't work.

**Comment by benjick** [comment]
@SamyPesse That link isn't working, is there a way to add footers? I want to add a date of generation of a PDF to each page

**Comment by jlavezzo** [comment]
Seems like this ticket was closed prematurely.  Is there a solution out there?  At least a corrected link?
