### ISSUE TITLE
Glossary markdown links and code do not appear as such

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#729]
This issue is with the actual gitbook website. The problem is that links and code (those two for sure) are rendered as plain text. That means that the code ticks that normally create code blocks are visible as such and markdown links appear as they would if opened in a text editor. 

However, editing the page using the online editor displays the page as it should in the preview, but the built website doesn't do the same. Here's a link to the page that is problematic: [GLOSSARY.md](http://icytesseract.gitbooks.io/project-euler-rust/content/GLOSSARY.html).

**Comment by ThomWright** [comment]
I'm having the same issue. I'd like to link off to e.g. Wikipedia for some definitions in my Glossary, but the links just end up as plain Markdown.

**Comment by piranna** [comment]
I'm having the same problem when using the command line tool on my computer.

**Comment by aaronwest** [comment]
+1 - At my organization we are using several Gitbooks where the Glossary is used to provide detail about terms found in the book. We often want to link out to other online resources for additional information but the HTTP links aren't rendered.

**Comment by torsday** [comment]
+1

**Comment by noerw** [comment]
still no fix?

**Comment by Frijol** [comment]
+1
