### ISSUE TITLE
Link to SUMMARY.md not working

### ISSUE THREAD

**Issue by tttp** [GitbookIO/gitbook#735]
Hi,

In a page (the README.md) I wanted to add a [you can see the table of content](SUMMARY.md) as I was hoping to use the SUMMARY.md page both for the left hand column on the generated html book and as a standalone page.

However, it doesn't replace the README.md link into a readme.html when generating the html. Is this on purpose? Do I miss something? it works fine with other md files

**Comment by yely** [comment]
`README.md` does not generate a `readme.html`, it generates `index.html`.

**Comment by tttp** [comment]
Yes, but my point was that from any page (readme was an example) I'd want to be able to link to a single page that contains only the table of content (what I expected to be generated from the SUMMARY.md page into SUMMARY.html, that doesn't seem to be the case. 

Is this on purpose? Is there a way to force gitbook to generate a page for the SUMMARY.md?

**Comment by yely** [comment]
oh, i see. 
I think the `SUMMARY.md` file is just used for toc, it doesn't generate html file, and I think that makes sence. 
If you want to link to the toc page, you can make a hard link to `SUMMARY.md`, like `toc.md`, then link to the file.
