### ISSUE TITLE
how to design a graceful 404 page for a GitBook with custom domain?

### ISSUE THREAD

**Issue by JackDougherty** [GitbookIO/gitbook#736]
Is there a way to design a graceful 404 error page for a GitBook with a custom domain? 

I didn't see this anywhere in the GitBook documentation. I've tried different variations of the GitHub Pages approaches mention below, but no success. See
https://help.github.com/articles/custom-404-pages/
and
http://yizeng.me/2013/05/26/create-a-custom-jekyll-404-page/

Suggestions welcome.

**Comment by aaronwest** [comment]
I'd like to see GitBook support something like _404.md_ too. Given the whole concept of GitBook is to produce a static website I doubt there's much that can be done about this. It'd be up to a webserver to handle 404s and GitBook knows nothing about that since it's just straight HTML.

**Comment by AaronO** [comment]
@aaronwest We could actually kind of do this. On [GitBook.com](https://www.gitbook.com) at least. (Obviously we can't do anything for servers we don't control).

So in can be implemented technically, it's really a matter of demand (if it should be implemented) (it's not because we can that we should ;) ).

I think something like `404.md` could be nice, but ideally we shouldn't even need it, books shouldn't have broken links.

**Comment by aaronwest** [comment]
@AaronO - After I wrote my comment I did some more research and testing and it appears books hosted on gitbook.io already respond with a proper 404. Whereas books hosted on a custom domain do not. I'm guessing the 404 content which displays on gitbook.io is the same across all books. Being able to customize the content and have the gitbook.io app server respond with a root level 404.md file would be pretty slick.

Not that it matters, but this sort of behavior would be consistent with how GitHub Pages handles 404s with Jekyll.

>but ideally we shouldn't even need it, books shouldn't have broken links.

That's a good point. I know invalid links in a summary file cause the `gitbook build` process to break. Is that true in content files? I haven't tried the latter so I don't know.

**Comment by billryan** [comment]
Users would access broken links(old URL links) if the books changed some urls, a nice `404` page is necessary for this case.

> but ideally we shouldn't even need it, books shouldn't have broken links.

**Comment by erlend-sh** [comment]
> Being able to customize the content and have the gitbook.io app server respond with a root level 404.md file would be pretty slick.

:+1: 

Would love this! It's great for when you're transitioning from an older platform. Some redirects are bound to be incorrect, but then at least you can make sure your users land on a page that says "didn't find what you were looking for? Please use the search (...)"

**Comment by Unforgiven-wanda** [comment]
Still no word about this?

**Comment by jeromebp** [comment]
Is gitbook dead?

**Comment by rootsongjc** [comment]
Is gitbook dead?
