### ISSUE TITLE
Questions : Search feature 

### ISSUE THREAD

**Issue by cmoulliard** [GitbookIO/gitbook#737]
When `gitbook build` or `serve` a project, then a search_index.json file is created under _book

Questions : 
- What is the purpose of the file `glossary_index.json` ?
- Can we perform complex search requests like : 
  - word1 OR word2
  - word1 AND word2
  - word\* (where \* means every letter, digit, ...)
- Can you document what search feature allow to do ?

**Comment by friedger** [comment]
Looks like glossary_index is currently not used.
The search is based on http://lunrjs.com/. 
The documentation there says at  http://lunrjs.com/docs/#search:
```
Queries should be a string, multiple words are allowed and will lead to an AND based query, e.g. idx.search('foo bar') will run a search for documents containing both 'foo' and 'bar'.
```
Feel free to send a pull request to https://github.com/GitbookIO/documentation
