### ISSUE TITLE
project image paths broken on editor

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#738]
I'm not able to see an uploaded image to my repo, but the a random image url.

I set a resources folder manually and first of all I thought it was something related to image path, but I decided using your "upload image" UI widget, and it doesn't work either.

Here you are an image:

![screen shot 2015-05-06 at 12 06 50](https://cloud.githubusercontent.com/assets/1536079/7491356/14c9b102-f3e9-11e4-8d79-03015412dd79.png)

PS: popups.png is uploaded by editor. transition.gif image is uploaded by me

**Comment by joreg** [comment]
similar for me: using .adoc i never see images in the editor while i see them in the html output. 
but in the html output i also see them only if referenced locally (ie. in the same file as the .adoc) but not if the image is referenced from a globals /images directory.
