### ISSUE TITLE
plugin support for Gliffy?

### ISSUE THREAD

**Issue by Analect** [GitbookIO/gitbook#742]
I was wondering if someone was aware of plugin support for gliffy (https://www.gliffy.com/) so as to be able to render something like this (https://www.gliffy.com/examples/network_diagrams) in a gitbook.
Gliffy files appear to be saved as JSON. Thanks.

![image](https://cloud.githubusercontent.com/assets/4063815/7585852/8fa9cf24-f89e-11e4-9124-c8ae97f8ae1b.png)

**Comment by leesei** [comment]
Why don't export as PNG and insert the image to GitBook?

**Comment by Analect** [comment]
@leesei 
Thanks for the suggestion.
Yes, I could do that, but it would defeat the purpose of fully automating the integration of a gliffy diagram, which is what I'm after.

**Comment by leesei** [comment]
Well, Gliffy has [discontinued support for their API](https://www.gliffy.com/products/online/api/).
So I think there are technical difficulties of rendering Gliffy JSONs.

**Comment by Analect** [comment]
@leesei 
Thanks for the info.
Looks like a dead end. I'll close this out then and settle for the manual PNG generation route!
