### ISSUE TITLE
custom /images directory in root not copied to output?

### ISSUE THREAD

**Issue by joreg** [GitbookIO/gitbook#744]
i am using multilanguage so i have an /en directory where my content resides. 
next to that directory i put an /images directory. referencing images from that does not work as it seems the directory is not being copied to the book output. is that by design? is there anything i can do about it?

**Comment by billryan** [comment]
I met the same issue and found that gitbook can only render static files under the single language directory.

**Comment by ghuntley** [comment]
Also having the same issue.

Problem:
- When languages are enabled (any amount, even one)
- `/images/` or `/videos` are not deployed into `_book/`.
- .gitignore is configured appropriately.

**Comment by denisivan0v** [comment]
The same issue here.

My repo's directory structure is
`...`
`/docs/en/` - book content
`/media` - media content (e.g. images)
`...`

`_book` directory does not content `media` subdirectory, just `en` subdirectory, so links to images are broken

**Comment by denisivan0v** [comment]
Just found a temporary workaround.

We can add _media_ as a _language_, so I've added 

`* [Media](media)` 

line to `LANGS.md` + blank `README.md` and `SUMMARY.md` files to `media` directory (next to images).
There is `warn: Language "media" is not available as a layout locales (en, ar, bn, cs, de, en, es, fa, fi, fr, he, it, ja, ko, no, pl, pt, ro, ru, sv, uk, vi, zh-hans, zh-tw)` now while building, but 'media' directory is under `_book`

**Comment by ghuntley** [comment]
According to https://github.com/GitbookIO/plugin-versions/issues/2 this is being tracked to be fixed in v3.0.0

**Comment by billryan** [comment]
@denisivan0v Your workaround won't work for EPUB/MOBI/PDF output, but is works well for Web pages.
