### ISSUE TITLE
can not run multi gitbook server in one machine

### ISSUE THREAD

**Issue by seaify** [GitbookIO/gitbook#745]
It seems that it is livereload server listen port confict.

chuck@chucks-MacBook-Pro:~/seaify/books/learning-ruby(master↑2|✚2) % gitbook --port 4001 serve -v 2.0.1                                                                                                                                                       (master20)
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x
info: OK
info: load plugin gitbook-plugin-livereload ....OK
info: >> 1 plugins loaded
info: start generation with website generator
info: clean website generator
info: OK
info: generation is finished

Starting server ...
Serving book on http://localhost:4001

chuck@chucks-MacBook-Pro:~/seaify/books/learning-ruby(master↑2|✚6…) % gitbook --port 4002 serve -v 2.0.1                                                                                                                                                      (master20)

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Server.listen (/Users/chuck/.gitbook/versions/2.0.1/node_modules/tiny-lr/lib/server.js:154:15)
    at Promise.apply (/Users/chuck/.gitbook/versions/2.0.1/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/chuck/.gitbook/versions/2.0.1/node_modules/q/q.js:741:41)
    at /Users/chuck/.gitbook/versions/2.0.1/node_modules/q/q.js:1304:14
    at flush (/Users/chuck/.gitbook/versions/2.0.1/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

**Comment by xu-wang11** [comment]
I met this problem. You could notice that gitbook serve has one parameter called --lrport, if you use a different lrport value instead, you can serve another book.

**Comment by seaify** [comment]
@xu-wang11 Thanks. After running "gitbook help", I have seen the lrport parameter. Actually it would be better to have a wiki for common problems. But it seems that they choose to write the help.gitbook.com.

chuck@chucks-MacBook-Pro:~/seaify/books/learning-react(master↑1|✚16…) gitbook help                                   (master10)
  build [book] [output] 	 build a book
    --format 	 Format to build to (Default is website; Values are website, json, ebook)
    --log 	 Minimum log level to display (Default is info; Values are debug, info, warn, error, disabled)

  pdf [book] [output] 	 build a book to pdf
    --log 	 Minimum log level to display (Default is info; Values are debug, info, warn, error, disabled)

  epub [book] [output] 	 build a book to epub
    --log 	 Minimum log level to display (Default is info; Values are debug, info, warn, error, disabled)

  mobi [book] [output] 	 build a book to mobi
    --log 	 Minimum log level to display (Default is info; Values are debug, info, warn, error, disabled)

  serve [book] 	 Build then serve a gitbook from a directory
    --port 	 Port for server to listen on (Default is 4000)
    --lrport 	 Port for livereload server to listen on (Default is 35729)
    --watch 	 Enable/disable file watcher (Default is true)
    --format 	 Format to build to (Default is website; Values are website, json, ebook)
    --log 	 Minimum log level to display (Default is info; Values are debug, info, warn, error, disabled)

  install [book] 	 install plugins dependencies

  init [directory] 	 create files and folders based on contents of SUMMARY.md

**Comment by zarr12steven** [comment]
@xu-wang11 Hi ！ I already try it, but still not works.

gitbook_data
└── book1
    ├── _book
    ├── README.md
    ├── section1
    ├── section2
    └── SUMMARY.md
└── book2
    ├── _book
    ├── README.md
    ├── section1
    ├── section2
    └── SUMMARY.md

`
gitbook serve --lrport 32767 -o /gitbook_data/book1
gitbook serve --lrport 32768 -o /gitbook_data/book2
`

**Comment by sarus** [comment]
I found you have to change both `--port` and `--lrport`

```
gitbook --port 5000 --lrport 5001 serve
```

**Comment by therobyouknow** [comment]
Thanks sarus - I found that to work. The port 5000 is the port used for localhost:5000 when browsing the gitbook via the browser locally. 

I'm guessing that the other port is the "listening port" - related to listening for changes to the docs you might make locally as you work on.
