### ISSUE TITLE
how to publish a first version for the book on gitbook.com

### ISSUE THREAD

**Issue by ylyxf** [GitbookIO/gitbook#746]
I create a book on gitbook.com.I  have written some sections for the book, in the history of this book ,it shows:"No build yet for this book, go publish a first version." when i click an link on "go publish a first version.",it just navigate to the book edit page.

how can i publish my book ? should i create an special branch for it ?

**Comment by AaronO** [comment]
@ylyxf There was a small issue with our git server today, that's now fixed. Builds should work as normal :)

**Comment by ylyxf** [comment]
I am sorry, the book named 'stone-book' on gitbook ,still not build after some commits  :(

**Comment by Carrotzpc** [comment]
@AaronO I'm just like ylyxf ,  when i click an link on "go publish a first version.",it just navigate to the book edit page.How can I publish my first version?
