### ISSUE TITLE
Customize the gitbook

### ISSUE THREAD

**Issue by 13abylon** [GitbookIO/gitbook#751]
Is there a possibility to customize the gitbook?

I'm thinking about two things:
- **JS Files**: Since you can add additional css files, is it possible to also add additional *js* files?
- **Header / Footer**: Is it possible to add an own footer or header to the page? Instead of the given header / footer=

I think both would be great for the gitbook!

**Comment by brenoc** [comment]
I think you can achieve that with http://plugins.gitbook.com/plugin/customtheme

**Comment by AaronO** [comment]
@13abylon @brenoc You don't need a plugin to customize it, by default you can include css files: http://help.gitbook.com/styling/book.html

If you want to customize beyond CSS (add your own HTML) you will want to define your own theme.

**Comment by 13abylon** [comment]
And the own theme is only possible via .localtheme or is there another way?

**Comment by brenoc** [comment]
> If you want to customize beyond CSS (add your own HTML) you will want to define your own theme.

@AaronO Where can I read more about that subject?

**Comment by brenoc** [comment]
@AaronO can you help me? I've tried to create a theme. I copied the theme folder of this repo, to a new directory and referenced it on my `book.json`. But I've got an error message:

``` 
Error: (/home/breno/projects/gitbook-theme-vtex/templates/website/page.html) [Line 24, Column 20]
 Template render error: Template render error: Template render error: Template render error: Template render error: Template render error: Template render error: (/home/breno/projects/gitbook-theme-vtex/templates/website/includes/summary.html) [Line 35, Column 43]
  Error: Unable to call `__`, which is undefined or falsey
```

**Comment by AaronO** [comment]
@brenoc Can you share the source of your theme at least your `website/page.html` file ?

It seems like you have `nunjucks` template expression that isn't correct, this has probably to do with internationalisation.

**Comment by brenoc** [comment]
@AaronO the source is the exactly the same as https://github.com/GitbookIO/gitbook/tree/master/theme. I was trying to get a starting point.

**Comment by brenoc** [comment]
I tried using the source of https://github.com/Nijikokun/clarity, but it's too old, so I doesn't work with the current version.

**Comment by noerw** [comment]
@AaronO the documentation moved from where you linked.
any new info, on how to extend a theme with custom css?

**Comment by gbraad** [comment]
Some of the links result in 404. I have a similar question as I need multi-columns for the book I am generating.
