### ISSUE TITLE
Webhook problem - how to fix corrupted loose reference

### ISSUE THREAD

**Issue by friedger** [GitbookIO/gitbook#754]
We have an issue on https://www.gitbook.com/book/gdg-wisdom/gdg-wisdom-2015/dashboard with the webhook. The response is a 500

`Corrupted loose reference file: refs/remotes/github/master`

As we don't have access to the files on the gitbook server how can we fix this issue?
Detaching and re-attaching our github repo didn't change anything. Pushing to both repos from the command line is working fine.

Maybe you could add a "re-import" button somewhere that deletes the repo folder on clones from github again.

**Comment by AaronO** [comment]
Hi @friedger,

Sorry about that, I just fixed your repo. An empty ref file was preventing our git server from fetching your GitHub repo after receiving a WebHook.

Give it a try now, it should work as expected.

Sorry for the inconvenience.

**Comment by dw8547** [comment]
Hi AaronO, I have the same problem with a private book. The book is not being updated & I'm getting the following error message when I check the webhook:

`{"ok":false,"event":"push","error":"Corrupted loose reference file: refs/remotes/github/master"}`.

When I used the online editor to make changes to the book the GitHub repo is updated just fine, the same is true when I modify the book in the local repository. However, the changes don't appear in the book.

Would you be able to help? Any suggestions would be appreciated.

**Comment by Mooday** [comment]
Hi I'm having the same issue 
![image](https://user-images.githubusercontent.com/28793157/42360993-9998b11e-80b1-11e8-87ff-af228fe9ff89.png)
Out of nowhere it gives me the "corrupted loose reference file: refs/remote/origin/master" error. Needing help, this project is for today :(
