### ISSUE TITLE
why i failed to run gitbook init?

### ISSUE THREAD

**Issue by chapgaga** [GitbookIO/gitbook#760]
Error: Command failed: git -c core.longpaths=true clone C:\Users\chapgaga\AppData\Roaming\npm-cache_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-10c5b7b0 C:\Users\chapgaga\AppData\Local\Temp\npm-23968-0d8f0705\git-cache-45becb8cf00b\b56048584b3cf2cfebeef78b0fff54690e12e684
Cloning into 'C:\Users\chapgaga\AppData\Local\Temp\npm-23968-0d8f0705\git-cache-45becb8cf00b\b56048584b3cf2cfebeef78b0fff54690e12e684'...
fatal: '/cygdrive/c/Users/chapgaga/AppData/Roaming/npm-cache/_git-remotes/git-github-com-anthonny-opal-npm-wrapper-git-10c5b7b0/C:\Users\chapgaga\AppData\Roaming\npm-cache_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-10c5b7b0' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.ja

btw,  i am using admin priviledge

detailed error message with -d option:
http://pastie.org/10204676#7,9-10,17-18

**Comment by leesei** [comment]
Try clearing npm cache with:

```sh
npm cache clean
```

Hope that helps.

[when all else fails, clear you cache](http://codebetter.com/glennblock/2012/02/27/my-tale-of-npm-woe-when-all-else-fails-clear-you-cache/)
