### ISSUE TITLE
Syntax highlighting and AsciiDoc

### ISSUE THREAD

**Issue by AndreyAkinshin** [GitbookIO/gitbook#761]
What is the right way to format source code in `*.adoc` files. I have tried

    [source,cs]
    ----
    Foo();
    ----

but it don't work. Also I have tried

    [cs]
    ----
    Foo();
    ----

It was recognized as a code block, but syntax highlighting does not apply in this case.

**Comment by SamyPesse** [comment]
Sorry for the delay

**Comment by AndreyAkinshin** [comment]
@SamyPesse, Now I see the highlighting in the editor, but I don't see it in the web version.

**Comment by SamyPesse** [comment]
It's still not released (coming in a few days).
