### ISSUE TITLE
ES6 support in lessons

### ISSUE THREAD

**Issue by ericelliott** [GitbookIO/gitbook#764]
Since Babel has good support for many of the most useful ES6 features, and Babel is capable of working in an [online REPL](https://babeljs.io/repl/), we should add ES6 support to GitBook exercises.

**Comment by SamyPesse** [comment]
This is an issue for https://github.com/GitbookIO/plugin-exercises

**Comment by SamyPesse** [comment]
BTW: it's a good idea ;)
