### ISSUE TITLE
gitbook 2.0.1 doesn't use plugins installed by `npm`

### ISSUE THREAD

**Issue by chengweiv5** [GitbookIO/gitbook#766]
I upgraded gitbook from 1.5.0 to 2.0.1 and found that the newer version of gitbook doesn't load plugins from system-wide npm plugins directory, e.g. `npm install -g gitbook-plugin-anchors`

I use this plugin in several projects and I'd like to install it only once rather than use `gitbook install` for everyone.

Is there a good way to do that or am I missing something important?

Thanks in advance.

**Comment by SamyPesse** [comment]
Sorry, but this is a bad practice, you should not use global packages (https://docs.npmjs.com/misc/faq#i-installed-something-globally-but-i-can-t-require-it)

Add your plugins to your `book.json` then run `gitbook install`
