### ISSUE TITLE
Stop inserting print.css on custom css specified

### ISSUE THREAD

**Issue by wilhelmmatilainen** [GitbookIO/gitbook#775]
Please,

Stop inserting this **print.css** into files when I have specified my own custom styling.

When I add my own style I have to find out all the styling specified in the **print.css** and somehow try to reset it to original, so that it won't mess up libraries and my own styling.

The problem lies in here: https://github.com/GitbookIO/gitbook/blob/master/theme/templates/ebook/page.html#L6

I don't know how to specify that this line is removed on custom css and otherwise included.

**Comment by SamyPesse** [comment]
I agree, we need to find a better solution than forcing stuffs like:

```css
body  .page h1 {
    font-size: 10px;
    color: red;
}
```

There are 3 solutions:

- Remove the `print.css` when a custom style is available
    - **But:** it makes it harder to just extend the default (clean) style
- Add an option to not include `print.css`
    - **But:** I'm not a big fan of too much configurations
- Add an optional `print.css' in `styles`, if present will replace the default print.css
