### ISSUE TITLE
Add anchors to summary

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#776]
Summary.md only allow to add links to other markdown files at all, but it's not possible to add links to subititles inside of them, making it mandatory that each entry on the summary needs to be on its own markdown file and start in its own page/chapter when its not always necesary.

**Comment by despairblue** [comment]
:+1:

**Comment by rhuss** [comment]
:+1:

**Comment by freder** [comment]
:+1:

**Comment by ClintH** [comment]
:+1:

**Comment by AaronO** [comment]
:+1: I think this could be nice.

We would need to see how it works out in PDFs and MOBI/EPUB.

@piranna @despairblue @freder @ClintH Any of you interested in doing a pull request ? ;)

**Comment by piranna** [comment]
I don't have too much time, sorry :-/ Maybe if this were done by a
(build-in) plugin I would take a look, though.

**Comment by ClintH** [comment]
I could give it a stab at some point, but I'm rather fresh to Gitbook (just started using it yesterday) :)

**Comment by despairblue** [comment]
I'm not using gitbook at the moment. So I can't contribute to solving this issue. Sorry :disappointed:
