### ISSUE TITLE
Pdf generator lost a last level of a menu

### ISSUE THREAD

**Issue by xgrommx** [GitbookIO/gitbook#777]
Hello @SamyPesse. I think that pdf generator lost a last level of a menu. You can look on my site and pdf version:

Site: 
![aggregate deprecated _ rxjs - javascript library for functional reactive programming - google chrome 2015-06-01 02 53 40](https://cloud.githubusercontent.com/assets/1499594/7904551/9074508a-0809-11e5-83ea-9dcb1ff66961.png)

Pdf:
![book5 pdf - foxit reader 2015-06-01 02 53 04](https://cloud.githubusercontent.com/assets/1499594/7904556/aa163e18-0809-11e5-80eb-25062cc22494.png)

**Comment by jessiehan** [comment]
same problem

**Comment by jerger** [comment]
same problem

**Comment by SamyPesse** [comment]
Is it still happening with latest gitbook versions ?

I'm working on a PR to improve ebook generation (https://github.com/GitbookIO/gitbook/pull/959), but I can't seem to reproduce this error.

**Comment by jerger** [comment]
Did the retest with version 2.4.3 and the bug still exists. See:
https://dda.gitbooks.io/domaindrivenarchitecture/content/v/32e8627f4bb7c99bee5703c3e75f5dc3af6b0d6e/en/80_config_management/40_architecture/Modules/ddaCore.html

![screenshot - 09 10 2015 - 14 36 05](https://cloud.githubusercontent.com/assets/2706174/10393783/1fb9822a-6e93-11e5-8518-9c630fad2cb4.png)
