### ISSUE TITLE
Refreshing weird effect

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#782]
Because of #759 and https://github.com/GitbookIO/gitbook/blob/master/theme/javascript/core/navigation.js#L25, there is now a weird refresh effect when we are replacing the `head`.

**Comment by damz** [comment]
We are seeing some form of a "weird refresh effect". Something is forcing Chrome to reload/revalidate our web-fonts and it causes a massive flicker effect, made worse by the CSS transitions.

Is that what you are describing?

For some reason, we are seeing this only on Chrome, and only on our production servers and not on our local environments.

It seems like without a proper `Cache-Control` header, Chrome reloads the CSS files when the full `<head>` element is replaced. Once we started serving the CSS files with `Cache-Control: max-age=XXX`, the problem partially went away.

We still have one web-font that is reloaded, but at least the overall flicker is less painful. I have not been able to narrow it down more. I see three obvious differences between the local `gitbook serve` and our production server:

* `gitbook serve` is using HTTP, our server is using HTTPS;
* `gitbook serve` sends out `Cache-Control: public, max-age=0`, while our server issues something like `Cache-Control: max-age=XXXX`;
* `gitbook serve` returns the CSS files as `Content-Type: text/css; charset=UTF-8`, while our server is returning just `Content-Type: text/css`.

Damien

**Comment by patr7** [comment]
Is there any update on this bug, or suggested workarounds? We are seeing jumbled text on certain refreshes. Thank you.

**Comment by patr7** [comment]
The refresh issue went away when we installed with npm specifying gitbook@0.5.2 . It seems that our original install with npm (as detailed in the GitBook README) was pulling down version 0.3.4.
