### ISSUE TITLE
Issue with search and navigation

### ISSUE THREAD

**Issue by arvindsv** [GitbookIO/gitbook#783]
This issue seems similar to #235. But, slightly different.
1. Go to the index page of a gitbook book.
2. Click on the search icon.
3. Search for something e.g., "test".
4. Close the tab (as if you found what you wanted and are done for now)
5. Go back to the index page (note nothing is in the search field, you can even click the search icon and see nothing)
6. Click on a topic

Expected: search is still blank, results are not filtered

Actual: You are taken to the correct topic, but your results are filtered by the search term from step 3 which is now shown in the search box

Here are a couple of gitbooks from [gitbook.com's explore page](https://www.gitbook.com/explore) where this happens:
http://tutorial.djangogirls.org/en/index.html
http://0xax.gitbooks.io/linux-insides/content/index.html

I tried with a completely new browser session as well.

**Comment by arvindsv** [comment]
All credit to @kdishman for finding it, and writing all the steps. I'm just the messenger.

**Comment by CoDEmanX** [comment]
Same issue if you click the search icon (which apparently clears the search field), then click on any link. The search phrase will re-appear and links be filtered. https://docs.arangodb.com/
