### ISSUE TITLE
navigation item order sames uncorrect

### ISSUE THREAD

**Issue by jessiehan** [GitbookIO/gitbook#785]
Summary looks as below

* [section 1](section1.md)
    * [example 1](section1/example1.md)
    * [example 2](section1/example2.md)
* [section 2](section2.md)
    * [example 1](section2/example1.md)

but the order number is not correct, which is   1、1.2、1.3、2、2.3
I think it should be 1、1.1、1.2、2、2.1

**Comment by popotang** [comment]
yes,I have the same problem 
for example , the main section is 1，but the first sub item is start with 1.2 , I should be 1.1 . and the second main section is 2, but the first sub item is 2.3

**Comment by SamyPesse** [comment]
It has been fixed on version 2.1.0: https://github.com/GitbookIO/gitbook/blob/master/CHANGES.md#210
