### ISSUE TITLE
Styles in root folder not working with multilanguage books

### ISSUE THREAD

**Issue by aniav** [GitbookIO/gitbook#788]
There is a possibility to include the styles by adding them to the definition in `book.json`.
We have a multilanguage book, and I have noticed that adding the styles will work perfectly fine if they are added to one of the language folders.
We would like the styles to apply to all the languages and not be placed in each language separately and currently we can't do that. The folder `styles`, placed in the root folder isn't being transferred to the generated book. I have tried defining the styles in various ways, for example: `./../styles/website.css`, `/styles/website.css`, `../styles/website.css`. I have also tried moving the file to the root folder and changing the definition in `book.json`. None of this works.

We are using gitbook@2.1.0

**Comment by SamyPesse** [comment]
I'm going to fix this for the next release.

**Comment by billryan** [comment]
When will this issue be fixed? Is there any schedule or roadmap?
