### ISSUE TITLE
Changing font size in iBooks iPhone app changes nothing

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#791]
(Bug reported to gitbook.com)

**Comment by onevcat** [comment]
+1 for this. It works well in iBooks app on OS X. But in iPhone, it fails to change the font size.

**Comment by teejayvanslyke** [comment]
+1, On my iPad running iOS7, iBooks will not change the font size. It increments the font size (at least, it disables the +/- buttons when the min or max is reached), but the font remains the same.

Changing other display options works as expected.

**Comment by onevcat** [comment]
It seems the font size cannot be changed yet in the newest version (2.5.2). 
I tried to regenerate my book in epub format in gitbook 2.5.2, but I cannot adjust the font size in iPhone with iOS 9.
