### ISSUE TITLE
add body-progress or cumstom layout

### ISSUE THREAD

**Issue by zuoRambo** [GitbookIO/gitbook#792]
I'm confused about the layout of the website generated by gitbook. I create one example site under the guidance of readme.md file. but i find some question or diff with other book.
in [workerman manual](http://doc.workerman.com) ,i find that it's body-header is on the top and there is a div[class=book-progress] under page-wrapper & below page-inner?
how could the cusmtom my site to like that?
thanks a lot!

**Comment by dickielayden** [comment]
I'm also confused about this and would love some feedback.

I would like to be able to have the book progress bar for my chapters but I can't see the book-progress stuff in the latest 2.1.0 version of gitbook.

i believe that the progress bar stuff came from the clarity theme from nijikokun 
But then I read that gitbook is using the clarity theme as the default theme...
But no progress bar...

I've tried to install gitbook-theme-clarity into my 2.1.0 but I'm not having much joy.

Can somebody put me out of my misery?

Dickie

**Comment by zuoRambo** [comment]
@dickielayden hey buddy, i have solve the problem by another way. 
First of all, the progress-staff is a plugin you can add in your book.json file to install it, the plugin's name is 'anchors', so it will be like the follow segment
```json
{
    ...
    "plugins": ["maxiang","anchors"],
    ...
}
```
and the maxiang is a beautiful theme.
Then, you should to know ,[new version deprecated many hooks which was depended by some plugins ](https://github.com/GitbookIO/gitbook/issues/793)
Last, hope those could help you.

**Comment by dickielayden** [comment]
Many thanks for your help
Those plugins are great - unfortunately that's not quite what I wanted.

i was really wanting my gitbook to look like:
http://jason.bryer.org/Rgitbook/index.html

I will keep digging around.

Thanks again for your help
