### ISSUE TITLE
why page,page:before hooks was removed?

### ISSUE THREAD

**Issue by zuoRambo** [GitbookIO/gitbook#793]
```js
// Type of plugins resources
Plugin.RESOURCES = ["js", "css"];
     = [
    "init", "finish", "finish:before"
]
```
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be removed in the coming versions

**Comment by ymcatar** [comment]
Same here. It is a bug or if we can indeed use it safely in our plugin? Is it really deprecated?

**Comment by zuoRambo** [comment]
@ymcatar yes! so i use the gitbook@0.7.1 to solve the problem.

**Comment by leesei** [comment]
It is not a bug.
The warning is quite clear, those hooks are in the process of deprecation.
Use template blocks instead, see [doc](http://help.gitbook.com/format/templating.html) and [sample](https://github.com/GitbookIO/plugin/blob/master/index.js#L53)

**Comment by SamyPesse** [comment]
These hooks are no longer deprecated (https://github.com/GitbookIO/gitbook/commit/a4422593f20b9e410f13841cc20b8b9a1632eab0), but we advice to use blocks and filter when possible.
