### ISSUE TITLE
how to insert table in list ?

### ISSUE THREAD

**Issue by saifulindo** [GitbookIO/gitbook#794]
I try to insert a table into a list format markdowns as in the picture, Not Working:
![gitbook](https://cloud.githubusercontent.com/assets/1446053/8075788/eafffb32-0f6e-11e5-9ed6-f01fec50f16a.png)

Thanks.

**Comment by cesards** [comment]
+1 here

Gitbook doesn't support markdown alignments

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

**Comment by tormi** [comment]
The problem is that Gitbook uses 2 hyphens instead of 3 which is required for rendering tables correctly. Ref: https://github.com/github/markup/issues/371#issuecomment-56119335

**Comment by infotexture** [comment]
This isn't an issue with the number of dashes used for the separator line between table head and body as mentioned in github/markup#371. 

The problem is that GitBook doesn't seem to support tables nested within list items.

The following table within a list renders fine on GitHub:

> 1.  Download the package for your operating system from the project website:
> 
>     |Operating system|File name|
>     |----------------|---------|
>     |Linux or Mac OS X|file.tar.gz|
>     |Windows|file.zip|
> 
> 2.  Extract the contents of the package to the directory.

but in GitBook, the table is not recognized, and renders the dashes and pipe symbols literally:

```html
<ul>
  <li>
    <p>Download the package for your operating system from the project website.</p>
    <p>|Operating system|File name|
      |----------------|---------|
      |Linux or Mac OS X|file.tar.gz|
      |Windows|file.zip|</p>
  </li>
  <li>
    <p>Extract the contents of the package to the directory.</p>
  </li>
</ul>
```

**Comment by saifulindo** [comment]
OK. Thanks.

**Comment by mzlogin** [comment]
+1. Met the same problem. Any plan to support table nested in list?

**Comment by joepeak** [comment]
+1. Met the same problem.

**Comment by nashiki** [comment]
+1. Met the same problem.

**Comment by whimsycwd** [comment]
+1. Met the same problem.

**Comment by iVapor** [comment]
+1. The same problem. So I use HTML in Markdown.

**Comment by Huxpro** [comment]
+1

**Comment by marcobjorge** [comment]
+1

**Comment by akuma** [comment]
+1

**Comment by xiaohaoliang** [comment]
+1
