### ISSUE TITLE
Hide jekyll frontmatter

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#795]
We should hide metadata from Jekyll (for authors transitioning from it):

```
---
page: test
---
``

**Comment by AaronO** [comment]
The simple solution would be to add a rule for this in `kramed` and simply have no output rule in the html renderer.

**Comment by SamyPesse** [comment]
@AaronO :+1:

**Comment by jmatsushita** [comment]
+1 I need this too to migrate from Jekyll content, and to explore the possibility to use the gitbook editor and PDF renderer but using Jekyll (or other yaml frontmatter compatible static site generator) for the web rendering.

**Comment by clemsos** [comment]
+1 badly needed. How can I help to implement this ?

**Comment by SamyPesse** [comment]
I'll work on it next week, I'm going to make a PR to change the markdown parser to [markdown-it](https://github.com/markdown-it/markdown-it) in [gitbook-markdown](https://github.com/GitbookIO/gitbook-markdown).

**Comment by SamyPesse** [comment]
GitBook v3 process YAML frontmatter to extract page properties
