### ISSUE TITLE
How to extract the title of book.json in md?

### ISSUE THREAD

**Issue by sjm44** [GitbookIO/gitbook#802]
I want to extract the metadata `title` of `book.json` in the md file, then tried the `{{ title }}` and `{{ book.title }}` but don't take effect...

Is there any solutions to meet this? 3x a lot.

**Comment by SamyPesse** [comment]
`{{ book.options.title }}` should work.

**Comment by SamyPesse** [comment]
This will be possible in next release as `{{ config.title }}`.
