### ISSUE TITLE
Are block arguments parsed properly?

### ISSUE THREAD

**Issue by uliska** [GitbookIO/gitbook#804]
I'm writing a plugin and have something like this in it:

```javascript
  blocks: {
      authors: {
        process: function(block) {
          return "<div class=\"authors\">Main authors: "+block.args+"</div>";
        }
      }
  }
```

Basically this works, but I have the impression that the last argument in the input file is not included in the `args` list:

`{% authors "The author", "Someone else", "Yet another one" %}{% endauthors %}`
will give me `The author,Someone else`, while
`{% authors "The author" %}{% endauthors %}`
will result in an empty list.

Is this a bug or am I missing something?

**Comment by SamyPesse** [comment]
Thanks for pointing this out, The fix will be in the next release.

**Comment by uliska** [comment]
Thanks. That was fast ...
