### ISSUE TITLE
Markup to indicate end of page

### ISSUE THREAD

**Issue by xtrasmal** [GitbookIO/gitbook#807]
Hello,

Is there a way I can add markup that indicates that everything below this markup should be rendered on another page?

Something like this:

```markdown

# Chapter 1 

This is an extreme long text of which I want to control 

![end-page]

where it continues on the next page

```

So when rendering doing ```gitbook pdf ./my-book``` it will give me 2 pages.

**Comment by AaronO** [comment]
@xtrasmal Markdown doesn't have page breaks builtin by default, but since you can use HTML that should work.

Try inserting:

```
<div style="page-break-after: always;"></div>
```

**Comment by xtrasmal** [comment]
@AaronO  That worked out wonderfully, thank you so much.
