### ISSUE TITLE
Failed to create,  delete or save file

### ISSUE THREAD

**Issue by witwall** [GitbookIO/gitbook#808]
when I tried to delete a file, I always got the message
```Failed to parse revision specifier - Invalid pattern ''```
![gitbook00](https://cloud.githubusercontent.com/assets/3222056/8346453/5dc788f8-1b2f-11e5-8cc4-5be7442bb9b5.png)

and when I tried to create a new file, I got 
```missing argument 1 when calling function c[l]```
![gitbook01](https://cloud.githubusercontent.com/assets/3222056/8346454/6384d228-1b2f-11e5-94a0-8a424fabe972.png)

and whenI tried to save a file, I got
![gitbook02](https://cloud.githubusercontent.com/assets/3222056/8346652/7309bdf0-1b32-11e5-8864-a8272a675fc2.png)

then I have to refresh the page, though the content is saved correctly.

**Comment by rharbird** [comment]
Yes, I'm experiencing these problems too.

**Comment by SamyPesse** [comment]
- What browser are you using ?
- Is your book hosted on GitHub ? What are you book's ids ?
- Are you working on the master branch ?

**Comment by rharbird** [comment]
* Chrome and Firefox
* No, the book is not hosted on GitHub (but if it solves the problem I can do so).
* Title: 'The Engduino Challenge Book' - https://www.gitbook.com/book/raeharbird/engduinochallenges/dashboard
* Yes, working on the master branch

Thanks

**Comment by SamyPesse** [comment]
The save bug has been fixed, the other one (delete) will be fixed soon.

**Comment by SamyPesse** [comment]
The delete has been fixed.
