### ISSUE TITLE
Allow processing md files NOT included in SUMMARY.md

### ISSUE THREAD

**Issue by ramnathv** [GitbookIO/gitbook#81]
Here is my use case. I want to include some static exercises in an `exercise.md` file in a chapter so that it is displayed as a separate page. However, I don't want it cluttering my navigation. I will be including it as a link at the end of a lesson. Currently, there is no way for me to tell  `gitbook` to build this file since it is not included in `SUMMARY.md`.

**Comment by 13abylon** [comment]
Are there any updates on this idea? I would like to see it in the future!

**Comment by hpehl** [comment]
+1 having this in 2.0

**Comment by akshayrawat** [comment]
+1 on having this in 3.2

**Comment by bethesque** [comment]
+1

**Comment by ekristen** [comment]
+1

**Comment by brettelliot-efl** [comment]
+1

**Comment by jsntn** [comment]
+1

**Comment by tidyjiang8** [comment]
+1, and the following doesn't work any more:
```
- [chapter1](chapter1/readme.html)
  - [example1](chapter1/example1.html)
  - [*example2](chapter1/example2.html)
```
or
```
- [chapter1](chapter1/readme.md)
  - [example1](chapter1/example1.md)
  - [*example2](chapter1/example2.md)
```

**Comment by jfrux** [comment]
+1

**Comment by zzq0324** [comment]
+1

**Comment by yujiangshui** [comment]
still need this 😂
