### ISSUE TITLE
DOWNLOAD LINK???

### ISSUE THREAD

**Issue by xtrasmal** [GitbookIO/gitbook#816]
Hello there

Who uses online editors anyways. Where can download the offline editor for OSX.

This is just really insanely hard to find!!!!!

**Comment by leesei** [comment]
Well, the offline editor has been put into legacy mode.
You can download it from [GitbookIO/editor-legacy](https://github.com/GitbookIO/editor-legacy).

But this info is not hard to find, I used a site called Google.
