### ISSUE TITLE
markdown display error

### ISSUE THREAD

**Issue by chaucerling** [GitbookIO/gitbook#817]
gitbook: http://kaisery.gitbooks.io/rust-book-chinese/content/content/4.4.Documentation%20%E6%96%87%E6%A1%A3.html
github: https://github.com/KaiserY/rust-book-chinese/blob/master/content/4.4.Documentation%20%E6%96%87%E6%A1%A3.md

**Comment by SamyPesse** [comment]
The only difference I see is caused by the font size settings: https://github.com/KaiserY/rust-book-chinese/blob/master/book.json#L16 You should remove this value ti use the default one.

Let me know if there is something else I'm missing.
