### ISSUE TITLE
Special letters - problem

### ISSUE THREAD

**Issue by bogdankowalski** [GitbookIO/gitbook#818]
I would like to write in gitbook with my native language (polish), that has unique letters such as: ą, ę, ł, ś, ć, ó, ż, ź. When I try to put in one of those, "ą" for example, usually i need to use the combination of ALT + A. In Gitbook however, this combination doesn't work, so I can't use polish letters.

**Comment by leesei** [comment]
[The curious case of the disappearing Polish S — Medium Engineering — Medium](https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df)

I read this interesting article some time before. It seems to be the same problem.
