### ISSUE TITLE
Keyboard re-mapped

### ISSUE THREAD

**Issue by rogeralsing** [GitbookIO/gitbook#820]
In the markdown editor, if you press `ctrl` + `7` gitbook MD editor renders a `*` and moves the cursor down.
On a Swedish keyboard, `ctrl` + `7` is the key combination for `{` so if you try to write code, you will have a really bad time as its impossible to type any curly brace in your editor, at least using a swedish keyboard layout..

**Comment by dominiks** [comment]
Same issue when using a German keyboard. Makes the editor unusable without switching the layout.

**Comment by SamyPesse** [comment]
We just released a new version of the editor with a settings to disable keyboard shortcuts, the next release will include settings to set your own keyboard shortcuts.
