### ISSUE TITLE
Creative Commons HTML breaks editor

### ISSUE THREAD

**Issue by ThomWright** [GitbookIO/gitbook#821]
#### Symptoms
On affected page:
- no preview
- when trying to change file from the 'Files Tree' the hash in the URL changes but the UI doesn't respond

#### Cause
As far as I can tell, the following HTML, generated from [Creative Commons](https://creativecommons.org/choose/), seems to be the problem. All other files in [my repo](https://github.com/circuitsim/electronic-circuit-simulation) seem to be fine.
```html
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
  <img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
</a><br />
<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Electronic Circuit Simulation</span> by 
<a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/circuitsim/electronic-circuit-simulation" property="cc:attributionName" rel="cc:attributionURL">Thom Wright</a> is licensed under a 
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
```

**Comment by ThomWright** [comment]
**Update**
Having something like the following also breaks:
```html
<div align="center">This is some text!</div>
```
but having a simple `div` seems fine:
```html
<div>This is some text!</div>
```

**Comment by SamyPesse** [comment]
It should be fixed in the latest release.

**Comment by znmeb** [comment]
Thanks! I had to take the CC stuff out of my build. Testing it now.
