### ISSUE TITLE
React errors - DOM mutations?

### ISSUE THREAD

**Issue by ThomWright** [GitbookIO/gitbook#822]
The following error appeared in the preview pane today on gitbook.io.

Unfortunately I was unable to get any more info from the console. I'll update this issue if it happens again.

![image](https://cloud.githubusercontent.com/assets/1884486/8671980/9868fca2-2a21-11e5-8187-ef08ec575e7b.png)

**Comment by SamyPesse** [comment]
Fixed in the new release.
