### ISSUE TITLE
Math rendering

### ISSUE THREAD

**Issue by ThomWright** [GitbookIO/gitbook#823]
I'm using `KaTeX` for my equations, and there is a big difference between what I see in the preview and in the actual book. 

**Preview**
![image](https://cloud.githubusercontent.com/assets/1884486/8673868/0ea07156-2a32-11e5-8997-423cef42d038.png)

**Book**
http://thomwright.gitbooks.io/electronic-circuit-simulation/content/DC%20Analysis.html
![image](https://cloud.githubusercontent.com/assets/1884486/8673881/25aa1c6c-2a32-11e5-8d12-60831e18aea1.png)

**Source**
```tex
Rather than constructing a list of equations node-by-node, it is often easier to build up the matrix element-by-element, using ‘matrix stamps’. Using this technique, every element contributes a set pattern to Equation . Equation  shows the contribution to the $$Y$$ matrix of a resistor with conductance $$g_k$$ from node $$i$$ to node $$j$$:

$$
\begin{array}{cc}
\begin{bmatrix}
g_k & -g_k \\
-g_k & g_k
\end{bmatrix}
&
\begin{matrix}
row\ i\\ 
row\ j
\end{matrix}
\\
col\ i \quad col j
\end{array}
$$
```

**Comment by AaronO** [comment]
@ThomWright There difference you're getting comes from the fact that the Preview uses MathJax while you're using the KaTex plugin, one solution would be to use the MathJax plugin.

Ideally KaTeX will improve to the point where it's a full replacement of MathJax, unfortunately as of today MathJax is more feature complete / compliant, so that's what we use in the preview.

**Comment by ThomWright** [comment]
@AaronO Gotcha. Would it be possible to make the preview use whichever plugin is selected? Otherwise the usefulness of the preview somewhat diminishes...

**Comment by ThomWright** [comment]
Even using MathJax there are discrepancies between the preview and the actual online rendering. For example, using `\!` for small spaces:

**Preview**
![image](https://cloud.githubusercontent.com/assets/1884486/8678289/aa5469b8-2a4b-11e5-8a0d-2c96ac6232bb.png)
**Book**
![image](https://cloud.githubusercontent.com/assets/1884486/8678318/cfed3416-2a4b-11e5-9e6a-e2c474a6dac8.png)
**Source**
`$$n\!+\!1$$`
