### ISSUE TITLE
markdown versus commonmark

### ISSUE THREAD

**Issue by thorade** [GitbookIO/gitbook#826]
Just a question:
According to 
http://help.gitbook.com/format/markdown.html 
you are supporting John Gruber's Markdown or Github-Flavored-Markdown.

AFAIK, github supports the [commonmark.org](http://commonmark.org/) initiative and will use CommonMark everywhere in the future. Will you in the future support multiple markdown flavors or will you follow the switch to CommonMark?

**Comment by erlend-sh** [comment]
The [markdown-it](https://github.com/markdown-it/markdown-it#syntax-extensions) library quite outstanding. It follows the CommonMark spec along with common extensions such as GFM and other optional goodies such as superscript, abbreviations and footnotes, all very useful for book formatting.

**Comment by SamyPesse** [comment]
markdown-it looks really great, I'll take a deep look at it, I'm not sure it's already supporting some of the KramDown syntaxes that gitBook supports.

**Comment by thorade** [comment]
The above link is broken, docs are now here:
http://toolchain.gitbook.com/syntax/markdown.html

github now uses kramdown:
http://kramdown.gettalong.org/

**Comment by erlend-sh** [comment]
GitHub is all-in on CommonMark now:

https://githubengineering.com/a-formal-spec-for-github-markdown/
