### ISSUE TITLE
How could I install gitbook on my own server?

### ISSUE THREAD

**Issue by nntoan** [GitbookIO/gitbook#828]
Greeting world,

I'm amazed by there is a platform like GitBook exists. It's too perfect for my service, I'm wondering how could I host this platform in my own server?

**Comment by xabeng** [comment]
Why host on your server? What do you want to get from it?

**Comment by nntoan** [comment]
I found there is a stuff call Forever in Node, then I think I have to build my own platform to make GitBook run on my own server.

**Comment by dev-clavis** [comment]
+

**Comment by Mtax** [comment]
+1
