### ISSUE TITLE
GitBook.com support not active?

### ISSUE THREAD

**Issue by naturalprogrammer** [GitbookIO/gitbook#832]
GitBook.com is a great platform, and I have started to author my books on it.

However, I had posted a query to GitBook support (https://www.gitbook.com/contact) a few days back, but did not receive a response. Hope the platform is active. If not, I'd like to know if there is any other online platform for hosting gitbooks.

**Comment by SamyPesse** [comment]
The platform is still active and we have a lot of great stufs that we'll release in the coming weeks.

Sorry that we didn't answer your support question, we'll get back to you as soon as possible.

**Comment by naturalprogrammer** [comment]
That's great, Sammy! I am blown away by the elegance of GitBook, its plugin system etc. Great work!

**Comment by naturalprogrammer** [comment]
The question I had asked long back at GitBook support (https://www.gitbook.com/contact) isn't answered yet, and so I'm getting a bit worried about what happens if I publish commercial books there and my readers or me don't not get support in a reasonable amount of time. Probably you guys have currently become busy here, and would be getting back to gitbook.com soon?

**Comment by SamyPesse** [comment]
I just answer your support question, again I'm really sorry for the late answer, we are focus on the next release and improving the web-editor.
