### ISSUE TITLE
Disable pushState?

### ISSUE THREAD

**Issue by cmichaelgraham** [GitbookIO/gitbook#834]
Is there already a way to disable the use of push state when navigating to pages in my book?

**Comment by cmichaelgraham** [comment]
the reason i want to be able to do this?  i figured out how to put adsense banners to the right of my page, and i want the page to load completely on each navigation.

i'd really like it if this was a flag in book.json (so i don't have to hack the code, build it with grunt, and then copy the app.js into my book ;)

**Comment by geeyan** [comment]
+1， same demands
