### ISSUE TITLE
<div> with "style" specified breaks online editor

### ISSUE THREAD

**Issue by hawkhero** [GitbookIO/gitbook#835]
# Steps to reproduce
1. enter <div style="text-align:center"></div>

# The result I saw

The preivew area shows error message below:
> Invarriant Violation: The 'style' prop expectes a mapping from style properties to values, not a string. For example...

**Comment by ThomWright** [comment]
Dupe of #824?

**Comment by AaronO** [comment]
@hawkhero @ThomWright Yes, this is a duplicate. Closing this in favor of #824 which we should fix/change (and when fixed will fix your issue).
