### ISSUE TITLE
Styles resetting after change page in serve mode

### ISSUE THREAD

**Issue by theaqua** [GitbookIO/gitbook#838]
Hi, I run `gitbook serve` and when I went to another page, styles resets and page is glitching.
Here's a [demo](https://www.dropbox.com/s/zrxnrjcdcyb0rmv/Untitled.mov?dl=0).

Weird bug.

**Comment by gaearon** [comment]
It also happens in the production builds.

**Comment by mikekaminsky** [comment]
Happening locally and on gitbook.com for me.

**Comment by AaronO** [comment]
@gaearon My PR: https://github.com/GitbookIO/gitbook/pull/847 fixes this.

The bug was originally introduced by #759

**Comment by AaronO** [comment]
@gaearon This should be a good UX improvement already :), I wasn't fond of the flickering myself ... ;)

I'm working on a few other quick things, we'll get those packaged up and out the door in a new release soon !

**Comment by AaronO** [comment]
Fixed by #847

**Comment by gaearon** [comment]
Hey, thanks a lot for working on this! I appreciate it a lot.

**Comment by theaqua** [comment]
Thanks, @AaronO!
