### ISSUE TITLE
Include inside a codeblock

### ISSUE THREAD

**Issue by gaearon** [GitbookIO/gitbook#839]
I can use `{% include "../../src/myfile.js" %}` but if I put it inside a codeblock annotated with three backticks, Gitbook ignores it. I just want a way to include my actual source code in the docs (and have it highlighted). Is it possible without plugins?

**Comment by xgrommx** [comment]
@gaearon Maybe better use it? https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting. In my book I use this approach and jsbin http://xgrommx.github.io/rx-book/content/guidelines/when/index.html and http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/aggregate.html

**Comment by xgrommx** [comment]
@gaearon But probably you can use this plugin http://plugins.gitbook.com/plugin/include-highlight
