### ISSUE TITLE
Control/Disable the Page Read Checkmark

### ISSUE THREAD

**Issue by timdoes** [GitbookIO/gitbook#848]
Is there a way to control or disable the page read checkmark? I have looked through all the docs and issues but have found nothing. This seems like a very important feature for people using this to create training books.

**Comment by SamyPesse** [comment]
We can add a configuration in `book.json` to disable it. But this feature should probably be a plugin instead of being in the gitbook core.

**Comment by ddidier** [comment]
I agree that would be an appreciated feature, thanks

**Comment by SamyPesse** [comment]
This feature is no longer present in the latest versions. I'll reimplement it as a plugin if needed by authors.

**Comment by wohenbushuang** [comment]
@SamyPesse But what if we need this feature now? may be it's better to remove it after the plugin released. By the way, which version should i roll back to if i want the checkmark?

**Comment by hedleysmith** [comment]
We're building a set of training material on Gitbook and it would be very useful for the participants of the training courses to be able to mark off or see what they've read. Is there are documentation for writing plugins so we could help to bring this in as a plugin?

**Comment by johnnychen** [comment]
feature wanted!~

**Comment by josephkandi** [comment]
I really want this features, keen on adding it as a plugin, where are the docs for it and in what version of gitbook is it implemented, willing to rollback to get it.

**Comment by hckhanh** [comment]
Me too, I find everything but I cannot find the way to add this feature :cry: 

Like Redux documentation: http://redux.js.org

**Comment by rahul286** [comment]
Oh. I came here looking for this feature only!

This feature is an essential one to track training progress.

**Comment by Alicture** [comment]
is there any plugin for this?...
