### ISSUE TITLE
Make GitBook lighter ?

### ISSUE THREAD

**Issue by AaronO** [GitbookIO/gitbook#850]
Here's a proposal to make GitBook lighter, improving page loads and UX (flickering, etc ...) (partially solved by #847). I would love to hear your input.
- [x] Prefer local/system fonts over web fonts (#849)
  - I think we can get these very similar looking that it won't really affect rendering quality
  - Text will render a lot faster and won't flicker since it won't need to fetch the webfonts
- [ ] Optimize JS
  - [ ] Replace `require.js` with `browserify` (we don't need `require.js` 's runtime dependency) (would this break plugins ?)
  - [ ] Replace `jquery` with `minified.js` (since we only use a subset of jquery)
  - [ ] Drop `lodash` ? (this is less of a gain)
- [ ] Use optimized assets (there's a few un-optimized that are shipped) (some images, etc ...)

The big one here is webfonts IMHO, they are the bigger annoyance and will likely have the biggest UX impact for a given "cost".

Let me know what you think.

**Comment by piranna** [comment]
browserify works as a charm :-) It should not give problems for the plugins.

**Comment by SamyPesse** [comment]
@piranna browserify will break plugins, for example: https://github.com/GitbookIO/plugin-mathjax/blob/master/book/plugin.js#L1 We can maybe export a special `require(modules, callback);' But why using browserify instead of just concatenating JS with a compatibility `require(modules, callback)` ? 

Switching from `jquery` to `minified.js` will also break a lot of plugins. And dropping `lodash` will break a few plugins that depend on it.

**Comment by piranna** [comment]
> @piranna browserify will break plugins, for example: https://github.com/GitbookIO/plugin-mathjax/blob/master/book/plugin.js#L1 We can maybe export a special require(modules, callback);' But why using browserify instead of just concatenating JS with a compatibilityrequire(modules, callback)` ?

That require() function don't have the same signature of Node.js require() and it's not compatible so browserify will not work. require.js seems useful in browser environments, but for Node.js + browser ones, browserify is the standard.


> Switching from jquery to minified.js will also break a lot of plugins. And dropping lodash will break a few plugins that depend on it.

This can be left for gitbook 3, +1 to remove these dependencies and minimize gitbook.

**Comment by SamyPesse** [comment]
@piranna I know, but we can easily switch to browserify and have a backward compatibility with something like:

```js
var _ = require('lodash');

var modules = {
    'gitbook': require('./gitbook'),
    'something': require('./something')
};

window.require = function(modules, callback) {
    var results = _.map(modules, function(mod) {
        if (!modules[mod]) throw new Error("Module not found: "+mod);
        return modules[mod];
    });
    callback(results);
};
```

**Comment by piranna** [comment]
Will it work in Node.js, or would be conflicts?

**Comment by SamyPesse** [comment]
Why do you want it to work in Node.JS ? We are just talking about the client-side JS (located in https://github.com/GitbookIO/gitbook/tree/master/theme/javascript). GitBook itself will not run in the browser, so we don't need it to be built with browserify. If you want to use some parts of GitBook in the browser, take a look at https://github.com/GitbookIO/gitbook-parsers

**Comment by AaronO** [comment]
@SamyPesse @piranna Reducing the size of the JS code isn't an absolute must, it shouldn't have a massive impact, it would be nice but I think removing webfonts is the big improvement, having lighter JS is a bonus.

Out of the JS code I think `require.js` + `jquery` is about 80% of the code, `lodash` isn't that bad (~20kb), either way, we can plan that later, I don't think breaking plugins for a few `kb` is worth it.

**Comment by kylebrowning** [comment]
Using require seems to break gitbook builds when putting them inside a node app.

For example, try putting a gitbook book into electron, all hell breaks lose.

**Comment by piranna** [comment]
Sorry, I missed the mails. I was thinking about using a standard Node.js + browserify build flow, also for the client-side JS. The more standard we do things, the better.
