### ISSUE TITLE
Creative Commons SVG badges not correctly rendered on PDF

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#853]
When including a Creative Commons SVG badge like http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.eu.svg and create a PDF gitbook, the badge gets heavily pixelated and lowres, also worse than the png equivalent. Other SVG images on the document like https://github.com/NodeOS/media/blob/master/NodeOS.svg gets correctly rendered.

**Comment by piranna** [comment]
I've reviewed the images source code and the Creative Commons one size is defined in pixels while the NodeOS one is defined in centimeters. Would this be the reason? Shouldn't the html generated for PDF output use a 300ppp resolution or higher? Maybe also the ppp could be configured...

**Comment by SamyPesse** [comment]
We are currently using [svgexport](svgexport) to convert svg to png during ebooks build. We have the same issue with math rendering.

**Comment by piranna** [comment]
So SVG images are converted to PNG images first to create a PDF? Webkit (used by PhantomJS) has native support for SVG, so I don't think this extra step is neccesary...
