### ISSUE TITLE
Better syntax highlighting: line numbers and highlighted blocks

### ISSUE THREAD

**Issue by naturalprogrammer** [GitbookIO/gitbook#869]
I am authoring a few software books, and am often feeling the shortage of line numbers and highlighted blocks inside syntax highlighting, like [this](http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/). These features would certainly help authors like me to explain the code to the readers more clearly.

As I understand, the currently used JS library doesn't support this feature. Was wondering if some other JS library, whatever other sites use for this kind of highlighting, could be instead used.

**Comment by martinibooks** [comment]
Hi Sanjay.

Check out FicShelf.com  - we would love to assist you!

Best regards

Martin
ᐧ

On Sat, Aug 15, 2015 at 8:55 AM, Sanjay Patel <notifications@github.com>
wrote:

> I am authoring a few software books, and am often feeling the shortage of
> line numbers and highlighted blocks inside syntax highlighting, like this
> <http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/>. These
> features would certainly help authors like me to explain the code to the
> readers more clearly.
>
> As I understand, the currently used JS library doesn't support this
> feature. Was wondering if some other JS library, whatever other sites use
> for this kind of highlighting, could be instead used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/869>.
>



-- 
*Martin Szyllo*
*Co-founder, Chief Technology Officer*

*ficshelf.com <http://ficshelf.com>*

FicShelf Limited
189-190 Shoreditch High Street
London
E1 6HU
Office #7

mobile: +447412997939

**Comment by SamyPesse** [comment]
I agree this can be useful, but this can be achieve using a plugin and we can keep the gitbook core as it is.

Some example of plugins:
- http://plugins.gitbook.com/plugin/ace
- [Plugins about "code"](http://plugins.gitbook.com/?q=code)
