### ISSUE TITLE
gitbook init in Mac

### ISSUE THREAD

**Issue by ahmadalkaid** [GitbookIO/gitbook#871]
Hi guys,

After I follow up with the steps you provided, I couldn't run "gitbook init " even with the sudo command in mac os 10.10.4 , so could you provide us with more information on this issue ?? 
note after I run this command bash give's me 
sudo: gitbook: command not found

Thanks,
-Kaid

**Comment by yurrriq** [comment]
Make sure you use the `-g` flag with `npm install`.

**Comment by SamyPesse** [comment]
You need to install `gitbook-cli`:

```
$ npm install gitbook-cli -g
$ gitbook init
```

`gitbook-cli` is high-level manager to use multiple versions of gitbook on the same machines.

**Comment by ahmadalkaid** [comment]
Sorry guys, I didn't tank you for this later and earlier.
So.. Thx alot :)
