### ISSUE TITLE
Files aren't building

### ISSUE THREAD

**Issue by theasder** [GitbookIO/gitbook#872]
During build of PDF, EPUB and MOBI version of book occured error:

    Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:124:16)

Though, web version is ok.

**Comment by SamyPesse** [comment]
This error is happening when the book includes images with invalid urls.

Basically, when building ebooks, GitBook will download all images included in books, if the image doesn't exist, it currently failed with the error from node.js.

We need to improve this error message to be more helpful.
