### ISSUE TITLE
eperm lstat

### ISSUE THREAD

**Issue by imshann** [GitbookIO/gitbook#876]
When I running "gitbook serve".Once I change my file.It is show.

Stopping server
info: loading book configuration....OK
info: load plugin gitbook-plugin-livereload ....OK
info: >> 1 plugins loaded
info: start generation with website generator
info: clean website generator
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EPERM, lstat 'C:\Users\Administrator\Desktop\wdphp_book\gitbook'
    at Error (native)

what happen?

**Comment by myhere** [comment]
+1
