### ISSUE TITLE
Webhooks don't get added to GitHub

### ISSUE THREAD

**Issue by wimpers** [GitbookIO/gitbook#879]
* Following is the GitHub repo https://github.com/openvstorage/ovs-documentation. I have access to https://github.com/openvstorage/ovs-documentation/settings/hooks.
* The Book is https://www.gitbook.com/book/openvstorage/openvstorage

When clicking add deployment webhook I see a spinning icon for a second, no error but the webhook doesn't get registered in GitHub. I tried removing and adding the GitHub repo but no luck.

**Comment by billhsu** [comment]
same here.

**Comment by rwatts3** [comment]
Likewise , major issue connecting to github account.
I've spent nearly 6 hours trying to get this to work. 

```sh
Error: An user is already associated to this github account.


```

**Comment by SamyPesse** [comment]
@rwatts3 it's not the same issue, in your case, you created 2 accounts (http://help.gitbook.com/account/duplicate.html).

You need to remove the other account.

**Comment by TomasKulhanek** [comment]
Same here
* github repo https://github.com/TomasKulhanek/medical-physiology-in-modelica
* book is https://www.gitbook.com/book/tomaskulhanek/medical-physiology-in-modelica

**Comment by wimpers** [comment]
Hi Samy,

any update on this issue?

**Comment by SamyPesse** [comment]
You can add the webhook shown at https://www.gitbook.com/book/openvstorage/openvstorage/settings/github by hand to your GitHub repository.
