### ISSUE TITLE
template  {% raw %}  has a bug?

### ISSUE THREAD

**Issue by sojuker** [GitbookIO/gitbook#882]
`{% raw %}` works， but not work perfectly.

what I want is that in the output file, `{% raw %}` and  `{% endraw %}`  don't appear.

env: 
```
{
    "gitbook": "2.2.0",¬                                                                                   
    "language": "zh-cn"¬
} 

gitbook -V
0.3.4
```

## input
![qq20150827-1](https://cloud.githubusercontent.com/assets/2988612/9511126/c7c50170-4ca5-11e5-91a3-d957d302b63f.png)

## output
![qq20150827-2](https://cloud.githubusercontent.com/assets/2988612/9511125/c77073da-4ca5-11e5-9f88-5fa01d75e3b8.png)

**Comment by SamyPesse** [comment]
That's not a bug, code blocks are escaped by default, you don't need to add `{% raw %}` in your code blocks.
