### ISSUE TITLE
It's no convenient to move .md files after creation

### ISSUE THREAD

**Issue by zzxwill** [GitbookIO/gitbook#883]
It's no convenient to move .md files after creation. I have to write the name every time instead of moving the .md to a specific folder in the 'File Tree'

Or I missed any skills? 

BTW, are there any plugin for the enhancement? 

Thanks.

**Comment by SamyPesse** [comment]
I'm not sure I really understand the problem.

Do you want the editor to update the `SUMMARY.md` when you move files ? We can add an option for this (enabled by default).
