### ISSUE TITLE
Font Awesome is missing?

### ISSUE THREAD

**Issue by phaedryx** [GitbookIO/gitbook#884]
https://github.com/GitbookIO/gitbook/blob/master/theme/stylesheets/website.less#L3

This line prevents me from compiling the less for the default theme.

**Comment by SamyPesse** [comment]
Font-Awesome is installed using bower: https://github.com/GitbookIO/gitbook/blob/master/bower.json#L11

For building the theme (js/css), you need to run the grunt command.
