### ISSUE TITLE
The Link did not work in gitbook editor 4.0

### ISSUE THREAD

**Issue by satan1999** [GitbookIO/gitbook#885]
Hi There

After i upgraded the gibbook editor to 4.0, the local link did not work any longer , for example :  [I'm a relative reference to a repository file]    (../blob/master/LICENSE)

Another issue, i noticed, the generated htmls in (_book folder) are not up to the latest md files.

Cheers
Wallace

**Comment by SamyPesse** [comment]
Links should work perfectly, are you sure the file `../blob/master/LICENSE` exists inside your repository ?

The new GitBook editor is more integrated with gitbook.com, but currently doesn't integrate the gitbook toolchain.
To build the book (output `_book`), you'll need to use the command line `gitbook` utility.
