### ISSUE TITLE
Gitbook editor: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by RobinDavid** [GitbookIO/gitbook#886]
![bug](https://cloud.githubusercontent.com/assets/1887063/9599529/d815f65e-5094-11e5-8982-b8b466f74dd3.png)

gitbook-editor-4.0.0-linux-x64 yield this error when opening a local book on a Debian machine.

Terminal output did not yield any weird message, so I was unable to spot the origin of this error, but the book does not load.

Any ideas ?

**Comment by SamyPesse** [comment]
Thank you for the feedback, can you send me a zip of the book at
samy@gitbook.com

It will help find the bug.

On Tuesday, September 1, 2015, Robin David <notifications@github.com> wrote:

> [image: bug]
> <https://cloud.githubusercontent.com/assets/1887063/9599529/d815f65e-5094-11e5-8982-b8b466f74dd3.png>
>
> gitbook-editor-4.0.0-linux-x64 yield this error when opening a local book
> on a Debian machine.
>
> Terminal output did not yield any weird message, so I was unable to spot
> the origin of this error, but the book does not load.
>
> Any ideas ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/886>.
>


-- 
Sent from Gmail Mobile

**Comment by KINGSABRI** [comment]
Hi 

Same are here, this happens when I import a previously created gitbook via the older version.

Thanks and you did great job with the newer version.

**Comment by RobinDavid** [comment]
Exception now handled in 4.0.1. Thanks a lot Samy :+1:

**Comment by SamyPesse** [comment]
You're welcome :beers: thank you for the feedback
