### ISSUE TITLE
Gitbook Desktop Editor v4.0.x review

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#887]
Hi guys

I'm using Gitbook Desktop editor 4.0.1 on Linux Mint 17.1. 
First of all, Well Done guys!/

Second, my review.
### Import
- **[FIXED]** I was facing the same #886 issue and it's gone in 4.0.1 and working fine but.
  - the good thing it handles all the links properly from the imported old book but not with new book!
- Now when I add an old book it gives me `Empty GIT Repository (please make an initial commit)` error.
  - Why do I have to initialize a repository? some books will be totally offline forever.
### Images

In my book, I've directory called "images" when I insert a new image from disk it does the following behaviors:
- It copies the image to chapter's folder (It does not use the real image path!(`../images/img.png`)
- When I replace the image(Same name different image) it keeps overwrite the new image with the older one.
-  even when I delete the image and its markdown link, it keeps adding the image to chapter's folder again and again; even I'm wondering from where gitbook gets the image again? 

I was using the old version and it was good with images path and never face any issue. I think using the image's path is much convenient instead of copying it.
#### Creating Chapters

Back to old version, when we were creating a new chapter, it was creating a new folder automatically. Now it creates a file and we have to write the path manually like **`chaptername`/chaptername.md**.
- **[FIXED]** If you would make an option in the **preferences** to allow creating new folder for new chapter.
#### Creating Articles

Older version was creating the new article under the created chapter's folder automatically which wa much better than the current state which force me to add the path of chapter's folder each time.
- **[FIXED]** If you would add an automatic detection for the chapter's folder it would be great.
- **[FIXED]** Add Chapter / Article Title automatically
#### Files, folder management
- If I create an article and it's file was created in the wrong path(ex. out of chapter folder) I move the .md file to the correct place, if I clicked on the article again it gives me pop-up to save the article file to the disk and which I select the " path corrected" file it says "The file already exist".
  - You may add an option for ability to **1. Use**,  **2. Overwrite** the existing file.
- Deleting a chapter or an article dose not delete its files, deleting it's files dose not delete the chapter/article(which is good)
  - If you would make an option to delete the file when I delete its chapter/article it would be great. 
  - Automatically update SUMMERY.md file. (issue #883 )
### `<pre>` tags

issue #842
### Cover Image
- **[FIXED]** If you would like to add an option in the tools menu to add cover page with image instead of following the documentation each time.

Thanks for accepting my initial review 

_Well done guys, again!_

**Comment by chengjun** [comment]
#Math equation

It does not work with this version.

**Comment by juaalta** [comment]
I totally agree with what is said in the review.

**Comment by znmeb** [comment]
@SamyPesse Is the new Desktop Editor going to be open source? So far all I see is .deb packages for Linux.

**Comment by SamyPesse** [comment]
@chengjun Maths had been fixed in version 4.0.2

@znmeb No, we currently don't have plan to open source the editor.

We took note of all of your feedback :) Most of it will be done for version 4.1.0.

**Comment by KINGSABRI** [comment]
Thanks for the new update. 
Cant wait to fix the image path issue :'(

**Comment by KeranChen** [comment]
please fix the image path issue:)
