### ISSUE TITLE
Invalid ID normalization (fails at epubcheck)

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#888]
The current IDs normalization done by kramed can output IDs starting with `-`.

Example:

``` md
### !global flag + variables/arguments in mixins and functions
```

will output:

```
<h3 id="-global-flag-variables-arguments-in-mixins-and-functions">!global flag + variables/arguments in mixins and functions</h3>
```

This is not accepted by epubcheck:

```
ERROR: ./book.epub/default-flag.html(184,85): value of attribute "id" is invalid; must be an XML name without colons
```

We should fix this in Kramed, but we should also consider normalizing IDs in our current HTML normalization (common for Markdown. Asciidoc, ...) to have standard IDs for whatever is the input format.

**Comment by Uko** [comment]
:+1: thanks for taking a look

**Comment by christopheradams** [comment]
I just noticed this issue, having encountered the exact same bug and asking to get it fixed in kramed: https://github.com/GitbookIO/kramed/pull/38

**Comment by christopheradams** [comment]
If anyone else is having this problem, and you can't wait for a package fix, you can try setting the heading id manually using this syntax:

```
### !global flag + variables/arguments in mixins and functions {#global-flag-variables-etc}
```
