### ISSUE TITLE
live restart after change doesn't work (v2.3.0)

### ISSUE THREAD

**Issue by brunobord** [GitbookIO/gitbook#890]
Hi,
I've installed the latest (2.3.0) version and it appears that the serve live reload doesn't work anymore.
After a downgrade to the 2.0.0 version, the live reload is working back again (I've used ``gitbook version:install`` to install the version, and modified the ``book.json`` file to specify the version).

I've tried to "bisect" it a bit and it looks like the last working version is: 2.0.1, so it seems that the live reload stops working as of v2.0.2.

Hope this helps solving the problem (if it's a bug, it might come from my setup).

**Comment by SamyPesse** [comment]
This is working for me on OS X (10.11) with Node.js (0.12.7).

**Comment by brunobord** [comment]
@SamyPesse :(
Almost the same setup here (OSX 10.10.3) and same Node.js version.

I've searched the changelog, and it looks like the [2.0.2 introduces a new watch tool](https://github.com/GitbookIO/gitbook/blob/master/CHANGES.md#202): chokidar. That might be related, then, because it's the version that stops working here.

Activating the debug mode didn't help much, when a file is changed in the directory, nothing happens and nothing is logged, nothing crashes.
What can I do to investigate a bit more?

**Comment by brunobord** [comment]
I GOT IT!

I've added a ``console.log(dir)`` in the ``watch.js`` module... And it looks like the ``book.root`` variable [passed as an argument here](https://github.com/GitbookIO/gitbook/blob/master/lib/index.js#L157) is being **lowercased**.

* my original path: ``/Users/bruno/Projets/Writings/Book``
* resulting path as ``book.root``: ``/Users/bruno/Projets/writings/book``

The weird thing: the path is not **entirely lowercased** (it starts after the ``~/Projets`` bit)

I've tested using a path like: ``/Users/bruno/Projets/book`` and it WORKED!

Have you got any idea about how this upper/lowercase mix happens in the ``book.root`` variable, and how to fix it?

**Comment by SamyPesse** [comment]
I still don't understand why this is happening, I can't reproduce the bug.

**Comment by brunobord** [comment]
That might be because my OSX filesystem has been formatted with the "case insensitive" option (not my fault, I promise, I didn't do the formatting, I was given this laptop like this)

**Comment by brunobord** [comment]
I'm closing this issue, I've tested with a more recent version (2.5.0) and the live reload works like a charm.
