### ISSUE TITLE
double scroll bar in chrome v43

### ISSUE THREAD

**Issue by y4h2** [GitbookIO/gitbook#891]
windows 8.1
chrome v 43
As figure shows, when cursor in the code tags, the browser will show double scroll on right.
![image](https://cloud.githubusercontent.com/assets/5662692/9646812/14cb7842-51a5-11e5-825b-7baa7980914a.png)

Under firefox, there is no this problem.

**Comment by therimalaya** [comment]
I am having the same problem, It is annoying.

**Comment by therimalaya** [comment]
In my case, It was the `save to pinterest` plugin that was making the problem. It is solved now.
