### ISSUE TITLE
How to logon to gitbook desktop?

### ISSUE THREAD

**Issue by zzxwill** [GitbookIO/gitbook#892]
I used github account to connect gitbook.com on the web. How can I login to the desktop edition? Thanks.

**Comment by SamyPesse** [comment]
It's not possible to login using GitHub in the editor for the moment.

You need to setup a password in your account settings (https://www.gitbook.com/settings), then you can login in the editor. You can also use your API token instead of your password.

**Comment by zzxwill** [comment]
Got it. Much appreciated.
