### ISSUE TITLE
Sometimes adoc format does not seam to work

### ISSUE THREAD

**Issue by sirinath** [GitbookIO/gitbook#895]
The following adoc text does not work. I tried even removing as much items as possible and changed them. https://www.gitbook.com/book/sirinath/notes-on-dhamma/edit#/edit/master/4-Foundations-of-Mindfulness.adoc

**Comment by SamyPesse** [comment]
Here is the output of [4-Foundations-of-Mindfulness.adoc](https://raw.githubusercontent.com/NotesOnDhamma/NotesOnDhamma.github.io/master/4-Foundations-of-Mindfulness.adoc) in the editor (version 4.0.2):

![screen shot 2015-09-06 at 20 58 13](https://cloud.githubusercontent.com/assets/845425/9706081/1ecb5ba4-54da-11e5-9e8f-a770cf8abeb9.png)

What's wrong?

**Comment by sirinath** [comment]
In the web editor everything is jumbled up.

**Comment by sirinath** [comment]
![image](https://cloud.githubusercontent.com/assets/637415/9752747/77a7e5b4-56d1-11e5-88cb-3f02c1b54857.png)

**Comment by sirinath** [comment]
It it possible to prioritise fixing this as most of what I am writing is table heavy. Others also would be using tables heavenly.
