### ISSUE TITLE
Templating {% can't be escaped

### ISSUE THREAD

**Issue by alandekok** [GitbookIO/gitbook#896]
I have documents which have `...{%...` in their contents.  The templating engine complains about the text.

If I do `...\{%...`, the templating engine stll complains.

If i do `...{\%...`, the templating engine no longer complains.  But it does *not* de-escape the characters, so my document now has an extra backslash in it.

I can work around it by using am HTML zero width character `&#8203;`, but that clutters up my source with extra stuff.

**Comment by SamyPesse** [comment]
You can use the {% raw %} tags to escape content, take a look at
http://help.gitbook.com/format/templating.html

On Thursday, September 3, 2015, Alan DeKok <notifications@github.com> wrote:

> I have documents which have ...{%... in their contents. The templating
> engine complains about the text.
>
> If I do ...\{%..., the templating engine stll complains.
>
> If i do ...{\%..., the templating engine no longer complains. But it does
> *not* de-escape the characters, so my document now has an extra backslash
> in it.
>
> I can work around it by using am HTML zero width character &#8203;, but
> that clutters up my source with extra stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/896>.
>


-- 
Sent from Gmail Mobile

**Comment by alandekok** [comment]
I know that.  The "raw" escaping affects output formatting.  Using &#8203; doesn't affect output formatting.  Fixing the escaping doesn't affect output formatting.

I guess "it's broken by design" is a response.  Not a good one, but a response.
