### ISSUE TITLE
Font for header and footer in PDF is different

### ISSUE THREAD

**Issue by kylebrowning** [GitbookIO/gitbook#899]
When generating a pdf, the header and footer font is quite different than the content of the page.

Is there any setting to set in book.json to fix this?

Ive tried 

```
    "pluginsConfig": {
        "fontSettings": {
            "theme": "white",
            "family":"sans",
            "size": 1
        }
    }
```

and 
```
    "pdf": {
        "pageNumbers": true,
        "fontSize": 12,
        "fontFamily": "sans",
        "paperSize": "a4",
        "margin": {
            "right": 62,
            "left": 62,
            "top": 36,
            "bottom": 36
        },
        "headerTemplate": "_TITLE_ | _PAGENUM_",
        "footerTemplate": "Acquia.com | 53 State Street, 10th Floor, Boston, MA 02109"
    },
```

But it still looks different 

![cursor_and_llnl-aug-2015-arch_pdf__page_1_of_41_](https://cloud.githubusercontent.com/assets/113023/9675543/d213fd4c-5273-11e5-8b59-7a9884e28be5.jpg)

**Comment by xtrasmal** [comment]
@kylebrowning

May I ask where you found all the settings that can be used for the pdf.css?
