### ISSUE TITLE
Prevent multiple summary entries from having the same filename

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#900]
Currently, it's possible to have multiple summary entries with the same path:

```md
# Summary

- [Test 1](test.md)
- [Test 2](test.md)
```

This should be parsed like there is only one entry.

**Comment by AaronO** [comment]
Should it parse as one or crash or simply display a warning ? Should we prevent doing this in the editor on our side ?

**Comment by SamyPesse** [comment]
It should just simply display one (see previous message), since it'll be handled in the `gitbook-parsers`, this will also be prevented in the editor.

**Comment by nagim** [comment]
Is there a way to override this somehow?

Thanks,
Imre
