### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by wcandillon** [GitbookIO/gitbook#902]
Using [linguist](https://github.com/github/linguist) instead of `highlight.js` would enable gitbook syntax highlighting to be in sync with github

**Comment by SamyPesse** [comment]
Linguist is a ruby package, using it instead of highlight.js will make installation of GitBook much harder.

But you can easily build a package that will use `linguist` to re-highlight code blocks (you can use the hook `page` to run linguist on all `$(code').text()`).

**Comment by AaronO** [comment]
@wcandillon Also, linguist isn't used for syntax highlighting so it's not a replacement for `highlight.js`, linguist's only job is to detect and classify code files to a specific language. (So you could use it to automatically detect which highlighting to use, `highlight.js` already does part of that, but then once again it wouldn't replace `highlight.js`).

**Comment by wcandillon** [comment]
@SamyPesse @AaronO maybe I pointed to the wrong package, github now provides a package to do static syntax highlighting of all these grammars. I think this is related to the atom project.
