### ISSUE TITLE
Glossary items consisting of markdown only are not rendered

### ISSUE THREAD

**Issue by emilbayes** [GitbookIO/gitbook#903]
Of the following glossary:

``` markdown
# Nonlinear dynamics

Small changes in input yield disproportionate changes in output, eg $$y = x^2$$

# Map

* Time: Discrete
* Model: Difference equation

# Flow

* Time: Continous
* Model: Differential equation

# Difference equation

$$
x_{n+1} = f(x_n)
$$

# Differential equation

$$
\frac{df(x)}{dx} = f(x)
$$
```

`Flow` and `Map` are not rendered, as (I presume) they're deemed empty.

**Comment by xtrasmal** [comment]
I have a problem that may be similar. It seems like:

- Links are shown as the markdown used for links --> ```[title](link)```, instead of [title](link)
- Same goes for bold text, which is shown as --> ```***bold***```, instead of ***bold***

**Comment by torsday** [comment]
+1

**Comment by noerw** [comment]
see https://github.com/GitbookIO/gitbook/issues/729
still no fix available?
