### ISSUE TITLE
Support to display line number in a code block

### ISSUE THREAD

**Issue by hawkchen** [GitbookIO/gitbook#905]
When authors explain a code snippet, line number can help them precisely link their explanation to a specific code. Therefore, this can improve readers' understanding. Hope that a code block can have line number on it.

**Comment by dkotrada** [comment]
Same here I need it

**Comment by hackingbeauty** [comment]
+1

**Comment by starwavelin** [comment]
+1

**Comment by AaronO** [comment]
@hawkchen In the new release, all code blocks with 2 lines or more have line numbers (see screenshot)

![image](https://user-images.githubusercontent.com/949223/30924326-6e566d60-a37c-11e7-9892-b746ad62cec7.png)
