### ISSUE TITLE
gitbook.com - Not able to restart build

### ISSUE THREAD

**Issue by Vdragon** [GitbookIO/gitbook#911]
I tried to restart the failed builds of issue #910 by clicking the "Restart this build" button but the build result isn't changing at all.

**Comment by SamyPesse** [comment]
What is your build url?

**Comment by Vdragon** [comment]
@SamyPesse 
https://www.gitbook.com/book/vdragon/hello_git_world_/build/55ef25dff08e600f00529b72

**Comment by SamyPesse** [comment]
Your last build worked fine: https://www.gitbook.com/book/vdragon/hello_git_world_/build/55efe45969713910008447cd

So rebuilding a previous build is not needed.
