### ISSUE TITLE
Segmentation fault when 'gitbook serve' using node js 4.0

### ISSUE THREAD

**Issue by linesh-simplicity** [GitbookIO/gitbook#913]
Hi guys, I'm updating node js to version 4.0 yesterday, and when i run actually any gitbook-related command it just showed me a 'segmentation fault'. Not sure if it's because the upgraded node js version, does anyone get a clue of what's going on and how can I fix it?

__Here's my environment:__
gitbook-cli version:   0.3.6
node js version:       4.0.0
npm version:            2.14.2 
mac osx version:     10.10.4

Approaches like `npm uninstall gitbook-cli -g` and `npm install gitbook-cli -g`  `npm rebuild` again have been tried but not seem to work out.

**Comment by SamyPesse** [comment]
Like I said in https://github.com/GitbookIO/gitbook-cli/issues/12 I don't have this issue on my OS X.

Can you try cloning the `GitbookIO/gitbook` and run the unit tests:

```
$ npm i
$ npm test
```

I want to determine if the issue come from `gitbook-cli` or `gitbook`.

**Comment by linesh-simplicity** [comment]
Yeap do as you said, unit tests of `gitbook` are all passing.

**Comment by linesh-simplicity** [comment]
Issue is solved but I don't know how. Now my versions for these apps are:

gitbook-cli version:   0.3.6
node js version:       4.3.1
npm version:            3.7.3 
mac osx version:     10.11.3
