### ISSUE TITLE
The new desktop (offline) editor

### ISSUE THREAD

**Issue by hackhowtofaq** [GitbookIO/gitbook#916]
It is supposed to be an offline editor, but it asks to login first before opening my book.

Any clues?

Ty

**Comment by SamyPesse** [comment]
You need to authenticate once, this authentication is used to clone remote books from GitBook.com and to authenticate commit from the editor.
Once you're authenticate, you can edit your books offline.

**Comment by hackhowtofaq** [comment]
I think that this should be optional, since if you don't have an account and/or remote books you need internet access and one more account with no use.


Ty
