### ISSUE TITLE
Failed to connect to worker when trying to edit README.md

### ISSUE THREAD

**Issue by naturalprogrammer** [GitbookIO/gitbook#917]
In a GitBook, I'm able to edit all the pages except README.md. When clicking on README.md on the GitBook editor, the message "Failed to connect to worker" is shown on the editor panel. Here is the editor:

https://www.gitbook.com/book/naturalprogrammer/spring-lemon-getting-started/edit#/edit/develop/README.md

**Comment by SamyPesse** [comment]
What browser are you using ? (What version and which OS ?)

**Comment by naturalprogrammer** [comment]
Now it's working.

I'm using Chrome latest version on Windows 8.1.
