### ISSUE TITLE
Make code highlighter configurable

### ISSUE THREAD

**Issue by gaearon** [GitbookIO/gitbook#918]
Currently highlight.js is used, but I don't quite like the way it highlights JS, and in addition, it has multiple problems with JSX. I would much rather use [Prism](http://prismjs.com).

It does not appear that this is configurable. (I don't want to create a plugin with a custom tag because that would break vanilla doc display on the Github repo.)

How would I go about switching to Prism? For now, I'll probably fork, but it would be nice to allow this to be configurable.

**Comment by SamyPesse** [comment]
### Current solution:

You can create a plugin that search for `pre > code` in the page and apply Prism to replace inner html:

```js
var cheerio = require('cheerio');

module.exports = {
    hooks: {
        'page': function(page) {
              var $ = cheerio.load(page.content);

              $('code').each(function() {
                  var text = $(this).text();
                  $(this).html(prism(text));
              });

              page.content = $.html();
              return page;
        }
    }
};
```

(this code is just an example).

### Future solution

GitBook will use a `code` block (default being using highlight.js), since plugins can extend `blocks`, we'll just need to re-define this block.

```js
module.exports = {
    blocks: {
         'code': function(text) {
                return prims(text);
         }
    }
};

```

**Comment by gaearon** [comment]
Thanks! I think I'll keep a fork for now because I want to do this on server side (just like Highlight.js is currently used), but I'll keep an eye on this issue.

**Comment by SamyPesse** [comment]
This is only server side, there is no client side code here.

**Comment by gaearon** [comment]
Wow, I didn't know about cheerio, thanks.

**Comment by SamyPesse** [comment]
The current solution is not perfect for performance (it requires re-parsing HTML during `gitbook build`), but it works perfectly.

The new solution will be released next week. You can start a `gitbook-plugin-prism` repository using the current solution and update it once the version `2.4.0` has been released.
I believe this is a better solution that maintaining a fork

**Comment by gaearon** [comment]
One more question: where would I put injecting Prism's CSS file?

**Comment by SamyPesse** [comment]
Take a look at this plugin (this one is only client-side): https://github.com/spricity/google_code_prettify/blob/master/index.js

You need to add to the sample plugin that I give you in previous comments:

```js
book: {
        assets: "./book",
        css: [
            "prism.css"
        ]
    },
```

**Comment by gaearon** [comment]
Got it. Thanks :+1:

**Comment by gaearon** [comment]
I just published https://github.com/gaearon/gitbook-plugin-prism!

**Comment by gaearon** [comment]
Also, for a long term solution, there needs to be a way to remove highlight.js styles as I don't need them anymore. Could the "default" highlighting could be a plugin which I could blacklist? Is this the plan?

**Comment by SamyPesse** [comment]
Yes I totally agree, that's the plan :)

**Comment by gaearon** [comment]
One more tiny question. Is there a good way to use an NPM dependency's assets? I want my plugin to use `node_modules/prismjs/themes/prism.css` instead of copy-pasting it. Currently my plugin config looks like this:

```js
book: {
  assets: './node_modules/prismjs/themes',
  css: [
    'prism.css'
  ]
},
```

That doesn't work with NPM 3 because it flattens dependencies, and `prismjs` it installed outside the plugin's folder. Ideally I'd want to have `assets` be resolved using Node resolution mechanism so that `assets: 'prismjs/themes'` just works (currently it doesn't). What do you think?

**Comment by SamyPesse** [comment]
I think you can use `require.resolve` (https://nodejs.org/api/globals.html#globals_require_resolve) to resolve the path to `prism`.

**Comment by gaearon** [comment]
Awesome, I forgot it's Just Code. :-)
https://github.com/gaearon/gitbook-plugin-prism/commit/903456c8c2203d3b86aab36fc70edb0780cf85f1
