### ISSUE TITLE
Navigating to anchor by hash doesn't set correct scroll position

### ISSUE THREAD

**Issue by gaearon** [GitbookIO/gitbook#920]
See here:

![](http://g.recordit.co/4Wc3ALWEuc.gif)

---

When I navigate to http://rackt.github.io/redux/docs/introduction/PriorArt.html#rx **with a clean browser cache** (or when I shift+cmd+R it), the scroll doesn't jump to the anchor.

There is a flash of unstyled content (no sidebar).

My theory is that when the sidebar appears, it changes the layout, and the position restored by browser from anchor link gets lost. The flash of unstyled content is frustrating on its own, too.

I'm not sure where to look yet but I'll try to debug it a little.

**Comment by gaearon** [comment]
It appears that the problem is due to toggling `with-summary` [here](https://github.com/GitbookIO/gitbook/blob/3bf592f870eb24d1b4753fa538bad2cbfaa98a24/theme/javascript/core/sidebar.js#L14). Because it only executes after JS is loaded, this unfortunate flash happens.

I guess it would be nice if, by default, the styles look at a media query (are we on mobile?), and `with-summary` would override it. This way in most cases the outcome on the first load would be correct. Another option is to inline some JS crucial to rendering into the page.

**Comment by sifue** [comment]
I prepared a plugin for this problem.
https://www.npmjs.com/package/gitbook-plugin-anker-enable
