### ISSUE TITLE
Github authentication support in GitBook for Desktop

### ISSUE THREAD

**Issue by hantsy** [GitbookIO/gitbook#921]
I found the newest GitBook for Desktop does not support Github.com account to login, or I missed something?

**Comment by Tr4pSt3R** [comment]
@hantsy try it again with Gitbook(-v 4.1.2). I was able to login successfully after recovering my password. Use the "forgotten password" feature.

**Comment by SamyPesse** [comment]
Fixed in the version 5.0.0 (https://www.gitbook.com/blog/releases/editor-5-beta)

**Comment by KINGSABRI** [comment]
I would take the risk and use the beta version because I love you, gitbook
