### ISSUE TITLE
A bug about link markdown

### ISSUE THREAD

**Issue by plantain-00** [GitbookIO/gitbook#923]
I have:

```
[/api/books](/api/books)
```

and I expect 

```
<a href='/api/books'>/api/books</a>
```

but the html file that it produces is:

```
<a href='api/books'>/api/books</a>
```

or is there other way to meet my expectation?

**Comment by bbatsche** [comment]
I'm having the exact same issue. It seems absolute paths are being converted to relative paths. My Markdown:

```markdown
[css_selectors.php](/content/examples/css/css_selectors.php)
```

My expected result:

```html
<a href="/content/examples/css/css_selectors.php">css_selectors.php</a>
```

Actual output:

```html
<a href="content/examples/css/css_selectors.php">css_selectors.php</a>
```

**Comment by timaschew** [comment]
This is fixed in my fork: https://github.com/timaschew/gitbook
