### ISSUE TITLE
occasional python code block missed

### ISSUE THREAD

**Issue by DaveBackus** [GitbookIO/gitbook#925]
This is a one-off, but it's puzzling to me.  I have lots of code blocks, but here's one that refuses to format:  

http://davebackus.gitbooks.io/test/content/installing-python.html

Scroll down to "Run test programs" and note the code block that's printed verbatim (ie, not formatted) in the second bullet.  Even more puzzling, the GitHub md viewer renders it fine:  

http://davebackus.gitbooks.io/test/content/installing-python.html

Any suggestions?  It doesn't happen often, but when it does I'm stumped.  I can avoide it by adding a space before, but then it's not indented to align with the bulleted text,

**Comment by AaronO** [comment]
@DaveBackus Looking at your markdown source, you need to insert a newline before that code block starts.

I tried that locally and it fixes your issue. In general, non-inline code blocks should be preceded by an empty line.

**Comment by DaveBackus** [comment]
Thanks for the fast response.  Yes, I know that "works," but it generates
other problems/questions:

* It messes up the indentation -- should be indented like the bullets.

* It doesn't explain the many examples of code blocks that aren't preceded
by spaces, yet work fine.  Also why the GitHub viewer handles it correctly
and GitBook does not.  Does the latter have problems with code blocks in
bulleted lists?
