### ISSUE TITLE
language code: suggest use zh-hans not zh-cn

### ISSUE THREAD

**Issue by sinkcup** [GitbookIO/gitbook#926]
I use "zh-hans" in `LANGS.md`, but there is warning:

```
warn: Language 'ja' is not available as a layout locales (en, ar, bn, de, en, es, fa, fi, fr, he, it, jp, ko, no, pl, pt, ro, ru, vi, zh-cn, zh-tw)
```

language has nothing to do with locale. it's better to use "ja" not "jp", "zh-hans" not "zh-cn".

docs:

https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

**Comment by tkawachi** [comment]
:+1:
"jp" means a country Japan, and "ja" means a language Japanese.

**Comment by howiehu** [comment]
after these change, zh-hans cannot show chinese words in search & font view.

@SamyPesse

**Comment by SamyPesse** [comment]
@howiehu this is because `search` and `fontsettings` are external plugins. There isn't i18n for plugins, but we might add it.
