### ISSUE TITLE
ignore folder in .bookignore but not .gitignore

### ISSUE THREAD

**Issue by uliska** [GitbookIO/gitbook#931]
I have a Gitbook where I want to track a custom node_module with Git (because it's developed within this book) but don't copy to the build directory.

```
.gitignore:
node_modules
!node_modules/my-custom-plugin

.bookignore:
node_modules/my-custom-plugin
```

`gitbook build` will now ignore the other node modules (those installed regularly) but will still copy over `my-custom-plugin`.

I think it is a good idea to automatically respect entries from `.gitignore`, but I think `.bookignore` should be processed later and should be able to override settings from `.gitignore`.

**Comment by juzerali** [comment]
:+1: Another use case is that we only want to commit the source code and allow deployment to generate the gitbook. Thus we don't want to commit the `_book` folder. Adding `_book` folder to `.gitignore` will result in no pages being shown in the book. Therefore it is best to leave `.gitignore` alone for repository management concerns only.

**Comment by timpulver** [comment]
Is there a way now to have different ignores for gitbook and git?
I am generating docs based on markdown-files which I copy to the gitbook-directory, these should be included in the book but should not be checked in to Github.

**Comment by travis** [comment]
any word on this? I'd like to use a dynamically generated `SUMMARY.md`, so want it to be ignored by git but do not want it ignored by `gitbook build`

**Comment by AaronO** [comment]
@travis Could you elaborate a little more on your use case ? It's interesting that you're dynamically generating your `SUMMARY.md`.

We should in theory support `.bookignore` (see [lib/constants/ignoreFiles.js](https://github.com/GitbookIO/gitbook/blob/b9fa6c3051f9faa46fb65a04c22b05ba68c23452/lib/constants/ignoreFiles.js)).

BTW, GitBook v4 is currently being worked on (see `dream` branch), we just pushed our new editor and `gitbook.com` releases out, so now would be a perfect time to get some feedback in for the v4 release.

**Comment by travis** [comment]
I'm putting together a book of words we use at work (inspired by http://blog.carbonfive.com/2016/10/04/ubiquitous-language-the-joy-of-naming/) and we'd like to have have a page-per-word so we can attach metadata to them. I'd like to avoid manually editing `SUMMARY.md` when we add a new page, so I'm using https://www.npmjs.com/package/gitbook-summary to generate the summary file before I `gitbook build`. Let me know if I can clarify more!

**Comment by timpulver** [comment]
I’m doing it as @travis – generating a dynamic SUMMARY.md, which I would like to gitignore.

**Comment by timpulver** [comment]
Any news on this? It would be really handy if we could:

- defined files / folders to be ignored in `.bookignore`
- optionally ignore files / folders in `.gitignore` (I would disable this for my use-case

**Comment by timpulver** [comment]
Is there any way to make gitbook _not_ ignore entries from .gitignore?
I don’t want to check in certain files but still be able to use them in my gitbook.

Any workarounds?

**Comment by tbouron** [comment]
I would love to have this option too. Here is my use-case @AaronO:

I'm generating a big documentation which is the aggregation of multiple project's markdown file. I build this by:
- having a git submodule per project's doc
- create my own folder structure based on all the markdown files, under a folder call `stage`
- having a custom `SUMMARY.md` pointing to the right pages

I want to build this with Gitbook but don't want to check-in the file from the "dependencies" therefore I added my `stage` folder to `.gitignore`... which prevent gitbook from generating my doc. Having an option to disable this would be awesome.

**Comment by ark3** [comment]
We use GitBook for the documentation website for [Telepresence](https://github.com/telepresenceio/telepresence). Our workaround for this issue is to use the top-level `.gitignore` file for Git stuff and keep all the GitBook stuff in a subdirectory (`docs`). We run GitBook from that subdirectory, and it doesn't look at the top-level `.gitignore` but _does_ look at `docs/.gitignore` and `docs/.bookignore`.
