### ISSUE TITLE
Book not getting built

### ISSUE THREAD

**Issue by naturalprogrammer** [GitbookIO/gitbook#932]
My book https://naturalprogrammer.gitbooks.io/spring-lemon-getting-started/content/ is not getting built, even if I have updated the master branch a few days back.

**Comment by AaronO** [comment]
Hi SanJay, your builds did go through on your `develop` branch: https://www.gitbook.com/book/naturalprogrammer/spring-lemon-getting-started/activity?branch=develop

We don't trigger a build after merging two branches (we'll fix that). So if you make a small change in your master and save, that should trigger a new build and everything should work as expected.

Can you give that a try and let me know if it works ? Thanks !

**Comment by naturalprogrammer** [comment]
Yes, doing a little change to the master branch did the trick. Thanks!

I'm not getting confirmation mails nowadays, though, which I was getting a few days back, as I remember.

**Comment by SamyPesse** [comment]
What confirmation mails ? You should receive emails about builds only when it fails or succeed after a failed one.

**Comment by naturalprogrammer** [comment]
Oh, I see. I was getting those mails that time, then. Thanks!
