### ISSUE TITLE
Edit file is broken

### ISSUE THREAD

**Issue by cesards** [GitbookIO/gitbook#933]
Editing a file is not intuitive and I think it's broken. I follow next steps:

1. I create a new article
<img width="1179" alt="screen shot 2015-09-16 at 11 05 36" src="https://cloud.githubusercontent.com/assets/1536079/9911354/0a75d7f4-5ca2-11e5-972a-a97a0825ebfe.png">
<img width="292" alt="screen shot 2015-09-16 at 11 05 45" src="https://cloud.githubusercontent.com/assets/1536079/9911362/16f74fda-5ca2-11e5-9fdc-ba19350462cc.png">

2. Every time I create a new article, I need to create the appropiate file in order to write something.
<img width="1180" alt="screen shot 2015-09-16 at 11 05 58" src="https://cloud.githubusercontent.com/assets/1536079/9911397/3801ca02-5ca2-11e5-831d-2e6822e00cc4.png">

3. I want to edit the file, so I click "Edit" on the file
<img width="1214" alt="screen shot 2015-09-16 at 11 06 09" src="https://cloud.githubusercontent.com/assets/1536079/9911415/4d5e57e4-5ca2-11e5-95da-b06d85439f35.png">

    (I'm gonna name it "Test 2" and I will change the file name two)
<img width="1193" alt="screen shot 2015-09-16 at 11 06 23" src="https://cloud.githubusercontent.com/assets/1536079/9911432/612d9ec4-5ca2-11e5-9d70-f5990945b924.png">

4. Boom. I can't access the new file
<img width="1186" alt="screen shot 2015-09-16 at 11 07 01" src="https://cloud.githubusercontent.com/assets/1536079/9911485/a665294e-5ca2-11e5-952f-1efdb5155bc3.png">

**Comment by SamyPesse** [comment]
The `Edit` means editing the summary entry itself; once you created the file (step 2), you juste need to click on the summary entry and it'll open the associated file.

I'll improve this workflow, we already have some improvements coming for this.
