### ISSUE TITLE
Need update documentation about "gitbook version specified in your book.json might be too strict for future patches" warning

### ISSUE THREAD

**Issue by Vdragon** [GitbookIO/gitbook#939]
I've tried `2.x.x`, `=2.x.x`, `==2.x.x` but none seems to be working, please update `help.gitbook.com` about how to properly specify the version.

**Comment by SamyPesse** [comment]
Which version of gitbook are you using ?

**Comment by Vdragon** [comment]
@SamyPesse 2.4.1

**Comment by SamyPesse** [comment]
`2.x.x` works fine for me, can you your `book.json` and tell me which version of Node.js you are using ?

**Comment by Vdragon** [comment]
repo: https://github.com/Vdragon/Generic_GitBook_Template
`book.json`: https://github.com/Vdragon/Generic_GitBook_Template/blob/06bd2928dda6b1ad24a38265ddde6ca7ff15d014/book.json
build on GitBook.com: https://www.gitbook.com/book/vdragon/generic_gitbook_template/build/55fefd2440165c1000940e3d
Node.js in local system: 0.10.25

**Comment by SamyPesse** [comment]
Ok i've found the problem, it doesn't come from your main `book.json`, but from the "virtual" book.json associated with every languages in your book.

I'm going to fix this, you can just ignore the warning (`2.x.x` is a good value).
