### ISSUE TITLE
Error loading GitHub repos: No authenticated user

### ISSUE THREAD

**Issue by emilbayes** [GitbookIO/gitbook#940]
I can't seem to create a new Gitbook from a Github repo. I'm authenticated using Github, have tried reconnecting my Github account "With access to public repos" and also checked my "Applications" tab here on Github.

I keep getting the same error tough:

> Error loading GitHub repos: No authenticated user

**Comment by SamyPesse** [comment]
What is your GitBook username ?

**Comment by emilbayes** [comment]
Same as here, emilbayes

**Comment by SamyPesse** [comment]
I've found the bug, it'll be fixed in the next release (not related to you).

**Comment by SamyPesse** [comment]
I'll push a fix in a few hours (max).

**Comment by emilbayes** [comment]
Great, thanks :)

**Comment by SamyPesse** [comment]
The fix is live in production :rocket:
