### ISSUE TITLE
Add more than one custom style

### ISSUE THREAD

**Issue by coderDem** [GitbookIO/gitbook#946]
Hello,

I would like to add more than one style-file to my gitbook.
Here my code:

<code>
    "styles": {
        "bootstrap": "styles/bootstrap.css",
        "website": "styles/style.css",
        "font": "styles/font-awesome.css",
        "demo": "styles/iconmoon/demo.css"
    }
</code>

Only style.css added to the gitbook. I tried the type pdf or mobi but this had no effect.

Best regards

**Comment by coderDem** [comment]
Ok now I concat all styling files and add the files with:

<code>
 "styles": {  "website": "styles/main.css" }
</code>

**Comment by SamyPesse** [comment]
We can support a list of css files: `"styles": { "website": [ "styles/font-awesome.css", "styles/main.css" ] } `

But right now, the only solution is to concat css.
