### ISSUE TITLE
Anchors not working in deeplinks from other pages

### ISSUE THREAD

**Issue by dothebart** [GitbookIO/gitbook#953]
We render chapters with several subheads with anchors attached to them:

```
<p><a name="fulltext_index:"></a></p>
```

in
https://docs.arangodb.com/HttpIndexes/index.html
If I edit the location bar and add the anchor:
https://docs.arangodb.com/HttpIndexes/index.html#fulltext_index:
the page is scrolled to that sub-heading.
If however, I use the same URL by pasting it into a new window (or following a link from another chapter) one can see on slow computers that the page is scrolled to the top by javascript.

http://developer.gitbook.com/plugins/filters.html#defining-a-new-filter

also reproduces this behaviour.

**Comment by panicbit** [comment]
I'm experiencing the same issue. :bulb:

**Comment by dothebart** [comment]
it seems to be fixed if you click on the dev.gitbook page...

**Comment by panicbit** [comment]
Oh yeah, it is indeed fixed! I didn't realise that I needed to `gitbook versions:update`.
