### ISSUE TITLE
Syntax Highlight disabled 

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#961]
Hi 
I'm using the desktop version 4.1.2
I was trying some gitbook plugins on a test book I've created then suddenly, all code syntax highlight has been gone for all languages(ex. bash, ruby ) from all existing books. 

Note: 
- the syntax highlight is working fine on the published gitbook 
- the testbook plugins are not all installed on the other books 
- Other books have `expandable-chapter` and `anchor` plugins only

**Comment by KINGSABRI** [comment]
Issue has been fixed in version 4.1.3

Thanks guys

**Comment by SamyPesse** [comment]
You're welcome :sparkles:
