### ISSUE TITLE
Problem In Update your book using GIT

### ISSUE THREAD

**Issue by JeremiahZhang** [GitbookIO/gitbook#962]
I created mynew book on gitbook.com, and then you need to push some content in my PC to it. 
I went through the Method in [Update your book using GIT](http://help.gitbook.com/build/push.html). But it failed.

So I found this issue [I can't push to gitbook master](https://github.com/GitbookIO/gitbook/issues/660). 

But I also  got following errors: 
[rejected] master -> master (fetch first)

I'm also using this Github account for integration.

thanks

        git remote add gitbook https://username:apitoken@git.gitbook.com/jeremiahzhan/gitbookguide.git
        git push -u gitbook master
        errors failed to push some refs to https://username:apitoken@git.gitbook.com/jeremiahzhang/gitbookguide.git
        hint: Updates were rejected because the remote contains work that you do
        hint: not have locally. This is usually caused by another repository pushing
        hint: to the same ref. You may want to first integrate the remote changes
        hint: (e.g., 'git pull ...') before pushing again.
        hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by JeremiahZhang** [comment]
OK I git pull the https://username:apitoken@git.gitbook.com/jeremiahzhan/gitbookguide.git,

**Comment by anxiaoyi** [comment]
@JeremiahZhang Where is the API token ? How can I generate it ?

**Comment by darth-veitcher** [comment]
@anxiaoyi and anyone else interested I've created a gist showing how I [publish from gitbook to github](https://gist.github.com/darth-veitcher/e5eb5a12b23bf2b82c6112283c722097)
