### ISSUE TITLE
Change font family

### ISSUE THREAD

**Issue by iamchathu** [GitbookIO/gitbook#966]
Hi,

I would like to know how to customize gitbook.I want to use different font family which support my locale.

**Comment by TakahiRoyte** [comment]
read help below

https://help.gitbook.com/styling/book.html
https://help.gitbook.com/format/configuration.html

**Comment by urbanhop** [comment]
The links above explain well how one can insert additional css styles. But they do not explain how to change the styles that are built into gitbook:

For example I would like to change the background color (I guess that similar to the question here). I only got it working this way.

    .book-body {	
	background: red !important;
    }

I am surprised that my custom styles have lower precedence than the built in style rules, thus requiring the !important attribute.

thx for more clarification on styling.

**Comment by iamchathu** [comment]
Great will go through this. Thank you

**Comment by sjkordis** [comment]
The links above don't work anymore. Where do these docs live now?
Thanks!

**Comment by nagim** [comment]
Try http://toolchain.gitbook.com/.
