### ISSUE TITLE
Highlight search results in page

### ISSUE THREAD

**Issue by Nasicus** [GitbookIO/gitbook#967]
Is it currently possible (using the newest gitbook version) to highlight words on the page which were typed in the search box? Currently when I type something in the search box only the pages which contain the results are displayed and when you click on them you are redirected to this page, however on the page itself nothing is highlighted.  In my opinion it would be very nice if the found results on the page would be highlighted. (Same functionality as PDF readers or all browsers have)

Does something like this currently exist? If not what do you think about implementing it?

**Comment by kramer8** [comment]
@Nasicus it may not be topical now, but there is a plugin that does this:
https://github.com/gitbook-plugins/gitbook-plugin-search-pro
https://www.npmjs.com/package/gitbook-plugin-search-pro
