### ISSUE TITLE
Glossary should allow alternate terms

### ISSUE THREAD

**Issue by mstade** [GitbookIO/gitbook#969]
Often times, variations of a word or phrase mean the same thing, and so should ideally be the same glossary entry. Here's an example, and proposed change to the glossary feature:

``` markdown
# Function composition
## Composable function

Function composition is ...
```

A regular markdown renderer would produce this, which I think is perfectly acceptable:
# Function composition
## Composable function

Function composition is ...

---

Gitbook however, could be a bit smarter and recognize the (immediate) subheadings to produce something a bit nicer, perhaps something like the following:
# Function composition

_(Also: composable function)_

Function composition is ...

---

Most importantly, this would provide a way to refer different phrases to the same glossary entry.

**Comment by torsday** [comment]
Man, this would be sweet
