### ISSUE TITLE
meta-data missing in PDF generation

### ISSUE THREAD

**Issue by adulau** [GitbookIO/gitbook#970]
It seems that there is no meta-data (author or description) populated when generating a PDF document.

**Comment by AaronO** [comment]
@adulau Author is definitely added, as long as GitBook knows who the author is.

If you generate a book on [GitBook.com](https://www.gitbook.com) the PDF contains your profile's name as the author's name.

You can also specify this in your `book.json`, for example:

```json
{
    "author": "James Smith",
    "description": "Bla blabla"
}
```

**Comment by adulau** [comment]
Thank you for the feedback. I wrongly assumed that the autocover variables were used for the generation but the metadata were the ones at the root of book.json.
