### ISSUE TITLE
warn: search index is too big

### ISSUE THREAD

**Issue by lesserwhirls** [GitbookIO/gitbook#971]
When trying to generate a gitbook, I get the following message:

```bash
$ gitbook build
info: loading book configuration....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: >> 1 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 
warn: search index is too big, indexing is now disabled
```

Is there a way to increase the allowed size of the search index, or another way around the size issue?

Thanks!

**Comment by SamyPesse** [comment]
Yes, add to your `book.json`:

```
{
    "search": {
        "maxIndexSize": 1000000000
    }
}
```

**Comment by lesserwhirls** [comment]
Thanks @SamyPesse! However, I cannot seem to overcome the limit, even with

"maxIndexSize": 10000000000000000000

Is there a hard upper limit?

Thanks!

**Comment by erlend-sh** [comment]
My site successfully builds and as far as I can tell the search works fine, but even after adding `"maxIndexSize": 100000000` I still get the error:

> warn: search index is too big, indexing is now disabled

**Comment by velneo** [comment]
Hi,

I tried to add this clausule in book.json file but it returns an error when I try to save it.

What's wrong?

Thanks,

Rafa C.

**Comment by nagim** [comment]
@velneo If you're using GitBook v3, then you need to add this:

```
{
    "lunr": {
        "maxIndexSize": 1000000000
    }
}
```

**Comment by velneo** [comment]
Got it!

Thanks a lot @nagim!
