### ISSUE TITLE
Emacs Org mode support

### ISSUE THREAD

**Issue by tharpa** [GitbookIO/gitbook#972]
Please add the Emacs Org mode support as an alternative to Markdown.

**Comment by wahn** [comment]
+1

**Comment by ColorFuzzy** [comment]
+1

**Comment by freeduck** [comment]
+1

**Comment by StoneJiaJia** [comment]
+1

**Comment by skyjia** [comment]
+1

**Comment by liaowang11** [comment]
+1

**Comment by zealinux** [comment]
+1

**Comment by zarcen** [comment]
+1

**Comment by scastillo** [comment]
+1

**Comment by sarcilav** [comment]
+1

**Comment by tninja** [comment]
+1

**Comment by lotuc** [comment]
+1

**Comment by fbob** [comment]
+1

**Comment by hanzejl** [comment]
+1

**Comment by markhuyong** [comment]
+1

**Comment by gongzhitaao** [comment]
Probably an alternative or more easier way (IMO) is to customize an org exporter based on ox-md

**Comment by guoxiangyang** [comment]
+1

**Comment by xcaptain** [comment]
+1

**Comment by nothingthere** [comment]
+1

**Comment by lianghuiyuan** [comment]
+1

**Comment by 0x4ec7** [comment]
+1

**Comment by takaxp** [comment]
+100

**Comment by Soreine** [comment]
Supporting different syntaxes in GitBook is a difficult topic, since it is resource demanding. We would be interested in understanding why you would use the Org mode syntax over Markdown? This is a general question, that also applies to Asciidoc. But in the case of Org mode, I wonder if the main advantage would be the ease of editing within Emacs (Emacs users 🤘), or if it would be the features of Org mode ?
If converting is enough, as @gongzhitaao suggested, why would one want to use the Org syntax in the first place ? Would a better `markdown-mode` suffice ? Or even a "gitbook-mode" ?

**Comment by nagim** [comment]
I don't know about Emacs Org, but in case of AsciiDoc, it's features.
Two examples are tables and lists, but there's also applying custom CSS classes to the text.

In Markdown for example, you cannot add a list inside a table cell in Markdown, only in HTML.
Also merging cells is not possible, AFAIK.

In lists, I saw a lot of issues with keeping, for example, step list continuation, when you would like to indent a table after a list item, then write the next list item. It's just simpler and more reliable in AsciiDoc.

It's discussed and explained further [here](https://github.com/awestruct/web-editor/issues/12#issuecomment-19943154) and [here](http://asciidoctor.org/docs/user-manual/#compared-to-markdown).

**Comment by akovari** [comment]
+1

**Comment by cnglen** [comment]
+1!

**Comment by rongyi** [comment]
+1

**Comment by lvii** [comment]
+1

**Comment by techmaniack** [comment]
+1

**Comment by chasinglogic** [comment]
@Soreine Another reason for org mode: Org Babel I'm currently writing a python book and using gitbook to host it, it'd be SUPER NICE to not have to export the org to markdown when I want to upload. The reason I'm writing it in org mode is I can test my source blocks using Org babel and even generate full source code files using Org Tangle which is nice to have with the book.

**Comment by idhyt** [comment]
+10086

**Comment by swdevbali** [comment]
I haven't test it with MarkDown, but the main reasoning to use Org-Mode the way I can structure / navigate the book in collapsible manner: heading 1, 2, 3.. etc.

**Comment by ofenerci** [comment]
+1

**Comment by tninja** [comment]
+1s

**Comment by chuan-su** [comment]
+1

**Comment by 0xFORDCOMMA** [comment]
+1

**Comment by yydai** [comment]
+1

**Comment by ageekymonk** [comment]
+1

**Comment by TedwardErker** [comment]
+1

**Comment by DiogoFerrari** [comment]
+1

**Comment by csantosb** [comment]
+1

**Comment by mastropiero90** [comment]
+1

**Comment by wahn** [comment]
Because org mode can be used for [literate programming](https://en.wikipedia.org/wiki/Literate_programming) as described here:

https://youtu.be/dljNabciEGg

**Comment by LostCogs** [comment]
+1 emacs is where I live.

**Comment by ye-lin-aung** [comment]
+1
