### ISSUE TITLE
failed to download external image when parameter of the url to the image contains special character

### ISSUE THREAD

**Issue by argszero** [GitbookIO/gitbook#974]
i.e the 02.08.md like:
```
![equation](http://latex.codecogs.com/gif.latex?{n^3=n^{\log_28}})
```

Error: Fail downloading http://latex.codecogs.com/gif.latex?{n^3=n^{\log_28}}: ENOENT, open '/tmp/tmp-16249bn95vio/1092b88c.latex?{n^3=n^{/log_28}}' (In file '02.08.md')

**Comment by argszero** [comment]
this is because the dest file name "/tmp/tmp-16249bn95vio/1092b88c.latex?{n^3=n^{/log_28}}" is not a legal file name.

this can be fixed by convert the dest file to be a legal file name, for example:
```
--- a/lib/utils/page.js
+++ b/lib/utils/page.js
@@ -134,6 +134,7 @@ function normalizeHtml(src, options) {
                 origin = src;
                 src = '/'+crc.crc32(origin).toString(16)+path.extname(origin);
                 src = links.toAbsolute(src, options.base, options.output);
+                src = crc.crc32(src).toString()+Math.random();
                 isExternal = false;
             }
```

**Comment by SamyPesse** [comment]
BTW I just build a plugin that use latex.codecogs.com to render math equations: https://github.com/GitbookIO/plugin-latex-codecogs
