### ISSUE TITLE
Try to use gitbook to link to github,but it shows "This book has not been published yet"all the time

### ISSUE THREAD

**Issue by xpgeng** [GitbookIO/gitbook#978]
- Aim
     * I try to use an exited github repo to publish a gitbook.
- Try
    * After I create a new book repo, link to Github repo,  add the webhook and so on, I only can edit the files in the gitbook editor
- Result
    * I cannot see my book published like others who have a homepage of the book. Mine is just 404 all the time. 
- So 
    * Do I need to clone the reop to local, and push to gitbook? 
Thank you very much.

**Comment by SamyPesse** [comment]
What is the link to your book?

**Comment by xpgeng** [comment]
I have checked other issues,  and my problem looks like  #508 ,  I think this reason is that in my github, there isn't any webhook. 
This is my gitbook: https://www.gitbook.com/book/xpgeng/omooc2py
But it is 404.
I hope to  link to this: https://github.com/xpgeng/OMOOC2py
 - I have checked the webhook, There isn't ant webhook in the list.
- I click the botton"add a deployment webhook" , it only shows "Book settings has been saved! " 
- I also  return to github to add the webhook by hand, I use the Payload url "<https://git.gitbook.com/xpgeng/omooc2py.git >". But it showed that "Invalid HTTP response:401".

So, what can I do next to publish my book linking to github?

Thank you !

**Comment by SamyPesse** [comment]
I jus puhsed in production a version of Gitbook.com that shows the webhook url at https://www.gitbook.com/book/xpgeng/omooc2py/settings/github

Can you try adding it manually then commit to your GH repository ?

**Comment by xpgeng** [comment]
Thank you very very very much!   My question has been done!
It bothered me  several three days, when I saw the url you left under the page, I was going to cry!  ; P

Ps: When I click the copy button, there is nothing in the clipboard. So I have to view the source page to copy the url. 

In the end, thanks very much!

Best regards,

**Comment by SamyPesse** [comment]
@xpgeng what browser are you using ?

**Comment by xpgeng** [comment]
@SamyPesse    Firefox.

**Comment by xpgeng** [comment]
Thank you Samy,  I have learned double push and can push my files using one command, it‘s very convenient.
