### ISSUE TITLE
.gitignore expression starting with hash symbol

### ISSUE THREAD

**Issue by uliska** [GitbookIO/gitbook#985]
I need to add an ignore rule for filenames starting with a hash symbol, such as

```
#README.md#
```

This is because Emacs produces these autosave files, and `gitbook serve` crashes for that reason.

Of course the hash indicates a comment, so somewhere on Stackoverflow I saw the recommendation to use the character class like `[#]*[#]` to define an ignore rule in .gitignore. But it seems GitBook doesn't recognize this rule - the server crashes nevertheless.

Is this something GitBook doesn't manage (yet), or is there another way to achieve what I need?

**Comment by SamyPesse** [comment]
Did you test `\#abc` ?

**Comment by uliska** [comment]
OK, it turned out that the file actually has a dot in front of the hash. `.\#*` seems to solve the gitignore issue.

With that in place GitBook doesn't crash anymore, however, the affected page is not generated anymore. So the actual issue - making `gitbook serve` work together with Emacs - isn't solved, but that's not what the current issue is about.
