### ISSUE TITLE
whitelist support

### ISSUE THREAD

**Issue by azu** [GitbookIO/gitbook#990]
Please support whitelist for files & folders.

GitBook already support [blacklist](https://github.com/GitbookIO/gitbook#ignoring-files--folders), but not support whitelist.

|  | blacklist | whitelist |
| --- | --- | --- |
| npm | [.npmignore](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) | ["files" field](https://docs.npmjs.com/files/package.json#files) |
| GitBook | .gitignore/.bookignore/.ignore | ???? |

I want to whitelist for GitBook.

Or 

`gitbook build` should not ignore files under the `.gitignore`
### Use case

I'v generated `*.md` files from `original-one-source-file`.
I want to control `original-one-source-file` under the Git, but not want to control `generated/*.md` files.

**.gitignore**:

```
generated/*.md
```

Unfortunately, `gitbook build` ignore `generated/*.md`.

Example: https://github.com/azu/nodefest-technical-writing

**Comment by Simran-B** [comment]
You can actually do a white list like this in a `.bookignore` file:

```
*
!README.md
!SUMMARY.md
!book.json
!allFilesInHere/
```

\* to ignore everything
! to white-list files (or folders)

**Comment by martindale** [comment]
Thanks for that, @Simran-B!  Very helpful!  Where in the documentation should this go?

**Comment by Simran-B** [comment]
It would be great if it could be added here:
https://toolchain.gitbook.com/structure.html#ignore

**Comment by martindale** [comment]
Thanks @Simran-B!  I've submitted a pull request to add it (see above).  Using this in production now, so thank you!
