### ISSUE TITLE
Table of Contents Inconsistant when Reading Online

### ISSUE THREAD

**Issue by HyunsungJo** [GitbookIO/gitbook#991]
In the Gitbook I'm editing (https://steamshon.gitbooks.io/s2graph-book), if I start reading online on a MacBook with a Chrome browser, Table of Contents seems to break.
1. Initial table
   ![screen shot 2015-10-26 at 6 43 02 pm](https://cloud.githubusercontent.com/assets/4621667/10725828/43724832-7c12-11e5-896c-ed275308a629.png)
2. After clicking "1. Getting Started", table is broken.
   ![screen shot 2015-10-26 at 6 43 10 pm](https://cloud.githubusercontent.com/assets/4621667/10725863/968806ba-7c12-11e5-8613-cc64c23403f0.png)
3. Go back to the intro page and the table is still broken.
   ![screen shot 2015-10-26 at 6 43 22 pm](https://cloud.githubusercontent.com/assets/4621667/10726213/ae91aa84-7c14-11e5-83af-cc09ddb09bb9.png)
4. Refresh and the full table is back.
   ![screen shot 2015-10-26 at 6 43 02 pm](https://cloud.githubusercontent.com/assets/4621667/10725828/43724832-7c12-11e5-896c-ed275308a629.png)
- No such problem with Safari. 
- Tested with three different MacBooks and got the same result. (Although the broken table all looked slightly different.)

**Comment by djfwan** [comment]
There are some bugs on css.
As you know, each browser has another browser engine.
As a result, Safari and Chrome look diffrently.

In chrome developer's tool, li eliments are "display:none".

![screen shot 2015-10-30 at 16 29 32](https://cloud.githubusercontent.com/assets/10102134/10840525/76ec0784-7f23-11e5-974b-ca1bc2646ea4.png)
