### ISSUE TITLE
Bold text not rendered in AsciiDoc

### ISSUE THREAD

**Issue by salsa-system** [GitbookIO/gitbook#992]
Since last Gitbook version, text in bold formatted with AsciiDoc is not rendered in web and desktop clients.

**Comment by SamyPesse** [comment]
Are you on Windows ?

**Comment by salsa-system** [comment]
Ubuntu 15.10

**Comment by SamyPesse** [comment]
Ok, Windows and Linux doesn't have `Helvetica Neue`, and the font being used doesn't show correctly the bold text.

So don't worry, the text is still bold, it's just a font issue; we'll fix it in next release.

**Comment by salsa-system** [comment]
Yes I've noticed that the online reading version contains bold text...it's just an client editor issue...thx for you answer...

**Comment by SamyPesse** [comment]
Fixed in styleguide, it'll be in the next release.
