### ISSUE TITLE
Gitbook Desktop Editor 4.1.5 [An email need to be linked to your account]

### ISSUE THREAD

**Issue by ArpiaPsuv** [GitbookIO/gitbook#993]
Hello friends! I have a problem when I try to access my account using gitbook Gitbook Desktop Editor 4.1.5

![captura de pantalla de 2015-10-28 08_12_58](https://cloud.githubusercontent.com/assets/7016544/10788970/0604727c-7d4d-11e5-9108-2d5615d75eea.png)

gitbook-editor-4.1.5-linux-x64.deb 

 I get this error when I try to sign in,  but I have an email verified in this account 
![captura de pantalla de 2015-10-28 08 30 11](https://cloud.githubusercontent.com/assets/7016544/10789231/56196e4c-7d4e-11e5-94e6-38c64fbce8ca.png)

**Comment by davidenq** [comment]
Hi, I have the same problem.

**Comment by SamyPesse** [comment]
Sorry, It was a regression on our side, it should be fixed and working now.
