### ISSUE TITLE
gitbook cannot show contents of double brace in html code block

### ISSUE THREAD

**Issue by huguangju** [GitbookIO/gitbook#996]
```html
  <div ng-controller="Customer as customer">
      {{customer.name}}
  </div>
  ```

`{{customer.name}}` no according to its original appearance, but hidden away.

**Comment by SamyPesse** [comment]
This is processed by the templating engine (http://help.gitbook.com/format/templating.html).

You need to use `{% raw %}....{% endraw %}`, code blocks are automatically escaped in Markdown.

```
{% raw %}
<div ng-controller="Customer as customer">
      {{customer.name}}
</div>
{% endraw %}
```
